### ISSUE TITLE
Telemetry probe to measure the tab switches to loaded & unloaded tabs

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/android-components#10000]
Individual issue to track [new telemetry related to page persistence metrics](https://github.com/mozilla-mobile/android-components/issues/9624).

- number of times the user switches to a tab and
-     the tab is not loaded
-     the tab is loaded

This metrics could help us track how memory/performance affects retaining tabs/getting killed and how often our users get their tabs reloaded. Also it can help us know how many tabs are actually alive in users devices (e.g. when thinking about memory/performance tradeoffs based on number of tabs)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5)

**Comment by jonalmeida** [comment]
Issue 10000! 🎉 

(ignore this comment)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795410

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
