### ISSUE TITLE
Update to application-services 75

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10011]
Breaking changes revolve around introducing per-field encryption to the autofill module. See @mhammond's PRs: https://github.com/mozilla-mobile/android-components/pull/9978 & https://github.com/mozilla-mobile/android-components/pull/9977

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7)

**Comment by grigoryk** [comment]
cc @gabrielluong as this blocks your work.

**Comment by mcarare** [comment]
This seems to be obsolete since we are already at 93.7.0 version for a-s.
