### ISSUE TITLE
GeckoView Web Extension fails to connect to connect to Android application

### ISSUE THREAD

**Issue by aarain** [mozilla-mobile/android-components#10029]
I have an issue which only occurs when installing an APK or AAB from Google Play, both via their release channel and internal app testing. When I install the APK manually on to my device or run in debug mode via Android Studio the extension functions correctly.

Regardless of the app installation method, my extension appears to install correctly (obtaining web extension controller from the default GeckoRuntime, and calling the ensureBuiltIn() method in my application code). My issue begins when the web extension attempts to open a connection to the application via the background.js file:

````
"use strict";

// Establish a connection with app.
const portToApp = browser.runtime.connectNative("native_app");

portToApp.onMessage.addListener(function(response) {
    portFromCS.postMessage(response);
});

// Receive a connection from the content script.
let portFromCS;

function connected(port) {
    portFromCS = port;

    portFromCS.onMessage.addListener(function(jo) {
        portToApp.postMessage(jo);
    });
}

browser.runtime.onConnect.addListener(connected);
````

I used the following resource for developing my extension:
https://firefox-source-docs.mozilla.org/mobile/android/geckoview/consumer/web-extensions.html#connection-based-messaging

When I run my application, I can see the following debug lines in the working version but not in the failing version:
````
D/WebExtension: handleMessage GeckoView:WebExtension:Connect
````
````
D/WebExtension: handleMessage GeckoView:WebExtension:Message
````

Is there any way I can implement communication between the web extension and my application when the app is downloaded from Google Play?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-13)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793235

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
