### ISSUE TITLE
[Telemetry] crash in uploadPingsInBackground

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#1004]
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/1250545/46625654-a2a96000-cae9-11e8-8f5f-2feca4d97b03.png">

https://sentry.prod.mozaws.net/operations/focus-android/issues/4418897/

**Comment by pocmo** [comment]
In this situation we are iterating over the ping builders while the app code is adding a new ping builder. That's weird and I wouldn't expect that to happen (-> telemetry getting setup before the upload service starts).

**Comment by pocmo** [comment]
@boek I think you want to fix the following thing in Focus: Move the call to add the metrics ping builder...
https://github.com/mozilla-mobile/focus-android/blob/8df1d9ccc90cd3a9089d1405d02865aeb7486a0d/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L331-L332
... to the place where we initialize telemetry:
https://github.com/mozilla-mobile/focus-android/blob/8df1d9ccc90cd3a9089d1405d02865aeb7486a0d/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L263-L266

We can fix the concurrent modification problem here but you nevertheless may want to have the ping added as early as possible.

**Comment by boek** [comment]
@pocmo ah great find
