### ISSUE TITLE
Fix deprecated ‘Autocomplete.LoginStorageDelegate’ with Autocomplete.StorageDelegate

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#10093]
> ⚠️ Deprecated ‘Autocomplete.LoginStorageDelegate’ with the intention of removing it in GeckoView v93. Please use Autocomplete.StorageDelegate instead. (bug 1691819).

https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/doc-files/CHANGELOG

_Originally posted by @pocmo in https://github.com/mozilla-mobile/android-components/issues/10081#issuecomment-818785139_

**Comment by csadilek** [comment]
Let's also remove the `Deprecation` in Fenix when doing this: https://github.com/mozilla-mobile/fenix/pull/19078/files#diff-8ecac70de1aee8f4328f42b95277d2465c2061798690319ad9012daba98e48e7R86

**Comment by gabrielluong** [comment]
Related Fenix ticket https://github.com/mozilla-mobile/fenix/issues/19080

**Comment by gabrielluong** [comment]
I find myself fixing this along with the credit card prompt prework. Will take this over
