### ISSUE TITLE
Better key management

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10123]
https://github.com/mozilla-mobile/android-components/pull/10054 introduced first steps towards a more principled approach to key management.

Currently, that's all done within the context of a credit cards storage. It's also quite bare-bones - e.g. there's no telemetry, etc.

We have the same basic need in other places - namely, for managing the key used to encrypt the FxA state, and another key used for protecting the logins db.

This issue is for generalizing what's appropriate out of https://github.com/mozilla-mobile/android-components/pull/10054 so that we can use these building blocks for all our keys.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-88)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796411

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
