### ISSUE TITLE
Telemetry for bad key state in AutofillCrypto

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10122]
When lost/corrupted/etc key state is detected, these events should be recorded in our telemetry for monitoring/analysis.

Two alternatives to this:
- do nothing; but, then we don't know if managed keys are being lost/corrupted
- send artificial exceptions to Sentry; as a crash tracking system, Sentry really isn't well-suited for tracking these kinds of metrics over time though; I don't want to add even more noise to what's already a hard-to-navigate environment.

So we're basically looking at emitting some glean metrics - either directly, or in Fenix via Facts. Seems like doing this directly in the component, and not forcing the consuming application to deal with telemetry is the better approach here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-87)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796332

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
