### ISSUE TITLE
Use registerWithSyncManager for all syncable stores

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10128]
We will need A-S APIs for this, but it'll be nice to stop using the awkward `getHandle` method.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-95)

**Comment by jonalmeida** [comment]
Landed in https://github.com/mozilla-mobile/android-components/pull/11256.
