### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#10137]
Notifying teams:

 - [x] Send an email to internal teams
 - [x] Leave a note on forks that we know of

Changes that need to land:

 - [ ] https://github.com/mozilla-mobile/android-components/pull/10647
 - [ ] https://github.com/mozilla-mobile/relbot/pull/65
 - [ ] https://github.com/mozilla-l10n/android-l10n-tooling/pull/34

Manual steps:

 - [ ] Rename the branch on GitHub, update Branch protection
 - [ ] update the default branch in ci-configuration

Verification:

 - [ ] Make sure Nightly builds get integrated into Fenix
 - [ ] Make sure we pick up string changes
 - [ ] Make sure we pick up new GeckoView builds

**Comment by bhearsum** [comment]
We also needed https://github.com/mozilla-l10n/android-l10n-tooling/pull/35 for l10n to override a default.
