### ISSUE TITLE
[Bug] New tab three-dot menu should be wider when not signed in

### ISSUE THREAD

**Issue by eliserichards** [mozilla-mobile/android-components#10133]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/43795363/114916891-f6980c80-9dea-11eb-950b-26b26088b44b.png">  <img width="323" src="https://user-images.githubusercontent.com/43795363/114916514-7ffb0f00-9dea-11eb-84ac-38e3468091fa.png">

When we're signed in to sync, the menu is wide enough to see the whole "Desktop Site" string. But when we're signed out, "Desktop site" gets cut off. I think the minimum width should allow us to see that whole string (in En-US)

**Comment by Mugurell** [comment]
Moving the ticket from Fenix to AC wasn't the best choice.
We still need a way to track issues and verify them on Fenix, so I've created a new ticket there.

**Comment by Mugurell** [comment]
This was verified on Fenix - https://github.com/mozilla-mobile/fenix/issues/19310#issuecomment-831740190
Moving to `Done`.
