### ISSUE TITLE
list_compatible_dependency_versions failure on GV 90: ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#10158]
When running `list_compatible_dependency_versions.py` with a fenix argument:
```sh
# Called from the fenix repo
../android-components/tools/list_compatible_dependency_versions.py .
```

The ac -> GV part of the script now fails with the following output:

```
Traceback (most recent call last):
  File "/Users/mcomella/dev/fenix/../android-components/tools/list_compatible_dependency_versions.py", line 210, in <module>
    raise e
  File "/Users/mcomella/dev/fenix/../android-components/tools/list_compatible_dependency_versions.py", line 204, in <module>
    main()
  File "/Users/mcomella/dev/fenix/../android-components/tools/list_compatible_dependency_versions.py", line 200, in main
    main_repo_to_hash(fenix_path, is_no_fenix_passed)
  File "/Users/mcomella/dev/fenix/../android-components/tools/list_compatible_dependency_versions.py", line 180, in main_repo_to_hash
    mc_hash, _, _, nightlyv, = ac_checkout_to_mc_hash(PATH_AC_ROOT)
ValueError: not enough values to unpack (expected 4, got 2)
```

Bisection:
- Good: 72d73704127ac174ed356452d80c23c2e3a626c0
- Bad: 17f7aff4ed99c584eb207f4218894c354a372b76

The bad revision is 6 commits later after we merged to GV 90 & updated the script accordingly: I'm guessing the changes to the script didn't update to the new state correctly or some format of the GV POM changed in 90.

**Comment by mcomella** [comment]
It looks like the `ac_checkout_to_mc_hash` function was changed to return two arguments:
```diff
 def ac_checkout_to_mc_hash(ac_root):
-    releasev, betav, nightlyv = ac_checkout_to_gv_versions(ac_root)
+    version = ac_checkout_to_gv_version(ac_root)
 
-    validate_gv_nightly_version(nightlyv)
-    mc_hash = gv_nightly_version_to_mc_hash(nightlyv)
-    return mc_hash, releasev, betav, nightlyv
+    validate_gv_nightly_version(version)
+    mc_hash = gv_nightly_version_to_mc_hash(version)
+    return mc_hash, version
```

But it's call site was not changed to destructure 2 args instead of 4 ([source](https://searchfox.org/mozilla-mobile/rev/7e39907c88a69c653f1435302c3aa0994e4c8d15/android-components/tools/list_compatible_dependency_versions.py#180)).

So this is a regression from https://github.com/mozilla-mobile/android-components/issues/10070

@pocmo Do you know what necessary change is?

**Comment by pocmo** [comment]
Ugh, sorry, I must have skipped running this before landing. I'll take a look.
