### ISSUE TITLE
Enable an detekt rule for wrap blocks in { }

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1015]
e.g

🔴 Bad
```kotlin
        if (!successful)
            println("Hoorah!")
```

🍏  Good
```kotlin
        if (!successful){
            println("Hoorah!")
       }
```

**Comment by vadimsemenov** [comment]
Hey,
Am I right, that you want include [that style rule](https://arturbosch.github.io/detekt/style.html#mandatorybracesifstatements)?

If yes, please assign this issue to me.

**Comment by pocmo** [comment]
@vadimsemenov Yeah, that looks correct.

Unfortunately GitHub doesn't allow me to assign the issue to a contributor. But feel free to start working on it and opening a pull request. Thank you for your help! :)

**Comment by vadimsemenov** [comment]
@pocmo thank you!
I've already done this :)
Please see #1040
