### ISSUE TITLE
Can't use PromptFeature for uploading a file

### ISSUE THREAD

**Issue by Alexspriet** [mozilla-mobile/android-components#10171]
Hi,

Your component PromptFeature doesn't seem to retrieve a file (video, picture from directory or from the phone).
I tried with your Reference Browser, your Sample Browser or even Firefox Focus.
It only work with Fenix, but I can't figure out what is the difference.

Cheers!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-131)

**Comment by Alexspriet** [comment]
I figure it out:

You have to change this:
`PromptFeature(fragment= this, ...`

into 

`PromptFeature(activity = requireActivity(), ... )`

**Comment by Alexspriet** [comment]
Hi guys,

IDo you have any clue why it doesn't work with a fragment context?

Cheers

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795409

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
