### ISSUE TITLE
Overwriting Firefox Fenix menu Add-ons Icon from Android Components

### ISSUE THREAD

**Issue by imnotabr** [mozilla-mobile/android-components#10180]
I want to overwrite the icon for Add-ons at the top of the menu in Fenix with a different icon.

Is the file android-components/components/ui/icons/src/main/res/drawable/mozac_ic_extensions.xml?

https://github.com/mozilla-mobile/android-components/blob/master/components/ui/icons/src/main/res/drawable/mozac_ic_extensions.xml

Do I need to create my custom file in the assets folder of my project or use a local copy of android-components to overwrite this icon?

@clauub, same thing right?

![Screenshot_20210429-132805 2107](https://user-images.githubusercontent.com/62814903/116615042-97102580-a8ef-11eb-8e63-84c9f498afa8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-135)

**Comment by clauub** [comment]
@imnotabr you should try to add your own file in the assets folder. This should work fine!

**Comment by shofiq301** [comment]
I was able to change default extension icon by replacing my own icon the the same name "mozac_ic_extensions.xml"
