### ISSUE TITLE
Expose user agent in browser-engine-gecko-* components

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1018]
There will be an API to get the user agent soon:
https://bugzilla.mozilla.org/show_bug.cgi?id=1454444

We won't be able to set it - but maybe we want to make it readable from the engine's settings?

**Comment by pocmo** [comment]
The API is now available: https://bugzilla.mozilla.org/show_bug.cgi?id=1454444

**Comment by csadilek** [comment]
We landed support for setting/getting the user agent override, but we still need support reading the default. This is blocked on: https://bugzilla.mozilla.org/show_bug.cgi?id=1512997

Let's track this here as well.
