### ISSUE TITLE
A-C: Expose Flank UI test artifacts

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/android-components#10198]
Only _now_ just noticed no Flank artifacts are uploaded. E.g, [task](https://treeherder.mozilla.org/jobs?repo=android-components&selectedTaskRun=KNoaioTQTXuFidiKkYdahA.0)  – vs [Fenix we get a JUnitReport and Matrix related artifacts](https://treeherder.mozilla.org/jobs?repo=fenix&selectedTaskRun=cw6-yGQcShyuoMd5AyyV1A.0).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-148)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795408

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
