### ISSUE TITLE
Add tests for onLoginFetch and onLoginSave in GeckoLoginStorageDelegateTest

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#10199]
We do not currently test the entirety of `GeckoLoginStorageDelegate`. We would like to add a test to verify the calls for `onLoginFetch` and `onLoginSave`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-153)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794221

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
