### ISSUE TITLE
Update README to include the Mozilla Maven repository

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1021]
In all component README files, we mention that you can download it from JCenter, but now we also have Mozilla Maven!
```
Use gradle to download the library from JCenter:
```

Maybe point to one location root README to show how to add the Maven repository to your project?

**Comment by dector** [comment]
I suppose this issue [can be closed](https://github.com/mozilla-mobile/android-components/blob/master/README.md#maven-repository)?

**Comment by pocmo** [comment]
Yes, thanks! :)

**Comment by jonalmeida** [comment]
Looks like browser-state is still using the old doc line if you're interested in fixing that @dector  🙂 : https://searchfox.org/mozilla-mobile/search?q=Use+gradle+to+download+the+library+from+JCenter&case=false&regexp=false&path=

**Comment by dector** [comment]
Okay, I'll check it.

**Comment by dector** [comment]
Done. #3193
