### ISSUE TITLE
Partially update the background color (tint) of the site security indicator icon

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10225]
Right now we are changing [the color of the whole asset](https://github.com/mozilla-mobile/android-components/blob/1cf5f96366ebece60e1c5262dec6f9554f37a696/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt#L506), but with the new icon update https://github.com/mozilla-mobile/android-components/pull/10196/ the unsecured site icon will have red line, this line should be red and must be keept as it's, independently of the tint color.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-180)

**Comment by Amejia481** [comment]
Old icon:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/773158/117175604-06c55b00-ad9d-11eb-8e4f-af69aee539dd.png">

New Icon:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/773158/117175509-f0b79a80-ad9c-11eb-8b88-188b663db597.png">

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795426

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
