### ISSUE TITLE
Engine: Expose API for receiving history/visits

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1025]
We will need an API for exposing history/visits. That's what we store as browsing history. This data is different from just URLs we load. For example it doesn't include error pages or redirects.

WebView API:
https://developer.android.com/reference/android/webkit/WebViewClient.html#doUpdateVisitedHistory(android.webkit.WebView,%20java.lang.String,%20boolean)

The GeckoView API is not implemented yet:
https://bugzilla.mozilla.org/show_bug.cgi?id=1494713

**Comment by grigoryk** [comment]
I'm doing this in https://github.com/mozilla-mobile/android-components/issues/905

**Comment by pocmo** [comment]
@grigoryk Awesome. Is it okay to break that down and land this separately? It seems to be a completely independent change.

**Comment by grigoryk** [comment]
Yeah, absolutely. Submitted a PR for a first stab at this.
