### ISSUE TITLE
Update the add-on rating icon

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10255]
As part of the proton icon update we can to replace the rating icon for add-on for this one https://www.figma.com/file/UJ5BsuvpQOADF3EPyfvtyv/Icons-(WIP)?node-id=3041%3A7

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-217)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796306

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
