### ISSUE TITLE
Add functionality to be able to query the status of the migration on the GeckoSitePermissionsStorage

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10296]
For more info see https://github.com/mozilla-mobile/android-components/pull/10176#discussion_r635306563

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-248)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796463

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
