### ISSUE TITLE
Expand the list of credit cards in the select credit card prompt by defaullt

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#10295]
This came from @violasong. 

> I noticed this collapsed CC bar with numpad view which I didn't expect. I think I expect to see the expanded list of CCs here

![Screenshot_20210518-130804_Firefox Nightly](https://user-images.githubusercontent.com/1190888/118844105-b0761300-b898-11eb-8eb1-1cf3dca092cb.jpg)

Relevant code is here.
https://searchfox.org/mozilla-mobile/source/android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardSelectBar.kt#73

Please also update the test

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-246)

**Comment by codrut-topliceanu** [comment]
@gabrielluong @violasong 
Are we sure this is this the desired behavior: 


https://user-images.githubusercontent.com/60002907/119512457-fdb42200-bd7b-11eb-956d-5729ede642fc.mp4

**Comment by violasong** [comment]
Ah, I realized the logins view always shows up as collapsed when on a new
logins screen. Maybe ideally, both of these should show the first 1-2
entries by default. We wouldn't want it to cover up too much of the screen,
especially not the input field.

But yes, probably better to resolve this later when @topotropic or others
can take a look at this.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796335

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
