### ISSUE TITLE
Intermittent [taskcluster:error] Task timeout after 1200 seconds. Force killing container.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#10320]
4 task failures for latest push, 3 have the execution halting during lintRelease

### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=340579822&repo=android-components
### Stacktrace:
```
[task 2021-05-23T19:10:53.656Z] > Task :feature-tabs:mergeReleaseJavaResource
[task 2021-05-23T19:10:53.756Z] > Task :feature-tabs:compileReleaseUnitTestKotlin
[task 2021-05-23T19:10:53.856Z] > Task :feature-tabs:lintRelease

[taskcluster:error] Task timeout after 1200 seconds. Force killing container.
[taskcluster 2021-05-23 19:28:19.309Z] === Task Finished ===
[taskcluster 2021-05-23 19:28:19.309Z] Unsuccessful task run with exit code: -1 completed in 1220.447 seconds
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/090542c8ea9208b9a7db2446cc3427f779354239

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-263)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794872

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
