### ISSUE TITLE
Expose facts tracking protection exception migration

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10339]
It will be useful to expose facts about the migration to report telemetry event from the consumer apps to understand if the migration was completed successfully.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-286)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795425

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
