### ISSUE TITLE
Create query to report if the site permissions migration is over 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10340]
As part of the geckoView site permissions migration we want to understand, how many users have been migrated to the geckoview storage for this reason we need a spesific query for it

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-288)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795424

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
