### ISSUE TITLE
Samples-browser uses deprecated Fragment.requestPermissions API

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10358]
In `BaseBrowserFragment` there are multiple calls to `Fragment.requestPermissions()`. This API is deprecated in `androidx.fragment:fragment` 1.3+.

The docs say:

> use registerForActivityResult(ActivityResultContract, ActivityResultCallback) passing in a androidx.activity.result.contract.ActivityResultContracts.RequestMultiplePermissions object for the ActivityResultContract and handling the result in the callback.

Maybe we could call it on the attached activity as a workaround for now?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-303)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795423

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
