### ISSUE TITLE
PromptContainer: Migrate away from Fragment.startActivityForResult()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10357]
`PromptContainer` uses `Fragment.startActivityForResult()`. This API is deprecated in `androidx.fragment:fragment` 1.3+.

https://github.com/mozilla-mobile/android-components/blob/429f8390559bfdac7a01f10c81b4231cfe71fa68/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptContainer.kt#L51

The docs say:

> use registerForActivityResult(ActivityResultContract, ActivityResultCallback) passing in a androidx.activity.result.contract.ActivityResultContracts.StartActivityForResult object for the ActivityResultContract.

But maybe an easier solution would be to call `startActivityForResult()` on the attached `Activity` for now?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-302)

**Comment by pocmo** [comment]
@Amejia481 For now I'll suppress the deprecation in the appcompat upgrade PR. But maybe we can squeeze this into one of the upcoming sprints?

**Comment by Amejia481** [comment]
Sounds good, let's add the deprecation for now and we can address it later as you mentioned.

**Comment by Amejia481** [comment]
Using the attached Activity could cause that `requestCode` varies when we get a response on `onActivityResult` listener,  as both `fragment.startActivityForResult` and  `fragment.onActivityResult` should match the same object activity/fragment we have seen similar issues before see https://github.com/mozilla-mobile/fenix/pull/17874.

**Comment by jonalmeida** [comment]
If we only support `activity` that should make it easier to avoid the situations in mozilla-mobile/fenix#17874 and the credit card prompt as well.

Today, we propagate the results/errors from the activity to the fragment so that should keep us covered, I think.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796377

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
