### ISSUE TITLE
Try other icons if downloaded icon is too small.

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#10377]
Currently, If we select the best icon candidate, download it and then determine that it is too small then we continue with no icon instead of trying to download the next candidate.  We should try other icons if there is more than one candidate.

Also see: mozilla-mobile/fenix#2964

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-318)

**Comment by j9t** [comment]
As raised in #3814, what dimensions would be “too small”?

**Comment by kbrosnan** [comment]
If the favicon contains a 16x16 px icon even if there are other sizes present then the whole favicon is not used. I am going to check in the new year if there is bandwidth to look into using the best quality icon size instead of the smallest.

**Comment by Mugurell** [comment]
Based on Sebastian's comment from here - https://github.com/mozilla-mobile/android-components/pull/11183#discussion_r742935118 to fix this in a sure-fire way for the future we might have to refactor the entire `BrowserIcons` functionality.

**Comment by Mugurell** [comment]
The general direction from Sebastian:
> - Getting rid of the abstractions around loaders and storage. Instead have explicit references to memory/disk/network loaders and storages. The abstraction is unnecessary (it’s not like we have fancy configurations, and its a singleton anyways) and makes things more complicated.
> - Once the abstraction is gone we can write explicit logic. For example we can ask the memory storage synchronously and immediately return an image if it’s in memory, no need to wait for an async coroutine.
> - The same is true for other logic. Like in the case you had, we can easily omit asking the network loader, because we know which one it is.
> - And same in the case here. We can easily rewrite the logic to try downloading the next icon if this is not all abstract.

The new providers could also be combined to emit in a flow
> I also thought about getting rid of the deferred icon because that makes it awkward. thought about just a callback, that can be invoked immediately for memory icons. but a Flow may be more idiomatic. You could even have both with an extension function that turns it into a flow

**Comment by rocketsroger** [comment]
Looks like apple.com have the opposite issue.  The icon we found was bigger than 512px.
