### ISSUE TITLE
Consider disabling codecov

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10389]
Unfortunately the numbers are pretty random, maybe caused by us uploading partial (and multiple) reports. Originally having the ability to upload multiple reports that get merged was the major reason for using codecov. But it's not realiable.

Let's consider disabling it. The individual coverage reports get generated on taskcluster and are exposed in the taskcluster check on GitHub (just not as a comment on the PR).

**Comment by jonalmeida** [comment]
RIP codecov, closing.
