### ISSUE TITLE
Android Autofill: Add preference for toggling autofill

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10385]
Similar to the one in Reference Browser, but also handling the case of disabling autofill.

https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/autofill/AutofillPreference.kt

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-326)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796338

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
