### ISSUE TITLE
Support for getting recently bookmarked items

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10419]
We'll need this for some upcoming feature work.

Basically, three ways of doing this:
1) expose dateAdded/lastModified timestamps in our `BookmarkNode` type (these are already available to us over FFI); to get recent, fetch the entire tree and perform an in-memory filter.
2) add a places API specifically for this purpose (which will perform this work entirely in SQL).
3) keep track of recently bookmarked items in some auxiliary storage

(1) is likely the slowest, but quick to do. (2) will be certainly faster, but the most work. However, it's not _that_ much work, we should be able to easily add this additional API to A-S.

(3) seems wrong to me entirely, given that (1) and (2) exist.

**Comment by eliserichards** [comment]
Needed for https://jira.mozilla.com/browse/FNX-22339

**Comment by eliserichards** [comment]
Looks like the `Places` API already supports this functionality: https://github.com/mozilla/application-services/blob/f6ed9047aa79b4ce8745022b3bf0ff414d27c13e/components/places/android/src/main/java/mozilla/appservices/places/Bookmarks.kt#L255

**Comment by eliserichards** [comment]
AS pull request: https://github.com/mozilla/application-services/pull/4181

**Comment by grigoryk** [comment]
Left a comment on the A-S PR (we _probably_ don't want `recently modified` stuff).

But, let's expose `getRecentBookmarks` API in A-C for now!
