### ISSUE TITLE
Rotate fullscreen media using sensor orientation even when rotation lock is active

### ISSUE THREAD

**Issue by augustelalande** [mozilla-mobile/android-components#10433]
I suppose this may have been a philosophical choice, but I thought I would at least bring up the issue.

Personally, I always keep rotation lock on because I want to keep reading articles in portrait mode even when laying sideways. However, when watching a video, I would like the video to be in landscape mode (this is currently supported) and ideally be rotated according to the device orientation (this is not the current behavior). This contrasts to the behavior on other browsers such as the chrome mobile app.

Unless I am mistaken, I believe this behavior is defined in https://github.com/mozilla-mobile/android-components/blob/master/components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt where orientation is set to `ActivityInfo.SCREEN_ORIENTATION_USER_PORTRAIT` and `ActivityInfo.SCREEN_ORIENTATION_USER_LANDSCAPE` instead of `ActivityInfo.SCREEN_ORIENTATION_SENSOR_PORTRAIT` and `ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE`.

Was this done intentionally?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-361)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796369

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
