### ISSUE TITLE
Expose a way in the crash reporter to track nimbus slugs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#10442]
When we want to reproduce crashes, users may be in various nimbus experiments that we need to be aware of.

Adding an ability to do this at runtime would be needed so that nimbus can provide that data when it's done warming up.

One idea would be to expose a unified API that is similar to [SentyService's `addTag`](https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt#L75) that lets us know which experiment had users crashing in.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-368)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792900

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
