### ISSUE TITLE
CrashReporterActivity: Show progress

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1044]
Currently we try to send the crash report and then finish the activity. We should show some kind of progress and disable the buttons.

**Comment by st3fan** [comment]
Are you thinking this should go in the notification tray or in the application? I noticed that many apps use the notification tray to report progress on longer running background tasks.

**Comment by pocmo** [comment]
In this case I was thinking about the crash dialog itself. Afaik in Fennec we keep it open until the report is sent.

**Comment by Shubhamurkade** [comment]
Hi @pocmo! I would like to take up this issue. Do you think we should add a Progress Bar here?
