### ISSUE TITLE
Clearing search terms on "back" is wrong when going back to the original search page

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10487]
We saw this in https://github.com/mozilla-mobile/fenix/pull/20075.

STR:
- search for X
- open link from search results
- press "back"
- at this point, tab won't have `searchTerms` in its state

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-393)

**Comment by grigoryk** [comment]
cc @csadilek

**Comment by grigoryk** [comment]
This was introduced while fixing the mirror version of this bug in https://github.com/mozilla-mobile/fenix/issues/7632

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793185

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
