### ISSUE TITLE
Intermittent [taskcluster:error] Error uploading "public/reports/jacoco/jacocoReleaseTestReport/html/mozilla.components.feature.webauthn/WebAuthnFeature.html" artifact. Artifact already exists with different properties, and none of the allowed exceptions apply: { 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#10514]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=343613555&repo=android-components
### Stacktrace:
```
[task 2021-06-23T13:21:32.140Z] BUILD SUCCESSFUL in 2m 3s
[task 2021-06-23T13:21:32.140Z] 426 actionable tasks: 283 executed, 143 from cache
[fetches 2021-06-23T13:21:32.549Z] removing /builds/worker/fetches
[fetches 2021-06-23T13:21:33.013Z] finished
[taskcluster 2021-06-23 13:21:33.351Z] === Task Finished ===
[taskcluster:error] Error uploading "public/reports/jacoco/jacocoReleaseTestReport/html/mozilla.components.feature.webauthn/WebAuthnFeature.html" artifact. Artifact already exists with different properties, and none of the allowed exceptions apply: {
  "storageType": "s3",
  "contentType": "text/html",
  "expires": "2022-06-23T13:15:42.621Z"
}
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/f8a5c6a05acc79f6de8dfde5ea9623433a671457

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9727)

**Comment by jonalmeida** [comment]
I don't think there is anything we can do about this in the codebase; seems like an intermitttent TC issue.

**Comment by Archaeopteryx** [comment]
Any idea why this got frequent? A change in the worker setup or was there any relevant change on the mobile side?

**Comment by jonalmeida** [comment]
Maybe @bhearsum  or @escapewindow would know about worker setup changes.

"Artifact already exists with different properties.." sounds like we aren't using a clean worker?

**Comment by bhearsum** [comment]
> Maybe @bhearsum or @escapewindow would know about worker setup changes.
> 
> "Artifact already exists with different properties.." sounds like we aren't using a clean worker?

These tasks run inside fresh docker containers each time, so I doubt there's any carryover. I'm not entirely certain what this means, to be honest. @petemoore or @imbstack, do you have any insight? I'm wondering if there's something in one of the more recent Taskcluster versions we upgraded to that has increased the frequency of this?

**Comment by escapewindow** [comment]
Is there a softlink pointing to another copy of the same file?

**Comment by Archaeopteryx** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1711612

**Comment by csadilek** [comment]
I am closing this, since we disabled jacoco report uploads.
