### ISSUE TITLE
Abstract ensureChannelExists() calls into the support library

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#10520]
Currently there are a lot of functions named `ensureChannelExists` that are very similar.  Refactor these functions into a support library / extension function.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16636)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795421

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
