### ISSUE TITLE
Update Robolectric and Mockito

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10550]
With Java 11 there are some tests failing because Mockito is unable to mock some Android system classes. This currently affects tests in `feature-autofill`, `feature-app-links`, `browser-engine-gecko` and `tooling-lint`.

At least some of them seem to get fixed when we update Robolectric and Mockito to the latest version. However a bunch of things changed with the latest Robolectric version and we may need to adapt some tests. Primarily Robolectric no longer allows instantiating activities that are not listed in the manifest. And our components have a bunch of abstract activity classes that we have been testing with Robolectric. We need to do something else for that. So that's why I've split this upgrade into a separate issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-16963)

**Comment by csadilek** [comment]
Outdated and upgrades since landed. Closing.
