### ISSUE TITLE
Update WebExtensionBrowserMenuBuilder build method

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/android-components#10559]
To implement the new Focus [browser menu](https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/MVP---iOS%2FAndroid---Product-UI?node-id=902%3A3557) with report site issue extension we need to use a WebExtensionBrowserMenuBuilder.
By default WebExtensionBrowserMenuBuilder add "Add-ons" menu item but we don't want that , so WebExtensionBrowserMenuBuilder needs to be updated to be able to build a menu without it

**Comment by mcarare** [comment]
@ionutbedregeanu AFAIK the "Add-ons" menu item shows up only when you have add-ons installed. The implementation in Fenix uses a placeholder for the "report site issue" extension that moves it from the add-ons menu, so that menu would not show up.

**Comment by ionutbedregeanu** [comment]
What I want is to show "report site issue" but hide "add-ons" menu item. From what I saw "add-ons" is added even if the list of extensions is empty

**Comment by lobontiumira** [comment]
Verified on the 8.13.1 (build 1192.0a1-20210721092353), and on 8.18.0-rc.1 with Google Pixel (Android 10), that the "Report site issue" option is displayed in the menu, but the "Add-ons" option isn't.
