### ISSUE TITLE
SelectOrAddUseCase should allow filtering existing tabs to match

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#10560]
[SelectOrAddUseCase](https://github.com/mozilla-mobile/android-components/blob/e535713ea8eca6528c4c0d44fea9c829ff7a3989/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt#L369-L399) will currently try to match any tab with the given url not differentiating between private / normal tabs.

This leads to the following edgecase scenario in Fenix:
- we have a normal tab opened with "url"
- user goes to app settings and enable "Open links in private tab"
- then taps to open an external link with "url"
- although "Open links in private tab" is checked the app opens showing a normal tab.

The reverse is also true. If a private tab for that url exists, even with "Open links in private tab" disabled tapping to open the same link would open the private tab.

After confirming with Sebastian it seems that `SelectOrAddUseCase` needs to allow defining whether we want to select only normal tabs/private tabs or not care and select any.

**Comment by csadilek** [comment]
Closed by https://github.com/mozilla-mobile/android-components/pull/10593.
