### ISSUE TITLE
Localization comments for strings

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/android-components#1057]
We've heard from the Firefox Reality folks that they'll be using strings from Error Pages: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/errorpages/src/main/res/values/strings.xml

In order to meet their timeline for launch in a subset of languages, we'll have to kick-off localization this week. In order for us to do this, localization comments are needed for each string in order to give context to translators (and preferably not using too much technical jargon so they can understand how to translate).

Here are guidelines for writing localization notes: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Add_localization_notes

I can review that once it's done. Please reach out should you have any questions about this.

In the meantime, I'll be going through each string and checking for any specific issues that may need to be fixed.
(also, CC @Pike)

**Comment by cpeterso** [comment]
We might be able copy many of existing localized strings from Fennec in the Errorpages component. Here are Fennec's string IDs:

https://searchfox.org/mozilla-central/source/mobile/locales/en-US/overrides/appstrings.properties

**Comment by jonalmeida** [comment]
> We might be able copy some of existing localized strings from Fennec to the Errorpages component. Here are Fennec's string IDs:
> 
> https://searchfox.org/mozilla-central/source/mobile/locales/en-US/overrides/appstrings.properties

I took a look at the strings from Fennec and from our ~70 that we have, I only found four matches that share unfortunately:
```
unsafeContentType
malwareBlocked
harmfulBlocked
deceptiveBlocked
```
