### ISSUE TITLE
Lint Log check leaks into embedding applications.

### ISSUE THREAD

**Issue by bluemarvin** [mozilla-mobile/android-components#1058]
Firefox Reality is currently using `implementation "org.mozilla.components:service-telemetry:0.26.0"`. This is causing all usages of android.util.Log to be marked as a warning:

<img width="563" alt="screen shot 2018-10-10 at 2 58 53 pm" src="https://user-images.githubusercontent.com/3066/46979667-0520d400-d087-11e8-8c92-788b044a5825.png">

This is caused by the custom linter rule: 
https://github.com/mozilla-mobile/android-components/blob/761f43462120913f2d9e0e00c8d73e37dd9a214d/components/tooling/lint/src/main/java/mozilla/components/tooling/lint/LintLogChecks.kt#L37

**Comment by csadilek** [comment]
We could limit the scope of these checks to components, so that component devs get the warning if they use the wrong logger by mistake, but app devs aren't affected e.g. by addding a check like
`method.containingClass?.qualifiedName?.startsWith("mozilla.components")`

Wdyt @pocmo ?
