### ISSUE TITLE
Always display URLs left to right

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#10598]
Tracking https://mozilla-hub.atlassian.net/browse/FNXV2-17223

**Comment by Mugurell** [comment]
This should be ready to test in the next Nightly.
Haven't opened a Fenix issue. More details are in Jira and Bugzilla. Ping me for access.

**Comment by SoftVision-LorandJanos** [comment]
Verified as fixed on the latest Nightly build (92.0a1 - 2021-07-22T05:11:19.498)
The text layout is as described in [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1704422) ticket.
Devices used:
- Google Pixel 4 (Android 11).
- Samsung Galaxy Tab 3 (Android 9).
- LG Nexus 5 (Android 6.0.1).
