### ISSUE TITLE
InterceptResponse.Deny in SystemEngineView has no effect

### ISSUE THREAD

**Issue by marcin-kozinski** [mozilla-mobile/android-components#10592]
Hey,

I think I found a bug in `SystemEngineView` implementation. I experimented with adding my own request blocking logic to an app based on `SystemEngineView`. I tried doing that by returning `RequestInterceptor.InterceptionResponse.Deny` from `RequestInterceptor.onLoadRequest()`, but it doesn't seem to have any effect.

Should this line:
https://github.com/mozilla-mobile/android-components/blob/cd897a8e533b21716ac734be36e69593c0a3670e/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt#L275

return `WebResourceResponse(null, null, null)`? It's what some surrounding code does to block requests.

Edit: I just tested a small fork with this one line changed and I'm able to use the above approach to selectively block web view requests. I believe this confirms this is in fact a bug in `SystemEngineView`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17241)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796471

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
