### ISSUE TITLE
Remove deprecated `createTestCoroutineDispatcher` (v94.0.0)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#10606]
I deprecated it in https://github.com/mozilla-mobile/android-components/issues/10604 and its PR https://github.com/mozilla-mobile/android-components/pull/10605. At the time the PR was written, it was deprecated on v92.0.0 so it should be removed in v94.0.0 or later.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17252)

**Comment by jonalmeida** [comment]
Probably good to add a 'help wanted'/'good first bug' once the parent issue lands and it's baked for sufficient amount of time.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795454

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
