### ISSUE TITLE
Perma-failing `build-docker-image-ui-tests` on latest master

### ISSUE THREAD

**Issue by ahal** [mozilla-mobile/android-components#10600]
https://firefox-ci-tc.services.mozilla.com/tasks/G_z5mJTZRemv9GgAvqdiiA

I hit this perma failure in PR #10574 . I couldn't figure out why my changes would cause it to fail, so tested it out on master and hit the same failure. This went unnoticed because the task rarely ever runs (and only got triggered by my PR because it is modifying some taskgraph stuff).

This will need to be fixed (hopefully sooner rather than later) as it will cause a CI outage whenever the current `build-docker-image-ui-tests` task expires.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17248)

**Comment by ahal** [comment]
Here's the current task:
https://firefox-ci-tc.services.mozilla.com/tasks/agXZblS1SlSvfzoVdZJ5fQ

It expires in 11 months, so not a fire drill but still easy to forget about.

**Comment by AaronMT** [comment]
@kbrosnan  brought this to my attention 

```Log
INFO[0060] RUN URL_FLANK_BIN="$($CURL --silent 'https://api.github.com/repos/Flank/flank/releases/latest' | jq -r '.assets[].browser_download_url')"     && $CURL --output "${TEST_TOOLS}/flank.jar" "${URL_FLANK_BIN}"     && chmod +x "${TEST_TOOLS}/flank.jar" 
INFO[0060] cmd: /bin/sh                                 
INFO[0060] args: [-c URL_FLANK_BIN="$($CURL --silent 'https://api.github.com/repos/Flank/flank/releases/latest' | jq -r '.assets[].browser_download_url')"     && $CURL --output "${TEST_TOOLS}/flank.jar" "${URL_FLANK_BIN}"     && chmod +x "${TEST_TOOLS}/flank.jar"] 
INFO[0060] util.Lookup returned: &{Uid:1000 Gid:1000 Username:worker Name: HomeDir:/builds/worker} 
INFO[0060] performing slow lookup of group ids for worker 
INFO[0060] Running: [/bin/sh -c URL_FLANK_BIN="$($CURL --silent 'https://api.github.com/repos/Flank/flank/releases/latest' | jq -r '.assets[].browser_download_url')"     && $CURL --output "${TEST_TOOLS}/flank.jar" "${URL_FLANK_BIN}"     && chmod +x "${TEST_TOOLS}/flank.jar"] 
curl: (3) Illegal characters found in URL
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 3
Error: Could not build image.
[taskcluster 2021-07-14 17:18:20.189Z] === Task Finished ===
[taskcluster 2021-07-14 17:18:20.269Z] Artifact "public/image.tar.zst" not found at "/workspace/image.tar.zst"
[taskcluster 2021-07-14 17:18:20.340Z] Unsuccessful task run with exit code: 1 completed in 70.001 seconds
```

I think you just need to adjust how Flank is downloaded as it's returning multiple releases now (we don't care about `flank.sha256`). 

```Bash
RUN URL_FLANK_BIN="$($CURL --silent 'https://api.github.com/repos/Flank/flank/releases/latest' | jq -r '.assets[].browser_download_url')" \
```

```Bash
echo $URL_FLANK_BIN
https://github.com/Flank/flank/releases/download/v21.07.1/flank.jar https://github.com/Flank/flank/releases/download/v21.07.1/flank.sha256
```

I guess you can just target `.assets[0]` but I have no idea if thats' going to be consistent.

**Comment by pocmo** [comment]
Patch for this is in #10451.

We should have hold off landing #10574. Now we do not run any UI tests on `master` anymore..

**Comment by ahal** [comment]
Sorry I didn't realize this was going to start running on every push after my PR. We can back it out if it helps.

**Comment by ahal** [comment]
(I also didn't realize that adding the `needs-landing` label could cause mergify to merge, I thought it would only do that if the PR was green.. so I didn't even really intend to land it yet, my mistake!)

**Comment by csadilek** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/10451.
