### ISSUE TITLE
Fix GeckoViewFetchUnitTestCases unit tests

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10608]
With the switch to Java 11 (https://github.com/mozilla-mobile/android-components/pull/10451) I had to disable some tests in `GeckoViewFetchUnitTestCases`. Mockito was complaining about not being able to mock `MockWebServer`.

- I think this can be fixed after the other version bumps have been fixed (There's a problem with Robolectric and Mockito and different class loaders which seems to work with the latest versions.)
- Another options could be rewriting the tests to not require mocking the mock webserver (isn't that weird?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17258)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795419

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
