### ISSUE TITLE
Add recommended push hook to repository

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1062]
I like how other teams have this in the repository:
https://github.com/mozilla-mobile/firefox-tv/blob/master/quality/pre-push-recommended.sh

Let's do that too and add something to our docs about how to use it.

**Comment by Amejia481** [comment]
Apart from `ktlint` and `detektCheck` tasks. Is there another task that we should run too ?

**Comment by pocmo** [comment]
I also run `assemble` in my hook. Most of the time that's fast enough because most components are already built. However that can take a bit if you haven't done or if your cache is not up to date.

**Comment by mcomella** [comment]
@pocmo Where should this hook be located? Where is an appropriate place to document it? There are no set-up steps in the main repository.
