### ISSUE TITLE
Upstream more icons from Fenix to AC

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#10621]
There are more icons shared between Fenix and Focus. We should upstream them from Fenix so we can make use of them in the other.

This Focus PR is currently copying over the files: https://github.com/mozilla-mobile/focus-android/pull/4980/files#

- ic_home
- ic_desktop
- ic_add_to_home_screen
- ic_help
- ic_share
- ic_settings
- ic_search
- ic_desktop
- ic_open_in_*

**Comment by ionutbedregeanu** [comment]
Those changes will be verified on [5152](https://github.com/mozilla-mobile/focus-android/issues/5152)

**Comment by lobontiumira** [comment]
Verified on the latest debug build from main from 8/25, with Lenovo Tab M10 (Android 10), on both page's three-dot menu, and custom tab's three-dot menu.

![AC icons](https://user-images.githubusercontent.com/40694158/130786613-321a0337-f7e2-4702-afaa-ae3b8e1eeddc.png)
