### ISSUE TITLE
LastMediaAccessMiddleware update

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#10632]
An issue about the media tab was observed on Fenix (https://github.com/mozilla-mobile/fenix/issues/20402)
```
ClassCastException: mozilla.components.browser.state.state.CustomTabSessionState cannot be cast to mozilla.components.browser.state.state.TabSessionState
```

This is happening [here](https://github.com/mozilla-mobile/android-components/blob/be131aa5bb792cc69a1dc7f26bd87a21e86e40d4/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/LastAccessReducer.kt#L27) following media starting to play in a custom tab when trying to force a cast to TabSessionState and then save `lastMediaAccess`.
It's not happening [here](https://github.com/mozilla-mobile/android-components/blob/be131aa5bb792cc69a1dc7f26bd87a21e86e40d4/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/LastAccessReducer.kt#L21) when saving `lastAccess` because of [this previous if check](https://github.com/mozilla-mobile/android-components/blob/4ab72a8644a62721276fd2d5b4e73d996194cf9a/components/feature/session/src/main/java/mozilla/components/feature/session/middleware/LastAccessMiddleware.kt#L37) based on which `lastAccess` will be updated only for the currently selected tab, hence we'll never try for a custom tab.

**Comment by Mugurell** [comment]
Testing this scenario I also see a maybe bigger issue: If playback starts in a custom tab we "forget" the last media playing tab because [we recieve DeactivatedMediaSessionAction here](https://github.com/mozilla-mobile/android-components/blob/be131aa5bb792cc69a1dc7f26bd87a21e86e40d4/components/feature/media/src/main/java/mozilla/components/feature/media/middleware/LastMediaAccessMiddleware.kt#L33-L35).

I think the solution, as suggested in [the original PR](https://github.com/mozilla-mobile/android-components/pull/10518) is to also consider navigations and use `UpdateUrlAction` as a second condition to reset the media playing status.

**Comment by csadilek** [comment]
@Mugurell We don't need to handle custom tabs for these features as "jump back" in and "past explorations" target open tabs in Fenix or history metadata (which we also don't record for custom tabs). We shouldn't crash, of course, but don't need to make the feature work for custom tabs. So we can just land a fix and reactivate the feature in Fenix.

**Comment by Mugurell** [comment]
There are still a few reports https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9238032/?referrer=github_plugin but with more days in a row showing 0 events I think this can be closed.
