### ISSUE TITLE
Video Freezing and audio continues in geckoview Android TV

### ISSUE THREAD

**Issue by vengateshvengi03** [mozilla-mobile/android-components#10639]
In geckoview ,i am just playing some ott content in ABR setup.After it got high resolution video is freezing and audio continues playing.But in normal browser its playing good.How to fix it?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17301)

**Comment by csadilek** [comment]
We're going to need more information (device, OS and GV build number and version, plus ideally steps to reproduce. Please provide those and file again here: https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView

Thanks!
