### ISSUE TITLE
Review 'UnusedResources' lint errors

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10643]
The latest version of Android lint finds a ton of unused resources across our components. It's way too much for me to fix in the upgrade PR. I will have to disable this check. This issue is about going through them and removing the unused resources if appropriate.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17306)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795427

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
