### ISSUE TITLE
Unused resources in feature-addons

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10642]
The new version of lint complains about a ton of unused strings in `feature-addons`. It's too much for me to review and fix in the upgrade PR. So I'm failing this separate issue.

For now I will have to disable this check in the `feature-addons` component.

Some of them (not all):
<img width="916" alt="Screenshot 2021-07-20 at 11 57 09" src="https://user-images.githubusercontent.com/89638/126304314-86c3a7b4-f1b7-46e7-ba38-d1abc1ff1daf.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17305)

**Comment by Amejia481** [comment]
I think many of these string are getting use directly on apps, we put them on AC to have central place for them. We'll take a look.

**Comment by pocmo** [comment]
Okay, makes sense. In this case we may want to either reference them somewhere here too or just suppress the warning.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796305

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
