### ISSUE TITLE
Android 12: Explicitly set mutable or immutable flag on PendingIntent instances

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10641]
https://developer.android.com/about/versions/12/behavior-changes-12

> If your app targets Android 12, you must specify the mutability of each PendingIntent object that your app creates. This additional requirement improves your app's security.

Lint is complaining about all our `PendingIntent` objects. To continue with the Gradle / Android Plugin update I will disable this specific lint check. However we need to go through the `PendingIntent` objects and decide whether they should be mutable or immutable (mostly probably immutable). To make things worse: `FLAG_IMMUTABLE` is only available on API 23+. If you mirror the value (since it's just an int) then Android Studio complains that this is not a `PendingIntent.*` flag you are using. Argh.

**Comment by Mugurell** [comment]
This was done in https://github.com/mozilla-mobile/android-components/pull/11669
