### ISSUE TITLE
503 errors from Firebase?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10667]
Quite often I see this the following error in UI test tasks. It started when we upgraded our build (Gradle, Android Plugin, Java), but somehow that doesn't seem related?

> [task 2021-07-22T00:42:58.565Z]       "domain": "global",
[task 2021-07-22T00:42:58.565Z]       "message": "The service is currently unavailable.",
[task 2021-07-22T00:42:58.565Z]       "reason": "backendError"
[task 2021-07-22T00:42:58.565Z]     }
[task 2021-07-22T00:42:58.565Z]   ],
[task 2021-07-22T00:42:58.565Z]   "message": "The service is currently unavailable.",
[task 2021-07-22T00:42:58.565Z]   "status": "UNAVAILABLE"
[task 2021-07-22T00:42:58.565Z] }
[task 2021-07-22T00:42:58.565Z] 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
[task 2021-07-22T00:42:58.565Z] 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
[task 2021-07-22T00:42:58.565Z] 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
[task 2021-07-22T00:42:58.565Z] 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
[task 2021-07-22T00:42:58.565Z] 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
[task 2021-07-22T00:42:58.565Z] 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
[task 2021-07-22T00:42:58.565Z] 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
[task 2021-07-22T00:42:58.565Z] 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
[task 2021-07-22T00:42:58.565Z] 	at ftl.client.google.AppDetailsKt.getAndroidAppDetails(AppDetails.kt:7)
[task 2021-07-22T00:42:58.566Z] 	at ftl.run.platform.RunAndroidTestsKt.reportPackageName(RunAndroidTests.kt:101)
[task 2021-07-22T00:42:58.566Z] 	at ftl.run.platform.RunAndroidTestsKt.access$reportPackageName(RunAndroidTests.kt:1)
[task 2021-07-22T00:42:58.566Z] 	at ftl.run.platform.RunAndroidTestsKt$runAndroidTests$2.invokeSuspend(RunAndroidTests.kt:54)
[task 2021-07-22T00:42:58.566Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2021-07-22T00:42:58.566Z] 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
[task 2021-07-22T00:42:58.566Z] 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
[task 2021-07-22T00:42:58.566Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
[task 2021-07-22T00:42:58.566Z] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[task 2021-07-22T00:42:58.566Z] 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
[task 2021-07-22T00:42:58.566Z] 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
[task 2021-07-22T00:42:58.566Z] 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
[task 2021-07-22T00:42:58.566Z] 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
[task 2021-07-22T00:42:58.566Z] 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
[task 2021-07-22T00:42:58.566Z] 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
[task 2021-07-22T00:42:58.566Z] 	at ftl.domain.RunTestAndroidKt.invoke(RunTestAndroid.kt:66)
[task 2021-07-22T00:42:58.566Z] 	at ftl.presentation.cli.firebase.test.android.AndroidRunCommand.run(AndroidRunCommand.kt:54)
[task 2021-07-22T00:42:58.566Z] 	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
[task 2021-07-22T00:42:58.566Z] 	at picocli.CommandLine.access$1300(CommandLine.java:145)
[task 2021-07-22T00:42:58.566Z] 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
[task 2021-07-22T00:42:58.566Z] 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
[task 2021-07-22T00:42:58.566Z] 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
[task 2021-07-22T00:42:58.566Z] 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
[task 2021-07-22T00:42:58.566Z] 	at picocli.CommandLine.execute(CommandLine.java:2078)
[task 2021-07-22T00:42:58.566Z] 	at ftl.Main$main$1.invoke(Main.kt:12)
[task 2021-07-22T00:42:58.566Z] 	at ftl.Main$main$1.invoke(Main.kt:10)
[task 2021-07-22T00:42:58.566Z] 	at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:28)
[task 2021-07-22T00:42:58.566Z] 	at ftl.run.exception.ExceptionHandlerKt.withGlobalExceptionHandling(ExceptionHandler.kt:17)
[task 2021-07-22T00:42:58.566Z] 	at ftl.Main.main(Main.kt:10)

https://firefox-ci-tc.services.mozilla.com/tasks/Q30_Hg8pS0qh1gtv5LfDIg/runs/0/logs/public/logs/live.log

**Comment by pocmo** [comment]
@rpappalax I am not sure how to proceed here.

**Comment by AaronMT** [comment]
See this too. I'll open a GCP ticket.

**Comment by AaronMT** [comment]
> Hello, 
> 
> Thank you for the more recent occurrence, I have passed it on to our product team. 
> 
> Our product team has seen a recent report similar to yours (503s in the /getApkDetails endpoint). They are working on rolling out a fix based on the current working theory that this is an internal deadline being exceeded. 
> 
> The external symptoms match with your report. I will update you as soon as I have confirmation that this is the same internal symptoms as your reported case, or no later than 18:00 PDT 2021-08-02.

**Comment by AaronMT** [comment]
Upgraded Flank as well

21.08.0 supports an `executeWithRetry` in `ftl.client.google.AppDetailsKt` which is causing frequent `503` error timeouts in UI tests on Firebase. This is a result of our large APKs. Google is also rolling out a fix based on the current working theory that this is an internal deadline being exceeded in the next several days.
