### ISSUE TITLE
Engine: Add open window / close window API

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1067]
Websites can open links in new windows/tabs - via JavaScript or via `target="_blank"` links. We will need the necessary APIs for that to `EngineSession`:

WebView APIs:
* https://developer.android.com/reference/android/webkit/WebChromeClient#onCreateWindow(android.webkit.WebView,%20boolean,%20boolean,%20android.os.Message)
* https://developer.android.com/reference/android/webkit/WebChromeClient#onCloseWindow(android.webkit.WebView)

WebView's `onCreateWindow` API is potentially problematic: It requires to return a boolean to indicate whether the app is going to open a new window and has an asynchronous result message parameter.

**Comment by csadilek** [comment]
There's a subtask here as we need to support a setting for multiple window support: https://github.com/mozilla-mobile/android-components/issues/1452

**Comment by pocmo** [comment]
Should we just enable this by default (to align the default with GeckoView)?

**Comment by csadilek** [comment]
@pocmo I think we could, but we'd need to make sure firetv sets it to false to keep the current behaviour. we can add that to the changelog.

**Comment by csadilek** [comment]
We've hit a limitation here when implementing the engine-gecko-* parts of this. Details can be found here: https://bugzilla.mozilla.org/show_bug.cgi?id=1510314
