### ISSUE TITLE
Expose and implement GeckoView ServiceWorkerDelegate

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#10723]
We don't seem to currently have support for GeckoView's ServiceWorkerDelegate: https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoRuntime.ServiceWorkerDelegate.html.

**Comment by Mugurell** [comment]
This functionality was verified in https://github.com/mozilla-mobile/fenix/issues/24618#issuecomment-1101576771.
Closing.
