### ISSUE TITLE
DataProtect: Make `Keystore` class `open` for client tests

### ISSUE THREAD

**Issue by sashei** [mozilla-mobile/android-components#1072]
We need to mock the `Keystore` class in DataProtect for our tests. To do this, the class needs to be `open` rather than `final`.

**Comment by pocmo** [comment]
Are you using Mockito?

You can place such a file in your test resources folder and then you will be able to mock final classes:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-system/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

We use that in a bunch of places in this repository. Would this be helpful for your use case?

**Comment by sashei** [comment]
We aren't using Mockito.

**Comment by pocmo** [comment]
> We aren't using Mockito.

What are you using? :)

> However, I could see that use case being a good reason to include it if that's the android-components preferred way to mock libraries.

That's what we use extensively. However use whatever works for you. I'm not opposed to opening the classes at all.

I'll move this issue into our sprint so that we can resolve it timely. Either we make the classes open in the next release or you switch to Mockito. :)
