### ISSUE TITLE
Add support for the Storage Access API prompt

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10739]
[Storage Access API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API) helps prevent website breakage in ETP Standard mode, it's needed to enable multiple use cases like paying with third party services.

GeckoView bug https://bugzilla.mozilla.org/show_bug.cgi?id=1543720

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17445)

**Comment by Amejia481** [comment]
This prompt is part of [the permissions API](https://hg.mozilla.org/mozilla-central/rev/53dfbd4776e8) for it to work we need to :

* Add a new permission to [SitePermissions](https://github.com/mozilla-mobile/android-components/blob/main/components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/SitePermissions.kt#L18)
* Add a new permission request for this new type to [PermissionRequest](https://github.com/mozilla-mobile/android-components/blob/8299d94751f6b7dd56bf41004f4d3a47591d9731/components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/PermissionRequest.kt#L11)  and Add the Gecko equivalent [one](https://github.com/mozilla-mobile/android-components/blob/main/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt#L64-L69).
* Add a [dialog for the new permission ](https://github.com/mozilla-mobile/android-components/blob/main/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt#L688-L693).

After implementing the dialog you can trigger it by using this page https://senglehardt.com/test/dfpi/storage_access_api.html

**Comment by Mugurell** [comment]
The prompt was verified in Fenix - https://github.com/mozilla-mobile/fenix/issues/22852.
