### ISSUE TITLE
Metadata is saved for purely redirect urls

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#10743]
STR:
- type something like `reddit.com/r/vancouver` into the awesomebar, and go to that link
- refresh the page, perform ^^ a few times

Visiting this url will result in a series of redirects, some of which register as navigation events, triggering us to save metadata for the final url in the redirect chain (A=https://www.reddit.com/r/patientgamers/) and for the intermediate step (B=https://www.reddit.com/r/patientgamers). There are also two more urls in my moz_places (http://reddit.com/r/patientgamers and https://reddit.com/r/patientgamers) which didn't end up in the metadata.

Checking moz_historyvisits, i see that B has only visit_type=5 visits, which is a permanent redirect visit.

The desired outcome, I think, is that we don't save metadata for URLs which are redirecting. We can _probably_ do this at Fenix/A-C level (does content or session state for the tab have anything about visit flags we got from GV? e.g. "this is a redirect").

And we can _certainly_ do this at A-S level (check moz_historyvisits, bail out if only stored visits are redirects... and perhaps if most recent visits were redirects? not very certain how to account of potential variety of visit types here).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17458)

**Comment by grigoryk** [comment]
There's `contentState.loadRequest?.triggeredByRedirect` which seems useful here.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796410

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
