### ISSUE TITLE
Add a timeout to BrowserIcons#loadIconInternal

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#10749]
While trying to find a root cause for https://github.com/mozilla-mobile/fenix/issues/20351 i saw that [BrowserIcons#loadIconInternal](https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt#L121) will wait indefinitely and stall all future call until the current icon call is resolved.

With 
```
if (request.url.contains("nwradu")) {
    Thread.sleep(50_000) 
    // or delay(50_000)
}
````
(the url filtering allowing for other calls being resolved gracefully but to test that when something is slow it will affect even otherwise the results that we just saw worked nicely) 
somewhere in that method or in `load()` I get the exact same outcome as in the Fenix issue:

https://user-images.githubusercontent.com/11428869/128301202-e3574e78-cbac-4038-86ff-300ab29a8291.mp4

The easiest solution I think would be to have a timeout for  `load()` call, maybe 100ms, and if reached return a generated icon.
Maybe also to parallelize `loadIcon()` calls in suggestion providers so that in the most extreme cases we'll not wait 100ms for each suggestion, but 100ms for all.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17474)

**Comment by Mugurell** [comment]
@csadilek @pocmo 
I was looking at the logs from https://github.com/mozilla-mobile/fenix/issues/20351#issuecomment-912791590 where I see the following scenario:
- enabled suggestion providers: `HistoryStorageSuggestionProvider`, `BookmarksStorageSuggestionProvider,` `SyncedTabsStorageSuggestionProvider`, SessionSuggestionProvider`, `SearchEngineSuggestionProvider`
- on a quick succession user entered 0 -> 6 characters in the awesomebar
- for the first inputs the the bookmarks / history providers found some results but they are cancelled before returning because the text input changed
- then for the 6 characters input we see the first from 4 suggestions from `SyncedTabsStorageSuggestionProvider` being mapped [inside List<ClientTabPair>.into()](https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/SyncedTabsStorageSuggestionProvider.kt#L61) with a generated icon after 14 minutes.
And although the [providers are queried in a separate coroutine](https://github.com/mozilla-mobile/android-components/blob/f1661b79e676fba03446cb017cbc94b35c60179a/components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt#L164) the first result from `HistoryStorageSuggestionProvider` is mapped with a generated icon after 10 more seconds.
I think the only thing these providers have in common is using the same client for fetching the icon.

One improvement that can be done in `SyncedTabsStorageSuggestionProvider` is to limit the number of results.
But this should not have impacted the 14 minutes time for mapping one result.
It seems that the `HttpIconLoader` timeouts or the coroutine one I added are not enough to prevent the issue.

Thinking about how a slow download can stall all results mappings in a provider - the 10 second read timeout is enough to make the user close the suggestions without seeing a result (why I wanted to squeeze a bit of time by having these mappings run concurrently) another approach that could help with showing the suggestions as fast as possible would be to not wait for http icons. Show the results with memory/disk/generated icons and update them with the downloaded icons when those are available.

Looking at the [timings telemetry for suggestions providers](https://sql.telemetry.mozilla.org/dashboard/fenix-awesomebar-performance?p_w57759_days=7&p_w57759_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57760_days=7&p_w57760_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57761_days=7&p_w57761_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57762_days=7&p_w57762_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57763_days=7&p_w57763_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57764_days=7&p_w57764_org_mozilla_fenix=org_mozilla_fenix_nightly&p_w57765_days=7&p_w57765_org_mozilla_fenix=org_mozilla_fenix_nightly) seems like this is not a widespread issue though so maybe we can wait until the above scenario with placeholder icons is easy to be implemented in Compose using Sebastian's ImageLoader ?

(Regarding suggestion providers telemetry, not all telemetry is sent to Glean yet. [#20693](https://github.com/mozilla-mobile/fenix/pull/20693) is waiting for review to collect the data from new/updated providers)

**Comment by Mugurell** [comment]
Talked "offline" with Christian about this.
He suggested asking users for a stack trace to understand what's hanging the `BrowserAwesomeBar` threads.

**Comment by Mugurell** [comment]
@pocmo Following the above approach of asking for a thread dump two users helped and in one's logs there were clear `futex_wait_queue_me` occurences for the `BrowserIcons` threads though not clear why / where. 

So as a last try I just commented out the `HttpIcons` provider, kept the same code otherwise (no coroutines timeout like I initially proposed) and even without the clipboard issue fixed users who tested reported everything being "really fast" with no luck in reproducing the issue again - https://github.com/mozilla-mobile/fenix/issues/20351#issuecomment-922245667

Talked now with Christian about a possible approach for instant suggestions: not show http icons in suggestions.
For suggestions we could only go through `memory`/`disk`/`data uri` loaders and return immediately the suggestions with an icon either from these or a generated one. This would mean instant suggestions.

**Only if** we return a generated icon (which I assume means we don't have one in memory/disk/uri) start the download for that icon url (one thread would be sufficient for all these downloads?) just to feed the memory, which would then cache the icon on disk for future requests.

This would mean a high probability we would show a generated icon for the first time a certain suggestion is shown but instant suggestions all around and instant suggestions containing a downloaded icon even for that case the next time around.

Not sure how this applies to tippy top.

Thoughts?

cc @csadilek

**Comment by pocmo** [comment]
> Talked now with Christian about a possible approach for instant suggestions: not show http icons in suggestions.
> For suggestions we could only go through `memory`/`disk`/`data uri` loaders and return immediately the suggestions with an icon either from these or a generated one. This would mean instant suggestions.

- We could consider this as a workaround. I thought that we already had this as a config option in `IconRequest`, but I can't find it. Maybe that only existed in Fennec and we didn't add that to our component so far. Let's test this in a build a bit: Do we see re-requests, do we see icons appear later, does it cause visual noise?
- Separately we should still investigate if requests block longer than our request limits and involve the GeckoView team. If we still end up blocking our threads then this is still problematic - just not as visible.
- Eventually I think I would like to get away from having the icons in the `Suggestion` at all. Let's move the loading of the icons to the UI layer - like we do for Pocket for example. The UI layer is also the one that decides which suggestions are going to get displayed. No need to load all the icons for suggestions we never display. In the UI layer we also have the ability to show a placeholder and async replace it with the icon once loaded.

**Comment by Mugurell** [comment]
Instead of a timeout we went with loading icons in the background and not blocking.
Change is live for some time in Focus and Fenix. Closing this.
