### ISSUE TITLE
(API 31) ClipboardSuggestionProvider: Use ClipDescription.getConfidenceScore()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10761]
When reading the clipboard on Android 12+, a toast message notifies the user of this clipboard access. We are reading the clipboard in `ClipboardSuggestionProvider` to show an awesomebar suggestion if the clipboard contains a URL. This means this toast message may popup randomly when the awesome bar is shown.

[See Android 12 behavior changes](https://developer.android.com/about/versions/12/behavior-changes-all#clipboard-access-notifications)

We can avoid the toast message by not reading the clipboard and instead (On API 31+):
* Read the description only with `getPrimaryClipDescription()`
  * https://developer.android.com/reference/android/content/ClipboardManager#getPrimaryClipDescription()
* Use `ClipDescription.getConfidenceScore()`with `TextClassifier.TYPE_URL`
  * https://developer.android.com/reference/android/content/ClipDescription#getConfidenceScore(java.lang.String)
  * https://developer.android.com/reference/android/view/textclassifier/TextClassifier#TYPE_URL

Also note that, unfortunately, Fenix has its own `ClipboardHandler` that we may need to update too:
https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt

**Comment by pocmo** [comment]
Needs SDK 31: #10910

**Comment by Amejia481** [comment]
Similar Fenix implementation https://github.com/mozilla-mobile/fenix/commit/cc968d093cf4629683bb8292ae734c80cc79d2ec

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/android-components/pull/11716.
