### ISSUE TITLE
Add API for file uploads

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1076]
For file uploads we get a callback from the engine to show a file chooser. This may require a system permission to read the external storage. I was wondering if we could handle this internally in the engine. However at least for the permission request and the intent result from the picker we'd need some help from the app, I guess.

For GeckoView take a look at Focus and `GeckoViewPrompt.onFilePrompt`:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java#L716

And `GeckoViewPrompt.onFileCallbackResult()`:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java#L770

The WebView APIs:
https://developer.android.com/reference/android/webkit/WebChromeClient#onShowFileChooser(android.webkit.WebView,%20android.webkit.ValueCallback%3Candroid.net.Uri[]%3E,%20android.webkit.WebChromeClient.FileChooserParams)

Both APIs require a callback. I'm not sure how we want to expose that. We do not really want to stuff a callback into `Session`.

**Comment by NotWoods** [comment]
Closing this since its been added to PromptFeature a while back
