### ISSUE TITLE
WebExtensionBrowserMenuBuilder does not support Custom Tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#10791]
In Focus, we want to enable the WebCompatFeature in the Custom Tabs browser menu, but using the `WebExtensionBrowserMenuBuilder`, we are not receiving updates that make a `WebExtensionPlaceholderMenuItem` visible.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17539)

**Comment by jonalmeida** [comment]
This is far more complicated than I anticipated.

Adding `tabId` to the `WebExtensionBrowserMenuBuilder` is one part of the fix needed.

The other is in `CustomTabsToolbarFeature` that needs to construct a new `BrowserMenuBuilder` with the combined `CustomTabsConfig` menu items and our browser menus. To have the feature know that it needs to use a specific type of menu builder is more complicated as we would need to change the design of the feature to support a menu builder that can have new items added to it or we delegate the construction to the caller to provide us with the completed menu builder with the items to add.

**Comment by jonalmeida** [comment]
Unassigning for now because it's not a high priority.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795442

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
