### ISSUE TITLE
Move ProfilerMarkerFactProcessor from fenix/focus to ac

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#10808]
Fenix and focus have a `ProfilerMarkerFactProcessor` class: let's move this shared code into ac and update both projects to use the shared code. Notes:
- the focus version has tests that use mockito like ac (fenix uses mockk) so we should copy that one here
- we intentionally copied this code into focus initially, rather than adding it to ac, to get it added to the product more simply and quickly https://github.com/mozilla-mobile/focus-android/issues/5030
- using a fact processor for profiler markers is not ideal – we'd rather call into the profiler API directly – but it makes it much easier to add new markers so my long term thinking is that we keep the fact processor but slowly migrate markers from the fact processor to the profiler APIs when we determine which ones are most useful

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17584)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795443

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
