### ISSUE TITLE
Update context menu builder and design

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/android-components#10822]
Why/User Benefit/User Problem
We are constrained to make some updates on context menu classes because with the current implementation Share link and Copy link candidates are added to image/video context menu and according to the [new design](https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2133%3A282251) we don't want that

Also as we can see in Figma, context menu dialog UI was updated

What / Requirements
Acceptance Criteria (how do I know when I’m done?)

**Comment by pocmo** [comment]
Let's ping @brampitoyo here. It would be nice to have the same options as in Fenix - and I'm not sure if there's any reason to not have copy & share in Focus.

**Comment by brampitoyo** [comment]
@ionutbedregeanu I agree with @pocmo’s suggestion. Let’s keep the menu options as identical as possible between Focus and Fenix – for maximum consistency and maintainability.

The only Focus-specific design element remaining is the caption text that says “Saved and shared images will not be deleted when you erase Firefox Focus history”. The rest can follow Fenix. Thanks!

**Comment by lobontiumira** [comment]
Verified as fixed as per https://github.com/mozilla-mobile/focus-android/issues/5098#issuecomment-908339763
