### ISSUE TITLE
API feedback and improvements for service/firefox-accounts

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#1085]
I am opening this issue to collect feedback I have while integrating [service/firefox-accounts](https://github.com/mozilla-mobile/android-components/tree/master/components/service/firefox-accounts) into our [reference-browser](https://github.com/mozilla-mobile/reference-browser/) and to start discussing future improvements. Nothing here needs to be addressed immediately. Should I run into a bug that can't be worked around I will file a separate issue.

~**Configuration:**~ (**Fixed**)
The first step when using the API is to create a `Config` instance and pass it to the `FirefoxAccount` constructor. In addition, a `CLIENT_ID` and `REDIRECT_URL` need to be provided separately:
```Kotlin
 Config.custom(CONFIG_URL).then { 
   config -> FirefoxAccount(config, CLIENT_ID, REDIRECT_URL)
 } ...
```
Later, when the OAuth flow is started, `scopes` and the `wantsKeys` boolean need to be provided:
```Kotlin
account.beginOAuthFlow(scopes, wantsKeys)
```
At least `CLIENT_ID` and `REDIRECT_URL` (and probably `scopes`) are client-side config properties as they won't change at run-time (if at all). We could extend the `Config` class to contain both server-side and client-side configurations. This would clean up the API quite a bit.

~**Result types:**~ (**Fixed**)
We've introduced `FxaResult` to have a promise type in Java < 8. This has now been duplicated in `SyncResult`. It doesn't appear to be a goal anymore to support old versions of Java. GeckoView switched to Java 8 as well. If that's the case, I'd vote for removing these types and replace them with `CompletableFuture` (Java SDK) or `Deferred` (Kotlin), where we need Promise types, and a simple synchronous result type otherwise.

**Higher-Level API:**
At least from a Java/Kotlin dev perspective, I originally expected `FirefoxAccount` to represent an account i.e. to be a data class or value object. In reality, it's the entry point of the API and contains almost all functionality of the library including the OAuth flow. After bringing in `service-firefox-accounts` as a component, I would have expected something along the lines of:
```Kotlin
val fxaService = FirefoxAccountsService(config)
val loginUrl = fxaService.createLoginUrl()
```
We could even provide login methods for the various supported use cases e.g.:
- Login using a CustomTab
  ```Kotlin
  fxaService.login()
  ```
- Login using a fragment with a WebView or GeckoView
  ```Kotlin
  fxaService.login(fragment)
  ```
- Login using full Android component integration where e.g. a. tab can be opened directly, which is how the reference browser will do it
  ```Kotlin
  fxaService.login(tabsUseCase)
  ```
We'd have to hide the Android components `UseCase` type/instance behind an interface or pass a Lambda instead to avoid the dependency from service/fxa to feature/tabs, but that's an implementation detail. I think this can be implemented without requiring changes to the underlying Rust API.

~**Race condition in FxA Sample App:**~ (**Fixed by** https://github.com/mozilla-mobile/android-components/pull/1148)
When the app is started and the main activity created, we asynchronously load the `Config`. It's possible for the UI to be visible before the `Config` is ready. If a login flow is initiated at that point, we'll be getting a NPE. I fixed that in the reference browser by making sure the `Config` is ready before the OAuth flow is started, but it would make sense to add this logic to the library directly so that Apps don't have to worry about it. Something along the lines of:

```Kotlin
  @Volatile lateinit var config: Config
  @Volatile var afterInit: ((Config) -> Unit)? = null

  fun init() {
    Config.custom(CONFIG_URL).whenComplete {
      config = it
      afterInit?.invoke(config)
    }
  }
    
  fun authenticate() {
    if (config != null) {
      authenticate(config)
    }
    else {
      afterInit = { authenticate(it) }
    }
  }
```

**Docs/Test:**
We still need to add docs for the public API and more test coverage.

**Comment by pocmo** [comment]
That's great document 👍 

>  I'd vote for removing these types and replace them with CompletableFuture (Java SDK) or Deferred (Kotlin), where we need Promise types, and a simple synchronous result type otherwise.

+1 for `Deferred`. All our (already 8) consumers are using Kotlin and I think we expect nothing else from other new projects. All our other components are made for Kotlin consumers.

In addition to that `CompletableFuture` seems to be API 24+ only and `desugar` doesn't backport it:
* https://developer.android.com/reference/java/util/concurrent/CompletableFuture
* https://developer.android.com/studio/write/java8-support

**Comment by pocmo** [comment]
> We could even provide login methods for the various supported use cases e.g.:

I haven't used fxa myself yet but those API examples for the different workflows look pretty nice to me :)

**Comment by eoger** [comment]
This proposal looks fine to me, would you be interested in us consolidating the `Config` object on the Rust side? I've been thinking about this for a while but never really had time to work on it.

**Comment by vladikoff** [comment]
cc @rfk

**Comment by vladikoff** [comment]
> +1 for Deferred. All our (already 8) consumers are using Kotlin and I think we expect nothing else from other new projects. All our other components are made for Kotlin consumers.

Notes uses the Java version, but I think I can switch it to Kotlin and then all consumers will be using Kotlin at this point.

**Comment by vladikoff** [comment]
> Higher-Level API:

The higher level API looks good to me. Thanks @csadilek !

**Comment by rfk** [comment]
> At least from a Java/Kotlin dev perspective, I originally expected FirefoxAccount to represent 
> an account i.e. to be a data class or value object. In reality, it's the entry point of the API and
> contains almost all functionality of the library including the OAuth flow. 

Having poked at the integration in the reference-browser a little, I agree with this and think there are some more improvements we could make here.

There's currently no clear distinction between the pre-authorization and post-authorization states of the application.  If I have a `FirefoxAccount` instance (such as the `account` property [here](https://github.com/mozilla-mobile/reference-browser/blob/98c682a26ea7ce0def89fb154ebf786aa06f323d/app/src/main/java/org/mozilla/reference/browser/browser/FirefoxAccountsIntegration.kt#L55)) then it's not obvious whether it's connected to a user's account or whether I need to do an OAuth flow to connect it.  We could use the typesystem to help us here by splitting out some separable concepts into distinct objects/types.

Here's a strawman with extremely verbose naming:

* The "*client configuration*" holds all the pre-authorization state of the application - its client id and redirect URI and what-not.  This is pretty close to the current `Config` object and it's a built-in property of the application, not loaded from or persisted to disk.
* The "*client authorization state*" holds the post-authorization state of the application once it's connected to a user's account - the refresh token and keys, user profile information, etc.  This is pretty close to the current `FirefoxAccount` object, except that it is always signed in, and is all the stuff that should be persisted to disk.

The purpose of doing an OAuth flow is to go from the pre-authorization state to the post-authorization state, so I would expect things like `complete_auth_flow` to be methods on the client configuration that, if successful, return the newly-created client authorization state.  In other words, the client config is a kind of "factory" for producing an active authorization state for the application to use.

Imagine using it like this (and forgive my I-don't-actually-know-kotlin pseudocode):

```
// The app should always know its correct client config parameters.
clientConfig = FxAClientConfig(CLIENT_ID, REDIRECT_URI, ...etc...)

// The app may or may not be currently connected to a user's account,
// let's see by trying to load authorization state from disk.
authzState = null
savedState = getSharedPreferences().getString(FXA_STATE_KEY, "")
if (savedState) {
  try {
      // We should check that the saved state actually belongs
      // to the expected FxAClientConfig, especially for developers who
      // change between different server environments.
      authzState = clientConfig.loadAuthorizationStateFromString(savedState)
  } catch {
      // Oh no! Corrupt data, or changed settings, or something.
      // Wipe saved state and ask user to re-authenticate.
  }
}

// If the app is not connected to a user's account then we can't
// accidentally try to call e.g. `getProfile()` because `authzState` will be null.

authzState.getProfile() // <-- null-checked type error

// When the user clicks the "sign in" button we can do an authorization flow
// and persist the resulting authzState to disk.

clientConfig.launchOAuthFlow(SCOPES).await().let {
  authzState = it
  authzState.toJSONString().let {
     getSharedPreferences().edit().putString(FXA_STATE_KEY, it).apply()
  }
}

// Once we know have a non-null "authorization state" object we know we're definitely
// connected to a user's account, so we can confidently do things like show
// their profile picture:

authzState.getProfile().await().let {
  display_profile_picture_in_menu(it.avatar)
}

// Or access their sync data:

authzState.getAccessToken("oldsync").await().let {
  sync_all_the_things(it)
}

// Or sign out, destroying our active OAuth tokens in the process.

authzState.revoke().await()
```

@csadilek, how would this feel from your PoV as a consumer?

I imagine splitting the current API between these two classes roughly as follows:

```
FxAClientConfig {

  constructor(clientId, redirectUri, issuerUri, ...etc...);

  // The state for in-flight OAuth flows belongs to this object.
  beginOAuthFlow(scopes, wantsKeys) -> String;
  beginPairingFlow(scopes, wantsKeys) -> String;
  completeOAuthFlow(code, state) -> FxAAuthorizationState;

  // Higher-level helpers also go here.
  launchOAuthFlow(scopes, wantsKeys) -> FxAAuthorizationState;
  launchPairingFlow(scopes, wantsKeys) -> FxAAuthorizationState;

  // Also this is responsible for hydrating from disk.
  loadAuthorizationStateFromString(state) -> FxAAuthorizationState;
}


FxAAuthorizationState {

  constructor(clientConfig, refreshToken, keys, ...etc...);

  getProfile() -> Profile;
  getAccessToken() -> OAuthAccessToken;

  // In future, client instance metadata stuff goes here.
  setDeviceName(name);
  setPushSubscription(...);

  // We don't currently expose this, but we should!
  revoke();
}
```

@eoger, this was partly inspired by the key-overwriting thing from #rust-components earlier today.  Do you think having this kind of separation at the Rust level would have made that bug less likely?

@vladikoff thoughts?  I'm not 100% jazzed about the naming here, but from my experience working with this library so far, I think this separation it worth teasing out more explicitly.

**Comment by eoger** [comment]
Looks interesting, I'll have a more-in-depth look tomorrow.
Some thoughts:
- How does `FxAAuthorizationState` deal with multiple different scopes? What if the application needs a new scope later in its lifetime?
- How would `loadAuthorizationStateFromString` deal with revoked tokens? Would it check them one-by-one before creating the `FxAAuthorizationState`? What if we have a long lived `FxAAuthorizationState` and one of the oauth token it holds is revoked?

In a general sense I think we need to be very careful around error states/401 Uauthorized responses and to make it easy for consumers to recover (possibly in a single place).

**Comment by csadilek** [comment]
@rfk I like the proposal of introducing a separate `FxaAuthenticationState` and agree that it will make the consuming code much clearer. I wouldn't go directly from a `FxaClientConfig` to a `FxaAuthenticationState` though, because then the config must contain all authentication flow functionality, which I wouldn't expect. 

I think we need a third concept e.g. a `Service` that takes a config, handles the auth flow, and returns a `FxaAuthenticationState`. Then the `FxaClientConfig` is really just holding configuration values, the `FxaService` contains the authentication functionality, and the `FxaAuthenticationState` represents the result (with some functionality.)

Not sure about the naming either, but I see these three concepts, a config, a service, and a result/state. That's where I had planned to go with the higher level API anyways...

**Comment by rfk** [comment]
> then the config must contain all authentication flow functionality, which I wouldn't expect.

Yes, good call, something called "Config" should really be static data.

**Comment by csadilek** [comment]
We have everything we wanted here now. The beginning of a higher-level API landed as well, introducing a feature module for fxa: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt#L22

Thanks everyone!
