### ISSUE TITLE
Verify if we still need the DOWNLOAD_WITHOUT_NOTIFICATION permission

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10858]
It looks like this permission is use to download files with the default Android [downloader without showing a notification](https://developer.android.com/reference/android/app/DownloadManager.Request#setNotificationVisibility(int)) and it's used in companion with [VISIBILITY_HIDDEN](https://developer.android.com/reference/android/app/DownloadManager.Request#VISIBILITY_HIDDEN) flag but [we are not using it](https://github.com/mozilla-mobile/android-components/blob/bdad210ca49c178e99deb90e28e996a4c6520a76/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/AndroidDownloadManager.kt#L131).  Maybe we needed it at some point but not any more, let's double check, if we still need it we can remove it and let the apps use the default Android download manager to add it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17646)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792930

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
