### ISSUE TITLE
Allow to customize the security icons

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10866]
As a request for https://github.com/mozilla-mobile/fenix/issues/20892, we need have control over security icons (secure and insecure) on consumer apps, as we want to apply a different set of colors (https://github.com/mozilla-mobile/android-components/issues/10225) on the `drawables` and at the moment we are restricted as the icons live completely on AC.

We want to add: 
* APIs for customized the security icons (secure and insecure).
* API to prevent AC from [adding tint to theses icons](https://github.com/mozilla-mobile/android-components/blob/main/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt#L498-L510).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17661)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796290

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
