### ISSUE TITLE
Allow to persist temporary permissions in private tabs

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#10915]
At the moment we are [only storing site permissions in normal tabs](https://github.com/mozilla-mobile/android-components/blob/73c23fd7e8e11c0a22376da28cc691ca4b5fb6b7/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt#L332). GeckoView is going to introduce some new APIs that will allow us to persist site permission for the session scope.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17753)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796464

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
