### ISSUE TITLE
Could not find org.mozilla.components:support-extensions:92.0.15

### ISSUE THREAD

**Issue by UltraBurstXD** [mozilla-mobile/android-components#10935]
Hi,

I'm trying to build my own custom browser based on Mozilla Fenix core, everything was synced well but I'm having issues with `org.mozilla.components:support-extensions:92.0.15`. Was it deprecated or renamed?

![Screenshot from 2021-09-05 09-03-34](https://user-images.githubusercontent.com/55871338/132118553-c254fc12-fe7f-4add-9019-2680045cb39b.png)
![Screenshot from 2021-09-05 09-06-20](https://user-images.githubusercontent.com/55871338/132118555-d5310055-0518-43ee-a7a3-274fc0d98633.png)

**Comment by pocmo** [comment]
The name of the component seems to be `support-webextensions`.
