### ISSUE TITLE
The Sync Strings workflow should not fail with an error if Fenix is not in Beta

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#10948]
I'm getting emails that the Sync Strings workflow on A-C is failing. But when I look at the error it says `[E] Branch mozilla-mobile/fenix:releases_v92.0.0` is not in beta.

Let's see if we can turn that into an Info or Warning and stop the workflow gracefully. Because this is a normal situation. It is only supposed to run when there is a Fenix Beta branch active.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17793)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795444

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
