### ISSUE TITLE
Android Autofill: Support diplaying inline suggestions (keyboard, Android 11+)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#10956]
On Android 11+ it's possible to show autofill suggestions inline in the keboard UI instead of overlaying the app UI.

Docs:
https://developer.android.com/guide/topics/text/ime-autofill

Example screenshots:
https://www.androidpolice.com/2020/08/10/android-11-will-make-password-autofill-much-better-thanks-to-keyboard-integration/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17819)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796337

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
