### ISSUE TITLE
Cannot access class 'mozilla.components.feature.push.AutoPushFeature'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by UltraBurstXD** [mozilla-mobile/android-components#10968]
Hi,
~~~ kotlin
// Enable push if it's configured.
        push.feature?.let { autoPushFeature ->
            FxaPushSupportFeature(context, accountManager, autoPushFeature, crashReporter)
        }
~~~

I'm getting `Cannot access class 'mozilla.components.feature.push.AutoPushFeature'. Check your module classpath for missing or conflicting dependencies` error with code above, I don't know what could possible cause that.

I have `implementation "org.mozilla.components:feature-accounts-push:$mozac_version"` added in my gradle.build module file. I'm missing something...?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17847)

**Comment by jonalmeida** [comment]
`feature-accounts-push` is for the integrationi between Firefox Sync and (generic) Autopush support.

As the logs suggest, you need to add `feature-push` to your dependencies too:

```gradle
implementation "org.mozilla.components:feature-push:$mozac_version"
```

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796422

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
