### ISSUE TITLE
Image context menu is truncated

### ISSUE THREAD

**Issue by ionutbedregeanu** [mozilla-mobile/android-components#10982]
Image context menu is truncated when its additional note is visible.
This can be reproduced on landscape, even on portrait but on small devices
Focus bug: https://github.com/mozilla-mobile/focus-android/issues/5387

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17886)

**Comment by lobontiumira** [comment]
This is not fixed yet, according to https://github.com/mozilla-mobile/focus-android/issues/5387#issuecomment-922769248.

**Comment by jonalmeida** [comment]
@ionutbedregeanu I think we need to uplift this change to the 93 branch of AC for the fix to make it into Focus 93 too. We can then bump the Focus AC version to get the change.

**Comment by csadilek** [comment]
Landed in https://github.com/mozilla-mobile/android-components/pull/10983.
