### ISSUE TITLE
`AutoPushFeature.renewRegistration()` doesn't seem to renew anything

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/android-components#10989]
I've a Fenix with an expired push endpoint. I was hoping #10913 would fix it, but it doesn't. That PR does do what it intended though - logcat now shows:

```
2021-09-16 13:41:32.260 14361-14394/? I/ConstellationObserver: Our push subscription either doesn't exist or is expired; renewing registration.
2021-09-16 15:04:36.633 21720-21787/? W/AutoPushFeature: Forcing registration renewal by deleting our (cached) token.
2021-09-16 15:04:36.634 21720-21787/? I/AbstractFirebasePushService: start
2021-09-16 13:41:32.261 14361-14394/? I/ConstellationObserver: Incrementing verifier
```

So now we are correctly hitting [the call to `AutoPushFeature.renewRegistration()`](https://github.com/mozilla-mobile/android-components/blob/823681c77194b0a87e64484b43d14d7d9c889ccf/components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt#L216) - and although it logs that its doing what it is supposed to, it has no impact - every single start shows the same log entries, and other devices still see the `notifyError: "expiredCallback"` in the response trying to send a tab to this device.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17896)

**Comment by jonalmeida** [comment]
Our "renew" [logic](https://github.com/mozilla-mobile/android-components/blob/823681c77194b0a87e64484b43d14d7d9c889ccf/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L280-L292) is to delete the device push token and submit the new one that we receive to autopush.

In your logs, were you able to see any logs from Firebase that suggested a new token was received?

Somewhere below your logs, you should see [this log line](https://github.com/mozilla-mobile/android-components/blob/823681c77194b0a87e64484b43d14d7d9c889ccf/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L152) if Firebasee provides us with a new token.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796421

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
