### ISSUE TITLE
Add support for incoming Intents

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#110]
In Focus we pass incoming Intents to SessionManager which then will decide whether a new session needs to be created etc. - UI components listening to the SessionManager will then update once there is a new Session or new data available:

https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/session/SessionManager.java#L53

I think the general approach is nice. However I would decouple this behavior from SessionManager and move this to an IntentHandler (name to be defined) class that an app can delegate Intents to - or decide to do its own thing.

**Comment by pocmo** [comment]
In this issue we should only care about Intent.ACTION_VIEW. Once we have that we can think about Intent.ACTION_SEND and others.

**Comment by csadilek** [comment]
We've merged the [IntentProcessor](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/src/main/java/mozilla/components/feature/session/SessionIntentProcessor.kt) and have this functionality.

Let's create separate issues for any specific future intents we want to handle by default.
