### ISSUE TITLE
Add a "Copy Link Text" button in link's long press menu

### ISSUE THREAD

**Issue by FSpark** [mozilla-mobile/android-components#11035]
Copying link text in other browsers is extremely easy via the context menu... 

In fact, in many cases, it is impossible to copy the link text.

It's quite useful, please 😢

Thank you in advance for your help.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18029)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795446

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
