### ISSUE TITLE
History suggestions: Ranked lower (No scoring?) and less useful?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11036]
In Fenix Nightly it seems like the order of suggestions in the `AwesomeBar()` composable is different than what the view-based `BrowserAwesomeBar` used.

Primarily I see history suggestions end up at the bottom of the list, while they used to be at the top. Suggestions are ordered by their "score" in both cases - so it is surprising that the order is different.

**Comment by csadilek** [comment]
@pocmo In Nightly we also use our new history suggestion provider. That could also be the cause, see 'CombinedHistorySuggestionProvider'. Maybe we missed something.

**Comment by pocmo** [comment]
> Yes, so suggestion from history metadata have no score. Just like say tab/session suggestions so assuming that's why they are lower ranked now.

Yeah, that's definitely the reason then - the awesome bar is ordering descending by score.

**Comment by pocmo** [comment]
CC @kbrosnan - I think Kevin mentioned getting less useful results in general regardless of the order. Seeing that we prefer using history metadata storage suggestions over history storage suggestions, this may be something to look into too.

```Kotlin
val combinedSuggestions = (metadataSuggestions.await() + historySuggestions.await())
            .take(maxNumberOfSuggestions)
```

**Comment by pocmo** [comment]
Findings:

* The history storage provider uses the frecency score
* The metadata storage provider assigns no score (0)
* The combined storage provider prefers metadata storage suggestions over history storage suggestions - which means it may be more likely to get suggestions with a score of 0
* With a 0 score those suggestions will be at the end - a bunch of other providers assign 0 too (bookmarks), which makes it also a bit random
* (Unclear: Are the suggestions from the metadata storage less "useful" in general?)

Thoughts:

* How do we rank under the hood of the metadata storage provider? Does it use frecency too?
* Possible workaround: If the list of suggestions from the metadata storage provider is ordered then we could use the order as score
* Possible workaround: In cases were the same suggestion is in the history storage provider, we could use its frecency score

**Comment by csadilek** [comment]
We've fixed the scoring to make sure history suggestions are ranked higher and to match the requirements: Metadata suggestions first, followed by regular history ones up to the desired maximum, and also de-duped by URL. Whether or not these suggestions are more useful remains to be seen, and we really should run an experiment and measure it. Ultimately, we want to switch to the new history highlights mechanism we're currently introducing that supports configurable weights.
