### ISSUE TITLE
parseContentDisposition incorrectly parses "filename*" segment with semicolon at the end

### ISSUE THREAD

**Issue by proninyaroslav** [mozilla-mobile/android-components#11054]
Some servers build responses with the wrong order of `filename`/`filename*` segments in the ContentDisposition, for example, instead of
```
attachment; filename=_.jpg; filename*=utf-8'en'filename.jpg
```
we have a messed up order:
```
attachment; filename*=utf-8'en'filename.jpg; filename=_.jpg
```
In this case, `DownloadUtils.parseContentDisposition` will produce an invalid name:
```
filename.jpgfilename_.jpg
```
instead of
```
filename.jpg
```

As an example, I will give a response from this web site: https://pan.tpcraft.cn/api/v3/file/source/7/Java8%2064%E4%BD%8D.exe?sign=TuX1WLnbXtd0V7RmoFDvvmqgMN8EmVNs03xeacaNqGA%3D%3A0
```HTTP
Content-Disposition: attachment;filename*=utf-8''f3I5VzTa%5FJava8%2064%E4%BD%8D%2Eexe;filename="f3I5VzTa_Java8 64%E4%BD%8D.exe"
```

`DownloadUtils.parseContentDisposition` will produce an invalid name:
```
f3I5VzTa_Java8 64位.exefilenamef3I5VzTa_Java8
```
instead of
```
f3I5VzTa_Java8 64位.exe
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18072)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792928

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
