### ISSUE TITLE
Thumbnails are deleted without support for undo

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#11079]
When a tab is removed we immediately delete the thumbnail for that tab. When the tab is undone (undo-ed? 😄 ), we no longer have it so we show our placeholder.

We can add support for undo by waiting for the `ClearRecoverableTabs` instead.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18149)

**Comment by pocmo** [comment]
Should we also add it to `RecoverableTab`, so that it can go back into `ContentState.thumbnail`?

**Comment by jonalmeida** [comment]
We can! We only store a very small set of thumbnails in the store memory (we hit `onTrimMemory` fast), so 90% of the time we are getting the thumbnails from disk.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796257

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
