### ISSUE TITLE
TabCollection(s) in BrowserState

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11088]
This issue is about investigating whether we could have `TabCollection`s inside `BrowserState`.

Currently the app accesses `TabCollectionStorage` directly.

However for new code we start to follow this pattern:
* All state is in `BrowserState`
* A `Middleware` is responsible for interacting with the storage
* The `Middleware` loads the initial state
* The `Middleware` persists state changes in the storage

Advantages of this pattern are:
* It's easy to observe the state and related changes
* Other code/components can interact with the state too and react to specific actions from a middleware (Adding tabs to collections, Restoring tabs, ...)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18179)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793183

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
