### ISSUE TITLE
Intermittent UI test failure - unit-sitepermissions - Test run failed to complete. No test results. onError: commandError=false message=INSTRUMENTATION_ABORTED: System has crashed. 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11095]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.9f526cd30412cc12/matrices/5197166843278548940/executions/bs.ba81460587553145/issues
### Stacktrace:
Nothing about `gecko` or `mozilla` in the log.
### Build: 
https://github.com/mozilla-mobile/android-components/commit/a992c202e76f186fe718464cd64b433b47cd3c1d

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18194)

**Comment by csadilek** [comment]
System crash that doesn't seem actionable by us. Let's close and re-open if we see again.
