### ISSUE TITLE
LoginsStorage APIs performance improvements around decryption 

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#11132]
A couple of problems with the API:
- fetching all items via `list` will decrypt every single item
- each call to `decrypt` will obtain a key via `key()`, which could be _very_ expensive
- canary verification happens every time we obtain a key. this could just happen once per session; in practice, probably doesn't matter if we're mindful about key handling though (e.g. not fetching it hundreds of times in a row)

In practice, we want to:
- obtain key once per-use, e.g. if we're displaying all logins in the "see all" ui, we want to have the key once and then use it to decrypt usernames; when displaying individual login, we want the key to decrypt username/password.
- have an ability to fetch all items without forcing decryption of the password field.
  - maybe without decrypting at all, actually, if there are places where we won't need the plaintext username right away.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18308)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796501

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
