### ISSUE TITLE
Android Autofill: Save credentials

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11145]
So far our `AutofillService` only autofills logins and passwords in other apps. But the reverse is possible too: Save credentials when logging into an app or creating a new account in an app.

https://developer.android.com/guide/topics/text/autofill-services#save

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18349)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794236

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
