### ISSUE TITLE
Implement WebExtension API |download.downloads|

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/android-components#11140]
All is needed for this is implementing `DownloadDelegate::onDownload`: https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/WebExtension.DownloadDelegate.html#onDownload-org.mozilla.geckoview.WebExtension-org.mozilla.geckoview.WebExtension.DownloadRequest-

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18337)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793214

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
