### ISSUE TITLE
MimeTypeMap.getFileExtensionFromUrl returns empty string on some file names.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#11153]
The same method was used to get file names in Focus, and in some cases, this returns an empty string. (`/storage/emulated/0/download/wikipedia-logo-v2@2x(17).png` for example, for a downloaded file).

Using `URLEncoder.encode` to encode the string first results in returning the correct filename.

IMO we should create an extension method that returns the file extension and use it in AC, Fenix, and Focus.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18408)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792927

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
