### ISSUE TITLE
Remove browser-storage-memory

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#11173]
This component was created mostly for testing purposes as a simple implementation of the `concept-storage`. While it was useful in the early days of A-C as a way to test-fit our storage components into things, we haven't really kept it up, and are not getting much value out of this code. It's time to remove it!

**Comment by 4shutosh** [comment]
I would like to work on this issue @grigoryk

**Comment by pocmo** [comment]
@4shutosh Great! Make sure to remove the Gradle module and related code as well as update `.buildconfig.yml`. Let us know if you need any help or if you have questions.

**Comment by 4shutosh** [comment]
Okay, on it.
