### ISSUE TITLE
`SuggestionFetcher` creates 7 threads – can we re-use existing threads?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#11177]
The search `SuggestionFetcher` creates a new `ExecutorService` with a thread for each provider:

https://github.com/mozilla-mobile/android-components/blob/4223f401756848b61ca39be8f6fd461bd4c97fc9/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/SuggestionFetcher.kt#L27-L30

In the current implementation, there appear to be 7 providers – https://share.firefox.dev/3E4PbEk – so we're creating 7 threads. (fwiw, [the old provider used 3](https://searchfox.org/mozilla-mobile/rev/1456b35d54833447fde34ead04d900ce581abcee/android-components/components/browser/awesomebar/src/main/java/mozilla/components/browser/awesomebar/BrowserAwesomeBar.kt#45)). Given these threads will be largely idle and some of these providers don't do IO, this seems excessive: are there other threads we can re-use to conserve resources? For example, could we use the IO dispatcher? Given the only thing on this screen is searching, it seems unlikely that that dispatcher will be at capacity. Also, there's a thread pool for the top sites icons that's likely inactive now – can we share those threads?

That being said, I'm not sure what and how many resources idle `ExecutorService` threads take up. Do they use CPU? How much memory do they use? How does sharing (or not sharing) threads affect cache locality?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18476)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795448

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
