### ISSUE TITLE
Remove BrowserAwesomeBar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11184]
Focus and Fenix are using the Compose version of the AwesomeBar. Only Reference Browser (and probably sample browser) need to be switched. After that we can remove `BrowserAwesomeBar`, which will allow us to simplify the interfaces in `concept-awesomebar`. The component was already marked as "deprecated" a while ago (#11063).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18494)

**Comment by gouri-panda** [comment]
@pocmo  I want to work on this issue. Can I first do this in the Reference browser and sample browser? If I'll successfully do this then I can simplify the `concept-awesomebar` and remove the `feature-awesomebar` . It'll be a great opportunity to learn both internally and externally :)
