### ISSUE TITLE
onOpenOptionsPage doesn't actually trigger a page load

### ISSUE THREAD

**Issue by birtles** [mozilla-mobile/android-components#11182]
### STR:

1. Install 10ten Japanese Reader using the following collection details:
  Collection owner (user ID): 6693726
  Collection name: japanese
2. Enable the extension
3. Load a page with Japanese text, e.g. https://ja.wikipedia.org/
4. Drag the "puck" so that some Japanese text is highlighted and popup window shows
5. Press the settings icon in the top-right of the popup

### Expected results:

The options page is loaded in a new tab.

### Actual results:

A new tab is opened with the options URL filled in the location, but it is not loaded.

If you open the location bar and press "Enter" / "Go" etc., however the page loads successfully.

Furthermore, if you open the options page from the menu it loads successfully.

(Note that the options page is currently not scrollable but that is a bug in the add-on itself and has been [fixed upstream](https://github.com/birchill/10ten-ja-reader/commit/c48159a5fca0bb84830e8f2d8be3663cb716e0cc).)

### Video:

https://user-images.githubusercontent.com/1232595/139200056-e490142d-9c82-47cd-9d20-94f12246ae08.mp4

### Notes:

This add-on does _not_ set `open_in_tab` so the options page should be loaded using the `onOpenOptionsPage` handler added in eed463d931206f3eb49edc864aa09c5888b4cf09 (see #7397).

At a guess, I wonder if instead of passing `false` as the `active` flag to `onNewTab` we should be passing `true`, here:

https://github.com/mozilla-mobile/android-components/blob/04bd14f2a3b5bea15641e03c8794303c02e3a243/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt#L278-L290

Note that the operation of this add-on is:

* Content script passes an `'options'` message to the background page
* Then the background page [calls `browser.runtime.openOptionsPage()`](https://github.com/birchill/10ten-ja-reader/blob/c48159a5fca0bb84830e8f2d8be3663cb716e0cc/src/background/background.ts#L467).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18491)

**Comment by birtles** [comment]
> At a guess, I wonder if instead of passing `false` as the `active` flag to `onNewTab` we should be passing `true`, here:

I tried this but it didn't help.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795449

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
