### ISSUE TITLE
AwesomeBar suggestions: Do not block on icon load

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11185]
Depends on: #11184

Currently the `AwesomeBar.Suggestion` data class has an `icon: Bitmap?` property. This means that suggestions have to reload the icon in order to add it to the data class. This delays showing suggestions unnecessarily. The AwesomeBar should be responsible for loading the bitmaps of suggestions it displays and while that happens can show a placeholder. This will allow us to show suggestions faster and avoid loading icons for suggestions that the awesomebar may not be displaying.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18493)

**Comment by pocmo** [comment]
Just came across this old issue:
https://github.com/mozilla-mobile/android-components/issues/4653

Apparently this was the case initially, we were delaying loads until the suggestion got displayed. But it seems like this caused some flickering. So we need to make sure we would not reintroduce this.

**Comment by pocmo** [comment]
> Apparently this was the case initially, we were delaying loads until the suggestion got displayed. But it seems like this caused some flickering. So we need to make sure we would not reintroduce this.

Some ideas to work around that:
* Since the input for the icon doesn't change (URL -> Icon), maybe Jetpack Compose can "cache" this for us and no fetching at all is needed for a "recompose"
* The memory look up could be synchronous and only file/http loads would happen asynchronously. With that it should not flicker because the icon is immediately available (from memory) for updates and we never display no icon.

**Comment by gouri-panda** [comment]
>Some ideas to work around that:

Since the input for the icon doesn't change (URL -> Icon), maybe Jetpack Compose can "cache" this for us and no fetching at all is needed for a "recompose"
The memory look up could be synchronous and only file/http loads would happen asynchronously. With that it should not flicker because the icon is immediately available (from memory) for updates and we never display no icon.

@pocmo It sounds a great idea! Can I try it?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796327

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
