### ISSUE TITLE
[Telemetry] Tag for DebugLogClient is not working

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/android-components#1121]
After using `Log.addSink(AndroidLogSink())`, logcat output no longer honor the tag set in DebugLogClient.

**Comment by pocmo** [comment]
All that should be needed here is passing the tag to the Logger class here:

https://github.com/mozilla-mobile/android-components/blob/c1b23d064dec60721ff21ce154d64a38f4728769/components/service/telemetry/src/main/java/org/mozilla/telemetry/net/DebugLogClient.kt#L16-L17
