### ISSUE TITLE
Move AwesomeBar wrapper into Android Components repository.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11214]
In Fenix I created an `AwesomeBarWrapper` class that wraps the `AwesomeBar()` composable and makes it available as a `View` and `concept-awesomebar` implementation.
https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarWrapper.kt

A similar wrapper exists in `samples-browser`:
https://github.com/mozilla-mobile/android-components/blob/main/samples/browser/src/main/java/org/mozilla/samples/browser/awesomebar/AwesomeBarWrapper.kt

And we will likely need such a thing for Reference Browser too in order to get rid of `browser-awesomebar` eventually (https://github.com/mozilla-mobile/android-components/issues/11184).

Let's move a generic implementation of this wrapper into `compose-awesomebar`. With that we can continue to get rid of `BrowserAwesomeBar` usages and remove `browser-awesomebar`. In addition to that having the wrapper inside Android Components will make it easier to change the interfaces in `concept-awesomebar` since we can update the wrapper right here and only once (https://github.com/mozilla-mobile/android-components/issues/11185).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18542)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796326

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
