### ISSUE TITLE
JCenter still getting used

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#11239]
In this PR: https://github.com/mozilla-mobile/android-components/pull/11237

I saw the following error come up:

> [task 2021-11-09T12:29:03.905Z] > Could not GET 'https://jcenter.bintray.com/org/gradle/kotlin/gradle-kotlin-dsl-plugins/2.1.4/gradle-kotlin-dsl-plugins-2.1.4.module'.
> [task 2021-11-09T12:29:03.906Z] > PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

Looks like JCenter is still getting queried for some Kotlin dependencies.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18591)

**Comment by pocmo** [comment]
Looks like its not our configuration and this is by design (according to the Kotlin Slack):
> The POM is hosted on the Gradle Plugin Portal and has a reference to the Gradle module metadata, so it searches for the module file.
The module file though is missing on the plugin portal.
Things that are missing on the plugin portal are forwarede to JCenter, which then finally forwards to Maven Central for things it does not host itself.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795451

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
