### ISSUE TITLE
Running A-C tests for GV Patches

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/android-components#11268]
Allows surfacing issues sooner, rather after GV Nightly integration PR lands in A-C.	

https://jira.mozilla.com/browse/FFXP-531

ask ahal about this

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18636)

**Comment by csadilek** [comment]
Let's keep tracking this in https://mozilla-hub.atlassian.net/browse/FFXP-531, as this repo will be archived soon.
