### ISSUE TITLE
Incompatible glean versions

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/android-components#11276]
Over at matrix#glean, mcomella found an inconsistency in the glean dependency:

service-glean depends on glean-native [42.0.1](https://nightly.maven.mozilla.org/maven2/org/mozilla/components/service-glean/96.0.20211115143414/service-glean-96.0.20211115143414.pom) and browser-engine-gecko depends on GeckoView [96.0.20211115093917](https://nightly.maven.mozilla.org/maven2/org/mozilla/components/browser-engine-gecko/96.0.20211115143414/browser-engine-gecko-96.0.20211115143414.pom) which depends on [42.1.0](https://maven.mozilla.org/maven2/org/mozilla/geckoview/geckoview-nightly-omni/96.0.20211115093917/geckoview-nightly-omni-96.0.20211115093917.module)

This should not build, but it does because our resoultion strategy prefers GeckoView: https://searchfox.org/mozilla-mobile/source/android-components/build.gradle#87-93

We shouldn't rely on the resolution strategy since outside consumers don't have that and instead have matching versions across the codebase. Will post a patch soon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18650)

**Comment by csadilek** [comment]
The fix for this landed, and the [link above](https://searchfox.org/mozilla-mobile/source/android-components/build.gradle#87-93) is actually pointing to it now. Original problem was: https://github.com/mozilla-mobile/android-components/blob/f925bb97085856ce7ec07f2579e4a1f9790de315/build.gradle#L87-L92
