### ISSUE TITLE
Support DRM videos by overriding onPermissionRequest

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/android-components#1128]
In order to support DRM videos, `WebChromeClient.onPermissionRequest` needs to be overridden and the `RESOURCE_PROTECTED_MEDIA_ID` permission needs to be granted. Could you provide a callback so we can optionally show a dialog to accept or deny the permission?

Something like this:
```
override fun onPermissionRequest(request: PermissionRequest) {
       for (r in request.resources){
          if (r == PermissionRequest.RESOURCE_PROTECTED_MEDIA_ID)
               ...
       }
}
```

See https://github.com/mozilla-mobile/firefox-tv/issues/787 for more context.

**Comment by Sdaswani** [comment]
@st3fan we would like to have this in the next A-C release so we can get it into 3.1 build. cc @athomasmoz

**Comment by pocmo** [comment]
Related to #1110.

**Comment by pocmo** [comment]
@dnarcese Do you need a callback to handle this or do you always want to grant this request automatically?

**Comment by dnarcese** [comment]
@pocmo If it's not too much more work, a callback would be nice 🙂 I think it's best to keep the option open for if we decide to show a dialog.

**Comment by Sdaswani** [comment]
Ah yes, the callback isn't needed now - you can always put it on if the release can be had quicker and then build the callback later.

**Comment by pocmo** [comment]
Okay, I prepared a patch and will open a PR.

I used this test page:
http://shaka-player-demo.appspot.com/demo/

Without the patch I can't select/play DRM content and with the patch that works.
