### ISSUE TITLE
 Integrate feature-downloads component For download support 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1129]
https://github.com/mozilla-mobile/reference-browser/issues/24

**Comment by behlsoft** [comment]
Great! I was using this sample but was unable to download anything pdf or file. I was thinking it was my implementation issue. 
Eagerly waiting for this!
All the best mate!

**Comment by Amejia481** [comment]
:) I will you know as soon is integrated! 👍

**Comment by Amejia481** [comment]
@behlsoft the download feature is now available on this repository and also in [Reference-Browser
](https://github.com/mozilla-mobile/reference-browser). Your feedback is more than welcome! :)

**Comment by behlsoft** [comment]
@Amejia481 but am unable to download bank statement from my bank website. It does show popup but unable download

**Comment by Amejia481** [comment]
Could you describe the steps to simulate the issue? This way we can replicate it.
Is this only happening with your bank website or are you able to download other files?

Like this one: https://www.mozilla.org/media/img/logos/firefox/logo-quantum.9c5e96634f92.png

**Comment by behlsoft** [comment]
@Amejia481 am able to download files from some websites including attachment from gmail but when it comes to my bank websites like ICICI Bank or Aadhaar, it just shows pop up!
https://eaadhaar.uidai.gov.in/

 I can share screen recording too if you want!

**Comment by Amejia481** [comment]
Thank you for your wiliness to help. We filled a issue https://github.com/mozilla-mobile/android-components/issues/1159

Please, keep the feedback comming are preatty helpful!
Thanks for your help!
