### ISSUE TITLE
question about Prompts component

### ISSUE THREAD

**Issue by shalva97** [mozilla-mobile/android-components#11297]
Im making my own browser just for fun. Currently using Engine-Gecko component and it all works nice.

Yesterday I looked at prompts component. It confused me, seems like it has dependency on State component but on the docs at[ this link](https://github.com/mozilla-mobile/android-components/blob/main/components/feature/prompts/README.md) it shows:
```Kotlin
val promptFeature = PromptFeature(fragment = this,
  sessionManager = sessionManager,
  fragmentManager= fragmentManager,
  onNeedToRequestPermissions = onNeedToRequestPermissions
)
```

what is sessionManager? actually PromptFeature doesnot have such argument in any of its contructors.

The problem for me is that prompts component requires `BrowserStore`, which is part of State component. Is there a way to just make it work without adding other components?

**Comment by pocmo** [comment]
> what is sessionManager? actually PromptFeature doesnot have such argument in any of its contructors.

The documentation is outdated. `SessionManager` (`browser-session`) was a component that managed the state previously. It was replaced by `BrowserStore` from `browser-state`.

> The problem for me is that prompts component requires BrowserStore, which is part of State component. Is there a way to just make it work without adding other components?

No, that is not possible. `BrowserStore` is a central piece that many components will have a dependency on. It maintains the state the browser is in (`BrowserState`) and provides a mechanism for components to observe and change it. What happens under the hood is that the engine will add a prompt request to the state for a tab, and the prompt feature will observe the state and react to those requests in the state.
