### ISSUE TITLE
Metadata feature: group removal use cases

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#11309]
Let's start bringing bits and pieces of the metadata logic from Fenix and into A-C.

The first thing we can consider is adding removal use case for groups. There's just enough steps involved to perform removal correctly (sometimes matching history visits, sometimes not, dispatching actions on various stores, etc) to warrant encapsulating it all in a few use cases.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18728)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795453

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
