### ISSUE TITLE
Add error pages for HTTPS ONLY MODE

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#11306]
We need to add an error page for handling when users want to enter to insecure page (HTTP), as [suggested](https://github.com/mozilla-mobile/focus-android/issues/5365#issuecomment-918772374) by @brampitoyo, we can re-use the same error pages as Firefox desktop as they are responsive. You can find the desktop error page [here](https://searchfox.org/mozilla-central/source/toolkit/components/httpsonlyerror/content/errorpage.html) and hook it on AC via [GeckoEngineSession#onLoadError](https://github.com/mozilla-mobile/android-components/blob/677e24ca0dc1df5c2f22c18b51538a189286b245/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L549) using [ERROR_HTTPS_ONLY](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/WebRequestError.java#133).

![image](https://user-images.githubusercontent.com/773158/143094531-37a8cab4-866c-439d-bcd4-ecbdc190c627.png)

**Comment by pocmo** [comment]
This is the error page that currently shows up, without handling this case.

![request](https://user-images.githubusercontent.com/89638/144429320-629ee6a7-a9b3-4bf5-8fc2-7858b0bb24d2.png)

**Comment by pocmo** [comment]
For the button we need to invoke `document.reloadWithHttpsOnlyException();`
