### ISSUE TITLE
Update Prompts component example page

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#11303]
We have done multiple updates on the `feature-prompts` but we haven't update the [documentation](https://github.com/mozilla-mobile/android-components/blob/main/components/feature/prompts/README.md) in while.

As part of this ticket, we would like to revise the [README](https://github.com/mozilla-mobile/android-components/blob/main/components/feature/prompts/README.md) page update the parts that are not relevant anymore, and update them, show-case its usage.

An easy way to confirm what part are relevant, it is to verify [Sample browser](https://github.com/mozilla-mobile/android-components/tree/main/samples/browser), and see its `feature-prompts` usage, as it should be up to date.

**Comment by Amejia481** [comment]
Related ticket https://github.com/mozilla-mobile/android-components/issues/11297

**Comment by gouri-panda** [comment]
@Amejia481  I would like to work on this issue :)

**Comment by Amejia481** [comment]
Please, go for it :)

**Comment by gouri-panda** [comment]
@Amejia481 Should I implement all the parameters of `PromptFeature` or important ones?
