### ISSUE TITLE
Support Android Intent URLs

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#1132]
The [Android Intent URL spec](https://developer.chrome.com/multidevice/android/intents) lets web pages open Android apps. afaict, this is not currently built into components (`ag browser_fallback_url`) nor do the products handle such a case. If so, **this regresses existing Focus and Fire TV functionality).** This functionality is also supported in Fennec.

Fennec's behavior was roughly the following:
- Try to open app for intent. Prompt user first that they may be leaving the app.
- If there is no app, try to load the provided fallback URL, if relevant
- If there is no fallback URL, try to open the app on the market if relevant (note: some devices do not have the Play Store or other market so don't assume they do)
- If it fails, handle the link such that no action occurs (i.e. no error page is shown). Chrome has this behavior and many sites rely on it (see [fennec code for details](https://searchfox.org/mozilla-central/rev/fcfb479e6ff63aea017d063faa17877ff750b4e5/mobile/android/base/java/org/mozilla/gecko/IntentHelper.java#544)) such as clicking Facebook messenger links

See the old Focus, or Fennec, implementations for details. **This behavior may be outdated and we may want to reaudit** (e.g. is searching the store the best behavior?).

Test pages:
- m.facebook.com (click messenger)

**Comment by mcomella** [comment]
I tested on Focus and it appears that GeckoView will prompt to find an app to open a link, which is a different behavior than the system WebView: maybe I am mistaken that this is not handled and that this needs to be resolved at the app level.

I have not tested on Fire TV: I haven't seen this use case being used yet.

**Comment by mcomella** [comment]
Filed https://github.com/mozilla-mobile/focus-android/issues/3710 and https://github.com/mozilla-mobile/firefox-tv/issues/1330 against the specific products.

**Comment by buttercookie42** [comment]
> Prompt user first that they may be leaving the app.

The prompt only happens during private browsing, though.

**Comment by vesta0** [comment]
Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=806385

**Comment by jhugman** [comment]
Broken down in to #2974, #2975 #2976

**Comment by Natim** [comment]
I have to say that as of the last stable I wasn't able to open links in app. Am I looking at the right place? Will it be part of the next release?

**Comment by andreicristianpetcu** [comment]
Are you doing this https://twitter.com/FirefoxPreview/status/1152896874967425025 @Natim?
If it does not work for you, please report a new bug and mention the site you are having issues with https://github.com/mozilla-mobile/android-components/issues

**Comment by Natim** [comment]
No, never met this menu!!!

I was looking there:

![image](https://user-images.githubusercontent.com/229453/64624916-a9241400-d3eb-11e9-84c5-6e951ad8c3ea.png)

**Comment by pwd-github** [comment]
Is there an open bug for actually supporting Android Intents as opposed to this workaround?
