### ISSUE TITLE
Update Room to 2.4.0 for M1 Macbook compatability

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/android-components#11362]
Room v2.3.0 does not have native support for M1 Macbooks because of the underlying SQLite library they use. This has been fixed since [2.4.0-alpha03](https://developer.android.com/jetpack/androidx/releases/room#2.4.0-alpha03). It was suggested to me that we should wait until the next stable release of Room to perform an upgrade, so I'm opening this issue to track progress.

It looks like the [first release candidate](https://developer.android.com/jetpack/androidx/releases/room#2.4.0-rc01) was released this week, so we shouldn't have to wait long.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18812)

**Comment by jonalmeida** [comment]
I'm trying to work through this on my Mac as well and so far this is my WIP patch:

```diffdiff --git a/build.gradle b/build.gradle
index fa8149781f..496fe3342a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -72,7 +72,7 @@ subprojects {
 
     // Enable Kotlin warnings as errors for all modules
     tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
-        kotlinOptions.allWarningsAsErrors = true
+//        kotlinOptions.allWarningsAsErrors = true // Need to fix the kotlin 1.6 warnings.
     }
 
     project.configurations.all {
diff --git a/buildSrc/src/main/java/Dependencies.kt b/buildSrc/src/main/java/Dependencies.kt
index 87d238f12a..20d4fe7dfc 100644
--- a/buildSrc/src/main/java/Dependencies.kt
+++ b/buildSrc/src/main/java/Dependencies.kt
@@ -7,7 +7,7 @@
 
 // Synchronized version numbers for dependencies used by (some) modules
 object Versions {
-    const val kotlin = "1.5.31"
+    const val kotlin = "1.6.0"
     const val coroutines = "1.5.2"
 
     const val junit = "4.12"
@@ -35,7 +35,7 @@ object Versions {
 
     const val material = "1.2.1"
 
-    const val compose_version = "1.0.5"
+    const val compose_version = "1.1.0-rc01"
 
     object AndroidX {
         const val activityCompose = "1.4.0"
@@ -54,7 +54,7 @@ object Versions {
         const val test = "1.3.0"
         const val test_ext = "1.1.2"
         const val espresso = "3.3.0"
-        const val room = "2.3.0"
+        const val room = "2.4.0"
         const val paging = "2.1.2"
         const val palette = "1.0.0"
         const val preferences = "1.1.1"
```

**Comment by MatthewTighe** [comment]
Oh nice, glad to see that the official version has released. Have you run into issues with the other dependencies you've updated in the above patch? Room was the only one I had hit so far.

**Comment by jonalmeida** [comment]
Yeah, updating room was not enough because the build fails further on with kotlin, and Compose needs to be updated to match with that version too.

**Comment by grigoryk** [comment]
Running into this now on my new M1, going to look at resolving Kotlin 1.6.0 warnings.

**Comment by grigoryk** [comment]
WIP in https://github.com/mozilla-mobile/android-components/pull/11516, getting close.

**Comment by jonalmeida** [comment]
This was done by https://github.com/mozilla-mobile/android-components/pull/12006
