### ISSUE TITLE
Extract Logings and credit cards code from PromptFeature

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#11409]
We @pocmo, @csadilek  we were chatting about refactoring the `PromptFeature` class to just have prompts that are coming from the web content and have the engine prompts like credit cards, logings and passwords in a separate feature/request as those need a special treatment, and mixing the  feature/request makes the `PromptFeature` difficult to maintain.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18936)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796341

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
