### ISSUE TITLE
[auto-publication] clean up old builds from the local maven repository

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#11413]
Currently, android-component builds accumulate in `~/.m2/repository/org/mozilla/components/`. We really only need to keep the latest build.

The proposal here is:
- when we determine that local publication is necessary, purge all of `~/.m2/repository/org/mozilla/components` before running `publishToMavenLocal`.

This assumes that `~/.m2/repository/org/mozilla/components` only has things that are controlled via auto publication scripts, which I think is true.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18940)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796653

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
