### ISSUE TITLE
Nimbus FML plugin: download project defined A-S version of the nimbus-fml, not 'latest'

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#11422]
This is a follow-up to https://github.com/mozilla-mobile/android-components/pull/11420/

Currently, if local publication of application-services isn't enabled, the plugin will download/unzip nimbus-fml from `https://github.com/mozilla/application-services/releases/latest/download`. While this works for now (and for @jhugman's workflow, who's moving the plugin and `nimbus-fml` forward), it's non-ideal long-term and we'd it to rely on the same version of the binaries as the rest of our A-S dependencies.

For example, with the current setup we have to be conscious of the runtime vs code generator misalignment - e.g. the plugin generates `FxNimbus.kt` file from the manifest, which uses capabilities that are supplied by A-S. Without synchronizing versions, we need to be very mindful of keeping these two aligned - e.g. plugin must not generate something that's not available via the currently consumed version of A-S.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-18947)

**Comment by grigoryk** [comment]
cc @jhugman

**Comment by tarikeshaq** [comment]
This is not fixed yet, ref: https://github.com/mozilla-mobile/android-components/blob/b7cc8bdbe8c98a4075847a6a987dbfca85474bad/components/tooling/nimbus-gradle-plugin/src/main/groovy/mozilla/components/tooling/nimbus/NimbusGradlePlugin.groovy#L168-L174
