### ISSUE TITLE
Allow to choose the restore location of a tab

### ISSUE THREAD

**Issue by Choucroute-melba** [mozilla-mobile/android-components#11462]
Actually, recently closed tabs are restored at the top of the list by default.
To fix [mozilla-mobile/fenix:#22372](https://github.com/mozilla-mobile/fenix/issues/22372), we should leave the choice for the restore location `(TOP, END, AT_INDEX)`.

Happy New Year, good health and have fun🙂

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19020)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796656

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
