### ISSUE TITLE
Add a long press listener to nav bar

### ISSUE THREAD

**Issue by mavduevskiy** [mozilla-mobile/android-components#11488]
The [...issue/176](https://github.com/mozilla-mobile/fenix/issues/176) wants to bring more gestures to the app, to help users to navigate around. One of the ideas was to let users to navigate directly to Site permissions fragment directly, without going through the quck settings -> settings -> site permissions flow, by long pressing the security indicator icon.

Currently there is a `clickListener`, but not a `longClickListener`

<img width="395" alt="Screen Shot 2022-01-05 at 3 03 35 PM" src="https://user-images.githubusercontent.com/92760693/148304754-719ab802-6927-42bb-abcd-9d2003972c2b.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19058)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795429

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
