### ISSUE TITLE
Enable TCP  in strict mode and private mode

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#11480]
Related https://github.com/mozilla-mobile/fenix/pull/22766#pullrequestreview-843649243

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19045)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795428

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
