### ISSUE TITLE
Migrate photon icons from Fenix into ui-icons

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#11493]
We are possibly running into having duplicated and out of date (non-photon) icons between Fenix and `ui-icons`. In order to realign and keep things up to date, I am proposing we move all photon icons from Fenix into ui-icons and maintain a single source of truth.

- mozac_ic_download is not used anywhere https://searchfox.org/mozilla-mobile/search?q=mozac_ic_download&path=&case=false&regexp=false
- mozac_ic_mozilla is not used anywhere https://searchfox.org/mozilla-mobile/search?q=mozac_ic_moz&path=&case=false&regexp=false
- mozac_ic_pin_filled, mozac_ic_pin_fillled_2 https://searchfox.org/mozilla-mobile/search?q=mozac_ic_pin&path=&case=false&regexp=false
- mozac_ic_reorder https://searchfox.org/mozilla-mobile/search?q=mozac_ic_reorder&path=&case=false&regexp=false
- mozac_ic_rocket, mozac_ic_rocket_filled https://searchfox.org/mozilla-mobile/search?q=mozac_ic_rock&path=&case=false&regexp=false

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19066)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793151

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
