### ISSUE TITLE
Core ping: Report experiments

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#115]
https://github.com/mozilla-mobile/telemetry-android/issues/15

`"experiments": [<string>, /* … */], // Optional, array of identifiers for the active experiments`

**Comment by pocmo** [comment]
@fercarcedo I wonder if you could take this over. That's one thing we would need to do to satisfy this:
https://github.com/mozilla-mobile/fretboard/issues/9

In a nutshell we would need to add another field/measurement to [TelemetryCorePingBuilder](https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryCorePingBuilder.java#L55) for the list of experiment ids (Strings) to follow the [core ping schema](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/core-ping.html). Like other measurements we would need to make this accessible so that the app can provide the values.

Let me know if you need more hints!

**Comment by fercarcedo** [comment]
I can take a look at this, yes :)
