### ISSUE TITLE
No executed tests in BrowserToolbarTest (Test without @Test)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1150]
Is there any especial reason why the below tests are not been executed? 

https://github.com/mozilla-mobile/android-components/blob/977b2e29892f9927200ef34e3236f89fb68e63fa/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt#L288

https://github.com/mozilla-mobile/android-components/blob/977b2e29892f9927200ef34e3236f89fb68e63fa/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt#L205

**Comment by pocmo** [comment]
Nope. Probably just an oversight. Do they pass?

We really need a lint/whatever check for that.

Test that actually should not run are annotated with `@Ignore`.

**Comment by Amejia481** [comment]
Cool 👍 !
One pass and the other fail, maybe it got outdated.
I will take a look 🕵️ !
