### ISSUE TITLE
Write documentation for browser-toolbar component

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1153]
The docs should go in [/components/browser/toolbar/README.md](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/README.md)

For references you can take look at existing components docs:

- [errorpages](https://github.com/mozilla-mobile/android-components/tree/master/components/browser/errorpages) 
- [engine-system](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-system)

**Comment by pocmo** [comment]
I don't think that's a particular good issue for someone completely new. Keeping the "help wanted" though :)
