### ISSUE TITLE
Remove unused browserToolbarTrackingProtectionAndSecurityIndicatorSeparatorColor attribute

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#11557]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19169)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795431

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
