### ISSUE TITLE
Add API for permission requests

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1157]
Like #1078 for geolocation requests.

See #1110 for related "events that require callback" discussion.

We currently allow protected media requests (EME APIs) by default in `browser-engine-system` (#1128).

**Comment by pocmo** [comment]
WebView API:
* `WebChromeClient.onPermissionRequest()`

**Comment by kbrosnan** [comment]
https://permission.site/ covers a lot of permission based apis from html spec. A few are not implemented in gecko so check against desktop before filing bugs.

**Comment by pocmo** [comment]
That's a pretty awesome test site. Thank you!
