### ISSUE TITLE
Unable to download urls that contain prefix blob:

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1159]
```
 java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:https://
        at android.app.DownloadManager$Request.<init>(DownloadManager.java:445)
        at mozilla.components.feature.downloads.DownloadManager.download(DownloadManager.kt:63)
        at mozilla.components.feature.downloads.DownloadManager.download$default(DownloadManager.kt:52)
        at mozilla.components.feature.downloads.DownloadsFeature$showDialog$1.invoke(DownloadsFeature.kt:105)
        at mozilla.components.feature.downloads.DownloadsFeature$showDialog$1.invoke(DownloadsFeature.kt:37)
        at mozilla.components.feature.downloads.SimpleDownloadDialogFragment$onCreateDialog$$inlined$with$lambda$1.onClick(SimpleDownloadDialogFragment.kt:59)
        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by pocmo** [comment]
Short-term solution: Ignoring those download requests.

Long-term: Saving the data behind the blob URL as Download.
 * GeckoView: https://bugzilla.mozilla.org/show_bug.cgi?id=1501735
 * WebView: Ouch! Maybe just ignore them in WebView: https://stackoverflow.com/questions/48892390/download-blob-file-from-website-inside-android-webviewclient/48954970#48954970

**Comment by behlsoft** [comment]
hi team,
any update regarding this bug.

**Comment by NotWoods** [comment]
Steps to reproduce:

1. Open https://squoosh.app/
2. Select one of the predefined images, such as the large fox photo.
3. Tap the blue download button.

**Comment by sv-ohorvath** [comment]
Still reproducing on Nightly 11/13. Thanks!

**Comment by jonalmeida** [comment]
I was also able to reproduce this from the STR in this comment if ever need more links to try: https://github.com/mozilla-mobile/fenix/issues/2579#issuecomment-535981773

**Comment by lovasoa** [comment]
Could this issue be revived ? It is preventing the download of COVID19 attestation from the french government website.

**Comment by Amejia481** [comment]
> Could this issue be revived ? It is preventing the download of COVID19 attestation from the french government website.

@lovasoa do not worry  @kglazko is taking a look at it!

**Comment by madb1lly** [comment]
For comparison, in Fennec F-Droid it doesn't work either, but the reason is different - clicking the button to generate the attestion doesn't even attempt a download.

Cheers 🙂

**Comment by klint** [comment]
Note that as a comparison, it works on old Firefox for Android beta, but I fear when this beta will be upgraded to Fenix any time soon!! Thanks for taking care of it in these dire times.

**Comment by liuche** [comment]
Downgrading this to a P2 for now so that not everything we send to GV is P1 - we should bump this later if we reprioritize on the Fenix side.

**Comment by kbrosnan** [comment]
This is one of the more common download issues users encounter. There is a fairly good list of dupes here and on Fenix and Webcompat.

**Comment by madb1lly** [comment]
Hi all,
I checked Fennec F-Droid again and it downloads the attestation form fine, I don't know what I was doing wrong before.
Cheers 🙂

**Comment by Songbird0** [comment]
Still doesn't work. Tested on: https://media.interieur.gouv.fr/deplacement-covid-19/

Version: `5.0.0 (Build #21212136)
39.0.1, f19856fa4
GV: 76.0-20200424000239
AS: 0.58.2`

**Comment by miketaylr** [comment]
Also affecting mega downloads https://www.reddit.com/r/firefox/comments/gi3s23/cant_download_files_from_mega/

**Comment by TitanNano** [comment]
We can download blobs 🎊🎉 (tested with telegram web and squoosh.app)

**Comment by Amejia481** [comment]
> We can download blobs 🎊🎉 (tested with telegram web and squoosh.app)

Awesome :)
We still have some issues with [Firefox send and Some extensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1432949#c18) that use blobs, but most of the sites should work now. We need help to test multiple sites and discover possible edge cases, if you see something that is not working please, let us know :)

**Comment by madb1lly** [comment]
Hi all,
Confirmed working for https://media.interieur.gouv.fr/deplacement-covid-19/
Cheers 😃

**Comment by Amejia481** [comment]
I tested with the latest geckoview version `78.0.20200521093657` and the[ FireFox send issue](https://github.com/mozilla-mobile/fenix/issues/3336#issue-454639904) is gone 🎉 . For this be on Fenix we need a new version of ac that includes the above GV version. We can close issue and follow the https://github.com/mozilla-mobile/fenix/issues/3336#issue-454639904 ticket to confirm with QA

**Comment by 1M6host** [comment]
please if anyone is facing this issue.. the following worked for me :-

go to "\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview" in your android studio and then method "webView.setDownloadListener()"

        DownloadManager.Request request = new DownloadManager.Request(Uri.parse(url.replace("blob:","")));
replace this line

rebuild and run the app normally

**Comment by avinashsahoo** [comment]
> please if anyone is facing this issue.. the following worked for me :-
> 
> go to "\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview" in your android studio and then method "webView.setDownloadListener()"
> 
> ```
>     DownloadManager.Request request = new DownloadManager.Request(Uri.parse(url.replace("blob:","")));
> ```
> 
> replace this line
> 
> rebuild and run the app normally

This will prevent crashing. It'll not download the file.

Please confirm, if the file being downloaded.
