### ISSUE TITLE
Opening app links more often than we should? Documentation and behavior of `AppLinksInterceptor.launchInApp` conflicts

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#11591]
I think the documentation and behavior of launchInApp conflict. The docs say:
```
@param launchInApp If {true} then launch app links in third party app(s). Default to false because
 * of security concerns.
```

i.e. we never launch in third party apps if this is false. However, iiuc, the code shows we'll launch in third party apps even if launchInApp is false if it's a scheme the engine doesn't support:

https://github.com/mozilla-mobile/android-components/blob/b55a7d8daf6f022a1a0bf9490611db70c293fe35/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt#L89

and we don't have a fallbackUri:

https://github.com/mozilla-mobile/android-components/blob/b55a7d8daf6f022a1a0bf9490611db70c293fe35/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt#L121-L125

**What's the desired behavior?** Should we update the documentation to explain the current behavior or change the behavior?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19237)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793208

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
