### ISSUE TITLE
Firefox crash notification is not displayed on devices with Android 11/Android 12

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/android-components#11627]
This issue was found on Focus android app. 
https://github.com/mozilla-mobile/focus-android/issues/6215

**Steps to reproduce**
Open several tabs.
Insert about:crashparent in the URL field.

**Expected behavior**
The app is closed, and the crash dialog notification is displayed in the notification bar.

**Actual behavior**
The app is closed, but the crash dialog notification is not displayed in the notification bar.

**Device information**
Android device: Google Pixel 6 (Android 12), Oppo Find X3 Lite (Android 11)
Not reproducible on Google Pixel (Android 10)
Focus version: Focus Beta 97.0.0-beta.1, Fenix Nightly 97

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19286)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794932

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
