### ISSUE TITLE
Add ImageIcon to load and cache image URLs

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#11630]
We need an alternative to `BrowserIcons` that can load an image based on a provided image URL, and have it cached and load into a provided view.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19298)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793150

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
