### ISSUE TITLE
Search suggestion buttons in awesomebar not visible

### ISSUE THREAD

**Issue by tasosb** [mozilla-mobile/android-components#11632]
See Fenix issue [#23378](https://github.com/mozilla-mobile/fenix/issues/23378)

The suggestion icon's (mozac_ic_edit_suggestion) color is changing every time by the `Suggestion.kt ` file (for example by AwesomeBarWrapper.kt in fenix).

Something is happening in Suggestion.kt and when an attribute value is set as the `mozac_ui_icons_fill` color, the Image isn't created/tinted.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19305)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795433

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
