### ISSUE TITLE
Update Sentry version to latest release

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#11646]
As part of moving to a newer instance of Sentry, we should/probably need to update our dependencies to the latest version that is supported.

Apps:

- Fenix:
  - [ ] https://github.com/mozilla-mobile/fenix/issues/23490
  - [ ] Update **Fenix** documentation that references Sentry process.
- Focus:
  - [ ] https://github.com/mozilla-mobile/focus-android/issues/6319
  - [ ] https://github.com/mozilla-mobile/focus-android/issues/6318
  - [ ] Update **Focus** documentation that references Sentry process.
- Reference Browser:
  - [ ] https://github.com/mozilla-mobile/reference-browser/issues/1799

AC Next steps:
  - [ ] https://github.com/mozilla-mobile/android-components/issues/11795

**Comment by Amejia481** [comment]
It looks like we have multiple breaking APIs going from `1.7.21` to `5.6.1` 😅

**Comment by Amejia481** [comment]
Updating from our actual version `1.7.21 `to the latest sentry `5.6.1 ` is not straightforward 😅 , as as the API changed significantly, we will practically need to re-write [SentryService](https://github.com/mozilla-mobile/android-components/blob/main/components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SentryService.kt)

**Comment by jonalmeida** [comment]
If the API changes we need for AC are also significant and require time to develop, test and verify, we could make a new sentry service component so that we don't have to make one big PR of +4000 lines.

That would make it easier to slowly introduce it into each project and learn along the way.

**Comment by Amejia481** [comment]
Yeah, let go with that approach thanks for the recommendation!
