### ISSUE TITLE
Intermittent test failure - Test run failed to complete. No test results. onError: commandError=false message=INSTRUMENTATION_ABORTED: System has crashed. 

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#11640]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.9f526cd30412cc12/matrices/5049017683579743164/executions/bs.9d96fa21d7793fa6/issues
### Build: https://github.com/mozilla-mobile/android-components/commit/538a60b0953d8e3995d016facf40f7f585c4b973

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19317)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794923

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
