### ISSUE TITLE
Consider upstreaming wallpaper managment code from Fenix

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#11679]
The code that manages wallpapers and it's mechanics would be useful to upstream into an existing or new component. This would be good to make it re-usable for our other browsers in the future and create a defined structure to the feature as well.

cc: @Amejia481 @MatthewTighe

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19415)

**Comment by MatthewTighe** [comment]
I would love to tackle this! I did [most of a refactor](https://github.com/mozilla-mobile/fenix/pull/23113) of the feature into the `State` pattern already, and could revisit that work in a port to A-C

**Comment by Amejia481** [comment]
Just an addition to this, will be allowing the flexibility of hosting the metadata for seasonal wallpapers host on remote configuration this way we add/remove dynamically wallpapers.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795435

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
