### ISSUE TITLE
Update Robolectric to support Android 31

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#11670]
Saw in https://github.com/mozilla-mobile/android-components/issues/11666 that requires a change imposed by Android 31 that the currently used Robolectric version does not support Android 31.

We are using [version 4.1](https://github.com/mozilla-mobile/android-components/blob/2d152a477f3c1ca162304db466a504753c0c9f24/buildSrc/src/main/java/Dependencies.kt#L14)
First version to support Android 31 is [version 4.7](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.7)

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/android-components/pull/11801.
