### ISSUE TITLE
Create a FeatureFlag annotation that can fail the build if it's past the released version

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#11730]
In Fenix and Focus, we have feature flags that need to be updated when they ride the trains. It's easy to forget to do this or requires extra effort to make it part of a process.

In GeckoView, we have a [`DeprecationSchedule`](https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/DeprecationSchedule.java), which [annotates](https://searchfox.org/mozilla-central/rev/679ebe4ffdc7312e42d55badb02ef89336af8223/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java#3509) when an API should removed for a particular release. 

In that same train of thought, we can introduce an annotation that is placed on the FeatureFlag field with the version number that the flag should be changing in. If the version number in Fenix is equal or higher than this value, the build should fail and require user intervention to consider if the flag needs to be updated.

This is initially filed in AC, so that we can see if there is a way for us to make and place the annotation here so that all our products can benefit from the single implementation.

cc: @agi for reference; @amedyne.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19523)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795437

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
