### ISSUE TITLE
Expose String.stripCommonSubdomains

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/android-components#11743]
Functionality to strip common subdomains (such as "www", "mobile", "m") from URLs has been replicated across Fenix and A-C.

[DomainMatcher in A-C](https://searchfox.org/mozilla-mobile/source/android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DomainMatcher.kt#84)

[ext/URI in A-C](https://searchfox.org/mozilla-mobile/source/android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt#24)

[ext/String in Fenix](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/ext/String.kt#34)

and BlocklistHandler in Fenix.

These could be standardized into a single collection of extensions. This could include behavior to allow any two URL-ish strings to be compared, such that protocols, common subdomains, trailing slashes, etc are all dealt with correctly. Additionally, it might be helpful to avoid using the `android.net.Uri` in order to remain unit testable without Robolectric.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19557)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794912

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
