### ISSUE TITLE
Webshare API support for files, eg. Images

### ISSUE THREAD

**Issue by thomassth** [mozilla-mobile/android-components#11745]
Firefox Android does not accept `navigator.share` that has files in it.

Test method: 
Using https://w3c.github.io/web-share/demos/share-files.html
1. Upload an image
2. Click 'share'
3. The site reports:
> Error: File sharing is not supported in this browser.

Although this is marked as closed, and the `files` parameter mentioned, the feature is not implemented.

https://github.com/mozilla-mobile/android-components/issues/3486

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19571)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794931

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
