### ISSUE TITLE
Update compose to latest version - 1.1.0

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#11753]
As a followup to https://github.com/mozilla-mobile/fenix/issues/23871.

Beside updating compose to `1.1.0` and kotlin to `1.6.10` because of the kotlin update we'll also need to update room to at least `2.4.0` - https://developer.android.com/jetpack/androidx/releases/room#2.4.0-rc01

**Comment by gabrielluong** [comment]
Closing since this landed in https://github.com/mozilla-mobile/android-components/pull/11754
