### ISSUE TITLE
Two identical sessions open when opening a custom tab within a PWA

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/android-components#11759]
* Install a PWA (e.g. twitter.com)
* Open a custom tab within the PWA, e.g. click on an external link in Twitter
* Notice how **two** identical sessions get created, e.g. using DevTools

![image](https://user-images.githubusercontent.com/69051186/155212922-b5be3a75-218f-4246-8454-68d2637c88e8.png)

reproduced on the latest Fenix Nightly

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19607)

**Comment by cpeterso** [comment]
Here is the corresponding Fenix Jira issue: https://mozilla-hub.atlassian.net/browse/FNXV2-19607

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796433

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
