### ISSUE TITLE
Upstream "whats new" code from Fenix/Focus

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#11763]
We have two different implementations for determining when to show the "What's New" messaging and we can consolidate that with both products using similar versioning processes.

Fenix: https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/java/org/mozilla/fenix/whatsnew/WhatsNew.kt
Focus: https://github.com/mozilla-mobile/focus-android/blob/main/app/src/main/java/org/mozilla/focus/whatsnew/WhatsNew.kt

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19618)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795438

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
