### ISSUE TITLE
Fix `MigrationTestHelper` constructor deprecation in new room versions

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#11765]
After https://github.com/mozilla-mobile/android-components/pull/11754 room will be updated to version `2.4.1` which will have 2 of the `MigrationTestHelper` constructors deprecated, includint the one we use in `LoginExceptionStorageTest` - https://developer.android.com/reference/androidx/room/testing/MigrationTestHelper.

For now this deprecation doesn't pose an immediate problem as according to the official documentation they would only be an issue in the cases of tests involving AutoMigration, something that we don't use.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19627)

**Comment by gouri-panda** [comment]
@Mugurell I would like to work on this issue.

**Comment by Mugurell** [comment]
@gouri-panda This already has a patch availabe. It was in fact merged but then backed out because of other related issues.
We'll work on re-landing that original patch soon.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794859

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
