### ISSUE TITLE
Add better callback handling of synced tabs update failures

### ISSUE THREAD

**Issue by MozillaNoah** [mozilla-mobile/android-components#11775]
If there isn’t internet, the sync operation will fail but not report back to the frontend to halt the loading UI.

The code reaches the logger statement in `FxaAccountManager` at line 317
- “Ignoring syncNow request, not in the right state: "

I believe there's one other scenario that this occurs in.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19658)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794230

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
