### ISSUE TITLE
Perceived performance of tab tray scroll seems janky due to thumbnail loads

### ISSUE THREAD

**Issue by RotBolt** [mozilla-mobile/android-components#11783]
Browser thumbnail loader component currently
-  sets the placeholder first
-  then loads the thumbnail
- - then sets the thumbnail

This gives sometimes janky experience

For more refer this issue on fenix: https://github.com/mozilla-mobile/fenix/issues/21547

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19665)

**Comment by mcomella** [comment]
Triage: this should be closed when https://github.com/mozilla-mobile/android-components/issues/11783 lands.

**Comment by mcomella** [comment]
Triage: https://github.com/mozilla-mobile/android-components/pull/11784 landed so I'm going to close this. Note: during triage, we didn't test that the underlying issue is addressed but we assume the reviewer had tested it during review.
