### ISSUE TITLE
Move lib-sentry-crash.SentryService to lib-crash.SentryService

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#11795]
As part of https://github.com/mozilla-mobile/android-components/pull/11777/, we want to update Sentry to the latest version ( Now `5.6.1`), and test the new SDK incrementally in some of our apps without migrating everything right away, for this reason we introduce a new module `lib-sentry-crash` after we confirm the new sdk works as expected we could remove the previous implementation, and move  `lib-sentry-crash.SentryService` to `lib-crash.SentryService`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19687)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795439

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
