### ISSUE TITLE
get visibility from IOException when writing minidumps to crash report

### ISSUE THREAD

**Issue by willkg** [mozilla-mobile/android-components#11812]
Right now, we can't tell from the Socorro data whether a minidump failed to be created or whether the crash reporter failed to put the minidump into the crash report. 

Those are different situations that both result in an empty minidump in Socorro. Having an empty minidump is a helpful signal, so we should keep empty minidumps in crash reports. It'd be great to know more about _why_ the minidump is empty.

If the minidump in the crash report is empty because there was an IOException adding the minidump to the crash report--that would be good to know.

There's a crash annotation for capturing errors when writing minidumps (DumperError: https://searchfox.org/mozilla-central/source/toolkit/crashreporter/CrashAnnotations.yaml#289). Maybe we could reuse that?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19711)

**Comment by gabrielesvelto** [comment]
> There's a crash annotation for capturing errors when writing minidumps (DuperError: https://searchfox.org/mozilla-central/source/toolkit/crashreporter/CrashAnnotations.yaml#289). Maybe we could reuse that?

Yes! I think that's a great idea until we can make Fenix use the oxidized minidump writer (which will populate that annotation with more detailed errors).

**Comment by willkg** [comment]
Oh, hrm... I think we should use a different field, then. Otherwise downstream processing will be all like, "omg! the world is ambiguous and full of problems! everything is futile!"

Maybe `PayloadError` or `FenixFulfillFileFunctionFailure` ?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794911

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
