### ISSUE TITLE
Update deprecated Coroutines code

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1181]
We recently updated the Coroutines library and now we have a bunch of deprecated code. I assume that code will get removed once Kotlin 1.3 gets released and Coroutines are no longer experimental. So let's update that.

The biggest change seems to be that we need to scope Coroutines now.

Building the tree will show a bunch of warnings that we'll need to fix here, e.g.:

> w: components/browser/domains/src/main/java/mozilla/components/browser/domains/DomainAutoCompleteProvider.kt: (120, 37): 'CommonPool' is deprecated. Use Dispatchers.Default
> ...

**Comment by pocmo** [comment]
Coroutines 1.0 removes this deprecated code. So this is a blocker for updating Kotlin.

**Comment by grigoryk** [comment]
Remaining bits closed in #1281.
