### ISSUE TITLE
Have the `additional_note` from the context menu sticky

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#11829]
Issue seen on https://github.com/mozilla-mobile/focus-android/issues/6593

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19769)

**Comment by indurs** [comment]
Will work on this issue.

**Comment by indurs** [comment]
@Mugurell , I've submitted the PR for this issue.
