### ISSUE TITLE
Crash reporter prompt: Persist checkbox state

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1182]
I assume we want to persist the state of the checkbox ("[ ] Send crash report to Mozilla"). Currently it will always be [x] when showing the prompt.

**Comment by Shubhamurkade** [comment]
Hi @pocmo! I've got the code working for this issue. Would it be fine to issue a pull request?

**Comment by Amejia481** [comment]
Hi @Shubhamurkade!
Sure, send the PR!
