### ISSUE TITLE
Remove deprecated addResolveInfoForIntent

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#11832]
Breakout from https://github.com/mozilla-mobile/android-components/issues/11670.

`addResolveInfoForIntent` is deprecated since https://github.com/robolectric/robolectric/releases/tag/robolectric-4.2.

It is currently used in `AppLinksUseCasesTest` and `BrowsersTest` to mimic browsers being installed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19776)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795440

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
