### ISSUE TITLE
Add browser "engine" field to Telemetry

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#1184]
With several projects moving from WebView to GeckoView, it would be helpful to know which browser engine is in use.

Focus was tracking its browser engine by appending to the build ID at Telemetry initialization time, but this caused a cyclic dependency between Telemetry and Fretboard. This is because Fretboard now needs Telemetry initialized first to create the client ID. This episode made it clear that the browser engine should probably be available as a separate field in the core ping.

**Comment by pocmo** [comment]
I wonder if we could expose this as a "custom setting" like "default browser", "fretboard bucket", "search engine", etc.:
* https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/telemetry/TelemetrySettingsProvider.kt#L21
* https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L253

However if this will need its own field then we need to involve the telemetry/data team and update the schema first:
https://github.com/mozilla-services/mozilla-pipeline-schemas/tree/dev/schemas/telemetry

(CC @fbertsch)

**Comment by pocmo** [comment]
The `service-telemetry` is deprecated.
