### ISSUE TITLE
Remove deprecated fatal and non-fatal native code crash keys from GleanCrashReporterService

### ISSUE THREAD

**Issue by jamienicol** [mozilla-mobile/android-components#11912]
In #11908 we switched from counting fatal and non-fatal native code crashes, to counting crashes per process type (eg main process, foreground child process, and background child process). We kept the code for the fatal and non fatal keys, however, to allow some time for persisted data on disk to be submitted correctly.

We should remove the fatal and non-fatal keys after a short period of time.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19920)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793209

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
