### ISSUE TITLE
Use Store.waitUntilIdle in tests to wait for actions being consumed instead of shadowOf(getMainLooper()).idle()

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#11919]
Issue seen in https://github.com/mozilla-mobile/android-components/pull/11886#issuecomment-1076571298

Because [`Store` use a background thread for updates](https://github.com/mozilla-mobile/android-components/blob/ac74a577b68be269a7d86ed753d176d6d1c33a45/components/lib/state/src/main/java/mozilla/components/lib/state/Store.kt#L42-L44) tests should use [Store.waitUntilIdle](https://github.com/mozilla-mobile/android-components/blob/6c0fe91ab83614265f533b819bf406fc046b2227/components/support/test-libstate/src/main/java/mozilla/components/support/test/libstate/ext/Store.kt#L19-L26) to wait for all actions to be processed.

`shadowOf(getMainLooper()).idle()` added in https://github.com/mozilla-mobile/android-components/pull/11801 is not enough is these cases.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19949)

**Comment by csadilek** [comment]
Probably best to fix this on a case-by-case basis. Will close for now.
