### ISSUE TITLE
[Bug]: [a11y] BrowserMenuImageTextCheckboxButton item

### ISSUE THREAD

**Issue by bigConifer** [mozilla-mobile/android-components#11958]
See https://github.com/mozilla-mobile/fenix/issues/24560

For the Bookmarks Menu item with integrated Add/Edit button the `BrowserMenuItem` called `BrowserMenuImageTextCheckboxButton` is used (introduced in #9943).

However there is an accessibility bug, regarding the size of it's clickable areas.

If you click a little off the checkbox area (namely on the right, top or bottom of the checkbox) then the parent bookmarks menu item is clicked. 
That behavior is definitely not intended. 

If users want to open the bookmarks list they will only click on the left where the label "Bookmarks" is and never on the right where the "Add/Edit" button is located.

<p>
<img src="https://user-images.githubusercontent.com/64743731/161560722-4946a6ef-cef6-4f52-b3ad-f17295c3e6e5.jpg" width="45%" title="checkbox is clicked"/>
<img src="https://user-images.githubusercontent.com/64743731/161560877-34b1dd44-124d-4e5f-9728-695316f4557c.jpg" width="45%" title="menu item is clicked"/>
</p>

Solution would be to extent the clickable area of the checkbox to the top, bottom and outer right end of its parent element.
Therefore, also paddingEnd coming from [`@style/Mozac.Browser.Menu.Item.Container`](https://github.com/mozilla-mobile/android-components/blob/c00ccb20c40aebede334f0091ba4a145ccd883d9/components/browser/menu/src/main/res/values/style.xml#L25) has to be removed for the [`mozac_browser_menu_item_image_text_checkbox_button`](https://github.com/mozilla-mobile/android-components/blob/main/components/browser/menu/src/main/res/layout/mozac_browser_menu_item_image_text_checkbox_button.xml) layout.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20048)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795115

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
