### ISSUE TITLE
Crash notification for background child process crashes opens crash prompt when clicked

### ISSUE THREAD

**Issue by jamienicol** [mozilla-mobile/android-components#11954]
In #11872 we made it so that background child process (eg GPU process) crashes show the crash notification. I didn't notice at the time, but @cpeterso has raised the point that clicking on the notification itself (rather than the "report" button in the notification) will open the crash prompt.

The crash prompt currently isn't suitable for background child process crashes.
* Its title says "Sorry. Firefox had a problem and crashed.". Instead of "Sorry. A problem occurred in Firefox." which we use for the notification when it's a background process.
* It has a "close" and "restart firefox" button. But we don't want to restart firefox here.
* It hides the browser before showing (by using `FLAG_ACTIVITY_CLEAR_TASK`).

We could make the notification not-clickable so that the unsuitable prompt is never shown. But I think that may be confusing to users why sometimes notifications are clickable and sometime they are not. So I think we should instead address these issues.

We could additionally then just use the prompt instead of preferring to use the notification - that might result in more crashes actually being submitted.

cc @csadilek @agi @rocketsroger

**Comment by jamienicol** [comment]
If we fix the issues with the dialog described above then it would look like this:

![image](https://user-images.githubusercontent.com/1907488/161538754-4f943533-ff6a-4b16-b361-a54e46464128.png)

Which I think is an improvement for the time being.

**Comment by csadilek** [comment]
@jamienicol ah good catch! I agree with changing the text of the dialog in case the user just clicks on the notification (instead of clicking on report), but wouldn't we want to keep the notification as well though? Otherwise, we wouldn't notify users of background crashes until the next time they switch the app to the foreground, which may never happen e.g., the next time they use the app could be via a cold start and we wouldn't show the dialog anymore.

/cc @rocketsroger @agi

**Comment by jamienicol** [comment]
I hadn't considered crashes while we're in the background. That's a good point.

The behaviour with #11955 isn't actually to only show the prompt when they switch the app to the foreground. It actually shows the prompt immediately even if the application is already in the background. This is also the case for current nightly for parent process crashes (on SDK < 29. 29 and later we always show the notification).

It might be a bit annoying to the user to interrupt them using a different app to tell them Firefox has crashed. Perhaps `shouldShowNotificationInsteadOfPrompt()` should always return `true` if the app is in the background. Do we have a way to detect whether we are in the foreground or background? (This might be tricky for parent process crashes...)

**Comment by jamienicol** [comment]
Ah, and on SDK > 29 we indeed cannot show the prompt while in the background. For fatal crashes we therefore choose to show the notification, but with my patch in 11955 we don't for GPU process crashes. The prompt is indeed shown when you next open the app, but that may not be reliable..

So does `shouldShowNotificationInsteadOfPrompt()` need to simply return `sdkLevel >= NOTIFICATION_SDK_LEVEL`. If we're on a recent SDK then it doesn't matter whether the crash is fatal or not. If the app is in the background we cannot show the prompt (and fatal crashes are always in the background, whereas other types just _might_ be.)

Making that change would mean the user always sees either the prompt or notification immediately. But wouldn't solve the problem of the prompt potentially interrupting them whilst using a different app.. but perhaps that's not a concern, since it already occurs on release for fatal crashes

**Comment by cpeterso** [comment]
Fenix's current user experience for crashes in utility processes like the GPU process is pretty bad. When I enter `about:crashgpu` in Fenix Nightly today:

* The current tab reloads. This seems like a good thing.
* But then I see *three* notifications in the Android status bar:
 1. One that says "Sending crash report to Mozilla", shows a progress bar, and then disappears. Does this automatically submit a crash report? Is crash report auto-submission opt-out on Nightly? Do you know if that will happen in Beta and Release?
 2. One that says "Sorry. Firefox Nightly had a problem and crashed". Tapping this one appears to do nothing. Eventually it disappears when the "Sending crash report to Mozilla" notification disappears.
 3. One that says "Sorry. A problem occurred in Firefox Nightly" and doesn't disappear automatically. Tapping this one shows a bigger "Sorry. Firefox Nightly had a problem and crashed" dialog asking me if I want to "Restart Firefox Nightly".

**Comment by csadilek** [comment]
> It actually shows the prompt immediately even if the application is already in the background. 

Right, yes, for Android <= 9, where that's still allowed, so not what we want going forward anyway.

> It might be a bit annoying to the user to interrupt them using a different app to tell them Firefox has crashed

Exactly, yes. When the app is in the background the notification is preferred.

> So does shouldShowNotificationInsteadOfPrompt() need to simply return sdkLevel >= NOTIFICATION_SDK_LEVEL?

I was about to propose moving your background child check below the SDK check:

```kotlin
return when {
  // We can always launch an activity from a background service pre Android Q.
  sdkLevel < NOTIFICATION_SDK_LEVEL -> false

   // We always want to show the notification for background child process crashes.
  crash is Crash.NativeCodeCrash && crash.processType ==
                    Crash.NativeCodeCrash.PROCESS_TYPE_BACKGROUND_CHILD -> true

  ...
```

I think it's fine to show the prompt if the user just clicks on the notification and foregrounds the app, as long as the notification has the new text and actions implying that it wasn't fatal.

This seems to be the fastest path forward, and we can review all combinations of crash notifications again separately.

**Comment by jamienicol** [comment]
Okay, so Ill adjust the prompt to use the same title as the notification for background crashes, and remove the "restart" button. @csadilek should I also remove the `FLAG_ACTIVITY_CLEAR_TOP` flag for background crashes? It's quite jarring for the browser to be hidden when you click on the notification to open the dialog.

And I'll make the change you suggested to `shouldShowNotificationInsteadOfPrompt()`.

**Comment by csadilek** [comment]
> should I also remove the FLAG_ACTIVITY_CLEAR_TOP flag for background crashes?

@jamienicol Yes, tested this now, that's a great idea!

**Comment by csadilek** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/11955.
