### ISSUE TITLE
Investigate supporting opening links in PWAs and TWAs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#11975]
This was reported in https://github.com/mozilla-mobile/android-components/issues/7477#issuecomment-1084651226 as a followup to tapping on PWAs notifications.

Tested in Chrome and it seemed to work even with the browser / pwa closed so we might need https://bugzilla.mozilla.org/show_bug.cgi?id=1763784

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20110)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795114

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
