### ISSUE TITLE
Thumbnail storage should support synced tabs. 

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/android-components#11971]
[Fenix #24177](https://github.com/mozilla-mobile/fenix/issues/24177) introduced a synced tab card on the home screen. The design includes a thumbnail for the synced tab.

Currently, the `ThumbnailStorage` relies on a tab ID to retrieve thumbnails from storage. Synced tabs, however, don't have IDs as the IDs are generated randomly by default. 

There should be a way to map a synced tab to a thumbnail, so that the following works:
- User is shown a synced tab on home for the first time
- Favicon is displayed since the page has not been visited locally
- User clicks synced tab and is opened locally
- The synced tab on home can then correctly display a thumbnail

This could probably be done on the Fenix side by mapping a synced tab to a local tab, but IMO it makes sense to add this behavior to A-C in case synced tabs ever require thumbnails anywhere else.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20102)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794229

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
