### ISSUE TITLE
The Play/Pause button does not remain displayed on the media notification

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/android-components#11990]
**Steps to reproduce**
1. Go to a website with audio content.
2. Play the audio stream.
3. Invoke the notifications bar.
4. Tap the Pause/Play button several times from the media notification.
5. Observe the media notification.

**Expected behavior**
The Play/Pause button should remain displayed on the media notification.

**Actual behavior**
After tapping on the Play/Pause button for several times, it disappears from the media notification. Playing/pausing the audio stream from the application, will restore the Play/Pause button on the media notification.

**Device information**
Android device:
Huawei MediaPad M2 (Android 5.1.1) - reproducible constantly;

https://github.com/mozilla-mobile/focus-android/issues/6758

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20131)

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox RC 101.2.0 and was unable to reproduce it.
### Devices used:
- Huawei MediaPad M3 (Android 7)
- OnePlus 6T (Android 9)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795113

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
