### ISSUE TITLE
Bug 1486879

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1199]
* Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1486879
* Fire TV: https://github.com/mozilla-mobile/firefox-tv/issues/1374

**Comment by athomasmoz** [comment]
Checking in on this one. Is it scheduled for an upcoming version?

**Comment by pocmo** [comment]
@athomasmoz Right now we do not implement the API mentioned in the bug. So component users should not be affected by it at that time.

**Comment by mcomella** [comment]
@pocmo I disagree: please see the Bugzilla issue.

**Comment by Amejia481** [comment]
See https://github.com/mozilla-mobile/android-components/pull/1636
