### ISSUE TITLE
Reference browser: Support private browsing

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1202]
https://github.com/mozilla-mobile/reference-browser/issues/26

**Comment by pocmo** [comment]
There may be a bunch of things missing: Let's use this issue to try to add private browsing and find missing pieces in our components.

**Comment by Amejia481** [comment]
For what I could find to support private browsing, we need to:

1. Add support for private browsing in WebView, not allowing to store history, cookies, and autofill.
2. Add support for private browsing in UI for tabs and Tray.

We can break down this issue.

If I missed something please let me know!

**Comment by pocmo** [comment]
> Add support for private browsing in SystemEngine(WebView), not allowing to store history, cookies, and autofill.

This issue already exists: #649

Please do not work on this in this sprint though: We won't need private mode in the reference browser. I'm going to remove the WebView flavor from it soon.

> Add support for private browsing in tabs and Tray.

You mean in `feature-tabs`?

**Comment by pocmo** [comment]
@Amejia481 I guess we can close this now since we are tracking this as user story and breaking this down in the ref browser repo, right?

**Comment by Amejia481** [comment]
👍
