### ISSUE TITLE
Deprecate or remove TWA intent processor

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#12024]
We do not support TWAs and that [has not changed for a while](https://github.com/mozilla-mobile/fenix/issues/19189#issuecomment-923616755), so let's remove the intent processor and any other references for now. If we need to bring it back, we always can.

cc: @mcarare

**Comment by mcarare** [comment]
IMO we should deprecate it and remove usages from Fenix.

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/android-components/pull/12039.
