### ISSUE TITLE
Support reverse landscape orientation for fullscreen videos

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#12034]
Needed to support https://github.com/mozilla-mobile/fenix/issues/24678

@indurs posted in https://github.com/mozilla-mobile/fenix/issues/24678#issuecomment-1103534104
> to play the video both in landscape and landscape reverse, when auto rotate is disabled we can use 
> 
> ```
> activity.requestedOrientation =
>                     ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE
> 
> ```
> instead of 
> ```
> activity.requestedOrientation =
>                     ActivityInfo.SCREEN_ORIENTATION_USER_LANDSCAPE
> ```
> 
> in MediaSessionFullscreenFeature
> https://github.com/mozilla-mobile/android-components/blob/62fe384048d6c4048c0ddd60befa1158774b3589/components>/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt#L55

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20228)

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?
