### ISSUE TITLE
intl.accept_languages are not persisted after restart when updated from about:config

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#12046]
Related to BZ-1765375, when Fenix is restarted, the `intl.accept_languages` is overridden from the value set `about:config`. This might be because we are always taking the system or user set language and ignoring what is GV settings first.

My suspicion is that we don't want to suporrt about:config in this way as we do other things, so updating the `intl.accept_languages` does not send the updates back to the embedder to know about it. We should still investigate to verify that is the case.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20241)

**Comment by shtstorm** [comment]
Another pref, `intl.locale.requested`, follows system languages without a way to have it changed persistently. Both, it and `intl.accept_languages`, contribute to wrong language UI presented on sites (e.g. tiktok.com) and fingerprinting.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795441

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
