### ISSUE TITLE
Reference browser: Make toolbar scroll away automatically

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1205]
https://github.com/mozilla-mobile/reference-browser/issues/31

**Comment by pocmo** [comment]
Also see Focus which has a Nested*View implementation for WebView and GeckoView.

**Comment by pocmo** [comment]
Re-open: The commit message says "Closes" but there should be change needed in the refernece browser repository too.

**Comment by Amejia481** [comment]
https://github.com/mozilla-mobile/reference-browser/pull/173
