### ISSUE TITLE
Create a SyncStore

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/android-components#12065]
With the increased desire to surface sync features, it's become apparent that the current sync implementation has a level of complexity that may make it difficult to iterate quickly. Additionally, the current implementation does not match the architecture as defined in `lib-state`.

Create an additional `Store` that can abstract the sync mechanisms and data. This should include things like:
- authentication state
- state of various sync engines, including most recent data
- actions that can trigger authentication state changes as well as initiate syncs

This should lead to the following benefits:
- simpler API surface for sync features
- easier to change underlying sync implementation, since there will be an overlaid abstraction
- matches desired architecture

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20295)

**Comment by jonalmeida** [comment]
What we spoke about on https://github.com/mozilla-mobile/fenix/pull/24894 is to allow for an easy migration of existing features to a store without breaking functionality. Which can do with the following steps:

Currently we have observers that register via `SyncAccountObserver`, `DeviceConstellationObserver`, or `AccountObserver`:

```mermaid
flowchart TD
A[Observer B]-->B[FxaAccountManager]
C[Observer A]-->B[FxaAccountManager]
```

We can introduce a SyncStore that registers for all of these observers and dispatches the state updates to the store:
```mermaid
flowchart TD
A[Observer B]-->B[FxaAccountManager]
C[Observer A]-->B
D[Sync Store]-->B
```

Individually, we can start migrating features to observe the store within their integrations and give opportunity to find and fix bugs in the new store model as they turn up:
```mermaid
flowchart TD
B[FxaAccountManager]
A[Observer B]-->D
C[Observer A]-->D
D[Sync Store]-->B
```

(Optionally) remove the observer pattern and have each part of the account manager dispatch store updates directly in that place.

(no diagram)

**Comment by MatthewTighe** [comment]
My initial thinking was to create a `Middleware` that would act as an observer and interactor with `FxaAccountManager`. There will likely be a need for several of these middlewares to capture the full sync state:
- `FxaAccountManager`
- Various `SyncableStore`s
- `SyncManager`

Any thoughts on that approach?

I think we should hold off on the optional, third part of the plan detailed above until Fenix and A-C have migrated away from directly interacting with the account manager, as removing existing behavior would require a larger migration.

**Comment by jonalmeida** [comment]
> My initial thinking was to create a `Middleware` that would act as an observer and interactor with `FxaAccountManager`. There will likely be a need for several of these middlewares to capture the full sync state:
> 
>     * `FxaAccountManager`
> 
>     * Various `SyncableStore`s
> 
>     * `SyncManager`
> 
> 
> Any thoughts on that approach? This would also introduce the possibility of doing these separately. We could introduce account state the the SyncStore as a first step, for example, and then even test the approach in Fenix if we wanted to.

A middleware observes the incoming actions and then alters or performs side-effects based on the incoming - what part of the code would be firing the incoming actions for your middlewares to observe?

> I think we should hold off on the optional, third part of the plan detailed above until Fenix and A-C have migrated away from directly interacting with the account manager, as removing existing behavior would require a larger migration.

Yes, the optional step is only after all our consumers are no longer observing the account manager directly. I'm largely describing the same process we followed for [migrating from SessionManager to BrowserStore](https://mozac.org/2019/09/02/browser-state.html) which seems to be quite similar here.

**Comment by MatthewTighe** [comment]
> A middleware observes the incoming actions and then alters or performs side-effects based on the incoming - what part of the code would be firing the incoming actions for your middlewares to observe?

That's totally correct, thanks for the reminder. I was thinking in terms `Middleware`'s persistence responsibilities and thought registering them as observers might be a similar usecase. I can see how it isn't, though, and agree it would be best for the various items above to dispatch actions directly to the store.

**Comment by jonalmeida** [comment]
The middlewares would make a lot of sense in Fenix though, maybe Fenix want to observe actions in the account manager and then react to those, e.g. when the account is authenticating, push would want to know when to do certain registrations as well.
