### ISSUE TITLE
Add 20px close icon

### ISSUE THREAD

**Issue by sarah541** [mozilla-mobile/android-components#12096]
https://www.figma.com/file/ujdiReypSypu2GhRgzArea/branch/SoVHeGS5UR99B7qFX1c8eK/Android-Components?node-id=2124%3A12124
<img width="819" alt="Screen Shot 2022-05-03 at 3 03 10 PM" src="https://user-images.githubusercontent.com/29518411/166524375-7e938216-f9cf-4e30-913f-677a745ea205.png">

**Comment by gabrielluong** [comment]
This should be adding 20x20 version not removing the 24x24 one.
