### ISSUE TITLE
Add option to log telemetry events

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#121]
Original issue: https://github.com/mozilla-mobile/telemetry-android/issues/55

> When writing new events or debugging issues it would be helpful to read events in the debug log. There's already the DebugLogClient() but pings are delayed and harder to read than a single event.

**Comment by dector** [comment]
Is this issue still valid (considering Glean replacement)?

**Comment by pocmo** [comment]
🔥
