### ISSUE TITLE
Set default screen orientation if playing media in pip

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#12118]
Not locking the device to landscape would allow a smooth transition when exiting pip.

For context:
- https://github.com/mozilla-mobile/fenix/pull/24951#issuecomment-1116967299
- https://github.com/mozilla-mobile/fenix/pull/24951#discussion_r863529214

We should check for any race conditions that would prevent setting this orientation and make sure that changing screen orientation while in pip would not cause any issues in the pip window.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-20399)

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

**Comment by indurs** [comment]
@Mugurell , while testing the fix for this issue, I noticed that full screen media cleanup is not performed when the user navigates away from the pip mode to the activity in the following scenarios
- when the user navigates from a shortcut 
- when a link is shared to fenix from focus 
- when a page is shared to fenix from focus 
- when voice search is performed from search widget 
Can we invoke the exitFullscreen usecase in handleNewIntent() of HomeActivity before any intent processor is called?

```
if(components.core.store.state.findActiveMediaTab() !=null){
            lifecycleScope.launch(IO) {
                var tab = components.core.store.state.findActiveMediaTab()
                components.useCases.sessionUseCases.exitFullscreen(tab!!.id)
            }
        }
```
Do we need to create a different issue in fenix to fix this issue?

**Comment by Mugurell** [comment]
I'm not sure what's the actual bug in those scenarios.
If the app is left in a bad state then yes, this warrants a ticket filed for this bug with a video showing the issue.

**Comment by indurs** [comment]
@Mugurell , submitted a draft PR for this issue. But I see this message "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." Could you please let me know what to do? Thank You

**Comment by Mugurell** [comment]
> But I see this message "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." Could you please let me know what to do?

Seeing that in the meantime you pushed again I'm curious if this is still happening.
Not sure where that message appears and haven't seen it for myself but I'd say that just rebasing on `main` pushing again (with `-f`) should probably help.

**Comment by indurs** [comment]
I didn't see any error message when I pushed from Github desktop. But I'm seeing the message in github site. 

<img width="1792" alt="Screen Shot 2022-05-16 at 4 21 51 PM" src="https://user-images.githubusercontent.com/12825812/168577841-ccf82540-ce6f-4193-8aa5-a2a9d553c8d5.png">

**Comment by Mugurell** [comment]
Saw it.
Seems to be a Github quirk.

`https://github.com/mozilla-mobile/android-components/pull/12169/commits/d9a02f1da2232099ebfa54183b235d3acf8bc987` - https://github.com/mozilla-mobile/android-components/pull/12169/commits/d9a02f1da2232099ebfa54183b235d3acf8bc987

 will actually shown and open 

`https://github.com/mozilla-mobile/android-components/commit/d9a02f1da2232099ebfa54183b235d3acf8bc987`

The `/pull/12169` part seems to be lost. 
Seems like this is happening for other commits from other PRs also so this should not prevent merging or cause other similar problems.

**Comment by indurs** [comment]
Sure. Thank You !!

**Comment by Mugurell** [comment]
PR merged. To be verified downstream.
