### ISSUE TITLE
Add facts for Address Autofill Feature

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#12132]
Needed for https://github.com/mozilla-mobile/fenix/issues/24857.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20422)

**Comment by gabrielluong** [comment]
Closing this since it has landed and adding this to the list of things to QA in https://mozilla-hub.atlassian.net/browse/QA-1528
