### ISSUE TITLE
Corrrect README.md file for ui-icons component dependency

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1214]
In  [ui-icons component README.md file](https://github.com/mozilla-mobile/android-components/blob/master/components/ui/icons/README.md) the gradle dependency is incorrect.

WRONG ❌ 
`implementation "org.mozilla.photon:ui-icons:{latest-version}"`

Must be 🔵 
`implementation "org.mozilla.components:ui-icons:{latest-version}"`

**Comment by pocmo** [comment]
Fixed by ed2e6fa4b03763ad1f37b1e396add8ac170476f6
