### ISSUE TITLE
Correct README.md file for ui-colors component dependency

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1215]
In  [ui-colors component README.md file](https://github.com/mozilla-mobile/android-components/blob/master/components/ui/colors/README.md) the gradle dependency is incorrect.

WRONG ❌ 
`implementation "org.mozilla.photon:ui-colors:{latest-version}"`

Must be 🔵 
`implementation "org.mozilla.components:ui-colors:{latest-version}"`

**Comment by Shubhamurkade** [comment]
I'm a newbie here. I would like to take up this task.

**Comment by pocmo** [comment]
@Shubhamurkade Alright! It's all yours. Please open a PR with the change. We do have some guides on contributing linked here: https://mozilla-mobile.github.io/android-components/contributing/
Please let us know if you have any questions.
