### ISSUE TITLE
CustomTabsToolbarFeature does not correct tint icons/text when no toolbar colour config provided

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#12155]
## Steps to reproduce
1. Send a CustomTabIntent _without_ any colour customizations.
2. Observe the back/three-dot icons.

## Expected Behaviour
They should be tinted to the default toolbar colour that we have.

## Actual Behaviour

| Focus | Fenix |
|------|-------|
| ![Screenshot_20220511_103514](https://user-images.githubusercontent.com/1370580/167885209-4dc4d4bc-c44b-43e6-aa1a-91e0a7fe8d4d.png) | ![Screenshot_20220511_103424](https://user-images.githubusercontent.com/1370580/167885301-c008759c-d498-438d-95b9-b61d59bd7aff.png) |

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20453)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796209

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
