### ISSUE TITLE
Investigate if migration interface is still needed in SearchMiddleware

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#12174]
Investigate if this [interface](https://github.com/mozilla-mobile/android-components/blob/2f5e16e73a686238f2ab2f624ac267048c6ffacd/components/feature/search/src/main/java/mozilla/components/feature/search/middleware/SearchMiddleware.kt#L40) is still needed.  Remove if not needed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20466)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794864

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
