### ISSUE TITLE
Add support for theme in Search Engine icons

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#12187]
Currently Search Engine icons are set when the search engine is created.  Add support so theme can be applied to the search engine icons if needed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20486)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796450

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
