### ISSUE TITLE
Expand toolbar when url changes

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#12215]
Issue seen on Firefox Focus in https://github.com/mozilla-mobile/focus-android/issues/7075 as it does not have a similar listener [as Fenix has](https://github.com/mozilla-mobile/fenix/blob/7ef036bd9c0c7f59e1862c267f802a1a3a74fc7f/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L871-L886) for when the url or the load request changes.

This being a common usecase and a general flow we'd want to enforce for all EngineView integrators it should be handled in A-C.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20531)

**Comment by indurs** [comment]
@Mugurell , can I work on this issue?

**Comment by Mugurell** [comment]
> @Mugurell , can I work on this issue?

Would be great to!
While this will probably not be a breaking change both Fenix and Focus will need to be updated to remove their own code addressing this scenario. Would you want to work on that also?

**Comment by indurs** [comment]
Sure. I'll also update Fenix and Focus

**Comment by indurs** [comment]
@Mugurell , do I need to create a  PR for Feniix and Focus seperately and mention this issue?

**Comment by Mugurell** [comment]
@indurs Opened https://github.com/mozilla-mobile/fenix/issues/25455 and https://github.com/mozilla-mobile/focus-android/issues/7140 to update the Fenix and Focus projects after this AC changes.

**Comment by indurs** [comment]
Thank You !

**Comment by Mugurell** [comment]
PR was merged, thank you @indurs .
Changes are to be tested on Fenix and Focus. Closing this ticket.
