### ISSUE TITLE
Consume SelectLogin and SelectCreditCard prompt requests on dismiss

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/android-components#12241]
Normally we always want to consume the `promptRequest` after finish using it, as it clears the store reference.

_Originally posted by @Amejia481 in https://github.com/mozilla-mobile/android-components/pull/12142#discussion_r873732264_

We want to avoid dismissing a prompt request without removing it from the content state. This happens in [`dismissCurrentLoginSelect`](https://github.com/mcarare/android-components/blob/c277fe7b61f75001f5b39c7206048123178cb0cb/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/LoginPicker.kt#L58) and [`dismissSelectCreditCardRequest`](https://github.com/mcarare/android-components/blob/c277fe7b61f75001f5b39c7206048123178cb0cb/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardPicker.kt#L94).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20580)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796340

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
