### ISSUE TITLE
FxA endpoint returning internal server error when getting keys

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#1225]
When the oauth flow is started with `wantsKeys=true`, we are now getting an internal server error.

This is caused by the presence of the `keys_jwk` parameter:
`&keys_jwk=eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6IktFTmMwc3lLeE5CTi1vdWZmTHl3YkhDQzFfVktlakJVdmVLbElXQ1FTaGciLCJ5IjoiMEJuTmNwaWxzUUk3TTJvU3BXVnJiX1ZqSVQ2NC1VeFlPdGNtOEhDYm4wdyJ9`

It can be reproduced by our FxA sample app.

/cc @eoger @rfk @vladikoff

**Comment by rfk** [comment]
I was able to reproduce, and by copy-pasting the OAuth URL into a normal browser window, to retrieve this error message from the browser console:

```
Error: "No key-bearing scopes requested"
```

We should probably show something better than "500 Error" on the FxA side here.  But you can work around this by requesting a key-bearing scope.  I'll see if I can put together a PR.
