### ISSUE TITLE
Use delegates for Login and Credit card pickers in PromptFeature

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/android-components#12257]
To decrease the long parameter list's size, we should use the delegate pattern for Login and Credit card pickers and their related callbacks, similar to [`shareDelegate`](https://github.com/mozilla-mobile/android-components/blob/main/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/share/ShareDelegate.kt).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20604)

**Comment by jonalmeida** [comment]
See also: https://github.com/mozilla-mobile/android-components/issues/10323
