### ISSUE TITLE
Intermittent UI test failure - mozilla.components.feature.prompts.PromptFeatureTest - User can stop further popups from being displayed on the current page

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#12256]
### Firebase Test Run:
https://treeherder.mozilla.org/logviewer?job_id=379668580&repo=android-components
### Stacktrace:
```
TEST: User can stop further popups from being displayed on the current page
  D/LifecycleMonitor: Lifecycle status change: android.app.Activity@485a9798 in: PRE_ON_CREATE
  D/LifecycleMonitor: Lifecycle status change: android.app.Activity@485a9798 in: CREATED
  D/LifecycleMonitor: Lifecycle status change: android.app.Activity@485a9798 in: STARTED
  D/LifecycleMonitor: Lifecycle status change: android.app.Activity@485a9798 in: RESUMED
FAILURE
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/588c2c465e5c95ddc924b014e4dd4afe5f367fd9

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20597)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794857

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
