### ISSUE TITLE
Correct query parameter for Sentry project URLs to the new format

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#12255]
For the new SDK, we need to change the URL format [here](https://github.com/mozilla-mobile/android-components/blob/0fba88005af33c60b6230a0acb73d44883674944/components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt#L56=):

Old: `$it/?query=$id`
New: `$it&query=$id`

This change would go nicely along with https://github.com/mozilla-mobile/fenix/issues/25183.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20594)

**Comment by maxslimb** [comment]
#12284
