### ISSUE TITLE
Notify crash reporter when loading search engines fails

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#12313]
In https://github.com/mozilla-mobile/android-components/issues/12304, we are seeing odd crashes around search engines. We should forward such crashes to the `CrashReporter` so that we can investigate the various ways.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20689)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796449

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
