### ISSUE TITLE
Uplift String.toShortUrl to support-ktx/utils

### ISSUE THREAD

**Issue by Alexandru2909** [mozilla-mobile/android-components#12368]
Based on [Fenix #22770](https://github.com/mozilla-mobile/fenix/issues/22770)

Refactor `String.toShortUrl` extension function into support-ktx/utils.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20770)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796379

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
