### ISSUE TITLE
Update components list on the website

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1236]
We should update our [components page][0] with all the new components we've built and list out the apps that are currently using a-c.

[0]: https://mozilla-mobile.github.io/android-components/components/

**Comment by jonalmeida** [comment]
## Browser
- [ ] engine-servo
- [ ] storage-memory

## Apps
Maybe just a line of what major component their using?
- [ ] Fire TV
- [ ] Echo Show
- [ ] Focus
- [ ] Lockbox
- [ ] Fenix?

## Services
- [ ] glean
- [ ] sync-login

## Library (new)
- [ ] crash
- [ ] dataprotect
- [ ] jexl

**Comment by grigoryk** [comment]
The root `README.md` should be the canonical documentation source of all the components we have. Use that as a reference when updating the website. Bonus points of making sure that list itself is up-to-date :lollipop:
