### ISSUE TITLE
Build with SDK for Android 13 / API 33

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#12378]
According to the [docs](https://developer.android.com/about/versions/13) has reached Beta 3, that "marks the [Platform Stability](https://developer.android.com/about/versions/13/overview#timeline) milestone, which means that Android 13 has reached final internal and external APIs and final app-facing behaviors".

We can try using 33 as `compileSdkVersion` to also be prepared for the upgrade of `targetSdkVersion`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20790)

**Comment by mcarare** [comment]
First bump in the road:

> We recommend using a newer Android Gradle plugin to use compileSdk = 33
> 
> This Android Gradle plugin (7.0.0) was tested up to compileSdk = 31

**Comment by cpeterso** [comment]
GeckoView bug to target Android API 33 (Android 13): https://bugzilla.mozilla.org/show_bug.cgi?id=1771343

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796353

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
