### ISSUE TITLE
SpocImpressionEntity relations warnings.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#12406]
Building with SDK 33 triggered this warning:

> SpocImpressionEntity.java:19: warning: spocId column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.

cc @Mugurell

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20829)

**Comment by Mugurell** [comment]
Code landed, closing the ticket.
