### ISSUE TITLE
Add API to concept-storage for autocompleting domains

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1241]
For (inline) autocompleting we need some kind of API where we pass the entered text to a component storage and get the best matching URL (frecency?) back (e.g. goo -> google.com; See Fennec). 

In our reference browser we currently only autocomplete popular domains from the `browser-domains` package here:
https://github.com/mozilla-mobile/reference-browser/blob/7c85233a6f848caea610205668e2a71aa081b41b/app/src/main/java/org/mozilla/reference/browser/browser/ToolbarIntegration.kt#L29-L38

@mhammond has implemented this for "sync-places" here:
https://github.com/mozilla-mobile/reference-browser/pull/28/files#diff-f57ff1e70c137a5bd652ab888ce5e95fR32

To fit this into our component architecture we want to move this behind the `concept-storage` interface so that we can have multiple implementations and not have a hard dependency.

We could think of moving the AutocompleteFilter implementation (query `concept-storage`, otherwise use `browser-domains`) into a feature component (storage? toolbar?). But for now we can just implement it in the fragment like in the linked PR.

**Comment by pocmo** [comment]
CC @grigoryk

**Comment by pocmo** [comment]
@grigoryk Oh, interesting! Yeah, a helper sounds good. That helper may be something for the provider implementation that looks at active sessions in the `SessionManager` too. Currently I just do a simple "contains" match on URL and title.

Should we break creating this helper out into a separate issue?

**Comment by grigoryk** [comment]
@pocmo filed #1279. For this ticket, I'll just do a very basic matcher.
