### ISSUE TITLE
Return nullable strings from the apis that return the bookmark GUIDs

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla-mobile/android-components#12413]
This is a follow-up to https://github.com/mozilla-mobile/android-components/pull/12300

In the above PR, we added exception handling for all the API places calls to prevent crashes on Errors.

However, in the case a catchable error happens in the retrieval of the bookmarks we return an empty string to the app, which is a smell. We should change those apis to return nullable strings, and have the consuming app handle the null value properly.

The APIs to change are the [`addItem`](https://github.com/mozilla-mobile/android-components/pull/12300/files#diff-c55dd5ad7d5f005e0f7c3137ed0b6a9257c9257d6c9916af2944eabd60a10307R124-R139) and [`addFolder`](https://github.com/mozilla-mobile/android-components/pull/12300/files#diff-c55dd5ad7d5f005e0f7c3137ed0b6a9257c9257d6c9916af2944eabd60a10307R154-R158) functions in that were modified in the PR mentioned above

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20852)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794914

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
