### ISSUE TITLE
The Play/Pause button should remain displayed on the media notification

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/android-components#12433]
The Play/Pause button does not remain displayed on the media notification

**Steps to reproduce**
Go to a website with audio content, like soundcloud.com.
Play the audio stream.
Invoke the notifications bar.
Tap the Pause/Play button several times from the media notification.
Observe the media notification.
**Expected behavior**
The Play/Pause button should is displayed on the media notification.

**Actual behavior**
After tapping on the Play/Pause button for several times, it disappears from the media notification.
Playing/pausing the audio stream from the application, doesn't restore the Play/Pause button on the media notification.
Playing/pausing the audio from a different app (like Fenix), restores the button on the Focus media notification until the user is using the Focus Beta Play/Pause button again.

This is the bug from Focus https://github.com/mozilla-mobile/focus-android/issues/7289
It happens the same thing in Fenix

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20904)

**Comment by ionutbedregeanu** [comment]
I had a discussion with @Mugurell and it seems that he already has a direction for this ticket, so I will assign this on him
