### ISSUE TITLE
Feature Request and Help: DNS-OVER-HTTPS setting in GeckoRuntimeSettings

### ISSUE THREAD

**Issue by Anatame** [mozilla-mobile/android-components#12458]
The option to configure DNS in about:config needs to be available in Gecko Runtime settings to set it programmatically.

Is there a way I can configure my geckoview to use specified DOH programmatically?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20952)

**Comment by Amejia481** [comment]
The source code of `GeckoRuntimeSettings` is outside of the domain of Android Component. It lives in the [GeckoView](https://mozilla.github.io/geckoview/) project please open a bug in [bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView), you could also start the discussion on https://chat.mozilla.org/#/room/#geckoview:mozilla.org.
