### ISSUE TITLE
Support breadcrumbs correctly in native crashes

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#12453]
Currently native crashes are reported on a different process.  Add mechanism to support breadcrumb reporting with native crashes.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20948)

**Comment by rocketsroger** [comment]
A good solution might be creating a persistent storage for breadcrumbs so we can retrieve it when reporting native crashes.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792898

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
