### ISSUE TITLE
Add wallpaper feature to A-C

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/android-components#12480]
Wallpapers were recently added to Fenix. They should be moved into A-C with more intentional API surfaces and abstractions, to make future additions to the feature easier.

See [WallpaperManager](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt) and [WallpaperDownloader](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/java/org/mozilla/fenix/wallpapers/WallpaperDownloader.kt) for some details on what should be included.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20979)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796351

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
