### ISSUE TITLE
Upgrade to Kotlin 1.7.10

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#12489]
https://kotlinlang.org/docs/whatsnew17.html

Note: This is currently blocked by Room. The latest version uses Kotlin 1.6.10: https://androidx.tech/artifacts/room/room-ktx/2.4.2. Building with Kotlin 1.7.0 results in errors in the DAO-generated code. 
The latest Room alpha uses 1.6.21.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20997)
┆Link To Issue: https://mozilla-hub.atlassian.net/browse/FNXV2-20997

**Comment by csadilek** [comment]
@mcarare 👀 looks like there's a new version https://androidx.tech/artifacts/room/room-ktx/2.4.3 using Kotlin 1.7.

**Comment by mcarare** [comment]
> @mcarare 👀 looks like there's a new version https://androidx.tech/artifacts/room/room-ktx/2.4.3 using Kotlin 1.7.

Yes, thank you! I already have the draft PR with that version. https://github.com/mozilla-mobile/android-components/pull/12566.

I will continue work on that after landing changes to the other libraries and Gradle upgrade.
