### ISSUE TITLE
Investigate a process to optimize SVGs in ui-icon

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#12502]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21008)

**Comment by jonalmeida** [comment]
We could use something like [avocado](https://github.com/alexjlockwood/avocado) to try and reduce the SVG files then validate that we aren't causing bug/glyphs in the icon when rendered.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795458

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by longsonr** [comment]
Isn't avocado for vector drawable files? Don't you want svgo?
