### ISSUE TITLE
Allow screen to turn off after media is stopped

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#12544]
Issue seen on Fenix - https://github.com/mozilla-mobile/fenix/issues/25041

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21121)

**Comment by Mugurell** [comment]
Cross-posting from https://github.com/mozilla-mobile/fenix/issues/25041#issuecomment-1193704896
> I think what we can try is exiting immersive and fullscreen mode when the media state becomes stopped this also removing FLAG_KEEP_SCREEN_ON.
But this becomes problematic in case of YouTube - Autoplay.
So maybe as a workaround we can delay exiting fullscreen and immersive mode after a timeout started when media is stopped.

cc @rocketsroger

**Comment by indurs** [comment]
Can we also try this way?
We've MediaSessionFullscreenFeature which also takes care of the full screen functionality. 
We can set/clear the FLAG_KEEP_SCREEN_ON flag in MediaSessionFullscreenFeature instead of the extension functions in Activity.

* MediaSessionFullscreenFeature will listen for any changes in the playback state and updates whether the device needs to be awake or not.  It can take care of setting and clearing the FLAG_KEEP_SCREEN_ON flag in window. 
* When the media is paused/stopped or reaches the end of the video(when Youtube - Autoplay is disabled) , MediaSessionFullscreenFeature will clear the FLAG_KEEP_SCREEN_ON so the device can go to sleep mode. 

```
override fun start() {
        scope = store.flowScoped { flow ->
            flow.map {
                it.tabs + it.customTabs
            }.map { tab ->
                tab.filter { it.mediaSessionState != null && it.mediaSessionState!!.fullscreen }
            }.ifChanged().collect { states ->
                processFullscreen(states)
                processDeviceSleepMode(states)
            }
        }
    }

```
```
private fun processDeviceSleepMode(sessionStates: List<SessionState>) {
        val activeTabState = sessionStates.firstOrNull()
        if (activeTabState == null || activeTabState.mediaSessionState?.fullscreen != true) {
            return
        }
        activeTabState.mediaSessionState?.let{
            when(activeTabState.mediaSessionState?.playbackState) {
                MediaSession.PlaybackState.PLAYING -> {
                    if (WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON and activity.window.attributes.flags != 0) {
                        return
                    } else {
                        activity.window.addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
                    }
                }
                else -> {
                    if (WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON and activity.window.attributes.flags == 0) {
                        return
                    } else {
                        activity.window.clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
                    }
                }
            }
        }
    }

```

https://user-images.githubusercontent.com/12825812/180800158-94a2b5d5-48c4-4ee1-99a3-836757fce8fe.mp4

**Comment by Mugurell** [comment]
> Can we also try this way?

LGTM.
Not sure we need to check the current flags though. Trying to update them would either succeed or be no-op without any issues?

**Comment by indurs** [comment]
You're right. Checking the flags is not necessary. Will update the code.

**Comment by indurs** [comment]
@Mugurell , while I was testing the changes, I was wondering why LayoutParams.FLAG_KEEP_SCREEN_ON is used in the enterToImmersiveMode and exitImmersiveModeIfNeeded methods in the Activity extensions. Does that flag need to be there for PWA when the display in manifest is FULLSCREEN? If so could you please suggest few PWA links that have FULLSCREEN mode set in their manifest.

**Comment by Mugurell** [comment]
Good catch with the `setAsImmersive`/ `exitImmersiveModeIfNeeded` methods!
I think them setting the `FLAG_KEEP_SCREEN_ON` flag was there for fullscreen videos, not PWAs.
In which case, if we set this flags from other parts of the code those extension methods would need to be refactored to not duplicate the functionality. 
And also prevent a bug from the scenario in which media stops and the new code removes `FLAG_KEEP_SCREEN_ON` but then "exitImmersiveMode**IfNeeded**" won't actually be exiting immersive mode.
This can be done in a second commit to have the changes easy to document now and follow later.

**Comment by indurs** [comment]
Sure, We'll just commit the changes for MediaSessionFullscreenFeature/MediaSessionFullscreenFeatureTest and leave the Activity as it is. But exitImmersiveModeIfNeeded won't exit the screen from immersive mode as you mentioned. We'll update the Activity and its testcases in the next commit. Will create a PR today for the MediaSessionFullscreenFeature changes today.
