### ISSUE TITLE
Remove or rename View.layoutDirection

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#126]
We do have an extension function for View.layoutDirection. Android Studio complains that this now conflicts with a synthetic extension. We may be able to just remove it in case it behaves like our implementation.

**Comment by ninad458** [comment]
This issue should be closed, since the above extension function I found at mozilla.components.support.ktx.android.view.View is unused.

**Comment by pocmo** [comment]
It may be unused in this repository (We should add tests for it..). But this doesn't mean that it is unused by consumers of the library.
