### ISSUE TITLE
Add permission string for "declarativeNetRequest" extension permission

### ISSUE THREAD

**Issue by Rob--W** [mozilla-mobile/android-components#12616]
I want to add the "Block content on any page" message for the "declarativeNetRequest" permission, as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1780747.

The API is disabled by default, until https://bugzilla.mozilla.org/show_bug.cgi?id=1782685 is resolved.

Ideally, to save efforts and divergence, the strings on Android should use the same message as on desktop.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21231)

**Comment by Rob--W** [comment]
Could this issue get the https://github.com/mozilla-mobile/android-components/labels/%3Cweb-extensions%3E label + be assigned to me?

**Comment by Amejia481** [comment]
> Could this issue get the[ <web-extensions>](https://github.com/mozilla-mobile/android-components/labels/%3Cweb-extensions%3E) label + be assigned to me?

Sure!
