### ISSUE TITLE
Sync work manager debounce should take engine set into account

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#12636]
Currently sync debounce in `WorkMangerSyncManager` does not take `customEngineSubset` into account.  This could cause an issue where the first sync request is with a smaller subset and the second sync request can be ignored even though we should still perform the second sync request.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21288)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794223

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
