### ISSUE TITLE
Sync debouncing should respect SyncEngines

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/android-components#12645]
Now that `syncNow` supports specifying sync engines, the debounce mechanism in the SyncManager should only debounce requests from the same engine. For example:

- Tabs sync is initiated
- Full sync is initiated with `debounce = true`

The full sync will now be debounced, even if the intention was to only debounce if a full sync had occured within the time out.

Each engine should be separately tracked so that it can be separately debounced, and full syncs should only be debounced if every supported engine has been debounced within the timer.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21284)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794234

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
