### ISSUE TITLE
syncNow debouncing should be configurable from the client call site.

### ISSUE THREAD

**Issue by MatthewTighe** [mozilla-mobile/android-components#12646]
With the increased focus on FxA accounts, it would make sense for a call to `syncNow` to be able to specify its debounce window. For example, a specific `syncNow` call might want to debounce to 5 or 30 seconds, rather than the full 5 minutes that is the current default.

Assuming this is completed after https://github.com/mozilla-mobile/android-components/issues/12645, then there could be debounced timers tracked for individual engines as well. For example, we may want to sync tabs every 5 seconds but only need to sync bookmarks every minute at most. Full syncs could be debounced if _any_ engine is outside the specified debounce window.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21283)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794222

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by rocketsroger** [comment]
Notes:
Investigation into if we should persist debounce time for each engine.
Update debounce time for each engine on sync success.
