### ISSUE TITLE
Cannot share images using Direct Share

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#12689]
When trying to share images using Android's Direct Share feature - https://developer.android.com/codelabs/android-direct-share the action fails with
> Caused by: java.lang.SecurityException: Permission Denial: opening provider mozilla.components.feature.downloads.provider.FileProvider from ProcessRecord{d075e90 23628:com.Slack/u0a227} (pid=23628, uid=10227) that is not exported from UID 10188

with potentially leaving the app in a bad state - saw that trying to share to Google Drive will result in an errors loop from which I could only get out by force closing the app.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21387)

**Comment by Bubu** [comment]
Thanks for opening the correspinding issue for this :).

**Comment by cketti** [comment]
My suggestion is to use `ShareCompat.IntentBuilder` from [AndroidX Core](https://developer.android.com/jetpack/androidx/releases/core). It contains code to work around this particular issue and will be updated in case future issues are identified.

**Comment by Bubu** [comment]
That sounds like a good idea for future refactoring, I won't have time to do work on that in the near future, so I'd leave that to the project maintainers.

**Comment by Mugurell** [comment]
Using `ShareCompat.IntentBuilder` seems like a welcome improvement.
@cketti Can you open a new ticket for this? I can also help with this.

@Bubu's fix resolves the problem for now so we'll land this in the meantime.
