### ISSUE TITLE
Set Padding only once in BrowserToolbar's Button and ToggleButton

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1270]
In both BrowserToolbar classes, we're re-setting padding twice, once here and then in the super.

We should fix this so that we can have a default padding for the Browser buttons while still making the padding optional in the Toolbar buttons.

**Comment by chikka** [comment]
@jonalmeida can i take this?

**Comment by chikka** [comment]
@jonalmeida  Thanks! I just want to confirm my understanding:

**Comment by jonalmeida** [comment]
@chikka sorry I missed your reply! 

>  I think we are already making sure null padding will be not set using

Oops, yes you're right. We're already null checking it, so this should be as easy as removing the `setPadding` call. :)

**Comment by chikka** [comment]
ok. will remove it and generate PR for it.
