### ISSUE TITLE
Awesomebar autocomplete may fail to show history suggestions

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#12711]
Issue seen in https://github.com/mozilla-mobile/fenix/issues/26687 and reported as intermittent.

Debugging I indeed saw cases in which the [getAutocompleteSuggestion from `ToolbarAutocompleteFeature`](https://github.com/mozilla-mobile/android-components/blob/19d85f964578a32f25f2c96226de48af52a56da0/components/feature/toolbar/src/main/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeature.kt#L38) will return null and so the app will show results from the shipped in domain providers.

My working theory is that the interrupted reads for history suggestions https://github.com/mozilla-mobile/android-components/blob/52e2fc78d6b1e6ea1ad977e47fb3d8e09e3792f0/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt#L57 are in a race with the autocomplete suggestions which use [the same `reader`](https://github.com/mozilla-mobile/android-components/blob/1b490c833c9935a250b7b4c1e29eb7f272d3e75f/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt#L154).

**Comment by rvandermeulen** [comment]
For 105, this will be in the Fenix 105.0b4 build.
