### ISSUE TITLE
Create component for showing browser context menu

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1272]
In the reference browser we want to show a context menu when long-pressing on web content:

For example:
* https://github.com/mozilla-mobile/reference-browser/issues/101 (Open Image In New Tab)
* https://github.com/mozilla-mobile/reference-browser/issues/100 (Download Link)
* https://github.com/mozilla-mobile/reference-browser/issues/104 (Download Image)
* https://github.com/mozilla-mobile/reference-browser/issues/103 (Share Image)

It's likely that we want to split this into multiple things:
* A `browser-contextmenu` component that can show a context menu with dynamic entries (like `browser-menu`) - with matching `concept-contextmenu` component.
* A `feature-contextmenu` component that sets everything up, that can add/customize some standard actions (see `feature-awesomebar` and providers)

**Comment by jonalmeida** [comment]
Taking a short stab at what the concept-contextmenu would look like after having worked on the Toolbar (feel free to ignore):
```kotlin
interface ContextMenuAction {
  // For an optional icon beside the text
  icon: Drawable? = null, 
  // Description of the optional icon
  iconDescription: String? = null,
  // Name of the context menu to display
  label: String,
  // If the context menu should be visible depending on some external factor (e.g. image instead of text)
  visible: () -> Boolean  = { true },
  // Click listener
  listener: () -> Unit
}
```

Still thinking about the `ContextMenu` itself.. 🤔

**Comment by pocmo** [comment]
It turns out that for the context menu it's more straight-forward to have an implementation like `feature-downloads` where we create the dialog inside the feature. With that we do not need a separate component and can still add options for customization. Other than components like `feature-toolbar` the context menu is used directly. I'll close this issue and fold it into #1386 which I'll move into the sprint instead.
