### ISSUE TITLE
Implement back (forward?) stack long-press component

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#1275]
In Firefox for Android, you can long press the back button to open the back stack to jump more than one entry in the past:

![screenshot_20181105-133501](https://user-images.githubusercontent.com/759372/48028372-2b72e600-e100-11e8-967f-6f493e780904.png)

This doesn't work in mobile Chrome and is a distinguishing factor for fennec: it'd be cool if we could bring it to our other mobile browsers, like Focus and Firefox for Fire TV, too. Mobile browsers can especially benefit from a back stack because of their lower processor power and limited network resources.

This functionality exists in Firefox desktop and Chrome desktop.

This is not motivated by a specific product ask but rather by me as a user wishing this existed in the browsers I use.

**Comment by mcomella** [comment]
For the feature request in the products' repos:
- https://github.com/mozilla-mobile/firefox-tv/issues/1465
- https://github.com/mozilla-mobile/focus-android/issues/3845

**Comment by pocmo** [comment]
I like that!

This implies that we expose the "history" of a `Session`. We do not have anything for that in `browser-session` and `browser-engine-*` yet.

* WebView has: WebView.copyBackForwardList()
* GeckoView has: ? I don't think there's anything yet?

**Comment by AmyYLee** [comment]
@pocmo I think we can do parody this function with Fenix long press back button like we do in Fennec. Are we able to style the view of this list in Fenix or is there an existing android component?

**Comment by pocmo** [comment]
Fenix has this feature now. I don't think we ended up building a component for this, but all the state is coming from AC.
