### ISSUE TITLE
Intermittent UI test failure - org.mozilla.samples.glean.pings.BaselinePingTest - validateBaselinePing

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#12776]
### Firebase Test Run:
https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.acacddb44ee28c64/matrices/5129477151601220277/executions/bs.9a7b91477bb24161/testcases/1
### Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.mockwebserver.RecordedRequest.getPath()' on a null object reference
	at org.mozilla.samples.glean.pings.BaselinePingTest.waitForPingContent(BaselinePingTest.kt:92)
	at org.mozilla.samples.glean.pings.BaselinePingTest.waitForPingContent$default(BaselinePingTest.kt:83)
	at org.mozilla.samples.glean.pings.BaselinePingTest.validateBaselinePing(BaselinePingTest.kt:125)
```
### Build: 
https://github.com/mozilla-mobile/android-components/commit/f2f208054e2039525d490557b5df1d3f26c16079

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21563)

**Comment by csadilek** [comment]
Same as https://github.com/mozilla-mobile/android-components/issues/11340.
