### ISSUE TITLE
[Bug] TransactionTooLargeException from "Open links in apps"

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#12804]
Issue seen on Fenix - https://github.com/mozilla-mobile/fenix/issues/27042
Seems like [queryIntentActivities from AppLinksUseCases](https://github.com/mozilla-mobile/android-components/blob/6431cfeee9987337ff9d9260f5a7ac6188bf6160/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt#L58) can throw this error.
Could not reproduce locally, the issue depends on the specific configuration of app and other installed apps on the device - with the functionality querying which of the currently installed apps have declared components with intent filters for the current url.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21614)

**Comment by csadilek** [comment]
@Mugurell can we close this?

**Comment by Mugurell** [comment]
> @Mugurell can we close this?

There is an open PR for catching the exception and avoid crashing - https://github.com/mozilla-mobile/android-components/pull/12807.
