### ISSUE TITLE
Gradle tasks output a deprecation warning for every module with a Software Component

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/android-components#12838]
Each time running `./gradlew` I see a few dozen of these corresponding to most modules:

> Configure project :browser-engine-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796654

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
