### ISSUE TITLE
Pontoon link in README is invalid

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/android-components#12849]
The link https://pontoon.mozilla.org/projects/android-l10n/ shows a `Page Not Found` error.

Perhaps this was moved to https://pontoon.mozilla.org/projects/firefox-for-android/?
@Delphine

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21677)

**Comment by Delphine** [comment]
Correct, this is the link to localize Firefox for Android (so, it contains both a-c and fenix strings).
[Focus for android](https://pontoon.mozilla.org/projects/focus-for-android/) would be another product using a-c strings - however the a-c strings live under the Firefox for Android link. 
Perhaps good to call both out?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796350

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
