### ISSUE TITLE
Upstream the CFR composable from Fenix

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#12855]
This would allow reusing it on other projects also.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21683)

**Comment by gabrielluong** [comment]
@Mugurell could you assign yourself to https://bugzilla.mozilla.org/show_bug.cgi?id=1796349 and close it? All AC PRs should just reference the Bugzilla equivalent going forward. Christian or myself will put out a PSA and add a mergify rule to enforce the naming.
