### ISSUE TITLE
Recommended pre-push hook fails without added shebang 

### ISSUE THREAD

**Issue by fice-t** [mozilla-mobile/android-components#12856]
Without adding `#!/bin/sh` to the top of the file, making a symlink from `.git/hooks/pre-push` to `../config/pre-push-hook` gives the following error:

```
$ git push
error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for (NULL) failed: No child processes
error: failed to push some refs to 'https://github.com/fice-t/android-components'
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21682)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796376

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
