### ISSUE TITLE
Update our tab prioritization algorithm to take in consideration uncommited data

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#12870]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1777506

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21696)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794852

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
