### ISSUE TITLE
When copy / pasting links Android 13 system notifications are overlapping the snackbars

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#12893]
Originally [reported](https://github.com/mozilla-mobile/focus-android/issues/7535) in the Focus repo, but it also affects Fenix.

The proposal would be to show confirmation snackbars only below Android 13. This change should be validated by UX / Product ?!

cc: @kbrosnan

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21733)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796355

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
