### ISSUE TITLE
Canceling the "Open in app?" displays an empty page

### ISSUE THREAD

**Issue by iorgamgabriel** [mozilla-mobile/android-components#12894]
## Prerequisites
Have Youtube, or Maps apps installed.

## Steps to reproduce
1. Go to Settings - Advanced, and enable the "Open links in apps" toggle.
2. Exit settings, and go to youtube.com, or maps.google.com.
3. On the "Open in apps?" tap on "Cancel".
4. Observe the page.

### Expected behavior
The page loads in browser, without issues.

### Actual behavior
The page is blank.

The original ticket from Focus https://github.com/mozilla-mobile/focus-android/issues/7777 
This bug was introduced with this pr https://github.com/mozilla-mobile/android-components/pull/12382

* Android device: all devices 
* App (fenix, focus, ...): focus
* App version: from 103 until present

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21732)

**Comment by Amejia481** [comment]
Should we also add test to [WindowTest](https://github.com/mozilla-mobile/android-components/blob/main/components/support/ktx/src/test/java/mozilla/components/support/ktx/android/view/WindowTest.kt)?

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796657

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
