### ISSUE TITLE
Upstream a way to get the previous visible fragment while always skipping the current one

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#12907]
On Fenix - https://github.com/mozilla-mobile/fenix/pull/27305 it was seen that it is possible to get into a situation where the current fragment has another one on top so a call to `NavController.previousBackStackEntry` would skip the one on top and return the current fragment. Which is not the previous fragment wanted.

This is a good helper to have in Android-Components which can then be shared to multiple projects.
When added it can be part of [support-ktx](https://github.com/mozilla-mobile/android-components/blob/main/components/support/ktx/README.md) module.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795470

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
