### ISSUE TITLE
Gradle: Enable parallel execution

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1291]
This is off by default and locally looks very promising.

According to the docs it requires tasks to be decoupled and I *think* this is the case here. But we should look more into what that actually means.

Anyhow, locally I see a more than 50% build time reduction: 6m, 22s -> 3m, 1s

**Comment by pocmo** [comment]
On taskcluster I hope to see:

* For single module builds (without module dependencies) in PRs there is probably no big improvement
* Modules with some module dependencies may build faster
* The sample browser depending on a lot of things should build a lot faster (and this one is the bottleneck currently)
* Releases where we build and test everything in one very long running task will hopefully be significantly faster too.

**Comment by pocmo** [comment]
On taskcluster building the sample browser still took 25 minutes. That's surprising.

**Comment by Dmitry-Borodin** [comment]
I investigated this problem for other project recently
The first step is always update gradle version and build tools version. It adds performance benefits for free. For other staff https://github.com/gradle/gradle-profiler - this tools generate nice traces with timings, so it's clear what exactly takes time.
Should I join working on this task to improve build time?

**Comment by pocmo** [comment]
@Dmitry-Borodin Yeah, help here is definitely welcome and very much appreciated! :)

**Comment by Dmitry-Borodin** [comment]
Which gradle task do we want to improve? The one takes 6m on your machine.
I've checked 
`  cleanup-tasks=["clean"]
  tasks=[":sample-browser:assembleGeckoBetaX86Debug"] `
With warm gradle daemon, and it takes only 30 seconds.  And it's good in parallelism.
[gradle-trace.zip](https://github.com/mozilla-mobile/android-components/files/2569880/gradle-trace2777244870883019233.zip)

For me only the initial setup was long. Is that an issue?

**Comment by Dmitry-Borodin** [comment]
Let's focus on some task to have measurable results.
Clean ":sample-browser:assembleGeckoBetaX86Debug" looks fast from profiling and by building from IDE as well.
Do you mean it should be fast without gradle daemon? Should we pick another task?

**Comment by pocmo** [comment]
In this issue I'm primarily interested in enabling `org.gradle.parallel=true`. However while I see improvements locally it didn't seem to have any impact on taskcluster.

**Comment by Dmitry-Borodin** [comment]
It is parallel already in master. I'm not sure what enables it by default - android plugin or recent gradle version, but just issuing ./gradlew :sample-browser:assembleGeckoBetaX86Debug - builds in 4 threads on my laptop (shown in terminal during build time).
org.gradle.parallel=false causing it to use only 1 thread. So it is on by default.

**Comment by Dmitry-Borodin** [comment]
While if something is unexpectedly slow, we can profile this task. But I need specific task (or flow) to profile, it doesn't make sense to profile everything...
