### ISSUE TITLE
Sample apps: Disable "release" build types

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1292]
We did that for the sample browser but not for the other sample apps. There's no need to build a debug and a release type for all of them.

**Comment by Shubhamurkade** [comment]
Hi @pocmo, Can I take this up?

**Comment by pocmo** [comment]
@Shubhamurkade Sure! Let us know if you have any questions.

**Comment by Shubhamurkade** [comment]
Thank you!
