### ISSUE TITLE
notifications for failed tasks on geckoview bump aren't working

### ISSUE THREAD

**Issue by jcristau** [mozilla-mobile/android-components#12920]
ac_taskgraph has code to send a notification to AC and geckoview developers when tasks fail on geckoview-bump PRs, however as far as I can tell this hasn't worked for a couple of years (e.g. it expects branch names that haven't been used since https://github.com/mozilla-mobile/relbot/pull/43).  Would it be OK to rip that out or should we try to fix/revive it?  (And if the latter, maybe only in the firefox-android repo?)

cc @JohanLorenzo @rvandermeulen

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21773)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796658

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
