### ISSUE TITLE
Fenix is crashing on private mode due to strict mode violation on android components.

### ISSUE THREAD

**Issue by sum20156** [mozilla-mobile/android-components#12943]
[SharedIds](https://github.com/mozilla-mobile/android-components/blob/main/components/support/base/src/main/java/mozilla/components/support/base/ids/SharedIds.kt#L88-L88) class accessing SharedPrefs on UI/Main thread. On debug build strict mode doesn't allow disk operation on UI/Main thread.

Solution:
1. Move disk operation on IO thread.
2. Suppress disk operation violations while accessing shared prefs and reset strict mode policy after the operation.

fenix crash issue: https://github.com/mozilla-mobile/fenix/issues/27293

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795459

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by sum20156** [comment]
@csadilek is it fixed?

**Comment by cadeyrn** [comment]
> is it fixed?

[BZ-1795459](https://bugzilla.mozilla.org/show_bug.cgi?id=1795459) is still open, so I guess no?

**Comment by csadilek** [comment]
@sum20156 The issue wasn't "closed". We're in the process of migrating our issue tracker to Bugzilla, and I moved the issue there. 

So the issue link is now: https://bugzilla.mozilla.org/show_bug.cgi?id=1795459
You can find more details in: https://github.com/mozilla-mobile/android-components/issues/12751
