### ISSUE TITLE
Target Android 13 (SDK 33)

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#12944]
The latest SDK apps can target is 33: https://developer.android.com/about/versions/13

See also related Android 13 [issues](https://github.com/mozilla-mobile/android-components/issues?q=is%3Aopen+is%3Aissue+label%3A%22Android+13%22.
)

Currently blocked on https://github.com/mozilla-mobile/android-components/issues/12378.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21807)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796348

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
