### ISSUE TITLE
Conceptualize/featurize domain autocompletion

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#1319]
For our toolbar we'd like to have multiple providers of auto-complete data. Currently `HistoryStorage` interface has a `getDomainSuggestions` method (landed in #1280), and we also have `browser-domains/DomainAutoCompleteProvider` which encapsulates two data sources - "shipped" and "custom" sets of domain, with logic to prioritize these data sources (use "custom" if available/configured, and "shipped" as a fallback).

Currently, autocomplete wiring and prioritization of autocomplete sources needs to happen at the application level.

If we describe a source of domains suggestions as a separate concept, we can implement source prioritization and autocompletion and source privatization logic within the `feature-toolbar` layer, which will operate over a set of DomainProviders. 

A `concept-domains` could describe a `DomainProvider::getDomainSuggestion(query: String): Result`, and we'll have four concrete implementations to begin with:
- browser-storage-sync
- browser-storage-memory
- custom domains
- shipped domains (these last two are the same except for the source on disk, so they'll share a base class)

The `feature-toolbar/ToolbarAutocompleteFeature` can have a single `addProvider` method which follows a builder pattern, with an order in which providers are added guiding internal source prioritization logic. Autocompletion glue can then live within the feature, and query configured domain providers.

These changes will be backwards compatible, as consumers don't have to use the new functionality. We can mark existing `DomainAutoCompleteProvider` as deprecated and remove it once we're confident existing users moved off of it. (I think there's just a single consumer currently). I don't think anyone's using `HistoryStorage.getDomainSuggestion` yet, so we can just move that method.

Questions/concerns:
- `browser-domains` has a concept of an "autocomplete source", which is used to distinguish between "shipped" and "custom" autocompletion results. The above plan suggests a potentially arbitrary set of autocomplete sources, without a globally defined set of all types of sources. As far as I can tell, we don't use this identifier for anything. It's plumbed and ignored in `ui-autocomplete/InlineAutocompleteEditText`.
  - Since it's the application that will be responsible for adding individual domain providers to the autocomplete feature, it can also name them.
  - `toolbarAutocompleteFeature.addProvider("coolProvider", provider)`.
  - If we'd like custom treatment of different autocomplete sources at the UI level, an application will be able to configure that:
   - `toolbarAutocompleteUiView.setAutocompleteSourceRules("customProvider", CustomProviderRules)`
- in the future, we're likely grow some kind of "blocked domains" functionality (e.g. #313). This might just plug in at the `feature` level (e.g. a "blocked list" to negate results from other sources). This needs more thought.

cc @pocmo @csadilek

**Comment by grigoryk** [comment]
We could also just expand existing `concept-toolbar` for now, instead of adding a new concept.

**Comment by grigoryk** [comment]
Going through this now, some further shuffling is required (moving bits and pieces out of concrete implementations and into `concept-toolbar`).

**Comment by grigoryk** [comment]
Took a first stab at this in #1321.

**Comment by csadilek** [comment]
@grigoryk idea looks good to me!

> We could also just expand existing concept-toolbar for now, instead of adding a new concept.

+1, I think that would be best to start with.

> browser-domains has a concept of an "autocomplete source"... As far as I can tell, we don't use this identifier for anything. It's plumbed and ignored in ui-autocomplete/InlineAutocompleteEditText

Focus is using it when sending telemetry: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L401

**Comment by pocmo** [comment]
> we don't use this identifier for anything.

It's used in telemetry (by Focus) to distinguish from which pool we autocompleted.

**Comment by grigoryk** [comment]
> It's used in telemetry (by Focus) to distinguish from which pool we autocompleted.

I've left `source` as part of a Result object (along with `url`), to make migrations easy. See #1321.
