### ISSUE TITLE
Port SyncManager from reference-browser

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#1320]
At some point soon, the [places library](https://github.com/mozilla/application-services/tree/master/components/places) will grow an ability to initiate a `sync` operation. That's likely to follow a pattern similar to one used for `logins` - `LoginsStorage::sync(SyncUnlockInfo): SyncResult`.

At the start of this, most likely we'll just expose a method to kick off sync in `concept-storage/HistoryStorage`. Over time, that's going to change as we can more data types (`BookmarkStorage`, etc).

At the very high level, we'd like data from other clients to appear locally as soon as possible, and for our data to be available to other clients as soon as possible. That means a few things:
- we want to be able to run sync in the background (while browser isn't running itself)
- we want to sync new upstream data as it becomes available
  - this could be push-driven at some point
- we want to sync up local data as soon as it's produced on the device - data type hooks
  - e.g. when a new bookmark is created, we can schedule a sync
- as a "catch all", we'd like to sync data periodically, on a reasonable schedule (once on launch, a few times per day in the background. this could be dynamically configurable over time to account for volume of local/remote data)

Concerns/questions:
- need to pick a scheduling mechanism. We can likely rely on `WorkManager` to abstract away lower-level scheduling logic, or drop down to `AlarmManager` or `JobScheduler` level ourselves if necessary.
- we'll have multiple types of data that can sync. Currently we just have `HistoryStorage`, but we'll have more. We need to have a good story around this. In Fennec, it's possible to sync only a specific data type, and we make use of that functionality throughout the UI for things like refreshing opened tabs on remote clients.
- this needs to play well with manually triggered syncs, because we'll always have those at the UI level.

For relevant background reading, some thoughts around scheduling sync when we were thinking about it in context of Mentat: https://discourse.mozilla.org/t/diary-so-when-do-you-sync-and-what-are-the-implications/25409

**Comment by pocmo** [comment]
> need to pick a scheduling mechanism. We can likely rely on WorkManager to abstract away lower-level scheduling logic, or drop down to AlarmManager or JobScheduler level ourselves if necessary.

+1. I think WorkManager is our best choice. There's some work needed to switch to Android X (#842). But I hope to make some progress there soon.

>  this could be push-driven at some point

When designing this consider supporting different push implementations; specifically we may want to support Amazon's Push Service at some point. There's an old issue about that: #283.

**Comment by grigoryk** [comment]
This worked happened in the reference-browser, and is "incubating" there. Let's port it when it's ready.

**Comment by grigoryk** [comment]
This happened in #2076.
