### ISSUE TITLE
(lib-crash) After simulating a non fatal crash ("about:crashcontent")  on GV and clicking return to the app gets a black screen

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1333]
This [video](https://drive.google.com/file/d/1vlsCtP4CVadFEI06Mgspt2OAjji3Cy80/view) shows the steps to replicate the issue

**Comment by pocmo** [comment]
@Amejia481 I'm going to add this to a user story and set it size to "S" here. If you disagree then please set it to something larger. :)

**Comment by Amejia481** [comment]
👍

**Comment by pocmo** [comment]
@Amejia481 Ah, I have an idea!

We do not recover from content crashes yet. See Focus here:
https://github.com/mozilla-mobile/focus-android/blob/5c6c0b54d2e33330879a59697a20876279a30e31/app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt#L384

That may fix the situation.

**Comment by Amejia481** [comment]
Thanks, let me take a look at it!

**Comment by Amejia481** [comment]
@pocmo you hit the nail on the head!  
This fix the issue, finally 🙌 !
