### ISSUE TITLE
Change namespace for custom XML attributes in BrowserToolbar to 'mozac'

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1336]
The awesomebar is currently using 'mozac' and the toolbar uses 'app'. I think that 'mozac' is more fitting for us to have.

The BrowserToolbar is the place in code where we retrieve the styles: https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt#L197-L213

**Comment by pocmo** [comment]
Afaik the code retrieving the styles doesn't care about the namespace. At least I can't remember defining "mozac" anywhere except in the XML where I use it.

**Comment by jonalmeida** [comment]
Interesting, some [smaller][1] [blogs][0] suggest you have to add it with the `xmlns` attribute, but I don't see that in our layouts like you said. 🤔 

[1]: http://jeffreysambells.com/2010/10/28/custom-views-and-layouts-in-android-os-sdk
[0]: http://myhexaville.com/2017/07/26/android-xml-namespaces/

**Comment by pocmo** [comment]
Yeah, when using the component in your layout. But afaik you can pick whatever namespace you want.

**Comment by jonalmeida** [comment]
TIL
