### ISSUE TITLE
Add components with strings to l10n.toml

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1338]
I just noticed that l10n.toml is not up-to-date. Let's fix that in preparation for getting translations for components. :)

While we are at this we could also start to document how we deal with strings.

**Comment by Pike** [comment]
Just came across this, too. And yes, test! I think a good test would do discovery and whitelist through `.buildconfig.yml` or `lib.build_config`, to make sure we're not hitting test strings, but only the strings of published libraries.

It'd be good to get this triaged to make sure we're not missing things rsn.

Please also CC me and @Delphine or @mozilla-mobile/l10n on issues like this.

**Comment by Pike** [comment]
PS: that gives the following components right now:

```
browser-engine-system
browser-errorpages
browser-toolbar
feature-contextmenu
feature-downloads
feature-prompts
feature-tabs
lib-crash
ui-tabcounter
```

which leave prompts, libcrash, and engine-system? Might be good to order l10n.toml as a ride-along.

I also think that a test could be split off into another issue.

**Comment by pocmo** [comment]
Agreed. I move this into our triage column for the next sprint. And filed a follow-up here: #1743
