### ISSUE TITLE
Fullscreen pages can be scrolled (because height of toolbar can be scrolled offscreen)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1339]
Our reference browser and sample browser have the same issue that is described in this Focus issue:
https://github.com/mozilla-mobile/focus-android/issues/3815

Let's investigate if we can find a solution for that.

**Comment by pocmo** [comment]
@Amejia481 Maybe something you want to investigate now that you are familiar with the Nested*View code? :)

**Comment by pocmo** [comment]
* In the Focus issue there's a discussion about trying to set scroll flags dynamically

* I recently asked the Pocket guys. They have a very nice implementation; they scroll the status and navigation bar away too though. Anyhow, they described their mechanism as:

![screenshot_2018-11-13 pocket-android mozilla slack](https://user-images.githubusercontent.com/89638/48418426-91d9b300-e755-11e8-9861-d1a08e2d0e8f.png)

**Comment by Amejia481** [comment]
Sure I'll take a look! 👍

**Comment by ekager** [comment]
FYI @Amejia481 I got WebView to work (with minimal testing) with this : 
https://github.com/ekager/focus-android/commit/09c0618918a0c2a3e022c6d89c62153a9c5c4767

Looks like we would need to ask for a similar GV method to get this to work across engines.

**Comment by Amejia481** [comment]
Awesome @ekager 💪 !

**Comment by pocmo** [comment]
Nice! 

> Looks like we would need to ask for a similar GV method to get this to work across engines.

You mean `canScrollVertically()`?

I assume `GeckoSession.shouldPinOnScreen()` doesn't help here?

**Comment by Amejia481** [comment]
@ekager I achieved the same behavior  by adding the same validation as your on`NestedWebView`.`onTouchEvent` without having to remove/add `scrollFlags` dynamically  

I barely tested, but so far is working pretty well.

```kotlin
 if(canScrollVertically(1)) 
     //continue with the implementation on NestedWebView.onTouchEvent
else
    return super.onTouchEvent(ev)

```
```kotlin
@SuppressLint("ClickableViewAccessibility")
    override fun onTouchEvent(ev: MotionEvent): Boolean {
        if(canScrollVertically(1)) {

            val event = obtain(ev)
            val action = ev.actionMasked

            if (action == ACTION_DOWN) {
                nestedOffsetY = 0
            }

            val eventY = event.y.toInt()
            event.offsetLocation(0f, nestedOffsetY.toFloat())

            when (action) {
                ACTION_MOVE -> {
                    var deltaY = lastY - eventY

                    if (dispatchNestedPreScroll(0, deltaY, scrollConsumed, scrollOffset)) {
                        deltaY -= scrollConsumed[1]
                        event.offsetLocation(0f, (-scrollOffset[1]).toFloat())
                        nestedOffsetY += scrollOffset[1]
                    }

                    lastY = eventY - scrollOffset[1]

                    if (dispatchNestedScroll(0, scrollOffset[1], 0, deltaY, scrollOffset)) {
                        lastY -= scrollOffset[1]
                        event.offsetLocation(0f, scrollOffset[1].toFloat())
                        nestedOffsetY += scrollOffset[1]
                    }
                }

                ACTION_DOWN -> {
                    lastY = eventY
                    startNestedScroll(SCROLL_AXIS_VERTICAL)
                }

                // We don't care about other touch events
                ACTION_UP, ACTION_CANCEL -> stopNestedScroll()
            }

            // Execute event handler from parent class in all cases
            val eventHandled = super.onTouchEvent(event)

            // Recycle previously obtained event
            event.recycle()

            return eventHandled
        } else{
            return super.onTouchEvent(ev)
        }
    }
```

**Comment by pocmo** [comment]
Do we have a follow-up issue for the GeckoView implementation (with API label?)

**Comment by Amejia481** [comment]
Yes it's the https://github.com/mozilla-mobile/android-components/issues/1392
