### ISSUE TITLE
Expose "session history" in Session

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1340]
Reference browser user story: https://github.com/mozilla-mobile/reference-browser/issues/69

To be able to render the "history" of a single `Session` we will need to expose this list in the `Session` itself.

Unclear is where this data should come from.

* WebView has [copyBackForwardList()](https://developer.android.com/reference/android/webkit/WebView#copyBackForwardList()).
* GeckoView doesn't seem to have anything like that yet.

**Comment by pocmo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1509110

**Comment by pocmo** [comment]
After discussing this with the GV team the consensus is that GV will provide APIs for:
* Getting the history list of a GeckoSession.
* Getting the current index (in the list) the session is at
* Navigating to a specific index (this is something we'd implement in a different issue)

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/firefox-tv/issues/1558

**Comment by cpeterso** [comment]
GV's History Stack API has landed in mozilla-central and should be in tomorrow's GV 68 Nightly build.

https://bugzilla.mozilla.org/show_bug.cgi?id=1509110

**Comment by bifleming** [comment]
@vesta0 this is still in the 'blocked' column on teh A/C sprint board... should it be moved? But is it post-MVP? we should take everything that is Post-MVP off of that board I think.

**Comment by jonalmeida** [comment]
This would be needed for supporting the tab history for sync'd tabs.

**Comment by jonalmeida** [comment]
This seems mostly for "read" access to the history stack, but we would need a way to add to it.
