### ISSUE TITLE
Kotlin: cancel(Throwable): Boolean is deprecated

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1342]
> w: /Users/skaspari/Projects/Mozilla/android-components/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt: (141, 26): 'cancel(Throwable? = ...): Boolean' is deprecated. Use CompletableDeferred.completeExceptionally(cause) or Job.cancel() instead
> w: /Users/skaspari/Projects/Mozilla/android-components/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt: (141, 26): 'cancel(Throwable? = ...): Boolean' is deprecated. Use CompletableDeferred.completeExceptionally(cause) or Job.cancel() instead
> ...

**Comment by dector** [comment]
Seems like not an issue anymore?

**Comment by pocmo** [comment]
:+1: Thanks
