### ISSUE TITLE
Kotlin: Experimental declaration (ObsoleteCoroutinesApi)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1343]
> w: /Users/skaspari/Projects/Mozilla/android-components/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt: (141, 26): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ObsoleteCoroutinesApi' or '@UseExperimental(kotlinx.coroutines.ObsoleteCoroutinesApi::class)'

**Comment by dector** [comment]
Seems like not an issue anymore?

**Comment by pocmo** [comment]
Correct!

And also someone fixed all the warnings :D
