### ISSUE TITLE
Add reader view feature component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1346]
Reference Browser User Story: https://github.com/mozilla-mobile/reference-browser/issues/152

For now we only need this for GeckoView. It's unclear whether GV would provide this functionality or whether we would need to do that ourselves. But even if we'd readermodify the current page we'd need some kind of API to mess with the page (inject JS).

**Comment by pocmo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1509257

**Comment by pocmo** [comment]
From https://github.com/mozilla-mobile/fenix/issues/74

> @snorp suggests that Reader View be implemented by A-C using a WebExtension to inject Readability.js as a content script.

**Comment by cpeterso** [comment]
@mbrubeck said he is investigating what we need to do for a Reader View extension in [GV bug 1509257](https://bugzilla.mozilla.org/show_bug.cgi?id=1509257).

**Comment by pocmo** [comment]
@cpeterso Nice, thanks! (cc @csadilek)

**Comment by csadilek** [comment]
Renamed this as we have an engine API now to install WebExtensions. We're trying to implement this without readerview-specific APIs, based on the generic messaging APIs implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1518843.

Moving into this sprint to prototype / make progress.

**Comment by cpeterso** [comment]
@pocmo You added the `blocked` label two days ago. What is Reader View blocked on? GV's new messaging API ([bug 1518843](https://bugzilla.mozilla.org/show_bug.cgi?id=1518843))?

**Comment by csadilek** [comment]
@cpeterso yes, we need the messaging API to complete the feature developed in: https://github.com/mozilla-mobile/android-components/pull/2273

**Comment by csadilek** [comment]
We have the feature component now which contains significant work and we decided to land it. However, Reader View can not yet be integrated and work will be continued in: 

- https://github.com/mozilla-mobile/android-components/issues/2243 (Engine API for web extension messaging)
- https://github.com/mozilla-mobile/android-components/issues/2623 (Appearance controls)
- https://github.com/mozilla-mobile/android-components/issues/2624 (Wire up messaging between feature and web extension)

See also the https://github.com/mozilla-mobile/android-components/issues/2005 (Meta: ReaderView)
