### ISSUE TITLE
Components with shouldPublish=false are not getting build at all anymore

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1348]
I just noticed that components with shouldPublish=false are not getting build at all anymore. 😨 

Now with `printModules` filtering those out for the release they are gone from **all** our decision tasks.

**Comment by pocmo** [comment]
@mitchhentges @JohanLorenzo @MihaiTabara I didn't notice that beforeö That's something we should fix as soon as possible! :)

**Comment by mitchhentges** [comment]
Oh, shoot, `shouldPublish` only applies to the release decision task.
Good catch Sebastian, I should've noticed that. I'll create a PR

**Comment by mitchhentges** [comment]
@pocmo I can't seem to get `:tooling-fetch-tests` building locally, even on its original commit.

If I do:
1. `git checkout 0271d0a3188ea6a424c06bf707b51b6fba156728`
2. `./gradlew clean :tooling-fetch-tests:lint`

I still get back the following linting errors:
```
  /home/mitch/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.50/be504b4901d75cbe129a178f5830e6c358ec214c/bcprov-jdk15on-1.50.jar: Error: Invalid package reference in library; not included in Android: javax.naming.directory. Referenced from org.bouncycastle.jce.provider.X509LDAPCertStoreSpi. [InvalidPackage]
  /home/mitch/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.50/be504b4901d75cbe129a178f5830e6c358ec214c/bcprov-jdk15on-1.50.jar: Error: Invalid package reference in library; not included in Android: javax.naming. Referenced from org.bouncycastle.jce.provider.X509LDAPCertStoreSpi. [InvalidPackage]
  /home/mitch/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar: Error: Invalid package reference in library; not included in Android: java.lang.management. Referenced from org.junit.internal.runners.statements.FailOnTimeout. [InvalidPackage]
```

**Comment by pocmo** [comment]
@mitchhentges Ah, yeah, I'll prepare a PR with a fix for that!
