### ISSUE TITLE
Use Case: Load URL in new tab

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#136]
See also: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/src/main/java/mozilla/components/feature/session/SessionIntentProcessor.kt#L25

**Comment by pocmo** [comment]
We should make this configurable in `SessionIntentProcessor`. There are some "one tab" browsers that would want to always re-use the existing session and never open a new tab.

**Comment by pocmo** [comment]
I'll land something for this as part of the tabs tray work. After that we can update the code that handles Intents. -> Moving to next sprint.
