### ISSUE TITLE
Improve lifecycle management of RustPlacesConnection (fix SQLiteBusy/PlacesConnectionBusy errors)

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#1369]
Follow-up to #1164. We need to establish a clear pattern for how shared resource like `RustPlacesConnection` should be managed. It may be used from an activity, from background jobs, etc. It's quite likely that we want to maintain just a single connection.

In sample browser's `BrowserActivity` we call `close` on the rust places connection from `onDestroy`, which is likely not correct for a number of reasons. To paraphrase @pocmo:
- Reading/Writing data is not limited to [an] activity (e.g. other activities, background jobs, ..). Is [close] only needs to be done if everything in this process is done with the storage?
- Activity.onDestroy() is not guaranteed to get called

**Comment by thomcc** [comment]
> - Activity.onDestroy() is not guaranteed to get called

Do you know under which circumstances it won't be called? Logins examples use this for cleanup.

**Comment by pocmo** [comment]
https://developer.android.com/reference/android/app/Activity#ActivityLifecycle

If you scroll down on that page a bit you'll get to a tablet with a "Killable" column. The last not "killable" method call is `onPause()` and then:
> for those methods that are marked as being killable, after that method returns the process hosting the activity may be killed by the system at any time without another line of its code being executed.

**Comment by csadilek** [comment]
There more I investigate and read about this, the more I think we need to change our design to rely on short-lived objects instead. If we opened a file or network connection we wouldn't keep any of those objects around either and expect them to be closed on a lifecycle event. Instead we'd recreate/reopen when needed.

With long-lived objects, I doubt this will ever be perfect i.e. there's always a chance we could be leaking memory or at least not properly closing resources. If we made it reasonably performant to create these objects, use them and copy/persist their state, then we could just rely on `.use` and they'd get closed right away.

We have the same problem with `FirefoxAccount` where it seem this pattern could already work? These long-lived object also consume memory and make it more likely for the app to get killed. So, it seems to me we should investigate avoiding this problem altogether.

Another way of arguing for this: We're already talking about moving `.close` to `onPause` which happens much more frequently. If it's fast enough to close these objects in `onPause` and recreate them in `onResume`, then it should be fast enough to close them right after usage and recreate them when needed. We just need to make we can persist/copy whatever state we need for the app.

Wdyt? It this unreasonable?

**Comment by thomcc** [comment]
> for those methods that are marked as being killable, after that method returns the process hosting the activity may be killed by the system at any time without another line of its code being executed.

This is fine, if the application is exiting then it's fine if things aren't cleaned up, since the OS will close files, terminate threads, release memory, etc. If the application is not exiting then the resources are heavyweight enough that they shouldn't be leaked, though.

> the more I think we need to change our design to rely on short-lived objects instead

This probably makes sense for things like FirefoxAccount, but probably not for a places connection, which is expensive to create and likely to be used very frequently (on every navigation, for example).

The only way to make it cheap to create an instance of it would be to cache the creation of the object, which maybe is the right call, but wouldn't reduce overall memory usage.

**Comment by grigoryk** [comment]
An important benefit of using multiple short-lived connections is that SQLite actually has isolation guarantees for operations that happen on different connections (with some caveats around use of shared cache and states of a few pragmas). This is particularly useful if we want to be able to clearly reason about something like sync and consuming application both operating over the same tables concurrently. https://sqlite.org/isolation.html

Orchestrating these connections is very straightforward at the application level, as well (wrap them in `.use` and you're done). This is more of a minefield for managing a long-lived resource.

Beyond that, we have regular concerns about the costs associated with these short-lived connections (creating them is expensive free, internal caches are invalidated, etc). These costs are likely too high for a few use cases - e.g. a performant awesomebar - but it'll be good to actually measure this in practice.

Here's where we stand, I think:
- we need to have a separate places connection for long-running operations which benefit from (require, even?) isolation guarantees, such as sync
  - to actually benefit from sqlite's isolation, all of the work sync does needs to be scoped to a single transaction. @thomcc can you confirm that's the case?
- a shared connection will improve peak memory usage, query performance and request latency
- most of the querying we'd like to do doesn't require isolation, and generally benefits from having the least amount of overhead possible. If we're already maintaining a shared connection, that's a natural fit
- lifecycle of a shared connection needs to be carefully considered (i.e. what this issue was initially about!)

As a concrete manifestation of this, in `feature-sync` work I'm going to land a change to `RustPlacesConnection` to allow creating "throw away" instances of `PlacesConnection` that serve a specific purpose (sync, whatever else), while also maintaining a cached connection which is suitable for general purpose querying work. Calling code will be responsible for cleaning up the throw away connections (wrap them in `.use` and call it a day).

Consumers of `RustPlacesConnection` will need to decide if they require an expensive throw away instance to do their work, or if they're fine using a shared instance. Pros/cons of each will be documented to help guide folks in making the right call.

Any improvements that makes creating instances of PlacesConnection cheaper, or increase query performance across connections, will benefits this split approach, and if they're significant enough we can move the needle further toward "single-purpose" connections. E.g., can we use SQLite's process level shared-cache mode to reduce memory/etc overhead of having multiple connections?

**Comment by grigoryk** [comment]
From a chat with @thomcc:
- history sync currently happens in a single transaction; a reserved lock might be taken earlier than necessary
- we'll need to deal with a SQL_BUSY regardless (a held exclusive or reserved lock will block writes from happening). A pretty lightweight strategy for that is to pump up the "busy" error from Rust and into PlacesConnection, and let consumers deal with it as appropriate. In practice, this will look like definitely retrying writes (we don't want to drop data on the floor), and maybe retrying reads, but less aggressively and with different latencies in mind. E.g. it's fine if a write of a visited URL takes a few seconds to complete, running on a separate thread; less clear what those requirements are for something like querying awesomebar.
- these busy errors should be rare, but will happen now and then, and likely to happen during a sync operation
- shared cache mode to be investigated more in our context

Relevant app service bugs: https://github.com/mozilla/application-services/issues/394 and https://github.com/mozilla/application-services/issues/395 (which we already do, just at a PlacesConnection level).

**Comment by grigoryk** [comment]
This is going to build on top of changes coming up in https://github.com/mozilla/application-services/pull/577
