### ISSUE TITLE
Update Engine's HistoryDelegate interface once GeckoView beta support is ready

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#1370]
Same as #1053 but for GV beta.

**Comment by pocmo** [comment]
Afaik this shouldn't require any work on our side: Once that moves in GV from Nightly -> Beta our component also makes the move Nightly -> Beta. Same for release.

**Comment by grigoryk** [comment]
But we would still need to add code to `browser-engine-gecko-beta`, `browser-engine-gecko-release`, right?

**Comment by pocmo** [comment]
I don't think we do (except stubbing when adding new APIs).

Currently we track:
* browser-engine-gecko-nightly -> 65
* browser-engine-gecko-beta -> 64
* browser-engine-gecko -> 63

On merge day what happens in the mercurial repositories is that:
* The state of mozilla-beta (64) becomes mozilla-release (64)
* The state of mozilla-central (65) becomes mozilla-beta (65)
* mozilla-central becomes 66.

We perform the same change (copying over the module code) in our repository when updating the major versions:
* The code of browser-engine-gecko-beta (54) becomes browser-engine-gecko (64)
* The code of browser-engine-gecko-nightly (65) becomes browser-engine-gecko-beta (65)
* browser-engine-gecko-nightly becomes 66.

Like GeckoView code "rides the trains to release" your code in the Nightly component code will ride the trains too. This will avoid that you need to keep track of all changes and re-apply them to beta/release at different times and end up with various inconsistencies.

When adding a new API to the gecko components you only need to:
* Add it to the channels where it is available: at least nightly (maybe beta or release)
* Stub it where it is not available (beta and/or release)

**Comment by pocmo** [comment]
Now after the merge day this should work with beta.
