### ISSUE TITLE
Add feature-prompts component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1379]
Supporting user story: https://github.com/mozilla-mobile/reference-browser/issues/66

We are going to have multiple prompt requests (e.g. see auth in #1378). Reacting to those and showing a prompt is a very generic thing and perfect for a feature component. This is also so basic browser functionality that I doubt that apps actually want to customize much here if anything at all.

There are many prompts. But for this first iteration let's just add:
- [ ] an http auth prompt (user/password) (https://github.com/mozilla-mobile/reference-browser/issues/66)

For reference see `GeckoViewPrompt` in Focus which was copied over from mozilla-central:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java

**Comment by NotWoods** [comment]
Closing since we've had this component for a while
