### ISSUE TITLE
browser-menu: Add ability for adding a two-state button

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1380]
*Maybe that's already possible with what we have. Let's try and add functionality if needed.*

For some menu buttons we want to have two states that can change dynamically. One example of that is the reload button: If the page is loaded you can "reload" and if the page is still loading you can "stop".

**Comment by jonalmeida** [comment]
We have `BrowserToolbar.TwoStateButton` already! 🎉

**Comment by Amejia481** [comment]
@jonalmeida then Can we close this issue?

**Comment by pocmo** [comment]
@Amejia481 No, in this case we need something similar for inside the menu! :)

**Comment by ekager** [comment]
So should #2201 close this issue, or is this still different?

**Comment by Amejia481** [comment]
I think they are the same!
