### ISSUE TITLE
Add implementation for capture thumbnail of websites on GeckoView

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1382]
User story: https://github.com/mozilla-mobile/reference-browser/issues/189

There's a issue on Bugzilla for the GeckoView API need it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1462018

**Comment by Amejia481** [comment]
GeckoView [just added the api](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoView.html#capturePixels--), let's working on that :)

**Comment by Amejia481** [comment]
We had a hard time trying to integrate this feature,  as `capturePixels()`  method is on `GeckoView` and `captureThumbnail()` is on `GeckoEngineSession` we don't have a way to link a `session` to  a `GeckoView`. Because we a clear separation between the relation between a `session` and a `view`, and it will require a big effort from our site to do that.

I inform the geckoView team about it, to see if they can provide `capturePixels()`  a method through `GeckoSession`.
 
https://bugzilla.mozilla.org/show_bug.cgi?id=1533112

**Comment by Amejia481** [comment]
Hi @pocmo,
I need a bit of help to clarify something about integrating this feature, I would like to hear your opinions about it.

How we architected taking screenshot was by adding a function on [EngineSession called captureThumbnail](https://github.com/mozilla-mobile/android-components/blob/d20edfd4658dc9b2b7fc1f6fdfc7f58cfa678942/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt#L245) and adding a variable on [Session called thumbnail](https://github.com/mozilla-mobile/android-components/blob/4b551dd3c8b3760bbeaa80d1ed356e5c0cfdf242/components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt#L251). 

`captureThumbnail` is a way to request screenshot on demand and the `thumbnail` variable represents the last screen shot  taken for this session.

To take a screenshots we need a instance of `GeckoView` or `WebView`.

As we implemented the feature first on [SystemEngineSession captureThumbnail](https://github.com/mozilla-mobile/android-components/blob/8e19da9ea8982ded0ac088242b5a54d944e6d266/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt#L335). We didn't have issues because each `SystemEngineSession` contains an instance of `Webview` because of the lack of sessions on `Webview`.

Now the API for GV is available, we are implementing the same on [GeckoEngineSession captureThumbnail ](https://github.com/mozilla-mobile/android-components/blob/e5cefefbcecf898c07fd149faea20f94015a168d/components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L562), but we can't use the same approach because as `GeckoView` has the concept of sessions, we don't have access to a `GeckoView` instance from `GeckoEngineSession`.

I reached the GV team and  asked them if they can add the API for taking screen shots on `GeckoSessions`, [they are not very happy with the idea](https://bugzilla.mozilla.org/show_bug.cgi?id=1533112), because they only can take a screen shot if a 
`GeckoView` instance is attached to the session, they really think that the API don't belong to `GeckoSession` and should only remain on `GeckoView`.

* Now I've been starting to think that they may be right, and we should remove the API for taking screenshots on demand  from [EngineSession  captureThumbnail](https://github.com/mozilla-mobile/android-components/blob/d20edfd4658dc9b2b7fc1f6fdfc7f58cfa678942/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt#L245) and expose it through [EngineView](https://github.com/mozilla-mobile/android-components/blob/51bc928a62d918eabcb8b212e74236f1d433b0a2/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt).

* An other change that we have to do is to change the type of  [captureThumbnail](https://github.com/mozilla-mobile/android-components/blob/4b551dd3c8b3760bbeaa80d1ed356e5c0cfdf242/components/browser/session/src/main/java/mozilla/components/browser/session/Session.kt#L251) from `Bitmap?` to a promise or future (callback) type value, [as the GeckoView API ](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoView.html#capturePixels--) returns `GeckoResult<Bitmap>`.

What do you think?

**Comment by pocmo** [comment]
Ah, that's a tough one.

I agree that this method makes more sense on the View. Especially since the thumbnail has the proportions of that view.

> Now I've been starting to think that they may be right, and we should remove the API for taking screenshots on demand from EngineSession captureThumbnail and expose it through EngineView.

This makes sense to me.

> An other change that we have to do is to change the type of captureThumbnail from Bitmap? to a promise or future (callback) type value, as the GeckoView API returns GeckoResult<Bitmap>.

Yes, the View API may be a Deferred<Bitmap> in our case, I guess.

> What do you think?

All above sounds good to me. The tricky part is how we are going to auto-take thumbnails when the page is loaded. Currently we only do that in onPageFinished() for WebView. We won't be able to do that from an `EngineSession` callback since they have no clue about the View.

Thinking about #891 and how we want auto-screenshotting be an optional feature (-> If you don't need screenshots it's wasteful to take them all the time), I'm coming to the conclusion that we want to rip that out and put that into a `Feature` class (something like `ThumbnailFeature`). This one can have the view, subscribe to whatever and take thumbnails automatically if needed (and updating the session). In fact this feature can be much smarter since we do not need to take thumbnails for custom tabs and other things that do not even show up in a tabs tray.

How does this sound?

**Comment by Amejia481** [comment]
> Yes, the View API may be a Deferred<Bitmap?> in our case, I guess.

That would be nice but we may be imposing an `kotlinx.coroutines` dependency on consumers.

I like the idea this way we can kill two birds with one stone 👍

**Comment by pocmo** [comment]
> That would be nice but we may be imposing an kotlinx.coroutines dependency on consumers.

Don't worry, `concept-engine` already does that. :)

**Comment by cpeterso** [comment]
The GV API for taking viewport screenshots has landed ([bug 1462018](https://bugzilla.mozilla.org/show_bug.cgi?id=1462018)).
