### ISSUE TITLE
DefaultSessionStorage: Decide what parts of `Session` we should serialize

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1384]
User story: https://github.com/mozilla-mobile/reference-browser/issues/77

Currently we only save a small amount of data. Let's figure out what parts of the `Session` we need to store and how to make this future-proof.

```
            put(SESSION_URL_KEY, session.url)
            put(SESSION_SOURCE_KEY, session.source.name)
            put(SESSION_UUID_KEY, session.id)
            put(SESSION_PARENT_UUID_KEY, session.parentId ?: "")
```

**Comment by csadilek** [comment]
@pocmo I've originally created this one: https://github.com/mozilla-mobile/android-components/issues/279 which I am closing as a dupe now. The new one has lables :)

**Comment by pocmo** [comment]
@csadilek Ah, thanks! I remembered that and tried to find it and failed! :)

**Comment by pocmo** [comment]
@csadilek Ah, wait, your's about the `EngineSession` and this here is just about `Session`. So maybe we can keep both. :)

**Comment by csadilek** [comment]
@pocmo heh, yes, I had already updated my comment above :)

**Comment by pocmo** [comment]
Closing: This has kind of been decided... :)
