### ISSUE TITLE
Expose state: "Is this page viewable in reader view?"

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1385]
Issue #1346 is about showing a page in reader view. However not all pages can be watched in reader view. The engine would need to tell us and we would need to forward that information through the `Session` to the UI.

**Comment by pocmo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1509258

**Comment by csadilek** [comment]
The plan is to implement this using the generic messaging API: https://github.com/mozilla-mobile/android-components/issues/2243
