### ISSUE TITLE
Update tracking protection lists in browser-engine-system

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1388]
Lists are here: https://github.com/mozilla-services/shavar-prod-lists

We took the list from Focus. Focus has never updated the list since we launched it. So we should definitely do that in the component soonish. Gecko comes with its own lists.

**Comment by Amejia481** [comment]
We should add some automation around it

**Comment by pocmo** [comment]
That would require a good test suite to make sure TP is still working as expected. I'm not sure if it will be worth it. Maybe, as long as FFTV is using it. However they also do not update that often:
https://github.com/mozilla-services/shavar-prod-lists/commits/master

**Comment by Amejia481** [comment]
👍
