### ISSUE TITLE
We need an exception handling strategy for PlacesHistoryStorage.kt (rust libraries in general)

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/android-components#1390]
Otherwise they seem to make the app crash.

cc @grigoryk

**Comment by grigoryk** [comment]
This is part of the larger robustness story. So far the exceptions have been useful at telling us when we're doing something wrong.

**Comment by grigoryk** [comment]
@mhammond what do you think? So far it's been quite helpful to see places crashes! Do you reckon we can ship as-is, given current stability of libplaces?

**Comment by mhammond** [comment]
I agree sentry reports are an excellent resource - is there any way to both catch them *and* get them in to sentry?

Ultimately though, I think this is really a product decision - the lib does appear reasonably stable, but I expect a long tail of users with issues (eg, corrupt databases or storage-full scenarios are likely to bite us). Not catching these exceptions probably makes the entire app unusable for those users, whereas catching them probably means the app continues to work but with reduced functionality.

If we can't both catch them and report them via sentry, a reasonable strategy would be to have sentry guide us, so I'm happy if we choose to do nothing at this time.

**Comment by pocmo** [comment]
@grigoryk Can we close this now?

**Comment by grigoryk** [comment]
I'll take a look at the Sentry volume for the current long tail, and will come back to close this.

**Comment by grigoryk** [comment]
Going to call this one as "good enough".
