### ISSUE TITLE
Custom Tab: Add ability to set toolbar color

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1397]
User story: https://github.com/mozilla-mobile/reference-browser/issues/209

`CustomTabsIntent.Builder.setToolbarColor(int)`

Note that based on the color we will need to adapt the text and icon colors too. There's some code for that in Fennec and Focus that we could borrow.

**Comment by pocmo** [comment]
@jonalmeida I was thinking about taking this too. So sharing some thoughts:
* I was thinking about adding a feature into `feature-customtabs` that does this. Something like `CustomTabsToolbarFeature`.
* Fennec has some code here to pick the right text color for a given toolbar color:
https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/util/ColorUtil.java#22

**Comment by jonalmeida** [comment]
> I was thinking about adding a feature into feature-customtabs that does this. Something like CustomTabsToolbarFeature.

@pocmo would this mean moving the toolbar logic for extracting the custom tab intent from `CustomTabConfig` into it's own feature?

**Comment by pocmo** [comment]
@jonalmeida I think that can stay where it is? The feature class would be able to access `CustomTabsConfig` from the `Session` and then apply the configuration to the toolbar (setting colors etc.).
