### ISSUE TITLE
Prototype session manager/store component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#140]
Requirements:
* Saves state of sessions ("session" + "engine session") frequently and when the app goes to background
* Restores sessions the next time the app is launched
* Hides the actual storage implementation (we do not want to make a decision on the actual storage implementation at this point)
* Should not be impacted by crashes (e.g. when the app crashes on the next start we restore a state that is not too old)

Resources:
* Focus saves the "engine session" state in the Session object in memory: https://github.com/mozilla-mobile/focus-android/blob/58d5ce0ae3382acf425ff13401488069014bdde3/app/src/main/java/org/mozilla/focus/session/Session.java#L33
* Fennec's session store: https://dxr.mozilla.org/mozilla-central/source/mobile/android/components/SessionStore.js

**Comment by csadilek** [comment]
Closing this. Follow up issues file: #163 #164
