### ISSUE TITLE
Add default state for new private session

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1404]
When we create a new Session, we have to enter an `initialUrl` or we provide a default Session to the session manager.

For a private session, we may want to a different default Session (or not provide an initial url?).

I've tagged 'session' and 'tabs' because I'm not sure where we would want to put this logic. `feature-tabs` seems like the most reasonable place for this "business logic".

**Comment by pocmo** [comment]
What do you want to achieve here? A session requiring a URL is a design decision. The SessionManager doesn't require any Session though.

If this is about Fennec not showing the URL when opening a private session: It's actually pointing to `about:home` and the toolbar displays that as blank. You can enter that at any time and you'll see the URL disappear. :)

**Comment by jonalmeida** [comment]
My use case is:
1. Click the new private tab button.
2. See some content that describes what a private tab is.

So from that I figured maybe we wanted a default private session as well.

**Comment by jonalmeida** [comment]
I'm closing this because I realized that we can do this without adding to functionality.
