### ISSUE TITLE
Consider using assertion library for tests

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1407]
Since assertj came up in a PR and since junit4 assertions are not particular great, let's discuss if we want to use some nicer assertion library for our unit tests.

This thread lists a bunch of them:
https://discuss.kotlinlang.org/t/what-assertions-library-do-you-use/1809/2

Some requirements:
* Should improve our ability to write/read tests
* Should be a serious project and actively maintained
* Should work locally and on a device

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-809)

**Comment by pocmo** [comment]
@csadilek @Amejia481 @jonalmeida @grigoryk Do you have any opinion here?

**Comment by jonalmeida** [comment]
No real preference, but AssertJ seems like the most standard one to use? If there's a version of it with any extra special Kotlin bindings, probably that one (if it's properly maintained). Mockito works well for us, but there have been some nice things in [`mockito-kotlin`](https://github.com/nhaarman/mockito-kotlin) that would make some tests easier to write.

**Comment by csadilek** [comment]
Don't feel strongly, but closing for now. We've been doing OK for years and have been bitten by additional third party testing libraries. We don't seem to have a strong enough use case at this point.
