### ISSUE TITLE
Improve URL detection in Strings

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#1438]
We currently have a very simple implementation of URL detection in Strings using a Kotlin extension:
https://github.com/mozilla-mobile/android-components/blob/master/components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt#L25

There's a much better implementation in Fennec:
https://searchfox.org/mozilla-central/source/mobile/android/services/src/main/java/org/mozilla/gecko/sync/setup/activities/WebURLFinder.java
https://searchfox.org/mozilla-central/source/mobile/android/services/src/test/java/org/mozilla/gecko/sync/setup/activities/WebURLFinderTest.java

**Comment by pocmo** [comment]
To be used in share intent processing. The toolbar should not search for URLs I guess and continue to use the simple check. :)

**Comment by csadilek** [comment]
This is no longer valid, we have this now :).
