### ISSUE TITLE
Sample browser crashes on download

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1439]
```
E  FATAL EXCEPTION: main
E  Process: org.mozilla.samples.browser, PID: 2599
E  java.lang.ClassCastException: org.mozilla.samples.browser.BrowserActivity@7543be3 must implement DownloadDialogListener
E      at mozilla.components.feature.downloads.SimpleDownloadDialogFragment.onAttach(SimpleDownloadDialogFragment.kt:76)
E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1404)
E      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
E      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
E      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
E      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
E      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
E      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
E      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
E      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
E      at android.os.Handler.handleCallback(Handler.java:873)
E      at android.os.Handler.dispatchMessage(Handler.java:99)
E      at android.os.Looper.loop(Looper.java:193)
E      at android.app.ActivityThread.main(ActivityThread.java:6680)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by pocmo** [comment]
That may have been caused by a local change I did during development: Maybe that's not actually crashing. :)

**Comment by Amejia481** [comment]
👍

**Comment by pocmo** [comment]
@Amejia481 I wonder why `DownloadDialogListener` exists though. The code checks whether the Activity or the parent Fragment implements it and throws if not; but it's not actually required and the interface has empty default implementations. The dialog seems to notify the feature **and** the listener - but why the listener?

**Comment by Amejia481** [comment]
It's a way to enforce that the Activity or the parent Fragment provide an implementation for positive and negative actions and when the fragment/activity is recreated the listener get re-attach.

```kotlin
    override fun onAttach(context: Context) {
        super.onAttach(context)
        buttonsListener = context as? DownloadDialogListener
        buttonsListener = buttonsListener ?: parentFragment as? DownloadDialogListener

        if (buttonsListener == null) {
            throw ClassCastException("$context must implement DownloadDialogListener")
        }
    } 
```

It has an option overridden because [SimpleDownloadDialogFragment](https://github.com/mozilla-mobile/android-components/blob/039fe8fc1644d1da9509d8f7abd893a9fbd20be5/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadDialogFragment.kt) already  re-attach the listener and handle the positive and negative behavior in it. But I also to want to re-attach the listener for people that create their own version of [DownloadDialogFragment](https://github.com/mozilla-mobile/android-components/blob/039fe8fc1644d1da9509d8f7abd893a9fbd20be5/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragment.kt).

**Comment by Amejia481** [comment]
**[UPDATED]**
 It's there in case your want to be notified for positive and negative buttons, this listener needs to be re-atteched.

**Comment by Amejia481** [comment]
It has a optional override in case you don't want to be notified for the positive and negative buttons

**Comment by Amejia481** [comment]
[SimpleDownloadDialogFragment](https://github.com/mozilla-mobile/android-components/blob/039fe8fc1644d1da9509d8f7abd893a9fbd20be5/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/SimpleDownloadDialogFragment.kt) handles everything for you, but I need a way to enforce in case you want to be notified for positive and negative buttons actions.

**Comment by Amejia481** [comment]
Good point!
I can't find a really good use case! I did just to have more flexibility for the user.

Should I remove it ?

**Comment by pocmo** [comment]
Maybe. Less public API is less things to maintain :)

**Comment by Amejia481** [comment]
Sorry for the long discussion. Now I remember, why :sweat_smile: 

In the focus app, they log a telemetry event  (`downloadDialogDownloadEvent`)  for positive and negative bottoms. For this reason I added the called back, I thought that maybe useful for others.

https://github.com/mozilla-mobile/focus-android/blob/308317917a8103dcea02f2868e9d7c85b258feb1/app/src/main/java/org/mozilla/focus/fragment/DownloadDialogFragment.kt#L58

```kotlin
    private fun setButtonOnClickListener(
        button: Button,
        pendingDownload: Download?,
        shouldDownload: Boolean
    ) {
        button.setOnClickListener {
            sendDownloadDialogButtonClicked(pendingDownload, shouldDownload)
            TelemetryWrapper.downloadDialogDownloadEvent(shouldDownload)
            dismiss()
        }
    }
```
Should I still delete it :sweat_smile: ?

**Comment by pocmo** [comment]
For telemetry I would like us to look into a more generic solution (#42). I would like to end up with something where the components can emit events and the app can decide to route them to telemetry or other things. Otherwise every app has to re-add probe for everything all over the place. :)

**Comment by Amejia481** [comment]
Awesome 👍 !
