### ISSUE TITLE
APK download uses "downloadfile.bin" as file name

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1446]
I wanted to download the reference browser from the reference browser (inception!)

But it didn't use the file name and instead offered to download "downloadfile.bin".

![screenshot_20181120-195001](https://user-images.githubusercontent.com/89638/48857591-8885c180-edb9-11e8-9c02-824205625fc9.png)

**Comment by Amejia481** [comment]
After we changed [`Download.fileName` to nonull](https://github.com/mozilla-mobile/android-components/commit/abed27220ec20ce3ce33b652782e13d453bed420). We're calling `DownloadUtils.guessFileName(contentDisposition = response.uri, url = null,  mimeType= null)` with in correct parameters. 

https://github.com/mozilla-mobile/android-components/blob/4e439433d52db5d2f0190b29436a8130df2b9234/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L369
 ```kotlin
   override fun onExternalResponse(session: GeckoSession, response: GeckoSession.WebResponseInfo) {
            notifyObservers {
                val fileName = response.filename
                        ?: DownloadUtils.guessFileName(response.uri, null, null)
                onExternalResource(
                        url = response.uri,
                        contentLength = response.contentLength,
                        contentType = response.contentType,
                        fileName = fileName)
            }
        } 
```

For this reason when `response.filename` is null `DownloadUtils.guessFileName` is returning `downloadfile.bin`

We should call it with something like `DownloadUtils.guessFileName(contentDisposition ="", url = response.uri, mimeType=response.contentType)`
