### ISSUE TITLE
Add new TabsUseCases for closing all sessions

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1457]
We need a use case that lets you close:
- all
- regular tabs only
- private tabs only

**Comment by pocmo** [comment]
FYI: In the context menu PR that I'm going to open now I renamed some of the use case classes inside `TabsUseCases`. There may be conflicts! :)

**Comment by chikka** [comment]
@jonalmeida @pocmo can i take it up?

**Comment by jonalmeida** [comment]
@chikka Definitely! Although you should wait for #1459 to get merged. If you're keen to work on this ASAP, then you can work off that branch.

Have a look at [`TabsUseCases.kt`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt) to get an idea of how to write one.

**Comment by chikka** [comment]
@jonalmeida Thanks!. I have looked into it and I think we need to create two classes for it

   ```
 class RemoveAllTabsUseCase internal constructor(
        private val sessionManager: SessionManager
    ) {
       
        fun invoke() {
            
        }
    }
```

 ```
   class RemoveTabsUseCase internal constructor(
        private val sessionManager: SessionManager
    ) {
       
//send privateOnly=true for closing only private tabs otherwise false to close all normal tabs
        fun invoke(privateOnly: Boolean = false) {
            
        }
    }
```
Please let me know your thoughts on it

**Comment by jonalmeida** [comment]
@chikka looks great! Feel free to create a PR and we talk review it there as well.

Small nit:
```kotlin
fun invoke(privateOnly: Boolean = false) { }
```
I'd change the attribute name from `privateOnly` to `private`. It may imply that it would remove _all_ tabs vs only private tabs.
