### ISSUE TITLE
Expose page loads that are redirects

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/android-components#1493]
When visiting youtube.com/tv, it redirects through 5 youtube pages which do not alter the page content. This affects the backstack history, because when trying to go to the previously visited site, you instead have to back-click through all of the redirects. FFTV would like a way to know whether the page load is a redirect so it can be handled differently.

See issue: https://github.com/mozilla-mobile/firefox-tv/issues/1543

**Comment by dnarcese** [comment]
cc @jonalmeida

**Comment by mcomella** [comment]
@jonalmeida afaict, the issue is that youtube is not handling back presses, not that it's showing redirect links. See https://github.com/mozilla-mobile/firefox-tv/issues/1543#issuecomment-447098581

I don't think this needs to be fixexd.

**Comment by jonalmeida** [comment]
This seems fair from my own parallel investigation. I'm going to close off this issue in that case.
