### ISSUE TITLE
Be smarter about logging

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#15]
We imported some Firefox for Android code with random Log.* statements.

How can we avoid logging random things in the app's log? How can the app control this?

Some thoughts:
* Do we need to log from components at all? Could we avoid this completely?
* Do we need a log component for our apps? Could components hook into that?
* How can we make sure that the consumer is in control?

**Comment by pocmo** [comment]
It probably comes down to one of:

* A) Using Timber and exposing it from the base component (#482)
* B) Writing a simple Log wrapper (maybe even wrapping Timber) and exposing that

I almost tend to (B) because it would allow us to iterate on the API and give the app more controls.

**Comment by walmyrcarvalho** [comment]
I like the B plan (no pun intended), it's possible to have a custom Timber tree with contextual logging (per flow or per user interaction), or maybe have another `BuildConfig` to turn an specific logging on. What you think?
