### ISSUE TITLE
Abstract HTTP API Client

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#1508]
On top of our *concept-fetch* we should probably write a generic HTTP API client that abstracts away some common functionality ("good behaviour") that we expect from an API client. Things like:

* Identifying the request by including the application name/identifier/version in the UA - Specially important for debugging situations where we need to know exactly which application is making the request.
* Implementing a retry strategy so that requests that fail can optionally retry themself
* Implementing a back-off strategy / rate-limiting to make sure clients do not rapidly retry requests
* Handling server response codes. For example, decide to stop making requests completely on a 4xx but retry on a 5xx.
* Handling redirects
* Handling TLS security
* A common way to build test/staging/production endpoint URLs?
* Make sure that no cookies are shared between APIs and WebViews
* Ensure that requests are not looking any information (UA, Locale, Cookies, etc.)

The Firefox TV team has been doing some great work in this area recently around the Pocket client. Maybe some of that code can be re-used here?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-910)

**Comment by st3fan** [comment]
The first point, *Identifying the request by including the application name/identifier/version in the UA* needs to be able to determine some of these values at runtime instead of being compiled in.

We have been in a situation where people have forked our applications, and the API calls appear as if they are coming from our own products. To identify those requests we should include the app identifier/name that we have discovered at runtime.

**Comment by Baron-Severin** [comment]
I think this sounds like a great idea.  One additional feature that I think would be helpful would be opening a stream of recurring updates (for example, we update Pocket in the background every 45 minutes).

We can probably borrow some code from FFTV here, but our present implementation does have a challenge in that we have not yet worked out how to effectively test some of the temporal logic around background updates and backoff logic.  One potential solution to that problem could be internally implementing this using RxJava (where such tests would be fairly straightforward to write) and exposing data in a more generic way at the edges of this component (i.e., not forcing an Rx dependency upon client code).

For reference, this is the relevant code in FFTV: https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/pocket/PocketVideoRepo.kt

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793149

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
