### ISSUE TITLE
Globe icon rendered incorrectly

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1513]
Device: Nexus 5, Android 6.0.1

![device-2018-11-29-101252](https://user-images.githubusercontent.com/89638/49211688-6ba44c00-f3c0-11e8-8c51-429a1241e549.png)

**Comment by pocmo** [comment]
I think we have seen a similar issue with Focus in the past. Afaik it depends on how the icon was loaded or set on the view: We want the support library to load/set the icon so that it will render correctly on all Android devices (what kind of SVG features are supported depends on the Android version otherwise).

**Comment by pocmo** [comment]
CC @jonalmeida

**Comment by jonalmeida** [comment]
Thanks for fixing this! :)
