### ISSUE TITLE
Browser toolbar: Follow app bar specs

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1514]
https://material.io/design/components/app-bars-top.html#specs

In this case I mean the icon specs and specifically for the menu button. In our implementation there's a noticeable large gap between the menu and browser actions.

**Comment by jonalmeida** [comment]
Bram has also provided us with a design layout for Custom Tabs:
![](https://user-images.githubusercontent.com/51007/53133685-dee0e700-35d8-11e9-96d8-09c2be0bbdd4.png)

**Comment by Amejia481** [comment]
Related https://github.com/mozilla-mobile/android-components/issues/4503

**Comment by rocketsroger** [comment]
Related https://github.com/mozilla-mobile/android-components/issues/4442

**Comment by sblatz** [comment]
(I believe) related: https://github.com/mozilla-mobile/fenix/issues/5671

**Comment by pocmo** [comment]
@sblatz Good to know that it is already broken. I was confused why it is broken in my refactoring branch. :D

Will fix this as part of this bug here.

**Comment by theres-waldo** [comment]
Is there a corresponding patch for `reference-browser` that allows it to build against this change?
