### ISSUE TITLE
Use multiprocess Gecko

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#155]
On GeckoSessionSettings: `setBoolean(GeckoSessionSettings.USE_MULTIPROCESS, true);`

**Comment by csadilek** [comment]
Multiprocess seems to be turned on by default:

https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSessionSettings.java?q=GeckoSessionSettings.java&redirect_type=direct#118

Of course, we could still add it to make it explicit.
