### ISSUE TITLE
Unified documentation

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1551]
Teams have mentioned that they've found our documentation to be quite dispersed around. Things we can do to improve it:
- [ ] Add a search bar on the components website.
- [ ] Create a unified 'getting started' entry point.
- [ ] Unified documentation (API docs, examples)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-963)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795074

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
