### ISSUE TITLE
Set HistoryTrackingDelegate via SessionManager

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#1552]
Currently, `HistoryTrackingFeature` creates a history tracking delegate and sets it on the engine's settings. If we're using SessionManager to handle our session creation, we need to make sure that `HistoryTrackingFeature` is initialized before the first session is created. Otherwise, that first session is created with a `settings` object which doesn't have the delegate, and so history tracking won't work.

Ideally we shouldn't need to worry about correct sequencing of these events. One way to achieve that is by using SessionManager to augment the underlying engine's settings at the correct moment. This would require changing our tracking feature to depend on the sessionManager instance instead of an engine. We could also consider folding HistoryTrackingFeature into sessionManager itself.

**Comment by grigoryk** [comment]
Another option is to fold this functionality into `feature-session`.

**Comment by csadilek** [comment]
As part of this we need to make sure we can lazily initialize the HistortyTrackingFeature and the Engine (it depends on). Eagerly initializing it caused the crashes fixed (worked around) in: https://github.com/mozilla-mobile/reference-browser/pull/326#issuecomment-446398187
