### ISSUE TITLE
Create a lint check to make sure Engine is never created in Application.onCreate

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1564]
Not sure if this is possible, but it would be nice to make sure that an engine is always created in an Activity/Fragment instance only.

If we create an engine in the Application, (for Gecko) this will call the Application's onCreate again which will cause issues.

**Comment by jonalmeida** [comment]
Assigning to myself because I wanted a reason to write a lint rule. 😄

**Comment by pocmo** [comment]
> Not sure if this is possible, but it would be nice to make sure that an engine is always created in an Activity/Fragment instance only.

This assumption is not correct. We explicitly want to create engines in other contexts too (e.g. background services).

> If we create an engine in the Application, (for Gecko) this will call the Application's onCreate again which will cause issues.

More precise: An `Application` instance is created for every process and if `GeckoView` runs in E10s mode then it will use multiple processes.

The only rule that may (maybe) apply is that you only ever want to initialize GeckoEngine from the main process. But that would be a runtime check.

**Comment by pocmo** [comment]
> I wanted a reason to write a lint rule.

A lint check for the MPL license header would be great btw. :D
