### ISSUE TITLE
AutofillService component on top of for services-sync-logins

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#1581]
It'll be great if we can have Autofill support that's backed by the synced logins data. We could create an AutofillService which operates over a login-shaped storage layer (or is specific to sync-logins) and fills out autofill requests coming from the OS.

This service could be used in the reference browser to provide basic synced logins autofill experience, as well as in Lockbox (see https://github.com/mozilla-lockbox/lockbox-android/issues/214).

**Comment by pocmo** [comment]
I would only push for this as a component at this point if Lockbox would be interested in using and maintaining (most of) it. That's a rather big thing to maintain.

**Comment by pocmo** [comment]
Looks like we have this now (or start to have).
