### ISSUE TITLE
Remove Drawable.toBitmap in favor of official KTX version

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#162]
https://developer.android.com/reference/kotlin/androidx/core/graphics/drawable/package-summary#(android.graphics.drawable.Drawable).toBitmap(kotlin.Int,+kotlin.Int,+android.graphics.Bitmap.Config)

Unclear what the differences in implementation could be.

**Comment by pocmo** [comment]
👍 

Let's wait until core-ktx 1.0 is released (latest version is still 1.0.0-alpha1) and then let's remove everything that's already part of one of Android's *-ktx libraries.

**Comment by pocmo** [comment]
`androidx.core:core-ktx:1.0.0` is available now. But we need to switch to androidx first (#842).
