### ISSUE TITLE
Gecko Engine: Add open window / close window support

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1626]
I noticed we didn't have any issue tracking this for GeckoEngine after the SystemEngine was implemented (#1067).

Re-opening this for https://github.com/mozilla-mobile/reference-browser/issues/315

Currently blocked on [bug 1510314](https://bugzilla.mozilla.org/show_bug.cgi?id=1510314).

**Comment by csadilek** [comment]
@jonalmeida we do have an issues for that: https://github.com/mozilla-mobile/android-components/issues/1503 :)

**Comment by jonalmeida** [comment]
Welp, closing.
