### ISSUE TITLE
System: Disable zoom buttons on page

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1628]
We should disable these zoom buttons since:
1. they don't work.
2. they're a deprecated way of controlling zoom since we have pinch to zoom.
3. their position seems very off (above the system navigation buttons).

![screenshot_20181229-215215](https://user-images.githubusercontent.com/1370580/50543938-52a3dc00-0bb4-11e9-9284-08f5ee0987f2.jpeg)

**Comment by karishnu** [comment]
I would like to work on this. Is there anything I need to know before I start?

**Comment by jonalmeida** [comment]
@karishnu You should look into fixing this inside `SystemEngineView`. 

Remember to also change your build variant to `systemUniversalDebug` to test if it works with the `sample-browser` project.

If you're not sure about your implementation feel free to leave comments here if you'd like.

**Comment by jens1o** [comment]
@karishnu I wonder whether you are still working on this? Otherwise I'd like to give it a shot.

**Comment by karishnu** [comment]
@jens1o  You can take it up. I did not find time to look at it after that :(

**Comment by jens1o** [comment]
Okay, I'll take a look! Thanks for your reply!

**Comment by kartikgits** [comment]
@jonalmeida Are you working on it? I'm a beginner and would like to work on it.
