### ISSUE TITLE
Add IWebView component

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#167]
We previously discussed creating an `IWebView` component, similar to the one in Focus. If that isn't in the plans anymore, you can close this.

fwiw, I took time to refactor the components in firefox-tv from Focus, which I think improved it: I'd recommend looking at the firefox-tv implementation when making this. In particular, I:
- Decoupled components (e.g. WebFragment called into BrowserFragment and vice versa with listeners and abstract methods)
- Made each component have one responsibility (e.g. iirc, WebFragment did a few different things)
- Renamed components to make their single responsibility clearer (e.g. after the refactor, WebFragment handled fetching the WebView after inflation and destroying it so I renamed it `IWebViewLifecycleFragment`)

That being said, I did have the luxury of removing Focus code we didn't need to use so this made it easier. If you want more details about my refactor, let me know.

**Comment by pocmo** [comment]
Yep! That's what the "engine" component does. It hides the actual browser engine between three classes: EngineView (the view component that actually renders content), EngineSession (that you can assign to a view and where you actually perform actions on or get events from), Engine (the "runtime" that currently just helps you create views and sessions).

WebFragment initially was just an IWebView-version of Android's WebViewFragment:
https://developer.android.com/reference/android/webkit/WebViewFragment

We do not have any fragment wrapping the view in our components yet. But we may need that soon.

**Comment by mcomella** [comment]
@pocmo Would you say the engine component is ready for production use? It seems to be missing IWebView functionality, but perhaps that's because you're re-envisioning the scope in which it should be used?

fwiw, apparently WebViewFragment is deprecated in P. :P

Should this bug be closed if engine already exists?

**Comment by pocmo** [comment]
> @pocmo Would you say the engine component is ready for production use? It seems to be missing IWebView functionality, but perhaps that's because you're re-envisioning the scope in which it should be used?

Not yet. Maybe in Q3 we are able to think about integrating it into Focus.

> fwiw, apparently WebViewFragment is deprecated in P. :P

Yeah, (platform) Fragments in general are deprecated now. There is no replacement in the support libraries - but I guess nowadays a lifecycle observer may be better suited.

> Should this bug be closed if engine already exists?

Yeah, let's do that. There's also #125 about maybe adding a fragment.
