### ISSUE TITLE
Menu: Add mechanism for dynamically update items

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#170]
Some menu items will need to update dynamically while they are being shown:

Examples:
* Stop/Reload: In Focus while loading a page there's a "stop" button. If the page has finished loading we show a "reload" button.
* Forward: Whether this button is disabled or not depends on the current state. This state can change while the item is displayed. See #169

**Comment by NotWoods** [comment]
I'm interested in working on this! @csadilek @pocmo

**Comment by NotWoods** [comment]
Closed by #3022
