### ISSUE TITLE
Create android-components app in Firebase

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/android-components#1700]

**Comment by rpappalax** [comment]
@pocmo our GCP projects for mobile need to be moved to a different GCP org.  Has the GCP project you created for mobile been integrated in any way yet?  If not, then I'd like to delete the one that's in the old org and create a new one in the new org.  Is that OK with you?

**Comment by pocmo** [comment]
@rpappalax No, the only usage I can think of is the UI tests of Focus.

**Comment by rpappalax** [comment]
> @rpappalax No, the only usage I can think of is the UI tests of Focus.

OK, cool.  I've re-created the firebase proj in the new org.  Can you can confirm that you can see the projects we're working on in the firebase dashboard?  https://console.firebase.google.com/

**Comment by pocmo** [comment]
@rpappalax In the firebase console I can see:
* moz-reference-browser
* rocket
* moz-fx-mobile-firebase-testlab

I assume "moz-reference-browser" is the new one?

**Comment by pocmo** [comment]
This seems to be done.
