### ISSUE TITLE
Menu: Style rounded corners

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1712]
That should be style-able by a component consumer.

**Comment by pocmo** [comment]
See: https://github.com/mozilla-mobile/fenix/issues/133

**Comment by Amejia481** [comment]
@pocmo now it can be done by overriding this dimension property `mozac_browser_menu_corner_radius` on the consumers `dimens.xml` file. Do we want a programmatically way to do that ?

I achived this by overriding `mozac_browser_menu_corner_radius` on `dimens.xml` file of the sample browser.
```xml
<resources xmlns:tools="http://schemas.android.com/tools">
    <dimen name="mozac_browser_menu_corner_radius">14dp</dimen>
</resources>
```

![image](https://user-images.githubusercontent.com/773158/51205696-77968f80-18d4-11e9-9808-4ae788db5da6.png)

**Comment by pocmo** [comment]
Awesome! I think the `dimen` is good enough for now! :)

**Comment by Amejia481** [comment]
Cool, I will add some docs of how to override it. 👍 

Maybe in the future, we should add some docs about all the properties that can be overridden, like other dimens :)
