### ISSUE TITLE
Document adding usesCleartextTraffic to the app manifest

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1723]
For API 28+, applications that make insecure connections (HTTP) need to be explicitly allowed to do so with `<application android:usesCleartextTraffic>`.

This is mostly an issue for SystemEngine implementations since Gecko isn't limited to this.

We should document this requirement. Maybe in the shared doc, since this isn't an engine/component specific requirement?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1136)

**Comment by mcomella** [comment]
> Maybe in the shared doc

That's here: https://github.com/mozilla-mobile/shared-docs

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795076

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
