### ISSUE TITLE
Unexpected failure during lint analysis of module-info.class

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1730]
Lint for `support-test` is failing in the 0.38.0 release task:
https://tools.taskcluster.net/groups/UJ-v477WQZq5QY2gtNQ7Xw/tasks/U5fFFP4nTAiHckdK_fq8-Q/runs/3/logs/public%2Flogs%2Flive.log

We re-run the task multiple times but it always fails with that error. The same commit has passed on master without any issues.

**Comment by ligi** [comment]
FYI for me bumping a dependency to "bouncycastle 1.61" in a library caused the problem for me and reverting this bump solved the problem.
Should still report this problem upstream at some point. Just making you aware - perhaps this also helps you closing this issue.
