### ISSUE TITLE
Add support to show security indicator in toolbar

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#177]
DisplayToolbar structure:

```
 +------+-----+--------------------+---------+------+
 | icon | nav |         url        | actions | menu |
 +------+-----+--------------------+---------+------+
```

We want to show a security indicator (lock / globe) in the toolbar depending on the security level of the current site.

* Engine: Hook up security level callbacks
* Session: Expose security level state
* Toolbar: Add option to display security levels

**Comment by pocmo** [comment]
We do have that functionality in the engine implementations. But we do not have anything in the toolbar yet.

**Comment by jonalmeida** [comment]
With out current implementation that notifies `onSecurityChange` we don't expose different types of page security like mixed content, so for now, we have to follow the `secure` flag.

We can follow up in the future to have a more fleshed out abstraction to provide more details in the toolbar.

**Comment by jonalmeida** [comment]
I have the icon updating from the callback(1), but in [some tests][0] I can see the need for a newer security changed API already.

[Here][0], the initial page loaded is secure and the secondary content (an iframe in this case) is insecure. So I get two callbacks: `true` -> `false`. We set the insecure icon then. What if only the secondary content is secure then? We would get: `false` -> `true` and wrongly mark the entire site as secure.

Another issue I've seen in the sample browser that might be a Gecko bug:
1. Load the mixed content site.
2. Observe two `secure` flag changes: true then false.
3. Click the 'http' link.
2. Observe one `secure` flag change: false.
3. Click the back button.
2. Observe **only one** secure flag change: true.

At step 6, I expect the same count and values from the callback as in step 2 (i.e. true then false).

(1): `EngineSession#onSecurityChanged(Session, Session.SecurityInfo)`.

[0]: https://googlesamples.github.io/web-fundamentals/fundamentals/security/prevent-mixed-content/active-mixed-content.html

**Comment by jonalmeida** [comment]
For the first issue, I guess what we want is an AND of all the `secure` flags while the main page load is still the same. 🤔

**Comment by pocmo** [comment]
```
Here, the initial page loaded is secure and the secondary content (an iframe in this case) is insecure. So I get two callbacks: true -> false. We set the insecure icon then. What if only the secondary content is secure then? We would get: false -> true and wrongly mark the entire site as secure.
```

Your first scenario (true -> false) makes sense; the main frame is not secure anymore if it loads an resource that is not secure. The reverse: Does this actually happen with GeckoView? If yes then this sounds like a bug.

**Comment by jonalmeida** [comment]
> > Here, the initial page loaded is secure and the secondary content (an iframe in this case) is insecure. So I get two callbacks: true -> false. We set the insecure icon then. What if only the secondary content is secure then? We would get: false -> true and wrongly mark the entire site as secure.
> 
> Your first scenario (true -> false) makes sense; the main frame is not secure anymore if it loads an resource that is not secure. The reverse: Does this actually happen with GeckoView? If yes then this sounds like a bug.

I did a test with an insecure site and secure iframe. Once we get a false from the first request, we don't get any more. The second one is still a bug.

**Comment by jonalmeida** [comment]
Filed [bug 1505827][0].

[0]: https://bugzilla.mozilla.org/show_bug.cgi?id=1505827
