### ISSUE TITLE
Components wrapping WebExtensions?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1791]
GeckoView is going to provide a WebExtension API (limited) that will allow to at least use content scripts. This will be GeckoView's preferred way of execute JavaScript in the context of the website (as opposed to WebView's methods for injecting JavaScript).

There will/could be some features that are (partially) implemented as WebExtensions: Adblocking, https everywhere, reader mode, ..

How can we build such features in a way that they can be used by all our apps? Could/should we wrap WebExtensions in an Android Component for that purpose? If we end up landing WebExtensions/JavaScript code here: How can we make this a pleasant development experience (tooling like linter etc.)?

**Comment by pocmo** [comment]
**Build**

Let's say (as an example) we have a layout like:

```
src
|-- main
    |-- java
    |   `-- ... Java/Kotlin code
    `-- extension
        `-- WebExtension code and resources...
```

At build time we'd need as gradle task that would wrap up the `extension` directory, zip it and place it into the assets folder. With gradle's task output caching we'd need to make sure that this either happens every build (meh) or only if the files have changed.

Since we'd need that for every "extension component" maybe it would be worth wrapping that up as a Gradle plugin?

**Comment by ligi** [comment]
Is there currently any way to inject javascript in a page?

**Comment by pocmo** [comment]
@ligi Currently only via a `javascript:` URL. I'm not sure whether that gives you access to the current page's DOM though. The GeckoView APIs for basic WebExtensions (e.g. Content Scripts) should land soon though!

**Comment by csadilek** [comment]
Closing now that reader view landed: https://github.com/mozilla-mobile/android-components/tree/master/components/feature/readerview
