### ISSUE TITLE
Gecko Engine: Clear data

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1798]
We have a basic API for this right now working SystemEngine, but we didn't have an issue to track the Gecko Engine work.

Feature requirement for r-b: https://github.com/mozilla-mobile/android-components/issues/644
Related bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1489669

**Comment by pocmo** [comment]
Related Fenix mocks:
https://mozilla.invisionapp.com/share/HNRJ99EF3E6#/screens

**Comment by pocmo** [comment]
Patches attached to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1489669

Needs to get into gecko-engine-nightly and gecko-engine-beta (68+).

**Comment by cpeterso** [comment]
GV's Clear User Data API landed last week:
https://bugzilla.mozilla.org/show_bug.cgi?id=1489669#c22

And should be available in yesterday's GV 68 Beta build:
https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/geckoview-beta-armeabi-v7a/68.0.20190527103257/

**Comment by csadilek** [comment]
@cpeterso thanks! PR to integrate is already up: https://github.com/mozilla-mobile/android-components/pull/3156 :)
