### ISSUE TITLE
Improve lib-crash dialog to add additional fields

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#1811]
The Fennec crash dialog allows the user to provide more info, that helps in to simulate the crash.
We should improve the lib-crash to add these fields.

![image](https://user-images.githubusercontent.com/773158/51630430-2875dd80-1f18-11e9-8bbe-d947db7f4a0b.png)

**Comment by dector** [comment]
Can be epic for #3262, #3261 and #3260. :)

**Comment by pocmo** [comment]
Let's close this and just track the separate issues. :)
