### ISSUE TITLE
Meta: Site permissions & controls

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1818]
### Description

> We have not started this work yet, but are peeking at it. We have a goal this quarter to start looking at permissions dialogs, which is part of Site Permissions, but it is bigger than that, I think we should also include a standard UI for managing permissions in Android Components so that this will be reusable for other products. We should turn this into a mini project with its own board where we can keep track of all the work involved.

* UX issues:
 * Site permissions: https://github.com/mozilla-mobile/fenix/issues/188
 * Site controls: https://github.com/mozilla-mobile/fenix/issues/191

For Android Components it makes sense to provide (rough draft):

* A `feature` component that can display permission requests while browsing (probably as toolbar doorhangers; but UX is not defined yet)
* A storage that persists decisions for specific sites (updated by the `feature` component and app specific UI like settings)
* Functionality that auto-accepts permission requests based on previous permission grants.

### Target

https://github.com/mozilla-mobile/fenix/issues/218

**Comment by shorlander** [comment]
This is the UX issue: https://github.com/mozilla-mobile/fenix/issues/188
