### ISSUE TITLE
Meta: Good crash statistics

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1820]
### Description

We want to have good crash statistics (e.g. crash rates) in order to:
- make release decisions 
- measure the app quality
- identify regressions

Our current crash reporting tools are insufficient: 
* Sentry only knows about crashes and not users. Therefore Sentry cannot calculate crash rates.
* Socorro is only used for native code crashes and does not know about other crashes.
* Google Play has some statistics but we can't correlate them with our other data (e.g. telemetry)

### Resources

* [Bug 1407557 - Fennec implementing crash ping](https://bugzilla.mozilla.org/show_bug.cgi?id=1407557)

### Target

- https://github.com/mozilla-mobile/fenix/issues/235

### Tasks

- [Bugzilla: Collect crash data from Android apps using glean](https://bugzilla.mozilla.org/show_bug.cgi?id=1522461)
- (needs further breakdown)

### Dependencies

- [x] Discuss with *glean* team.

**Comment by pocmo** [comment]
@Dexterp37 FYI. Good crash statistics is something that has haunted us for a while. Since we can generate custom pings with Glean I think we could just build such a crash ping.

A small technical challenge here is that the crash reporter is running in a different process (since the app process crashes) and we should avoid corrupting our data while writing from multiple processes.

**Comment by pocmo** [comment]
From the GV meeting: GV catches native code crashes; In non-GV apps with native code (e.g. Lockbox; or a WebView-based browser) we may not be able to send a crash ping since we do not catch those crashes.

**Comment by st3fan** [comment]
If we do a crash ping, it would be good to have a 'component' classifier in it, so that we can see where the crash originated. Could be a string that we fill in, like 'frontend', 'geckoview', 'glean', etc.
