### ISSUE TITLE
Support WebAPK

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1832]
Meta: https://github.com/mozilla-mobile/android-components/issues/1819
User Story: https://github.com/mozilla-mobile/reference-browser/issues/300

> Chrome automatically generates and installs a special APK of your app. We sometimes refer to this as a WebAPK. Being installed via an APK makes it possible for your app to show up in the app launcher, in Android's app settings and to register a set of intent filters.

https://developers.google.com/web/fundamentals/integration/webapks

It's unclear at this point how we can make use of this.

**Comment by igalic** [comment]
would it be possible or sensible to duplicate what chrome / android does?
