### ISSUE TITLE
Allow UseCases to be used without selected session

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1835]
A bunch of our use cases use `SessionManager.selectedSessionOrThrow`. That's a bit annoying in browsers that can have no sessions at times. A simple approach may be to create a new session in this case. Maybe we could even make this configurable so that an app can override this behavior.

**Comment by csadilek** [comment]
@pocmo I wonder if `selectedSessionOrThrow` is really needed. It's not an exception we want to recover from (don't want to use it as control flow either). How about we change that everywhere to default to `seelctedSessionOrNew`? This way if no session is specified, we'll look for the selected one, and failing that create a new one. We wouldn't need to configure anything this way...

**Comment by pocmo** [comment]
@csadilek Yes, fully agree and have a patch in-flight that I wanted to toss to you. I wrapped the code that creates the new session in an optional lambda that the app can provide (if it wants to do some other Session setup or for some reason not pass it to the SessionManager).
