### ISSUE TITLE
DownloadUtils: Unnecessary non-null assertion

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#184]
From the release build log:

```
DownloadUtils.kt: (133, 36): Unnecessary non-null assertion (!!) on a non-null receiver of type String
```

**Comment by ninad458** [comment]
Can I work on this?

**Comment by pocmo** [comment]
@ninad458 Yes, absolutely! Please open a PR once you have a fix for this.

**Comment by ninad458** [comment]
@pocmo the commit #0e58d73466dc7716fea250e0c5d568278a65e765 should solve have solved the issue, right?

**Comment by pocmo** [comment]
Oh, yes, we already merged that. :)
