### ISSUE TITLE
Add properties for changing the colour of menu and security icons

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1840]
Fenix wants the ability to stylize the icons in the toolbar a bit more and we don't expose the ability to do so.

cc: @ekager

**Comment by pocmo** [comment]
"stylize the icons a bit more"? :)

**Comment by ekager** [comment]
The main use case right now is being able to directly tint the menu icon. The other icons we can load and tint our own resources, but we would have to overload the menu icon to tint it ourselves right now IIRC
