### ISSUE TITLE
SessionProvider: Always expect storage parameter

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#185]
It's a bit inconvenient that I have to pass a `Context` to `SessionProvider` just so that I may be used to initialize `DefaultSessionStorage`. I wonder if we could always pass a SessionStorage implementation and avoid requiring a `Context`.

**Comment by pocmo** [comment]
@csadilek What do you think?

**Comment by csadilek** [comment]
@pocmo true, that's a design flaw on my part. the context is only needed for the default storage, yet has to be provided separately. technically, other storages might not even need the context at all. I will refactor.
