### ISSUE TITLE
Meta: Sync Tabs

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/android-components#1850]
This meta covers the work by the Sync team and A-C team to enable the sync tabs functionality. 

See Fenix meta here: https://github.com/mozilla-mobile/fenix/issues/5762

**Comment by bbinto** [comment]
Dependency on application services team

**Comment by bbinto** [comment]
AS team has not planned for this.

**Comment by vesta0** [comment]
This is now on Sync team's Q4 roadmap.

cc @jdragojevic
