### ISSUE TITLE
Meta: Site Controls

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#1852]
TODO What is the name of this component. 

![screenshot_20190124-103418](https://user-images.githubusercontent.com/122897/51688989-bd81e080-1fc3-11e9-9cec-b0f2e3203333.png)

**Comment by bbinto** [comment]
@st3fan, would you mind writing some user stories issues for this epic?

**Comment by vesta0** [comment]
Dup of Fenix [#227](https://github.com/mozilla-mobile/fenix/issues/227)
