### ISSUE TITLE
Allow some customization for the suggestion item in ClipboardSuggestionProvider

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#1853]
Currently the suggestion item doesn't have an icon, and the title and description is just the URL with no way to identify it being from the clipboard.

I would like to customize the icon and title in the suggestion item generated by [`ClipboardSuggestionProvider`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/ClipboardSuggestionProvider.kt)

**Comment by boek** [comment]
I can open a PR for this :)

**Comment by pocmo** [comment]
This is related to #1367: The providers add some flags to the suggestions that allow the component implementing the awesomebar to make them look differently. This is not implemented by our component yet; it only has a very simple layout that it uses for all suggestions.
What I would like to do as part of #1367 is to find a way how a user of the `browser-awesomebar` component can control the layouts of the suggestions without writing everything from scratch.
