### ISSUE TITLE
Long pressing on link does not display context menu

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#1857]
Long-pressing a URL (ie after google searching) doesn't currently pull up a context menu in RB. Focus is having the same issues since updating ~9 days ago so I think it's GV related and possibly related to https://bugzilla.mozilla.org/show_bug.cgi?id=1522228

From my (short) investigation it seems the URIs we're getting from GV aren't passing isLink() test so there's no menu displayed

**Comment by pocmo** [comment]
It looks like this should be fixed after #1709 lands.

**Comment by csadilek** [comment]
Yes, I've verified that this works again on master!
