### ISSUE TITLE
Move Picture-In-Picture feature to components

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1862]
The feature currently lives in the [Reference Browser](https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/pip/PictureInPictureFeature.kt) but it's abstract enough that we can move it to an existing feature component.

Probably `feature-session` since that's where the `FullScreenFeature` resides as well (although maybe we want to move both to some better place?).

**Comment by ArazAbishov** [comment]
Hi @jonalmeida. I would like to work on this task if it is still available for grabs.

**Comment by pocmo** [comment]
@ArazAbishov Yes, it's still available. As part of this issue we want to move the `PictureInPictureFeature` class into the `feature-session` component. Let us know if you have further questions.

**Comment by ArazAbishov** [comment]
Great, I will take a look then.

**Comment by ArazAbishov** [comment]
@pocmo @jonalmeida The PR https://github.com/mozilla-mobile/android-components/pull/2323 is up. As soon as it is merged into android-components, I will update the reference browser as well.
