### ISSUE TITLE
Miner site problem and Browser History

### ISSUE THREAD

**Issue by jahmadiiiii** [mozilla-mobile/android-components#1864]
When go to site like downloadly.ir Phone hanges cause this have Miner please add miner blocked in all version Of FireFox.

Browser History must encrypt by default to deny accsess other spywares to history.

**Comment by pocmo** [comment]
This seems to be about Firefox Android?

Please file this issue here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android

And I also recommend filing two distinct issues. :)
