### ISSUE TITLE
Upgrade to Kotlin 1.3.20

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1865]
https://blog.jetbrains.com/kotlin/2019/01/kotlin-1-3-20-released/

**Comment by jonalmeida** [comment]
These error messages are so nice!

**Comment by pocmo** [comment]
> e: /Users/skaspari/Projects/Mozilla/android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt: (97, 5): A 'return' expression required in a function with a block body ('{...}'). If you got this error after the compiler update, then it's most likely due to a fix of a bug introduced in 1.3.0 (see KT-28061 for details)

https://github.com/mozilla-mobile/android-components/blob/68c571802597d9a1a9a1713a05c0eb4e4835b193/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt#L91-L97

It's not defined what `getAutocompleteSuggestion` should return if `resultText` is null. (CC @grigoryk)
