### ISSUE TITLE
Solo Browser Action Getting Included in Url Box View 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#1881]
I'm trying to use the toolbar component and customize the URL background and running into an issue where the first browser action I add is getting sucked into the url bounding box, but looking at documentation for `addBrowserAction` it looks like it *should* be on the right side of the toolbar outside the bounding box. 

Screenshot of the solo browser action being included in the URL box layout: 
![screenshot_20190128-154818](https://user-images.githubusercontent.com/25442310/51875876-96a51080-231b-11e9-9bd2-b95f2f27c0e1.png)

Screenshot of adding another browser action (its white and the grid icon, a bit hard to see, sorry!) and that one then gets included and the home icon is "freed"
![screenshot_20190128-154936](https://user-images.githubusercontent.com/25442310/51875874-94db4d00-231b-11e9-903b-7301ba9af1de.png)

Relevant Branch: 
https://github.com/ekager/fenix/tree/url-bar-background

**Comment by jonalmeida** [comment]
I did some investigation and I think our `urlBoxView` is either measured or layed out wrong.

![untitled](https://user-images.githubusercontent.com/1370580/51878331-46d74100-233d-11e9-8deb-9ed74d5fed42.png)

The top picture is the current behaviour of the width with an 8dp `urlBoxMargin`.

The bottom picture is calling layout on the `urlBoxView` up to the visible url bar (`urlView`)

Below is the patch that I used, but I'm wondering if @pocmo knows of a better way to fix this. Should we fix our measure to give us an accurate `measuredWidth` instead?

```diff
diff --git a/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt b/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
index 7e198e82..31c74400 100644
--- a/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
+++ b/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt
@@ -417,7 +417,7 @@ internal class DisplayToolbar(

         urlBoxView?.let { view ->
             val urlBoxLeft = navigationActionsWidth + urlBoxMargin
-            view.layout(urlBoxLeft, 0, urlBoxLeft + view.measuredWidth, measuredHeight)
+            view.layout(urlBoxLeft, 0, urlRight, measuredHeight)
         }
     }
```

**Comment by pocmo** [comment]
Thank you for filing and debugging. I noticed that bug recently too when experimenting with the url box in the reference browser. But I forgot to file :(

> Should we fix our measure to give us an accurate measuredWidth instead?

Yes, this sounds like what we should do here. The view used as "urlBox" may need to know about its own size too. For example Firefor for Echo Show uses a view that also acts as a progress bar. That may break if the measured size is different than the size in the layout.

Let's move this in the sprint. I'll try to take a look today too.

We have some tests for layout/measure but it seems like we are missing one for this exact setup.
