### ISSUE TITLE
Revert CustomTabsConfig workaround Jetifier

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1884]
Context: https://github.com/mozilla-mobile/reference-browser/issues/487

We've found that we need to introduce a small hack in order to stop the jetifier tool from re-writing CustomTabsIntent strings.

Once `1.0.0-beta03` of `jetifier-processor` is published *and* we add it to our classpath, as mentioned in the google tracker [issue 119183822](https://issuetracker.google.com/issues/119183822), we can then go about removing this hack.

**Comment by jonalmeida** [comment]
The PR with commits to revert: https://github.com/mozilla-mobile/android-components/pull/1886

**Comment by pocmo** [comment]
We should be able to do that now. :)
