### ISSUE TITLE
Menu with icons has only partial touch targets

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#1891]
When you have a menu item with an icon, the text of the menu seems to have a separate touch target (that has no action associated) than the rest of the button. If you press on the right or left of the text the button functions as expected.

![menu bug](https://user-images.githubusercontent.com/4400286/51942018-dd9e0f00-23ca-11e9-9f97-28050d4f3fe9.gif)

**Comment by jonalmeida** [comment]
@sblatz this was fixed (on Friday?), do you mind verifying if this is still an issue?
