### ISSUE TITLE
Using browser toolbar inside a ConstraintLayout

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#1893]
I am unable to use the toolbar inside a ConstraintLayout. In order to implement find in page in fenix, I need to put it [above the bottom toolbar](https://github.com/mozilla-mobile/fenix/compare/master...sblatz:add-find-in-page?expand=1#diff-665af00480a4cfd1e86a6260b0a40568R34). When I put it inside a ConstraintLayout the toolbar no longer scrolls off the page, nor does the menu attached to it properly display above it (it goes "off" the screen which can be seen below--there are several other menu options besides "help").

<img width=200 src=https://user-images.githubusercontent.com/4400286/51952873-e274ba00-23ee-11e9-9f78-7c2dd3f82b70.png>

**Comment by pocmo** [comment]
@sblatz I integrated `feature-findinpage` into the reference browser in [this PR](https://github.com/mozilla-mobile/reference-browser/pull/524). I used a custom `CoordinatorLayout.Behavior` to keep the "find in page bar" above the toolbar. Let me know if that helps you with Fenix or if a different solution is needed.

**Comment by jonalmeida** [comment]
@sblatz can we close this?
