### ISSUE TITLE
Memory leak: Session holds long-lived reference to SystemEngineView and its Activity Context

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#1915]
## FFTV background context
In FFTV, we separate our model from view state: model state is held by the `Application` while view state is held by `Activity`/`Fragments`. As part of the model, we hold our the `SessionManager` in `WebRenderComponents` which is held by the `Application`: the Engine, SessionManager, and other components are initialized with the application context. When our Activity is destroyed, e.g. under memory pressure, we keep our model and discard the view state. When the views are restored, we reactively push the data from the model to the view state (via architecture components style MVVM).

A consequence of this is that we keep the session manager, and its sessions, around for the duration of the `Application`. This is intentional: for as long as the application is alive, we don't see any reason to discard the user's browsing state, including tabs.

## Problem: the memory leak
However, we have the following reference hierarchy:
```
FirefoxApplication
- SessionManager (via WebRenderComponents)
 - Session
  - EngineSessionHolder
   - EngineSession (mutable reference but never cleared for lifecycle, only session add/removed)
     is a SystemEngineSession
    - NestedWebView (mutable reference but only written for window feature)
     - Activity Context
```

To emphasize, this means the Application is holding a long-lived reference to an Activity Context beyond the Activity's lifecycle: a common Android memory leak. Analysis with LeakCanary has backed up this theory.

We found this issue as part of the investigations in https://github.com/mozilla-mobile/firefox-tv/issues/1628

## Proposed solution
From a user's perspective, we want to keep their tabs around even when the system kills us to free up resources. Note: we could rely on session restore but that's unperformant and we haven't implemented it yet. As an application, that leaves us with two options:
- Fix the issue within the session: null the WebView reference when the Activity's lifecycle ends
- Fix the issue outside of the sessions: remove the sessions when the Activity's lifecycle ends and restore later (i.e. session restore)

Speaking with Christian, we noticed that `Session.link` and `unlink` remove the `EngineSession` from the `Session`, nulling the WebView reference. These are private so the app can't call them but `Session.add` and `remove` will call through to these methods. As such, we decided that at the end of the Activity's lifecycle, we can:
- Remove all the sessions, unlinking them from the SystemEngineView
- Cache the sessions in the application's memory
- Restore these cached sessions when the new Activity begins

Here's the code:
```kotlin
class WebRenderComponents {
    ...
    val cacheSessions = mutableListOf<Session>()
}

class MainActivity {
    ...
    override fun onStart() {
        with(application.webRenderComponents) {
            if (cacheSessions.size != 0) {
                cacheSessions.forEach {
                    sessionManager.add(it)
                }
                cacheSessions.clear()
            }
        }
    }

    override fun onStop() {
        with(application.webRenderComponents) {
            cacheSessions.addAll(sessionManager.all)
            sessionManager.removeAll()
        }
    }
}
```

Note: we still need to decide which lifecycle methods to use.

**We decided to test this code change in the application, in case it has bugs, for a few weeks before moving this implementation to components** because the application should not be handling this.

LeakCanary is catching other leaks so it's hard to say if it's fixed on LeakCanary alone. However, fixing this issue also fixed https://github.com/mozilla-mobile/firefox-tv/issues/1761, identifying that there is indeed a problem.

## Discarded solutions
The WebView javadocs recommend constructing the WebView with an Activity context and we do (in `WebViewCache.getWebView` when we create the `SystemEngineView`) so we can't pass in an `Application` context.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1346)

**Comment by csadilek** [comment]
Thanks @mcomella for the great summary! While we're testing our solution in FireTV, I will investigate and come up with a proposal how to fix this in A-C. So, assigning this to me.

/cc @pocmo

**Comment by pocmo** [comment]
> A consequence of this is that we keep the session manager, and its sessions, around for the duration of the Application. This is intentional: for as long as the application is alive, we don't see any reason to discard the user's browsing state, including tabs.

👍  That's definitely how we intent it to be used too :)

```
   - EngineSession (mutable reference but never cleared for lifecycle, only session add/removed)
     is a SystemEngineSession
    - NestedWebView (mutable reference but only written for window feature)
     - Activity Context
```

This is the part I do not fully understand. In AC we create the internal WebView from the application context and not the activity context (on purpose so that we can keep on to it longer than the activity lifecycle).

**Comment by mcomella** [comment]
> In AC we create the internal WebView from the application context and not the activity context (on purpose so that we can keep on to it longer than the activity lifecycle).

The application [creates the `SystemEngineView`](https://github.com/mozilla-mobile/firefox-tv/blob/71f193efaff95aeef93727f587557a63c279c812/app/src/main/java/org/mozilla/tv/firefox/webrender/WebViewCache.kt#L65-L72) and will usually pass in the Activity context (because it's created in XML). According to Christian, we're actually supposed to create the `SystemEngineView` [through `SystemEngine.createView`](https://github.com/mozilla-mobile/android-components/blob/539c0b34ff1ac417761969fea378f59d407b2584/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngine.kt#L35) but this also does not modify the context used.

fwiw, the WebView documentation recommends using the Activity context to instantiate:
> Note: WebView should always be instantiated with an Activity Context. If instantiated with an Application Context, WebView will be unable to provide several features, such as JavaScript dialogs and autofill.

I don't know if this refers to standard implementations for JS dialogs and autofill or that you can't use these features at all. I'm also concerned about what other functionality will not work in the WebView if used with the Application Context.

**Comment by pocmo** [comment]
> The application creates the SystemEngineView and will usually pass in the Activity context (because it's created in XML)

That's totally fine. The WebView inside the Session object is not created from that Context though.

**Comment by mcomella** [comment]
> > The application creates the SystemEngineView and will usually pass in the Activity context (because it's created in XML)
> 
> That's totally fine. The WebView inside the Session object is not created from that Context though.

Spoke with Christian and confirmed that was the case. The default argument that creates a NestedWebView in `SystemEngineView.initWebView` was misleading to me: I filed #1944 to add clarifying comments.
