### ISSUE TITLE
Concept component for push

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1916]
We need to create an abstraction that allows us to implement different push messaging platforms.

The ones we currently need are FCM (#1917) and ADM (#1918).

On top of this, we need to build our feature components for [Send Tab](#1921) and [push for web content](#1920) but this is out of scope for now though we should investigate what this would require to attach to an engine (#1919).

There's a good chuck of Fennec code that we can leverage as well: Starting point to read: https://dxr.mozilla.org/mozilla-central/source/mobile/android/services/src/main/java/org/mozilla/gecko/fxa/devices/FxAccountDeviceRegistrator.java

**Comment by pocmo** [comment]
Something to consider: The concept (and/or the actual implementation, e.g. for FCM) needs to allow re-routing of some ("untouched") messages to third-party consumers of push that do not know about whatever abstraction we define here. One such example is the `Leanplum` SDK which will require to get (some) push notification that arrive via FCM.
