### ISSUE TITLE
Create FCM implementation of concept-push

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1917]
A ~`browser-push-fcm`~ `lib-push-fcm` component for Firebase Cloud Messaging.

We should take some ideas from Fennec's implementation but remember that it's still using parts of the old GCM client.

Starting point to read: https://dxr.mozilla.org/mozilla-central/source/mobile/android/services/src/main/java/org/mozilla/gecko/fxa/devices/FxAccountDeviceRegistrator.java

**Comment by pocmo** [comment]
nit: I suggest using the `lib-` prefix since they may be useful for other apps like Lockbox too. I assume the push components themselves will have no knowledge of anything "browser"-related?
