### ISSUE TITLE
Find in page browser component

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#192]
As part of mozilla-mobile/focus-android#967 we're going to add the ability to find text in a page. I think it makes sense to componentize JavaScript/WebView communication. Would we want a UI component as well?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1353)

**Comment by pocmo** [comment]
See comment in https://github.com/mozilla-mobile/focus-android/issues/967 - WebView has APIs for that. No JavaScript needed. :)

We want to add something for that to engine(-gecko/webview) here. But it will take some time until the engine component is ready to be used in Focus. So for now I recommend to use the WebView APIs in Focus and request the matching GeckoView APIs as soon as possible!

**Comment by boek** [comment]
Ah! How did I miss that! That makes this quite a bit easier :)
