### ISSUE TITLE
Observe session based on a provided session ID

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1940]
We tend to use the same bit of code for observing the correct session in most of our features to support Custom Tabs.

We should add this to `SelectionAwareSessionObserver` as an extension function or something similar that abstracts out this logic:
```kotlin
val session = sessionId?.let { sessionManager.findSessionById(sessionId) }
session?.let { observeFixed(it) } ?: observeSelected()
```

**Comment by RomanWuattier** [comment]
Hey, I would enjoy working on this issue. Can I?

**Comment by jonalmeida** [comment]
Go for it! :)
