### ISSUE TITLE
Create feature-sitepermissions component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#1949]
This component will be responsible for consuming `PermissionRequest` instances from the `Session` and display a permission prompt UI to the user.

The rough flow of the component should be:

* (1) On content permission request:
  * Show permission request UI

* (2) On Android permission request:
  * Invoke app callback to let app handle request

* (3) Provide callback for app to notify component about granted/denied permissions

Later when adding a site permission database the first case will be extended to:

* (1) On content permission request:
  * Lookup site in permission database
    * If permission was already granted auto-grant permission request from engine
    * If permission was not granted before show permission request UI
       * Update database to remember user choice

I'll file a separate issue for the permission database. So this initial implementation does not require it.

**Comment by cpeterso** [comment]
Here is the GV bug to add the permission request API: https://bugzilla.mozilla.org/show_bug.cgi?id=1524489

**Comment by Amejia481** [comment]
@cpeterso these are also bug related to site permissions:
https://bugzilla.mozilla.org/show_bug.cgi?id=1527056
https://bugzilla.mozilla.org/show_bug.cgi?id=1527074
