### ISSUE TITLE
Can't run sample in emulator via AS: not bundling x86 deps? (improve docs?)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#197]
I built the default AS configuration, which uses the `samples-browser`module, but am unable to run due to: `INSTALL_FAILED_NO_MATCHING_ABIS`. I assume it's because the sample is bundling the Gecko AARs which don't have an x86 variant.

**Comment by mcomella** [comment]
I discovered the x86 dependencies:

https://github.com/mozilla-mobile/android-components/blob/master/samples/browser/build.gradle#L47-L48

Maybe we should include some docs (in the readme?) about how to run the sample.

**Comment by pocmo** [comment]
No we have multiple build variants for the app:
* geckoview channel (nightly, beta, production) X processor architecture (arm, aarch64, x86).
