### ISSUE TITLE
[Feature][Custom Tabs] Prevent onBackPressed when it's not initialized

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#1970]
Original report: mozilla-mobile/fenix#389

https://github.com/mozilla-mobile/android-components/blob/master/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt#L137

Even in a state where we're not running in a custom tab we're calling the `closeListener`.

**Comment by pocmo** [comment]
Oh yes, if this is not a CustomTab then this should be a no-op. CC @jonalmeida

**Comment by boek** [comment]
got a PR just about to open
