### ISSUE TITLE
Create a menu that uses a specific session

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1975]
In our current menus, we act mostly on the selectedSession, however, this does not take into account a Custom Tab session that will not be the selected session. We have to pass in the appropriate session so that menu items will behave correctly based on that session and it's attributes.

There may be some/no work for a-c and only apps that need to implement this change, but I'm filing it here to track for now.

**Comment by pocmo** [comment]
My gut feeling is that we should stop trying to have "one menu to rule them all" defined globally. Instead the app should define two menus (normal, custom tab, ..) and keep them local to the integration class.

**Comment by jonalmeida** [comment]
This is the path I was going to go down today. :)

**Comment by jonalmeida** [comment]
To be clear in this ticket: we need a separate menu not only because of needing to pass the sessionId for these specific actions, but also the menu items itself would need to be different, and CT sessions would also need to add their own menu items at the bottom (top in Fenix).

**Comment by jonalmeida** [comment]
We should probably implement the menu items for CT similar to the designs here: https://github.com/mozilla-mobile/fenix/issues/203#issuecomment-463426620

**Comment by jonalmeida** [comment]
This is done by @pocmo in r-b. I'll create a ticket for Fenix to implement the same.
