### ISSUE TITLE
Meta: Push / Send Tab Components

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#1983]
This feature is detailed on its own board at https://github.com/orgs/mozilla-mobile/projects/19

**Comment by cpeterso** [comment]
@st3fan, is this meta issue about sending tabs to other devices and not about the [Web Push Notification](https://developers.google.com/web/fundamentals/push-notifications/) API for Service Workers?

**Comment by grigoryk** [comment]
@cpeterso Web Push API is currently not scoped for the Fenix MVP. This is about push-driven send-tab. This work _will_ put into place some of the fundamental pieces we'll need for the Web Push API.

**Comment by jonalmeida** [comment]
I'm going to close this as fixed and completed. 🙂
