### ISSUE TITLE
Notify a11y of page loading progress

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#1991]
When using Talkback, clicking on web content performs the click but we never know if the page is loading or has completed loading.

Thoughts?

**Comment by pocmo** [comment]
If I remember we added some `announceForAccessibility` calls for that to Focus.

**Comment by pocmo** [comment]
@eeejay What's your opinion here? Is that a good thing to do? Should we fix that for Fenix MVP?

**Comment by eeejay** [comment]
I thought I fixed that in pull #2526, is this another issue?

**Comment by pocmo** [comment]
Oh, yes, you are right. Closing. :)
