### ISSUE TITLE
Docs unavailable: "mozac.org" redirect breaks CSS, internal links

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#2011]
Going to https://mozilla-mobile.github.io/android-components/, it automatically redirects to https://mozac.org/ However, this page:
- Has broken CSS
- Has broken links, e.g. clicking on API Reference 404s: https://mozac.org/android-components/reference/

**Comment by pocmo** [comment]
I reverted the change. https://mozilla-mobile.github.io/android-components/ should stop redirecting soonish.

**Comment by pocmo** [comment]
Re-enabled the new domain and fixed the base domain so that everything should be working again.
