### ISSUE TITLE
[Feature][History] Store website title along with URL

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#2015]
In Fenix we want to expose the website title along with the URL. It would be nice to get a structure that holds both :+1:

**Comment by pocmo** [comment]
I think we already store the title.

CC @grigoryk

**Comment by boek** [comment]
https://github.com/mozilla-mobile/android-components/blob/master/components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt#L37 Then we'll just need to expose it here. I can take a whack at it :+1:

**Comment by pocmo** [comment]
@boek `getVisited()` is a wonky API that only exists to feed that data back into a `WebView`. It's not really meant to be used for building the history UI. @grigoryk may know what kind of access methods we have in the pipeline.

**Comment by boek** [comment]
@pocmo That makes sense. I will welcome anything else
