### ISSUE TITLE
Allow background color theming of toolbar menu

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#2024]
It'd be great if we could theme this background color to better match the theme of Fenix!

<img width=300 src=https://user-images.githubusercontent.com/4400286/52659325-e1915d00-2eb1-11e9-93c5-0ece400cc170.png>

**Comment by pocmo** [comment]
@sblatz Do you prefer to set the color in the theme or do you need something that is more dynamic?

**Comment by sblatz** [comment]
Settings from the theme is fine as long as I know the attribute it's pulling from 😄

**Comment by pocmo** [comment]
We definitely need to add something custom. Under the hood we are using `CardView` and the menu inherits the CardView style (but we should make it possible to pick an independent background color):
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/cardview/res/values/styles.xml
