### ISSUE TITLE
[browser][menu] Give ability to color the text in a menu item

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#2028]
For destructive actions I would like to make the text red on a menu item

**Comment by pocmo** [comment]
@boek Do you have an example in the Fenix app or a mock that shows that?

**Comment by boek** [comment]
@pocmo no, but in the library items will have a menu button that will have Delete as an option. Would like to make the text red for destructive actions

<img width="325" alt="image" src="https://user-images.githubusercontent.com/1250545/52872002-3fb37f80-3100-11e9-9d2f-f0b60e853f59.png">

**Comment by pocmo** [comment]
Ah, nice, thanks! That makes sense.

**Comment by pocmo** [comment]
Hey @sblatz. Since you know about the internals of `BrowserMenu` now... maybe that's something you want to pick up? :)

Since that is something that would be customized on "item level", I guess we'd want to add a new parameter for that to at least `SimpleBrowserMenuItem`?

**Comment by sblatz** [comment]
Happy to grab this!
