### ISSUE TITLE
EditToolbar cancelView appearing very small (and not visible on light theme)

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#2054]
See Fenix issue for context: https://github.com/mozilla-mobile/fenix/issues/478

Two issues: 
1. The cancelView is not visible on our light theme, I think we will need an attr to set this with theme changes like the other icons?
2. The cancelView is very small (when visible). We are now adding the toolbar dynamically so I wonder if measuring is wonky somehow since I don't see this in RB.

![screenshot_20190213-111259](https://user-images.githubusercontent.com/25442310/52737502-5b444c00-2f81-11e9-92ec-b457125fe7c9.png)

**Comment by pocmo** [comment]
@ekager I remember some discussion about whether we should have the ability to hide the cancel view or whether it should only clear the field and not close edit mode. Do you know what the state of that is? Happy to add anything
