### ISSUE TITLE
BrowserToolbar enters Display Mode onURLEntered flashing in Fenix SearchFragment

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#2077]
Currently, BrowserToolbar enters display mode when a URL is entered, but in Fenix we have two separate fragments for display + edit (SearchFragment and BrowserFragment) and on slow phones you can see a flash of display mode in the SearchFragment right after the URL is entered. Would it be possible to not automatically enter displayMode here or we can brainstorm other solutions too! 

```
internal fun onUrlEntered(url: String) {
        displayMode()

        urlCommitListener?.invoke(url)
    }
```

**Comment by cadeyrn** [comment]
> on slow phones you can see a flash of display mode in the SearchFragment right after the URL is entered.

Not only on slow phones. I have a HTC U11, that's a high-end device and there you see the same issue. ;-)
