### ISSUE TITLE
Add Browser Utils for Default Browser Logic 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#2078]
[Discussed in Fenix](https://github.com/mozilla-mobile/fenix/issues/420), we want to be able to determine if we are the current default browser. Focus [had a Util File for it](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/Browsers.java), if this could be useful across multiple Android browsers, should we make it part of AC?

**Comment by pocmo** [comment]
> should we make it part of AC?

Yes, this looks like a great candidate! :)
