### ISSUE TITLE
telemetry: Failed to resolve dependencies

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#208]
### Steps to reproduce
Downloaded .zip from https://github.com/mozilla-mobile/firefox-tv and extracted.
Opened Android Studio 3.1.2 and imported the extracted file as a new project.
Let Android Studio build the app

### Expected behavior
The application should build without error

### Actual behavior
App does not build
Message of "Failed to resolve: org.mozilla.telemetry:telemetry:1.2.0" is displayed.  This references line 168 in app, that states "implementation 'org.mozilla.telemetry:telemetry:1.2.0'"

### Device information
Android Studio 3.1.2 on Ubuntu 18.04

---

Speaking with csadilek and pocmo, it sounds like this is a configuration issue on bintray's end. See also https://github.com/mozilla-mobile/firefox-tv/issues/918

**Comment by pocmo** [comment]
It's now back on jcenter (with the new group id). Latest version:
```
org.mozilla.components:telemetry:0.7
```

**Comment by mcomella** [comment]
@facekunal I believe this should be fixed in master in Focus: see https://github.com/mozilla-mobile/focus-android/issues/2657#issuecomment-392488337

Older builds will still be broken because we haven't gotten the old group ID to work correctly.

**Comment by pocmo** [comment]
I'm going to close this. I don't think it is worth getting the old libraries back and it's quite straight-forward to use the library with the new group ID if an old branch needs to be build.
