### ISSUE TITLE
browser-icons: Add support for SVG favicons

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2081]
Related resources:
* https://caniuse.com/#feat=link-icon-svg
* https://bugzilla.mozilla.org/show_bug.cgi?id=366324

Like for ICO we would need to ship our own decoder (How much code is that?).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1533)

**Comment by pocmo** [comment]
As an example twitter had a mask icon in its list (#3294):
https://abs.twimg.com/responsive-web/web/icon-svg.9e211f626ec9d2812.svg

**Comment by NotWoods** [comment]
Filed BZ-1650692. Looks like an API has been added but isn't public.

**Comment by unrelentingtech** [comment]
This also affects PWA (Web Manifest) icons :(

https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/feature/pwa/src/main/java/mozilla/components/feature/pwa/WebAppShortcutManager.kt#L270-L273

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793165

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
