### ISSUE TITLE
Reverse dependency: concept-engine -> browser-errorpages

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2102]
The concept shouldn't depend on an implementation of error pages.

It looks like the concept depends on the `ErrorType`. In this case the `ErrorType` should live in the concept. Only the mapping from `ErrorType` to strings etc. should live in `browser-errorpages`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1552)

**Comment by jonalmeida** [comment]
This was my error as well when trying to figure out where to place the ErrorType. An open sealed class in the concept-engine might solve this:
```kotlin
sealed class ErrorType(@StringRes open val titleRes: Int, @StringRes open val messageRes: Int)
```

**Comment by jonalmeida** [comment]
This is going to take a some strategic thinking since there are [multiple consumers](https://searchfox.org/mozilla-mobile/search?path=&q=ERROR_NET_TIMEOUT) that we need to inform or fix when we break this API.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794663

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
