### ISSUE TITLE
Engine: Expose setAutomaticFontSizeAdjustment()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2105]
Fenix issue:
https://github.com/mozilla-mobile/fenix/issues/577

GeckoView:
https://bugzilla.mozilla.org/show_bug.cgi?id=1460874

GeckoView landed an API to use the system font size for non-mobile pages. Let's see if we want to expose this as part of the Engine/Settings interface. Since this is an API on `GeckoRuntimeSettings` we could also consider punting on this and let the app handle it.

**Comment by buttercookie42** [comment]
> [...] to use the system font size for non-mobile pages

And also scale mobile pages as well, provided the OS-level font size setting is set to anything larger/smaller than the default value of "normal".
