### ISSUE TITLE
Allow theming of InlineAutoCompleteEditText cursor

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#2107]
We should surface the ability to change the cursor color for the edit text box.

**Comment by sblatz** [comment]
(I'd be happy to work on this!)

**Comment by pocmo** [comment]
@sblatz I think the cursor will use the `accent` color of the theme:
![image](https://user-images.githubusercontent.com/89638/53030510-35c8ae00-346b-11e9-83ee-c006f3dbcf8d.png)

(Image from: https://www.appcelerator.com/blog/2015/07/understanding-the-android-material-theme/)

**Comment by sblatz** [comment]
Ah, my bad! Thanks for the heads up :)
