### ISSUE TITLE
Do we need a permission for local storage?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2122]
The site permission mocks show a prompt for local storage. But we do not have anything for that in our permission list.

**Comment by Amejia481** [comment]
Maybe the site could use this permission for using a service worker to cache some file?

**Comment by Amejia481** [comment]
Related bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1527074

**Comment by Amejia481** [comment]
It looks like the GV issue was fixed. Now we can implement it on AC. Let's use #3153  for that.
