### ISSUE TITLE
Do we need a permission for bluetooth?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2123]
The mocks show a site permission prompt for bluetooth. But it looks like that's something that Gecko doesn't support?

**Comment by Amejia481** [comment]
We don't have a GV api for that

**Comment by kbrosnan** [comment]
The Gecko bug is https://bugzilla.mozilla.org/show_bug.cgi?id=674737 and discussion about Mozilla's position on the standard is at https://github.com/mozilla/standards-positions/issues/95

**Comment by Amejia481** [comment]
thanks @kbrosnan
