### ISSUE TITLE
Investigate unknown site permissions

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2129]
We do have the following additional permissions. How can they be triggered? Do we need prompt UI for them?

- ContentAudioCapture
- ContentAudioOther
- ContentVideoCapture
- ContentVideoApplication
- ContentVideoBrowser
- ContentVideoScreen
- ContentVideoWindow
- ContentVideoOther
- Generic

**Comment by Amejia481** [comment]
I was wonder the same, let's investigate about it! 👍

**Comment by Amejia481** [comment]
Issue this bug for getting more info from GV team!
https://bugzilla.mozilla.org/show_bug.cgi?id=1533575

**Comment by pocmo** [comment]
@Amejia481 Did you follow those constants back to the engine implementation? It's very well possible that some of them only apply to WebView. :)

**Comment by Amejia481** [comment]
Yes, I did the mapping can be found here on [GeckoPermissionRequest.kk](https://github.com/mozilla-mobile/android-components/blob/84345a0bafb9b760953a1d583aa2af04a0271fea/components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoPermissionRequest.kt#L131) :)
