### ISSUE TITLE
Implement decoder using ImageDecoder

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2131]
On API 28+ we can use `ImageDecoder`:
https://developer.android.com/reference/android/graphics/ImageDecoder

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1591)

**Comment by Amejia481** [comment]
@pocmo  what are we going to use for backward compatibility? Is there any `CompatImageDecoder`?

**Comment by pocmo** [comment]
#2059 -> [BitmapFactory](https://developer.android.com/reference/android/graphics/BitmapFactory.html)

**Comment by colintheshots** [comment]
FWIW, they've promised a support library for ImageDecoder for many months now. BitmapFactory will work for the moment, as I have no idea when that support library will land.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793168

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
