### ISSUE TITLE
Add support for searchDefault in list.json

### ISSUE THREAD

**Issue by mkaply** [mozilla-mobile/android-components#2132]
Currently the SearchEngineManager appears to use the first engine in the list of engines from list.json as the default.

This means that if you add a search engine that replaces a built in engine, you have to include your own list.json so you can set your new engine as the first engine.

We should add the value searchDefault to list.json and use that. It might mean that we have to read the XML of the engines to get the search engine name, similar to what we did on Fennec.

https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/search/SearchEngineManager.java#578

**Comment by mcomella** [comment]
@mkaply @pocmo Is this a dupe of #2371?

**Comment by mkaply** [comment]
yep.
