### ISSUE TITLE
BrowserToolbar: Apply security icon colours on init

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2151]
We apply the colours when the security state changes only, but not on initialize.

This can be seen in Fenix and Custom Tabs in r-b.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-1613)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796299

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
