### ISSUE TITLE
Doorhanger card doesn't have much margin from the window edges

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2198]
From the screenshot below, you can see the card is touching the edge of the window and looks a bit off. You aren't able to properly see the rounded corners as expected as well.

<img width="901" alt="screen shot 2019-02-26 at 9 56 22 am" src="https://user-images.githubusercontent.com/1370580/53422480-91d08c80-39ad-11e9-971d-5df52b63d9a7.png">

Comparing it to other system doorhangers, this is how I would have expected it to be spaced out.

<img width="851" alt="screen shot 2019-02-26 at 9 58 28 am" src="https://user-images.githubusercontent.com/1370580/53422541-a9a81080-39ad-11e9-91c2-4986536907c1.png">

**Comment by jonalmeida** [comment]
This might be something for https://github.com/mozilla-mobile/android-components/issues/2125?

**Comment by pocmo** [comment]
Yes, #2125 is to make sure that we support the Fenix style. 

Note that the prompts are going to be full size and are not following the guidelines for heads-up notifications, see mocks in https://github.com/mozilla-mobile/fenix/issues/332

**Comment by jonalmeida** [comment]
Gotcha, I'm going to close this then since there are issues that already cover this.
