### ISSUE TITLE
Add ability to invalidate BrowserMenuItemToolbar items

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#2212]
As part of #2211, I noticed that there is not a simple way to invalidate the menu items/rebind them (for a two-state menu button, we may want to change the state of the button when some other state changes in the app i.e. loading). 

There seems to be a toolbar invalidate method, maybe we could add something similar for the menu.

**Comment by jonalmeida** [comment]
The Fenix issue that's related to this: https://github.com/mozilla-mobile/fenix/issues/654

Closing this for https://github.com/mozilla-mobile/android-components/issues/170 since the Fenix issue references that issue already.
