### ISSUE TITLE
[SessionBundleStorage] SQLiteBlobTooBigException: Row too big to fit into CursorWindow

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#2216]
https://github.com/mozilla-mobile/fenix/issues/715

It looks like if you add too many sessions you will eventually break SessionBundleStorage. Is this something we should handle in Fenix?

**Comment by kbrosnan** [comment]
Fenix about data URI is nearly 22,000 characters long. 4-8 copies of this URI crashes Fenix in an unrecoverable state.

**Comment by boek** [comment]
Oh we're passing the logo in base64 in the url? I'm going to fix that too :|

**Comment by pocmo** [comment]
Ouch!

While we should try to not blow up ourselves with big data uris.. this seems to be a problem we could hit regardless - although I would love to know how big that row actually was and how that compares to a "regular sized" session.

**Comment by pocmo** [comment]
If that is going to be a problem then we may need to save that state to disk and only reference the file from the database 🤔
