### ISSUE TITLE
[SessionManager] Provide APIs to remove just normal sessions or private sessions

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#2217]

**Comment by pocmo** [comment]
@boek We may have something for that in [TabsUseCases](https://mozac.org/api/mozilla.components.feature.tabs/-tabs-use-cases/) already. Maybe [RemoveAllTabsUseCase](https://mozac.org/api/mozilla.components.feature.tabs/-tabs-use-cases/-remove-all-tabs-use-case/)?

**Comment by boek** [comment]
Ah yes! This works for me!
