### ISSUE TITLE
"[ci skip]" in PR title no longer has effect

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2221]
In this PR, you can see the issue take place: https://github.com/mozilla-mobile/android-components/pull/2220

The TC push and PR tasks were both created and the full list of jobs were run.

**Comment by pocmo** [comment]
On push always all tasks are run.

On the PR task there's only the decision task and it correctly did not schedule any additional tasks:
https://tools.taskcluster.net/groups/RMT_IjY6Ttmo4bxL_VgLQA

I think that is working as expected. :)

**Comment by jonalmeida** [comment]
Odd. I see two TC tasks. A 'pull request' and a 'push' task: the push task has all the components being built.

Here's the push task link that I see on the PR: https://tools.taskcluster.net/groups/OJYDaaQqQdy_Nb4bC6YGmQ

**Comment by pocmo** [comment]
Yes, you see a "push" task since you create the branch in this repository (and not your fork); and yes, for pushes we run all tasks (by design; and well, push tasks do not have a "PR title").

**Comment by jonalmeida** [comment]
Oh I understand now, thanks for clarifying!
