### ISSUE TITLE
Provide secure implementation of AccountStorage

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#2229]
This is so we have an encrypted `AccountStorage` implementation to be used by Fenix.

**Comment by rfk** [comment]
Related: https://github.com/mozilla-mobile/reference-browser/issues/121

Would this mean that the user has to "unlock" the app before it can sync, rather than syncing periodically in the background?

**Comment by csadilek** [comment]
I forgot that lib-dataprotect requires API 23. Changing the title for now.

**Comment by pocmo** [comment]
> https://mozilla-mobile.github.io/android-components/changelog#0450

I came here to mention that :D

**Comment by grigoryk** [comment]
Marking as "maybe" right now because the current behaviour is in-line with what Fennec does. This will be an improvement.

**Comment by sarentz** [comment]
Moving out of Fenix backlog - we will document this choice.

**Comment by rfk** [comment]
> I forgot that lib-dataprotect requires API 23

From slack conversations, I got the impression that we may have found a way to lower this requirement by falling back to a different crypto method (RSA instead of AES maybe?).

**Comment by mcomella** [comment]
> > I forgot that lib-dataprotect requires API 23
> 
> From slack conversations, I got the impression that we may have found a way to lower this requirement by falling back to a different crypto method (RSA instead of AES maybe?).

Here's [a list of the supported ciphers](https://developer.android.com/training/articles/keystore#SupportedCiphers) at which API levels. Before deciding, please also test on Fire TV hardware which may support a different subset at various API levels.

**Comment by grigoryk** [comment]
Blocked on https://github.com/mozilla-mobile/android-components/issues/5004
