### ISSUE TITLE
CrashReporter.instance is not thread-safe

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#2232]
We require that apps call `install` in `Application.onCreate`: https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt#L172

The processing of crashes happens on a different thread: https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/src/main/java/mozilla/components/lib/crash/handler/CrashHandlerService.kt#L17

We don't guarantee the visibility of `CrashReporter.instance` across threads.

**Comment by csadilek** [comment]
@pocmo was just helping the GV team investigate why they were seeing this error. This was not the cause, but this still looks like a bug to me. Wdyt?

**Comment by pocmo** [comment]
Yep, that looks wrong and those are definitely running on different threads.
