### ISSUE TITLE
Implement better handling of back press when keyboard is showing on search bar

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#2255]
Per recommendation [here](https://github.com/mozilla-mobile/fenix/issues/847), it'd be great if our "hide keyboard" button also called `onBackPressed`.

It seems like we can achieve this by [listening to `KeyEvent.BACK`](https://stackoverflow.com/questions/8080711/android-back-key-event-while-displaying-soft-keyboard)

**Comment by sblatz** [comment]
I'm happy to work on this, but want the a-c team's input on whether or not they think this is a good idea :)

**Comment by pocmo** [comment]
Yes, I think that is a great idea. I thought that may not really be possible since the keyboard is handling the back button key. But since Chrome can do it .. there's a way. :)

`onKeyPreIme` from the linked Stackoverflow posting looks good. :)

**Comment by Cheap-Skate** [comment]
Thanks!
