### ISSUE TITLE
Investigating about how  "Don't ask again on this site" checkbox should work on a site permissions prompt?

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#2287]

**Comment by Amejia481** [comment]
Hi @brampitoyo,
I have some questions about the checkbox, could you help me to clarify please :)

As I could see on https://github.com/mozilla-mobile/fenix/issues/332 , not all permissions will include the "Don't ask me again for this site?" check box, only location, camera, and microphone, but never for  **Camera + Microphone (together)**. 

1. The behavior that I see now, in Fennec is that the check box acts remembering the user selection.
 For instance, if I go to a site that requires location and I tap **"Allow"** with the check box checked, next time that I visit the site location will be auto granted and the same case with **"Don't Allow"**. Do we want the same behavior right?

2. The only way, that user can change its decision is through the **"clear the permission"** button?
![image](https://user-images.githubusercontent.com/773158/53988409-63f7f000-40f1-11e9-9d05-4a776dc202a5.png)

**Comment by brampitoyo** [comment]
@Amejia481 

> […] not all permissions will include the "Don't ask me again for this site?" […] never for Camera + Microphone (together).

This is my mistake. I should’ve included the “Don’t ask me” checkbox for Camera + Microphone (together).

I’ll update issue #332, but just to double clarify of what screen this refers to:

<img width="360" src="https://user-images.githubusercontent.com/51007/54092372-3a401100-43f0-11e9-91a1-b652bffb5122.png">

-----

> 1. The behavior that I see now, in Fennec is that the check box acts remembering the user selection […] Do we want the same behavior right?

Yes. We do want the same behaviour as Fennec.

-----

> The only way, that user can change its decision is through the "clear the permission" button?

Correct.

As you noted, this button is located deep within Settings. How can a user access it easily?

As I explained on https://github.com/mozilla-mobile/fenix/issues/191#issuecomment-460509170

> 1. On the bottom of the site info panel, there’s a link called “Manage site permissions”
> 2. When tapped, it takes you to:
>    **Settings > Advanced > Site permissions > Exceptions > {domainName}**

![Slice@2x](https://user-images.githubusercontent.com/51007/54092499-b7b85100-43f1-11e9-8f95-33b9d6cad9db.png)

**Comment by Amejia481** [comment]
Hi @brampitoyo,
I have some questions about the permission prompt  and how it should behave:

**How the prompt should behave when a Camera + Microphone permission is requested when the followed conditions are met at the same time:** 

1. You have visited this site and granted the Camera permissions and checked “Don’t ask me” checkbox.
2. You have visited this site and blocked the Microphone permissions and checked “Don’t ask me” checkbox.

Should the prompt be shown always?
If the prompt must be shown, and the user grant 2 (Microphone permissions with “Don’t ask me” checkbox). When the user visit this site again and the site requests the Microphone permission, should it be auto-granted or the prompt should be shown?

Thanks in advance :)

**Comment by brampitoyo** [comment]
Hi @Amejia481, in that scenario, we want to show the Microphone permissions only.

Auto-granting permission would be doing too much, but showing the prompt for camera+microphone would be too much.

So, we should only show the permission of the feature that was previously blocked.

Does that sound reasonable to you?
