### ISSUE TITLE
PWA: Support splash screen

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2294]

**Comment by NotWoods** [comment]
We can display the splash screen until first paint.
[`GeckoSession.ContentDelegate#onFirstComposite`](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.ContentDelegate.html#onFirstComposite-org.mozilla.geckoview.GeckoSession-)
