### ISSUE TITLE
Implement GeckoWebNotificationDelegate

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2295]
Waiting for GeckoView API.

**Comment by cpeterso** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1533057

**Comment by cpeterso** [comment]
The Web Push API landed in GV 70 Nightly on 2019-08-21:

https://bugzilla.mozilla.org/show_bug.cgi?id=1533057#c11

**Comment by jonalmeida** [comment]
Looking at [the API docs](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/WebNotificationDelegate.html), this is an engine delegate as opposed to an engine session one which we usually have.

I imagine we can follow a similar pattern and have engine observers that are connected to a notification manager that handles showing the android OS notification/dismissal.

For `WebNotificationDelegate#onCloseNotification`, aside from notifying observers, I'm not sure what we should do with it or apps could do with it. 🤔

**Comment by pocmo** [comment]
> For WebNotificationDelegate#onCloseNotification, aside from notifying observers, I'm not sure what we should do with it or apps could do with it. 🤔

Remove the notification if it is still showing? 🤔

**Comment by jonalmeida** [comment]
> Remove the notification if it is still showing? 🤔

I believe this maps to the Web API [`onClose`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/onclose) which I imagine would be invoked when we call [`close`](https://developer.mozilla.org/en-US/docs/Web/API/Notification/close) (GV is [`dismiss`](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/WebNotification.html#dismiss--)) on it.

If that's true, then this would be for other observers to know a user interacted and dismissed the notification. 

It is still true, that we may also want to also ensure that the no notification is showing if we have to programatically close all notifications for currently unknown reasons.

**TODO:** observe all interactions possible with WebNotifications in Desktop and Chrome Android to compare.

**Comment by pocmo** [comment]
I assume its triggered by this:
https://developer.mozilla.org/en-US/docs/Web/API/Notification/close

And we need to know that we need to cancel the notification if JS decides to close it?
