### ISSUE TITLE
Inline `JSONArray.mapNotNull` when android gradle plugin 3.4.0 is released

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#2305]
From https://github.com/mozilla-mobile/android-components/pull/2279#issuecomment-471133448:

> This issue is caused because the google android gradle plugin instruments methods before they are inlined, which breaks jacoco when testing across module boundaries: https://issuetracker.google.com/issues/109771903 (and jacoco [jacoco/jacoco#688](https://github.com/jacoco/jacoco/issues/688) which was closed in favor of the google issue). This is fixed in 3.4.0 (current is 3.3.0, released in January).
> 
> The function is inlined for performance (like Collection.map) so the solution is to temporarily uninline it and wait for the version bump.

We should inline `JSONArray.mapNotNull` when gradle gradle plugin 3.4.0 is released.

**Comment by dector** [comment]
@mcomella Your fixes can be merged after #3471 .
