### ISSUE TITLE
:service-pocket endpoint URLs should be overridable by application

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#2337]
For all intents and purposes, the Pocket endpoint URLs are hard-coded into android-components: `PocketEndpoint` creates `PocketURLs` with hard-coded urls and passes it to `PocketEndpointRaw`.

This is a problem in a few scenarios:
- We want to override a URL for local testing
- The servers are down and we need to update the URLs in the application (this would require a components hotfix to fix)

It's not too much work to provide developers with the option to pass in their own URLs so we should pre-emptively do that.

**Comment by mcomella** [comment]
> It's not too much work to provide developers with the option to pass in their own URLs so we should pre-emptively do that.

@pocmo Before I invest in implementing this, would you agree that this seems like an important thing to do?

**Comment by pocmo** [comment]
> @pocmo Before I invest in implementing this, would you agree that this seems like an important thing to do?

I think you are in a way better position to decide the importance or priority here. Is this something you intend to use once available? Does Pocket have staging or development server that we may want to use in certain situations? Do you intend to write tests that will use a local (mock) server? It definitely sounds very reasonable to have the ability to change/configure such things - if we have actual use cases for it. :)

**Comment by mcomella** [comment]
I don't think we plan to address your use case examples nor do I have a specific use case in mind beyond, "We need an emergency update to update the URL endpoints!" That being said, the cost of doing an Android components hotfix (or even reflection) is low if it doesn't happen often so I think we shouldn't put in any extra effort here. I'm going to close as WONTFIX and we can reopen if it becomes a problem again. Thanks for the suggestions. :)
