### ISSUE TITLE
:service-glean:Bootstrap_CONDA_'Miniconda3' task does not execute in isolation

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#2344]
STR:
- Run `./gradlew clean :service-glean:Bootstrap_CONDA_\'Miniconda3\'`

Expected: task completes successfully
Actual: task fails with:

```
Local configuration: loaded local.properties
Local configuration: application-services substitution path missing. Specify it via 'substitutions.application-services.dir' setting.

> Task :service-glean:Bootstrap_CONDA_'Miniconda3' FAILED
Downloading Miniconda3-4.5.11-MacOSX-x86_64.sh

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':service-glean:Bootstrap_CONDA_'Miniconda3''.
> java.io.FileNotFoundException: /Users/mcomella/dev/moz/android-components/components/service/glean/build/Miniconda3-4.5.11-MacOSX-x86_64.sh (No such file or directory)
```

Speculation: it might be assuming other tasks create the build directory hierarchy before it runs, in which case it should not assume that or should declare other tasks as a dependency.

CC @Dexterp37 on glean's behalf

**Comment by mcomella** [comment]
Running '/gradlew :service-glean:compiledebugkotlin` seems to fix this issue: `service-glean:createBuildDir` runs before the Bootstrap.

**Comment by Dexterp37** [comment]
Thanks @mcomella , we'll look into that.
