### ISSUE TITLE
Enable kotlin warningsAsErrors on remaining modules that its disabled on

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#2346]
In #54, I enabled kotlin warnings as errors on modules that already had no errors. For each disabled module, we should:
- Fix the warnings
- Remove it from the list of modules with warnings as errors disabled

When we empty the list, don't forget to enable the check to selectively enable warnings as errors.

**Comment by mcomella** [comment]
To fix a module locally, you should remove it from the list of suppressed modules in KotlinCompiler.kt, compile kotlin for the production code, the unit test code, and the android test code, e.g. for all modules:
```sh
./gradlew compileDebugKotlin compileDebugUnitTest compileDebugAndroidTest
```

Then fix all the errors.

**Comment by mcomella** [comment]
@pocmo fwiw, as a downstream consumer, I'd prefer this to happen sooner than later: there are issues the compiler can catch _right now_, before they have a chance to crash our app in production – it'd be great to enforce this at least on the most popular modules like `browser-session` and `browser-engine-*`.

**Comment by pocmo** [comment]
Landed fixes for:
* browser-session
* concept-engine
* browser-engine-gecko-nightly

**Comment by Amejia481** [comment]
@pocmo Is there a way to pull [this list](https://github.com/mozilla-mobile/android-components/blob/c3cae262766d1f288bab81ac6f9db9ffd5d33dbd/buildSrc/src/main/java/KotlinCompiler.kt#L15) from [.buildconfig.yml](https://github.com/mozilla-mobile/android-components/blob/master/.buildconfig.yml)?

**Comment by pocmo** [comment]
@Amejia481 Yeah, would be an option. But I don't think it's worth changing the code to a configuration flag in .buildconfig.yml since the goal is for this list to no longer exist. :)

**Comment by mcomella** [comment]
> Landed fixes for:

🙌 Thanks for working on this so quickly! :)

**Comment by pocmo** [comment]
Additionally off the list now:
* `browser-engine-gecko-beta` (Thanks merge day!)
* `support-base`
* `support-ktx`
* `lib-crash`

**Comment by dector** [comment]
Taken:
```
browser-domains
support-utils
tooling-lint
ui-autocomplete
ui-progress
ui-tabcounter
```

**Comment by dector** [comment]
Fixes for all modules are on review. :)

**Comment by pocmo** [comment]
This is finally done. Thank you for all your hard work @dector! 💯
