### ISSUE TITLE
Add EngineView.getVersion()?

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#2349]
FFTV and focus (maybe fenix?) all display gecko (and possibly webview) version in the About page. We are currently exposing this through our `BuildConfig` in FFTV: https://github.com/mozilla-mobile/firefox-tv/blob/master/app/build.gradle#L253. Can this be added to `EngineView`?

**Comment by pocmo** [comment]
Picking this up. This will also be helpful for Fenix to keep features behind flags for certain engine versions; e.g. If feature X lands in GeckoView 70 then an app can create a feature flag to only enable this feature if GeckoView 70 is used.

**Comment by pocmo** [comment]
GeckoView version numbers:
* Release: 67.0.1
* Beta: 68.0
* Nightly: 69.0a1
