### ISSUE TITLE
BackgroundSyncManager: pass up SyncResult from the workers

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#2350]
This is a follow-up to #2076.

Currently the result of a sync is dropped on the floor. Workers pass it along, but it's ignored. This means we can't distinguish successful syncs from broken ones, and `onError` observer method will not be called in case of errors.

**Comment by grigoryk** [comment]
This is required to enable sync telemetry, which is a ship-requirement.

**Comment by grigoryk** [comment]
cc @linacambridge

**Comment by linacambridge** [comment]
This no longer blocks telemetry (#3092), now that we're collecting Glean metrics directly in the Storage-Sync component, so we don't have to pass it around to Fenix.

**Comment by grigoryk** [comment]
Closing for now; initially needed it for telemetry, but that got resolve differently. Will re-open if we need it.
