### ISSUE TITLE
Implement constants for shared HTTP headers

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#2361]
It'd be nice if apps could share a single HTTP header constant definition with values like, "Content-Type" and "Authorization". A list of common HTTP request headers can be found at: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Standard_request_fields

@pocmo What's a good place for this? I'd think:
- `support-base`
- `support-utils`
- A new HTTP abstraction module

I'm leaning towards base because it's a "building block". I think it should be separate from `concept-fetch` because, in theory, some consumers may not want to use our abstraction but might want pre-defined headers.

**Comment by mcomella** [comment]
FYI: I just made a PR with `support-base`: not sure why I bothered asking here :P.

**Comment by pocmo** [comment]
> I think it should be separate from concept-fetch because, in theory, some consumers may not want to use our abstraction but might want pre-defined headers.

I think adding this to `concept-fetch` is fine. A concept only has such constants, interfaces and data types. There's a high chance that if you need headers you need a client too. And even if not: The component is light-weight (only interfaces etc..) and proguard will strip everything away.

I'm concerned about landing too much in `base` and that becoming the dumping ground for things.
