### ISSUE TITLE
AwesomeBar: Two different ViewHolders have the same stable ID

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2364]
From the reference browser:

> Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change. ViewHolder 1:ViewHolder{959c237 position=6 id=1262243701, oldPos=-1, pLpos:-1 not recyclable(1)} View Holder 2:ViewHolder{39ea416 position=2 id=1262243701, oldPos=-1, pLpos:-1 not recyclable(1)} mozilla.components.browser.awesomebar.BrowserAwesomeBar{d37fdf7 VFED..... ......ID 0,0-1080,1101 #7f080020 app:id/awesomeBar}, adapter:mozilla.components.browser.awesomebar.SuggestionsAdapter@4429464, layout:androidx.recyclerview.widget.LinearLayoutManager@2e7d6cd, context:org.mozilla.reference.browser.BrowserActivity@ad8263b

* https://sentry.prod.mozaws.net/operations/reference-browser/issues/5329251/
* https://sentry.prod.mozaws.net/operations/reference-browser/issues/5327619/

**Comment by pocmo** [comment]
@grigoryk Collisions :(

**Comment by grigoryk** [comment]
Ah! Just filed a duplicate #2501 for this. Yup, collisions.
