### ISSUE TITLE
Upgrade to A-S 0.20.1

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#2369]
Lots of changes we'd like to get in soon. Due to package name changes, our consumers may possibly be affected as well: https://github.com/mozilla/application-services/releases/tag/v0.20.0

**Comment by grigoryk** [comment]
This will need to be 0.20.1, as 0.20.0 is busted.

**Comment by csadilek** [comment]
Current version is 0.27.0. Closing...
