### ISSUE TITLE
Glean test timeout

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2384]
Happened on this task:
https://tools.taskcluster.net/groups/F0bADsJAT9awd9esM7TDbw/tasks/UJaLe8wqQsSb1JpYskmyOg/runs/0/logs/public%2Flogs%2Flive.log

```
> Task :service-glean:generateReleaseUnitTestResValues
> Task :service-glean:generateReleaseUnitTestResources
> Task :service-glean:mergeReleaseUnitTestResources
> Task :service-glean:generateReleaseUnitTestConfig
> Task :service-glean:processReleaseUnitTestJavaRes
> Task :service-glean:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
> Task :service-glean:testReleaseUnitTest
[taskcluster:error] Task timeout after 7200 seconds. Force killing container.
```

**Comment by pocmo** [comment]
Happened here again: https://tools.taskcluster.net/groups/W649Uv3EQwmvlxGN2E7Lsg/tasks/GOdKAupSSH6p24KvTpBFIA/runs/0/logs/public%2Flogs%2Flive.log

**Comment by pocmo** [comment]
@Dexterp37 @mdboom @travis79 It looks like we have intermittent issues with deadlocking glean tests.

**Comment by pocmo** [comment]
Happened on this PR that introduced better logging:
https://tools.taskcluster.net/groups/RnMOiJ2fTmqPH4Fn4VShDg/tasks/dmaOv5v2T32q8G1pjo7-yA/runs/0/logs/public%2Flogs%2Flive.log

Last output:
```
SUITE: mozilla.components.service.glean.CounterMetricTypeTest
 TEST: The API saves to its storage engine
```

**Comment by travis79** [comment]
I believe this may be fixed by #2429

**Comment by mdboom** [comment]
Yeah -- if we don't see it again by end-of-week, I imagine we should close this.

**Comment by pocmo** [comment]
Old issue is old. Closing. :)
