### ISSUE TITLE
Consider adding `Request.Body` factory function for GET request query params style body

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#2394]
In #2336, I'm adding an endpoint to Pocket whose Request body looks like the formatting of parameters in a GET request:
```
url=https%3A//news.com/my-article.html&article_id=1234&v=2&locale=en-US"
```

[Sebastian suggested](https://github.com/mozilla-mobile/android-components/pull/2378#discussion_r266502042) we could turn this into a factory function on Request.Body. My concern with this is that I'm not sure "GET request parameter" formatting is common enough to warrant this to go into the main library: however, whoever implements this bug can do that research. :P

There could be two APIs I see:
- `fun fromUriEncodedQuery(uri: Uri): Response.Body`
- `fun fromQueryParams(params: Map<Pair<T, U>>)`, where we also encode the parameter values for them

fwiw, my current implementation leverages the `Uri` class:
```kotlin
        Uri.Builder()
            .appendQueryParameter("url", articleUrl)
            .appendQueryParameter("article_id", articleID.toString())
            .appendQueryParameter("v", "2")
            .appendQueryParameter("locale", "en-US")
            .build()
            .encodedQuery!!
```

**Comment by pocmo** [comment]
> "GET request parameter"

Isn't that `application/x-www-form-urlencoded`, which is a common thing ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST))?

**Comment by mcomella** [comment]
> > "GET request parameter"
> 
> Isn't that `application/x-www-form-urlencoded`, which is a common thing ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST))?

So it is – this sounds like it's worth doing then.
