### ISSUE TITLE
Review notes on component strings.xml files

### ISSUE THREAD

**Issue by Pike** [mozilla-mobile/android-components#2428]
@flodolo found a couple of nits when doing a review of https://github.com/mozilla-l10n/android-l10n/pull/3.

Copying them over to get traction on them.

We'd like to have better comments on:

What's %s?
https://github.com/mozilla-mobile/android-components/blob/f2fc6a00ef0a26497f97d3872eeff494c4703436/components/browser/engine-system/src/main/res/values/strings.xml#L7
https://github.com/mozilla-mobile/android-components/blob/f2fc6a00ef0a26497f97d3872eeff494c4703436/components/ui/tabcounter/src/main/res/values/strings.xml#L2

Proper apostrophe in 

https://github.com/mozilla-mobile/android-components/blob/f2fc6a00ef0a26497f97d3872eeff494c4703436/components/feature/sitepermissions/src/main/res/values/strings.xml#L37-L42

Adding both here, @Delphine filed #2426 for the second one.

@flodolo, did you have more?

**Comment by flodolo** [comment]
There are a few "Web" uppercase, e.g. "Web browsing", that should probably be lowercase. 

But I realize these come from Firefox, and I'm not sure if someone actually wants to fix.
