### ISSUE TITLE
FirefoxAccountsAuthFeature is coupled to "tabs"

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/android-components#2438]
@ryanfeeley is proposing a UI for FxA login in a view that takes over the **whole screen** (like Firefox iOS). With the current implementation we always do `tabsUseCases.addTab`.@grigoryk  what are your thoughts to let the app decide how to open the FxA login?

https://github.com/mozilla-mobile/android-components/blob/d3068f313c86d210bb599a1712f64ac62642ab7b/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt#L43

cc @csadilek

**Comment by Amejia481** [comment]
This is fixed, now you can provide a lambda for it. 
https://github.com/mozilla-mobile/android-components/blob/9d8c2ca12db14645aef96a391b2528cc2486b610/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt#L58
