### ISSUE TITLE
Unit tests creating GeckoView instance block indefinitely

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2439]
Follow-up from 2374.

With the latest GeckoView Beta and Nightly unit tests that create a `GeckoView` instance block indefinitely.

Tests that do that in `GeckoEngineTest`, `GeckoEngineViewTest` and `NestedGeckoViewTest` have been disabled (`@Ignore`).

Let's figure out what's causing this and re-enable the tests.

**Comment by csadilek** [comment]
@pocmo I found the cause of this: `GeckoView.init` now calls `getActivityFromContext`: https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoView.java?q=GeckoView.java&redirect_type=direct#220

And `getActivityFromContext` goes into an infinite loop: https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/gecko/util/ActivityUtils.java#71
