### ISSUE TITLE
Engine-Gecko: Create variants for "beta" and "nightly" 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#246]
# Current state

Currently we build against GeckoView **Nightlies**. At some point we want to build against **Release** versions - so that we can ship stable products based on the `engine` component.

# Problems

Even though we want to use **release** builds in shipping products, we still want to be able to use **beta** or **nightly** builds too:
* (A) We want to implement and test new APIs as they become available and not wait until release.
* (B) We want to ship preview/beta-builds of products that may use a beta/nightly version of GeckoView.
* (C) We want to switch to a release build as fast as possible so that apps can make use of the new version that usually includes security fixes.

## Release trains

GeckoView follows the release trains of mozilla-central:

![image](https://user-images.githubusercontent.com/89638/40648696-592bbbd4-632f-11e8-8b53-a6c03d3e9c2a.png)

Roughly every six weeks Nightly becomes Beta and Beta becomes Release. In theory it would be possible to let the components follow those trains and always build against mozilla-central and branch simultanously. But we do not want this:
* We want to go fast and release whenever we want to.
* We do not want the overhead of multiple branches and uplifting.

# Proposal

What if we duplicate the `engine-gecko` component so that we end up with:

* engine-gecko (tracking release)
* engine-gecko-beta (tracking beta)
* engine-gecko-nightly (tracking nightly)

This would allow us to:

* (A) Add new GeckoView APIs to `engine-gecko-nightly` as soon as they become available.
* (B) Use different GeckoView channels in product variants (e.g. Fenix Nightly vs. Fenix Release)
* (C) Do the integration work early and not wait until release day.

In this model every 6 week, when there is a new GeckoView release, `engine-gecko-nightly` would become `engine-gecko-beta` and `engine-gecko-beta` becomes `engine-gecko`.

Our `engine` abstraction would make it possible to hide the actual GeckoView version. Of course some Nightly features would not be implemented / throw an "not supported in this version" in the release version of the component.

Also: Could we automate updating the (pinned) Nightly versions in `engine-gecko-nightly` so that a "bot" opens PRs if no integration work is needed (and file an issue if it needs to be done manually).

**Comment by pocmo** [comment]
>    engine-gecko (tracking release)
>    engine-gecko-beta (tracking beta)
>    engine-gecko-nightly (tracking nightly)

That's only one option here. Maybe we can hide all this in the same package and use a flavor (or runtime-based implementation choosing).

**Comment by pocmo** [comment]
Having build flavors in libraries seems to be a bit painful. I managed to get sample-browser to pick the right library variant; but I'll have to test what is going to get published to jcenter.

**Comment by pocmo** [comment]
@csadilek ^--- What you think? Currently only option 2 seems to be maintainable to me - although I would have preferred option 1 before actually trying it. I haven't tested option 2 yet. That's what I'm going to do next.

**Comment by pocmo** [comment]
Option 2 basically rebuilds the release trains as modules.

**Comment by pocmo** [comment]
Okay, I have implemented option 2 now. That was quite easy and straight-forward. It took me quite a while to do option 1 only partially. option 2 is already done and just works. As code only needs to be added to the nightly component this isn't harder than before too. :)

**Comment by csadilek** [comment]
@pocmo yes, seems too tedious to go with option1. Having separate modules is definitely easier to maintain.
