### ISSUE TITLE
Map Media state to PlaybackStateCompat

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2461]
For #1845.

To update a `MediaSession` we will need to map the state of `Media` to a `PlaybackStateCompat` instance.

https://developer.android.com/reference/android/support/v4/media/session/PlaybackStateCompat.Builder

**Comment by gabrielluong** [comment]
Hey @pocmo, I am interested in taking a stab at this. Can you describe how to approach this issue? Thank you!

**Comment by pocmo** [comment]
@gabrielluong I haven't read enough of the `MediaSession` API yet unfortunately. This may not be a good starter bug.

**Comment by pocmo** [comment]
A simple version of this landed and it seems to be good enough for now. Let's file new issues once we need more functionality.
