### ISSUE TITLE
Glean tests: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2477]
When building the Docker image locally I get an OutOfMemory error. Every time at the point where the glean UI tests get executed.

I just saw his here on taskcluster happening too:
https://tools.taskcluster.net/groups/WqDA3nf0Qv2_-phVARgSyg/tasks/PG4cZumcQIqJryUIGH0sLg/runs/0/logs/public%2Flogs%2Flive.log

**Comment by pocmo** [comment]
Some snippet:

```
java.lang.OutOfMemoryError: Java heap space
  TEST: testGetValue() throws NullPointerException if nothing is stored
    [Robolectric] mozilla.components.service.glean.StringMetricTypeTest.testGetValue() throws NullPointerException if nothing is stored: sdk=28; resources=legacy
    [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
    I/AssetManager: no overlays.list file found
    I/MonitoringInstr: Instrumentation started!
    I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@4640e234', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@4640e234'
  FAILURE
java.lang.OutOfMemoryError: Java heap space
  TEST: The API saves to secondary pings
    [Robolectric] mozilla.components.service.glean.StringMetricTypeTest.The API saves to secondary pings: sdk=28; resources=legacy
    [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
    I/AssetManager: no overlays.list file found
    I/MonitoringInstr: Instrumentation started!
    I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@4640e234', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@4640e234'
  FAILURE
```

**Comment by pocmo** [comment]
Before that I see quite often such lines:

>  W/SQLiteConnectionPool: A SQLiteConnection object for database ':memory:' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

Maybe those are ending up filling the memory? 🤷‍♂️

**Comment by pocmo** [comment]
CC @mdboom @Dexterp37 @travis79

**Comment by mdboom** [comment]
Glean doesn't use SQLite directly, AFAIK.  Any idea where this is coming from?

I'll probably just start with a `git bisect` to investigate this, since I can reproduce locally and I know it was working yesterday...

**Comment by travis79** [comment]
I don't know of anything we are using that would have anything to do with SQLite...  the only storage mechanisms we use are either directly writing to a file or SharedPreferences.

**Comment by mdboom** [comment]
`git bisect` tells me that the bad commit is probably 637c0cfdb2c9d119a9a2a6e3f6003bc55a842ff0.  (The previous commit, 1c398446a8a45abfbd78733965c2a91186012c4d, doesn't build).  So the issue is probably the update of gradle?

**Comment by mdboom** [comment]
Turns out that the running out of memory is a bit non-deterministic.

Instead, bisecting and checking for the message:

> W/SQLiteConnectionPool: A SQLiteConnection object for database ':memory:' was leaked! Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

gives us 4d7b6f329077fa317d7bac20fc75f99799ed084d as the first bad commit -- but that *might* only be because the messages themselves were hidden before that change.  Good times.

**Comment by mdboom** [comment]
Ok, I'm pretty convinced that the `SQLiteConnection leak` is a red herring and has been there for a long time.

I bisected again, running a clean build and test 3 times at each position, treating and `OutOfMemory` errors as a failure, and all signs again point to the new version of Gradle.  The failures post Gradle upgrade not 100% reproducible, but prior to the Gradle upgrade is the culprit.

```
git bisect start
git bisect bad
git bisect good 3a949265b
git bisect run ./gradlew clean :service-glean:testDebugUnitTest && ./gradlew clean :service-glean:testDebugUnitTest && ./gradlew clean :service-glean:testDebugUnitTest
```
bad commit is 1c398446a -- that one doesn't build at all, so skip it and try the next commit 637c0cfdb, and that fails with `OutOfMemory`.

**Comment by pocmo** [comment]
@mdboom Thank you for bisecting. I'll try debugging with different version a bit. Hopefully we do not need to go back to an old Gradle version.

**Comment by pocmo** [comment]
Gradle 5.3 was released 2 days ago. I'll give that a try.

There are also newer Robolectric versions (although they may not work on Windows yet) and RC releases of a new Android Gradle plugin.

**Comment by pocmo** [comment]
Gradle 5.3 didn't help.

Trying Android Gradle Plugin 3.4.0-rc02 next.

And then finally Robolectric 4.2.1 or 4.3 Alpha 1.

**Comment by mdboom** [comment]
Thanks.  Let me know if there's anything else I can do to help or if signs point to glean again :)

**Comment by pocmo** [comment]
Haven't seen that happen anymore 🤷‍♂️
