### ISSUE TITLE
Automate GeckoView Beta update

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2487]
We have automated updating GeckoView Nightly. Now that we start to use Beta in Fenix it would be helpful if we automate updating Beta too.

**Comment by pocmo** [comment]
@Amejia481 Is it easy to add an additional task for updating the GeckoView Beta version? After that I can take that and run that from taskcluster :)

**Comment by Amejia481** [comment]
Yes, I think is not a lot of work, because most of the things are already customizable. I will take it from here and do the adjustments :)

**Comment by pocmo** [comment]
Re-opening for the taskcluster changes. That's something I haven't done yet. :)
