### ISSUE TITLE
Add search icon to BrowserToolbar editToolbar 

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#2493]
For Fenix, we would like the ability to set the search provider icon on the `editToolbar` itself instead of putting it in suggestions. 

See [here](https://mozilla.invisionapp.com/share/U8R4ASRNZ59#/screens).

**Comment by pocmo** [comment]
I wonder if it would be an option too to add the icon in front of the toolbar in Fenix. I think you already wrap the toolbar in the grayish background rectangle?

**Comment by sblatz** [comment]
Good call on this. Seems like we don't need an a-c change for this 😄
