### ISSUE TITLE
Expose color theme setting via engine

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2538]
GeckoView: https://bugzilla.mozilla.org/show_bug.cgi?id=1529972

To toggle CSS prefers-color-scheme media query we will need to tell the engine (in this case GeckoView) when switching to dark/light mode.

For that we will need to add an engine setting.

**Comment by sarentz** [comment]
I think this also needs to be able to change the setting for existing webviews. As in: you should be able to flip a setting in the browser and all the existing tabs will follow that choice.
