### ISSUE TITLE
Update string ID (and maybe string) in latest export

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/android-components#2541]
The string is question is: https://github.com/mozilla-l10n/android-l10n/commit/d29b39b77b509e48e5fa3603bb1fd29f39b6fb76#diff-de2648461f9789d9707e0712c8334383R35

As per our l10n review on quarantine, this string ID should probably be updated (see https://github.com/mozilla-l10n/android-l10n/pull/10/files/2570fba7770c72ffc368b95dabd67bac9cb9455f#diff-de2648461f9789d9707e0712c8334383R35).

Concerning updating the actual string, maybe @mheubusch can give a recommendation / advice here? We're wondering if the right string here is "pop-ups", instead of "a pop-up", because we'd expect the block to stop multiple popups.

Seems like @pocmo introduced this change, so pinging for an update (once Michelle replies we'll know if just the ID needs to change, or also the actual string) :) 
thanks!

(also CC @Pike and @flod so they are aware)

**Comment by mheubusch** [comment]
I think it is ok to change this to <string name="mozac_feature_prompts_popup_dialog_title">Prevent this site from opening pop-up windows?</string>

but note that this is not a string I provided and we do not use the negative (Prevent) pattern in Fenix. We use a positive (Allow) pattern, so I am not entirely sure what the context is.

**Comment by pocmo** [comment]
@Amejia481 This is about `mozac_feature_prompts_popup_dialog_title`. Can you take a screenshot of this prompt and explain the context this is showing up in?

**Comment by Amejia481** [comment]
This prompt is shown when a page is trying to show multiple popup windows, you can the behavior in [this website](http://www.popuptest.com/)
![image](https://user-images.githubusercontent.com/773158/55166342-51e3fd00-5145-11e9-80a5-f151d33e1da2.png)

**Comment by Pike** [comment]
Interesting, that sounds like we probably want _this_ to be in the copy, given we show the URL?

We might still want a positive wording, though?

What are the next steps here?

**Comment by mheubusch** [comment]
in Fenix, we plan to block pop-ups by default and not prompt a user to allow or deny. users can allow popups at the site level as exceptions, though i am not sure how a user would know anything was blocked in the first place unless they happened to open the site control panel.  @brampitoyo @AmyYLee what are your thoughts?

**Comment by mheubusch** [comment]
but @Pike our current plan is to not use this string in fenix so I don't think any action needed at this time.

**Comment by brampitoyo** [comment]
@mheubusch wrote:

> users can allow popups at the site level as exceptions, though i am not sure how a user would know anything was blocked in the first place unless they happened to open the site control panel. @brampitoyo @AmyYLee what are your thoughts?

Let me try to answer the question by looking at the solution holistically – in context of our Site Permission Settings.

There are permissions that we default to Allow, Ask and Block.

Permissions set to Allow don’t need to show any message when they’re triggered.

Permissions set to Ask can show something that demands action when they’re triggered: a permission prompt.

Permissions set to Block must not show something interruptive. They can only show snackbars that don’t last forever.

<img width="360" src="https://user-images.githubusercontent.com/51007/55460719-e0acba00-561c-11e9-942b-7d29b2b6af1c.png">

When the snackbar action is manually tapped, then a permission prompt will show up.

<img width="360" src="https://user-images.githubusercontent.com/51007/55460751-f4582080-561c-11e9-9237-bfb987fdf8be.png">

The same permission prompt can also be opened by going to the site information panel and tapping on the permission name.

<img width="360" src="https://user-images.githubusercontent.com/51007/55460780-076af080-561d-11e9-85f5-5d7fff699cff.png">

What do you think?

-----

### How this proposal can scale to the future

Let’s say, in the future, that Fenix wants to block malicious redirects or autoplaying video with sound.

Whenever a redirect is about to trigger, or whenever a site is about to autoplay a video with sound, we can show similar snackbar message to the pop-up one:

> Redirect blocked. [ALLOW]

> Autoplay video blocked. [ALLOW]

When “Allow” is tapped, we can also show permission prompts that allows user to Allow Once, or Allow Forever.

**Comment by Pike** [comment]
> but @Pike our current plan is to not use this string in fenix so I don't think any action needed at this time.

With the status quo, we actually ask localizers to take action on this string, and new localizations we add will have translations for a different string than the ones we have right now.

I'll quickly add a PR to move this string out of the way.
