### ISSUE TITLE
Allow hooks for telemetry

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#2545]
In Fenix we want to have metrics for how users share content. https://github.com/mozilla-mobile/fenix/issues/957. I would love to have a way to know when an candidate action is invoked here: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFeature.kt#L113

I was thinking about adding a contextMenuItemWasSelected delegate method that I could hook into. What do you think?

**Comment by pocmo** [comment]
For such things our components can emit `Fact`s. 

The mechanism is explained here:
https://github.com/mozilla-mobile/android-components/tree/master/components/support/base#facts

Unfortunately we haven't added that to all our components yet.

One example of that is `browser-toolbar` and you can see the `Fact`s it emits in the README here:
https://github.com/mozilla-mobile/android-components/tree/master/components/browser/toolbar#facts

Related code in the component is here:
* https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt#L58
* https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/facts/ToolbarFacts.kt

And finally this PR in the Reference Browser repo shows the app side where we register a `FactProcessor` and forward some of them to Glean:
https://github.com/mozilla-mobile/reference-browser/pull/677

@boek Following this generic approach we could emit `Fact`s from all the context menu items. Does this make sense to you?

**Comment by boek** [comment]
It does! I'll take a look :)

**Comment by boek** [comment]
done!
