### ISSUE TITLE
Android Components Sticker - June 2019

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2592]
Sticker refresh! (starting this early so that we have enough time to get them printed).

Are we:
- Sticking with emojis on a crate.
  - TODO: choose new emojis. (🍌 required)
- Getting a GeckoView icon.
- Using new sticker ideas.

Ref: https://github.com/mozilla-mobile/android-components/issues/1231

**Comment by pocmo** [comment]
@jonalmeida How are we doing? What's the plan? You are "Head of Stickers". :)

**Comment by jonalmeida** [comment]
Blocked on getting a GV icon! 

We can each choose a release emoji to be on the crate?

> You are "Head of Stickers".

🎉

**Comment by jonalmeida** [comment]
We have a GV sticker, working on this!

**Comment by jonalmeida** [comment]
Please review. :)

![crate-v3 copy](https://user-images.githubusercontent.com/1370580/59009063-3a3a8c00-87fa-11e9-9dfd-6b2029bb8068.png)

**Comment by pocmo** [comment]
✅

**Comment by Amejia481** [comment]
✅

**Comment by jonalmeida** [comment]
_Merging into stickers.._

**Comment by jonalmeida** [comment]
AC stickers received thanks to @ekager ! 👏 
![128022](https://user-images.githubusercontent.com/1370580/59361532-02eb4400-8d00-11e9-8888-bb224a9c3095.png)


@dector how do we get some to you? :)

**Comment by dector** [comment]
:heart_eyes: Look so cool!
But I'm afraid I'm quite far from Canada. :(

**Comment by jonalmeida** [comment]
> 😍 Looks so cool!
> But I'm afraid I'm quite far from Canada. :(

If you could private message one of us with postal code, we can get them to you. :)

**Comment by pocmo** [comment]
Yeah, we are all at Mozilla's bi-annual sticker conference next week (also called "All Hands") and the one closest to you can take a bunch of them home to send you. :)
