### ISSUE TITLE
Resources.pxToDp is actually dpToPx

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#2605]
`Resources.pxToDp` converts a value in DIP to its pixels values: the naming is incorrect (though the kdoc correctly explain what this method does).

It looks like I accidentally suggested the wrong name in #754 and it got implemented.

We should do this sooner, rather than later, so we can introduce a real `pxToDp` method later (for consistency) :).

**Comment by NotWoods** [comment]
I'll do this refactor soon after the codebase settles down
