### ISSUE TITLE
History: Ignore initial load of about:blank

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2606]
Fenix issue: https://github.com/mozilla-mobile/fenix/issues/1318

A `GeckoSession` will always start by loading `about:blank` and there are technical reasons why that is the case.

In `GeckoEngineSession.onLocationChange()` we ignore the initial load (added in #403):
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L282-L286

We don't do that for history though. And therefore every time you open a tab we track an `about:blank` visit.

**Comment by pocmo** [comment]
FYI @grigoryk

**Comment by grigoryk** [comment]
Our HistoryDelegate is probably a good place to do this filtering.

**Comment by grigoryk** [comment]
We also currently insert custom home page extension URLs, e.g. `moz-extension://<extension-id>/stuff.html`

**Comment by grigoryk** [comment]
Here's this logic in Fennec. We probably just want to port it over: https://dxr.mozilla.org/mozilla-central/source/mobile/android/components/build/nsAndroidHistory.cpp#326
