### ISSUE TITLE
Portrait mode tablet fails to read QR code when pairing

### ISSUE THREAD

**Issue by jdragojevic** [mozilla-mobile/android-components#2608]
Testing the pairing flow in the reference browser version 1.0.1914, samsung galaxy tab s4

When I hold the tablet in portrait mode, the QR code for pairing is not recognized.  When I shift it to landscape mode (which is more zoomed out) then the pairing is successful.

cc @vladikoff

**Comment by vladikoff** [comment]
Christian and I have spotted issues with portrait vs landscape changes while implementing the component. Thought it was fixed, but we shall investigate on various devices to confirm. So far it seems phones are okay with reading the QR codes.

**Comment by csadilek** [comment]
@jdragojevic @vladikoff this should be fixed in both Fenix and Reference Browser now (as part of https://github.com/mozilla-mobile/fenix/issues/2565). When you get a chance, can you verify and close, if that's the case? :)

**Comment by jdragojevic** [comment]
Yes - I've paired numerous times with table in portrait mode - and it's much improved and reliable.
