### ISSUE TITLE
BrowserToolbar uses unconventional package name

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#261]
To include it:
```xml
<mozilla.components.browser.toolbar.BrowserToolbar
```

It should be a reverse url like `org.mozilla.components...`

**Comment by csadilek** [comment]
@mcomella This was intentional. See this PR for more details: https://github.com/mozilla-mobile/android-components/pull/20

**Comment by mcomella** [comment]
I'm concerned about future proofing (e.g. how google.com didn't foresee google.org) but we can address that when it actually becomes a problem.

Another side effect could be searchability (will someone search for all Mozilla's packages with on some tool with "mozilla.org" and it won't find components?) but considering we don't expect high external usage, seems reasonable.

wfm.
