### ISSUE TITLE
Integrate / provide FxA component prototype

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#263]
Work is underway over at https://github.com/mozilla/application-services to prototype FxA integration on Android based on a new Rust library. We should try and provide a library/component for FxA based on the outcome.

**Comment by csadilek** [comment]
We should be able to fetch the Rust lib and its dependencies for all supported platforms as .zip files from Taskcluster .e.g: https://tools.taskcluster.net/groups/QtbZsMENQ72gk6BFCzKNpg/tasks/QtbZsMENQ72gk6BFCzKNpg/runs/0/artifacts

**Comment by pocmo** [comment]
Is this a temporary thing and will we be able to just pull everything from cargo?

**Comment by csadilek** [comment]
I think we're going to want to consume binaries here (maven/bintray-style), as otherwise, we'd have to build everything from source (cargo). The problem with that is that the FxA build is quite complicated esp. building the dependencies (openssl). Wdyt? I figured it's easiest if we are just consumers of the released binaries.

**Comment by csadilek** [comment]
The scope of this issue is to bring in / consume the FxA Rust library plus dependencies, and include very basic usage. We can then create follow-up issues for full integration.
