### ISSUE TITLE
Integrate concept-fetch powered A-S Megazord

### ISSUE THREAD

**Issue by sarentz** [mozilla-mobile/android-components#2677]

**Comment by bifleming** [comment]
@vesta0 @st3fan is this a release-blocker?

**Comment by sarentz** [comment]
The 'concept-fetch powered' part is release blocking.

**Comment by vladikoff** [comment]
@thomcc @csadilek this has been resolved in https://github.com/mozilla-mobile/fenix/pull/1904 right?

**Comment by thomcc** [comment]
Yep!

**Comment by jdragojevic** [comment]
Closing, based on above comment @vesta0 @st3fan
