### ISSUE TITLE
Ability to redirect to native account settings UI on fxa sign-in completion

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#2680]
This is part Fenix, part A-C work.

**Comment by bifleming** [comment]
@vesta0 is this a release blocker for MVP?

**Comment by vesta0** [comment]
@bifleming I am not 100% sure what this refers to but we have all the account functionality we need for MVP at the moment.

**Comment by grigoryk** [comment]
This is from conversations with rfeeley. Once user completes the sign-in, they should be redirected to the native accounts/sync UI in the settings, which will let them customize what’s being synced, etc.

Current behaviour is that they will stay on the “you’re now signed in” tab. That’s non-ideal, since there’s no straightforward way for them to get back to the place from which they started the sign-in process. Back button would not work, etc. It’s also just not a great experience. Fennec does this; if we can do better, we should.
