### ISSUE TITLE
Allow images to be injected into ErrorPages

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#2689]
In Fenix, we'll want the ability to add an image to the top of the error page. Ideally in createErrorPage I'd like to pass in a drawable and have it inject it into the HTML page.

**Comment by sblatz** [comment]
This could be a sizeable amount of work. I know when we tried doing this in Fenix it led to lots of issues due to the decoding of an image taking a long time (several seconds).

**Comment by sblatz** [comment]
See [designs here](https://mozilla.invisionapp.com/share/FXR7YVSHT3G#/screens/354559463) for more context.

**Comment by dector** [comment]
BTW, do we need to display error screen as web-page or special layout will be good as well?

**Comment by sblatz** [comment]
Closing this as fixed :)
