### ISSUE TITLE
docs: Link to API reference from README

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#2696]
I've heard folks say they didn't know API reference docs were available: if the API reference was linked from the readme, it might be more discoverable.

The API reference is available at https://mozac.org/api/

**Comment by pocmo** [comment]
In #2116 I am planning to merge the READMEs and the web page to only have a single source of documentation. This will hopefully make everything more discoverable.

Of course we can still link to the API references from the READMEs in the meantime.

**Comment by xXAligatorXx** [comment]
I have submitted a pull request for this: #2830
