### ISSUE TITLE
glean histogram sanity checking

### ISSUE THREAD

**Issue by bdekoz** [mozilla-mobile/android-components#2697]
Current gv_measurements.json has the following data for the probe CONTENT_PAINT_TIME:

"CONTENT_PAINT_TIME": {
    "sum": 125988,
    "counts": [
     4,
     0,
     0,
     2,
     0,
     0,
     0,
     0,
     1,
     0,
     0,
     1,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     3,
     21,
     435,
     672,
     807,
     549,
     101,
     7,
     5,
     5,
     1,
     3,
     1,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
    ]
   },

This compares the the following desktop data for the same probe:

 "CONTENT_PAIN_TIME": {
            "bucket_count": 50,
            "histogram_type": 0,
            "sum": 521,
            "range": [
              1,
              1000
            ],
            "values": {
              "0": 12,
              "1": 34,
              "2": 31,
              "3": 17,
              "4": 7,
              "5": 13,
              "6": 9,
              "7": 4,
              "8": 3,
              "9": 1,
              "11": 1,
              "14": 1,
              "20": 3,
              "23": 3,
              "26": 0
            }
          },

So, it would appear as if the gv_measurements histogram has no info on the bucket count, the range, and no way to tell (at a glance) how the histogram is scaled and where the sampled values (or counts) fall into the buckets. Is this intentional, and if so, what is the background thinking and rationale.

Without this info, how are histograms being scaled on android?

**Comment by pocmo** [comment]
CC @Dexterp37 @mdboom @travis79

**Comment by mdboom** [comment]
@bdekoz: How did you obtain the data in the first example?  It doesn't look like it comes from glean.  Glean does include the range, and the values as a map (which gives the bucket locations), just as on desktop.

As far as I know (and it's possible I'm out of date on this) GeckoView is not using glean telemetry.

**Comment by mdboom** [comment]
Upon further investigation, I think the tool generating this is actually the GeckoView-specific telemetry documented here: https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/docs/internals/geckoview.rst

Based on that, I'm Cc'ing @georgf and @chutten who can probably provide more details.

**Comment by georgf** [comment]
Note that these histograms are currently not sent through Glean to our data pipeline.
If there is important data in there that you need, let's talk about how to make that happen.
