### ISSUE TITLE
Remember scroll position in geckoview state

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2700]
https://github.com/mozilla-mobile/fenix/issues/1185

**Comment by pocmo** [comment]
GeckoView already listens to scroll positions and is supposed to restore it. But that doesn't seem to work in RB and Fenix.

https://hg.mozilla.org/mozilla-central/rev/51b9ea359763#l2.242

**Comment by pocmo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1543387

**Comment by cpeterso** [comment]
@pocmo - Is this bug still a happening? You said in Bugzilla that restoring the scroll position is "sometimes working" now.

https://bugzilla.mozilla.org/show_bug.cgi?id=1543387#c5

**Comment by pocmo** [comment]
Updated Bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1543387#c7

**Comment by pocmo** [comment]
A fix for that landed in GeckoView. Let's re-test that once we have that version in AC.

**Comment by jonalmeida** [comment]
Came across this while testing other things. Scroll position seems to be saved now, but I'm going to close this since it's an assigned issue.

**Comment by cpeterso** [comment]
> I'm going to close this since it's an assigned issue.

@jonalmeida, did you mean to write "not going to close"?

**Comment by jonalmeida** [comment]
> @jonalmeida, did you mean to write "not going to close"? This issue is still open.

Thanks for catching - that's correct!

**Comment by pocmo** [comment]
Test as well and it's working as expected for me now! :)
