### ISSUE TITLE
Fxa state machine must integrate with Auth errors

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#2724]

**Comment by vladikoff** [comment]
from mtg: "How much detail do we show in the errors?"

@ryanfeeley "Mark wrote about:sync-logs for detailed errors, in Fenix we should only show hard errors when you change your password or you have to reconnect to sync"

**Comment by vladikoff** [comment]
cc @mhammond @grigoryk let us know if you need to speak with @ryanfeeley about this
