### ISSUE TITLE
Expose bookmark syncing APIs

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#2726]
... once they're available in appservices.

**Comment by grigoryk** [comment]
A-S issues blocking this: https://github.com/mozilla/application-services/pull/918 and https://github.com/mozilla/application-services/pull/892.

**Comment by thomcc** [comment]
Went out in https://github.com/mozilla/application-services/releases/tag/v0.26.0, usable once https://bugzilla.mozilla.org/show_bug.cgi?id=1545289 is completed.

**Comment by grigoryk** [comment]
This was done.
