### ISSUE TITLE
Upstream tab counter changes from Fenix

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2743]
Fenix has a copy of `ui-tabcounter` to apply some customizations. Let's see if we can upstream those to AC in some generic way. :)

There is also `TabCounterToolbarButton` from `feature-tabs` that is copied over as well.

**Comment by jonalmeida** [comment]
Can I add `feature-tabs` to this ticket as well since it's related (i.e. `TabCounterToolbarButton`) is also copied over. :)

**Comment by pocmo** [comment]
sure 👍

**Comment by eliserichards** [comment]
The Fenix version of the TabCounter has already removed the SessionManager, so we are going to move the implementation to replace the AC version
