### ISSUE TITLE
Add UseCase for updating Tracking Protection Policy

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2746]
Updating the `TrackingProtectionPolicy` for the engine and all sessions is a bit cumbersome. We could add a usecase to make this easier.

Here is what we do in Reference Browser:
https://github.com/mozilla-mobile/reference-browser/pull/439

I wonder if this is a pattern that we will see more often (update engine setting + for all sessions) and whether we could implement this in a more generic way. But then again a simple `UseCase` would be enough here!

**Comment by dector** [comment]
Hi, @pocmo . Can you please add few more details about this issue? I want to work on it but I'm not sure that I have deep-enough understanding.

**Comment by csadilek** [comment]
@dector thank you for offering your help! @NotWoods just started working on this one. We have added "good first issue" labels to some other issues (and will add more soon). We definitely appreciate your help!
