### ISSUE TITLE
Persist and restore thumbnails

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2754]
Thumbnails are not persisted. This means the next time a session is restored there are not thumbnails. We could consider persisting them to make that a more pleasant experience.

There are two options:
* Have the session storage take care of persisting and restoring thumbnails
* Have an independent cache of thumbnails (that may be useful if we want to display them eventually in other places).

**Comment by pocmo** [comment]
Looks like thumbnails may no longer be needed in the latest tabs tray. Removing the "MaybeFenix?" label.

**Comment by jonalmeida** [comment]
This is going to be useful for the tabs tray component that needs to persist the thumbnails. ([Link to a Tabs Tray concept design](https://app.abstract.com/share/82263092-59d2-4d3e-8e27-22bc19f3b190?collectionId=d5d149bc-d87b-438e-9da4-0df1a3812144&collectionLayerId=017c3ded-0536-44ad-a4ae-5e22de9c9d37&present=true&preview=false&sha=8b2d00528bfa380af43843d9035ec380da7f954a))

 - Passing in a storage cache to the ThumbnailsFeature might work.
 - To avoid hitting the `onTrimMemory`, we could scale the image down to what the device's screen will draw on the screen and/or trimming the thumbnail down only to what is visible in the tray.
