### ISSUE TITLE
Custom Tabs: Title doesn't fade to the end like the title

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2760]
Open a CT and observe the ellipses of the title compared to the end of the URL fading out.

I can see the ellipses being an alternative to the fade-out, but doing both seems awkward.

<img width="618" alt="Screen Shot 2019-04-17 at 2 21 56 AM" src="https://user-images.githubusercontent.com/1370580/56265824-a03b4a80-60b8-11e9-99f0-e2eb3c451a23.png">

**Comment by lime124** [comment]
removing reference browser issues from UX feedback board. please ping stefan if you need support from a ux team member.

**Comment by jonalmeida** [comment]
@lime124 This also affects Fenix issue, but granted it probably is a post-MVP one.

**Comment by jonalmeida** [comment]
From Michelle: don't use the ellipses and fade the title as well (similar to the url).
