### ISSUE TITLE
Autocomplete suggestion gets triggered on search term

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#2769]
## STR
1. Type "Mo" then backspace to remove the autocomplete suggestion
2. Press "go" button
3. Tap the URL bar to go back to the search view

## Expected
1. URL bar displays "Mo"

## Actual
1. URL bar displays "Mozilla.org" (the autocompleted suggestion based on the search query).

**Comment by pocmo** [comment]
Oh, wow. I can reproduce this in the Reference Browser too. :)

**Comment by sblatz** [comment]
Yeah, I noticed this when trying to implement it in Fenix. This is likely a bug we want to prioritize as we consider [search terms](https://github.com/mozilla-mobile/fenix/issues/1205) to be a blocker for our MVP, and this is a pretty common bug, I'd say.

**Comment by sblatz** [comment]
@pocmo of note, the search terms don't seem to be getting *set* to the incorrect text, it's set to "Mo" when I debug. However, I think when the editMode changes the text it's autocompleting the search term.
