### ISSUE TITLE
Update to Gradle Plugin 3.4.0

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2784]
https://tools.taskcluster.net/groups/FIPPiRlpRS-_ZCRcvfQyjA

There are some new warnings (that break for components that treat them as errors) and some new lint checks. Overall some clean up is needed.

**Comment by dector** [comment]
This issue is blocked on (at least) two downstream users. (See [PR](https://github.com/mozilla-mobile/android-components/pull/3471) for details.)
