### ISSUE TITLE
Glean: Adding both a counter and a labeled_counter to metrics.yaml causes dupe imports

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#2793]
I was tasked with adding a new counter metric to Fenix. When I added it to metrics.yaml in the same group as a labeled_counter, the resulting generated code included duplicate imports for mozilla.components.service.glean.private.CounterMetricType. This caused the final app build to error out with this error message:

"Conflicting import, imported name 'CounterMetricType' is ambiguous"

**Comment by mdboom** [comment]
Thanks for the report.  Shouldn't be too hard to fix.  I'm on it.
