### ISSUE TITLE
RequestInterceptor fails after visiting an about: link

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2794]
STR:
1. Using the sample browser, enter 'sample:about'.
2. Observe.
3. Enter 'about:about'
4. Observe.
5. Enter 'sample:about' again.
6. Observe.

Expected:
- At 2, you should see the 'I am a sample browser' text in the content.
- At 4, you should see the list of about pages available in GV.
- At 6, you should see the 'I am a sample browser' text in the content _again_.

Actual:
- At 2, you see the 'I am a sample browser' text in the content.
- At 4, you see the list of about pages available in GV.
- At 6, you see a blank white screen.

This is unrelated to https://github.com/mozilla-mobile/android-components/issues/2790 as I tested this issue out before this issue arose.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2228)

**Comment by pocmo** [comment]
Is this a GV bug and needs a Bugzilla report?

**Comment by jonalmeida** [comment]
@pocmo we haven't investigated to see if it is.
