### ISSUE TITLE
ReaderView: L10N string review

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2799]
There were some strings added for ReaderView for the appearance controls that should be reviewed and be done async to the integration work.

Strings: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/readerview/src/main/res/values/strings.xml

This is the only screen that has strings for the android component, the rest would land in the Fenix repository:

![Screenshot_2019-04-18 Reader View - Appearance](https://user-images.githubusercontent.com/1370580/56395400-6ed19480-6208-11e9-8525-cc9f112772c8.png)

cc: @Pike & @Delphine

**Comment by Delphine** [comment]
FWIW these strings LGTM.
I think we're waiting for a confirmation from @mheubusch though?

**Comment by mheubusch** [comment]
Yes, these are good - sorry for the lag.  I approved this in the design bug.

**Comment by jonalmeida** [comment]
@Delphine :
> During my initial review, I found these strings rather explicit. But on second thoughts, it's probably good to have a short, simple comment for each -just so people know what/where these strings correspond to

**Comment by Pike** [comment]
Adding blocks-quarantine as we need the comments to start exposing this to l10n.

**Comment by bifleming** [comment]
@jonalmeida are you able to get the comments in?

**Comment by jonalmeida** [comment]
> @jonalmeida are you able to get the comments in?

We can look into this since we're doing some reader mode work today.
