### ISSUE TITLE
Re-evaluate url parsing regex

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2812]
We thought #2790 would be good enough to pass our url detection regex but this doesn't seem to be the case. We should re-evaluate (ASAP) how we can update our regex check and/or revert to our old version if we need more time for this.

The [gruber v2 or stephenhay regex](https://mathiasbynens.be/demo/url-regex) might be good enough for us to use for now.

**Comment by jonalmeida** [comment]
Offline conversation: take a look at Fennec's solution.

**Comment by jhugman** [comment]
I think we should the `String.isUrl()` method into `support-utils`, and implement this in terms of `WebURLFinder`.

The given regular expressions do not accept scheme-less strings.

We should deprecate the `support.ktx String.isUrl()` method, or remove it altogether.
