### ISSUE TITLE
Allow Fenix to pass in our own Snackbar style for context menu

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2825]
Original issue split into two: https://github.com/mozilla-mobile/android-components/issues/2811

Fenix is seeing some issues with the context menu snackbar and it would be great to pass in more customization of the style.

**Comment by ekager** [comment]
Also see https://github.com/mozilla-mobile/fenix/issues/1997 for the full screen feature snackbar

**Comment by jonalmeida** [comment]
There's some more work here that makes styling a snackbar a little harder than expected. I spoke with @vesta0 offline and she agreed this is not a P1 blocker right now.
