### ISSUE TITLE
Consder how to handle Push messaging

### ISSUE THREAD

**Issue by bbangert** [mozilla-mobile/android-components#283]
Push functionality on Android has several options depending on target platform and features desired. These come with varying levels of functionality and allow for features such as Send Tab to Device.

The WebPush standard implemented in Fennec utilizes the Google Play based [GCM](https://developers.google.com/cloud-messaging/) for its messaging, and generates WebPush compatible message endpoints using the [Mozilla Push Service Bridge API](https://autopush.readthedocs.io/en/latest/http.html#push-service-bridge-http-interface). Mozilla then relays messages through GCM/[FCM](https://firebase.google.com/docs/cloud-messaging/) for delivery to the Android device. WebPush message endpoints are utilized by the Send Tab to Device system in Firefox Accounts.

Google Play services enabled platforms have the ability to use GCM/FCM which is:
1. Low-power
2. Always-available
3. Best-effort message delivery

Amazon android devices (FireTV, tablets, etc.) use [ADM](https://developer.amazon.com/docs/adm/overview.html) for device messaging which is similar in features to FCM. We have not currently implemented ADM bridge messaging for the [Mozilla Push System](http://mozilla-push-service.readthedocs.io/en/latest/), but it would be a fairly quick feature to add.

Desktop Firefox uses a websocket connection to the Mozilla Push Service for direct delivery which is being expanded to include a new broadcast system for faster updates.

Holding a websocket connection even on mobile devices (when the app is foregrounded) is beneficial for cases where broadcast messaging, more reliable delivery, and lower latency is desired. For always-connect devices like TV's, the websocket connection should be a better option than the platforms native messaging.

Currently the websocket client handler for [Push in desktop Firefox is a JSM](https://github.com/mozilla/gecko-dev/blob/master/dom/push/PushService.jsm), however its rather hefty with technical debt and should be updated/replaced. The Push team has looked into making a Rust client lib for this, which would be a good candidate for use in android-components as well as replacing the desktop version.

At the very least, android-components should include a minimal Rust library that can register for WebPush compatible endpoints with Mozilla Push Service, and utilize the platforms native messaging.

**Comment by pocmo** [comment]
Some thoughts:

The way we currently build _pluggable_ components we'd define a _concept-push_ component that contains generic interfaces etc. that define how we want to interact with push services. We'd then implement multiple components based on that, e.g.: _app-push-firebase_, _app-push-amazon_, _app-push-mozilla_. All other components/features that require push would only know about _concept-push_ and the actual app would decide which implementation it wants.

> Holding a websocket connection even on mobile devices (when the app is foregrounded) is beneficial for cases where broadcast messaging, more reliable delivery, and lower latency is desired.

Is there really a benefit over FCM? According to the docs FCM delivers messages immediately if the app is in the foreground (_normal_ priority). For _high priority_ messages it will even try to wake a sleeping device.
https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message

Unfortunately we won't be able to reliably keep any connections while the app is not in the foreground (without a foreground service with an ongoing notification).. so the use cases for keeping our own connection seems to be very narrow?

**Comment by bbangert** [comment]
> Is there really a benefit over FCM? According to the docs FCM delivers messages immediately if the app is in the foreground (normal priority). For high priority messages it will even try to wake a sleeping device.

The main feature our connection has is broadcast, which will be used by OneCRL and others for faster updates to reduce polling. We would still need to have the device register an FCM endpoint to wake the app even if it did open its own connection later though, so FCM or ADM should be default choices for the vast majority of use-cases.

The websocket connection could be used primarily for broadcast awareness, perhaps that should be a separate component. We've discussed having device-to-device messaging which might also be more convenient over our own websocket connection while the app is foregrounded.

> Unfortunately we won't be able to reliably keep any connections while the app is not in the foreground (without a foreground service with an ongoing notification).. so the use cases for keeping our own connection seems to be very narrow?

Agreed, though we might be able to keep it open as a background process default for Android TV devices.

**Comment by jonalmeida** [comment]
We've created a sprint board for breaking down and tracking this work, so I'm closing this issue in place of it since we have a rough idea how to start and we can add more investigation tickets there along the way.

https://github.com/orgs/mozilla-mobile/projects/19
