### ISSUE TITLE
mozilla.components.ui.icons "Pin" icons should be mirrored + settings icon

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/android-components#285]
According to Amin, this icon should be mirrored so it points the same direction as the Turbo button.

However, if it should be mirrored ONLY in firefox-TV, then please close this issue, and we will mirror it locally.

Also, tagging along with this issue, there's not a "gear/settings" icon in android-components - is that something we can add?

**Comment by pocmo** [comment]
Let's mirror it in the component. You are the only user of that icon for now.

> Also, tagging along with this issue, there's not a "gear/settings" icon in android-components - is that something we can add?

Yes, absolutely, let's add it! Those XML files are tiny and proguard can strip them if they are not needed.
