### ISSUE TITLE
Custom Tabs: Pressing the back button doesn't close the session

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2874]
See the following issues for STR:
- https://github.com/mozilla-mobile/reference-browser/issues/660
- https://github.com/mozilla-mobile/fenix/issues/2097

We should be closing the session in the SessionManager before we invoke the close callback here: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt#L109

**Comment by pocmo** [comment]
Mh, some time ago I added this to RB:
https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/BrowserActivity.kt#L72

**Comment by jonalmeida** [comment]
> Mh, some time ago I added this to RB:
> https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/BrowserActivity.kt#L72

Ah ha! This would go away when we fix this in the CT toolbar.
