### ISSUE TITLE
Create "collections" / "tab groups" component (storage)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2883]
* Fenix Meta: https://github.com/mozilla-mobile/fenix/issues/1573
* UX designs: https://mozilla.invisionapp.com/share/U2RMIIZYBKE

Fenix will support "collections" of sessions. Similar to `feature-session-bundling` (Deprecating in #2882) we can provide the storage layer for that.

We will need to support:
* Creating collections
* Removing collections
* Updating collections
  * Adding sessions to existing collections
  * Removing sessions from collections
  * Renaming collections
* Restoring (partial) collections

Overall we can follow the same patterns we use in `feature-session-bundling` - a similar auto-save/restore functionality is not needed.

**Comment by pocmo** [comment]
Looking at the mocks it seems like we need can design this with a simple 1:n database schema, like:


collections:

| field      | type                  |
|------------|-----------------------|
| id         | long (auto_increment) |
| name       | string                |
| created_at | long (timestamp)                  |
| updated_at | long (timestamp)                      |

sessions:

| field         | type                        |
|---------------|-----------------------------|
| id            | long (auto_increment)       |
| title         | string                      |
| url           | string                      |
| file          | string (file name of state) |
| collection_id | long (foreign key)          |
| created_at | long (timestamp)                  |

**Comment by bifleming** [comment]
@pocmo @vesta0 What is the effort for this story?  Any chance we could get someone on it soon to unblock the remaining Fenix collections work?

**Comment by vesta0** [comment]
@betty I have prioritized this as P1 and it's on the Fenix board. We can move it to the new A-C sprint on Monday but I believe Sebastian is already working on it.
