### ISSUE TITLE
Expose JavaScript errors in web extensions happening in production

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2886]
If an error happens in the JavaScript code of a web extension then this will be logged. This is good enough for development... however it means that this code can fail silently in production and we would never know.

It would be nice if we could surface those errors in Sentry - like errors happening in Kotlin code.

Adding the [needs GeckoView API] label here since that may require some generic error callback.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2320)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796325

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
