### ISSUE TITLE
lib-crash: Allow reporting exceptions without crashing

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#2887]
In some situations you need to catch a certain type of exception (famous example: `JSONException`). In those situations often you can continue without crashing the app. In the case of an `JSONException` the cause is often that the JSON was different than what you expected. In those situations it would be nice to not only silently continue running but also report this exception (like a crash) via `lib-crash`. With that this error is visible to us and we can fix our code.

**Comment by pocmo** [comment]
This would be very handy for the Fennec migration code: We want to be super defensive here and not crash. However we desperately want to know if anything goes wrong and if we need to fix our migration code.

@rocketsroger Maybe a good follow-up for the work you have been doing? :) Maybe something like a `CrashReporter.submitReportFor(throwable: Throwable)`?

**Comment by rocketsroger** [comment]
> Maybe something like a `CrashReporter.submitReportFor(throwable: Throwable)`?
Agreed.  Issue created: https://github.com/mozilla-mobile/android-components/issues/4467

**Comment by pocmo** [comment]
Wait. This is already an AC issue :D

**Comment by rocketsroger** [comment]
> Wait. This is already an AC issue :D

I see what you mean.  My mistake.  You wanted a Fenix issue created.  I'll close and create a Fenix one.  😅

**Comment by rocketsroger** [comment]
Follow up after this issue is fixed: https://github.com/mozilla-mobile/android-components/issues/4589
