### ISSUE TITLE
Clear all coroutines when site permissions feature is stopped

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#2889]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2324)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796372

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
