### ISSUE TITLE
ReaderView page action is visible in Custom Tabs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#2897]
We should find a way to make this optional so that we don't add to all Custom Tab clients if they don't want that feature enabled in a CT session.

cc: @csadilek

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2330)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795351

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
