### ISSUE TITLE
a-c 51 build error: "OS independent path 'META-INF/atomicfu.kotlin_module`"

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#2900]
When running FFTV with a-c 51 upgrade, we are running into this problem:

```
Execution failed for task ':app:transformResourcesWithMergeJavaResForSystemDebug'.
More than one file was found with OS independent path 'META-INF/atomicfu.kotlin_module'
```

For now, I added `exclude 'META-INF/atomicfu.kotlin_module` in our gradle packaging option but I wonder if that should be a permanent solution

**Comment by jonalmeida** [comment]
@psymoon this doesn't look like we can prevent this from the looks of it. All dependant projects had to add it.

Reference: https://github.com/mozilla-mobile/reference-browser/pull/735

**Comment by psymoon** [comment]
@jonalmeida did you guys update `kotlinx.coroutines` recently? 

Related: https://github.com/Kotlin/kotlinx.coroutines/issues/1116

**Comment by jonalmeida** [comment]
Yes: https://github.com/mozilla-mobile/android-components/pull/2739

**Comment by mcomella** [comment]
I think this is the upstream issue: https://github.com/Kotlin/kotlinx.coroutines/issues/1064
