### ISSUE TITLE
Remove moment.js from reader view web extension

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#2923]
This is currently being used to generate a human-readable and localized string for the reading time e.g. 3 - 5 minutes.

We could use the minified version of this script, but we'd still be better off not needing it. We should likely pass the localized constants down from the feature using messaging, but the String is dependent on the language of the article currently.

**Comment by Pike** [comment]
I guess that @pocmo poked me about this one. This one is tough, let's buckle up.

Quick investigation on the status quo: `50 - an hour` is a possible outcome right now.

On how to fix this, I've seen in the commit log that there's communication between the extension code and native, I suggest to get the reading time string from the Android side through that channel. That way you solve a ton of problems around packaging, language negotiation, fallbacks, etc.

On to the problem of formatting ranges of times. There is code in icu that does that, http://icu-project.org/apiref/icu4j/com/ibm/icu/number/NumberRangeFormatter.html. I don't know if that's available to you, though.

As indicated above, you probably need to decide if you want multiple or a single units for start and end.

Note, if you don't have `NRF`, you can use https://developer.android.com/reference/kotlin/android/icu/text/MeasureFormat, but you'll need a joiner. You could make that a localized string, to make sure we get " - " vs "-" right. I'd expose it as "%1$s - %2$s", to make the whitespace easier to see.

Note, using the second number to determine the unit form is often right, but sometimes wrong. See the data on https://www.unicode.org/repos/cldr/tags/release-35-1/common/supplemental/pluralRanges.xml. I don't have a good idea on how to hack that up, though.

**Comment by csadilek** [comment]
Thanks @Pike for sharing your insights.

> Quick investigation on the status quo: 50 - an hour is a possible outcome right now.
This one I have a fix for (should land today).

I agree with the plan to try and to solve this on the Android-side and passing down the String.

**Comment by mlissner** [comment]
> 50 - an hour

The units for reader mode will always be minutes and hours, right? If we decide not to care about seconds and days as units, it seems like this could be a lot simpler.

Could there just be a rule that says, "We always use the unit from the lower bound?"

**Comment by csadilek** [comment]
I am going to assign to me to prototype a simple solution just to replace what we have now. I would really like to get rid of moment.js.

**Comment by csadilek** [comment]
Switching to [Intl.RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat) allows us to at least replace the existing functionality provided by moment.js to format the reading time in minutes.

I will file a follow-up to think about l10n for our web extension features more broadly. We likely want to rely on our Android l10n system and exchange messages with web extensions to share localized values.
