### ISSUE TITLE
Pinch to Zoom Triggers Toolbar Behavior and Doesn't Zoom

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#2930]
Similar to #2695 
See Fenix issue https://github.com/mozilla-mobile/fenix/issues/2278
"Pinch to zoom trigger the address bar, even if the page doesn't scroll."

**Comment by Mugurell** [comment]
I think this issue stems from the fact that we don't have a clear way of knowing if the panning gesture was used for scrolling or for zooming. We treat both the same.

This explains why [panning even with two fingers](https://drive.google.com/file/d/1cNNq3renCvr1JUs5ZkEj-QR6C3uTs0GO) will animate the navbar.
But even [one finger zoom](https://drive.google.com/file/d/1BMdSf5jk-s26NG5HEpoFOWCrjb_flyD3) will have the same effect.

We need to have a proper way to differentiate between this 2 gestures.
