### ISSUE TITLE
Take a look at the Androidx dependency tracker plugin

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#2951]
At Google I/O 2019. [The Android team showed a plugin](https://youtu.be/PZBg5DIzNww?t=109) that they are using in Androidx to run on CI only the tests on the module that has changed and its dependencies. This could decrease the time invested in CI. 

It may worthwhile taking a look at it. [Androidx dependency tracker plugin](https://goo.gle/androidx-dependency-tracker)

**Comment by pocmo** [comment]
That's nice!

To be more effective we'd need this one step earlier in the decision task so that we do not even schedule tasks for modules that can't be affected.

**Comment by Amejia481** [comment]
So far our build speed has improved significantly, it looks like the resource for the plugin  https://goo.gle/androidx-dependency-tracker is not available anymore. I'll close this for now, but feel free to re open if needed :)
