### ISSUE TITLE
Implement UI for feature-custom-schemes

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#2975]
Connected to #2936 
Depends on #2974

UI needs some product/design decisions. Should we warn the user that the app or play store is going to be launched? If there is a choice of app, should we make our own dialog or should we rely on the system one.

**Comment by topotropic** [comment]
@jhugman browsers which have implemented this usually just open the app – if there are no major security/privacy concerns, I'd suggest we do that as well.

Do you have an example for the "Choice of app" case?

**Comment by nikoloskii** [comment]
> Connected to #2936
> Depends on #2974
> 
> UI needs some product/design decisions. Should we warn the user that the app or play store is going to be launched? If there is a choice of app, should we make our own dialog or should we rely on the system one.



> @jhugman browsers which have implemented this usually just open the app – if there are no major security/privacy concerns, I'd suggest we do that as well.
> 
> Do you have an example for the "Choice of app" case?

There is no security/privacy concerns in case like this, and I think there is no need for "Choice of app", because It should be opened with system's default app, it will be the set by you anyway, right?

**Comment by pocmo** [comment]
For comparison: Fennec shows an icon in the toolbar (like reader mode) for switching to a third-party app if the current URL can be handled by another app. Other browsers switch to the third-party app immediately. Firefox Focus asks the user before leaving the app.

There is a case to be made to not switch automatically during private browsing - since that technically leaks your "private" visit of a page to a third-party app. I haven't checked how other browsers handle this case.

**Comment by jhugman** [comment]
@topotropic @pocmo @nikoloskid 

There is a system chooser, which I'm very happy to default to.

There are two cases which give me concern: 

 * the case where the chooser's "Use every time" option is taken. This is much less of a concern however.
 * the case @pocmo outlines: visiting a link in private browsing. The user may have no warning that a third party app will open, and the visit may be privacy invasive. (fwiw Chrome does warn you when leaving "This site is about to share information with an app outside of incognito mode").

**Comment by jhugman** [comment]
Spoken to @topotropic re opening from private browsing: 

> I’d feel more comfortable to warn users but it also depends on how much work it is, so it’s probably @vesta’s call what to do here

The plumbing here is difficult, not the implementing of the design. Two ways to proceed here.

1. Try and use the existing `RequestInterceptor` mechanism. This does not play well with putting UI on the screen. 
2. Add an extra field either to `Observer.onUrlChanged()` or `EngineSession.onLoadRequest(triggeredByUserInteraction: Boolean)` to differentiate between a loaded from the URL bar, clicked on by the user and set from JS without the user clicking. [Start here][1].

[1]: https://github.com/mozilla-mobile/android-components/blob/8ecfb1c0ae512a93c234621618c4f0ac89f3261a/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L326

**Comment by sarentz** [comment]
This should be moved post-MVP.

**Comment by vesta0** [comment]
@jhugman thanks for looking into this. It's important that we follow minimum android best practices + ensure alignment with our mission to protect user rights and privacy so I agree with @topotropic's suggestion:

-In regular mode, we can just switch automatically to the 3rd party app.
-In private mode, we should add a warning indicating that the user is about to exit private mode, and that the site is about to share information with an app outside of private mode. @mheubusch will you please provide strings? 

@jhugman let me know how much work this will cause.

**Comment by jhugman** [comment]
The Alert Dialog is done, the strings are needed, but can be landed separately. The largest chunk of the remaining work is ensuring that clicking on a link, but not via a URL typed into the URL bar causes the opening of a native app. I'd like @pocmo to see the approach I've taken so far. 

API to be used from a `ContextMenu` is still available. I don't have designs for this though.

**Comment by mheubusch** [comment]
recommended string: This link will open in <name of destination app/store> and your activity may no longer be private.  
Button 1: Cancel 
Button 2: Open

**Comment by jhugman** [comment]
@mheubusch We can't be certain of the app that the user is able to open the link in if there is a choice. Resolving the title of the first app that matches and then offering the chooser would then be the option.

We have three possible UI pieces: a menu option for opening the app, a dialog for breaking out of private mode and a title for the app chooser.

The strings for these latter two are in:

https://github.com/mozilla-mobile/android-components/pull/3058/files#diff-0111136e0a5d9e236b09d4d9d896ecf3

**Comment by mheubusch** [comment]
It looks like the strings are for the menu option and the dialog. Do you mean you still need the app chooser?

**Comment by mheubusch** [comment]
Or is that "Open in . . . " 

Then, for the contextual menu option it would have to be generic, yes? Like "Open in app . . . "

**Comment by jhugman** [comment]
App chooser is currently `mozac_feature_applinks_open_in`: "Open in…"

> for the contextual menu option it would have to be generic, yes? Like "Open in app . . . "
Yes, exactly so.

**Comment by mheubusch** [comment]
For the dialog, can we update it to say: Open link in app? Your activity may no longer be private.

**Comment by jhugman** [comment]
Fixed by #3058.
