### ISSUE TITLE
Add API for showing if the current page can be opened in a native app.

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#2976]
Connected #2936 .
Depends on #2974.

 * Add API for session observers to observe if the session's URL can be opened by a native app (this is more generic intent filtering, not just `custom://` protocols.
   - Ensure that we're filtering out generic browsers from this list.
   - Add API/UI for choosing the app to open from a filtered list of apps.

**Comment by pocmo** [comment]
There's `Browsers` in `support-utils` which has code to lookup default apps and may be helpful here.

**Comment by raygervais** [comment]
I'd be interested in working on this, will not have the chance to touch the code though for a week since I am travelling. If this is much more pressing, give to anyone else more interested and I'll find something for when I get back. 

Otherwise, any pointers?

**Comment by sarentz** [comment]
@vesta0 This can be moved post-MVP because won't have the feature work to integrate this in Fenix?
