### ISSUE TITLE
Web Extension ports should be connected/disconnected on pageshow/pagehide

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#2984]
We're currently connecting on load and disconnecting on unload which wouldn't work for cached pages and back/forward navigation.

We haven't seen a page yet where this broke for reader mode, but should, of course, still fix this.

**Comment by grigoryk** [comment]
What is this blocked on, @csadilek ?

**Comment by csadilek** [comment]
I've spent some time testing this last night, and what we have currently works as expected. We've also not had any bugs reported about this. The concern here was specifically about navigating to/from cached pages, but I tested this with reader mode and everything worked as expected. So, I am going to close this.
