### ISSUE TITLE
(Advice needed) Uncheck "Remember decision" on permision request dialog. 

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/android-components#2988]
There is issue [#fenix/2403](https://github.com/mozilla-mobile/fenix/issues/2403) in Fenix project to uncheck "Remember decision" checkbox by default.

![Request permission dialog](https://user-images.githubusercontent.com/265872/57565463-0b7df100-73c7-11e9-8a0e-a775c074abf1.jpg)

However, current implementation has hard-coded value that is not configurable.
[Layout](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/sitepermissions/src/main/res/layout/mozac_site_permissions_prompt.xml#L54) | [Fragment](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsDialogFragment.kt#L154)

I see two ways of fixing this:

**a)** _(Breaking change. Simple solution.)_ Just change value in layout to "more-privacy-by-default" (unchecked).
**b)** _(Non-breaking change. More code.)_ Leave checked value by default. Add ability to configure default checked state in [SitePermissionsFeature](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt#L63) from outside.

Please advise. I'm assuming that option **b** is a way to go for now.

**Comment by pocmo** [comment]
CC: @Amejia481

**Comment by jan-ivar** [comment]
What does "breaking" means in this case?

> Leave checked value by default. 

On the surface this does not sound like it would solve https://github.com/mozilla-mobile/fenix/issues/2403, or am I mistaken?

**Comment by mheubusch** [comment]
IANAEngineering, and may not be understanding  this issue, but I would  think we should always strive to fix the issue directly and not rely on a workaround in the case of user control and privacy.  Like the bug in 2403 mentions, the default setting for camera, microphone, location permissions is "Always Ask" so we **should not have** the Remember this decision checked by default, even if we have different code in components to reverse that decision, in the   case that  a-c changes and someone is not aware  of the dependency  and Fenix reverts to the check becoming the  default.

**Comment by Amejia481** [comment]
@dector thanks for taking this. 

I think the best approuch as you mentioned is to have a configuration for this value, this way we give consumers the option to customize it from outside. **But I think the `checkBox` should be uncheck by default** [more-privacy-by-default](https://github.com/mozilla-mobile/fenix/issues/2403).

**Comment by dector** [comment]
@jan-ivar 

> What does "breaking" means in this case?

It means that option **(a)** changes implementation details of the component and all its clients (dependent apps) will have different behavior in new version (in this case - default state of the checkbox changed).

> On the surface this does not sound like it would solve mozilla-mobile/fenix#2403, or am I mistaken?

mozilla-mobile/fenix#2403 is exactly about default checkbox state if I get it right.

@mheubusch 

Current semantics of this checkbox is "Remember my choice" (not "Always Ask"). So if and only if option **(a)** will be applied - we'll have breaking change but it'll be change towards more-privacy-by-default approach. Seems like product owner's decision for me. :)

@Amejia481 

Totally agree.

**Comment by dector** [comment]
Closing as this change is merged.
