### ISSUE TITLE
Consider adding View.showKeyboard(), View.hideKeyboard()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3]
Based on:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/ViewUtils.java#L101

**Comment by shikhart98** [comment]
Can you explain a bit whats needed to be done in this issue?

**Comment by pocmo** [comment]
> Can you explain a bit whats needed to be done in this issue?

Sure. :)

We want to import the functionality of `ViewUtils.showKeyboard()` and `ViewUtils.hideKeyboard()` (in the Focus for Android repository! See link above.) into this repository. However instead of a *Utils class we want to write [Kotlin extension functions](https://kotlinlang.org/docs/reference/extensions.html).

As a result of this we will be able to call those methods on a View object, e.g.:

```Kotlin
myView.showKeyboard()
myView.hideKeyboard()
```

To achieve that we will need to add a View.kt file to the right package (mozilla.components.support.ktx.android.view) in the ktx module and then write the extension functions:

```Kotlin
fun View.showKeyboard() {
    // ...
}

fun View.hideKeyboard() {
    // ...
}
```
