### ISSUE TITLE
MapTest.kt: 'Assert' is deprecated.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#301]
From the build log:

```
w: /build/android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/
MapTest.kt: (12, 24): 'Assert' is deprecated. Deprecated in Java
```

**Comment by jeandersonbc** [comment]
Is this just a matter of replacing `Assert` for an appropriate class? I'm going to take a look on it :-)

**Comment by pocmo** [comment]
@jeandersonbc Yeah, tests should import from org.junit instead of junit.framework. :)
