### ISSUE TITLE
Measure, plot and monitor component sizes

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#302]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2440)

**Comment by pocmo** [comment]
This is a great article describing something similar:
https://medium.com/@emmaguy/tracking-android-app-metrics-431cbea2113d

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794658

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
