### ISSUE TITLE
Improve Suggestions of HistoryStorageSuggestionProvider

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3027]
Awesome Bar Suggestions still contain many redirects/useless URLs and we should introduce some filtering/excluding here

See: 
https://github.com/mozilla-mobile/fenix/issues/2542

## Expected behavior

I should see history entries for https://www.mozilla.org/en-US/firefox and
https://www.mozilla.org/en-US/firefox/new

## Actual behavior

I get four history entries:
https://www.mozilla.org/firefox
https://www.mozilla.org/en-US/firefox
https://www.mozilla.org/firefox/new
https://www.mozilla.org/en-US/firefox/new

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2448)

**Comment by bifleming** [comment]
@ekager Janet is requesting a little more info on this bug...specifically with regard to 'useless URLs'.

**Comment by ekager** [comment]
Please direct Janet to the linked Fenix issue above for more details

**Comment by sblatz** [comment]
Fenix issue: https://github.com/mozilla-mobile/fenix/issues/2542

**Comment by thomcc** [comment]
I'm a bit surprised these are showing up, and will have to do some digging. Over time does this issue remain? I'd expect hte redirects to have a very low frecency score once you have a decent amount of history...

**Comment by vesta0** [comment]
Vesta will discuss this with A-S and UX

**Comment by jdragojevic** [comment]
[a-s PR 1715](https://github.com/mozilla/application-services/pull/1715)  Exclude hidden URLs from syncing and views and
[a-c PR 4268](https://github.com/mozilla-mobile/android-components/pull/4268) Pass redirect source and target flags to history tracking delegates should resolve this.

cc @linacambridge @bifleming @vesta0

**Comment by linacambridge** [comment]
To close the loop, #4268 no longer syncs or shows redirect sources in the history list view (#1331, even if they aren't consecutive), but they'll still be shown in the awesomebar (https://github.com/mozilla-mobile/android-components/pull/4268#issuecomment-531947764).

**Comment by csadilek** [comment]
Tested this now and this has since been fixed. Closing.
