### ISSUE TITLE
Toolbar: fix menu animation for bottom toolbar

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3032]
When opening the menu, the animation shows the items entering from the top rather than the bottom. 

Somewhat related to #1744

**Comment by pocmo** [comment]
Related Fenix issue: https://github.com/mozilla-mobile/fenix/issues/343

**Comment by NotWoods** [comment]
This currently works for menu buttons on top bars but not on bottom bars. 😨 Seems that `PopupWindow.showAsDropDown` doesn't get called by `showPopupWithUpOrientation`.
