### ISSUE TITLE
Toolbar: Menu should automatically close if I exit the app

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3033]
When exiting the browser, pop-ups like the menu should close instead of remaining open when I return to the app.

[`Lifecycle.Event.ON_STOP`](https://developer.android.com/reference/androidx/lifecycle/Lifecycle.Event.html#ON_STOP) is probably a good time to close the menu.

**Comment by mauryat** [comment]
@pocmo I'd like to work on this!

**Comment by mauryat** [comment]
@NotWoods any suggestions on how this can be done?

The best I could think of was implementing a ToolbarLifecycleObserver with which both the host activity and the BrowserMenu register. But, this is ugly in the sense that the host activity would need to explicitly register with the observer. Can we rely on users of the module to always register?

**Comment by NotWoods** [comment]
I think we have toolbar feature wrappers, which have `stop()` methods corresponding to the lifecycle. Maybe you can call a `dismiss` method from there?

**Comment by mauryat** [comment]
We don't have access to the menu from the toolbar. The BrowserToolbar contains DisplayToolbar which contains MenuButton which in turn contains BrowserMenu. And all these in the chain are private. So, from ToolbarFeature.onStop(), we can't really call browserMenu.dismiss(). Not sure if that is what you intended in your suggestion!

**Comment by mauryat** [comment]
@NotWoods ^^

**Comment by NotWoods** [comment]
It's ok to introduce new public methods for this if needed. You could expose a function in BrowserToolbar that calls browserMenu.dismiss()
