### ISSUE TITLE
Apply remaining UI updates from CustomTabConfig

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#306]
In #282 we only addressed the toolbarColor. All remaining configurations still need to be applied.

**Comment by pocmo** [comment]
@jonalmeida I think we can close this one since you have separate issues for the custom tab related UI changes, right?

I also noticed that we have a comment about this in `ToolbarPresenter.initializeView`. Since you created a separate feature for that we may be able to remove the comment?

**Comment by jonalmeida** [comment]
Yes, I think so since https://github.com/mozilla-mobile/reference-browser/issues/209 lists all main Custom Tab configurations to apply.
