### ISSUE TITLE
Touch targets are off when using setVerticalClipping with a visibile toolbar

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3091]
STR:
1. Visit a site that has content that sticks to the bottom of the screen (e.g. Reddit web/app chooser).
2. Ensure the bottom browser toolbar is visible.
3. Click a button/option in that content area.
4. Observe.
5. Hide the bottom browser toolbar.
3. Click a button/option in that content area again.
4. Observe.

## Expected
- At 4, the content is clicked at the right place.
- At 7, the content is clicked at the right place.

## Actual
- At 4, the content is not clicked at the right place (it is offset by the height of toolbar).
- At 7, the content is clicked at the right place.

**Comment by jonalmeida** [comment]
TODO: Check if a bugzilla already exists for this or file one.

**Comment by pocmo** [comment]
* Fenix: https://github.com/mozilla-mobile/fenix/issues/2574
* GeckoView: https://bugzilla.mozilla.org/show_bug.cgi?id=1552608
