### ISSUE TITLE
Telemetry endpoint is not configurable

### ISSUE THREAD

**Issue by sammacbeth** [mozilla-mobile/android-components#3095]
The public constructor for creating a telemetry configuration for `Glean` does not expose `serverEndpoint` option. We run our own telemetry server and would like to be able to configure this component to use that endpoint. Would it be possible to expose this option?

https://github.com/mozilla-mobile/android-components/blob/a488abd56718ed14ed1bf5d16c5c4d4b530380bf/components/service/glean/src/main/java/mozilla/components/service/glean/config/Configuration.kt#L48-L64

**Comment by pocmo** [comment]
CC: @Dexterp37 @mdboom @travis79

**Comment by georgf** [comment]
@sammacbeth Sure, we're happy to figure out a solution.
What's your timeline on this?

**Comment by sammacbeth** [comment]
@georgf This is not time-critical. We are still testing the android-component ecosystem and can simply not use Glean in our prototypes for the time-being.

This issue is mainly to point out a possible oversight in the public API if this component is intended to be usable by third parties, as currently Mozilla's servers are hard-coded.

**Comment by georgf** [comment]
@sammacbeth Got it, thanks!

The current goal for Glean is to first support the launch of the Fenix MVP.
After that, from July 1 on we're up to integrating into other products, so we'd line this up for then.
But let us know if you end up having specific timing requirements.

We are tracking a related issue [over here](https://bugzilla.mozilla.org/show_bug.cgi?id=1554946), where we're considering to make the endpoint configurable from the build environment.
Maybe you can comment there if that would make sense for your use-case?

**Comment by Dexterp37** [comment]
@sammacbeth hi! I wanted to give you a quick update on this. The endpoint is now configurable through the [`Configuration`](https://github.com/mozilla-mobile/android-components/blob/c3a40397d27e892152a3db7049a1d065a228a63c/components/service/glean/src/main/java/mozilla/components/service/glean/config/Configuration.kt#L49).

Enabling endpoint changes at build time is still on our roadmap.

**Comment by travis79** [comment]
Closing this since we now allow the telemetry endpoint to be supplied by the consuming application through the `Configuration` constructor for both [Android](https://github.com/mozilla/glean/blob/4ee44a2333a0174ed44079c27788d26b88c2bdc6/glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt#L94) and [iOS](https://github.com/mozilla/glean/blob/4ee44a2333a0174ed44079c27788d26b88c2bdc6/glean-core/ios/Glean/Config/Configuration.swift#L59).
