### ISSUE TITLE
Crash reporter triggers Android Q warning about background activity starts

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/android-components#3097]
When GeckoView or Fennec crashes on Android Q, a toast notification appears warning of a background activity start. To avoid the warning and ensure the crash reporter runs to completion, the crash reporter should use a foreground service instead of an Activity.

https://developer.android.com/preview/privacy/background-activity-starts

This bug was originally reported by @kbrosnan in Bugzilla for Fennec's crash reporter:
https://bugzilla.mozilla.org/show_bug.cgi?id=1550291

**Comment by pocmo** [comment]
We can turn our `CrashHandlerService` into a foreground services. But since GeckoView is starting the service we would need it to use [startForegroundService](https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent)) on API 26+.

As I understand the docs even this won't allow us to start an activity from a service if the app is not in the foreground though. It seems like the only option is to show a (at best [heads-up](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up)) notification on crash?

**Comment by cpeterso** [comment]
> We can turn our `CrashHandlerService` into a foreground services. But since GeckoView is starting the service we would need it to use [startForegroundService](https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent)) on API 26+.
> 
> As I understand the docs even this won't allow us to start an activity from a service if the app is not in the foreground though. It seems like the only option is to show a (at best [heads-up](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up)) notification on crash?

If GeckoView will need to change how it launches the CrashHandlerService, please file a new GV bug or let me know and I can file the bug.

@snorp - Is starting the service with startForegroundService on API Level 26+ also relevant for Fennec's crash reporter?

Fennec bug https://bugzilla.mozilla.org/show_bug.cgi?id=1550291

**Comment by snorp** [comment]
> We can turn our `CrashHandlerService` into a foreground services. But since GeckoView is starting the service we would need it to use [startForegroundService](https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent)) on API 26+.
> 
> As I understand the docs even this won't allow us to start an activity from a service if the app is not in the foreground though. It seems like the only option is to show a (at best [heads-up](https://developer.android.com/guide/topics/ui/notifiers/notifications#Heads-up)) notification on crash?

GeckoView already starts the crash handling service with `startForegroundService`, so changes neded there. I agree, notification seems like the best option.

**Comment by pocmo** [comment]
Adding this to triage: We want to see Android Q issues and Q is now API stable. The current version is Beta 4. According to the roadmap there may be Beta 5 and Beta 6 release candidates with a final release in Q3. And Q3 already starts next month.

**Comment by pocmo** [comment]
Landed a first version. For fatal crashes on Android Q it will show a notification now. Tapping the notification will trigger the prompt.

This should show up in one of the next Reference Browser builds.

I think we can improve this a bit more later on. For example we could add a "Report" action right to the notification. I'll file an issue for that.
