### ISSUE TITLE
BrowserToolbar: Support "highlighting" menu button

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3101]
We will need to support a "highlighted" state for the menu button in BrowserToolbar. See Fenix mock below.

In #3100 @sblatz is adding a "highlightable" menu item. Ideally whenever a menu item has a "highlight" attached then the menu button would switch to the highlighted state after calling `invalidate()` - which @NotWoods recently changed to affect menu items too.

Needed to support thew full UI flow of mozilla-mobile/fenix#2327.

![highlight](https://user-images.githubusercontent.com/89638/58288346-53b2f100-7d81-11e9-8c47-94c0d2588b21.png)

**Comment by pocmo** [comment]
Per discussion in https://github.com/mozilla-mobile/fenix/issues/2327#issuecomment-495393891 and https://github.com/mozilla-mobile/fenix/issues/2793 this will drop of the Fenix MVP list. But it's something we want to add soon-ish after that. In the best case this only needs a change in AC and doesn't affect Fenix code.

**Comment by pocmo** [comment]
@NotWoods I just noticed that we do not mention anything in the changelog. Can you add an entry for this? :)

**Comment by NotWoods** [comment]
#3446
