### ISSUE TITLE
Allow passing in initial desired state to BrowserToolbar so Fenix doesn't flash display mode

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3120]
See:
https://github.com/mozilla-mobile/fenix/issues/1910

With the way Fenix is set up with SearchFragment and BrowserFragment separately, we want to be able to init the toolbar component with the desired state so we don't see a flash of display toolbar in SearchFragment. 

Looks like it's currently always set to display when initialized:
https://github.com/mozilla-mobile/android-components/blame/master/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt#L398

**Comment by pocmo** [comment]
Is Fenix calling `editMode()` somehow delayed? There should be no flash when it's set to edit mode  immediately. 🤔

**Comment by ekager** [comment]
correct, closing
