### ISSUE TITLE
Some tests in `BrowserAwesomeBarTest` are flaky

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/android-components#3124]
Some tests in `BrowserAwesomeBarTest` are [flaky](https://docs.gitlab.com/ee/development/testing_guide/flaky_tests.html). Some PR checks are failing sometimes because of it.

<details>
<summary>Smile! :smiley_cat: </summary>

<img src="http://s3.media.squarespace.com/production/2129687/19317774/.a/6a00d8341d3df553ef01348876b247970c-800wi" title="Geek&Poke's List Of Best Practices - Today: Continuous Integration" />
</details>

**Comment by pocmo** [comment]
@dector Does this fix #3119 or #1300?

**Comment by dector** [comment]
@pocmo I suppose both.

[this](https://github.com/mozilla-mobile/android-components/pull/3125/files#diff-a22877a65b636f406024394e5038ebb9R76) fixes #3119.

[this](https://github.com/mozilla-mobile/android-components/pull/3125/files#diff-a22877a65b636f406024394e5038ebb9R274) for #1300.

**Comment by dector** [comment]
However, the best way to test coroutines in components is to use [runBlockingTest {}](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/run-blocking-test.html) in combination with [TestCoroutineDispatcher](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-test/kotlinx.coroutines.test/-test-coroutine-dispatcher/index.html). But in this case it requires some changes in implementation.
