### ISSUE TITLE
Adding a domain component

### ISSUE THREAD

**Issue by levimatheri** [mozilla-mobile/android-components#313]
I just added a BlacklistedDomains.kt object to work with blocked websites feature that I'm implementing, referenced [here ](https://github.com/mozilla-mobile/focus-android/issues/2556). How do I include it in focus the same way as CustomDomains has been?

**Comment by pocmo** [comment]
Yes, I think for now it makes sense to implement this in Focus directly.

It seems like we have the need for "domain lists" (+ persistance) for implementing various features. This is indeed something we may be able to add to the components. Either in browser-domains if it's simple - or as part of our storage where we want to have a way to save domains/URLs with some flags.
