### ISSUE TITLE
Problem! ?

### ISSUE THREAD

**Issue by edtw** [mozilla-mobile/android-components#3143]
Excuse me, have you removed this feature?

https://wiki.mozilla.org/Electrolysis
"dom.ipc.processCount"
https://fossbytes.com/how-to-make-firefox-faster-by-enabling-multi-process-e10s-manually/
Please open this parameter, but always show only 1 Why is this happening?

"browser.tabs.remote.force-enable:
Also, is this parameter mobile version not supported?

I'm firefox android 68a1 user

**Comment by pocmo** [comment]
Is this a question about "Firefox for Android"?

The bug tracker for it can be found here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android
