### ISSUE TITLE
[qr] The camera feed is stretched in the QR component

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/android-components#3149]
From one of the Fenix testers:

> The camera feed is stretched on my phone when trying to sign in with qr code.

Ref https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/fenix-nightly/n9KcYqPXtd8/1hCw7hBWAQAJ

We should probably just make the view finder square or something.

**Comment by ryanfeeley** [comment]
The Fenix UX team has provided this design. What kind of assets would you need to make this happen? Note the darkened area.
![android](https://user-images.githubusercontent.com/68213/58515686-9c98ea00-8173-11e9-9152-eeaac1e2a464.png)

**Comment by pocmo** [comment]
I added this to our triage list (CC: @st3fan @vesta0 in case you think that is important and needs to be added to the board/spring before the next triage).

**Comment by ryanfeeley** [comment]
Attached is a ZIP file containing the desired reticle in SVG, as well as a simplified Sketch file that I'm hoping @sblatz can work with to produce the correct Android assets for the varying languages and screen sizes.
[reticle.zip](https://github.com/mozilla-mobile/android-components/files/3237518/reticle.zip)

**Comment by jonalmeida** [comment]
Why is this a P1 issue, but the [Fenix issue](https://github.com/mozilla-mobile/fenix/issues/2432) is P2?

**Comment by vladikoff** [comment]
There are 2 issues in 1 here, I moved the "UX update" into https://github.com/mozilla-mobile/android-components/issues/3267

**Comment by bifleming** [comment]
@pocmo is this actually In Progress? If not, it's a P2 and we can move it to the backlog for later.

**Comment by pocmo** [comment]
Not in progress. Was just labeling it. :)

**Comment by ryanfeeley** [comment]
@vesta0 @lime124 I still see the old QR code crosshair screen (aka reticle). Does this issue cover updating it or do I need to create a new issue?

**Comment by vladikoff** [comment]
>  Does this issue cover updating it 

it does not (IIRC)

**Comment by ryanfeeley** [comment]
@vesta0 @lime124 I filed it: https://github.com/mozilla-mobile/android-components/issues/4261

**Comment by RotBolt** [comment]
Could I take this one up? Seems an interesting issue to work on overlays
cc @pocmo

**Comment by jonalmeida** [comment]
I think this issue may have been solved by another issue. I do not see this bug any more.

**Comment by RotBolt** [comment]
ok if this is the case, Could you verify and close this issue? @jonalmeida

**Comment by jonalmeida** [comment]
Closing as: works for me.
