### ISSUE TITLE
Visiting Reddit always shows app popup or launches singular matching app

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3217]
Sorry @jhugman I wasn't sure if the work on this was done on your end (it looks like #2974, #2975, and #2976 were marked as done, but not closed).

In Fenix currently seeing that visiting Reddit will immediately launch the Reddit app for me without prompt. Our reporter in https://github.com/mozilla-mobile/fenix/issues/3058 is experiencing the prompt showing up on every page. Neither situation allows us to really browse reddit in Fenix.

**Comment by jhugman** [comment]
Looking at the video in https://github.com/mozilla-mobile/fenix/issues/3058#issuecomment-498036130 : 

I think this was fixed by #3210.

**Comment by jhugman** [comment]
We should address triggering when the user goes back, forward, reload, toggleDesktopMode.
