### ISSUE TITLE
Make search provider search engine description optional and controllable

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3231]
In Fenix, we want to be able to remove the second line from the search engine provider and not show the engine. 
See: https://github.com/mozilla-mobile/fenix/issues/1741

**Comment by pocmo** [comment]
`BrowserAwesomeBar` let's you add a `SuggestionTransformer`. Whenever a provider returns a list of  suggestions the awesome bar will call `transform()` which allows you to re-write the suggestions. 

Something like this may allow you to change the description of search suggestions:

```kotlin
class SearchSuggestionTransformer : SuggestionTransformer {
    override fun transform(
        provider: AwesomeBar.SuggestionProvider,
        suggestions: List<AwesomeBar.Suggestion>
    ): List<AwesomeBar.Suggestion> {
        return if (provider is SearchSuggestionProvider) {
            suggestions.map { it.copy(description = null) }
        } else {
            suggestions
        }
    }
}
```

Would this be an option here?

**Comment by ekager** [comment]
Thanks! I tried this and it makes those rows very slim compared to the other rows. Is this also something I can control or no?

**Comment by pocmo** [comment]
I think some time ago @sblatz added code to hide the "description view" if the description is null or empty.

Setting a description like `"  "` might keep the view but won't center the title.

Maybe we could add a "minHeight" - but I wonder whether that breaks whatever @sblatz needed that for ("shortcuts" maybe?).

**Comment by sblatz** [comment]
Shortcuts actually also have this issue if you select them, it just wasn't noticeable because we have a large amount of padding between items. @ekager were we also wanting to address the amount of padding between them?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/59046990-db940300-8837-11e9-869b-1ccbafa60e4e.png">
