### ISSUE TITLE
Glean intermittent failure: TEST: test sending of background pings

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3237]
We are seeing an intermittent glean test failure every now and then for pull requests and master merges.

For example here:

https://tools.taskcluster.net/groups/ci5k1yZmRVykNugxtTbLMQ/tasks/X48WYLTDQJuaXBCzJnoA5g/runs/0/logs/public%2Flogs%2Flive.log

```
TEST: test sending of background pings
  [..log..]
  FAILURE
```

**Comment by pocmo** [comment]
CC @Dexterp37 @mdboom @travis79

**Comment by Dexterp37** [comment]
Thank you. We filed [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1556692) on Bugzilla to track this.

**Comment by pocmo** [comment]
Another one. But it looks like a different test failing:

`TEST: schedulePingCollection must correctly append a work request to the WorkManager`

https://tools.taskcluster.net/groups/OH2QzV6YSjSowTgXbiGXUw/tasks/NPWlHIdLSmu5QkasR-s-iA/runs/0/logs/public%2Flogs%2Flive.log

**Comment by pocmo** [comment]
Ah, the other one is #3258

**Comment by pocmo** [comment]
Here's another failure of that test:
https://tools.taskcluster.net/groups/LZJcTvWPR6-sIP7nr18hSA/tasks/ZJ9vXDTyRxil51ARW2tw9w/runs/0/logs/public%2Flogs%2Flive.log

**Comment by pocmo** [comment]
This still breaks runs:
https://tools.taskcluster.net/groups/D2__mh3zRx-1GvgCGIC9Og/tasks/DzKflsI3R_m3M9DfJQcq8Q/runs/0/logs/public%2Flogs%2Flive.log

**Comment by Dexterp37** [comment]
> 
> 
> This still breaks runs:
> https://tools.taskcluster.net/groups/D2__mh3zRx-1GvgCGIC9Og/tasks/DzKflsI3R_m3M9DfJQcq8Q/runs/0/logs/public%2Flogs%2Flive.log

Thanks, we'll look into this. I filed [bug 1564924](https://bugzilla.mozilla.org/show_bug.cgi?id=1564924) for tracking it.

**Comment by Dexterp37** [comment]
This is no longer relevant, since glean test was moved to the glean repo :) (and the source of the problem was fixed!)
