### ISSUE TITLE
glean performance ping tracker

### ISSUE THREAD

**Issue by bdekoz** [mozilla-mobile/android-components#3245]
For assessing mobile performance in the wild, parts of gecko telemetry need to be exfiltrated to glean and sent as a tentatively-named  'performance ping.'

During 2019, the performance team is concentrating on page load and memory-related performance issues, so probes detailing these characteristics are necessary on Fenix. A subset of existing gecko telemetry probes will be used, broken down into sub categories for page load, graphics, and cache/memory as follows:

page load
FX_PAGE_LOAD_MS_2 or in the mobile case GV_PAGE_LOAD_MS
GV_PAGE_LOAD_PROGRESS_MS
TIME_TO_DOM_COMPLETE_MS
TIME_TO_DOM_CONTENT_LOADED_END_MS
TIME_TO_DOM_INTERACTIVE_MS
TIME_TO_NON_BLANK_PAINT_MS
TIME_TO_LOAD_EVENT_END_MS

graphics
(see https://metrics.mozilla.com/webrender/dashboard_intel.html)
CONTENT_FRAME_TIME_VSYNC
FX_TAB_SWITCH_COMPOSITE_E10S_MS
CONTENT_FULL_PAINT_TIME
CONTENT_PAINT_TIME
CONTENT_FRAME_TIME
COMPOSITE_TIME

cache/memory 
MEMORY_TOTAL
CACHE_DISK_SEARCH_2
NETWORK_CACHE_HIT_TIME_V2

In addition, information from these probes must be attached to relevant data about the client's machine and environment. Some of this data is already represented in the core_ping, and the rest will be exfiltrated from the environment. A full list of needed metadata is:

os_name
os_version
os_locale
cpu_count
memoryMB
device_manufacturer
device_model
software_name
software_version
software_arch
software_build_id

not immediately necessary but has proven to be useful in the past
gfx_display_h
gfx_display_v
gfx_model

**Comment by bdekoz** [comment]
Related to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1497812

**Comment by bdekoz** [comment]
Fallout from removing this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1547331

**Comment by stuartphilp** [comment]
Could we make 
```
gfx_display_h
gfx_display_v
gfx_model
```

part of the main list? device resolution and gpu family/speed have been important for a lot of perf work, and for picking reference devices

**Comment by bdekoz** [comment]
sure, thanks for the feedback

**Comment by bdekoz** [comment]
After other feedback, looks like the minimal metadata for performance environment looks like

# os_name
# os_version
# os_locale
# system_cpu_count
# system_cpu_speed
# system_memory_size
# system_gfx_adapter
# system_gfx_screen_height
# system_gfx_screen_width
# system_disk_cache_size
# system_network_cache_size
# device_manufacturer
# device_model
# application_name
# application_version
# application_arch
# application_build_id

# as histograms in MS
# system_disk_cache_search
# system_network_cache_search

# as histograms of MB, MHz
# system_memory_used
# system_cpu_used

**Comment by bdekoz** [comment]
After more internal team review and consultation with datasci, looking like this is the minimal environmental metadata:

os_name
os_version
os_locale
system_cpu_count
system_cpu_speed
system_memory_size
system_gfx_adapter
system_gfx_screen_height
system_gfx_screen_width
system_disk_cache_size
system_network_cache_size
device_manufacturer
device_model
application_name
application_version
application_arch
application_build_id

(as histograms in MS)
system_disk_cache_search
system_network_cache_search

(as histograms of MB, MHz)
system_memory_used
system_cpu_used

**Comment by bdekoz** [comment]
Will spin off a separate issue for the data review, using much of this text.

**Comment by Dexterp37** [comment]
Please consider that some of the data from the previous comments is already available, out of the box, in the [`client_info` section that comes with all Glean pings](https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/docs/pings/pings.md#the-client_info-section). For instance:

- os_name
- os_version
- device_manufacturer
- device_model
- application_name
- application_version
- application_arch
- application_build_id

**Comment by bdekoz** [comment]
Thanks Dexter! It looks like 

os_locale 

is present in 

metrics/string/glean.baseline.locale 

as well. So none of the os_*, device_*, application_* bits are needed if metrics is to be the baseline ping for performance.

**Comment by bdekoz** [comment]
Here's a WIP for the environment section of the performance-related needs

[perf-metrics-environment-wip.20190612.txt](https://github.com/mozilla-mobile/android-components/files/3283222/perf-metrics-environment-wip.20190612.txt)

**Comment by Dexterp37** [comment]
> 
> 
> Thanks Dexter! It looks like
> 
> os_locale
> 
> is present in
> 
> metrics/string/glean.baseline.locale
> 
> as well. So none of the os__, device__, application_* bits are needed if metrics is to be the baseline ping for performance.

Please note that if you need the locale in your ping, you'll need to add it to your ping as well. The `baseline` ping should not be overloaded with other metrics, if possible, given its frequency of sending. The `metrics` ping or some custom pings can be used for that (all the common fields will be present there as well).

**Comment by travis79** [comment]
Closing this since project EXTRACT added capabilities for Gecko to stream telemetry to Glean.
