### ISSUE TITLE
Memory leak in ObserverRegistry

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/android-components#3254]
`ObserverRegistry` stores observers in a `WeakHashMap` and does not remove values explicitly, relying on the weak references for cleanup.  

Buried deep in the `WeakHashMap` javadoc is a warning that the “value objects in a `WeakHashMap` are held by ordinary strong references. Thus care should be taken to ensure that value objects do not strongly refer to their own keys, either directly or indirectly, since that will prevent the keys from being discarded.”

Values of `ObserverRegistry` maps (`LifecycleBoundObserver` and `ViewBoundObserver`) both hold strong references to their observers, preventing deallocation.  This is leaking memory on FFTV, which can be shown by comparing a heap dump from master (which depends on A-C 54) with one that depends on [this draft PR](https://github.com/mozilla-mobile/android-components/pull/3255).  It seems likely that this affects most if not all projects that depend upon A-C.

**Comment by Baron-Severin** [comment]
I'm still mulling over how to write a unit test for this that won't be flaky and based on VM behavior.  Any suggestions would be welcome.

**Comment by pocmo** [comment]
> I'm still mulling over how to write a unit test for this that won't be flaky and based on VM behavior.

See comment in PR. If we remove explicitly and not use another weak reference then we may be able to test.
