### ISSUE TITLE
When opening a link in a new tab, pressing back should close the tab

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3256]
See: https://github.com/mozilla-mobile/fenix/issues/2483

Since the concept of the "parent" tab is not exposed to Fenix, this will require AC work.

**Comment by pocmo** [comment]
Since `SessionManager` already manages parents and their selection state, I think the only thing needed here is for Fenix to know whether a `Session` has a parent?

**Comment by ekager** [comment]
I think that would work yes! I just thought I remembered you saying in a meeting this was not something you would want to expose, but maybe I misheard :)

**Comment by pocmo** [comment]
Initially we didn't want to since we primarily needed that for `add()` (to add the new session next to its parent) and `remove()` (to select the parent). I guess for now I'll just add `hasParent: Boolean` and then let's see if we need more further on. :)
