### ISSUE TITLE
Crash reporter: Allow including email address

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3261]
Fennec allows users to enter an email address to contact them.

![image](https://user-images.githubusercontent.com/89638/58954667-1f382f80-879a-11e9-90ee-4141086dee67.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2650)

**Comment by cpeterso** [comment]
WONTFIX. Firefox desktop's crash reporter no longer asks users for email addresses and the Socorro backend no longer stores email addresses. So there's no need for our Android crash reporter to ask for email addresses.
