### ISSUE TITLE
Crash reporter: Allow adding comments

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3262]
Fennec allows users to enter comments when the app crashed (to add STRs).

![image](https://user-images.githubusercontent.com/89638/58954667-1f382f80-879a-11e9-90ee-4141086dee67.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2651)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792915

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
