### ISSUE TITLE
[qr] Investigate the new qr scanner design

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/android-components#3267]
From https://github.com/mozilla-mobile/android-components/issues/3149#issuecomment-496708615

<img src=https://user-images.githubusercontent.com/68213/58515686-9c98ea00-8173-11e9-9152-eeaac1e2a464.png width=350 />

**Comment by mcarare** [comment]
Closing this in favor of https://github.com/mozilla-mobile/android-components/issues/4261, as the other contains more feedback.
