### ISSUE TITLE
Improve interface to create a FirefoxAccountsAuthFeature

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#3272]
Currently the [FirefoxAccountsAuthFeature](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt) requires a TabUseCase. I would love to be able to provide my own method for dealing with the authURL to better control the auth flow.

see: https://github.com/mozilla-mobile/fenix/pull/3153

**Comment by grigoryk** [comment]
`LoadUrlUseCase` should work well here.
