### ISSUE TITLE
Add `setFocus` to BrowserToolbar

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3274]
Per Fenix's issue: https://github.com/mozilla-mobile/fenix/issues/3175 we want a separate function (outside of [BrowserToolbar.editMode()](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt#L514-L523)) that has the ability to just set the focus of the editToolbar.

**Comment by pocmo** [comment]
@dector Now I wonder if calling `editMode()` should actually only focus if the toolbar is already in "edit mode" :)

**Comment by dector** [comment]
@pocmo May be like this but I'm bit worried that `editMode()` will violate SRP. :) It's inner logic is quite complex to understand already.

**Comment by pocmo** [comment]
@dector Yes, true, although right now it does a state transition even if it is already in that state.

**Comment by dector** [comment]
@pocmo I totally agree that `editMode()` should do smart state-transition instead.

**Comment by sblatz** [comment]
I tried working on this for a bit. Unfortunately it's not a quick fix since calling `focus()` highlights all of the text in the urlView.

**Comment by pocmo** [comment]
@sblatz In `EditToolbar` we set `setSelectAllOnFocus(true)` on `urlView`. :)

**Comment by pocmo** [comment]
We could try removing that call and calling `selectAll()` ourselves when switching to `editMode`. However I do not know if that has any other side effects.

**Comment by sblatz** [comment]
@pocmo Yes, I've tried setting it to false, but doing this:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/4400286/59522551-c9dbdc80-8e83-11e9-8d6b-dac9e28556c6.png">

Doesn't work since `focus()` does not happen immediately

**Comment by sblatz** [comment]
> We could try removing that call and calling selectAll() ourselves when switching to editMode. However I do not know if that has any other side effects.

This is a great suggestion. I will test this :)
