### ISSUE TITLE
HighlightableMenuItem has incorect icon constraints at large size

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3276]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/4400286/58987274-0c226100-8794-11e9-90a4-a8009cc30e6e.png">

**Comment by pocmo** [comment]
✨

**Comment by mcarare** [comment]
Verified as fixed. 
<img src =https://user-images.githubusercontent.com/48995920/68199777-5455e180-ffc7-11e9-9df7-63d1d7922e7b.png width = 30%>
