### ISSUE TITLE
ObserverRegistry.unregister claims to be thread-safe but isn't

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#3277]
See: https://github.com/mozilla-mobile/android-components/pull/3255/files#r290891814

**Comment by pocmo** [comment]
Looking at this now I think we should synchronize all access to internal properties - at least to have the values visible; otherwise we may not unregister a certain lifecycle/view observer because this thread just happened to not see it (yet).

**Comment by pocmo** [comment]
I think I tried to be too fancy by just synchronizing `observers` access and using `observers` as a lock. Now that we manipulate multiple properties we probably should just add `@Synchronized` to the public methods and avoid any more complexity.
