### ISSUE TITLE
Fenix syncs twice immediately after startup

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/android-components#3284]
The Fenix logs show that immediately after startup there are 2 syncs scheduled. They are correctly serialized, but as soon as the first completes the second starts. This is likely to make "warming up" of the browser slower than it needs to be.

One comes [from android components, here](https://searchfox.org/mozilla-mobile/rev/2316858e5e401a9c303e381e0c3b697afb1af28d/android-components/components/feature/sync/src/main/java/mozilla/components/feature/sync/BackgroundSyncManager.kt#209) and the other comes [from Fenix, here](https://searchfox.org/mozilla-mobile/rev/2316858e5e401a9c303e381e0c3b697afb1af28d/fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#112).

The a-c one is responding to onAuthenticated, so I suspect it does a "sync now" for the initial sync as an account is connected, but because Fenix also schedules a "startup" sync we end up getting called twice when starting when already connected. So I'm not sure where the fix for this should be, but I opened the bug in this repo and I'm confident one of the fine people here will get the bug to its rightful home :)

cc @grigoryk

**Comment by grigoryk** [comment]
Once https://github.com/mozilla-mobile/android-components/pull/4129 lands, fixing this in Fenix is a one-liner.
