### ISSUE TITLE
[Bug] App links - custom scheme URLs not reaching the SessionObserver

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#3293]
This affects logging into slack.

STR:
1. Go to https://api.slack.com/docs/deep-linking
2. Click on `Open in slack`.

Expected:
The slack app opens.

Observed:
The page reloads.

This is the a-c part of [fenix#1213][1].

[1]: https://github.com/mozilla-mobile/fenix/issues/1213

**Comment by pocmo** [comment]
Ah, yeah, probably because they are not actually getting loaded. Does the interceptor see them?

**Comment by jhugman** [comment]
Both interceptor and `GeckoEngineSession.onLoadRequest()` sees them. However, this isn't forwarded on to `EngineObserver.onLoadRequest()`.
