### ISSUE TITLE
Investigate top sites without icons

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3294]
From Fenix issue: https://github.com/mozilla-mobile/fenix/issues/3094 - The following pages from the top 50 pages don't show an icon in Firefox Preview. Let's debug what caused that and whether it's the page or our code that is responsible for that.

### Sites without icons

- [x] google.com,
  - icons.js: 0 icons
  - manual: No icons listed in document head
  - ✅ tippy-top-200: yes
  - favicon.ico: yes, but only 32x32
- [x] youtube.com,
  - icons.js: 2 icons, both tiny (16x16) and therefore not used
  - manual: no additional icons found
  - ✅ tippy-top-200: yes
  - favicon.ico: yes, but only 16x16
- [ ] qq.com,
  - ⚠️ icon.js: 2 large (180x180) icons. Needs investigation why they are not used.
- [ ] tmall.com,
  - icons.js: 0 icons
  - manual: No icons listed in document head
  - 🚫 tippy-top-200: no
  - favicon.ico: no
- [ ] twitter.com,
  - icons.js: very small and very large: 32x32, 1024x1024
  - manual: contains a "mask" icon (SVG) that we ignore: https://abs.twimg.com/responsive-web/web/icon-svg.9e211f626ec9d2812.svg
  - ✅ tippy-top-200: yes
- [ ] jd.com,
  - 🤔 about:debugging console not working
  - manual: No icons listed in document head
  - 🚫 tippy-top-200: no
- [ ] live.com,
  - icons.js: 0 icons
  - 🚫 tippy-top-200: no
  - manual: No icons listed in document head
- [ ] weibo.com,
  - ⚠️ icons.js: 5 icons. Looks like it should pick apple-touch-icon
  - ✅ tippy-top-200: yes
- [x] m.vk.com,
  - icons.js: only one small icon
  - manual: no additional icon
  - ✅ tippy-top-200: yes
- [x] taobao.com,
  - icons.js: only 16x16 default favicon
  - manual: no additional icon
  - ✅ tippy-top-200: yes
- [ ] 360.cn,
  - icons.js: only 16x16 default favicon
  - manual: no additional icon
  - 🚫 tippy-top-200: no
- [ ] twitch.tv,
  - ⚠️ icons.js: contains a good apple-touch-icon that doesn't get used
- [ ] alipay.com,
  - icon.js: no icon
  - manual: no icon
  - 🚫 tippy-top-200: no
  - default favicon: small
- [ ] ebay.com,
  - icons.js: only 16x16 default favicon
  - manual: no additional icon
  - 🚫 tippy-top-200: no
- [x] github.com,
  - icon.js: lots of options. the default favicon is small - do we not continue with the other icons?
  - ✅ tippy-top-200: yes
- [ ] gmw.com.
  - icons.js: no icons
  - manual: no icon
  - 🚫 tippy-top-200: no
- [ ] maps.google.com
  - ⚠️ icons.js: multiple options: should pick apple touch icon
  - ✅ tippy-top-200: yes (redirect to www.google.com/maps and there's an icon for google.com)
- [ ] https://www.camp-firefox.de/ and https://www.camp-firefox.de/forum/ (See comment below)
  - ✅ icon.js: 3 icons, should pick up apple-touch-icon
  - ✅ icon appears in sample browser
  - may be caused by Fenix integration: tab tray may not react to icon updates and only shows static

### Possible solutions:

- tippy-top icon list
- favicon.ico default icon
- supporting "mask" icons (SVG)
- fenix: support dynamic/asynchronous icon updates
- URL changes from content do not trigger web extension: No link between icons and URL

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2688)

**Comment by cadeyrn** [comment]
I se a problem with the icon of another website which is not part of Alexa Top 50. The icon sometimes appears and sometimes not. Can I post the URL here to get this investigated, too? Or do you prefer a separate issue?

**Comment by pocmo** [comment]
@cadeyrn Yes, absolutely, just post it here and I'll add it to the list.

**Comment by cadeyrn** [comment]
The affected website is https://www.camp-firefox.de. There is a CMS and and a forum (https://www.camp-firefox.de/forum). Both are one software so there is no technical difference between these two parts, both have the same icon code:

```
<!-- Icons -->
<link rel="apple-touch-icon" sizes="180x180" href="https://www.camp-firefox.de/images/favicon/2.apple-touch-icon.png">
<link rel="manifest" href="https://www.camp-firefox.de/images/favicon/2.manifest.json">
<link rel="shortcut icon" href="https://www.camp-firefox.de/images/favicon/2.favicon.ico">
<meta name="msapplication-config" content="https://www.camp-firefox.de/images/favicon/2.browserconfig.xml">
```

I attached two screenshots. In the first screenshot you can see that there is no website icon for the forum ("Forum"). In the second screenshot you can see that there is a website icon for the CMS ("Nachrichten"). But to make it more confusing: After using a Fenix a bit the opposite was true: suddenly there was a website icon for the forum and only the big "C" for the CMS.

![Screenshot_20190606-163936](https://user-images.githubusercontent.com/1100614/59102959-dfa24c80-892d-11e9-9a36-3f0a3710c630.png)
![Screenshot_20190606-163948](https://user-images.githubusercontent.com/1100614/59102985-e630c400-892d-11e9-9295-ca45b47f9e62.png)

**Comment by pocmo** [comment]
Summary:

- A lot of websites do not provide us with good icons and that's the reason we do not display one. We have some options to improve that situation:
  - Lookup icons with our "tippy top" list: #2047 - For listed hosts this gives us great icons
  - Default favicon (/favicon.ico): Existed for some pages that didn't have other icons listed in markup, however the quality was always super bad (16x16) so that it doesn't seem worth loading it if not linked in markup
- A small amount of pages did seem to have good icons but they were not used. Those pages need further debugging to investigate what happens in our code.
- One website provided a "mask" (SVG) icon that we do not support yet.
- Fenix does load an icon but not use one attached to `Session` or update the view once the icon gets loaded asynchronously. With that you see a generated icon even if we just loaded an icon for that page.

**Comment by pocmo** [comment]
In addition to the issues above:
* If content updates its URL dynamically then our web extension doesn't notice that and therefore we never link the new URL with the resources.

**Comment by pocmo** [comment]
Fenix follow-up: https://github.com/mozilla-mobile/fenix/issues/3846

**Comment by pocmo** [comment]
SVG favicons (mask): https://github.com/mozilla-mobile/android-components/issues/2081

**Comment by pocmo** [comment]
Using an absolute maximum size: https://github.com/mozilla-mobile/android-components/issues/3619

**Comment by pocmo** [comment]
Moving this out of the sprint: From the investigation I opened some follow-up issues that we should work through and move into the coming sprints.

**Comment by csadilek** [comment]
Investigation was completed and follow-up issues filed at the time.
