### ISSUE TITLE
Port Fenix's stripCommonPrefixes code

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3299]
As found [here](https://github.com/mozilla-mobile/fenix/pull/3191/files#diff-8ff21caf8656d55765bd244230ed71feR35), it'd be great to have this function available for all a-c

**Comment by pocmo** [comment]
For reference here are some other implementations from us:
* Focus: https://github.com/mozilla-mobile/focus-android/blob/e0881fc660332000e42e90d22ed811559b0cc114/app/src/main/java/org/mozilla/focus/utils/UrlUtils.java#L142-L160
* Fennec: https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/gecko/util/StringUtils.java#139-157

**Comment by cadeyrn** [comment]
There is already a method in AC:
https://github.com/mozilla-mobile/android-components/blob/master/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt#L9-L23

**Comment by pocmo** [comment]
@cadeyrn Ah, perfect. I couldn't find that.
