### ISSUE TITLE
Lock icon in custom tabs is really far to the right

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3300]
For some reason there is a large gap between the lock and the close button. We should reduce this space 😄 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/59069472-0e57ee80-886c-11e9-8028-e8e4de957424.png">

**Comment by jonalmeida** [comment]
Dupe: https://github.com/mozilla-mobile/android-components/issues/1514

Related: https://github.com/mozilla-mobile/reference-browser/issues/505

**Comment by pocmo** [comment]
Closing this and adding the Fenix label to #1514.
