### ISSUE TITLE
Toolbar doesn't return to display state when it loses focus

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/android-components#331]
When the user clicks on web content and the toolbar loses focus, it should return to display mode and not remain in edit mode.

Can we add an `onFocusChanged` listener that switches back to display mode when focus is lost?

**Comment by pocmo** [comment]
Interesting. That's something we would need to make configurable. Not every app wants that. For example in Firefox for Android you can interact with the "home panels" and the toolbar will lose focus but not switch to back display mode automatically.

@liuche The toolbar has to methods `editMode()` and `displayMode()` for switching manually. Are you able to implement this in your app by calling displayMode() whenever your content area gains focus (or whatever event you want to choose)?

**Comment by liuche** [comment]
I played around with a few things, but the challenge is that it's not just the WebView that needs to grab focus. We also want to clear the editMode when any of the tiles of the homescreen are focused.

I could do a workaround where I traverse the global view tree and check for the editToolbar, but at that point, I'm wondering if you could just expose a `onEditToolbarFocusLost` method. Let me know what you think!

**Comment by pocmo** [comment]
Okay, I'll have a look. I wonder at what point the toolbar loses focus and whether on Fire TV we lose Focus when the input keyboard is shown on top of the app.

**Comment by pocmo** [comment]
I opened PR #357 that introduces a new method:

```Kotlin
BrowserToolbar.setOnEditFocusChangeListener(listener: (Boolean) -> Unit)
```

With that I could implement the behavior you described in the sample app by adding this:

```Kotlin
        toolbar.setOnEditFocusChangeListener { hasFocus ->
            if (!hasFocus) {
                toolbar.displayMode()
            }
        }
```

I tested this on a Fire TV stick.
