### ISSUE TITLE
Recover when content process gets killed

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3310]
Fenix issue: https://github.com/mozilla-mobile/fenix/issues/1577
GeckoView bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1557096

Currently we see `onCrash()` getting called for a `GeckoSession` - but we have no clue whether that is a crash or whether the content process just got killed by Android to reclaim some resources.

We can handle crashes (via `lib-crash`) and allow the user to restore manually - but we need a way to know whether a call to `onCrash()` was just for a process kill so that we can auto-restore.

**Comment by pocmo** [comment]
Blocked: The added GeckoView API was backed out due to regressions :(
https://bugzilla.mozilla.org/show_bug.cgi?id=1557096

**Comment by jonalmeida** [comment]
This is no longer blocked on nightly GV. The `ContentDelegate.onKill` API is now available.
