### ISSUE TITLE
Improve TabCollection API

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3315]
In Fenix, we'd like the following features:

* [ ] The ability to grab a `cachedTabCollection` (or some in-memory version so we don't have to do an async call). This should stay updated with the database and be read only
* [x] (67373b2c6a841ebbd58057f3d2937d64d69a3ddf) A collection diff that is usable. Currently the collections are sent to use with different objects every time and it makes it difficult to actually produce a diff from them. See [our implementation](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt) for more info.

With these changes, we'd be able to get rid of our wrapper on the Fenix side :grinning:

Thanks @pocmo for your help on this!

**Comment by sblatz** [comment]
Let's include https://github.com/mozilla-mobile/android-components/issues/3302 as part of this :)

**Comment by pocmo** [comment]
67373b2c6a841ebbd58057f3d2937d64d69a3ddf should contain a fix for diffing. Now objects returned from the storage should correctly implement `equals()` and `hashCode()`.
