### ISSUE TITLE
Add build flavor to build sample browser with WebView

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#333]
For testing purposes.

We should also look at not restoring the state from another engine implementation when doing that, I guess. :)

**Comment by csadilek** [comment]
> We should also look at not restoring the state from another engine implementation when doing that, I guess. :)

What do you think about making the storage engine-specific i.e. for the `DefaultSessionStorage` it would write to different files for Gecko and WebView. This seems to make sense to me as we won't support restoring session states across engine anyway? We'd basically avoid the problem altogether.

**Comment by csadilek** [comment]
OK. I've filed: https://github.com/mozilla-mobile/android-components/issues/334

**Comment by csadilek** [comment]
Closed by: https://github.com/mozilla-mobile/android-components/commit/dfe7290d44b54689433fc648ea1f11008b47c2f6
