### ISSUE TITLE
Allow "restoreWithNewId" on a session

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3341]
In Fenix, we'd like the ability to restore a session with a newly created sessionId so that, when restoring a session from a collection, it won't clash with existing id's. 

See https://github.com/mozilla-mobile/fenix/issues/3215 for more information, and https://github.com/mozilla-mobile/fenix/issues/3280 for issues caused by duplicate id's.

**Comment by vesta0** [comment]
@sblatz I've been thinking about tracking back history for a session. I wonder if there are use cases where user may not expect or find it desirable. What do you think?

**Comment by sblatz** [comment]
@vesta0 I honestly find it a bit odd, as it's not something we do with bookmarks, and I likely only care about the last page I landed on (hence why I'm saving it with that page displaying). It's something we should discuss with UX, though :)

**Comment by pocmo** [comment]
@vesta0 @sblatz If you remove that part then you basically have re-invented bookmarks 😜 - and then we should just consider exposing bookmarks in this style - which has the advantage that those bookmarks+folders get synced too.

**Comment by sblatz** [comment]
> we should just consider exposing bookmarks in this style 

The engineering team actually discussed this with UX recently. I think it's a possible solution moving forward. For now then, we should probably just implement this ticket?

**Comment by vesta0** [comment]
Sounds like the overall experience needs more thinking through. 

@sblatz I think what you are suggesting is to implement this ticket which is the underlying logic to restore a session with a newly created sessionId so we have the flexibility to tweak the sessions history if we want later on. If so then that sounds good to me.
