### ISSUE TITLE
Provide API to get providedDefault from SearchEngineManager

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#3344]
Fenix has a requirement to show the default (not selected) search engine at the top of the list.

I'm using `getDefaultSearchEngine` with the paramater `"."` to force the behavior that I need in [SearchEngineManager.kt](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/java/mozilla/components/browser/search/SearchEngineManager.kt)`. But we should get a more explicit API for this behavior

**Comment by gabrielluong** [comment]
Hello, I am interested in working on this unless this is already being worked on. Thanks!
