### ISSUE TITLE
Define deprecation process

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3359]
Related: #3281

We do not have a process about how we deprecate code and when we remove it.

**Comment by pocmo** [comment]
https://docs.oracle.com/javase/7/docs/technotes/guides/javadoc/deprecation/deprecation.html

**Comment by pocmo** [comment]
https://developers.google.com/api-client-library/java/

> Deprecated non-beta features will be removed eighteen months after the release in which they are first deprecated. You must fix your usages before this time. If you don't, any type of breakage might result, and you are not guaranteed a compilation error.

**Comment by pocmo** [comment]
https://softwareengineering.stackexchange.com/questions/67837/when-to-deprecate-and-when-to-delete-in-java

**Comment by Amejia481** [comment]
Some questions that I think we should answer:

- How often should we remove code after a deprecation warning?
- Are we going to have a standard to indicate so in the changelog?

**Comment by pocmo** [comment]
> How often should we remove code after a deprecation warning?

I think we should look how others do it and then derive a rule that fits our development cycle/style. Right now I'm thinking of something like: Deprecate in version X and remove in version X+Y (Y ~= 2). If it's fixed we can already create an issue for removing the API and move it into the right milestone.

> Are we going to have a standard to indicate so in the changelog?

Yes, we should absolutely do that. Also see #3281

**Comment by csadilek** [comment]
I think removing at X+2 seems fine. When X is released, we should send a deprecation warning to the mailing list and note it in the changelog. When X+1 is released, we should send a removal warning for the next version. At X+2, it's 👋 .

However, it could be > 2 in case we release really quickly :).

**Comment by pocmo** [comment]
> However, it could be > 2 in case we release really quickly :).

👍 

Also in cases were the code is used a lot and there is a bigger migration required. Think of us deprecating `browser-session` to move to `browser-state`. Removing that in two releases would be pretty hard for the app teams. :D
