### ISSUE TITLE
[WebPush] Support multiple push subscriptions

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3418]
From https://github.com/mozilla-mobile/android-components/issues/1919#issuecomment-486677816:

> With MessageRouter and Delivery Manager (mozilla/application-services#545), we should have this covered.

There should be some work involved migrating from the a-c baked-in version of DeliveryManager to the a-s one.

This should support WebPush/PWA subscriptions.

GeckoView issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1343678

**Comment by cpeterso** [comment]
@snorp landed GV support for Web Push in GV 71 Nightly, which will ride to GV 71 Beta on October 21. Unfortunately, this feature is too big to safely uplift to the current GV 70 Beta.

https://bugzilla.mozilla.org/show_bug.cgi?id=1343678
