### ISSUE TITLE
Define PWA installability

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3424]
Currently we are primarily focused on the existence of a manifest. Browsers often use other additional criteria to define if a pwa is "installable". For example Chrome's criteria are listed here:
https://developers.google.com/web/fundamentals/app-install-banners/#criteria

* What additional criteria should we use to define an app as installable?
* Does Gecko(View) do any checks before handing the manifest to us; e.g. does a manifest received through Gecko(View) mean it's already "installable"?

**Comment by NotWoods** [comment]
Websites are installable if:

- The site is served over HTTPS
- The site has a valid manifest with a name or short_name and the icons array contains an icon of at least 192x192
