### ISSUE TITLE
Persist and restore fxa state to avoid having to log in every time

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#343]
Currently a log in is required every time the app starts.

**Comment by csadilek** [comment]
This should be handled by the underlying FxA Rust lib. Let's keep this open for tracking purposes.

**Comment by vladikoff** [comment]
> extracted code/state

Just to clarify if you are talking about persisting OAuth `code` and `state` params you should not be doing that. `code` is one time use anyway. Might need to rename the issue to avoid confusion

**Comment by csadilek** [comment]
The FxA lib is currently exposing `fxa_to_json` and `fxa_from_json` for this. We still need to be able persist and restore the returned json.
