### ISSUE TITLE
DomainAutoCompleteProvider.autocomplete naming is untuitive

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#344]
It sounds like it would mutate the view being autocompleted but it doesn't. Maybe `DomainAutoCompleteProvider.getAutocompleteSuggestion(...)`? It also makes me wonder if the return type should be called, `DomainAutoCompleteProvider.Suggestion` rather than result.

**Comment by csadilek** [comment]
Closing this as per discussion in #345: https://github.com/mozilla-mobile/android-components/issues/345#issuecomment-402512701
