### ISSUE TITLE
InlineAutocompleteEditText.onAutocomplete naming is unintuitive

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#345]
It sounds like a callback that will be called when an autocompletion happens, rather than a method that would apply an autocomplete result/suggestion. Maybe `.applyAutocompleteSuggestion` or `useAutocompleteSuggestion`?

**Comment by csadilek** [comment]
I agree that `onAutocomplete` isn't the right name here, but #344 seems OK to me i.e. the provider autocompletes the input text and returns a result: 
`val result = autoCompleteProvider.autocomplete(inputText)`

I propose to only change `InlineAutocompleteEditText` (as suggested in this issue) to make it clear that it applies the result:
`
val result = autoCompleteProvider.autocomplete(inputText)
view.applyAutocompleteResult(AutocompleteResult(result.text, result.source, result.size))
`

Our design goal here was to keep the autocomplete provider and the UI component completely independent of each other. I think this is the cause for some additional complexity, making this not entirely intuitive. It seems that, with this one change, we can improve the situation. I would not want to introduce a dependency between the two components, and I think adding the complexity of a shared interface and module (for the provider) isn't justified either (at this point). While The API would be simpler, as we could simply pass a provider to the view, the complexity would just move to the dependency/module setup.

@pocmo @mcomella

**Comment by pocmo** [comment]
> I agree that onAutocomplete isn't the right name here

Agree! Just approved the PR.

Regarding #34: I think `autocomplete()` is fine. It's an action that does something and then returns a result. `getAutocompleteSuggestion` sounds to me like just a getter in a POJO and not necessarily something that *performs an action*.
