### ISSUE TITLE
Toolbar.setOnUrlChangeListener naming unintuitive

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#346]
From names alone, I'd think that:
- setAutocompleteFilter
- setOnUrlChangeListener

would both be called each time a character changes in the URL. Also, I'd think `setOnUrlChangeListener` could be called if the page changes the url whereas it appears to only change when the user commits a new address.

Perhaps we should call it `setOnUrlCommitedListener` or `setOnUserInputNewUrlListener`?

**Comment by pocmo** [comment]
I agree that *change* is not clear here. Following InlineAutocompleteEditText (setOnCommitListener) I think it would make sense to name it setOnUrlCommitListener on the Toolbar.
