### ISSUE TITLE
Add locale to default Sentry tags

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3478]
We were just debugging an issue where it would have been helpful to know about the locale of the crashing device. This seems to be missing from the default Sentry tags.

**Comment by pocmo** [comment]
Note: Requires data review.

**Comment by pocmo** [comment]
@rocketsroger Saw you picked this up: Do you think we can do that for Socorro too? Or should we file a separate issue?

**Comment by rocketsroger** [comment]
> @rocketsroger Saw you picked this up: Do you think we can do that for Socorro too? Or should we file a separate issue?

Sure, I'll do it for Socorro too.
