### ISSUE TITLE
Add support for Web Share API

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3486]
GeckoView will be adding a delegate for the Web Share API, which we should handle to show a native sharing prompt.

The delegate API is expected to pass data corresponding to parts of the Web Share API:
- `title`: optional string
- `text`: optional string
- `url`: optional URL string
- `files`: optional list of URIs representing files to share

At least one of those values will be defined.

The delegate API is expected to have the following callbacks:
- `onDismiss`: when the share panel is dismissed or an error occurs, this will tell GeckoView to send an `AbortError` to the web app.
- `onSuccess`: when the share is complete, this will tell GeckoView to resolve the share promise.

## Steps that the implementation should take:

1. If there are no share targets available, call `onDismiss` and abort these steps.
2. Present the user with a choice of one or more share targets, selected at the user agent's discretion. The user MUST be given the option to cancel rather than choosing any of the share targets (done by native share UI). Wait for the user's choice.
3. If the user chose to cancel the share operation, call `onDismiss` and abort these steps.
4. Activate the chosen share target, convert data to a format suitable for ingestion into the target, and transmit the converted data to the target. If an error occurs starting the target or transmitting the data, call `onDismiss` and abort these steps.
5. Once the data has been successfully transmitted to the target, call `onSuccess`.

---

Spec: https://wicg.github.io/web-share/level-2/
GeckoView Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1557039

**Comment by cpeterso** [comment]
The GV bug is assigned to Dylan for Q3, but work has stalled because there are higher priority GV bugs.

https://bugzilla.mozilla.org/show_bug.cgi?id=1402369

**Comment by cpeterso** [comment]
GV team plans to land the WebShare API in September (GV 71 Nightly): https://bugzilla.mozilla.org/show_bug.cgi?id=1402369
