### ISSUE TITLE
App crashes when setting USER_AGENT_MODE

### ISSUE THREAD

**Issue by dipiana** [mozilla-mobile/android-components#3492]
Hi,

this might be my mistake as I am completely new to Java. I would appreciate support very much in this regards!

I try to let a website load as the desktop version and therefore set the USER_AGENT_MODE to 1. With this line in my code, the app compiles without any error but crashes. Without the line, it works just fine.

```
package com.example.geckotest;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

import org.mozilla.geckoview.GeckoRuntime;
import org.mozilla.geckoview.GeckoSession;
import org.mozilla.geckoview.GeckoSessionSettings;
import org.mozilla.geckoview.GeckoView;

public class MainActivity extends AppCompatActivity {

    private GeckoView geckoview;
    private GeckoSession GeckoSession;
    private GeckoRuntime geckoRuntime;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        GeckoView view = findViewById(R.id.geckoview);
        GeckoSession session = new GeckoSession();

        GeckoSession.getSettings().setInt(GeckoSessionSettings.USER_AGENT_MODE, 1);

        GeckoRuntime runtime = GeckoRuntime.create(this);


        session.open(runtime);
        view.setSession(session);
        session.loadUri("https://google.com");

    }
}
```

What am I doing wrong? Thanks in advance!

**Comment by jonalmeida** [comment]
Hello, 

This looks like a GeckoView question (this is android-components) so you might get more support on IRC in the #gv channel for future questions. :)

You probably want to set the user agent on the instance of the session from what I see:
```kotlin
session.getSettings().setInt(GeckoSessionSettings.USER_AGENT_MODE, GeckoSessionSettings.USER_AGENT_MODE_DESKTOP);
```

Have you had to look at the quick start guide for GeckoView? That might solve some future problems that arise. https://mozilla.github.io/geckoview/consumer/docs/geckoview-quick-start

**Comment by pocmo** [comment]
> GeckoSession.getSettings().setInt(GeckoSessionSettings.USER_AGENT_MODE, 1);

FYI: Note that the settings object also has a setter for desktop mode.

If you are still facing this issue and if it looks like a GeckoView bug then please open a GeckoView bug here and include **GeckoView version*  and a *Stacktrace*  of your crash:
https://bugzilla.mozilla.org/enter_bug.cgi?product=GeckoView
