### ISSUE TITLE
Move .buildconfig.yml data into gradle files

### ISSUE THREAD

**Issue by mitchhentges** [mozilla-mobile/android-components#3503]
The type of user that most commonly updates the list of `android-components` modules (and per-module configuration) are `android-components` devs.
Rather than having them learn and memorize a new config format, we should move config into `gradle`, where the rest of the project build configuration happens

**Comment by pocmo** [comment]
CC @rpappalax who wanted to add an additional flag for whether a component needs to run ui/on-device tests.

**Comment by mitchhentges** [comment]
It sounds like that the "run ui/on-device tests" flag would need to exist regardless of how config is encoded (gradle, yaml). Just to make sure we're on the same page: this ticket shouldn't block adding that flag :)

**Comment by pocmo** [comment]
Yeah, agree! Only wanted to make @rpappalax aware that this move is happening. :)

**Comment by rpappalax** [comment]
@pocmo  thanks for the heads-up guys, I've started working on this.  I took a peak at application-services to see if they had done this but it looks like they opted not to take this route. @mitchhentges once you have a branch can you paste it here?   I'd like to see how it's going to look.

**Comment by mitchhentges** [comment]
@rpappalax I've shifted teams and won't be able to push this ticket further - I believe that @JohanLorenzo is probably the best Release Engineering contact to ask about how this will be prioritized.

**Comment by rpappalax** [comment]
howdy @JohanLorenzo! do you have this currently on your radar? How I implement this: https://github.com/mozilla-mobile/android-components/issues/3652 will be different depending on where the data is being pulled from.  🌞

**Comment by JohanLorenzo** [comment]
Hey Richard! I didn't, thanks for bringing it to my attention! Let's have a chat this week 🙂 I'm not sure what the scope of #3652 is and I'd need to see if moving `.buildconfig.yml` is a requirement or a nice-to-have.

**Comment by JohanLorenzo** [comment]
Discussed over video. @rpappalax and I agreed using `.buildconfig.yml` for #3652 for 3 reasons:

1. This enables #3652 to be done quickly
2. At the moment, no more than a couple of components are planned to support UI tests. Therefore, we don't need to heavily change `.buildconfig.yml` to make this real.
3. Changing a yaml file is a much easier task to do rather than deep diving in gradle.

**Comment by pocmo** [comment]
> This enables #3652 to be done quickly

💯

I like #3652 to be done quickly. 🙃
