### ISSUE TITLE
Add support for invalid URI schemas to Error Pages

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3517]
Fenix user story: https://github.com/mozilla-mobile/fenix/issues/3608

**Comment by Amejia481** [comment]
We have an [error page for that](https://github.com/mozilla-mobile/android-components/blob/b49cd72c5c27ad335fd1885a358071abc2c70214/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L682) but we are not getting [the corresponding callback](https://github.com/mozilla-mobile/android-components/blob/b49cd72c5c27ad335fd1885a358071abc2c70214/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L357) from GeckoView. I opened [an issue on Bugzilla for that](https://bugzilla.mozilla.org/show_bug.cgi?id=1563343).

**Comment by Amejia481** [comment]
As we already [had an error page for that](https://github.com/mozilla-mobile/android-components/blob/d40f5a40d8b1dbf20cfe472522282c677a3190bb/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L851), there is nothing more for us to do here.

![Screenshot_20191018-163104](https://user-images.githubusercontent.com/773158/67126399-f783ba00-f1c4-11e9-9aef-641d834ab418.png)
