### ISSUE TITLE
Remove fontInflationEnabled from all GV Engine Abstractions

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3522]
See: https://github.com/mozilla-mobile/fenix/issues/3639

@snorp wants us to remove it entirely because we should never be using it and he has a theory it's accidentally getting enabled somehow.

**Comment by snorp** [comment]
It turns out this is a bug in GV. Somehow enabling `automaticFontSizing` also enables (instead?) font inflation. See https://bugzilla.mozilla.org/show_bug.cgi?id=1561135

**Comment by ekager** [comment]
Closing because we use font inflation now
