### ISSUE TITLE
maven2 - geckoview nightly arr doesn't get pulled

### ISSUE THREAD

**Issue by kscm** [mozilla-mobile/android-components#3535]
Shortly after -nightly channel [disappeared](https://maven-default.stage.mozaws.net/?prefix=maven2/org/mozilla/geckoview/), pulling the arr from maven2 is failing, including for modified channel -nightly-try, when building with different abi targets as in the [official instructions](https://wiki.mozilla.org/Mobile/GeckoView).

Any ideas how set the pull of the [-nightly arr](https://maven-default.stage.mozaws.net/?prefix=maven2/org/mozilla/geckoview/geckoview-nightly-try-armeabi-v7a/69.0.20190620184700/) from maven?

**Comment by pocmo** [comment]
The links you posted are pointing to the staging server. The correct link is *maven.mozilla.org*:
https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/

**Comment by kscm** [comment]
thanks
ps.my bad - I was taking the build numbers from the wrong server, which started to deviate.
