### ISSUE TITLE
PublicSuffixList: Treats last segment of IP as public suffix

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3540]
getPublicSuffix(`127.0.0.1`) -> `1`

While this is technically correct ("If no rules match, the prevailing rule is "*"") it's still not what we want since we didn't input a "domain".

You can see that in Fenix's tabs tray where we strip the public suffix (IPs have only 3 segments).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2882)

**Comment by trupples** [comment]
I think this is also be the cause for mozilla-mobile/fenix#8048

**Comment by pocmo** [comment]
Yeah, that is pretty likely.

**Comment by dector** [comment]
@pocmo Should valid IPs be conceptually handled as exceptions?

**Comment by pocmo** [comment]
> @pocmo Should valid IPs be conceptually handled as exceptions?

I wonder if we want some other entry points that take a URL (or host) and return something more helpful. The PSL implementation is technically correct, but that is not actually what consumers want to use directly here, I think.

**Comment by dector** [comment]
Do you mean something like:

```
fun resolvePublicSuffix(url: String): PublicSuffixResolution

sealed class PublicSuffixResolution {
    data class Succeeded(val suffix: String) : PublicSuffixResolution()
	data class IP(val value: String): PublicSuffixResolution()
    data class Undefined(val sourceUrl: String): PublicSuffixResolution()
}
```

Better naming needed though :)

**Comment by pocmo** [comment]
I was thinking more of a `format` function that provides functionality specific for https://github.com/mozilla-mobile/fenix/issues/8048 - using the PSL internally.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793182

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
