### ISSUE TITLE
Improve popup windows dialogs 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#3549]
When a site is trying to show multiple popup windows Fennec shows only one dialog for allowing or deny all the popup window request, while in AC we are showing a dialog per popup window request. You can use this site to test http://www.popuptest.com/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2890)

**Comment by Amejia481** [comment]
Related [GeckoView issue ](https://bugzilla.mozilla.org/show_bug.cgi?id=1566446)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796345

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
