### ISSUE TITLE
Telemetry documentation

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/android-components#356]
Had someone drop into a telemetry channel to ask how to add a new mobile app to telemetry.

Is all that's needed is to add a new app name (like [here](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt#L45)) or is some server-side action required? (Is there a token that needs to be added for telemetry as well?)

**Comment by pocmo** [comment]
I started to write a documentation when adding it the core ping to Firefox Reality. The PR may be a good starting point for now:
https://github.com/MozillaReality/FirefoxReality/pull/57/files

**Comment by pocmo** [comment]
> Is all that's needed is to add a new app name (like here)

Yes, taking an existing configuration and changing the app name is a good start.

> (Is there a token that needs to be added for telemetry as well?)

No token is required for telemetry.

The app should take care of sending telemetry only for actual release users. Ideally building a release build will not just send telemetry either (to avoid release versions of forks sending telemetry automatically too) - a build flag that is only enabled in automation is preferable.

The telemetry team has this guide for testing pings:
https://docs.telemetry.mozilla.org/cookbooks/view_pings_cep.html

**Comment by liuche** [comment]
I've made a documentation page for the data review repo, which is some basic steps for how new projects should go through data review. Is there somewhere in the android-components Telemetry documentation where I could add this? https://github.com/mozilla/data-review/wiki/New-Projects-and-Data-Review

**Comment by pocmo** [comment]
The `service-telemetry` is deprecated.
