### ISSUE TITLE
SelectTabAction: Do not allow selecting tab that does not exist

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3564]
Currently we just copy over whatever ID is in the action without doing any validation.

* We could throw, that's what `SessionManager` does. However that will be silent at the moment; see #3563

* We could just ignore this. That works but somehow hides errors. However I wonder if because of the asynchronous reducing we may need to ignore this to avoid crashing after a quick remove+select?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2906)

**Comment by Pheonix73** [comment]
@pocmo could you elaborate more?
What is the expected behaviour and current behaviour?

**Comment by pocmo** [comment]
### Background

This is a change in the [`browser-state`](https://github.com/mozilla-mobile/android-components/tree/master/components/browser/state) component. This component is currently in development and bound to replace `browser-session`. It's purpose is to maintain the state in a [redux-like way](https://redux.js.org/introduction/core-concepts). In a nutshell: There's a `BrowserStore` that maintains an immutable `BrowserState`. Dispatching a `BrowserAction` on the store will internally create a new state and then notify all observers.

### Current behavior

In `BrowserState` we use the `selectedTabId` property to remember the ID of the tab that is currently selected:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt

This can be changed by dispatching a `SelectTabAction` on the store:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt#L54

This will be processed internally by the reducer and create a new state with the new ID:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TabListReducer.kt#L64-L66

### Expected behavior

There's currently no validation that the provided ID is actually the ID of a tab that exists in `BrowserState.tabs`.

We should throw an exception if a tab is getting selected that does not exist. We already do this when creating a new BrowserStore with a state:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/state/src/main/java/mozilla/components/browser/state/store/BrowserStore.kt#L27-L31

Let's throw an exception and also write a unit test for this new behavior.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793196

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
