### ISSUE TITLE
TippyTopPreparer: Pull list from service

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3565]
Currently we ship a JSON list with the `TippyTopPreparer`. However there's a web service that distributes the list via Kinto. We should just try to pull that list from the service and then get rid of the included list.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2912)

**Comment by pocmo** [comment]
tippy top service:
https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/tippytop/records

For questions: najiang

**Comment by mauryat** [comment]
@pocmo Can you assign this to me?

**Comment by pocmo** [comment]
@mauryat Assigned! Just make sure you do not work on to many things in parallel. Looks like you are already assigned to 7 open issues.

**Comment by mauryat** [comment]
@pocmo Sure! I had about 2 already in PR. Also, was waiting on questions for other open ones, so figured I might as well work on something else while I'm waiting on others. But, yeah I will make sure I don't have too many open!

**Comment by rocketsroger** [comment]
Moving this to backlog since I went with updating the built in Tippy Top list and lowering the minimum Icon size.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793164

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
