### ISSUE TITLE
Support Internationalized Domain Names (IDN)

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/android-components#3571]
I think we partially do this, but there are still some bugs reported against Fenix that are around IDN. We should probably aim to handle all IDN logic and rules inside A-C so that a browser does not have to worry about this.

Two good sources of info are:

* https://en.wikipedia.org/wiki/Internationalized_domain_name
* https://wiki.mozilla.org/IDN_Display_Algorithm

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2918)

**Comment by pocmo** [comment]
> there are still some bugs reported against Fenix

Links or it didn't happen. 🙃

**Comment by cpeterso** [comment]
Related GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1561634

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793228

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
