### ISSUE TITLE
Add intent handling

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3576]
## Steps to reproduce

1. Open this sample Google Form link via Sample Browser: https://forms.gle/rCg3diu7NUQo7QQq9
2. Sample Browser populates the address bar with link but user sees nothing

### Expected behavior

1. Open this sample Google Form link via Sample Browser: https://forms.gle/rCg3diu7NUQo7QQq9
2. Google Form opens

### Actual behavior

Sample Browser populates the address bar with link but user sees nothing

See [fenix issue](https://github.com/mozilla-mobile/fenix/issues/2576) for more discussion

**Comment by denschub** [comment]
Opening the short link with the Reference Browser/Fenix UA results in a 302 to an `intent://` URL:

```
# curl -I -H "User-Agent: Mozilla/5.0 (Android 7.0; Mobile; rv:69.0) Gecko/69.0 Firefox/69.0" https://forms.gle/rCg3diu7NUQo7QQq9
HTTP/2 302
location: intent://forms.gle/rCg3diu7NUQo7QQq9#Intent;package=com.google.android.gms;action=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK;scheme=https;S.browser_fallback_url=https://docs.google.com/forms/d/e/1FAIpQLSesvATqinDx2_uccD2kp2TPoIQcgs2S5DIbl8X1laL_xTdRMw/viewform%3Fusp%3Dsend_form;end;
```

And those got disabled again in https://github.com/mozilla-mobile/fenix/issues/3358.

**Comment by sblatz** [comment]
Good catch, @denschub. I'm going to keep this ticket open as a request to add support for intent handling.

**Comment by jhugman** [comment]
This is being tracked on the [Android Intent URLs board][0].

[0]: https://github.com/orgs/mozilla-mobile/projects/32
