### ISSUE TITLE
Add the ability to observe a store on the main thread

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#3577]
Currently all dispatching/reducing happens on a separate thread. If we intend to observe the store to update the UI we should provide a nice / distinct API to improve the ergonomics of the library.

**Comment by pocmo** [comment]
We have been looking into this and other things by writing helpers that "build" an observer. Right now we have an `onlyIfChanged` helper that also supports observing on the main thread. It's a bit verbose to use and the syntax is very likely to change in the future:

The idea is that you get a big state (`SomeState`) but you are only interested in a subset (`SomeOtherThing`) and only want to invoke the observer (on the main thread) if the subset has changed:

```kotlin
store.observer(onlyIfChanged<SomeState, SomeOtherThing>(
  onMainThread = true,
  map = { state -> /* Map the state to the thing you care about (SomeOtherthing) */ } ,
  then = { state, other ->
     // Will run on the main thread. Use "other" to update UI.
  }
))
```

**Comment by pocmo** [comment]
Another thing that I have locally is an extension method that allows you to observe the state as a Kotlin [BroadcastChannel](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-broadcast-channel/) and from that as a hot [Flow](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/). Using those Kotlin/Coroutine idioms will make it much easier to switch contexts.

**Comment by pocmo** [comment]
I think the channel API and the `consumeFrom()` helpers are doing that now.
