### ISSUE TITLE
SessionSuggestionProvider shows current selected session, does nothing

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3578]
See https://github.com/mozilla-mobile/fenix/issues/3695

**Comment by boek** [comment]
This is [another](https://github.com/mozilla-mobile/android-components/issues/1813) [case](https://github.com/mozilla-mobile/android-components/issues/1872) where we have to change a tiny bit of behavior.

**Comment by pocmo** [comment]
Oh yeah, we probably want to ignore the selected Session. @ekager you are assigned to this - are you intending to write a patch? Otherwise I'll move this into our next AC sprint. :)

**Comment by ekager** [comment]
@pocmo unassigning myself now! I did look at it briefly and I think it will be more complicated than just ignoring the current session because if you're coming from Home -> Search you probably DO want to see your currently selected session? That's why @boek linked the two use case issues above.

**Comment by Amejia481** [comment]
@pocmo @ekager  

Could having an additional parameter on [SessionSuggestionProvider](https://github.com/mozilla-mobile/android-components/blob/d4678eea596ea0130df9ef62ea4020573f38a468/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt#L18) to control when to exclude the selected session be an alternative?

Like `excludeSelectedSession`?

```kotlin
class SessionSuggestionProvider(
    private val sessionManager: SessionManager,
    private val selectTabUseCase: TabsUseCases.SelectTabUseCase,
    private val excludeSelectedSession: Boolean,
    private val icons: BrowserIcons? = null
)
```
