### ISSUE TITLE
Create a preference widget language switcher. 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#3585]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2934)

**Comment by Amejia481** [comment]
[Focus](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java) and [FFTV](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/widget/LocaleListPreference.java) implementation.

**Comment by liuche** [comment]
We're talking about this in Q4 planning, and Fenix will implement this in https://github.com/mozilla-mobile/fenix/issues/220

And it can be upstreamed into AC.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793181

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
