### ISSUE TITLE
Create a Gradle plugin to auto-detect with languages are support in an app

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#3586]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2936)

**Comment by Amejia481** [comment]
[Focus](https://github.com/mozilla-mobile/focus-android/blob/e9f5c60e297351edb5b4227f4aaf9004973825c7/app/build.gradle#L422) and [FFTV](https://github.com/mozilla-mobile/firefox-tv/blob/202345441ebdd778066efd9dae92c66cf68eb9fc/app/build.gradle#L272) implementation

**Comment by Pike** [comment]
If we're going with https://developer.android.com/studio/build/shrink-code.html#unused-alt-resources in https://github.com/mozilla-mobile/fenix/issues/3088#issuecomment-566975413, we'll need to do something tricky.

Which makes me wonder, can we use https://developer.android.com/reference/android/content/res/Configuration.html#getLocales() (Android N), and what does that return exactly in practice?

**Comment by BranescuMihai** [comment]
@Pike, unfortunately configuration.getLocales() returns an array with only the selected locale (example: ["en-US"]). There's also assets.getLocales(), which returns the list of all the **phone's** supported locales. Besides accessing through reflection an internal API method (`getNonSystemLocales()`) which I do not recommend, I don't know of any way to access our locales at runtime. 

So I think the Gradle task solution is the way to go

**Comment by Amejia481** [comment]
We could try https://github.com/mozilla-mobile/fenix/pull/7070/files#r360014168

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793180

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
