### ISSUE TITLE
Hold to select in browser-menu

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3587]
Originally filed by @Nxt3 in mozilla-mobile/fenix#3713:

> ### Why/User Benefit/User Problem
> 
> In Google Chrome (and other Android apps), when there is an overflow menu button, you can long press on the menu icon, and then drag down to the menu item you want to select.
> 
> In both Firefox apps, you have to tap the menu button and then tap the menu item you want.
> ### What/Requirements
> 
> I believe it's because Firefox uses a custom implementation of the overflow menu. I'd love to see this follow how other Android apps work.
> ### Acceptance Criteria (how do I know when I’m done?)
> 
> When the overflow menu behaves like other Android apps.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2938)

**Comment by yoasif** [comment]
I may have duped this here: https://github.com/mozilla-mobile/fenix/issues/3720

Please close that if so.

**Comment by jonalmeida** [comment]
R-B dupe: https://github.com/mozilla-mobile/reference-browser/issues/420

**Comment by Nxt3** [comment]
@NotWoods Dang man that was quick!

**Comment by Poopooracoocoo** [comment]
Aww. Now I feel bad for @dragocubed who filed an issue on the ref browser in Jan

**Comment by NotWoods** [comment]
For what it's worth I didn't even work at Mozilla in January ¯\_(ツ)_/¯

This one will still take some time!

**Comment by Poopooracoocoo** [comment]
What does r-b mean?

**Comment by yoasif** [comment]
reference browser.

**Comment by Nxt3** [comment]
@NotWoods And modest!

Where I work it takes a while for defects to make the whole cycle lol. Wish we could do defects like this.

Best of luck to ya with the new gig. 😎

**Comment by Poopooracoocoo** [comment]
Dang. Almost two years since the OG issue. Any updates on this?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793145

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
