### ISSUE TITLE
Support 'Open in' use cases for launching browser

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3594]
We've reached some interesting situations in Fenix where we want to open the browser from a custom tab. This is a use case we haven't covered that we should probably try.

Added `customtab` and `contextmenu` labels as places where these are probable places to have this option.

Added the `reasearch` tag as well, since we're not sure what the solution should be.

User stories/issues: 
 - R-B: 
   - https://github.com/mozilla-mobile/reference-browser/issues/766
   - https://github.com/mozilla-mobile/reference-browser/issues/621#issuecomment-467252502
 - Fenix: https://github.com/mozilla-mobile/fenix/issues/3739

**Comment by pocmo** [comment]
Related: #3620

**Comment by jonalmeida** [comment]
Closing as dupe of the above.
