### ISSUE TITLE
Fix EditToolbar keyEvent handling

### ISSUE THREAD

**Issue by julKali** [mozilla-mobile/android-components#3600]
The [EditToolbar](https://github.com/mozilla-mobile/android-components/blob/40653c6f1df71f0c4990c04a4c334bf9b75fd28f/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt#L44) class applies the following `setOnDispatchKeyEventPreImeListener` function on the `urlView` text view. 
```Kotlin
setOnDispatchKeyEventPreImeListener { event ->
            if (event?.keyCode == KeyEvent.KEYCODE_BACK) {
                toolbar.onEditCancelled()
            }
            false
}
```
The method checks if the pressed key is the BACK key and if it is, it calls `toolbar.onEditCancelled()`. However, it doesn't check the event action resulting in `toolbar.onEditCancelled()` getting called twice (once for ACTION_DOWN and once for ACTION_UP). I might be mistaken but as far as I can see this makes no sense, it should only trigger `onEditCancelled` once. I would thus suggest another check that makes sure it only reacts to UP (or DOWN).

After the KEYCODE_BACK check, the function always returns `false`. Again, I don't know all the mechanisms in this library and it might be intentional, but I am very sure that this causes [this Fenix issue](https://github.com/mozilla-mobile/fenix/issues/3767). Because the function returns `false`, the Android runtime passes the action down the chain and in Fenix it ultimately triggers the `onBackPressed` function in [HomeActivity](https://github.com/mozilla-mobile/fenix/blob/55f5c5d049fc4a93c3dbd65fb8d87a7f0832304a/app/src/main/java/org/mozilla/fenix/HomeActivity.kt#L164). This causes the app to close. I think it makes sense to let it return `true` because the event is already processed through the `onEditCancelled` method.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2944)

**Comment by pocmo** [comment]
Thanks for this detailed issue. The way you describe it makes sense and we should investigate and fix that.

**Comment by julKali** [comment]
@sblatz You added this behavior in reference to #2255. What do you think about this?

**Comment by sblatz** [comment]
This was intentionally added so that when pressing the "close" button on the keyboard (down arrow) we would navigate back to the home fragment in Fenix so that users didn't have to press back twice.

**Comment by sblatz** [comment]
@julKali it may be possible for us to return `false` only if the keyboard is showing. Perhaps that's a good fix?

**Comment by julKali** [comment]
Yeah, I think that could work. How do you find out if the virtual keyboard is open, though? As far as I know, there is no proper way to check this.
And by the way, I'm having a hard time figuring out how to use the local mozac source in Fenix for proper debugging. Is there any guide on how to set this up?

**Comment by sblatz** [comment]
@julKali [This](https://mozac.org/contributing/testing-components-inside-app) should be a good resource for that. Let me know if you have any questions!

**Comment by mauryat** [comment]
Is anyone working on this? If not, I'd like to work on this.

**Comment by julKali** [comment]
@mauryat in Fenix v1.1.0 the issue I referenced doesn't exist because you cannot close the keyboard anymore. Nevertheless, a refactor of setOnDispatchKeyEventPreImeListener would be very beneficial. While you're at it, you could also check why the keyboard isn't hideable anymore. It would be good to know if it was intentionally fixed or if it was just a side effect of some other change. Thank you in advance!

**Comment by mauryat** [comment]
The events fired on back button click (when keyboard is currently on display) are not consistent across devices. On my Samsung Galaxy S8, I only get a BACK+DOWN event. I don't get the UP event. It's best left as is in my view. Any thoughts?

**Comment by julKali** [comment]
I noticed that as well. When I fiddled with the code I didn't test it on multiple devices but even between Fenix and the test browser from mozac examples behaviors differed in terms of handling BACK key events. Yes, we could just leave it as is but in my opinion this would mean accepting uncertainty about the workings of the mozac codebase. If this were my project, I would definitely want to know why this is happening so that I can mitigate unwanted behavior. I believe Mozilla to be interested in clean and stable code, too.

**Comment by ajaypro** [comment]
Maybe we can handle the keyevent of backpress on `onKeyDown()` so that this event should happen across devices. 
e.g 

```
@Override
    public boolean onKeyDown(int keyCode, KeyEvent event) 
   {
        if ((keyCode == KeyEvent.KEYCODE_BACK)) 
        {
            return false; 
        }
        return super.onKeyDown(keyCode, event);
   }
```

**Comment by miDeb** [comment]
I was able to reproduce this by closing the keyboard with a gesture:
![Screen-Recording-20200522-112019](https://user-images.githubusercontent.com/44171190/82654272-bfdc6500-9c20-11ea-8a29-f98f1e0f6a1a.gif)
I will try to submit a PR to fix this.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796298

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
