### ISSUE TITLE
browser-icons: Consider using absolute icon size

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3619]
(From investigation in https://github.com/mozilla-mobile/android-components/issues/3294)

Currently we are using a density independent size (64dp). This translates to different sizes for different screen densities:

* hdpi | @ 64.00dp | = 96.00px
* xhdpi | @ 64.00dp | = 128.00px
* xxhdpi | @ 64.00dp | = 192.00px
* xxxhdpi | @ 64.00dp | = 256.00px

In theory that's great. But in reality icons often have fixed sizes and they go up to 512 and 1024. For example twitter serves a 1024x1024 icon and we ignore it. We probably should go up to at least 512 - if not 1024. The only reason to go lower should be a memory constrained device where loading one or multiple 1024x1024 bitmaps is just using too much memory.

**Comment by NotWoods** [comment]
I wrote `ResizingProcessor` to deal with large icons for PWAs, its probably useful here too.
