### ISSUE TITLE
Automate changelog generation

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/android-components#3623]
What do you think about building changelog automatically?

It will add additional step to documentation delivering but has some upsides as well:

  - Data-driven approach can be used.
  - No need to deal with huge file that is growing quite fast.
  - Changelog entries can be post-processed (e.g. changed modules can be sorted alphabetically to simplify lookup).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2973)

**Comment by pocmo** [comment]
See #954 for a previous discussion.

Our changelog is intended to be more detailed / rich than just plain lists of changes (e.g. code samples). Where would we write that?

**Comment by dector** [comment]
@pocmo Thanks! I'll check it.

> Our changelog is intended to be more detailed / rich than just plain lists of changes (e.g. code samples). Where would we write that?

Making changelog-as-a-data doesn't contradict to providing snippets with examples. They can be handled as a part of the description but I would prefer some kind of samples/usage section.

**Comment by csadilek** [comment]
Closing in favour of https://github.com/mozilla-mobile/android-components/issues/7816.
