### ISSUE TITLE
Implement SearchEngineProvider using MLS

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3637]
Also see: #1720, https://github.com/mozilla-mobile/fenix/issues/3869

In Fennec we do a region lookup via MLS. Let's port this to AC so that we can use it in Fenix. Our updated `list.json` requires a region and using the locale for that is not that helpful.

**Comment by vesta0** [comment]
Let's try to fix this in this sprint please.

**Comment by pocmo** [comment]
- Code in Fennec: https://searchfox.org/mozilla-central/rev/da3f3eaaacb6fb344fd21ac29ace2da0e33f12d3/mobile/android/base/java/org/mozilla/gecko/search/SearchEngineManager.java#374-428
- https://location.services.mozilla.com/
- API docs: https://mozilla.github.io/ichnaea/api/index.html
- Seems like this is a good candidate for a new component, e.g. `service-mls` or `service-mozillalocationservice` or ...
- Code needs to be ported to use `concept-fetch`
- A token is needed for the service. So we'd need to request one for Fenix and potentially Reference Browser. There's a test token for development purposes.

**Comment by pocmo** [comment]
Moving this out of the sprint. Filed #3934 which seems to be a prerequisite to finishing this.
