### ISSUE TITLE
Check web app manifest for tab icons

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3642]
We current prioritize `apple-touch-icon` as one of the best icon sources. `apple-touch-icon` is traditionally used as a home screen icon when a website is added to the home screen in iOS. The `icons` field in the Web App Manifest serves to provide a standard way to declare icons for the home screen just like `apple-touch-icon`. 

We should read the icons field in the web app manifest when loading icons for the session and prioritize them above apple icons, since they represent the standard.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-2988)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793163

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
