### ISSUE TITLE
Show broken padlock on all HTTP sites

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3647]
Originally filed by @Madis0:
> ### Why/User Benefit/User Problem
> Users should be made aware that HTTP connections are not "normal", but unsecured.
> The desktop Firefox does it by showing [a broken padlock](https://design.firefox.com/icons/viewer/#secure%20broken) on the address bar of [HTTP sites](http://http-password.badssl.com/).
> 
> It also has several relevant about:config options for enabling additional warnings, such as "Not secure" text and icon change on all or private windows. Current Fennec and Fenix lack all of that, placing users at a risk.
> 
> ### What/Requirements
> Implement the following about:config options from desktop Firefox:
> 
> * security.insecure_connection_icon.enabled
> * security.insecure_connection_icon.pbmode.enabled
> * security.insecure_field_warning.contextual.enabled
> * security.insecure_password.ui.enabled
> 
> ### Acceptance Criteria (how do I know when I’m done?)
> * [ ]  Default-enabled warnings on password fields
> * [ ]  Config options for private tabs
> * [ ]  Config options for all tabs

GeckoView bug: [Bug 1563431](https://bugzilla.mozilla.org/show_bug.cgi?id=1563431)

**Comment by Madis0** [comment]
Fenix still needs a flag to mark all HTTP insecure as well, as that will be the default in desktop Firefox soon - [bug 1562881](https://bugzilla.mozilla.org/show_bug.cgi?id=1562881) (see D37790).

**Comment by NotWoods** [comment]
Changing this issue to affect all HTTP sites since desktop firefox shows the broken padlock for all.
