### ISSUE TITLE
Run sample browser (and other components) UI tests in automation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3652]
#3621 / #3651 introduces a first UI test for sample browser. Now let's run it in automation! :)

**Comment by pocmo** [comment]
@rpappalax Can you help us with that? I looked at `ui-test.sh` where we define `APK_APP` and `APK_TEST`. Is it possible to add the sample-browser test APK to the mix?

**Comment by pocmo** [comment]
Nominating this for the next sprint. We start to have on-device tests in multiple components now. We should start running them in automation.

**Comment by Dexterp37** [comment]
This is really important for making sure the Glean SDK doesn't break :) We have an instrumented test in `sample.glean` that makes sure we're able to send data as expected :)

**Comment by rpappalax** [comment]
> This is really important for making sure the Glean SDK doesn't break :) We have an instrumented test in `sample.glean` that makes sure we're able to send data as expected :)

OK,@Dexterp37, is there a specific kind of test that we could stand up that would accomplish this?  Also, do we only need this for 1 sample app to provide the kind of verification needed?  (I assume this one? https://github.com/mozilla-mobile/android-components/blob/master/samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt)

**Comment by Dexterp37** [comment]
> 
> 
> > This is really important for making sure the Glean SDK doesn't break :) We have an instrumented test in `sample.glean` that makes sure we're able to send data as expected :)
> 
> OK,@Dexterp37, is there a specific kind of test you're looking for that would accomplish this or it ok to just to start the app and browse a site (to ensure that glean doesn't crash the app)? In addition to doing some UI activity, do we need to start glean and verify that data is being pushed out? Also, do we only need this on 1 sample app to provide the kind of verification needed? (I assume this one? https://github.com/mozilla-mobile/android-components/blob/master/samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt)

Hey @rpappalax , thank you for your quick reply :)

We already [have the tests](https://github.com/mozilla-mobile/android-components/tree/master/samples/glean/src/androidTest/java/org/mozilla/samples/glean): we currently test that we collect and send a baseline ping when going to background and do some trivial validation on the received content.

However, looks like these tests do not run in automation (so we don't fail if we break things :( )

**Comment by rpappalax** [comment]
> > > This is really important for making sure the Glean SDK doesn't break :) We have an instrumented test in `sample.glean` that makes sure we're able to send data as expected :)
> > 
> > 
> > OK,@Dexterp37, is there a specific kind of test you're looking for that would accomplish this or it ok to just to start the app and browse a site (to ensure that glean doesn't crash the app)? In addition to doing some UI activity, do we need to start glean and verify that data is being pushed out? Also, do we only need this on 1 sample app to provide the kind of verification needed? (I assume this one? https://github.com/mozilla-mobile/android-components/blob/master/samples/glean/src/main/java/org/mozilla/samples/glean/GleanApplication.kt)
> 
> Hey @rpappalax , thank you for your quick reply :)
> 
> We already [have the tests](https://github.com/mozilla-mobile/android-components/tree/master/samples/glean/src/androidTest/java/org/mozilla/samples/glean): we currently test that we collect and send a baseline ping when going to background and do some trivial validation on the received content.
> 
> However, looks like these tests do not run in automation (so we don't fail if we break things :( )

@Dexterp37 Oh, that's much easier.  Is this the one you want to run?  https://github.com/mozilla-mobile/android-components/blob/master/samples/glean/src/androidTest/java/org/mozilla/samples/glean/pings/BaselinePingTest.kt

**Comment by Dexterp37** [comment]
> @Dexterp37 Oh, that's much easier. Is this the one you want to run? https://github.com/mozilla-mobile/android-components/blob/master/samples/glean/src/androidTest/java/org/mozilla/samples/glean/pings/BaselinePingTest.kt

@rpappalax both that and [this one](https://github.com/mozilla-mobile/android-components/blob/master/samples/glean/src/androidTest/java/org/mozilla/samples/glean/MainActivityTest.kt). Thanks!

**Comment by rpappalax** [comment]
@Dexterp37 putting this in place should address this, correct? https://bugzilla.mozilla.org/show_bug.cgi?id=1587821
+ @AaronMT @isabelrios

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 putting this in place should address this, correct? https://bugzilla.mozilla.org/show_bug.cgi?id=1587821

This is actually a different problem than the one in bug 1587821 (sorry if I was unclear!): this PR enables an integration test that's useful to guarantee that we don't mistakenly break the integration of the Glean SDK in Android Components (this is *very important*!), so while the bug that brought you here is for a different thing, I'd still appreciate any effort that could be poured on this 💯 👍 

Bug 1587821 is about investigating if instrumented tests are sending telemetry to the production endpoint (given your answer in the bug, they are!) and assessing if that's a concern from an analysis point of view

**Comment by isabelrios** [comment]
Hi @pocmo, @Dexterp37, as you know I have started to work on this issue. I'm not super familiar with taskcluster, firebase and so but I'm making some progress I would like to share. 

I know the desired option that was discussed is to read from `.buildconfig` file a new variable added, like `'ui-test'` to automatically detect if there are tests and then rum them. 
But things get complicated when trying to run the tests since each `component`, `samples-*` have different APK_PATH and/or APK_TEST_PATH. Also I heard that `.buildconfig` may be added to gradlew and will look different.

So, as a first approach, to simplify things and get tests running, I'm modifying only the [ui-test.sh](https://github.com/mozilla-mobile/android-components/blob/7fb465a173cd29c88e57a03fd14858bbb18d3cfc/automation/taskcluster/androidTest/ui-test.sh) script (to specify the different APK paths) and [kind.yml](https://github.com/mozilla-mobile/android-components/blob/7fb465a173cd29c88e57a03fd14858bbb18d3cfc/taskcluster/ci/test/kind.yml) file to call the script for each component/sample

Once we know the progress on the .buildconfig change, this solution could be changed/improved accordingly.
Please let me know if you have any thoughts on this. Thanks!

**Comment by pocmo** [comment]
This landed a while ago :)
