### ISSUE TITLE
Icon loading: Ignore fragment part of URL

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3662]
From investigation:
https://github.com/mozilla-mobile/android-components/issues/3294

- We should ignore the fragment part of the URL when loading an icon.
- We may only care about documents with a http/https URL.
- On icon load when comparing to the Session URL we need to ignore fragments too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3004)

**Comment by pocmo** [comment]
Follow-up from: https://github.com/mozilla-mobile/android-components/issues/3294

**Comment by mauryat** [comment]
>     * We should ignore the fragment part of the URL when loading an icon.
@pocmo Is this the same as point 3 below? 
>     * We may only care about documents with a http/https URL.
This will be the only code change required for this issue if I'm understanding it right.
>     * On icon load when comparing to the Session URL we need to ignore fragments too.
This should be taken care of in PR #4029

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793162

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
