### ISSUE TITLE
Investigate Session.icon clearing

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3663]
When navigating to a new URL we clear the icon on `Session`. But not always is that an actual navigation that will re-trigger the content script.

For example when loading twitch.tv then we start on:
* https://m.twitch.tv/?desktop-redirect=true

We load an icon for that page and then the URL changes to:
*  https://m.twitch.tv/

After that we clear the icon. The content script is not re-triggered. The result is that we do not have an icon for this page.

See also #3662 - should we ignore query parameters?

**Comment by pocmo** [comment]
Follow-up from https://github.com/mozilla-mobile/android-components/issues/3294

**Comment by mauryat** [comment]
Can I work on this (after I'm done with #3664)?

**Comment by pocmo** [comment]
Yes, absolutely. :)

Also filed #4007 which may be interesting too!

**Comment by mauryat** [comment]
Thank you! Will check the other one out too!
