### ISSUE TITLE
BrowserIcons: Configure loader differently for private sessions

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3664]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3008)

**Comment by mauryat** [comment]
@pocmo curious what exactly the task entails.

**Comment by pocmo** [comment]
@mauryat In private mode we do not save any browsing history. We should also not save icons for private sessions to disk.

**Comment by mauryat** [comment]
Thanks @pocmo ! I'd like to work on this if nobody is taking it.

**Comment by pocmo** [comment]
Sounds good. Do you have an idea how you'd want to expose this? One idea I had was to add a `private` flag to the `IconRequest` (default: `false`?) and use that internally. `IconMessageHandler` is the place where we start a load for a visited website. Here we also have access to the `Session` and could set the flag.

I didn't verify if that is a feasible approach or if there is a better one. Feel free to try other things. :)

**Comment by mauryat** [comment]
Hmm, that's a helpful tip! I was trying to initialize a separate instance of BrowserIcons with an isPrivate flag, but now realize I'd be needlessly creating another heavy-weight instance. Let me try your suggestions.

**Comment by kbrosnan** [comment]
Is this done? @pocmo

**Comment by csadilek** [comment]
Landed back in https://github.com/mozilla-mobile/android-components/pull/4012.
