### ISSUE TITLE
Expose useWideViewPort web setting

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/android-components#3666]
FFTV needs to override the WebSetting [`useWideViewPort`](https://developer.android.com/reference/android/webkit/WebSettings.html#setUseWideViewPort(boolean)), but it is currently not exposed.

**Comment by pocmo** [comment]
What's the use case? Do you have a link to a Fire TV issue for tracking?

We are currently modifying `useWideViewPort` when `toggleDesktopMode()` is used. But I assume you need it for other things?

**Comment by dnarcese** [comment]
It is causing some video placement issues. Here is the related issue: https://github.com/mozilla-mobile/firefox-tv/issues/2386#issuecomment-506551642.

**Comment by jonalmeida** [comment]
> What's the use case? Do you have a link to a Fire TV issue for tracking?
> 
> We are currently modifying `useWideViewPort` when `toggleDesktopMode()` is used. But I assume you need it for other things?

To add to what @pocmo said, toggling desktop mode (on Gecko or WebView) will change the value of `useWideViewPort` so we need to consider that too when we expose this settings.
