### ISSUE TITLE
Wait until WiFi is avaliable before starting downloads

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3677]
Update the download feature so that, optionally, new downloads are en-queued until WiFi is available. Downloads should not start when only connected to mobile data.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3024)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792950

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
