### ISSUE TITLE
App links: extract metadata from page to drive a smart app banner

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#3692]
Required by [fenix#3385][1].

Pull out the play store links, app name and app link from twitter card or facebook graph data metadata. 

Detect the presence of an Apple smart app banner metadata.

[1]: https://github.com/mozilla-mobile/fenix/issues/3385

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3041)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794684

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
