### ISSUE TITLE
App links: smart app banner UI

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#3693]
Requires #3692 
Part of [fenix#3385][1].

Show an toast to indicate that the page can be opened by an external app specified by the page.

If the app is not installed, offer an Install button, instead of an open button.

[1]: https://github.com/mozilla-mobile/fenix/issues/3385

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3042)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793204

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
