### ISSUE TITLE
Feature component to disable screenshots

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3707]
`window.addFlags(WindowManager.LayoutParams.FLAG_SECURE)` can be used to disable screenshots and screen recoding. 

We should have a feature component to manage this flag for the following use cases:
- When a setting is turned on
- When in private mode (possibly also controlled by a setting)

mozilla-mobile/fenix#2768
mozilla-mobile/fenix#2248
mozilla-mobile/fenix#3422

**Comment by pocmo** [comment]
I added a similar card to the "Fenix upstreaming" board a while ago. I think we have multiple "private mode" releated things (another one would be the private mode notification) that we could "upstream" into a `feature-private` or similar.
