### ISSUE TITLE
FFTV Search Codes Missing

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/android-components#3711]
Hey everyone, having a problem with search codes.  Back in A-C 45, `SearchEngineProvider#loadSearchEngines` used to give us a list of `SearchEngine`s with these identifiers
```
"google-2018", "bing", "amazondotcom", "ddg", "twitter", "wikipedia", "google-b-amzftv", "google-b-1-amzftv"
```
but the current version is giving us
```
"google-b-1-m", "bing", "amazondotcom", "ddg", "twitter", "wikipedia"
/* "google-b-amzftv" & "google-b-1-amzftv" are missing */
```

I'm not sure what version the change was made, but from our telemetry it looks like our search code usage starts dropping off in mid ~March~ April.

`SearchEngine` is final and its contructor is internal, so I don't see any way short of reflection (👎 ) for us to fill in the missing values on our side.  Is there any chance these values could be added back in?

**Comment by Baron-Severin** [comment]
After investigating with @csadilek (thanks again for the help!), we determined the root cause here.  A change was introduced in https://github.com/mozilla-mobile/android-components/commit/6909302cb0cbe02019ecc09db473fa16ed58e08c#diff-cad46bdc11579832adfcf538f3ba0d4cR63 that causes `AssetsSearchEngineProvider` to filter out FFTV search codes.  FFTV search codes have unique identifiers, but share their `name` field with other codes.  A-C expects this field to be unique, and this causes them to be filtered out in the linked code block.

We've identified a few potential solutions to this:
1) Update FFTV search code `name`s to be unique: we've tested and this does solve this problem.  @mkaply do you know if this would cause any downstream problems?  Our telemetry uses `identifier` instead of `name`, but I'm not sure who else might rely on it.
2) Change `AssetsSearchEngineProvider` to filter by `identifier` instead of name (_**probably not possible**_): This would be ideal, but we rely on the `searchOrder` field in `List.json` for our filtering.  This provides `name`s instead of `identifier`s, and we share this with desktop, so changing it is not trivial.

If no change can be made in A-C to deal with the root cause here, it would be a helpful change to fail fast when duplicate names are found.

**Comment by Baron-Severin** [comment]
I talked to @mkaply and his only concerns about changing the name were:
1) That their not matching codes already in A-C could cause problems with other A-C code
2) Any user facing display of the name would look bad

This was suggested by @csadilek, so I think 1 should be fine, and we aren't currently displaying these names in app.

**Comment by pocmo** [comment]
Once fixed we should look into adding test coverage for this use case to AC. I also wonder if we should finally upstream some of the filtering mechanism to AC so that it will be in sync and can be tested against AC changes.

**Comment by csadilek** [comment]
Thanks @Baron-Severin for the thorough summary! Looking at this again, I think that although the FireTV fix/workaround seems sufficient for now, this still needs a fix in Android Components. We currently do return all search plugins if no `searchOrder` is specified, but only the first one if a `searchOrder` is present for that name...
