### ISSUE TITLE
BrowserMenuSwitch should also support icon

### ISSUE THREAD

**Issue by bogas04** [mozilla-mobile/android-components#3715]
I was trying to fix https://github.com/mozilla-mobile/fenix/issues/1071 however I realized that `BrowserMenuSwitch` doesn't support icons like `BrowserMenuImageText`. Can we add another component like `BrowserMenuImageSwitch` to support icons?

Or if it's possible to compose `BrowserMenuImageText` with `BrowserMenuSwitch`, then that would be helpful as well. Thanks!

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/fenix/issues/1071 has no UX feedback yet.

**Comment by bogas04** [comment]
We've UX feedback now. 

https://github.com/mozilla-mobile/fenix/issues/1071#issuecomment-513928187

**Comment by mcarare** [comment]
closed with #4365
