### ISSUE TITLE
Research and prototype cross-browser test suite

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3718]
As part of the following project we want to explore shipping a cross-browser test suite living in the AC repository:
https://github.com/orgs/mozilla-mobile/projects/39

This issue is about exploring solutions to that problem and prototyping some ideas.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3064)

**Comment by pocmo** [comment]
An example of a similar test suite is `tooling-fetch-tests` which we run against all implementations of `concept-fetch`.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794689

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
