### ISSUE TITLE
Research and prototype component instrumentation framework

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3719]
When apps use shared UI components (e.g. the toolbar) then test code that instruments those components (e.g. "Type a URL into toolbar") is very similar too. This means as part of AC we could ship higher level testing APIs that make writing UI tests a much nicer experience for app teams.

This issue is about exploring some options and prototyping some ideas.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3066)

**Comment by pocmo** [comment]
Ideally those form building blocks for the cross-browser test suite (#3718): If you have custom UI components then you will need to write those instrumentations yourself. But if you use Android Components then they should work "automatically" with the cross-browser test suite.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794690

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
