### ISSUE TITLE
SessionManager.remove() with the selected session doesn't notify Observer onSessionSelected

### ISSUE THREAD

**Issue by asafh** [mozilla-mobile/android-components#3720]
recalculateSelectionIndex is supposed to return true if the selection was updated, however it performs the check by seeing if the new selection index is the same as before.  
In the case were we delete the selected session, i.e. at index=0. both the newly selected index and the previously selected index will be 0 (since recalculateSelectionIndex selects a new index only if we removed a session to the left of the selectedIndex).

```kotlin
var newSelectedIndex = when {
//.... cases for selectParentIfExists or no more sessions
        indexToRemove < selectedIndex -> selectedIndex - 1
        selectedIndex == values.size -> selectedIndex - 1
        else -> selectedIndex
}
//....
val selectionUpdated = newSelectedIndex != selectedIndex
```
Which in turn makes remove() avoid notifying the observers:
```kotlin
if (selectionUpdated && selectedIndex != NO_SELECTION) {
    notifyObservers { onSessionSelected(selectedSessionOrThrow) }
}
```
This can be solved by changing recalculateSelectionIndex
```kotlin
val selectionUpdated = newSelectedIndex != selectedIndex
```  
To:  
```kotlin
val selectionUpdated = indexToRemove == selectedIndex ||
     newSelectedIndex != selectedIndex
```
That is, the selection was updated if the selected index was updated OR if the item removed was stored in the selected index.

**Comment by pocmo** [comment]
Thank you for this bug report.

Is this the cause for a product bug in one of the Mozilla apps? If you have a bug link then please post that too. :)

**Comment by asafh** [comment]
Thank you for the speedy response :)  

At the moment I'm not aware of any app bug caused by this - I run into this bug when I implemented (mozilla-mobile/focus-android#4309) a feature to close tabs (mozilla-mobile/focus-android#1362) in focus-android which runs into this bug (though I've created a [workaround](https://github.com/mozilla-mobile/focus-android/pull/4309/commits/9ad35694649128fc37c77c02736dd8f5162a5756) for now)

**Comment by pocmo** [comment]
Ah, thank you. That's super helpful for context.

**Comment by vesta0** [comment]
@pocmo @csadilek will look at this at a later date, low priority for now.

**Comment by mawen7** [comment]
Can I open a PR with the suggested solution mentioned in the report?
At least for short term in case you want to investigate further. See https://github.com/mozilla-mobile/fenix/issues/5332
