### ISSUE TITLE
App links: enable mailto: sms: and tel: play-store app-links

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#3725]
This issue is to allow built in apps to be used. 

There are issues to cover enabling generalized app-links[1]. This is just for the special cases for custom schemes for apps we are sure are on the device: `sms`, `tel`, `mailto`, and `market`.

[1]: https://github.com/mozilla-mobile/android-components/issues/3687

**Comment by jhugman** [comment]
Message from @vesta0: fix this so we can ship something before [GV#1555337][1] is fixed.

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1555337

**Comment by sv-ohorvath** [comment]
Verified on Fenix Nightly 190731. Devices: Pixel (Android Q), Samsung Galaxy Tab A 6 (Android 5.1.1), Galaxy S8 (Android 9)
