### ISSUE TITLE
Allow specifying tokenserverUrl in ServerConfig

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#3729]
This is a follow-up to https://github.com/mozilla-mobile/android-components/pull/3579.

Currently, the only way to use a self-hosted sync server is by specifying a custom FxA endpoint via ServerConfig (which will then be used during tokenserver url configuration internally). However, self-hosting FxA server currently is not well documented, and generally quite experimental.

A much more common path - and this is what both Firefox Desktop and Firefox for Android currently support - is to specify a tokenserver URL. Token server in our current architecture is what's responsible for pointing the client to a specific storage node. In case of self-hosting, both a sync storage server and a token server are easily deployed via available docker containers. 

By allowing specifying tokenserver url as part of the ServerConfig passed into the account manager, we're enabling easy use of self-hosted sync infrastructure.

Actual work here should be pretty trivial - making sure we override tokenserver url stored within the `SyncAuthInfoCache`.

**Comment by tublitzed** [comment]
I don't seem to have perms in this repo to assign this to myself, so just as a heads up; I'm currently working on this.

**Comment by Mugurell** [comment]
@tublitzed Are you still working on this? Do you need any help?

**Comment by tublitzed** [comment]
@Mugurell - thanks! Yes, I am. I wound up getting tasked with a lot of unrelated items, hence the delay here. Plan is get to a PR open here tomorrow then to come back and work on getting [#3762 in Fenix](https://github.com/mozilla-mobile/fenix/issues/3762) connected to it.

**Comment by tublitzed** [comment]
This work is no longer going to happen in this repo. This first step will be handled [here in app services](https://github.com/mozilla/application-services/issues/2651) and all the work is tracked [here, in this epic](https://jira.mozilla.com/browse/SYNC-926)

**Comment by eoger** [comment]
Can we close this? We have landed what's necessary in https://github.com/mozilla-mobile/fenix/pull/8916.

**Comment by kbrosnan** [comment]
Closing
