### ISSUE TITLE
Fretboard: IsInExperiment needs to be separated from is A or B treatment

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#3731]
As Fretboard stands today, its experiments suffer from a very common data science error. The library has a function `IsInExperiment()`which conflates the concept of eligibility with experiment branches. In essence, there needs to be a way to specify whether a client is eligible for an experiment separately from whether that client received a A (control) treatment or a B (active) treatment. We need new methods and the existing method must change in behavior.

I'd propose that in addition to IsInExperiment, we need isActiveBranch and/or isControlBranch methods. And perhaps we should deprecate the current, broken method.

We noticed this issue because Firefox Focus had issues with its GeckoView experiment. As our data scientist stated, the experiment data was biased because one must always check eligibility BEFORE checking and announcing what branch you're in. The two concepts are separate and equally important to data science.

If we're still using Fretboard, we need to improve Fretboard's current UX design to match data science best practices.

**Comment by pocmo** [comment]
Note that `service-fretboard` is going away eventually. The telemetry team started working on `service-experiments` (which started as a fretboard fork) and therefore we should probably not do any further work on fretboard itself.

Some more info here:
https://docs.google.com/document/d/1qlX5lGXZ3MwF0LYSoCKQcUYEWP6zdAa388elusvallw/edit

Also cc-ing @georgf

**Comment by st3fan** [comment]
@colintheshots If Focus is the primary driver for this change then we should probably not do this right now - I think we are at the state where we will completely stop doing experiments in Focus.

**Comment by colintheshots** [comment]
Focus should be fine without this change. I resolved the problem for the data scientists by removing all filters from the experiment and then giving them a list of the affected locales which were biasing the experiment. We shouldn't need this for Focus.

This issue is more about other apps using Fretboard which require unbiased sample groups for data science experiments.

**Comment by pocmo** [comment]
To follow-up on `service-experiments`: We recently added it to RB:
https://github.com/mozilla-mobile/reference-browser/commit/98048391d2ba04e02eb5b88c7093160136bc678c

And are about to run the first test experiment soon:
https://github.com/mozilla-mobile/reference-browser/pull/827

**Comment by pocmo** [comment]
🛑 fretboard.
