### ISSUE TITLE
Handle the "not now, but maybe later" use case (in SyncConfig?)

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#3732]
Follow-up to https://github.com/mozilla-mobile/android-components/pull/3579

Currently if you don't specify a SyncConfig, sync will be disabled and a sync scope won't be obtained during authentication.

However, for applications that are planning to include syncing in the future, or for applications that may enable/disable it based on some remote flags, that behaviour means that applications are forced to manually specify sync scope via `applicationScopes` escape hatch. Otherwise, users authenticated while sync was disabled will not have a sync scope, and will be asked to re-authenticate once sync becomes enabled.

This is a good example of an information leak, and an "unknown unknown".

SyncConfig could provide a flag to indicate that sync scope should be obtained regardless, while still allowing disabling syncing?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3082)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794219

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
