### ISSUE TITLE
Document that consumer's should generally add `AndroidLogSink`

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#3733]
I've been using a-c for a while but I had no idea that a-c wasn't logging and that, in order to do so, I need to add an `AndroidLogSink` like https://github.com/mozilla-mobile/firefox-tv/pull/2502/files. We should document this best practice.

I wonder where this should be documented. The README? Would it be appropriate to create a, "Best practices" or "a-c new integration guide"?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3084)

**Comment by pocmo** [comment]
There's a short guide about logging in the support-base component README:
https://github.com/mozilla-mobile/android-components/tree/master/components/support/base#logging

But yeah, I think it's time to have some guides or best practices too. At the moment I'm collecting some topics for writing short blog articles (like for saving state) and that may be a candidate too.

**Comment by csadilek** [comment]
Closing in favour of https://github.com/mozilla-mobile/android-components/issues/4108, which should cover this.
