### ISSUE TITLE
Add empty default implementation for AccountObserver

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3734]
This would not require account observers to implement the entire interface if they don't want to.

For example, in push, we care only about `onAuthenticated` and `onLoggedOut`, but we have to implement the others with no-op.

The change should be simple enough as adding `= Unit` for all interface methods.

**Comment by gagahpangeran** [comment]
I am interested in working on this issue, but this is my first time in this project. Just tell and describe me what must I do.

**Comment by jonalmeida** [comment]
@gagahpangeran you should just have to add `= Unit` to the `AccountObserver` inteface methods. You can find it in the `concept-sync` component. :)

**Comment by pocmo** [comment]
Test coverage may ask for a test for those empty implementations 🤔

**Comment by gagahpangeran** [comment]
OK, I'll do it.

**Comment by gagahpangeran** [comment]
Hello, sorry if I ask a lot.

I just write the code like this

```kt
fun onAuthenticated(account: OAuthAccount = Unit)

fun onProfileUpdated(profile: Profile = Unit)
```

Is it right? Or there's something that I must import?

Thanks.

**Comment by jonalmeida** [comment]
@gagahpangeran yes that sounds right. Sebastian has a good point that the test coverage may need some tests to cover this. 

You can check code coverage by creating a PR, and our CI build will run our tests there. This way is easier, but alternatively you can run the tests locally too:
Run `./gradlew :concept-sync:testDebug -Pcoverage` first.
Then open the report at `components/concept/sync/build/reports/jacoco/jacocoTestReport/html/index.html` and go to the file/class you changed and see if it's green.

**Comment by jonalmeida** [comment]
@gagahpangeran I misread! The `= Unit` should be on the method level and not on the parameter. So that would look like `fun myFunction(parameter: MyType) = Unit`.

Sorry if I confused you earlier!
