### ISSUE TITLE
History/Bookmark Provider, make use of WritableHistoryConnection.acceptResult(searchString, url)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3735]
From the AS 0.34.0 changelog:

> - Added WritableHistoryConnection.acceptResult(searchString, url) for marking an awesomebar result as accepted. (#1332)
>    - Specifically, queryAutocomplete calls for searches that contain frequently accepted results are more highly ranked.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3088)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796419

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
