### ISSUE TITLE
Consider a 'Firefox Send' component

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3744]
_throws idea into the a-c universe.._

This issue might need to be closed if we have a product direction for it so that it could go there, but I'm starting off here!

We've started with a `feature-sendtab` and we can potentially extend that to be `feature-sendfile` to have a files encrypted(`lib-encrypt` in the future?), uploaded (`concept-fetch`) and have the link sent to a device (`feature-sendtab`) to be downloaded on the other device.

**Comment by pocmo** [comment]
:(
