### ISSUE TITLE
Don't pass 'wantsKeys=true` for non-key bearing scopes

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#3747]
Currently we always invoke `beginOAuthFlowAsync` with wantsKeys=true, which will result in a 500 FxA page if the requested scopes aren't key-bearing (e.g., if sync scope wasn't requested).

In practice this means that it's currently not possible to sign-in without configuring sync.

**Comment by grigoryk** [comment]
Even better if this is done at the library level, see https://github.com/mozilla/application-services/issues/1399.

**Comment by rfk** [comment]
FWIW, ref https://github.com/mozilla/application-services/issues/1400#issuecomment-511253606, I strongly support removing "wants keys" from the API and having it managed internally by the library, implied by what scopes are being requested.
