### ISSUE TITLE
App Links: Strict Mode Violation Accessing PackageManager DB

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#3748]
The App Links feature repeatedly accesses the PackageManager database from the Main Thread, resulting in a StrictMode violation for the disk access. On Fenix, this happens roughly twice per browser screen load. Let's see if we can background the work to speed up our apps.

Also, it seems like these accesses are happening far too often. Could we cache the value?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3101)

**Comment by jhugman** [comment]
Most, if not all, of this can go OTMT. We can also put it an `LruCache` to ameliorate repeated hitting of the package manager db.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793244

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
