### ISSUE TITLE
Custom tab with media notification opens the main browser when clicked

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3751]
STR:
1. Open a Custom Tab.
2. Play some media on it.
3. Observe the media notification showing up.
4. Click on the notification.

Expected:
- The notification opens the Custom Tab where the media element is playing.

Actual:
- The notification opens the main browser app.

**Comment by pocmo** [comment]
See comment here: https://github.com/mozilla-mobile/android-components/issues/3986#issuecomment-517634001

Chromium just sets no intent on media notifications for custom tabs. That may be a workaround here until we have a fix for #3986.

**Comment by pocmo** [comment]
> I looked at Chromium and surprise! they have the same problem and currently just do not set any intent on the notification at all:
> https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/media/ui/MediaNotificationManager.java?type=cs&q=setMediaStyle+.java&sq=package:chromium&g=0&l=993-1001
> 
> The code links to https://crbug.com/585395 but unfortunately I am not allowed to read that bug. :(
> 
> Anyhow, I verified this and yeah, when playing media in a custom tab then the notification is not clickable. I'll use this as workaround for #3751 until we have a solution for the issue here.
