### ISSUE TITLE
App-links: Suppress opening about:blank once opening an app-link

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#3753]
### STR

1. Navigate to a page with a `tel:` link on
2. Tap the telephone number. 
3. Observe switch to the dialer.
4. Switch app back to browser.

### Expected:

Browser is still on the page that offered the telephone number.

### Observed

Browser has a blank page.

Note: this may have come from a redirect.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3103)

**Comment by csadilek** [comment]
This has been fixed.
