### ISSUE TITLE
Remove deprecated GlobalSyncableStoreProvider

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3756]
There are currently two `GlobalSyncableStoreProvider`, so we should remove the old one.

Old: `mozilla.components.feature.sync.GlobalSyncableStoreProvider`
New: `mozilla.components.service.fxa.sync.GlobalSyncableStoreProvider`

**Comment by grigoryk** [comment]
`feature-sync` was removed from the tree in #3579, and `GlobalSyncableStoreProvider` moved over to `services.fxa.sync`. Re-open if this is somehow incorrect, but afaik there's only one copy of this class.

**Comment by jonalmeida** [comment]
I think I was still seeing the old instance because I needed to update my local snapshots. Thanks for clarifying!
