### ISSUE TITLE
'productFlavors' is including .so files for other architectures

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/android-components#376]
I built a release build of samples-fxa and it still had the `.so` files for other platforms:

![](http://v14d.com/i/5b3ea2f110b6e.jpg)

![](http://v14d.com/i/5b3ea3436d4a6.jpg)

We need to optimize the gradle script to exclude .so files that are not for the targeted platform

**Comment by vladikoff** [comment]
(I cannot add <FxA> labels to this due to lack of permissions, sorry)

**Comment by vladikoff** [comment]
Seems like we will need to introduce `ndk` `abiFilters` in gradle. Simple example:

```js
ndk {
  abiFilters "armeabi-v7a", "armeabi"
}
```

**Comment by pocmo** [comment]
That seems fine. We are supporting all those three platforms.

And app using the lib can either define an abiFilter, like you did. Or configure an APK split so that gradle will build three APKs that can be uploaded to Google Play:
https://developer.android.com/studio/build/configure-apk-splits

**Comment by aperfilyev** [comment]
There's also new https://developer.android.com/guide/app-bundle/

**Comment by vladikoff** [comment]
cc @eoger @carolkng

**Comment by grigoryk** [comment]
We can do this at the application level as needed.
