### ISSUE TITLE
Add SendTabFeature to feature-sendtab

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3769]
A lot of the code [in this PR][0] can be converted to a SendTabFeature in our new feature-sendtab component.

[0]: https://github.com/mozilla-mobile/fenix/pull/4041

**Comment by grigoryk** [comment]
As part of this work, re-consider touching `FirebaseMessaging.isAutoInitEnabled` flag as we login/logout. Current behaviour creates some non-obvious states, and will likely negatively affect other components that rely on push.

**Comment by jonalmeida** [comment]
> As part of this work, re-consider touching `FirebaseMessaging.isAutoInitEnabled` flag as we login/logout.

Sorry, I don't follow. Do you mean change the value of this flag in the feature when we login/logout or change the implementation of the `PushService#start/stop`?

If it's the latter, I'll file a separate issue since that would be related to the `lib-push-firebase` implementation for how to start/stop a service.

**Comment by grigoryk** [comment]
I meant to say, can we  _not do that at all_? From other conversations, I think the answer is "yes, we'll need to leave it as always `on` for other push-dependent code to work".

**Comment by jonalmeida** [comment]
Oh oops! I'm at the wrong end of the conversation timeline here. 😅
