### ISSUE TITLE
Custom Tab: Session shows blank page when the browser is killed

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3773]
We lose the intent that launched the CT when the app was killed so we can't restore styling and the session that was used i.e. the intent **and** the `Session` is lost.

Related issues:
 - Fenix: https://github.com/mozilla-mobile/fenix/issues/2383
 - R-B: https://github.com/mozilla-mobile/reference-browser/issues/614

**Comment by jonalmeida** [comment]
This might be related to https://github.com/mozilla-mobile/android-components/issues/3310 so should be re-tested after that lands.

Assigning self to follow-up.

**Comment by jonalmeida** [comment]
@jonalmeida test this in 24 hours.

**Comment by jonalmeida** [comment]
I tested this with custom tabs on r-b and I still see this issue.

**Comment by pocmo** [comment]
@jonalmeida Do you have STR for this?

Is it possible to quick-fix this by finishing the custom tab activity if there's no intent?

**Comment by jonalmeida** [comment]
My STR:
 - Note the last selected session in r-b (e.g. google.com)
 - Open a custom tab
 - Play a mobile game for an hour.
 - Go back to the custom tab and observe the session there.
   - If it shows google, then you know that the CT session was lost.

> Is it possible to quick-fix this by finishing the custom tab activity if there's no intent?

I think so, iirc this is roughly what Chrome was doing.

**Comment by jonalmeida** [comment]
I've found the issue to our problem.

When we have an activity that was opened via an intent, and we background that app so that it gets reclaimed by the OS, the last activity is re-created and the original intent is still there.

In our designs, we assumed the `IntentReceiverActivity` was the only entry point, so intent processing was done there, then the activity is finished and the `BrowserActivity` is started to load the ***processed*** intent in the new activity.

Now we see that we're getting the original intent in the `BrowserActivity` but we don't know how to handle it because no session was created for it (which is done by the intent processor).

This would also be the case for Fenix as well (but s/BrowserActivity/HomeActivity/).

The quick fix for this in r-b/f-b is to do `components.utils.intentProcessor.process(intent)` in the `CustomTabActivity` before calling super (the BrowserActivity). I'm not sure if this is the _right_ fix though.  ¯\\\_(ツ)\_/¯

**Comment by pocmo** [comment]
@jonalmeida Regarding `switching to use other apps for bit` -> This can't be reproduced with "don't keep activities" or disabling background processes in dev settings?

**Comment by pocmo** [comment]
> @pocmo From my last update it seems that it's persistence related, so re-creating the activity doesn't make a difference.

Then disabling background processes should reproduce it if you move the app to the background and then resume?

> a. Persist Custom Tab sessions (which can also be PWA/TWA sessions soon)?
> b. Acknowledge that the session no longer exists and just gracefully close the session? (this is what Chrome does)

Not persisting them was a design choice so far. So I'd vote for (B) for now.

**Comment by jonalmeida** [comment]
This is blocked on landing a fix for it by https://github.com/mozilla-mobile/fenix/issues/5041

**Comment by jonalmeida** [comment]
Going to close this as done since the fixes for it need to go into each individual app so that it handles removed sessions in the CustomTabIntegration classes.
