### ISSUE TITLE
Expose the page load time to ac users

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/android-components#3774]
It is possible that users of ac will want to know how long it took the underlying engine load pages. Although this is a metric that will _eventually_ surface through a proposed integration between Glean and Telemetry, this is a more urgent priority for ac users and need something immediately but is not a hack. This is a request to fill that gap. For the necessary integration, please see the PR  #3760. @bdekoz @pocmo @csadilek

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3118)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796487

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
