### ISSUE TITLE
Incorrect treatment of history redirect visit flags

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#3784]
As part of [fenix#1331][1], the idea that redirected items were being recorded as separate history visits. This could be due to redirects (`http://example.com` -> `https://example.com`, `https://example.com` -> `https://m.en.example.com`).

This is the other side of #3027 which is filtering them out once recorded. This is about not recording them in the first place.

[1]: https://github.com/mozilla-mobile/fenix/issues/1331

**Comment by grigoryk** [comment]
Looked around for redirect-related issues, this is probably the earliest one we have so going to hijack it.
