### ISSUE TITLE
Make history record titles when they are updated

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/android-components#3785]
As part of [fenix#1331][1], the idea that a visit title is not being recorded when it changed came up.

The `title` can be changed programmatically using `document.title`. Additionally, the URL can be changed programmatically with `history.pushState`. 

These should be kept in sync (perhaps with a debounce?) so that a given visit to the URL has a latest known good title. 

Good examples: PWAs using `history.pushState`, e.g. https://m.youtube.com

[1]: https://github.com/mozilla-mobile/fenix/issues/1331

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3130)

**Comment by csadilek** [comment]
This works now. Title is updated [here](https://github.com/mozilla-mobile/android-components/blob/main/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L969).
