### ISSUE TITLE
Handling "no sessions" in sample browser.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#379]
We need to handle the case where the user closes all tabs.

What happens in this case is probably up to the app. For example in Fennec we open a new tab that points to the start page. The sample browser currently just crashes because it wants to display the selected session which doesn't exist anymore.

**Comment by pocmo** [comment]
There are two options:

* (1) Make selectedSession nullable. With that our components can handle the situation gracefully. And the app can decide what to do in an observer. We have to update all our code that deals with selected session because now it can be nullable (which technically could have thrown an exception previously).

* (2) Add something like sessionManager.hasSelectedSession. With that we would have to wrap at least some parts and may introduce race conditions. And overall a nullable session may be nicer to use.

* (3) Pass some callback to session manager that will be invoked once there's no session anymore. The callback would return a new session to be inserted. With that our code would be simpler (because there's *always* a session). But we couldn't handle the situation of "no session" nicely anymore. At least in Focus that's actually a valid state (no tab).

**Comment by pocmo** [comment]
I did start with (1) but it's a bit verbose. We use the selected session in a bunch of places (e.g. use cases) and I would need to do `sessionManager.selectedSession!!`.

**Comment by pocmo** [comment]
Then again technically there's no difference between `sessionManager.selectedSession!!` and the IllegalStateException we throw from `selectedSession` if there's none.

**Comment by csadilek** [comment]
@pocmo I do think (1) is a good solution, but wondering if we could instead have selectedSession return a default e.g. Session("about:home") if it has no session. We could pass the default to the SessionManager when its initialized. This way we we wouldn't have to handle possible nulls everywhere. Wdyt?

**Comment by csadilek** [comment]
Or something like sessionManager.defaultSession = Session("about:home"), and we'd be returning that if there's no other session. Hmm not sure :).

**Comment by pocmo** [comment]
@csadilek The problem is that it's application specific, so it would need to be at least a lambda. And then there are situations (like in Focus) where we really do not want to have a session.
