### ISSUE TITLE
Explore storage of PWA icons

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3799]
We may want to re-evaluate how we store icons for Progressive Web Apps, and potentially store them in a more permanent location (#2046). The launcher will also store a copy of the icon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3148)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796447

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
