### ISSUE TITLE
Use EditToolbar and DisplayToolbar individually

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3802]
When a user clicks the BrowserToolbar in Fenix, it opens the Search screen and uses a different BrowserToolbar in edit mode. Would it make sense to expose the internal DisplayToolbar and EditToolbar classes?

cc: @boek

**Comment by pocmo** [comment]
As-is we definitely should not just expose them. But yeah, we have multiple toolbar things that we should revisit and improve. @sblatz and I were also interested in making it easier to layout the toolbar differently in apps more easily.

**Comment by NotWoods** [comment]
Custom Tabs/Progressive Web Apps is another use case, since the toolbar is only used for displaying the URL and not editing.

**Comment by pocmo** [comment]
Yeah, but that is supported. :)

**Comment by pocmo** [comment]
I hope later this year we can look at rewriting the Toolbar using Jetpack Compose and at that point we will probably end up with a bunch of composables that can also be used individually.
