### ISSUE TITLE
Nightly: Settings -> Help launches search

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3811]
STR:
* Use Firefox Preview Nightly
* Go to Settings
* Select "Help"

Expected: The help page loads.
Actual: A search is triggered.

It seems like this was caused by us introducing spaces in the version name; and we are not correctly escaping the URL we build.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3160)

**Comment by cadeyrn** [comment]
see also https://github.com/mozilla-mobile/fenix/issues/3892

**Comment by Amejia481** [comment]
@pocmo I think this issue should be on the Fenix repo? Or Does it have something related to AC?

**Comment by csadilek** [comment]
Fixed in https://github.com/mozilla-mobile/fenix/issues/3892 :)
