### ISSUE TITLE
Don't throw away small favicons

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3814]
Lots of websites only supply 16x16 favicons, and we currently throw out small icons in browser-icons. I think a small icon is better than nothing, and we could add padding around the icon so it doesn't need to be scaled up as much.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3162)

**Comment by pocmo** [comment]
We did experiment a lot with that in Fennec and those small icons always ended up being either tiny or an unrecognizable pixel soup.

**Comment by mauryat** [comment]
@pocmo Should this be closed then?

**Comment by j9t** [comment]
Can you clarify, does this here only relate to 16×16, or also to other sizes; and if to other sizes, up to which ones?

(I’m asking as #18382 covered 64×64 pixels, which is still small, but considerably larger than 16×16.)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793161

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
