### ISSUE TITLE
FxA accounts WebExtension

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#3826]
This is a prerequisite for #3817.

We need a WebExtension that we inject into `accounts.firefox.com` and establish a communication channel with the page. At the very least, that channel needs to support three types of messages, `content script -> kotlin`:
- `accountSignedIn` (code, state)
  - when user signs-in into existing account
  - this should allow us to stop using a page load interceptor to fish out `code,state`
- `accountSignedUp` (code, state, list of enabled sync engines)
  - when user signs-up for a new account
- `passwordChange`
  - when user changes their account password using the web UI

Possibly there are more messages in the future (`signOut`?).
So far it seems like we won't need a bi-directional channel for this WebExtension.

**Comment by grigoryk** [comment]
@vladikoff says that "we [also] need a status message", details TBD.

**Comment by vladikoff** [comment]
*status* message example (this should come from FENIX):

```
{
  "command": "fxaccounts:fxa_status",
  "messageId": "15638861786821",
  "data": {
    "signedInUser": {
      "email": "testuser@testuser.com",
      "sessionToken": "session-token",
      "uid": "uid",
      "verified": true
    },
    "capabilities": {
      "engines": [
        "creditcards",
        "addresses"
      ]
    }
  }
}
```

login Message (coming to Fenix):

```
"{\"id\":\"account_updates\",\"message\":{\"command\":\"fxaccounts:login\",\"data\":{\"customizeSync\":true,\"declinedSyncEngines\":[\"addons\"],\"email\":\"ar@a.com\",\"keyFetchToken\":\"91b58b05dac5289c731a2483940832e80223f8ca57dc8d63bd53aade59abc297\",\"offeredSyncEngines\":[\"bookmarks\",\"history\",\"passwords\",\"addons\",\"tabs\",\"prefs\",\"creditcards\",\"addresses\"],\"sessionToken\":\"e337c0b98c4113e702e97f215e57afd0239695fe68e8f2e97f86f8c827a7da48\",\"uid\":\"039ab421ffe74a0e9971e897d1890d46\",\"unwrapBKey\":\"ba822e0974a25aa18a55f07088c94fb8ceabcba20e3b1710c95177c7f0c627ee\",\"verified\":false,\"verifiedCanLinkAccount\":true},\"messageId\":null}}"
```

**Comment by grigoryk** [comment]
This is done.
