### ISSUE TITLE
Replace ViewBoundFeatureWrapper with viewLifecycleOwner

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3828]
We created `ViewBoundFeatureWrapper` to bind features to the lifetime of a `View` that could be shorter than the lifetime of the Fragment (if it is detached).

In recent versions of the AndroidX `Fragment` class a `viewLifecycleOwner` property was added. This is a lifecycle owner that mirrors the lifecycle of the view:

*  created after onViewStateRestored(Bundle)
* started after onStart()
* resumed after onResume()
* paused before onPause()
* stopped before onStop()
* destroyed before onDestroyView()

So this means we could just bind the feature to this lifecycle owner and do not need to use our wrapper anymore.

We could experiment with that in RB and then slowly migrate apps and get rid of `ViewBoundFeatureWrapper`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3177)

**Comment by pocmo** [comment]
We found a bug in `viewLifecycleOwner` that is triggered when the activity is getting recreated in Fenix (e.g. normal/private mode or theme changes). We should hold back until that is fixed.

In addition to that right now `viewLifecycleOwner` is only available in alpha builds of AndroidX. :(

**Comment by Amejia481** [comment]
@pocmo To keep track of the issue, do we know in which version of `viewLifecycleOwner` is the bug? Did we report this issue to Google?

**Comment by pocmo** [comment]
In all of them. Not reported yet. We first need to isolate it. It's in a very complex flow in Fenix.

**Comment by Amejia481** [comment]
Got it 👍

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793173

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
