### ISSUE TITLE
Increase code coverage in browser-storage-sync

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3831]
`browser-storage-sync` has 71% branch coverage, which can probably increase to get our code cov back up again to 85% (currently at 80%).

A quick skim of the jacoco reports show that we can make the most impact with `RustPlacesConnection`, `PlacesBookmarksStorage`, and `PlacesStorage`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3179)

**Comment by jonalmeida** [comment]
Adding to triage but I'd like to get to this in the sprint after the next one if no one has got to it yet.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796418

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
