### ISSUE TITLE
Feature request: class to tidy up URLs before sharing 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#3833]
URLs can have UTM parameters, referral links, the wrong localized paths etc. We control the URL being shared so maybe we should make some ext functions to clean up the URL before sharing from our mobile browsers.

Add-ons exist on desktop:
https://addons.mozilla.org/en-US/firefox/addon/link-cleaner/

https://addons.mozilla.org/en-US/firefox/addon/clearurls/

https://addons.mozilla.org/en-US/firefox/addon/neat-url/

On GitHub here:
https://github.com/Smile4ever/Neat-URL

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3182)

**Comment by ekager** [comment]
Edge on Android apparently has this feature https://twitter.com/EvEm_Relic/status/1152474577596903424?s=19

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795121

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
