### ISSUE TITLE
[bug] Switching to tab list starts at top of page (shows Firefox logo), jittery animation

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/android-components#3834]
Steps to reproduce:

1. Open enough tabs so that the current tab is not present at the top of the tab switcher screen
2. From an open page, tap the tab switcher

What happens:

Fenix animates to the tab switcher *at the top of the switcher, showing the Fenix logo*, then jumps down to the correct place.

Expected result:

Fenix should animate directly to where it ends up instead of taking a detour to the top of the tab switcher.

See recording: [signal-attachment-2019-07-19-141759.zip](https://github.com/mozilla-mobile/android-components/files/3412232/signal-attachment-2019-07-19-141759.zip)

**Comment by jonalmeida** [comment]
@yoasif was this intended to be a Fenix bug?

**Comment by yoasif** [comment]
Sorry, you are right -- is there an easy way to migrate or should I just refile?

**Comment by yoasif** [comment]
Refiled as https://github.com/mozilla-mobile/fenix/issues/4189

**Comment by jonalmeida** [comment]
I think there is, but I don't think I have that super power. :)
