### ISSUE TITLE
HighlightableMenuItem does not have selectableItemBackground

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3838]
I forgot this 😭

If you press with your finger it does not highlight the HighlightableMenuItem

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3189)

**Comment by csadilek** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/3978.
