### ISSUE TITLE
Port the week picker widget from Fennec

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#3844]
Related issue: https://github.com/mozilla-mobile/android-components/issues/1532

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3197)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796344

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
