### ISSUE TITLE
Android Intents URLs shouldn't start without user's gesture

### ISSUE THREAD

**Issue by elinesterov** [mozilla-mobile/android-components#3857]
*Background:*
With the implementation of android intents now it is possible to launch apps from a webpage.
See https://github.com/mozilla-mobile/android-components/issues/1132 and  https://developer.chrome.com/multidevice/android/intents for the background on it.
As Chrome's documentation says browser shouldn't launch an external app in the following cases:
  * When the Intent URI is redirected from a typed in URL.
  * When the Intent URI is initiated without a user gesture.

*Problem:*
Currently, it is possible to launch an external app through the intent without a user gesture through the usage of iframes.

*To reproduce:*
create a  page  with the following content:

```html
<html>
<head>
  <title>Android Intents URLs test</title>
</head>
<body>
  <iframe src="intent://mozilla.org#Intent;scheme=https;package=org.mozilla.firefox;action=android.intent.action.VIEW;end" style="display: none;"></iframe>
</body>
</html>
```
Open it in Firefox Mobile it will automatically open a new page https://mozilla.org

*Expected result:* Nothing happens.

Chrome implements it correctly. I didn't dig into the code logic, but we seem have something related to user gesture here: https://github.com/mozilla-mobile/android-components/blob/53fb640ccfc0ca9070bd4951f3adb204828935c7/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt#L250

Here is a  PR where these changes were introduced first: https://github.com/mozilla-mobile/android-components/pull/3058/commits/5ae7c1551b1ed550f67ab39a690a862827384dff#

**Comment by pocmo** [comment]
CC @jhugman

**Comment by jhugman** [comment]
This appears to be reliant on [GeckoView bug 1555337][1]. Copied STR for this issue to there.

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1555337

**Comment by jhugman** [comment]
The gecko view bug seems to be ready to test now.

This is now about ensuring that the `Document.hasValidTransientUserGestureActivation` is being [wired up to the `triggeredByWebContent`][1], instead of kept track (i.e. faked) in the session itself. 

[1]: https://github.com/mozilla-mobile/android-components/blob/b7bf724302816ac0687cd6a53430a8d107c0ea9f/components/browser/engine-gecko-beta/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L354

**Comment by cpeterso** [comment]
This bug is in the GV team's October sprint, but we haven't started working on it yet.

**Comment by cpeterso** [comment]
snorp fixed the GV bug in GV 72 Nightly:

https://bugzilla.mozilla.org/show_bug.cgi?id=1555337#c26

**Comment by rocketsroger** [comment]
related https://github.com/mozilla-mobile/fenix/issues/3177
