### ISSUE TITLE
Ship repackaged forUnitTests AS libraries

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3861]
### Problem

Applications using AC get AS dependencies automatically as transitive dependencies. When the app wants to write unit tests that exercise the whole stack including AS then they will need to add a `forUnitTests` dependency (e.g. `org.mozilla.appservices:places-forUnitTests`). This forces the app to synchronize the version of this dependency with the AS version that the AC dependency is using too.

In Fenix this looks like this:
https://github.com/mozilla-mobile/fenix/blob/master/buildSrc/src/main/java/Dependencies.kt#L36-L42

This is annoying and blows up easily when not done right.

### Solution

Let's ship a "dummy" component (like `support-test-appservices`) that includes all `forUnitTests` dependencies as transitive dependencies.

With that the app only needs to depend on this component with the same AC version as all other components. It will get the AS dependencies and does not need to manually sync version numbers.

**Comment by rocketsroger** [comment]
Looks like with https://github.com/mozilla-mobile/fenix/pull/4391 the process has been simplified
