### ISSUE TITLE
Only show default search suggestion if entered text was autocompleted

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#3865]
### Why/User Benefit/User Problem
Having the same text to be searched for in two places is redundant.
See Fenix issue - https://github.com/mozilla-mobile/fenix/issues/1742
![FenixSearchSuggestions](https://user-images.githubusercontent.com/11428869/61718421-a00fb280-ad6b-11e9-9720-38659e116977.png)

### Acceptance Criteria (how do I know when I’m done?)
If the url bar has the text autocompleted the default search suggestion (user entered text) should be shown. 
Else - the default search suggestion (user entered text) should be skipped. The app should show other suggestions or none.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3220)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796329

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
