### ISSUE TITLE
TWA: Pass notifications to TrustedWebActivityService

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3875]
Client TWA apps can register a `TrustedWebActivityService` to display notifications through the client app rather than the browser.

`TrustedWebActivityServiceConnectionManager` is used to communicate with these services. `TrustedWebActivityServiceConnectionManager#execute` is called with the scope and origin, then gets a `TrustedWebActivityServiceWrapper` in the callback. The `TrustedWebActivityServiceWrapper#notify` function should be called with an Android notification object to display through the service.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3233)

**Comment by jonalmeida** [comment]
Blocked on WebNotification support.

**Comment by jonalmeida** [comment]
This is no longer blocked since we have WebNotifications and WebPush (in a few days).

**Comment by jonalmeida** [comment]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1642345.
