### ISSUE TITLE
Beta Uplift: Recover when content process gets killed

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3877]
Fenix issue: mozilla-mobile/fenix#1577
GeckoView bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1557096

This was implemented for `browser-engine-gecko-nightly` in #3310. After the GV uplift has happened we can implement this for beta too.

**Comment by pocmo** [comment]
The API landed in mozilla-beta and I triggered a new GV Beta build.

**Comment by sblatz** [comment]
This doesn't seem like it should be blocked anymore. Are we able to get this in? :)

**Comment by sblatz** [comment]
Let's make sure this restores all tabs that crash (since they're all turning to `about:blank` even when just one process crashes).
