### ISSUE TITLE
Improve tooling around finding leaks

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3888]
We have been investigating and fixing leaks in our apps and components. Hunting them and fixing them is always challenging and time consuming. The scary part is that we often did not notice them for a long time and "randomly" stumbled upon them. We desperately need tooling to discover them automatically and way earlier.

The only tool I know is [LeakCanary](https://github.com/square/leakcanary). It's primary use case is detecting leaks while using the app.

Ideally we'd be able to detect such leaks in automation and in the best case can correlate them with a specific commit that introduced them.

**Comment by pocmo** [comment]
We could also look at custom solutions - maybe in conjunction with LeakCanary. In our browser apps we primary care about Activities, Fragments, EngineSessions, GeckoSessions, ...

**Comment by Amejia481** [comment]
We could take a look at LeakCanary 2 looks pretty promising:
- Can be used independently in production, for instance to report the number of leaking instances on an OutOfMemoryError crash.(LeakSentry)
- [Running it on instrumentation test](https://square.github.io/leakcanary/upgrading-to-leakcanary-2.0/#running-leakcanary-in-instrumentation-tests)

Talk about LeakCanary 2
https://youtu.be/LEX8dn4BLUw?list=PLn7H9CUCuXAu5r4kT8RcK8B2GuBqMODX3

**Comment by pocmo** [comment]
Yeah, just saw this too, this looks promising:
https://speakerdeck.com/pyricau/leakcanary-2?slide=28

**Comment by pocmo** [comment]
LeakCanary depends on androix-core 2.0 alpha something. Can't use it yet. :|

**Comment by pocmo** [comment]
The old version of LeakCanary also supports running in instrumentation. I'll try experimenting with that.

**Comment by pocmo** [comment]
![Screenshot_2019-07-24 Test results - Class org mozilla samples browser SmokeTests](https://user-images.githubusercontent.com/89638/61815343-5649c980-ae4a-11e9-9e4d-9e8541f2e44c.png)

Yay, I'm able to reproduce #3887 with a ui test and leak canary.

**Comment by pocmo** [comment]
Closing this for now: We now have a LeakDetectionRule that we can use in AC and apps. And we have an additional UI test that protects us against a leak we saw in the past.
