### ISSUE TITLE
"Save link as" option to download linked files

### ISSUE THREAD

**Issue by yoasif** [mozilla-mobile/android-components#3897]
### Why/User Benefit/User Problem

As a user, I would like to be able to download linked resources. 

As seen in request in https://www.reddit.com/r/firefox/comments/aufvo2/firefox_android_download_txt_not_open/

### What / Requirements

For links, user is able to long press to download the linked resource to their device. 

### Acceptance Criteria (how do I know when I’m done?)

User is able to long press on a link and select "Download link" to save the linked resource to their device. 

See also: mozilla-mobile/fenix#214

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3247)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792951

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
