### ISSUE TITLE
Detect leaks of EngineSession / GeckoSession

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3908]
Follow-up from #3888. We now have the ability to detect leaks during instrumented tests. By default leak canary will detect context, activity, fragment leaks. However a big category of leaks that we would want to avoid is leaks of EngineSession / GeckoSession instances. Let's see if we can add them to the leak detection.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3259)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794936

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
