### ISSUE TITLE
Making changes to a collection, moves it to the top of the list

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#3914]
Related issue [https://github.com/mozilla-mobile/fenix/issues/4239](https://github.com/mozilla-mobile/fenix/issues/4239) 

Do we want collections to be ordered by creation date, or we want to keep the most recent updated collections at top (as it is now) ?

**Comment by jonalmeida** [comment]
I'm not sure if there was a confirmation that this is what we want to do on Fenix just yet from looking at that issue.

**Comment by mcarare** [comment]
I know. I have asked on slack, but I did not get an answer. Still, because it was labeled as a P2, I prepared the fix, in case it would be needed later.
