### ISSUE TITLE
Test exceptional fetch client results in feature-downloads

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#3917]
We want to add tests for some failure cases with fetching a download, such as `IOException` and timeouts.

**Comment by R4md4c** [comment]
@jonalmeida I think this is also covered in my PR?

**Comment by jonalmeida** [comment]
Yes, that seems so. :)

You can add 'Closes #[issue_number]' the opening PR comment to link this issue in it as well.
