### ISSUE TITLE
Refactor CustomTab implementation with SessionManager

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3919]
Currently the way custom tabs are handled requires that consumers (like Fenix) have to constantly pass around and keep track of a `customTabSessionId` since a custom tab session is never `selected`. This results in a lot of bookkeeping on our end, and is something that should likely just be handled by the `sessionManager` itself.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3274)

**Comment by csadilek** [comment]
SessionManager has been removed.
