### ISSUE TITLE
Replace kotlin_coroutines_test usages with testing_coroutines

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3923]
In `Dependencies.kt` we seem to have a duplicate references for the `kotlinx-coroutine-test` library.

One called [`kotlin_coroutines_test`](https://github.com/mozilla-mobile/android-components/blob/master/buildSrc/src/main/java/Dependencies.kt#L66) and [`testing_coroutines`](https://github.com/mozilla-mobile/android-components/blob/master/buildSrc/src/main/java/Dependencies.kt#L73).

We should replace [all references](https://searchfox.org/mozilla-mobile/search?path=&q=kotlin_coroutines_test) to `kotlin_coroutines_test` since the testing one follows the naming convention we already use.

**Comment by cx0der** [comment]
I would like to give this a go.
