### ISSUE TITLE
Find in page should use private mode keyboard

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3939]
From: https://github.com/mozilla-mobile/fenix/issues/4192#issuecomment-515813150

In private mode "find in page" should use a keyboard in private mode. For a `Toolbar` we added a flag that allows the consumer to define what state (private/regular) is preferred.

**Comment by mcarare** [comment]
@pocmo With FindInPageIntegration in Fenix we could set the privacy of the keyboard without making any changes to FindInPageBar.

**Comment by pocmo** [comment]
If possible I would love to move as much of that logic as possible to AC to avoid similar bug reports for every other browser based on AC.

**Comment by mcarare** [comment]
Ok. In Fenix is just an added check when the bar is launched. I can add the logic in AC, but it is rather complicated on the Fenix side, because it does not actually call the FindInPageBar constructor so it could pass a "private" argument, like in a toolbar case.

**Comment by miDeb** [comment]
I'd like to work on this :)
