### ISSUE TITLE
[Bug] "Open with" dialogue opens when interacting with website's search

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/android-components#3944]
### Steps to reproduce
-Open Fenix and navigate to Amazon.ca
-Type something in the website's search box
-Tap on X to clear the search

(you can also replicate when interacting with website's search on freshcityfarms.com

### Expected behavior

Search clears

### Actual behavior

Search clears AND Open with browser dialogue opens

### Device information

* Android device: Pixel 3
* Fenix version:  Nightly 190726

![Screenshot_20190729-134351](https://user-images.githubusercontent.com/42752644/62069801-19455480-b207-11e9-954f-b4be27598d2a.png)

**Comment by pocmo** [comment]
In this case a request for `javascript:;` gets triggered. One option would be to just ignore the `javascript` scheme. But I'll explore some other options first.

**Comment by pocmo** [comment]
I'll trigger the AC 6.0.1 release build now to get that out for the next Fenix release.
