### ISSUE TITLE
Should be allowed to visit insecure website if desired

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#3960]
As reported [in the fenix repo](https://github.com/mozilla-mobile/fenix/issues/6380), we should be able to visit insecure sites if wanted. Currently we only give users the option to "go back"

This depends on a [GV bug to allow bypassing](https://bugzilla.mozilla.org/show_bug.cgi?id=1553265), and probably involves exposing the GV API.

**Comment by pocmo** [comment]
GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1553265

**Comment by kbrosnan** [comment]
https://badssl.com/ is a good test site for this.

**Comment by wisniewskit** [comment]
Note that in [bz1553265](https://bugzilla.mozilla.org/show_bug.cgi?id=1553265), support just landed on error pages to add a bypass for the current window's failed certificate via:
```
document.addCertException(
  true|false /* true == temporary, false == permanent */
).then(
  () => {
    location.reload();
  },
  err => {
    /* unexpected */
  }
);
````
