### ISSUE TITLE
I want to confirm a place

### ISSUE THREAD

**Issue by ghost** [mozilla-mobile/android-components#3966]
@jonalmeida @pocmo 
Hi,

Does the Android version fully support DOH?
https://en.wikipedia.org/wiki/DNS_over_HTTPS

In addition, I would like to ask if there is a maximum limit for the "integer" value in about:config?

**Comment by pocmo** [comment]
> Does the Android version fully support DOH?

Do you mean a specific app with that like Firefox (Preview)?

**Comment by demotw** [comment]
> > Does the Android version fully support DOH?
> 
> Do you mean a specific app with that like Firefox (Preview)?

Sorry!
I mean firefox Android 68 version.
network.trr.mode
network.trr.uri
network.trr.bootstrapAddress
Mainly these three.

The second problem is this:
https://support.mozilla.org/en-US/kb/about-config-editor-firefox
"Integer is a number"

**Comment by jonalmeida** [comment]
Since this is for fennec and the user account doesn't exist anymore, I'm closing this issue.

Feel free to ask question about fennec on irc.mozilla.org at #mobile or file a [bug on Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android).

**Comment by kbrosnan** [comment]
DoH will not be in Fennec (Firefox for Android) it is essentially feature complete and builds are on our ESR 68 branch.
