### ISSUE TITLE
Consider a feature to turn private mode for all features on/off

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3972]
Currently, apps need to take care of turning off features when private browser (e.g. awesomebar, history, sync). We should consider if it makes sense to observe the session type and do this for all features that shouldn't track users.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3324)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794685

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
