### ISSUE TITLE
Consider a theme feature to respond to different browsing states

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3973]
When switching between normal/private mode, we can consider making a `ThemeFeature` that would delegate which theme should be set.

Other considerations:
 - non-browsing mode themes (like dark mode).
 - custom tabs

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3326)

**Comment by jonalmeida** [comment]
This was a basic ThemeFeature I had written a while back for Fenix:
```diff
diff --git a/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt b/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
index d6e7e2e..ff0d257 100644
--- a/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
+++ b/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
@@ -92,6 +92,7 @@ class BrowserFragment : Fragment(), BackHandler, CoroutineScope {
     private val fullScreenFeature = ViewBoundFeatureWrapper<FullScreenFeature>()
     private val thumbnailsFeature = ViewBoundFeatureWrapper<ThumbnailsFeature>()
     private val customTabsIntegration = ViewBoundFeatureWrapper<CustomTabsIntegration>()
+    private val themeFeature = ViewBoundFeatureWrapper<ThemeFeature>()
     private lateinit var job: Job

     var sessionId: String? = null
@@ -273,6 +274,12 @@ class BrowserFragment : Fragment(), BackHandler, CoroutineScope {
             view = view
         )

+        themeFeature.set(
+            feature = ThemeFeature(sessionManager, requireActivity()),
+            owner = this,
+            view = view
+        )
+
         val actionEmitter = ActionBusFactory.get(this).getManagedEmitter(SearchAction::class.java)

         sessionId?.let { sessionId ->
diff --git a/app/src/main/java/org/mozilla/fenix/browser/ThemeFeature.kt b/app/src/main/java/org/mozilla/fenix/browser/ThemeFeature.kt
new file mode 100644
index 0000000..5983279
--- /dev/null
+++ b/app/src/main/java/org/mozilla/fenix/browser/ThemeFeature.kt
@@ -0,0 +1,32 @@
+package org.mozilla.fenix.browser
+
+import android.app.Activity
+import mozilla.components.browser.session.SelectionAwareSessionObserver
+import mozilla.components.browser.session.Session
+import mozilla.components.browser.session.SessionManager
+import mozilla.components.support.base.feature.LifecycleAwareFeature
+import org.mozilla.fenix.BrowsingModeManager
+import org.mozilla.fenix.HomeActivity
+
+/**
+ * Updates the theme based on the session selected.
+ */
+class ThemeFeature(
+    sessionManager: SessionManager,
+    private val activity: Activity
+) : LifecycleAwareFeature, SelectionAwareSessionObserver(sessionManager) {
+
+    override fun start() {
+        observeSelected()
+    }
+
+    override fun onSessionSelected(session: Session) {
+        val browsingModeManager = (activity as HomeActivity).browsingModeManager
+        if (session.private) {
+            browsingModeManager.mode = BrowsingModeManager.Mode.Private
+        } else {
+            browsingModeManager.mode = BrowsingModeManager.Mode.Normal
+        }
+        super.onSessionSelected(session)
+    }
+}

```

**Comment by jonalmeida** [comment]
> We may want to additionally consider that containers may have custom themes. Perhaps we need a system that lets the app define which themes can be used.

Yes! I was thinking about this today as well! 😄

You might have more knowledge on this. I was looking into having custom styles for each theme.

Some considerations to also make are that we have dark-mode which is a system theme and private mode which is our custom theme.

What I've noticed in Fenix, is that there are 4 states for themes: normal mode with light theme and dark theme, as well as private mode with light theme and dark theme, but the private mode dark theme is ignored since it doesn't have a use.

We need to consider flattening this in our manager to have the system dark theme to behave like a user mode theme.

That should give us the customisation for supporting themed containers.

**Comment by NotWoods** [comment]
I haven't worked too much with the system side. For custom tabs, color schemes are defined as a map of int/enum to [CustomTabColorSchemeParams](https://developer.android.com/reference/androidx/browser/customtabs/CustomTabColorSchemeParams). We could perhaps also use ints, but have some way to define which are valid?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794665

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
