### ISSUE TITLE
Update the month picker layout to adapt the month widget with independently of the amount of the string character.

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#3975]
Related https://github.com/mozilla-l10n/android-l10n/pull/56

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3328)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796499

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
