### ISSUE TITLE
Intermittent test failure in EventsStorageEngineTest

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3977]
```
SUITE: mozilla.components.service.glean.storages.EventsStorageEngineTest
  TEST: getSnapshot() correctly clears the stores
    [Robolectric] mozilla.components.service.glean.storages.EventsStorageEngineTest.getSnapshot() correctly clears the stores: sdk=28; resources=legacy
    [Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40
    I/AssetManager: no overlays.list file found
    I/MonitoringInstr: Instrumentation started!
    I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@56fd9962', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@56fd9962'
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 1
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
    I [glean/Glean] Metrics enabled: true
    I [glean/Glean] Registering pings for mozilla.components.service.glean.GleanMetrics.Pings
    I/CursorWindowStats: Created a new Cursor. # Open Cursors=1 (# cursors opened by this proc=1)
    D/SQLiteCursor: received count(*) from native_fill_window: 0
  FAILURE
```

TC build logs: https://tools.taskcluster.net/groups/Q4iXZm0qRYq8cm6KyFAB-g/tasks/LyEsgU91Sh2x5kmFWDr3dg/runs/0/logs/public%2Flogs%2Flive.log

cc: @travis79

**Comment by travis79** [comment]
Tracking this intermittent failure in this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1564218)

**Comment by jonalmeida** [comment]
Ran into this again: https://tools.taskcluster.net/groups/RL1rz5SPQp6lIwdjK7su9A/tasks/NTh2FQglSyK9uE_q76WFHA/runs/0/logs/public%2Flogs%2Flive.log

**Comment by travis79** [comment]
> Ran into this again: [tools.taskcluster.net/groups/RL1rz5SPQp6lIwdjK7su9A/tasks/NTh2FQglSyK9uE_q76WFHA/runs/0/logs/public%2Flogs%2Flive.log](https://tools.taskcluster.net/groups/RL1rz5SPQp6lIwdjK7su9A/tasks/NTh2FQglSyK9uE_q76WFHA/runs/0/logs/public%2Flogs%2Flive.log)

Thanks @jonalmeida!  I'll take a look at this ASAP.

**Comment by Dexterp37** [comment]
@jonalmeida all these problems will be gone by end of month: we're planning on moving most of the code to a different repo. Thank you for your patience.

**Comment by jonalmeida** [comment]
No worries, just keeping this here for tracking since I noticed Travis was doing that on the bugzilla as well. :)

**Comment by travis79** [comment]
Since this issue has been filed, we should have resolved the underlying problem.  See also https://bugzilla.mozilla.org/show_bug.cgi?id=1564218.
