### ISSUE TITLE
Optionally[api 23 and up] encrypt  encrypt the contents of AccountStorage

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#3982]

**Comment by vesta0** [comment]
This impacts newer devices (~60% of users)

**Comment by grigoryk** [comment]
We also want this for devices with a broader security thread model, where we can't rely as much on physical protection, such as FireTV.

**Comment by grigoryk** [comment]
With #4758 in place, this would work for all API levels we support.

**Comment by grigoryk** [comment]
We won't be doing secure storage for API21-22. Work for newer API levels will happen in https://github.com/mozilla-mobile/android-components/issues/3982

**Comment by ekager** [comment]
I think you meant work will happen in #2229

**Comment by grigoryk** [comment]
That _is_ what I meant, thank you! Also, that work is getting close to landing in https://github.com/mozilla-mobile/android-components/pull/5053.
