### ISSUE TITLE
Save/restore desktop mode into SessionStorage

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#3983]
If we're in desktop mode, save a snapshot of the sessions, and leave the app to return back after the app has been killed, we restore the session but are no longer in desktop mode.

STR:
1. Open and login to Slack
2. Observe the "Use our app page".
3. Toggle desktop mode.
4. Use Slack like a boss.
5. Use other apps until the browser app gets killed.
6. Return to browser app and observe the "Use our app page" again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3338)

**Comment by pocmo** [comment]
Related to #1384.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793195

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
