### ISSUE TITLE
Add ability to switch to specific custom tab activity

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#3986]
For issues like #3751 (media notification for custom tab) we need to be able to switch to a custom tab activity.

For the browser it's easy, we can either just invoke the launcher intent (MVP?) or use an intent action that we ask the app to handle. However for custom tabs that doesn't really work since there are multiple. Even if we defer to the app with an intent and the session id: How would the app know which activity we want to switch to?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3341)

**Comment by pocmo** [comment]
CC @NotWoods: Since you work on that code right now. Do you have some ideas here? :)

**Comment by pocmo** [comment]
I looked at Chromium and surprise! they have the same problem and currently just do not set any intent on the notification at all:
https://cs.chromium.org/chromium/src/chrome/android/java/src/org/chromium/chrome/browser/media/ui/MediaNotificationManager.java?type=cs&q=setMediaStyle+.java&sq=package:chromium&g=0&l=993-1001

The code links to https://crbug.com/585395 but unfortunately I am not allowed to read that bug. :(

Anyhow, I verified this and yeah, when playing media in a custom tab then the notification is not clickable. I'll use this as workaround for #3751 until we have a solution for the issue here.

**Comment by NotWoods** [comment]
No idea how I missed this because I've been dealing with the similar issues. (Maybe we chatted about this in Slack at some point?)

Since we need to select a tab to open, we need to pass in the custom tab UUID via our intent. However, if we can do this, so can other apps (correct me if I'm wrong here, please). Since UUIDs are unique this might be OK, I don't know if their values are leaked anywhere.

**Comment by NotWoods** [comment]
One potential alternative is that we could treat the last custom tab in the list as a special "selected" tab that could be opened by intent. If we needed to open a specific session, the store could just reorder it to be the last in the list. 

We could even just introduce a `selelectedCustomTabId`/`customTabIdToOpen` field in the browser store.

**Comment by pocmo** [comment]
I do not fully understand the `selectedCustomTabId` plan. Other than the browser with only one activity there can be multiple custom tab activities open at the same time?

**Comment by NotWoods** [comment]
We've determined that we'll lookup sessions by adding a session ID extra to intents.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796217

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
