### ISSUE TITLE
[Bug] Unary expressions are not evaluated in JEXL library

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/android-components#3996]
Unary expressions are not evaluated in JEXL library (e.g. `!false`).

However this functionality is present in [mozilla/mozjexl](https://github.com/mozilla/mozjexl):

```javascript
const mozjexl = require('mozjexl')

var context = {}

mozjexl.eval('!false', context).then(function(res) {
        console.log(res); // Prints "true"
});
```

Tip: Proper evaluator should be added into the file [`EvaluatorHandlers.kt`](https://github.com/mozilla-mobile/android-components/blob/master/components/lib/jexl/src/main/java/mozilla/components/lib/jexl/evaluator/EvaluatorHandlers.kt).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3349)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793199

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
