### ISSUE TITLE
Create cross-project way to ensure license compliance

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#4003]
Currently, each team maintains their own license compliance files, which is a lot of duplicated tedious and time-consuming work: we should create a solution to help ensure compliance across teams.

My two ideas, in order of preference, are:
- Automated: generate a licenses file as part of the build step
- Manual: create a pre-push/CI task that ensures a `dependencies` block cannot be updated without also updating licenses.html (and if there are no relevant changes, we can update a timestamp in a comment in the file).

To share this code, we could use [our shared gradle plugin](https://github.com/mozilla-mobile/android-automation-tools/tree/master/gradle-plugin).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3356)

**Comment by pocmo** [comment]
For reference Google has a gradle plugin for that too. But unfortunately it's in Google Play Services and closed-source. But it may still be helpful to look at how this is added to the build and app:
https://developers.google.com/android/guides/opensource

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795120

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
