### ISSUE TITLE
Load icons for URLs updated via history API

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4007]
Icon loading from a high level works like this:
* A page is loaded
* Our web extension is triggered (icons.js; document_end event)
  * https://github.com/mozilla-mobile/android-components/blob/master/components/browser/icons/src/main/assets/extensions/browser-icons/icons.js
  * https://github.com/mozilla-mobile/android-components/blob/master/components/browser/icons/src/main/assets/extensions/browser-icons/manifest.json#L9
* The extension looks for icon resources and reports them back
* The app code passes the icon resources to `BrowserIcons`

Some pages update the URL of the page by using the history API:
https://developer.mozilla.org/en-US/docs/Web/API/History_API

A famous example of this is the mobile YouTube page.

When the URL changes that way then no `document_end` event is triggered. This means our extension won't run and for that new URL we won't be able to display an icon (and fallback to generate one).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3360)

**Comment by mauryat** [comment]
Yes @pocmo , I'd like to work on this too!

**Comment by mauryat** [comment]
Quick question, you mentioned youtube's mobile page uses the history api to change the page url. Can you mention a sample use case? I can see that during auto-play the next video's url will be the new url. But, curious how the History API would come into play.

**Comment by pocmo** [comment]
Go to "youtube.com" and navigate around. You'll see the URL change but no actual full page load has happened (and our extension does not get triggered) - instead YouTube updates the page content and then the URL.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793160

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
