### ISSUE TITLE
Let "Save Image" canidate be used with video and audio elements

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4021]
Originally filed as mozilla-mobile/fenix#3703.

Users expect to be able to download video and audio files too. The save image canidate should be updated to work with those types.

**Comment by rocketsroger** [comment]
![device-2020-02-26-125001](https://user-images.githubusercontent.com/6579541/75372445-910b5880-5896-11ea-8d5c-f8c8074defea.png)
