### ISSUE TITLE
Allow "force re auth" in FxA

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#4027]
[AS have added a new option](https://github.com/mozilla/application-services/issues/1196) to `force_auth` when signing in. This option means that even if a user previously signed in with an account, their username is not remembered when they sign out (which is the current behavior we have).

We need hooks for this new API so we can do this [Fenix work](https://github.com/mozilla-mobile/fenix/issues/2833).

**Comment by rfk** [comment]
I recall AS taking a slightly different approach in the end, one that did not result in significant new API surface, so it may be the case that there's nothing new to expose here.

@vladikoff or @grigoryk, could you please comment in https://github.com/mozilla-mobile/fenix/issues/2833 to describe the required work in Fenix to consume this new behaviour?

**Comment by rocketsroger** [comment]
> I recall AS taking a slightly different approach in the end, one that did not result in significant new API surface, so it may be the case that there's nothing new to expose here.
> 
> @vladikoff or @grigoryk, could you please comment in [mozilla-mobile/fenix#2833](https://github.com/mozilla-mobile/fenix/issues/2833) to describe the required work in Fenix to consume this new behaviour?

As far as I can see.  The change https://github.com/mozilla/application-services/pull/1204 was never merged.

The change related to this was https://github.com/mozilla/application-services/pull/1414.  But 'disconnect' API tries to keep the profile email if it can.

**Comment by rocketsroger** [comment]
@sblatz do we still want to remove profile email when FxA is disconnected?  If so we need more changes in AS.

**Comment by rfk** [comment]
IIUC, this is because signing out of Fenix doesn't destroy the underlying `sessionToken`, meaning you're still signed in to accounts.firefox.com on the web. The webchannel work to share a single `sessionToken` between web content and the browser will make this situation better as a side-effect.

**Comment by rocketsroger** [comment]
Retested and confirmed after disconnect user's email is not cached when signing into FxA

**Comment by jonalmeida** [comment]
Re-opening to investigate a bit more.

**Comment by sblatz** [comment]
See https://github.com/mozilla-mobile/android-components/issues/4236#issuecomment-547535790 for why we're closing this for now.
