### ISSUE TITLE
Update to Android SDK 28

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#404]
* Focus: https://github.com/mozilla-mobile/focus-android/issues/2909
* Fire TV: https://github.com/mozilla-mobile/firefox-tv/issues/991

**Comment by pocmo** [comment]
We want to do that soon - but not too early to avoid forcing the apps to update before critical releases that may require a components update.

**Comment by pocmo** [comment]
Final support libraries are not released yet. Latest version: 28.0.0-rc01.

**Comment by pocmo** [comment]
Focus has moved to the new SDK.

I moved this into the 0.20 sprint to a least figure out if there are blockers. We may want to delay updating the SDK until the support libraries are released in a final version.

**Comment by pocmo** [comment]
Focus has moved to the new SDK.

I moved this into the 0.20 sprint to a least figure out if there are blockers. We may want to delay updating the SDK until the support libraries are released in a final version.

**Comment by pocmo** [comment]
There's a WIP PR but some libraries we depend on are not available in a final version yet. I'll move this to the next sprint.

**Comment by mcomella** [comment]
FYI: apparently the public API definitions are stable in 28 and the RC is to make sure the code is bug-free:

> This release candidate of the support library is considered feature-complete and its public API surface is stable. This release will be shipped as final stable version barring any critical issues that may arise. This release should be safe to use in production. Please report any issues to the public issue tracker. 

via https://developer.android.com/topic/libraries/support-library/revisions

Driving me nuts we can't use the real KTX yet. :P

**Comment by pocmo** [comment]
28.0.0 is out now! :)

Will update to the new SDK here.

Additionally filed #842 to update to androix - The new namespace is stable now too. This may happen in the next sprint though.

**Comment by pocmo** [comment]
Backing out and moving to the next sprint.
