### ISSUE TITLE
Move CrashReporter to engine abstraction

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4052]
We use the Gecko CrashReporter directly in `lib-crash` and compile it against GeckoView Nightly only. This lead to a breaking API change on the crash report that exists in nightly but not in beta/release.

Since the crash reporter doesn't have the powers of the engine abstraction we've built for the different variants of Gecko, we had to put in [a hacky change](https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/src/main/java/mozilla/components/lib/crash/service/MozillaSocorroService.kt#L42-L72) that fixes this those versions.

What we should do is to abstract out the crash reporter into the engine so that we can avoid this issue in the future (and also remove our original patch).

**Comment by pocmo** [comment]
Looks like a duplicate of https://github.com/mozilla-mobile/android-components/issues/2203

**Comment by jonalmeida** [comment]
Closing!
