### ISSUE TITLE
how can i use this like webview shouldInterceptRequest

### ISSUE THREAD

**Issue by hebehan** [mozilla-mobile/android-components#4057]
hello
I want use GeckoView like the webview，but i can't find some method like shouldInterceptRequest(view: WebView?,request: WebResourceRequest?)
I want to track every requst in the page and get the request headers, could you tell me some solution

**Comment by hebehan** [comment]
i also want to get cookie by url, how can i get it? who knows?

**Comment by Amejia481** [comment]
> I can't find some method like shouldInterceptRequest(view: WebView?,request: WebResourceRequest?)

Using Android Components depending of what it is your use case, I think you could have two options:

*   [Registering an observer to the session](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/session/README.md#session). You are not able to change if the url load.

* Using a [RequestInterceptor](https://github.com/mozilla-mobile/android-components/blob/master/components/concept/engine/src/main/java/mozilla/components/concept/engine/request/RequestInterceptor.kt). You can provide a custom behavior  [(example)](https://github.com/mozilla-mobile/android-components/blob/master/samples/browser/src/main/java/org/mozilla/samples/browser/request/SampleRequestInterceptor.kt).


I believe as now `GeckoView` doesn't expose cookies. cc: @cpeterso

**Comment by cpeterso** [comment]
> > i also want to get cookie by url, how can i get it? who knows?
> 
> I believe as now `GeckoView` doesn't expose cookies. cc: @cpeterso

@snorp? ^

Here is the GeckoView developer documentation for people that want to build an app using GeckoView. I don't see any mention of HTTP headers or cookies in GeckoViews' `org.mozilla.geckoview.GeckoWebExecutor` class.

https://mozilla.github.io/geckoview/javadoc/mozilla-central/index.html
