### ISSUE TITLE
Migrate BrowserToolbar and FindInPage behaviours to components

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4059]
`BrowserToolbarBehavior` and `FindInPageBarBehavior` are living in integration classes in Fenix. We may be able to move those out to be in a-c as well if they're reusable enough.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3401)

**Comment by pocmo** [comment]
This existed in AC first as `BrowserToolbarBottomBehavior` and I think was cloned in Fenix to deal with the quick action bar too. We probably can solve that in a generic way in AC.

**Comment by jonalmeida** [comment]
It seems like there are now bottom and top toolbar behaviours in Fenix. 🤷‍♂

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794677

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
