### ISSUE TITLE
Fennec history/bookmarks data import

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4066]
Fennec will soon grow an ability to share history/bookmarks with trusted applications, using the same mechanism we rely on for FxA auto-login. See https://bugzilla.mozilla.org/show_bug.cgi?id=1572549

This work tracks getting the `browser.db` file from Fennec's ContentProvider, and passing it over to a-s for processing. Relevant a-s tickets are https://github.com/mozilla/application-services/issues/1463 and https://github.com/mozilla/application-services/issues/1460

**Comment by pocmo** [comment]
* https://github.com/mozilla-mobile/android-components/issues/4565
* https://github.com/mozilla-mobile/android-components/issues/4566
