### ISSUE TITLE
Fennec logins & password data import

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4067]
Sibling of #4066.

Fennec will soon grow an ability to share logins/password data with trusted applications, using the same mechanism we rely on for FxA auto-login. See https://bugzilla.mozilla.org/show_bug.cgi?id=1572550

This work tracks getting logins information Fennec's ContentProvider, and passing it over to a-s for processing.
Depending on how Fennec shapes up, this may be either a path to a database file (preferred), or a bulk set of logins/passwords.

Relevant a-s ticket: https://github.com/mozilla/application-services/pull/1472

**Comment by grigoryk** [comment]
Let's capture how logins/password are currently stored, and what we need to do to import them.

Fennec stores logins/passwords in `signons.sqlite`. Most of the information is stored in plaintext, except for two fields: `encryptedUsername` and `encryptedPassword`. Both of these fields are processed in the same way.

These fields are ASN.1 DER ("distinguished encoding rules", see http://luca.ntop.org/Teaching/Appunti/asn1.html) encoded binary blobs, which are then further base64 encoded before being stored in the database.

Here is an example of a username field. In the database, it's stored as:
```
MDoEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECPJ/HCXFEG88BBAd07UCQxnrPb8CcsJKbRtA
```

Putting this through an [ASN.1 decoder](https://lapo.it/asn1js/#MDoEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECPJ_HCXFEG88BBAd07UCQxnrPb8CcsJKbRtA), we get the following (with my annotations for what these values represent):
```
SEQUENCE (3 elem)
  OCTET STRING (16 byte) F8000000000000000000000000000001 -- keyid
  SEQUENCE (2 elem)
    OBJECT IDENTIFIER 1.2.840.113549.3.7 des-EDE3-CBC (RSADSI encryptionAlgorithm) -- cipher
    OCTET STRING (8 byte) F27F1C25C5106F3C -- iv
  OCTET STRING (16 byte) 1DD3B5024319EB3DBF0272C24A6D1B40 -- ciphertext
```

This tells us basic details:
- cipher used to for encryption (TDES-CBC). "T" is for "Triple", so we have three keys (one is repeated). EDE stands for "encrypt-decrypt-encrypt".
- `keyid` name, which is a reference to a key stored in `key4.db`, which is our "main" TDES key
- `iv` - our second key for TDES
- ciphertext itself

So, we need to get the referenced key out of `key4.db` to actually decrypt this field.

`key4.db` stores PKCS #11 token objects. We need to find the one referenced by `keyid` above.

In pseudo-code, here's how to obtain a key from `key4.db`. We will need a `master password`, which by default - if not set by the user - is an empty string, "".
- `SELECT item1,item2 FROM metadata WHERE id = 'password';`
- item1 is `global salt`, item2 is DER-encoded blob containing: `entry salt` and `ciphertext`.
- `master password` is combined with `global salt` and `entry salt`, and from this combination we derive ` key` and `iv` necessary for the TDES cipher.
- item2, once decrypted with a correct `master password`, will contain a "password check" string.

Now that we know that our master password is correct, we obtain the `key` we want, specified by the `keyid` (see above):
- `SELECT a11,a102 FROM nssPrivate;`
- iterate through results until `a102` matches specified `keyid`
- `a11` will contain a DER-encoded blob containing:  `entry salt` and `ciphertext`.
- just as above, we combine `master password` with `entry salt` and `global salt` (from `metadata` table), derive `key` and `iv`, use them to decrypt `ciphertext`
- this gives us a `key`, which is the `key` that is identified by `keyid`.

Finally, we can use this `key` to decrypt contents of `encryptedUsername` and `encryptedPassword` fields.

So, how to actually implement a migration?
- in Fennec, all of these operations are handled by the NSS stack.
- for our migration code, we essentially have two options:
  - implement all of this in Kotlin. TDES is a cipher that was supported from API1+, but we will need an ability to decode ASN.1 DER blobs. AFAIK, there are no Android APIs for this, just some random libraries online. I'm somewhat surprised to not find DER decoders in Android's API, since they're used pretty extensively internally... Luckily, we have a very narrow set of DER types we need to supported - only three, I think, Sequence, Object Identifier, and Octet String.
  - so, **option 1**: write defensive, ad-hoc ASN.1 DER decoder limited just to the types we need, and then perform db querying and decrypting in Kotlin.
- in application-services, there's a `support/rc-crypto` component, which provides Rust bindings to a subset of NSS functions. Unfortunately, DER decoding functionality isn't exposed - and afaik as-is, `key4.db`-stored keys aren't supported either.
  - so, we can expose the necessary bindings in Rust - specifically, expose one of two (i think) DER decoders we have in NSS, and then either expose these parts of `rc-crypto` over FFI, or implement some parts of the migration code (like, decryption of username/password fields) entirely in Rust.
  - we can also implement the rest of the migration in Rust as well, at that point
  - so, **option 2**: provide Rust bindings for the NSS DER decoder, expose these via FFI; db querying/decrypting still happens in Kotlin.

I'm currently leaning towards **option 1**, since we really don't need a general-purpose DER decoder here, but rather just something that can fish out three values from these binary blobs.

**Comment by grigoryk** [comment]
As a reference, I find https://github.com/louisabraham/ffpass/blob/42349e32e0b9b00840860f1e03895e12beb4f240/ffpass/__init__.py to be much easier to read than our `SecretDecoderRing.cpp` (https://searchfox.org/mozilla-central/source/security/manager/ssl/SecretDecoderRing.cpp) stuff in mozilla-central - in Fennec, this is what encrypts/decrypts logins.

**Comment by grigoryk** [comment]
Here's one of the DER decoders we have in NSS: https://searchfox.org/mozilla-central/source/security/nss/lib/util/quickder.c

Exposing this over FFI is probably an overkill for this...

**Comment by grigoryk** [comment]
There's `javax.crypto.SecretKeyFactory`, with support for `PBEwithSHAAND3-KEYTRIPLEDES-CBC`, `PBEwithSHAAND2-KEYTRIPLEDES-CBC`, `PBEwithSHA1ANDDES` - one of those is probably the right one for getting at our key material.

**Comment by grigoryk** [comment]
Key material in key4.db is encrypted with `1.2.840.113549.1.12.5.1.3` (`pkcs-12-PBEWithSha1AndTripleDESCBC`).

OIDref [describes](http://oidref.com/1.2.840.113549.1.12.5.1.3) it as "Deprecated, use the incompatible but similar {1 2 840 113549 1 12 1 3} or {1 2 840 113549 1 12 1 4} instead".

Those two schemes is exactly what `SecretKeyFactory` supports (`PBEwithSHAAND3-KEYTRIPLEDES-CBC`, `PBEwithSHAAND2-KEYTRIPLEDES-CBC`).

The "incompatible but similar" is not very promising :(

**Comment by grigoryk** [comment]
Completing the loop - it all worked out, at least for the happy test cases I have. Couldn't use `SecretKeyFactory` for `PBEWithSha1AndTripleDESCBC`, but deriving key/iv material manually wasn't difficult.

**Comment by ebalazs-sv** [comment]
@grigoryk Hi! Since we don't have yet "Saved Logins" section in the migration builds, is there another way to verify that the logins and passwords are imported? Thanks!

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly migration build 01/13 with Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2). The tested scenarios are:
- with and without Master Password;
- very long and very short username;
- very long and very short password;
- logged in and not logged in;

There are no duplicates in saved logins.
I will leave this in Ready for QA until the Saved logins will also be available for testing on Release and Beta builds.
