### ISSUE TITLE
Explicitly set GeckoView dependency to have classifier `@aar`

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/android-components#4068]
For technical reasons, Gradle module substitution can't change the "classifier type" of substituted modules.  Also for technical reasons, the "default" type of modules is `@jar`, but the Android-Gradle plugin has internal work-arounds to make it find AARs.  Together, this means that module substitution isn't straightforward: substituting `org.mozilla.geckoview:geckoview-nightly` for `org.mozilla.geckoview:geckoview-default` will find `@jar` type modules, not `@aar`.

It is possible to work around this: consumers can always find some way to make `browser-engine-gecko-*` _not_ include the GeckoView dependency, and then include it (or substitute it) themselves.  But it would be easier to do that -- for example, using the approaches of [Bug 1533465](https://bugzilla.mozilla.org/show_bug.cgi?id=1533465) -- if `browser-engine-gecko-*` set the `@aar` classifier itself.  Concretely, that means using:
```
implementation "org.mozilla.geckoview:geckoview-nightly:$VERSION@aar"
```

I am not aware of any repercussions from setting the classifier explicitly, but it's possible there are some that I'm not aware of.

**Comment by ncalexan** [comment]
@pocmo what do you think?  Are you aware of fallout from doing this?  If we had this classifier set explicitly, we could use something like I suggested in the Bugzilla ticket above and avoid most of the work that Emilio had to do [to substitute in `r-b`](https://crisal.io/words/2019/08/08/more-geckoview-debugging-fun.html).

**Comment by pocmo** [comment]
> @pocmo what do you think? Are you aware of fallout from doing this?

👍 That looks good to me and I do not know of any reason not do to that.

I recently [substituted AC in RB](https://github.com/mozilla-mobile/reference-browser/pull/815) and it worked but it was a bit annoying to use:
 * Unfortunately this will import ALL AC modules even those that are not substituted. Which may make sense for Gradle but is a bit much in the IDE.
 * Somehow it also stuck the other way around: When I opened the AC project then the RB module showed up too. That was totally unexpected.
 * Reverting the substitution did not get rid of all the gradle modules (in AC and RB) and no clean and invalidate caches etc. really helped getting rid of them. :(

**Comment by pocmo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1533465#c14

**Comment by pocmo** [comment]
@ncalexan I still see the snakeyaml issue with GeckoView 70.0.20190818094547 running the sample browser on a Nexus 5 (Android 6.0.1).

```
                         E  FATAL EXCEPTION: main
                         E  Process: org.mozilla.samples.browser, PID: 18078
                         E  java.lang.NoClassDefFoundError: Failed resolution of: Lorg/yaml/snakeyaml/constructor/Constructor;
                         E      at org.mozilla.gecko.util.DebugConfig.fromFile(DebugConfig.java:40)
                         E      at org.mozilla.geckoview.GeckoRuntime.init(GeckoRuntime.java:279)
                         E      at org.mozilla.geckoview.GeckoRuntime.getDefault(GeckoRuntime.java:153)
                         E      at mozilla.components.browser.engine.gecko.GeckoEngine.<init>(GeckoEngine.kt:37)
                         E      at org.mozilla.samples.browser.Components$engine$2.invoke(Components.kt:16)
                         E      at org.mozilla.samples.browser.Components$engine$2.invoke(Components.kt:14)
                         E      at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                         E      at org.mozilla.samples.browser.Components.getEngine(Components.kt)
                         E      at org.mozilla.samples.browser.SampleApplication.onCreate(SampleApplication.kt:28)
                         E      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                         E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                         E      at android.app.ActivityThread.-wrap1(ActivityThread.java)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5417)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                         E  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.yaml.snakeyaml.constructor.Constructor" on path: DexPathList
                            [[zip file "/data/app/org.mozilla.samples.browser-1/base.apk"],nativeLibraryDirectories=[/data/app/org.mozilla.samples.browser-1
                            /lib/arm, /data/app/org.mozilla.samples.browser-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                         E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                         E      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                         E      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                         E      ... 19 more
                         E      Suppressed: java.lang.ClassNotFoundException: org.yaml.snakeyaml.constructor.Constructor
                         E          at java.lang.Class.classForName(Native Method)
                         E          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                         E          at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                         E          at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                         E          ... 20 more
                         E      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by scientificware** [comment]
My project doesn't work anymore.
I have the same problem with GeckoView in Android Studio.
