### ISSUE TITLE
FxA AccountObserver.onAuthenticated: what is considered a newAccount? Update docs

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#4069]
In 7.0.0, the `AccountObserver` interface added a `newAccount` parameter to the `onAuthenticated` method. However, I'm not sure what's considered a `newAccount`. The docs say,

> @param newAccount True if this is a new account that was authenticated.

Is a new account an account that:
- has _never_ been added to this app before? (i.e. it's not new if you log out and log back in)
- wasn't logged out but onAuthenticated is called? (e.g. on app start or when authenticating after re-auth is needed)
- if the user has signed into a second account on the device (if that's even possible)?

We should clarify what a `newAccount` is and update the docs.

@grigoryk Any thoughts?

**Comment by jonalmeida** [comment]
When the app is cold booted, the account is re-authenticated so the the `onAuthenticated` callback is fired. There are some use cases where you want to be notified when an account was authenticated only on the time that a new account was signed into.

If you logged into an account (newAccount is true), logged out, logged in again with the same or another account, you would get `newAccount` as true.

> - has never been added to this app before? (i.e. it's not new if you log out and log back in)

Any new login is considered a new account.

> - wasn't logged out but onAuthenticated is called? (e.g. on app start or when authenticating after re-auth is needed)

It won't fire for this.

> - has never been added to this app before? (i.e. it's not new if you log out and log back in)

This case isn't really possible, but if you have a fennec install and you re-authenticated that account in a new browser (e.g. Fenix, Fire TV), then technically that's a new account added to the app.

**Comment by mcomella** [comment]
Thanks for the explanation, Jonathan. I think the action item here is to update the documentation.

**Comment by jonalmeida** [comment]
Closing again since this was completed in another PR.
