### ISSUE TITLE
Migrate InflationAwareFeature to components

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4077]
We should move the [`InflationAwareFeature`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/InflationAwareFeature.kt) to a-c since it's re-usable across other feature components. This can live in the `support-base` component where the `LifecycleAwareFeature` also lives.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3416)

**Comment by jonalmeida** [comment]
Some comments from the open PR to address:
> I'm not sure whether we should actually land this wrapper that the app needs to implement. Instead we should have a way to build our features diretctly with ViewStub if that makes sense (e.g. not wrap FindInPageFeature in the app with the help of this wrapper, but instead make FindInPageFeature work with a ViewStub directly (and if needed extract that pattern into something to build features with).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794676

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
