### ISSUE TITLE
GeckoView Nightly(70.0.20190809095611, complete rewrite of PromptDelegate 😎 😭 🔥 🚒 ) manual update required

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4079]

**Comment by Dexterp37** [comment]
Hey folks! Is there an estimate for when this would be available?

**Comment by Amejia481** [comment]
@Dexterp37 If everything go smoothly 🤞  I will put a PR by the end of the day.

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 If everything go smoothly 🤞 I will put a PR by the end of the day.

WOHOOO! That's great news! Thanks 💯
