### ISSUE TITLE
In list.json, SearchDefault/searchOrder is identified with ShortNames instead of identifiers

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#4088]
We normally handle search engines by their identifiers. For example, `google-b-m`:
- https://searchfox.org/mozilla-mobile/rev/a280b0a80ee58ed647a9fb82fa7e8f4d32ec3e7c/android-components/components/browser/search/src/main/assets/searchplugins/google-b-m.xml
- https://github.com/mozilla-mobile/android-components/blob/6909302cb0cbe02019ecc09db473fa16ed58e08c/components/browser/search/src/main/assets/search/list.json#L6

However, in list.json, we declare `searchDefault` and `searchOrder` fields that use the Short Name (e.g. "Google") to identify engines:
https://github.com/mozilla-mobile/android-components/blob/6909302cb0cbe02019ecc09db473fa16ed58e08c/components/browser/search/src/main/assets/search/list.json#L3-L4

https://github.com/mozilla-mobile/android-components/blob/6909302cb0cbe02019ecc09db473fa16ed58e08c/components/browser/search/src/main/assets/search/list.json#L64

afaik, identifiers are unique but ShortNames are not. **I'm concerned that we'll ship multiple engines with the same ShortName, potentially breaking our code.** Also, the inconsistency with how we handle engines is confusing and makes these files harder to understand.

`searchDefault` appears to have been added in #2371.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3424)

**Comment by liuche** [comment]
@mkaply any thoughts on this, or context on why we use the search engine names vs the identifiers?

**Comment by mkaply** [comment]
The reason we use engine names is because the identifiers have different names. We could have google-x, google-y, google-z depending on the platform (mobile, firetv, etc.), but they all have the name "Google". So we need to set the default to be "Google" because we don't know which identifier we will use.

As far as shipping multiple engines go, that shouldn't happen. We should only ever have one Google at a time active.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796456

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
