### ISSUE TITLE
Add Getting Started guide with necessary/recommended configuration

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#4108]
As an application (FFTV), I have overlooked two necessary configuration options:
- Adding an `AndroidLogSink` #3733
- Setting a fetch client in `RustHttpConfig` (no issue – please file one if you don't address here)

This has caused a lot of unnecessary work: I needed to add my own workarounds for debugging a-c code that already had log statements and the extended team was debugging errors when trying to use Rust code to find there's no client init.

I _highly_ recommend we add a getting started guide that would describe these necessary/recommended configuration options.

@pocmo What other necessary/recommended configuration options are there that I may have missed?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3441)

**Comment by mcomella** [comment]
I additionally found https://mozilla.github.io/application-services/docs/applications/consuming-megazord-libraries.html which includes a required `Megazord.init()` for when we're integrating ADM Send Tab push services.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795111

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
