### ISSUE TITLE
ParseException Unparseable date when clicking on datepicker widgets

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#4118]
Related Fenix issue https://github.com/mozilla-mobile/fenix/issues/4685

The problem is that we consider minDateString and maxDateString as having the same format as initialDateString, and that is not always the case.

Also, in cases when the minDateString and maxDateString are empty we set them as current date (keeping us from selecting other dates than the current date), which IMO is contrary to the purpose of not setting min or max (being able to select any date)

@Amejia481 how do you think we should to handle these issues?

**Comment by Amejia481** [comment]
@mcarare  I'm taking a look to what geckoview_example app is doing for those cases:
https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/BasicGeckoViewPrompt.java#597

**Comment by mcarare** [comment]
I think it handles each case depending on what type it gets from Gecko. And the transforms all the date strings, using a different function for each, to make all three date strings match that format.

**Comment by Amejia481** [comment]
Yes, for `minDateString` and `maxDateString` they default to `null` when an `exception` occurs. We could do the same as well.

https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/BasicGeckoViewPrompt.java#611
```java
     final SimpleDateFormat formatter = new SimpleDateFormat(format, Locale.ROOT);
        final Date minDate = parseDate(formatter, prompt.minValue, /* defaultToNow */ false);
        final Date maxDate = parseDate(formatter, prompt.maxValue, /* defaultToNow */ false);
        final Date date = parseDate(formatter, prompt.defaultValue, /* defaultToNow */ true);
        final Calendar cal = formatter.getCalendar();
        cal.setTime(date);
```

https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/BasicGeckoViewPrompt.java#555
```java
    private static Date parseDate(final SimpleDateFormat formatter,
                                  final String value,
                                  final boolean defaultToNow) {
        try {
            if (value != null && !value.isEmpty()) {
                return formatter.parse(value);
            }
        } catch (final ParseException e) {
        }
        return defaultToNow ? new Date() : null;
    } 
```

**Comment by Amejia481** [comment]
@mcarare  we are also going to need this changes on browser-engine-gecko-nightly,browser-engine-gecko-beta and engine-gecko(stable)

**Comment by Amejia481** [comment]
Locally, I stop the crash using on `notifyDatePromptRequest`:


```kotlin
        val minDate = if (minDateString.isNullOrEmpty()) null else {
            try {
                minDateString.toDate(format)
            } catch (e: ParseException) {
                null
            }
        }

        val maxDate = if (maxDateString.isNullOrEmpty()) null else{
            try {
                maxDateString.toDate(format)
            } catch (e: ParseException) {
                null
            }
        } 
```
