### ISSUE TITLE
Implement "frecency" algorithm used on desktop to suggest from history

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#4128]
Had a conversation with @Verdi and we wanted to confirm that we're matching desktop's algorithm for recent suggestions which should be based not only on recency but also on frequency of visit.

**Comment by pocmo** [comment]
Pretty sure we do. But this is handled by AS: Pinging @mhammond @linacambridge @rfk

**Comment by mhammond** [comment]
Yes, frecency is maintained by the AS components and used to sort the result sets.

**Comment by sblatz** [comment]
Thanks @mhammond for verifying!
