### ISSUE TITLE
Generate adaptive bitmaps for PWA task description in recents

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4135]
PWAs with maskable icons should have an adaptive icon on their recents entry.

We can probably achieve the right effect by converting an `AdaptiveIconDrawable` to a bitmap. \
https://stackoverflow.com/questions/44447056/convert-adaptiveicondrawable-to-bitmap-in-android-o-preview

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3464)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796446

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
