### ISSUE TITLE
Run 'on-device' tests in automation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#414]
With **fretboard** we will want to run some unit tests on a device (because it requires some crypto things that Robolectric doesn't mock/provide).

How can we do that? For Focus we use Firebase Device Lab. But that's made for UI tests and in this case we just want to run regular unit tests. Especially because here we do not have an "app under test".

**Comment by pocmo** [comment]
Sent a mail to Travis to ask for a Firebase account/project for android components.

**Comment by pocmo** [comment]
Moving this out of the sprint until it's actionable.

**Comment by pocmo** [comment]
Blocked on: Firebase account/project.

**Comment by fercarcedo** [comment]
Actually recently I modified the PRs for certificate pinning and signatures with mocks so that they now run on device. I think right now all Fretboard tests run on Robolectric

**Comment by pocmo** [comment]
@fercarcedo Awesome! :)

**Comment by pocmo** [comment]
We have a Firebase Device Lab for Android Components now! 🎉
