### ISSUE TITLE
Implement audio ducking for Android < 8.0

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4146]
Follow-up from #3936.

Automatic ducking is only available on Android 8+:
https://developer.android.com/guide/topics/media-apps/audio-focus#automatic-ducking

On lower Android versions we will have to implement this ourselves by listening to `onAudioFocusChange()`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3472)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796363

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
