### ISSUE TITLE
Add enum for SitePermissions types

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4151]
Site permissions are currently defined using property names.
```kt
    val location: Status = NO_DECISION,
    val notification: Status = NO_DECISION,
    val microphone: Status = NO_DECISION,
    val camera: Status = NO_DECISION,
    val bluetooth: Status = NO_DECISION,
    val localStorage: Status = NO_DECISION,
```
This gets difficult to work with quickly when dealing with SitePermissionsRules (which also has named properties) or serializing the permissions to SharedPreferences.

Fenix has the `PhoneFeature` enum to deal with this but it would make more sense to uplift the functionality to Android Components.

We already have the `Permission` sealed class so methods to work with it could be exposed.

**Comment by KaenDagger** [comment]
basically  we just need to make SitePermission enum class ? I could work on this

**Comment by KaenDagger** [comment]
Do we have to make enum class SitePermissionType wrapping Status and Action in it

**Comment by NotWoods** [comment]
Hi @KaenDagger, the goal is to access properties using an enum rather than the current property names.

For example, `sitePermissions.location` could be replaced with `sitePermissions[Enum.LOCATION]`.

The `Permission` sealed class may be sufficient so you may not need to create another enum.

**Comment by calvin-li** [comment]
@KaenDagger 
Are you still working on this?

**Comment by NotWoods** [comment]
@calvin-li Would you like to take this on?

**Comment by calvin-li** [comment]
Yeah

**Comment by calvin-li** [comment]
Not sure if I should be making a new issue for this, but is anyone using Windows and running `detekt` and `ktlint` through git hooks? If so, can you share your script? Can't get it to work for me.
