### ISSUE TITLE
Add a three-state security icon for the BrowserToolbar

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4156]
We're now using the "insecure" icon for the `BrowserToolbar` as the default icon. This seems a bit odd for internal `about` URLs and the empty state when there is no session.

We should consider having three states for the security icon for this:
 - no state - regular globe?
 - secure - lock
 - insecure - broken lock

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3484)

**Comment by NotWoods** [comment]
An alternative "third state" is no icon at all. Firefox Desktop and other browsers just don't show a security icon for about pages and loading pages.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796288

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
