### ISSUE TITLE
FXP-861 ⁃ AutoPushFeature strict mode disk read violations

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/android-components#4166]
On FFTV, when installing the push feature (`PushProcessor.install(pushFeature)`), I am getting 3 StrictModeDiskRead violations:
1.  at mozilla.components.feature.push.AutoPushFeature.<init>(AutoPushFeature.kt:77)
2. at mozilla.components.feature.push.AutoPushFeature.preferences(AutoPushFeature.kt:273)
3. at mozilla.components.feature.push.AutoPushFeature.getPrefToken(AutoPushFeature.kt:86)

[Full logs](https://gist.github.com/dnarcese/6201dee051ed25ca0ca8237b08bd5235)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXP-861)

**Comment by jonalmeida** [comment]
@dnarcese is this happening everytime the app starts up, or only after a fresh install? We aren't creating the file in the android component, it's the rust component that is, we would have to figure out how to lazy init that bit.

**Comment by dnarcese** [comment]
@jonalmeida It's happening everytime the app starts up.

**Comment by jonalmeida** [comment]
This has come up recently with higher strict mode requirements in Fenix.

**Comment by jonalmeida** [comment]
When debugging another StrictMode violation with csadilek, we found a difference in `canonicalPath` which is used by Push and `path`: `canonicalpath` _may_ touch IO but `path` will always return the in-memory constructed path.

If other Rust components are using that, maybe we can too?
