### ISSUE TITLE
Add generic image fetching component

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4175]
We currently have `BrowserIcons` which is dedicated to fetching/caching favicons. It works well for website images since there are usually multiple images that need to be selected from, and there are only a few potential sizes.

We need a more generic component for just fetching a generic image, for use cases such as:
- Fetch a profile image from a user's Firefox Account
- Fetch notification images
   - Large notification images don't have a defined size

We could update `BrowserIcons` to use this new generic image loader as well.

### What to keep from `BrowserIcons`
- Use `Client` from concept-fetch to download images
- Cache images to memory
- Decode different image types (ICO, etc)

#### What to change/remove
- Make defining an output size optional and allow any size
- Use only 1 URL rather than multiple URLs per request.
- Remove adaptive icon processing
- Don't generate a default icon (or change how its generated)

We could look at `BrowserIcons.loadIntoView` and the new Coil library for API ideas.

It might make sense to have this be another class in browser-icons rather than a separate feature since a lot of code will be shared.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3503)

**Comment by pocmo** [comment]
> We could update BrowserIcons to use this new generic image loader as well.

I'd recommend ignoring that for now and trying to implement a greenfield image loader and then later see if we can merge that with `BrowserIcons`. Mostly because this will not restrict you initially. For example `BrowserIcons` has very specific caching requirements while for an image loader you could just rely on the cache of the `concept-fetch` implementation.

**Comment by Amejia481** [comment]
We could take some inspirations from https://github.com/coil-kt/coil/ is has a pretty nice api that uses idiomatic Kotlin

**Comment by Amejia481** [comment]
I wonder why we could not just use one of the existing loading image libraries instead of creating our own?

**Comment by NotWoods** [comment]
We probably want to use the Gecko networking stack. I wonder if we could use concept-fetch with one of the existing libs.

**Comment by mcomella** [comment]
I did some previous research for Fire TV: https://groups.google.com/a/mozilla.com/d/msg/mobile-all/PTbZmm71kio/9rgH0K4tAgAJ

iirc, there were no known major pros/cons for each so we just went with Picasso because it's popular and we wanted to add it quickly.

**Comment by mcarare** [comment]
Is there a conclusion on what the best path for this would be? Another use case would be fetching an encoded image, save it and then sharing it, to avoid crashing (https://github.com/mozilla-mobile/android-components/issues/8450).

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793158

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
