### ISSUE TITLE
Add test dependency for Robolectric shadows

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/android-components#4188]
FFTV needs to write several robolectric shadows for the ADM classes in order for unit tests to run. It would be nice if these could be implemented in a-c and brought in as a test dependency!

**Comment by pocmo** [comment]
In the same component wouldn't work since you wouldn't want to ship them in the app.

> It would be odd to move this into support-test since ADM would need to be a dependency there and creating a new support-test-adm dependency is an overkill I guess?

I've been thinking about prototyping a test framework for AC components in Q4. This sounds like one good use case to cover. @jonalmeida ping me when you consider fixing this. :)
