### ISSUE TITLE
Safe Browsing isn't a TrackingProtectionPolicy (in TrackingProtectionPolicy.select)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#4190]
In `TrackingProtectionPolicy.select`, there are three arguments:
- trackingCategories
- safeBrowsingCategories
- cookiePolicy

afaik, 2 of these help with blocking trackers; the other, **Safe Browsing, does not help with blocking trackers**.

Most users probably never want to disable safe browsing: there's minimal risk to having it enabled (afaik, comparison happens locally) and having it disabled just opens them up to risks. **This creates a problem:** if you want to use the "defaults" to enable and disable tracking protection:
```kotlin
if (hasUserEnabledTrackingProtection) {
    TrackingProtectionPolicy.recommended()
} else {
    TrackingProtectionPolicy.none()
}
```

The user ends up disabling safe browsing when they disable tracking protection: this is unintuitive and probably not desired by the user.

My recommendation: make safe browsing a separate setting from the tracking protection policy.

CC @pocmo this seems like a serious issue to me.

**Comment by pocmo** [comment]
CC @Amejia481

**Comment by Amejia481** [comment]
On it!

**Comment by Amejia481** [comment]
> My recommendation: make safe browsing a separate setting from the tracking protection policy.

Agree with @mcomella comments 👍 
Working on dividing the API, thanks for raising this issue!

**Comment by pocmo** [comment]
@Amejia481 Do you want to move that into the sprint / on the board?

**Comment by Amejia481** [comment]
Yes thanks!
