### ISSUE TITLE
TrackingCategory.RECOMMENDED does not block ads as expected

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#4191]
I tried applying TrackingCategory.RECOMMENDED in FFTV but ads still appeared:
```kotlin
trackingCategories = arrayOf(TrackingCategory.RECOMMENDED)
```

(This is how the default values for `TrackingProtectionPolicy.select` define it)

I switched to adding these categories manually and it worked fine:
```kotlin
trackingCategories = arrayOf(TrackingCategory.AD, TrackingCategory.ANALYTICS, TrackingCategory.SOCIAL)
```

Looking at the code, these values are being added together:
https://github.com/mozilla-mobile/android-components/blob/1c652634c33b476f6ba8d7ada1e5a66e78bd7cba/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt#L179

However, these values look like they're supposed to be bit-packed because other values use bit-shift operators: I think they should be using `and` instead of `+`.

**Comment by mcomella** [comment]
Note: I tested on rottentomatoes.com which shows a banner ad at the top.

CC @pocmo This seems important because tracking protection may be broken in our apps.

**Comment by mcomella** [comment]
I set it up using `and` but that doesn't seem to work either: I'll leave this to the professionals.

**Comment by pocmo** [comment]
CC @Amejia481

**Comment by Amejia481** [comment]
On it!

**Comment by Amejia481** [comment]
> I tried applying TrackingCategory.RECOMMENDED in FFTV but ads still appeared:

@mcomella I believe tracking protection does not block ads, it blocks scripts/cookies/content from trackers depending on which policy you choose. ( **I have to confirm**). For blocking ads we need an Adblocker.

Ads not showing maybe a side effect in some cases, as they may depend on the scripts/cookies/content that we are blocking. 

________________

 If you want to confirm the categories, that you want are getting apply you can test verifying 
the `session.trackersBlocked` property that reports a list of trackers blocked on a site.  When a site finishes loading it should contain trackers that belong to the categories that you applied (**As long as the site has these trackers categories on it**) 

If we take  https://rottentomatoes.com/ as a guinea pig and apply `TrackingProtectionPolicy.recommended()` **(AD,ANALYTICS and SOCIAL)**, when the page finishes loading we are going to get reported that:

`session.trackersBlocked.trackingCategories`
**contains** `TrackingCategory.AD`,`TrackingCategory.ANALYTICS` and `TrackingCategory.ANALYTICS`.


A tracker may contain multiple categories, you can use the snippet below to not show duplicates:

```kotlin
var categoriesBlocked = mutableSetOf<EngineSession.TrackingProtectionPolicy.TrackingCategory>()

session.trackersBlocked.forEach{
    list.addAll(it.trackingCategories.toSet())
}
```

If we use the same site but just applying `AD`:

`TrackingProtectionPolicy.select(arrayOf(TrackingProtectionPolicy.TrackingCategory.AD))`

When the page finishes loading `session.trackersBlocked.trackingCategories` is going to contain
only `TrackingProtectionPolicy.TrackingCategory.AD` (**I apply the snipped above to avoid duplicates**)

The same could be seen if we apply just 
`TrackingProtectionPolicy.select(arrayOf(TrackingProtectionPolicy.TrackingCategory.ANALYTICS))`

When the page finishes loading `session.trackersBlocked.trackingCategories` is going to contain
only `TrackingProtectionPolicy.TrackingCategory.ANALYTICS` (**I apply the snipped above to avoid duplicates**)

**Comment by pocmo** [comment]
@Amejia481 Did you verify that this is still the case for WebView (`browser-engine-system`) too?

**Comment by Amejia481** [comment]
Checking!

**Comment by Amejia481** [comment]
Issue discovered, working on a patch!
Thanks @mcomella for reporting it!

**Comment by Amejia481** [comment]
> trackingCategories = arrayOf(TrackingCategory.AD, TrackingCategory.ANALYTICS, TrackingCategory.SOCIAL)

As you described above, until the fix lands you have to add the categories manually, sorry for that!

**Comment by mcomella** [comment]
> I believe tracking protection does not block ads, it blocks scripts/cookies/content from trackers depending on which policy you choose.

Sorry I was not explicit about SystemWebView (FFTV is still on it) and about ^: a side effect of TP is that it blocks ads and the ad I usually use for testing wasn't blocked. I probably should have been clearer. :)

**Comment by Amejia481** [comment]
I really appreciate you were very diligent double checking after the API refactoring. I'm covering with more tests to avoid similar issues in the future :),  Sorry for the inconvenience, that this may cause you!
