### ISSUE TITLE
Add support for blocking CRYPTOMINING and FINGERPRINTING trackers on SystemEngineView

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4195]
In `GeckoEngineView` we have built-in support for blocking `CRYPTOMINING` and `FINGERPRINTING` trackers that comes from `GeckoView` we should find a way to implement it on `SystemEngineView` too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3516)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796479

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
