### ISSUE TITLE
How can we incorporate telemetry without making it a requirement for consumers?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#42]
If you look at our current set of monolith apps then you will see that telemetry UI probes are scattered all over the code base. A reasonable chunk of the code emitting those telemetry events will be inside our components. How can we make sure that consuming apps can send telemetry events they are interested in without forcing something on all consumers using the app.

Some thoughts:
* Could we unify the telemetry events across all apps? (e.g. one standard event for "Open toolbar menu" that is the same for all apps)
* How can we make sure the app is in control what is send and how?

**Comment by csadilek** [comment]
I've had good results with AspectJ in the past. Hugo I didn't know yet (looks good). The one difficulty with any AOP solution is how to handle conditional logic within a method. We can intercept methods and execute logic before/after/around (if successful or if failed), but how would we inject conditional logic e.g. the telemetry events fired here: https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/activity/MainActivity.java#L159

Of course, we could refactor all these methods to make them easier to intercept.
