### ISSUE TITLE
Audio media doesn't show notification

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4201]
### STR
1. Click an audio-only media link (e.g. https://idiallo.com/blog/18000-dollars-static-web-page)

### Expected
 - A media notification when the audio is playing.

### Actual
 - No notification is shown (on desktop this shows a media icon, so I was expecting to see the same here too).

(Probably a GV bug, but filling here first to verify)

> 1.0.1935 (Build #1 GV: 70.0a1-20190823094538)
> :package:: 10.0.0, 78b1010f4
> :ship:: 0.37.1

**Comment by pocmo** [comment]
Wait. You didn't mention soundcloud. In that case it is a duplicate:
https://bugzilla.mozilla.org/show_bug.cgi?id=1554297

**Comment by pocmo** [comment]
I'll close this one too since I already track the soundcloud bugzilla issue on the media board. :)
