### ISSUE TITLE
Audio-only media autoplays in background; video media does not

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4202]
### STR
1. Play an audio-only media (e.g. https://idiallo.com/blog/18000-dollars-static-web-page)
2. Background the app or switch tabs.
3. Open Youtube and play a video.
2. Background the app or switch tabs.

### Expected
 - At 2 and 4 will both pause or autoplay together.

### Actual
 - At 2, the audio continues to play with no notification (see #4201).
 - At 4, the video pauses.

> 1.0.1935 (Build #1 GV: 70.0a1-20190823094538)
> :package:: 10.0.0, 78b1010f4
> :ship:: 0.37.1

**Comment by pocmo** [comment]
> At 2, the audio continues to play with no notification (see #4201).

This is a GeckoView issue:  https://github.com/mozilla-mobile/android-components/issues/4201 (Tracked on media project board)

> At 4, the video pauses.

This is unfortunately the behavior of  YouTube. It prevents background playback. The same can be observed in other browsers.

JanH wrote an add-on for that a while ago:
https://addons.mozilla.org/en-US/firefox/addon/video-background-play-fix
