### ISSUE TITLE
Add support for safe browsing on SystemEngine

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4206]
GeckoView comes out the box with support for safe browsing. On  SystemEngine we have to provide our own implementation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3532)

**Comment by pocmo** [comment]
WebView supports safe browsing too!

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796478

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
