### ISSUE TITLE
Add support for TrackingProtectionPolicy.CookiePolicy on SystemEngine 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4208]
GeckoView comes out of the box with support for indicating how cookies should behave for a given `TrackingProtectionPolicy`. On SystemEngine we have to provide our own implementation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3536)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796477

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
