### ISSUE TITLE
Add advanced color picker

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4215]
Split from #3480 

Fennec has a nice picker for `<input type="color">` that we have ported over to A-C. However, its limited to only selecting predefined colors. 

An advanced mode for the Fennec color picker was designed but seemingly not implemented, and we should implement that mode too.

![](https://blog.mozilla.org/ux/files/2013/12/mob_cpicker.png)

https://blog.mozilla.org/ux/2013/12/a-new-colour-picker-on-firefox-for-android/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3544)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796343

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
