### ISSUE TITLE
Add content descriptions to color picker

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4216]
Split from #3480

We should also add a `contentDescription` to the colours for screen readers. @thesillypeanut wrote code for this in Firefox Desktop DevTools: https://phabricator.services.mozilla.com/D35980. The patch can be ported to the color picker code in Kotlin.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3546)

**Comment by gurleennsidhuu** [comment]
Hi. Can I work on this issue? :)

**Comment by eliserichards** [comment]
Hi @gurleennsidhuu! Are you an Outreachy applicant? If so, feel free to pick this up 👍

**Comment by sanyud24** [comment]
hey @gurleennsidhuu install Miniconda3 , extract the files in a  folder  named "Miniconda3" then go to 'C:\Users\Gurleen Sidhu\.gradle\glean\ bootstrap-4.5.11 and inside " bootstrap-4.5.11" folder copy  paste the Miniconda3 folder . I spent half a day solving this problem on my laptop , Hope this works for you . Also if you are using windows run the command ".\gradlew clean assembledebug" inside the terminal before running the app.

**Comment by gurleennsidhuu** [comment]
> hey @gurleennsidhuu install Miniconda3 , extract the files in a folder named "Miniconda3" then go to 'C:\Users\Gurleen Sidhu.gradle\glean\ bootstrap-4.5.11 and inside " bootstrap-4.5.11" folder copy paste the Miniconda3 folder . I spent half a day solving this problem on my laptop , Hope this works for you . Also if you are using windows run the command ".\gradlew clean assembledebug" inside the terminal before running the app.

Hi @sanyud24. Thank you so much for your help. Did you follow any tutorial or any document for installation? If yes, can you please share the link? :)

**Comment by sanyud24** [comment]
Yeah sure @gurleennsidhuu  I took some help from here :

https://github.com/mozilla-mobile/fenix/issues/4349

https://github.com/mozilla-mobile/android-components/issues/2344

**Comment by peculiaruc** [comment]
Hi! I am an Outreachy applicant, Can i also work on this ? I haven't another one with Outreachy tag or should I just pick up any issue?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796498

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
