### ISSUE TITLE
Write documentation about how to work with site permissions

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4217]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3547)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795110

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
