### ISSUE TITLE
Document/define how/when to add permissions to the manifest of components

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4227]
Introducing new app permissions (via manifest merge) can be problematic for users with an Android version lower than 6 (App update with new permission needs to be manually approved).

Let's define when or how we add permissions to the manifest of our components and then document it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3557)

**Comment by pocmo** [comment]
Currently I think that:

* Adding a permission to the manifest of a component is warranted if it is absolutely impossible to use the component without that permission.
* If a component can (partially) be used without a permission then we should not add the permission to the manifest and instead ask the app to do that if it needs some specific functionality.
* In any case we should list permissions (No matter whether required or optional) in the documentation of the component. Ideally we describe what this permission is used for and whether it will be added by automatically or whether the app needs to declare it.
* There's a middle ground sometimes where we could list a permission in a component with the [`<uses-permission-sdk23>`](https://developer.android.com/guide/topics/manifest/uses-permission-sdk-23-element) tag. This would only affect devices that support runtime permissions. For everything else we'd delegate to the app.

**Comment by pocmo** [comment]
Since having strict rules for AC is not conclusive as long as other dependencies exist (and I think that's a fair assumption), I think we should tackle the consumer side in a separate issue. It sounds like this is something that could be solved on the app side with tooling for all dependencies: ~"compare app manifest permissions against approved list of permissions". GeckoView uses a similar "apilint" check that makes sure the public API doesn't change without explicit confirmation - we'd want something like that but for permissions?

**Comment by mcomella** [comment]
> Since having strict rules for AC is not conclusive as long as other dependencies exist (and I think that's a fair assumption), I think we should tackle the consumer side in a separate issue.

Good point – in that case, I'm less concerned about a-c's policy here and more concerned about application tooling. We have https://github.com/mozilla-mobile/firefox-tv/issues/2745 filed to track this on FFTV though I'm not sure it'll be prioritized.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795109

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
