### ISSUE TITLE
Stop manually handling configChanges in GeckoView based apps.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4228]
There shouldn't be any need for that anymore. The browser sessions are completely independent from the views now.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3559)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795108

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
