### ISSUE TITLE
feature-sitepermissions: Allow configuration of default handling of media content permissions

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4233]
We already map GeckoView media permissions to content permission requests:

https://github.com/mozilla-mobile/android-components/blob/f46f6f4a331fa7789c6bd50122e88ce7f3144594/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L667-L680

We'd like to control the default behavior via our `SitePermissionsRules`:
https://github.com/mozilla-mobile/android-components/blob/f46f6f4a331fa7789c6bd50122e88ce7f3144594/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsRules.kt

We need to be able to distinguish between:
* Allow video and audio
* Block audio
* Block video and audio

Needed for Fenix feature request:
https://github.com/mozilla-mobile/fenix/issues/255

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3560)

**Comment by colintheshots** [comment]
This is waiting on this GeckoView Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1577596

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796459

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
