### ISSUE TITLE
feature-sitepermissions: SitePermissionsRules: Allow on WiFi

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4234]
Follow-up from #4233

In addition to ALLOW/BLOCKED behavior we would like to have an option for "ALLOW ON WIFI ONLY" for media permissions.

Needed for Fenix feature request:
https://github.com/mozilla-mobile/fenix/issues/255

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3561)

**Comment by colintheshots** [comment]
This is waiting on this GeckoView Bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1577596

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796465

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
