### ISSUE TITLE
Add new SelectionActionDelegate to Clear Text Selection Menu on Back Press

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#4240]
See: https://github.com/mozilla-mobile/fenix/issues/2020

We should clear the text selection on back press before going back in history. It should work to create a `TextSelectionDelegate` that implements `onBackPressed` to deal with this.

**Comment by pocmo** [comment]
GV API improvements: https://bugzilla.mozilla.org/show_bug.cgi?id=1581161

**Comment by liuche** [comment]
@gabrielluong can you also update the sizing here once you have a better idea ty
