### ISSUE TITLE
Import from Fennec session storage (Open tabs)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4241]
To be able to keep "open tabs" when updating Fennec to Fenix we'd need to read from Fennec's Session Storage once.

**Comment by pocmo** [comment]
* https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/SessionParser.java
* https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/GeckoApp.java#210
* https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/home/RecentTabsAdapter.java#168
* https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/gecko/GeckoProfile.java
* https://searchfox.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/gecko/GeckoProfile.java#662-753

**Comment by pocmo** [comment]
First iteration done. Will file a separate issue for integration in Fenix.

**Comment by buttercookie42** [comment]
Am I  reading that commit correctly that this only loads the currently open page and discards all the rest of the data? The full contents of the `entries` array (i.e. that particular tab's session history), as well as `scrolldata` and `formdata` (where present) should basically still be compatible with GeckoView's session saving/restoring APIs, although a little rearranging of the JSON might be required (e.g. I think the `entries` array is now called `history`).
