### ISSUE TITLE
Consider merging CustomTabsServiceStore into BrowserStore

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4286]
Once `feature-customtab` is migrated to `browser-state` (#4257) check whether `CustomTabsServiceStore` and its state can/should be merged into `BrowserStore`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3611)

**Comment by pastasonica** [comment]
Fu

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793194

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
