### ISSUE TITLE
Make WindowFeature session ID aware

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4296]
When clicking on `window=_blank` links, a custom tab doesn't respond to it. This affects Custom Tabs, PWAs, and TWAs.

This may be related to the discussions in #1562 of loading them in the same session.

Example URL: https://www.zdnet.com/article/upcoming-firefox-update-will-decrease-power-usage-on-macos-by-up-to-three-times/

**Comment by jonalmeida** [comment]
UX question: In a Custom Tab/PWA/TWAs, when a site requests to open a link in a new tab, how should we handle that?

From what I can tell, we may have two options here:
 - Load the request in the same window, which might break some pages like login sites that close after you login to go back to the original content. We could try to "go back" in this case but it seems complicated to handle engineering-wise having not looked into the code yet.
 - We switch the user to the main browser window to handle the request there. This might also be awkward since we've lost context for the user.

For reference, Chrome follows the first pattern.

Also see https://github.com/mozilla-mobile/fenix/issues/5085 for STR.

**Comment by jonalmeida** [comment]
Moving conversation to the Fenix issue.

**Comment by jonalmeida** [comment]
We should go with option one from the discussion in the Fenix ticket.

**Comment by NotWoods** [comment]
Unblocked in Fenix now since we got UX feedback. I'll try to take a stab at this later.
