### ISSUE TITLE
How to incorporate L10N?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#43]
Some of the strings that need to be translated may be defined in (UI) components. How do we translate them?

* Should the components project be something that gets translated?
* Should only the app be responsible for translations?

**Comment by Pike** [comment]
We have some existing thought-work on l10n and web-components, which is likely related.

CC @stasm, @zbraniecki

**Comment by zbraniecki** [comment]
It's not currently easy to ship components with their resources in all available locales.

For that reason we currently ask component customers to provide translations for them and request that localizable component expose the localizable elements in the projected content, like this:

```html
<moz-confirm>
  <ok data-l10n-id="confirm-ok-button" />
  <cancel data-l10n-id="confirm-cancel-button" />
</moz-confirm>
```

this way the document can localize the two elements and component only uses them internally

**Comment by pocmo** [comment]
Closing this: We know what we want - we just need to get there. :)

**Comment by pocmo** [comment]
Closing this. We know what we want - we just need to get there. :)
