### ISSUE TITLE
Add ellipses or fade to the end of the EditToolbar hint

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4312]
On smaller screens, you can't see the full hint so I wonder if we should add a hint to the hint that it's a longer string.

Ellipses or fade?

<img width="461" alt="Screen Shot 2019-09-04 at 10 56 11 AM" src="https://user-images.githubusercontent.com/1370580/64268082-77034580-cf05-11e9-851a-1b1559526ca2.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3648)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796293

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
