### ISSUE TITLE
In Standalone PWA window.opener is null after window.open

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#4354]
> Copied from https://bugzilla.mozilla.org/show_bug.cgi?id=1574840 - Needs to be verified in our new PWA implementation.

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

Steps to reproduce:

    - https://piotrswigon.github.io/pwa-demo/standalone/
    - install PWA ("Piotr's Standalone PEA Demo")
    - run "Standalone PWA" from Home Screen
    - click on "Same-origin navigation with window.open(url)"

Actual results:

PWA APP show:
window.opener is null

Expected results:

PWA APP should display:
window.opener is not null
(This is shown, for example, when using PWA and Chrome.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3680)

**Comment by NotWoods** [comment]
Possibly blocked by #4296?

**Comment by paramsinghvc** [comment]
Yeah, facing the same issue here. Post OAuth login, the postMessage can't be sent back to the opener window as it gives `Cannot read property 'postMessage' of null` for `window.opener.postMessage`

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796445

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
