### ISSUE TITLE
Videos played in PWA try to open in another browser (instagram.com)

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#4355]
> Moved here from https://bugzilla.mozilla.org/show_bug.cgi?id=1565394

Originally reported: https://github.com/webcompat/web-bugs/issues/26693

URL: https://www.instagram.com/

Browser / Version: Firefox 67.0
Operating System: Android 9.0
Tested Another Browser: Yes

Problem type: Something else
Description: Videos played in PWA try to open in another browser
Steps to Reproduce:
Steps to reproduce:

    Navigate to https://www.instagram.com/
    Sign in with your account
    Tap button in address bar to add PWA to home screen
    Close Firefox and open the PWA on the home screen
    Find a video in someones feed to play
    Click the play button that appears over the video

Expected result:
Video plays without issue

Actual result:
Video begins playing but also displays the "Open with" menu to open the link in another browser

Issue doesn't happen in Chrome mobile and only happens if you add to home screen. Doesn't reproduce when navigating to Instagram in the browser.

Snorp mentioned

    I think I see the problem
    GeckoViewNavigation[C]: loadURI: uri=javascript:; where=1 flags=0x1000 tp=https://www.instagram.com/?utm_source=pwa_homescreen
    the javascript URI is tripping us up

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3681)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796444

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
