### ISSUE TITLE
Unable to scroll through permission pop up when there are too many

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#4356]
> From https://bugzilla.mozilla.org/show_bug.cgi?id=1568788

> We don't have this problem in A-C / Fenix _yet_ but that is the place where we need to do this better with a better UI to display these.

[Affected versions]:
Firefox 68.0 (20190705221915)
Firefox 68.1a1 (20190723202832)

[Affected platforms]:
Android 8.0.0

[Prerequisites]
Navigate to https://addons.allizom.org
Pick an extension which has over twenty or more permissions required.

[Steps to reproduce]:
1.Install an extension, for example https://addons.allizom.org/en-US/firefox/addon/all-of-the-permissions/
2.Receive the "Add <extension name>?" Pop Up.
3. Attempt to scroll through the pop up to view all permissions.

[Expected results]:
User can scroll up and down in the permission Pop Up in order to view them all.

[Actual results]:
User is unable to scroll through the Pop Up and view all permissions listed.

Note: This is an edge case as in the Release production version of the browser no extensions could be found having a similar number of permissions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3682)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795352

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
