### ISSUE TITLE
Move session removal when activity is finishing

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4361]
This is something we should probably look into getting into a-c: https://github.com/mozilla-mobile/fenix/pull/4985

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3687)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796229

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
