### ISSUE TITLE
TabsAdapterTest.kt: Variable 'holder3' is never used

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#437]
Fromt he build log:

> w: /home/travis/build/mozilla-mobile/android-components/components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabsAdapterTest.kt: (54, 13): Variable 'holder3' is never used

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabsAdapterTest.kt#L47-L74

The verifyNoMoreInteractions call on the last line should be on `holder3` and not `session3`.

**Comment by Pheonix73** [comment]
I have change the it to holder3
https://github.com/Pheonix73/android-components/blob/master/components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/TabsAdapterTest.kt

**Comment by pocmo** [comment]
@Pheonix73 Sorry, I have the wrong instructions in the comment above. The call to verifyNoMoreInteractions() can stay as it is. We just need to remove the line that creates holder3. This one isn't needed.

Can you update your pull request and also add the issue number to the commit message? Something like:

> Issue #437: TabsAdapterTest: Remove unnecessary  holder3.

**Comment by Pheonix73** [comment]
@pocmo Definitely i can do that 
 val holder3 = adapter.createViewHolder(view, 0) is the line that creates the holder3 will remove it.

**Comment by Pheonix73** [comment]
Sorry it kind of mess but i have  created a Pull Request,  Github Sometimes is Confusing
