### ISSUE TITLE
Replace the "IRC" section in the README with the gittler link

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4383]
Gitter link https://gitter.im/mozilla-mobile/android-components
Readme file https://github.com/mozilla-mobile/android-components/blob/master/README.md

**Comment by VMadalin** [comment]
@Amejia481 Maybe we should to close this issue, due the already merge PR of @jonalmeida. Or it's necessary to do any change more?

**Comment by Amejia481** [comment]
Hi @VMadalin,

We still need to update the [Getting Involved ](https://github.com/mozilla-mobile/android-components#getting-involved) section. It still points to "IRC", we have to update the text and link to point to Gitter onces.

![image](https://user-images.githubusercontent.com/773158/64909269-08c63c00-d6d8-11e9-9f1d-a85dcad09702.png)
