### ISSUE TITLE
Navigate to the home screen after a shortcut is added

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4386]
After a shortcut or PWA is added to the home screen, we should navigate to the home screen so the user immediately sees the new icon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3704)

**Comment by pocmo** [comment]
> Fennec currently does not navigate to the home screen/launcher on API 26 and above. 

I think the reason for that was that on 26+ the system shows a dialog and will allow the user to add the icon or add automatically and then switch to the home screen. Back then this was added before we had PWA support in Fennec afaik.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796443

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
