### ISSUE TITLE
Display alt text of image in context menu title

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4394]
Fenix issues:
- mozilla-mobile/fenix#580
- mozilla-mobile/fenix#4684

We should display the alt text of the image and fallback to the full URL. This would better match the behaviour of Fennec and other browsers.

**Comment by kbrosnan** [comment]
`alt` text should only be used if the image is unable to be displayed. `title` text should be used in cases where a tooltip or other similar ui is requested.

Wontfix from https://bugzilla.mozilla.org/show_bug.cgi?id=25537
