### ISSUE TITLE
Media notification: Emit Facts that apps can process

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4396]
We want to collect telemetry about the media notification usage.

Fenix: https://github.com/mozilla-mobile/fenix/issues/5197

**Comment by sblatz** [comment]
@pocmo are we able to pull this into the next sprint? If not, I can pick it up--just let me know 😄

**Comment by pocmo** [comment]
Oh, yes, absolutely. That was supposed to go into the current sprint but we didn't get through all the issues in triage.
