### ISSUE TITLE
Downloading a file that already exists overwrites any exisiting one without prompt

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4405]
### STR
1. Download a file (e.g. r-b APK).
3. Observe the file downloaded and the file name.
2. Attempt to download it again.
3. Observe the file downloaded and the file name.

### Expected
- The second file downloaded will not overwrite the previous file without asking first.
**OR**
- The second file will be downloaded with the filename format: `[filename]-1.[extension]` (e.g. `arm-1.apk`)

### Actual
- The file with the same name is overwritten silently.

This wasn't the case with the Android DownloadManager, so I suspect that this is something that came about when the Gecko one?

(I haven't tested this on Fenix yet.)

**Comment by sblatz** [comment]
This is fixed by https://github.com/mozilla-mobile/android-components/pull/4759 😄
