### ISSUE TITLE
Incorrect PWA added to home screen

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#4418]
On today’s build I first added Twitter to my home screen. Which works and starts the Twitter lite site. Then I went to Starbucks.ca and also added it to my home screen. 

What appeared on my home screen were two icons named Twitter. And they both start Twitter Lite. 

I know Starbucks.com is A PWA but I am not sure if the same is true for Starbucks.ca.

**Comment by NotWoods** [comment]
It seems that the web app manifest isn't cleared when we navigate to a new site. We need to define some behaviour for when the clear out the web app manifest attached to the session.

Is it the best choice to have GeckoView push the Web App Manifest to us? It might be worthwhile to only load the manifest when explicitly requested in A-C like Chrome.

**Comment by NotWoods** [comment]
@pocmo What do you think about clearing out the manifest when `onLocationChanged` is called with a URL outside the manifest scope?

**Comment by pocmo** [comment]
> @pocmo What do you think about clearing out the manifest when onLocationChanged is called with a URL outside the manifest scope?

Yes, that makes sense to me. Technically we could clear it on *any* location change since Gecko will pass it back to us anyways after load. However if that causes issues then we can also keep it until we leave the scope (we will still get a "new" one though).
