### ISSUE TITLE
Media Notification Displays "No Title" on Lock Screen

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#4431]
I can't take a screenshot because it displays when my device is locked but I can reproduce on Pixel 3, Android Q, Fenix master (9/16)
  
## Steps to reproduce
* Load Fenix and play a video from nfl.com. 
* A speaker icon shows in the device status bar indicating media is playing
* Press the device power button to show the notification screen

### Expected behavior
* Something should show which indicates there is active media playing. Fennec, for example, displays a Firefox icon

### Actual behavior
* "No title" shows below the active device time, but there is no Fenix icon.

### Device information

* Android device: Pixel 3 running Android 10
* Fenix version: 1.4.0 

See: https://github.com/mozilla-mobile/fenix/issues/5177

**Comment by mozillamarcia** [comment]
The other aspect of this is sometimes I cannot get rid of the "no title" verbiage even when the video is stopped and the Fenix app is killed. Last time this happened I had to restart my device to get rid of it - Pixel 3.

**Comment by gaby2300** [comment]
I cannot reproduce in my Sony Xperia Z3C with Android 6.0.1. 
I see an "N" square icon and "NFL Football High"... to the right. Below that: "https://www.nfl.com vide... and below the Pause icon.
I can't take a screenshot because it displays when my device is locked only.

**Comment by pocmo** [comment]
I can't test on nfl.com (SPOILERS 😂); but I can reproduce on an other site (also using Pixel 3, Android 10). I'll pick that up in the next sprint.

**Comment by pocmo** [comment]
Related Fenix issue: https://github.com/mozilla-mobile/fenix/issues/5294

**Comment by pocmo** [comment]
Possibly related: https://github.com/mozilla-mobile/fenix/issues/5290
