### ISSUE TITLE
MediaNotificationTitle displays "Unknown" on Samsung devices

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#4433]
see: https://github.com/mozilla-mobile/fenix/issues/5294

## Steps to reproduce
* Load Fenix and play a video from twitter.com
* A speaker icon shows in the device status bar indicating media is playing
* Press the device power button to show the notification screen

### Expected behavior
* The lock screen should show the title / description of the media

### Actual behavior
Lock screen displays "Unknown / Unknown"

### Device information

* Android device: Samsung Galaxy S9
* Fenix version: 2.0

**Comment by pocmo** [comment]
I assume that is the same issue as https://github.com/mozilla-mobile/android-components/issues/4431. Please reopen if you disagree. :)
