### ISSUE TITLE
Expose slow script observer

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4437]
GeckoView added a new function `onSlowScript` to `ContentDelegate` which allows handling of slow and hung scripts. We have to expose that through AC

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3747)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796488

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
