### ISSUE TITLE
[fxa] Implement `getSessionToken` in FxA component and use it in WebChannels

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/android-components#4443]
Some apps can now fetch a session token as part of the login process (using the `https://identity.mozilla.com/tokens/session` scope.
We should start using this functionality in WebChannels: https://github.com/mozilla-mobile/android-components/commit/29b118c6c7872a7161263f779c58ab9006e9c054#diff-55be12d531e8f5049e8ef0974937d004R278

Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1581576#c5

Ref: https://github.com/mozilla/application-services/commit/d6d5764e412682463dc0328c33a1ca5446ee874f

cc @grigoryk

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3753)

**Comment by csadilek** [comment]
This happened as part of https://github.com/mozilla-mobile/android-components/issues/4450.

**Comment by vladikoff** [comment]
Nice!
