### ISSUE TITLE
Custom app share icon is huge in Feedly custom tab

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#4457]
### Steps to reproduce
Have Fenix as default browser. Open links in Feedly using in-app Fenix tab. When you opened the link. In Feedly settings make sure "Preferred Browser" is set to "Built-in" which causes it to use custom tabs. Then simply tap on an article, then tap on the article title which will open it in the custom tab.

### Expected behavior
It should have a normal-looking Share button outside the 3-dot menu

### Actual behavior
When using Feedly there is a super-weird share button left to 3-dot menu button and it works. (Ignore image on right)

![image](https://user-images.githubusercontent.com/46045997/64907372-87d06a00-d702-11e9-85ee-6d4c8b5e48f2.png)

### Device information
* Android device: Samsung, Android 7.0
* Fenix version: 1.4.1

Modified from: https://github.com/mozilla-mobile/fenix/issues/5330

**Comment by NotWoods** [comment]
The large share button is probably a custom action button set by Feedly. We may not parse it properly. See `CustomTabActionButtonConfig`.

**Comment by ekager** [comment]
A user just reported in https://github.com/mozilla-mobile/fenix/issues/7948 that this share icon does not work.

**Comment by NotWoods** [comment]
Couldn't reproduce mozilla-mobile/fenix#7948
