### ISSUE TITLE
Remove `AbsentOrWrongFileLicense` detekt rule from baseline.

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/android-components#4460]
Remove all rule entries in `detekt-baseline.xml` and add/fix license header.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3766)

**Comment by csadilek** [comment]
I think we can close this. The remaining two cases are on code we "vendored in" with a different, but compatible license.
