### ISSUE TITLE
Fennec migration: Decide how to deal with about:reader URLs.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4466]
We need to decide how we want to deal with `about:reader` URLs.

* What do we want to do if a tab with an `about:reader` URL is open? Just point it to the original page? Or try to transform it into a "new" reader mode Session?

* What do we want to do with `about:reader` URLs in bookmarks? Those showed up as "offline available" content in Fennec.

**Comment by grigoryk** [comment]
Or we can actually deal with `about:reader` URLs, treating them as reader-mode? @csadilek mentioned this was blocked on some GV things though.

**Comment by pocmo** [comment]
Yeah, I skipped that option since we can't do that at the moment.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Nightly migration build 8 with Nexus 6P (Android 8.1.0) - ARM, Samsung Galaxy Note 9 (Android 9) - ARM64.
The pages in reader mode are migrated in normal view.
