### ISSUE TITLE
Uplift string extensions from Fenix

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4472]
We have some string extension methods in Fenix we'd like to move into the Android Components repo.

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/ext/String.kt

- `String.tryGetHostFromUrl` (can move as is)
- `String.urlToTrimmedHost` (needs new parameter for publicSuffixList)

**Comment by daphliu** [comment]
I would like to work on this!

**Comment by pocmo** [comment]
@daphliu Sure! :) Do you need any help? :)
