### ISSUE TITLE
MediaState notification on "background" tab  

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#4483]
Per this [fenix issue](https://github.com/mozilla-mobile/fenix/issues/5428), when a user opens a "link in a new tab" I believe we are getting a MediaState notification that updates based on that tab even though the user has never opened it. It's also possible this website just has some incompatibilities with our current implementation?

**Comment by pocmo** [comment]
This seems to only affect the tabs tray and not the notification (none shown).

For the background tab I see us transitioning to PLAY and then PAUSE:

```
                         I  Transitioning from Paused(session=Session(207537e6-ad2e-45ac-9eb7-d7eac60d45af, https://www.ableton.com/), media=[M
                            edia(state=PAUSED,playbackState=PAUSE)]) to Playing(session=Session(7c8efcd9-7582-4629-9351-be752dd97583, https://w
                            ww.ableton.com/en/blog/personal-take-erin-barra-sonic-prosody-and-songwriting/), media=[Media(state=PLAYING,playbac
                            kState=PLAYING)])
                         I  Transitioning from Playing(session=Session(7c8efcd9-7582-4629-9351-be752dd97583, https://www.ableton.com/en/blog/pe
                            rsonal-take-erin-barra-sonic-prosody-and-songwriting/), media=[Media(state=PAUSED,playbackState=PAUSE)]) to Paused(
                            session=Session(7c8efcd9-7582-4629-9351-be752dd97583, https://www.ableton.com/en/blog/personal-take-erin-barra-soni
                            c-prosody-and-songwriting/), media=[Media(state=PAUSED,playbackState=PAUSE)])
```

**Comment by pocmo** [comment]
The difference is coming from the fact that in the feature we see that there's only a 1 second media element and that it's not worth showing a notification for it. However the MediaStateMachine is nevertheless in the "playing" state and that's what the tabs tray displays. I wonder if we should completely avoid transitioning to the playing state in those situations.

**Comment by pocmo** [comment]
>  I wonder if we should completely avoid transitioning to the playing state in those situations.

Implemented that and it works great. Makes totally sense to do that inside `MediaStateMachine`.
