### ISSUE TITLE
Allow `Fretboard#setOverrideNow` to be called from the main thread

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/android-components#4488]
We perform some of our early app setup based on experiments, and the non-blocking nature of `Fretboard#setOverride` is preventing QA from testing these features.  

Since overrides are not meant to be used in release anyway, would it be possible to use source sets to make `setOverrideNow` a no-op on release (potentially with a log to telemetry), but usable from the main thread on debug?

**Comment by pocmo** [comment]
I'm not fully sure I understand the request. But I also think that some of the docs of those methods are misleading. So maybe there's a misunderstanding here.

* `setOverride` applies the override immediately. The next read will received the override value.
* Overrides are persisted to disk (and therefore active until explicitly cleared). And this write is the part that is asynchronously. However the value in memory is updated synchronously and so the asynchronous write does not affect the read. (Baked by SharedPreferences)
* The only reason `setOverrideNow` exists is that we had overrides that had to be written immediately before the process was getting killed - causing the asynchronous write to disk to not complete. If you do not kill the process then most likely you will not need `setOverrideNow` (Compare with SharedPreferences apply/commit).
* `setOverrideNow` is also used in release versions for manual experiment opt-in. So I think we can't change that behavior.

**Comment by Baron-Severin** [comment]
My mistake!  I misinterpreted the kdoc, thank you for clarifying the behavior for me.  I've taken a second look at our implementation and it seems like the problem is indeed on our side.

Sorry for taking your time unnecessarily, closing now.
