### ISSUE TITLE
Fretboard: Set default values for source and storage

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#449]
Now that we collapsed the gradle modules we could set default values for `source` and `storage` so that a user with defaults could just use:

```Kotlin
val fretboard = Fretboard()
```

**Comment by pocmo** [comment]
@fercarcedo What do you think?

**Comment by fercarcedo** [comment]
I think it looks good, and it's easy to create the FlatFileExperimentStorage with a default filename, but KintoExperimentSource still requires the URL, bucket name and collection name, so I'm not sure right now how de could do that.

Do you have any ideas?

**Comment by pocmo** [comment]
Oh, yeah, I didn't think about the constructors of those. In this case lets let the app deal with that. :)
