### ISSUE TITLE
Add engine API for Add-ons management

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#4500]
This may need to be broken down more later, but on a high level we need to wrap the Add-on management API (to be) provided by GeckoView to:

- download and install Add-ons
- query installed and available Add-ons
- enable/disable Add-ons
- update add-on

**Comment by csadilek** [comment]
Blocked on: https://bugzilla.mozilla.org/show_bug.cgi?id=1582185

**Comment by csadilek** [comment]
OK, we have everything now that was covered by this ticket. Closing.

**Comment by pocmo** [comment]
Looking forward to getting the Reference Browser update with that. :)
