### ISSUE TITLE
Investigate if we need helpers for executing code after a time interval when using WorkManager

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4502]
There are a couple of places where we want to execute code after a certain time interval (e.g. after every 24 hours). 

We store the timestamp for the first run in a pref, then every time that code block is executed, we check if it has passed our interval. If it has, then it executes the block.

These solutions can't be fulfilled by WorkManager since we want the code to be executed _within_ the application context (which doesn't seem like something WM can accomplish).

This exists in a few places so maybe we can generalize it. We have this in:
 - Fenix's FxaAccountManager; sync every 4 hours.
 - FxaSupportFeature: checking fxa if push is working.
 - AutoPushFeature: checking push subscriptions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3803)

**Comment by pocmo** [comment]
> to be executed within the application context 

What does this mean exactly? Only while the app is running?

Is `Timer`/`TimerTask` an option?

**Comment by jonalmeida** [comment]
> What does this mean exactly? Only while the app is running?

In a WorkManager, you can't call things that requires `Application#onCreate` to have executed first. So some things like `context.components.backgroundServices.push.doSomething()` would fail.

I'll have to look into TimerTask, I mostly trying to take out the same code where we try to do things on startup but not if it hasn't passed 24 hours since the last success.

**Comment by pocmo** [comment]
> In a WorkManager, you can't call things that requires Application#onCreate to have executed first. 

What, really? This is news to me. Afaik that's how we have been using WorkManager in various situations. Is there a specific scenario where this is not true?

**Comment by jonalmeida** [comment]
I had posted this in a thread a last week because it took me a bit to learn the limitations of Workmanager: https://app.slack.com/client/T027LFU12/threads/thread/CA4JKKLSG-1568383937.115600

> The biggest learnings are:
> 1. WorkManager tasks can outlive the application lifecycle, so if you try to invoke something in the app from the WorkManager, it will fail. Make whatever it is you want contained within worker (or maybe fire an intent for a service to execute the application-specific things you need).
> 2. The TestDriver is not dependable for actually doing what it says it will do :smile: . Running a specific test individually passes, but a test group fails.
> 3. Running things in a CoroutineWorker is easier to test because you can extend your worker and give it a synchronous executor to make sure everything completes. You can test the constraints of the request separately with simple assertions on the built request.Maybe these are less of an issue with the new testing helpers in the 2.1.0 updates, but I'm quite skeptical after this.
>
> Maybe these are less of an issue with the new testing helpers in the 2.1.0 updates, but I'm quite skeptical after this.

In my specific case, I wanted to call `PushProcessor.requireInstance.verifyActiveSubscriptions()` in a worker, but the task result would always fail if the app was no longer in memory when it was executed.

I assumed that it would start the application and run through the `Application#onCreate` which sets the `PushProcessor` instance to the AutoPushFeature, but it never did this in the cold-boot case.

**Comment by pocmo** [comment]
I still wonder if that is somehow a configuration issue on our side and we are shooting ourselves in the foot. Especially since this behavior is documented nowhere...?

The `Worker` gets a `Context` object. What other `Context` than the `Application` object can that be? Can we log that? Can we also look at which process we are in? We only do some setup in the main process.

**Comment by jonalmeida** [comment]
That's a fair point. I guess I can investigate what process we're in.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795122

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
