### ISSUE TITLE
Make fact "items" public 

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#4517]
Currently each "Fact" emitting feature has a `private object featureItems { }` (as seen in [MediaFacts.kt](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/media/src/main/java/mozilla/components/feature/media/facts/MediaFacts.kt#L12-L15)). 

Because they are private, we can't access them in Fenix, which causes us to [**hardcode the string values**](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/metrics/Metrics.kt#L300-L316). 

Can we make these items public so we don't have to do this and can access the enum directly or are there concerns with doing this?

**Comment by pocmo** [comment]
We did do this. Closing... :)
