### ISSUE TITLE
Custom tab "slide in" animation issue

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#4520]
![buggy url custom tab](https://user-images.githubusercontent.com/4400286/65536334-12118e80-deb8-11e9-9924-5aff6d0acb5a.gif)

Might be due to recent changes made by @Amejia481 🤔

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3823)

**Comment by Amejia481** [comment]
Yes, it looks like it. I will investigate further.

**Comment by gabrielluong** [comment]
This seems to be still an issue with the text sliding using the above gif as STR.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796216

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
