### ISSUE TITLE
Store: Test helper for waiting for all dispatched actions to complete

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4529]
See discussion:
https://github.com/mozilla-mobile/android-components/pull/4506#discussion_r327751819

When tests call code that dispatches actions on `BrowserStore` then there's no way to wait for those actions to be completed.

In some tests I dispatched a "dummy" action to be able to wait for all previous actions to be completed:

```
store.dispatch(SystemAction.LowMemoryAction).joinBlocking()
```

**Comment by csadilek** [comment]
I just had a case where this would have been nice-to-have even outside of tests. Basically, a way to make sure all currently pending actions and processed before continuing. I will move to triage to chat / try something next week.
