### ISSUE TITLE
Import more tab data from Fennec

### ISSUE THREAD

**Issue by buttercookie42** [mozilla-mobile/android-components#4532]
Am I reading [that commit](https://github.com/mozilla-mobile/android-components/commit/186fa2396addf884f95c8d0467acc03a244e20c4) correctly that this only loads the currently open page and discards all the rest of the data? The full contents of the `entries` array (i.e. that particular tab's session history), as well as `scrolldata` and `formdata` (where present) should basically still be compatible with GeckoView's session saving/restoring APIs, although a little rearranging of the JSON might be required (e.g. I think the `entries` array is now called `history`). The `desktopMode` flag would be nice to preserve, too...

_Originally posted by @buttercookie42 in https://github.com/mozilla-mobile/android-components/issues/4241#issuecomment-534461440_

**Comment by pocmo** [comment]
Yes, that is correct. So far we are only looking at the currently opened page. It's up for debate whether more than that is in scope.

But good that you are here. I was hoping that you could review some of that session store migration work. :)

**Comment by ebalazs-sv** [comment]
Moving this to Done as it was decided to not import more tab data than the currently opened page, as confirmed by pocmo. Thanks!
