### ISSUE TITLE
On smaller devices, Toolbar TP icon can look cut off

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#4537]
Seen while testing on a Nexus 5 API 21 emulator but don't have a physical device to verify this on :/
<img width="414" alt="Screen Shot 2019-09-25 at 8 03 52 PM" src="https://user-images.githubusercontent.com/25442310/65655057-ab7f9400-dfcf-11e9-844b-c67e0c4ef77b.png">

CC @Amejia481

**Comment by Amejia481** [comment]
On it 👍

**Comment by pocmo** [comment]
@Amejia481 Let's sync up. Before you end up quick fixing a lot of things, maybe we should just switch to the new version to fix those issues? Otherwise you spend a lot of time on code that may get replaced.

**Comment by Amejia481** [comment]
👍

**Comment by Scripterr** [comment]
Another example
![Screenshot_20190926-171009~3](https://user-images.githubusercontent.com/42364681/65686522-58035980-e054-11e9-81d3-bc168dc522f8.png)

**Comment by Amejia481** [comment]
Is this the same version  of Android?

**Comment by Scripterr** [comment]
No it's not same device, mine is android oreo.

**Comment by Amejia481** [comment]
Could you please give us more information about your device? (brand/model)

**Comment by Scripterr** [comment]
Sure.
Brand- Lenovo K8 note 4 GB varient
This might also be helpful
![Screenshot_20190926-184116](https://user-images.githubusercontent.com/42364681/65690980-9eaa8100-e05f-11e9-863d-373a1bce6b97.png)

**Comment by Amejia481** [comment]
Thanks you so much :)

**Comment by AndiAJ** [comment]
Hi guys, I've bumped in this on **Nightly Build #13110606 from 7/11** while using a **LG Nexus 4 (Android 5.1.1)**  :blush:
► Video
![20191107_164431](https://user-images.githubusercontent.com/51314259/68399167-a55c0600-017e-11ea-8c38-e1e112de1d76.gif)

**Comment by Amejia481** [comment]
Does the issue still persist? I'm a bit confused. https://github.com/mozilla-mobile/android-components/commit/4be7cd4957785e4574558fcf401775435cb9ba2e should fixed it.

**Comment by pocmo** [comment]
Yes, that looks like the patch hasn't made it into that build yet. Let's wait for the next Nightly build.

**Comment by AndiAJ** [comment]
I left the above comment just as another example. 
Sorry if any confusion created.  :blush:
