### ISSUE TITLE
Use JEXL/CEL in fretboard to evaluate experiments?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#454]
In Fretboard/Switchboard we sometimes had the problem that we couldn't have more complex configurations because we can only match against certain properties (with Regex) and not write more complex rules involving `AND`, `OR`, `>`, `<`. Something like "Users with version 58 and higher" is already ridiculously complex when trying to express this as a regular expression that we match against the actual version number.

The desktop version of Firefox (SHIELD, Normandy) uses JEXL (Javascript Expression Language) for that purpose.

* https://github.com/TechnologyAdvice/Jexl
* Mozilla JS JEXL: https://github.com/mozilla/mozjexl
* Mozilla Python JEXL: https://github.com/mozilla/pyjexl
* ~~Apache has something: (Is this actually the same?) https://commons.apache.org/proper/commons-jexl/download_jexl.cgi~~ (This is another JEXL)

**Comment by pocmo** [comment]
https://remote-settings.readthedocs.io/en/latest/target-filters.html

**Comment by fercarcedo** [comment]
I can take a look at this and modify the evaluator

**Comment by pocmo** [comment]
@fercarcedo I think this is a rather big project. As far as I can see there's no implementation of JEXL in Java/Kotlin and this alone is a project in itself. Let's focus on the other fretboard tasks first. :)

**Comment by pocmo** [comment]
Another option may be "Common Expression Language" (CEL):
* https://github.com/google/cel-spec
* https://github.com/google/cel-cpp

**Comment by mostlygeek** [comment]
I also opened this on our side: https://github.com/mozilla/product-delivery/issues/6 to track feedback / comments.

**Comment by pocmo** [comment]
I have been using some time here and there to write a Kotlin version of mozjexl. It's quite far already. I may hack a bit on that during my PTO next week because it's fun. I'll move this issue into the next sprint to share progress.
