### ISSUE TITLE
Add UI for addon management

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#4546]
This is a placeholder for now until we know exactly what's needed for Fenix. Once we do, we can also move this issue over.

We will need a user interface, possibly a simple native screen to start with, to install/uninstall (enable/disable) supported Add-ons. We could prototype this as part of a new feature-addon module. maybe?

Example (preliminary mock-up):

<img width="367" alt="Screen Shot 2019-10-18 at 3 32 25 PM" src="https://user-images.githubusercontent.com/472523/67122800-a1127d80-f1bc-11e9-88d4-c2bbb4bec83f.png">

<img width="315" alt="Screen Shot 2019-10-18 at 3 32 50 PM" src="https://user-images.githubusercontent.com/472523/67122808-a5d73180-f1bc-11e9-943b-8d508ec459a7.png">

**Comment by Amejia481** [comment]
We already covered all features on this ticket, will address any polish or future improvements on separate issues.
