### ISSUE TITLE
Create service to manage notifications and notify engine

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4548]
We may need a service to ensure the engine is still alive and interactions on the notification can be executed.

If `requireInteraction` is true, we need to keep the notification around until a user interaction.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3849)

**Comment by jonalmeida** [comment]
- Do we need to keep the engine alive? 
- If the engine is gc'd, can we still fire `click()`/`dismiss()` after restarting the engine?

**Comment by jonalmeida** [comment]
I don't think we need this any more, but maybe @rocketsroger thinks otherwise?

**Comment by rocketsroger** [comment]
> I don't think we need this any more, but maybe @rocketsroger thinks otherwise?

I don't think we need a service as well.  As long as we can handle the notification(s) in a way that's consistent.  Do we go with restart the engine then handle the pending intent?

**Comment by jonalmeida** [comment]
Will leave this open to test. :)

**Comment by jonalmeida** [comment]
Some instructions on how to kill GV child process (taken from fenix#1577) that can be used to kill the main process:

> 
> Simulate device killing content process:
> - connect to device `adb shell`
> - `$ run-as org.mozilla.fenix.debug`
> - Get `:tab` process id: `$ ps -A | grep org.mozilla.fenix.debug:tab`
> - Kill process `$ kill -9 <PROCESS ID>`

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796448

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
