### ISSUE TITLE
Create abstraction for WebNotificationDelegate for the Engine

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4549]
To fit our engine abstraction model, we need to implement an abstraction for WebNotifications where we can implement the `GeckoWebNotificationDelegate`.

**Comment by rocketsroger** [comment]
Confirmed abstraction is needed for `WebNotificationDelegate`.  Will fix at the same time as #2295

**Comment by jonalmeida** [comment]
> Confirmed abstraction is needed for `WebNotificationDelegate`. Will fix at the same time as #2295

Could you help me understand why we need to expose an abstraction on the Engine? Couldn't we just add `runtime.registerWebNotificationDelegate` in the `init` block of the GeckoEngine?

Having the abstraction on the engine would mean that apps can register their own delegate as well, is that intended?
