### ISSUE TITLE
Adding new types of SyncEngines

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4557]
Follow-up to #4480.
Before we add new types of SyncEngines, think through the implications for the `declined` stuff in the a-s SyncManager. We need to make sure that user choice is respected, and that if engine is already present in the declined/accepted lists, we're behaving in a sensible way.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3857)

**Comment by jonalmeida** [comment]
Hmm.. I don't see anything actionable to do here since this issue was first reported, so I'm going to close it because it seems more like a "spike" ticket.
