### ISSUE TITLE
Show media title on bluetooth devices (e.g. cars)

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4558]
We set the title on the `MediaSession` and this will make it show up on the lock screen. However this does not seem to affect playback devices connected via Bluetooth.

From my car while playing media in RB:

![IMG_20190926_200520](https://user-images.githubusercontent.com/89638/65760052-8f3d3d80-e11c-11e9-9599-49b17d2a9513.jpg)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3858)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796368

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
