### ISSUE TITLE
Fretboard: Allow filtering by release channel

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#456]
In Focus we would like to filter by release channel (e.g. have an experiment that only runs in Beta). The release channel is obviously something that is very app specific. So we would need some way to provide this data to `Fretboard`. There may be other data that we want to provide to the library in the future (or maybe even override some of the existing fields). That makes we wonder if we should pull that behavior out into its own class that `ExperimentEvaluator` uses to get the values. Basically turn the `RegionProvider` we already have into something that can provide more than just the region.

**Comment by pocmo** [comment]
@fercarcedo Is this something you could pick up? :)

**Comment by fercarcedo** [comment]
I can look at this, yes :)

**Comment by fercarcedo** [comment]
My draft looks something like this:

Rename `RegionProvider` to `ValuesProvider` (or something like that) and add a method `getValue(name: String): String?`, and with this we could return any value for any property.

But on the `Matcher` class all values are hardcoded, so if we need to introduce a new matcher (such as for example, now with the release channel), we would have to add a field to that class and update the `JSONExperimentParser`. What I thought about doing was adding another field to `Matcher` with custom matchers as a simple `Map<String,String>`, to provide flexibility

**Comment by pocmo** [comment]
> getValue(name: String): String?

@fercarcedo I think that's may be a bit too generic. At the end of the day we need to match against fields that really exist in the server side configuration anyways. I like `ValuesProvider`. Let's add separate, clearly named methods to it for the values we want to allow overriding. That's at least region and release channel for now. We could add all values we read (+ default implementations) and make ValuesProvider an open class so that an app can just override the things it wants to change. What do you think?

**Comment by fercarcedo** [comment]
It sounds good, yes!
