### ISSUE TITLE
Add a flexible Category Menu Item 

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#4560]
We should be able to menu item for a menu category. The menu item should be flexible, i.e. has a text size, style and colour, text alignment, etc

Fenix related issue:https://github.com/mozilla-mobile/fenix/issues/1487

**Comment by mcarare** [comment]
@pocmo Any thoughts on this? Should we also add optional icon and listener? TY!

**Comment by pocmo** [comment]
@mcarare `SimpleBrowserMenuItem` may already be close to what you need? 🤔

**Comment by mcarare** [comment]
I already tried to use it, but having problems with style (it should be bold) and with the alignment (due to padding). I did not want to modify `SimpleBrowserMenuItem` because it is already used in many menus in Fenix.

**Comment by pocmo** [comment]
@mcarare And you think it is too risky to add this to the existing one? 🤔

**Comment by mcarare** [comment]
@pocmo. Not risky, but I wanted it to have by default the style needed for a `category` item and not modify the existing usages of `SimpleBrowserMenuItem`. I can go with either solution, whatever you think it's best.

**Comment by pocmo** [comment]
@mcarare Ah, understood. Since they are also not clickable etc. I think it makes sense to have a separate item, yeah. :)
