### ISSUE TITLE
Fennec migration: Delay/synchronize sync with history/bookmark import

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4567]

**Comment by grigoryk** [comment]
Landed in https://github.com/mozilla-mobile/android-components/pull/4873

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fenix Nightly 191125 GV 71 with OnePlus 5T (Android 9).
The 'FennecFxaMigration: Migrating Fennec account' marker is the last one in the logs, line 1138.
[FennecFxaMigration.txt](https://github.com/mozilla-mobile/android-components/files/3887184/FennecFxaMigration.txt)
I will mark this as Done.
