### ISSUE TITLE
MediaState with PWA causes loading to freeze

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4570]
Possibly related to #4505.

@sblatz: I'm sometimes able to get the app in a very weird/broken state where no websites will load or the app will crash. I have an inkling this is related to pausing the app while it's loading media? I can only reproduce it on Twitter where there was media playing / on the page.
![](https://user-images.githubusercontent.com/4400286/65343741-9d261800-db8a-11e9-9849-920f8c01e814.gif)

I'm also getting a crash sometimes by doing the steps in this gif (can't reproduce on master):
![](https://user-images.githubusercontent.com/4400286/65343913-16256f80-db8b-11e9-8d18-b9058098a4d2.gif)

**Comment by pocmo** [comment]
> I'm also getting a crash sometimes

@sblatz Y u no stacktrace?? :)
