### ISSUE TITLE
Expose GeckoSession.purgeHistory

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4571]
Added `GeckoSession.purgeHistory` allowing apps to clear a session’s history. [(bug 1583265)](https://bugzilla.mozilla.org/show_bug.cgi?id=1583265)

**Comment by pocmo** [comment]
Is this needed for anything at the moment?

**Comment by Amejia481** [comment]
I'm not sure just saw the API added and added a ticket for it 😄

**Comment by pocmo** [comment]
Then I'll just kick it off the triage list unless someone needs it :P

**Comment by mcarare** [comment]
@pocmo, @Amejia481  This might be needed for https://github.com/mozilla-mobile/fenix/issues/13522.
If I clear the tab history individually using `ontentAction.UpdateHistoryStateAction` (is there another way? ) the history list is empty, but as soon as I reload the page, the history of the tab ahows up again.

**Comment by bifleming** [comment]
@kbrosnan can you weigh in on priority for this? It's been in our Hershey sprints as blocked, but came off of the a/c radar as not priority.

**Comment by kbrosnan** [comment]
This is fairly basic JS behavior we should be removing this data when history is cleared. I could also see this breaking extension behavior.

**Comment by Mugurell** [comment]
@jonalmeida We need this for https://github.com/mozilla-mobile/fenix/issues/13522
I see you removed this from the list of priorities. Can this be added back?

**Comment by jonalmeida** [comment]
We removed it from the bug list since it was new functionality and not a crash/bug. It can still go through triage and figure out a priority for it then since I don't see one here.
