### ISSUE TITLE
photon_colors are unexpectedly camel case

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#458]
Colors resources are traditional underscore_notation in Android. However, our photon colors are camelCase, e.g. `photonGrey90`.

Should we fix it to conform to convention?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3889)

**Comment by mcomella** [comment]
fwiw, I've added partially transparent colors like `photonGrey90_a60p` (for grey 90 @ 60% opacity) because `photonGrey90A60p` is less readable but `photon_grey90_a60p` would be just fine (realization: camel case works well for full words but not abbreviations).

**Comment by pocmo** [comment]
> Colors resources are traditional underscore_notation in Android

There are definitely two styles. The system colors.xml file uses snake_case (and also Snake_case 😂):
https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/colors.xml

But the colors in themes are camel case: colorPrimary, colorPrimaryDark, colorAccent, activityBackground, primaryTextColor:
https://developer.android.com/guide/topics/ui/look-and-feel/themes#CustomizeTheme

**Comment by pocmo** [comment]
> photonGrey90_a60p (for grey 90 @ 60% opacity)

Unrelated: In case this is used on top of another solid color try to use the "combined" color to avoid overdraw.

**Comment by mcomella** [comment]
Do we want to adopt snake_case or camelCase then? How do we decide?

> Unrelated: In case this is used on top of another solid color try to use the "combined" color to avoid overdraw.

Unfortunately, it covers the whole screen but thanks for looking out. 😎

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793136

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
