### ISSUE TITLE
Update Try Catch Error Logging To Use Lib-Crash Exception Reporting

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#4589]
Currently all try catch exception are only logged.  After lib-crash introduced exception reporting without crash, change all exception without crash logging to use the lib-crash exception reporting.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3895)

**Comment by pocmo** [comment]
Let's only change the ones where we are interested in the data - some (or most?) are okay to only go to the log... :)

**Comment by rocketsroger** [comment]
> Let's only change the ones where we are interested in the data

Understood.  Thanks

**Comment by csadilek** [comment]
Best to do this on a case-by-case basis, as we have been in order to keep Sentry as clean as possible.
