### ISSUE TITLE
Secure Proxy: Design a secure means of token generation/sharing

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#4596]
The secure proxy extension A-C will require a secure solution to generate and share FxA tokens to the WebExtension. We need to design this authentication scheme.

**Dependencies**:
The Firefox Accounts, Application Services team, Android Components team, and Secure Proxy team will need to weigh in on the solution.
This task should depend upon a security review to ensure proper practices were followed.

**Acceptance Criteria**:
- The Secure Proxy Android Component has a design to provide the tokens it requires to communicate with the Secure Proxy server.
- No security principles were violated that might leak the FxA key or allow other extensions to reuse it.

**Comment by grigoryk** [comment]
Going to happen in https://github.com/mozilla-mobile/android-components/issues/4753.

**Comment by colintheshots** [comment]
We now have a system design for this.
