### ISSUE TITLE
Secure Proxy: Build an initial prototype Android Component

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#4597]
The first step in building a Secure Proxy Android Component is to create the simplest possible prototype that merely loads the WebExtension with hardcoded credentials, sets up the proxy, and send traffic through it.

In doing so, I expect we'll discover any missing, critical APIs required to provide any Secure Proxy functionality.

**Dependencies**:
There should be no dependencies on other teams, but this exercise is meant to discover hidden dependencies.

**Acceptance Criteria**:
One should be able to send and receive traffic over the Secure Proxy.

**Comment by grigoryk** [comment]
Let's close this, we'll just do the concrete work as described in https://github.com/orgs/mozilla-mobile/projects/46
