### ISSUE TITLE
App links: Change AppLinkRedirect to provide Drawable and app name String

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4613]
We can make the API for `AppLinkRedirect` better by calling `ResolveInfo.loadIcon` and `ResolveInfo.loadLabel` before returning instead of making the calling app do that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3916)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793135

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
