### ISSUE TITLE
Allow context menu to show custom share sheet

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4614]
In https://github.com/mozilla-mobile/fenix/issues/2933, Fenix wants to show a custom share sheet instead of the standard Share Sheet.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3917)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793137

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
