### ISSUE TITLE
Publish `tooling-detekt` to maven repository for internal usage.

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/android-components#4618]
And let other projects use it.

For [mozilla-mobile/fenix/3880](https://github.com/mozilla-mobile/fenix/issues/3880)

**Comment by JohanLorenzo** [comment]
Hi there! 

`tooling-detekt` is blocking the snapshots from being published. The reason is:

```
* What went wrong:
Task 'publish' not found in project ':tooling-detekt'.
```

Source: https://tools.taskcluster.net/groups/ey939EkAQlKKc5d7CqwOxA/tasks/H3bWTY_uQpeYyixuShLuJQ/runs/0/logs/public%2Flogs%2Flive_backing.log

**Comment by csadilek** [comment]
Reopening this as we had to set `publish=false` again. Our publish tasks are not prepared/configured yet for publishing .jar files (only .aar). So, there's more work we need here and I wasn't able to fit that in today.

**Comment by dector** [comment]
Woops. I guess it's my fault. In [mozilla-mobile/fenix/#3880](https://github.com/mozilla-mobile/fenix/issues/3880) I wrote that I published to `mavenLocal()` with `maven-publish` plugin. Didn't try taskcluster task however.

**Comment by dector** [comment]
Guess we can close this issue in favor of #6351
