### ISSUE TITLE
Let apps request a private custom tab

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4625]
Some apps have their own private mode equivalent, but links will open in the user's browser and record history. We could offer an intent extra so apps can request custom tabs are opened in private mode, similar to the private keyboard flag.

Some possibilities for the extra name:
- Create our own namespaced extra (`mozilla.components.customtabs.EXTRA_OPEN_IN_PRIVATE_MODE`)
- Chrome uses an boolean extra for only internal intents: [`EXTRA_OPEN_NEW_INCOGNITO_TAB`](https://github.com/chromium/chromium/blob/50b04f5d3671799253eb163e0e5ce3d373bcb1e2/chrome/android/java/src/org/chromium/chrome/browser/IntentHandler.java#L272).
- Copy the more generalized terms used by android, such as [`FLAG_SECURE`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#FLAG_SECURE) or [`IME_FLAG_NO_PERSONALIZED_LEARNING`](https://developer.android.com/reference/android/support/v13/view/inputmethod/EditorInfoCompat.html#IME_FLAG_NO_PERSONALIZED_LEARNING)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3920)

**Comment by NotWoods** [comment]
Turns out this is also in the works for Chrome: https://conn.dev/chrome-incognito.html

Their current plans are to let external apps start an incognito tab, but only to the new tab page and not to a specific URL. This is to avoid leaking the current incognito session data.

Technically we don't have this problem right now because every private tab is currently isolated from each other 😄 

The long-term solution is probably to create a private container for the app, once the container API is set up.

**Comment by R4md4c** [comment]
@NotWoods Hello, is this ticket just a matter of handing `EXTRA_OPEN_IN_PRIVATE_MODE` as a boolean and add a new `Session` with `isPrivate=true` in [1]? or are there any caveats? 

[1] https://github.com/mozilla-mobile/android-components/blob/096e84b06b43a3cc4adf7750bddfafeaae0abf71/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabIntentProcessor.kt#L34

**Comment by NotWoods** [comment]
@R4md4c That's how to implement it, but we should decide what extra to use first. This is an API that we'd expose to any app so once we pick it's fairly set in stone.

**Comment by R4md4c** [comment]
Hmm, I guess I'm not the best one to decide then. Thanks for your quick response though!

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796214

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
