### ISSUE TITLE
Change suggestion providers to be a mutableSet, not a mutableList

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#4632]
Since we're currently just crashing if we try to add a `SuggestionProvider` that has the same ID as one already in use, why not just make this into a set?

Doing so would allow us in Fenix to [easily update which providers are available](https://github.com/mozilla-mobile/fenix/pull/5778/files#diff-de2161f65b2eebcd91d886bc5d00bbf3R228-R238) without having to keep track of this internally in Fenix.

It's a lot of bookkeeping and it's likely very useful for all consumers of AwesomeBar to be able to find out if their provider is already in the recyclerview. Either a `contains` function that checks the ID or using a set would work here 😄

**Comment by csadilek** [comment]
> Either a contains function that checks the ID or using a set would work here 😄

Definitely in favour of adding a method to check, but not just turning this into a set. The latter would swallow inconsistent states e.g. what if two different (types of / versions of)  providers with the same ID actually exist on the classpath and get added? So, I think throwing an exception in this case is fine.
