### ISSUE TITLE
Display Sharing Shortcuts for PWAs

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4637]
To support [Web Share Target](https://wicg.github.io/web-share-target/), we need to display entries in the Android share sheet for installed PWAs. 

We can use [Sharing Shortcuts](https://developer.android.com/training/sharing/receive#providing-direct-share-targets) to display entries in the share sheet dynamically. Note that this is different to Chrome's WebAPKs, since those are signed APK files that can create static share entries. We can use Direct Share (normally used to let users share to a specific person) to support Web Share Target on Android 6 and above.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3929)

**Comment by NotWoods** [comment]
Blocked on #4636

**Comment by NotWoods** [comment]
Blocked on #5667

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796442

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
