### ISSUE TITLE
Toolbar 3 dot menu button ripple clips behind Tab Counter toolbar item

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#4639]
## Steps to reproduce

In Fenix, click 3 dot menu in toolbar

### Expected behavior

Ripple should have circular effect

### Actual behavior

Menu ripple is cut off behind TabCounterToolbarButton

https://streamable.com/udfv5

### Device information

* Android device: Android Pie, OnePlus 3T
* Fenix version: 2.1.0

(copied from https://github.com/mozilla-mobile/fenix/issues/5781)

**Comment by mcarare** [comment]
Verified as fixed: https://github.com/mozilla-mobile/fenix/issues/5781
