### ISSUE TITLE
Fretboard: Let app access a list of experiments

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#464]
In apps we want to have UI to manually override experiments. In order to provide such a UI we would need to get a list of experiments from Fretboard.

Another use case is #115 where we would need to get the list of experiments (and filter active ones) to send the IDs to telemetry.

**Comment by pocmo** [comment]
@fercarcedo :)

**Comment by fercarcedo** [comment]
I'll add it, yes :)
