### ISSUE TITLE
Getting Unresolved MemoryUnit from org.mozilla.components:service-glean:6.00-SNAPSHOT@aar

### ISSUE THREAD

**Issue by Zfr21** [mozilla-mobile/android-components#4665]
as of Today, I'm getting build Failed constantly because of service-glean component doesn't have `MemoryUnit` in spite of nothing changed.

> Task :app:compileAarch64ProductionKotlin FAILED
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/Activation.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/BookmarksManagement.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/Collections.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/ContextMenu.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/CrashReporter.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/CustomTab.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/ErrorPage.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/Events.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/FindInPage.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/History.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/Library.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/Metrics.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/Pings.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/QrScanner.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/QuickActionSheet.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/ReaderMode.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/SearchDefaultEngine.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/SyncAccount.kt: (16, 49): Unresolved reference: MemoryUnit
e: /Users/zaferc/app/build/generated/source/glean/aarch64/production/kotlin/SyncAuth.kt: (16, 49): Unresolved reference: MemoryUnit

I can't see MemoryUnit enum class in service-glean under external libraries whereas I can see related class in [GitHub page](https://github.com/mozilla-mobile/android-components/blob/master/components/service/glean/src/main/java/mozilla/components/service/glean/private/MemoryUnit.kt)

<img width="653" alt="Screen Shot 2019-10-07 at 11 24 40" src="https://user-images.githubusercontent.com/3411255/66296074-6cb5dc00-e8f5-11e9-8381-5b13d6c189b6.png">

what I'm doing wrong?

**Comment by pocmo** [comment]
I'm not sure what exactly the issue is here. But I'm surprised that you are working on a 6.0.0 SNAPSHOT build. 6.0.0 has long been released. I'd recommend switching to the release version of 6.0.0 or better a more recent release version.
https://mozac.org/changelog/

**Comment by Zfr21** [comment]
due to business decisions we don't use come components from Mozilla-components and we moved those into the modules in project so we couldn't update project till July. How can I overcome this build issue with minimum effort?

**Comment by Zfr21** [comment]
I can also see a downloading related to glean + python 3.7.0

> Task :app:Bootstrap_CONDA_'Miniconda3'
Downloading Miniconda3-4.5.11-MacOSX-x86_64.sh
Bootstraping to /Users/ext02d17800/.gradle/glean/bootstrap-4.5.11/Miniconda3
PREFIX=/Users/ext02d17800/.gradle/glean/bootstrap-4.5.11/Miniconda3
installing: python-3.7.0-hc167b69_0 ...
Python 3.7.0
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-1 ...
installing: libcxxabi-4.0.1-hebd6815_0 ...
installing: xz-5.2.4-h1de35cc_4 ...
installing: yaml-0.1.7-hc338f04_2 ...
installing: zlib-1.2.11-hf3cbc9b_2 ...
installing: libcxx-4.0.1-h579ed51_0 ...
installing: openssl-1.0.2p-h1de35cc_0 ...
installing: tk-8.6.8-ha441bb4_0 ...
installing: libffi-3.2.1-h475c297_4 ...
installing: ncurses-6.1-h0a44026_0 ...
installing: libedit-3.1.20170329-hb402a30_2 ...
installing: readline-7.0-h1de35cc_5 ...
installing: sqlite-3.24.0-ha441bb4_0 ...
installing: asn1crypto-0.24.0-py37_0 ...
installing: certifi-2018.8.24-py37_1 ...
installing: chardet-3.0.4-py37_1 ...
installing: idna-2.7-py37_0 ...
installing: pycosat-0.6.3-py37h1de35cc_0 ...
installing: pycparser-2.18-py37_1 ...
installing: pysocks-1.6.8-py37_0 ...
installing: python.app-2-py37_8 ...
installing: ruamel_yaml-0.15.46-py37h1de35cc_0 ...
installing: six-1.11.0-py37_1 ...
installing: cffi-1.11.5-py37h6174b99_1 ...
installing: setuptools-40.2.0-py37_0 ...
installing: cryptography-2.3.1-py37hdbc3d79_0 ...
installing: wheel-0.31.1-py37_0 ...
installing: pip-10.0.1-py37_0 ...
installing: pyopenssl-18.0.0-py37_0 ...
installing: urllib3-1.23-py37_0 ...
installing: requests-2.19.1-py37_0 ...
installing: conda-4.5.11-py37_0 ...
installation finished.
Installing packages via pip: [glean_parser==1.9.0]
Executing '/Users/ext02d17800/.gradle/glean/bootstrap-4.5.11/Miniconda3/bin/pip install --trusted-host pypi.python.org --no-cache-dir glean_parser==1.9.0'
Collecting glean_parser==1.9.0
  Downloading https://files.pythonhosted.org/packages/77/d7/42038d8601d52caffa957c10a6cf9701db0373b068abdbbf13c9af3997b6/glean_parser-1.9.0-py2.py3-none-any.whl (42kB)
Collecting appdirs>=1.4.3 (from glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting Jinja2>=2.10.1 (from glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl (125kB)
Collecting inflection>=0.3.1 (from glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/d5/35/a6eb45b4e2356fe688b21570864d4aa0d0a880ce387defe9c589112077f8/inflection-0.3.1.tar.gz
Collecting jsonschema>=3.0.2 (from glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/54/48/f5f11003ceddcd4ad292d4d9b5677588e9169eef41f88e38b2888e7ec6c4/jsonschema-3.0.2-py2.py3-none-any.whl (54kB)
Collecting Click>=7.0 (from glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
Collecting PyYAML>=3.13 (from glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz (265kB)
Collecting diskcache>=4.0.0 (from glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/94/70/7f08ad115d1b82c4c212f9ee94235826d3873350a4d25e3c9d0d8137e5c9/diskcache-4.0.0-py2.py3-none-any.whl (44kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/ce/c6/f000f1af136ef74e4a95e33785921c73595c5390403f102e9b231b065b7a/MarkupSafe-1.1.1-cp37-cp37m-macosx_10_6_intel.whl
Requirement already satisfied: six>=1.11.0 in /Users/ext02d17800/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages (from jsonschema>=3.0.2->glean_parser==1.9.0) (1.11.0)
Collecting pyrsistent>=0.14.0 (from jsonschema>=3.0.2->glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/b9/66/b2638d96a2d128b168d0dba60fdc77b7800a9b4a5340cefcc5fc4eae6295/pyrsistent-0.15.4.tar.gz (107kB)
Collecting attrs>=17.4.0 (from jsonschema>=3.0.2->glean_parser==1.9.0)
  Downloading https://files.pythonhosted.org/packages/6b/e8/2ecaf86b128a34e225807f03b22664302937ab826bd3b7eccab6754d29ea/attrs-19.2.0-py2.py3-none-any.whl (40kB)
Requirement already satisfied: setuptools in /Users/ext02d17800/.gradle/glean/bootstrap-4.5.11/Miniconda3/lib/python3.7/site-packages (from jsonschema>=3.0.2->glean_parser==1.9.0) (40.2.0)
Installing collected packages: appdirs, MarkupSafe, Jinja2, inflection, pyrsistent, attrs, jsonschema, Click, PyYAML, diskcache, glean-parser

is this trigger the error?

**Comment by Zfr21** [comment]
quick fix is to change version from 6.0.0-SNAPSHOT -> 6.0.0
