### ISSUE TITLE
Support upcoming crash format changes

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#4666]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1420363

**Comment by rocketsroger** [comment]
Confirmed the change is to support the new JSON format in the extra file.  This will require GeckoView Changes first.

**Comment by pocmo** [comment]
@rocketsroger I wonder how we are going to deal with that internally: We may get a crash report from a GeckoView with the old or the new format. Can we dynamically handle both? Or would we need some help from GV to know what to do?

**Comment by pocmo** [comment]
@rocketsroger Since the GV change has not landed yet. Can you make sure to test that once that is available? :)

**Comment by rocketsroger** [comment]
> @rocketsroger Since the GV change has not landed yet. Can you make sure to test that once that is available? :)

Sure, issue created.  Thanks!
