### ISSUE TITLE
Move auto-publication workflow code out of Fenix's settings.gradle and into a-c

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4677]
Follow-up to https://github.com/mozilla-mobile/android-components/pull/4658:

A corresponding Fenix PR added a bunch of code to `settings.gradle` on the Fenix side. See https://github.com/mozilla-mobile/fenix/pull/5801

Ideally, this code should live in `substitute-local-ac.gradle`, and only changes that should stay in Fenix should be about `applying` that script from the local a-c repo.

With that clean-up in place, it should be trivial to enable this workflow to other projects that consume a-c (like lockwise).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3943)

**Comment by csadilek** [comment]
Won't be needed in the shared repo.
