### ISSUE TITLE
SearchSuggestionClient.getSuggestions(): Return empty list on error?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#469]
I wonder if we should just return an empty list here? It would be easier for clients to deal with that than a nullable **and** possible exceptions. If we really need the error case (Does an app care about error or *no* suggestions?) than this method could just return `null`?

https://github.com/mozilla-mobile/android-components/blob/1d924a0cd73b3525e919688111076f8ec50c252d/components/browser/search/src/main/java/mozilla/components/browser/search/suggestions/SearchSuggestionClient.kt#L39-L55

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3950)

**Comment by pocmo** [comment]
@boek What do you think?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796458

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
