### ISSUE TITLE
Make sure we don't run two downloads for the same file

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#4690]
This is a bug that I took from Fennec:

https://bugzilla.mozilla.org/show_bug.cgi?id=1586623

> *Steps to reproduce:* I opened an article at sina.cn *Actual results:* The webpage recursively downloaded the same .APK file. When I closed the page I had over 500 downloads pending. *Expected results:* Firefox should have asked me if I want to download the file. Also there needs to be a way to cancel all pending downloads.

Filing this here to be sure we can avoid this situation in our new implementation.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3951)

**Comment by pocmo** [comment]
Fenix is currently prompting for every download. So at least it should not start downloading the world. However this may still spam download prompts.

**Comment by liuche** [comment]
@kglazko this also looks like something that could be worked.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792949

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
