### ISSUE TITLE
Firefox for Android should use the backwards compatible Sharing Shortcut API from Android 10

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#4691]
This is a bug that was filed against Fennec. I am filing this here to be sure we cover this case properly in our share component. (If the sharing code lives in Fenix, then please move the issue over).

https://bugzilla.mozilla.org/show_bug.cgi?id=1586664

Steps to reproduce:

 - Use Android 10
 - Open any app (not just firefox)
 - Use the share functionality to share website link with firefox

Actual results:

Firefox appears lower in the list (low priority). This is due to it using the old Direct Share API.

Expected results:

Firefox, if shared to recently, should appear at the top of the list. This would happen if Firefox was updated to use the Sharing Shortcut API. Please see https://developer.android.com/training/sharing/receive.html#sharing-shortcuts-faq

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3952)

**Comment by SubhrajyotiSen** [comment]
Can I pick this up?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796207

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
