### ISSUE TITLE
Improve the TrackingProtectionUseCases to be able to remove an item using an URI (string)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4699]
The actual API  when you query what is on the exception list, it provides a list of URI (string) objects, but when you want to remove one specific item you have to provide an `Session` object. That is not usable for actual UI that we have on Fenix 

![image](https://user-images.githubusercontent.com/773158/66513327-daeed000-eaa8-11e9-962b-ab15e123d5b0.png)

https://bugzilla.mozilla.org/show_bug.cgi?id=1587552

GeckoView is going to provide us an api for that https://bugzilla.mozilla.org/show_bug.cgi?id=1587552

**Comment by fluffyemily** [comment]
Underlying Gecko issue resolved 17th Jan 2020

**Comment by Amejia481** [comment]
This can be closed was addressed in https://github.com/mozilla-mobile/fenix/commit/301f56d144754e6c26f7e390952f35287185dfd4
