### ISSUE TITLE
Support for handling `Manage Account` button

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4705]
Fenix will add a `Manage Account` button in https://github.com/mozilla-mobile/fenix/issues/5915. This ticket is about adding a method to `FxaAccountManager` to expose a settings FxA url, of form: `${config.fxaContentRoot}settings?automatedBrowser=true&context=oauth_webchannel_v1`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3958)

**Comment by jonalmeida** [comment]
We did this. :)
