### ISSUE TITLE
Use prettier to format JavaScript in extension code

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4706]
[mozilla-central uses prettier to format its JavaScript](https://bugzilla.mozilla.org/show_bug.cgi?id=1558517) and we can enable it here too. We're going to have more JS for extensions so it'll be good to lint it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3959)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796323

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
