### ISSUE TITLE
Create a per-task tab selection system

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4711]
Currently, we represent tabs as a list of objects with IDs, and have a field for the "selected" tab ID.

Unfortunately this system has some limitations. Notably, when dealing with custom tabs we need to track the custom tab session ID separately and pass that around rather than working with the selected tab. However, hardcoding the session ID makes it difficult to deal with pop-up windows and `_blank` links that open a new tab.

If we want to support multiple windows or split-screen (with the same browser app in each window/split) then there will also be multiple "selected" tabs at once.

We need to set up a new system. I suggest a system where the "selected" tab is local to the Fragment, rather than global. This could come in the form of storing it as saved state in the Fragment/Activity and passing it around, or through a map of task -> selected session. Like the current "selected" tab ID field, this ID needs to be mutable so that it can react to new tabs opening. 

Handling the selected tab per-task will also improve the custom tab workflow as custom tabs will be just another task. As a result the session handling will be the same for both custom tabs and normal tabs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3960)

**Comment by pocmo** [comment]
Can you elaborate a bit more what you are trying to solve here? (e.g. what you described in the second paragraph).

> If we want to support multiple windows or split-screen (with the same browser app in each window/split) then there will also be multiple "selected" tabs at once.

This is something we did not intent to do and therefore also did not design for it.

> We need to set up a new system. I suggest a system where the "selected" tab is local to the Fragment, rather than global. This could come in the form of storing it as saved state in the Fragment/Activity and passing it around, or through a map of task -> selected session.

I'm not sure how this would work in practice. The selected tab is independent from the view. Even if the view is destroyed and not visible anymore it is still the selected tab and will be selected the next time the app is launched.

**Comment by jonalmeida** [comment]
Taking a shot to explain what Tiger is suggesting: a single Custom Tab can have multiple sessions with new window requests (e.g. a pop-up window to login that closes). 

So we would need to observe the current session and when a new window request shows up, we want to new the same View™ with the new session, giving the impression it was loading in the same custom tab window, and when that child session wants to close itself, we would need to observe the parent session (via the `parentId` I imagine).

**Comment by jonalmeida** [comment]
Spoke with @csadilek on this offline: we decided that what is in `CustomTabWindowFeature` for `onOpenWindowRequested` should work fine if it launches a new window on top while appearing to be the same window, such that we can handle `onCloseWindowRequested` when done so that it goes back to the previous window.

This solution needs to be tested so that we can also see if it works with the `singleTask` mode that we have AND that we have the ability to close only the top most task and return back to the previous one.

If all the above is not possible though, we may have to introduce the concept of a parent/child relationship for CustomTabs into BrowserState as well.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793193

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
