### ISSUE TITLE
Confirm lib-crash works correctly with GeckoView new JSON extras file format

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#4717]
Once GV change is in, confirm that lib-crash works correctly with the new JSON format.
The GV change is
https://bugzilla.mozilla.org/show_bug.cgi?id=1420363

**Comment by rocketsroger** [comment]
This is to confirm changes merged in
https://github.com/mozilla-mobile/android-components/issues/4666

**Comment by pocmo** [comment]
Testing the new bugzilla autolink feature:
BZ-1420363

**Comment by rocketsroger** [comment]
From recent crashes this is confirmed working.  Closing
