### ISSUE TITLE
Seeing obsolete cached pages after going back

### ISSUE THREAD

**Issue by djc** [mozilla-mobile/android-components#4720]
Currently seeing this more often (at least once per day on Hacker News with Fenix), so I thought I might file it here. 

Steps to reproduce

    Navigate to Reddit (for example https://www.reddit.com/r/rust)
    Click one of the links
    Go back

Expected behavior

See the same version of the page as before.
Actual behavior

In some instances, I see an older version of the page (probably from some cache).
Device information

    Android device: Pixel 2
    Fenix version: 1.0.1924 (Build #11630620 68.0-2019060411028)

Previously reported for Fennec as https://bugzilla.mozilla.org/show_bug.cgi?id=1500797 and in Fenix as https://github.com/mozilla-mobile/fenix/issues/3470.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3963)

**Comment by ernstp** [comment]
Also seeing this a lot.

**Comment by RayBB** [comment]
This is also happening on Firefox Android 68.3.0.

**Comment by gwarser** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1545909

**Comment by csadilek** [comment]
Fixed by: https://bugzilla.mozilla.org/show_bug.cgi?id=1545909
