### ISSUE TITLE
WebChannels: ability to configure "FxA Capabilities" based  on "auth flow type"

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4751]
With the upcoming Secure Proxy work, we need to be able to configure "fxaCapabilities" in `FxaWebChannelFeature` based on the _reason_ we're authenticating.

Currently, "choose what to sync" is enabled/disabled at creation time, which works for a config flag but doesn't work for dynamic auth flows at runtime.

For now, we'll have a simple two-way split:
- if we're authenticating to enable Secure Proxy, we should disable "choose what to sync"
- otherwise, we enable it, while still allowing the app to overwrite to support "disable CWTS via an experiment"

But, keep in mind that we may have more permutations of these types of flags in the future, so the solution needs to be flexible enough to support that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3989)

**Comment by colintheshots** [comment]
This involves adding new methods to WebChannelFeature: addCapability() and removeCapability().
