### ISSUE TITLE
FxaAccountManager: introduce "reason" into begin/end auth API

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4752]
For the upcoming Secure Proxy integration, we need to be able to authenticate without necessarily turning on Sync.

I think this looks like introducing a concept of "auth reason" at the FxaAccountManager auth API level.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-3991)

**Comment by colintheshots** [comment]
Add sync reason to `syncManager.start(reason)` to not start syncing if the user signed in for Secure Proxy, but is not already signed in for syncing.
