### ISSUE TITLE
Make lib-dataprotect work for API21,22

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4758]
Currently it's API23+. Fenix is 21+, so it would be very helpful if dataprotect could be used there unconditionally. We can then use it to back our FxA state storage (see https://github.com/mozilla-mobile/android-components/issues/3982).
There's a PR in  progress that looks at loosening that requirement to be API18+: https://github.com/mozilla-mobile/android-components/pull/4740

**Comment by ekager** [comment]
Closing because we landed #4958 - which lowered the min API version for the dataprotect library and created SecureAbove22Preferences - which securely stores strings using the dataprotect `Keystore` for API 23 and up, otherwise just uses SharedPreferences to store for 21-22.
