### ISSUE TITLE
Make long presses on web content observable/consumable

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#476]
Part of #200.

**Comment by pocmo** [comment]
I think that a long press should be a `Consumable` in Session like `Download`. We could create some class like `LongClick` that contains meta data about what was clicked. Observers can then handle this click and consume the object.

For Focus-parity we need at least the functionality of `HitTarget`:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/web/IWebView.java#L15-L36

We can probably come up with a nicer API than just a bunch of booleans and Strings. However be aware that a `HitTarget` can be multiple things: It can be a link and an image at the same time.

Additionally we can look at the APIs of GeckoView and WebView and see if there's more we can implement or whether one of them (hopefully GeckoView) implements a nicer API that we can mirror.

**Comment by jonalmeida** [comment]
After some investigation I think we can support most of the [HitTestResults][3] that WebView does and do some simple checking in a-c for a few more types:
```kotlin
class HitResult(type: Int) {
    companion object {
        const val NONE_TYPE = 0
        const val IMAGE_TYPE = 1
        const val VIDEO_TYPE = 2
        const val AUDIO_TYPE = 3
        const val SRC_TYPE = 4
        const val IMAGE_SRC_TYPE = 5 
        const val PHONE_TYPE = 6 // URI prepended with 'tel:'
        const val EMAIL_TYPE = 7 // URI prepended with 'mailto:'
        const val GEO_TYPE = 8 // URI prepended with 'geo:'
    }
}
```
I can't find any other multiple types other than image + link, so having a separate `IMAGE_SRC_TYPE` for it seems fair.

For our Gecko implementation, we're given the [basic element types][1] (e.g. img, video, audio), but within the components, we can support more by checking the URI values (e.g. [geo][2]).

In System WebView, we just forward those on.

[1]: https://dxr.mozilla.org/mozilla-central/source/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/GeckoSession.java?q=GeckoSession.java&redirect_type=direct#2039-2043
[2]: https://tools.ietf.org/html/rfc5870
[3]: https://developer.android.com/reference/android/webkit/WebView.HitTestResult

**Comment by pocmo** [comment]
@jonalmeida Sounds great! :)

> WebView also supports long presses on edit texts but I'm not sure what use that is, nor does Gecko provide us with enough information for us to support that type.

Yeah, let's ignore that for now. That's usually handled by the text selection implementation.
