### ISSUE TITLE
Add engine setting for forcing the ability to scale content

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#4761]
With https://github.com/mozilla-mobile/fenix/issues/2477 we want to give the users the ability to always scale content. This was added to GeckoView here: https://bugzilla.mozilla.org/show_bug.cgi?id=1540615#c10.

**Comment by csadilek** [comment]
Closed by: https://github.com/mozilla-mobile/android-components/commit/5e23e29cc80be3d1331077a19dfdc6ed65e38cee
