### ISSUE TITLE
Ask AMO / SUMO how to deal with existing Firefox for Android links

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4763]
During bookmark migration, for most users we'll inherit Fennec's default bookmarks.

These are:
- about:firefox
- AMO: https://addons.mozilla.org/android?utm_source=inproduct&utm_medium=default-bookmarks&utm_campaign=mobileandroid
- SUMO: https://support.mozilla.org/products/mobile?utm_source=inproduct&utm_medium=default-bookmarks&utm_campaign=mobileandroid
- Mozilla: https://www.mozilla.org/en-US/
- Firefox Accounts: https://www.mozilla.org/en-US/firefox/accounts/

Last two are fine, but we need to make sure others do sensible things.

**Comment by st3fan** [comment]
Not actionable by migration.

**Comment by ebalazs-sv** [comment]
Since this is not actionable by migration as mentioned in the previous comment, I will move this to Done. Thanks!
