### ISSUE TITLE
Process intents for downloading a file

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4770]
To be able forward intents to an external download manager, first  we need to handle intents for downloading a file. Take a look at [TabIntentProcessor](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/intent/src/main/java/mozilla/components/feature/intent/processing/TabIntentProcessor.kt).

**Comment by pocmo** [comment]
I don't think we need to handle any intents ourselves. Instead we just forward incoming `Download`s to other apps if needed.

**Comment by Amejia481** [comment]
Yes, but as part of forwarding downloads to external apps we need to create **an intent chooser** where we are going to have **all the apps that can handle the download** and **add our app (Fenix or other consumer) to the list of intents**.

In the case, that our app is pressed from the intent chooser we have to handle the download. Is not the way that  Fennec how works?

**Comment by pocmo** [comment]
In Fennec it is custom UI that "looks like an intent chooser". It is not actually an intent chooser. When Fennec is selected it just schedules the download and if another app is selected it launches the intent.

**Comment by Amejia481** [comment]
Ok, thanks!
 Then we can close this issue and update https://github.com/mozilla-mobile/android-components/issues/4772 with that info.
