### ISSUE TITLE
position:fixed elements is not sticking to the dynamic toolbar when user release thier finger from screen in the middle of the dynamic toolbar transition

### ISSUE THREAD

**Issue by hiikezoe** [mozilla-mobile/android-components#4780]
Steps to reproduce
1. Open https://www.sozone.de
2. Drag the content slowly
3. Release your finger in the middle of the dynamic toolbar transition

CC @pocmo @snorp @theres-waldo

To reproduce this issue you probably need to modify fragment_browser.xml in reference-browser or fenix to call setVerticalClipping properly.

I haven't investigated in detail, but I guess this issue will be solved by sending notifications when the dynamic toolbar is completely hidden ([bug 1586147](https://bugzilla.mozilla.org/show_bug.cgi?id=1586147) and flushing layout in Gecko (it should probably just update position:fixed element positions).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4033)

**Comment by hiikezoe** [comment]
@jonalmeida could you please take a look at this issue?  I believe this should be a blocker of https://github.com/mozilla-mobile/fenix/issues/4383

**Comment by jonalmeida** [comment]
@hiikezoe `setVerticalClipping` is currently being [invoked dynamically](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/src/main/java/mozilla/components/feature/session/behavior/EngineViewBottomBehavior.kt#L47) as the toolbar is scrolled off the screen.

This is the EngineView behaviour that is attached to the EngineView in [`fragment_browser.xml`](https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/res/layout/fragment_browser.xml#L18).

Maybe we're using this API incorrectly?

**Comment by hiikezoe** [comment]
as far as I can tell, when the dynamic toolbar snaps to the state that the toolbar is completely hidden (or completely visible), onDependentViewChanged is not called at all. I am not sure it's an issue in CoordinatorLayout (or in CoordinatorLayoutBehavior itself) when the child's translationY is directly changed.  Maybe there is an API in CoordinatorLayout to change children's translation values to make sure onDependentViewChanged is called.

**Comment by Mugurell** [comment]
Tested on the latest beta and Nightly and also with the patch from https://github.com/mozilla-mobile/android-components/pull/10669 (fixed with Float.roundToInt()) and I see that everything works as expected:


https://user-images.githubusercontent.com/11428869/126629795-fb0d248b-c5b3-4b77-9cc2-de2b48cbb574.mp4

@hiikezoe Does this issue still reproduces for you?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796228

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
