### ISSUE TITLE
Duplicate calls to `Session.Observer#onLoadingStateChanged` on first load

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/android-components#4795]
The first time a new session loads a page, it seems that `Session.Observer#onLoadingStateChanged` is being called several times.  This is not reproducible on subsequent loads, and appears to be unintended behavior.

Verified on Fenix at [this issue](https://github.com/mozilla-mobile/fenix/issues/3676), and can be demonstrated in Reference Browser in [this PR](https://github.com/mozilla-mobile/reference-browser/pull/926)

**Comment by csadilek** [comment]
This is no longer reproducible. I will remove the temporary workaround introduced in Fenix as part of https://github.com/mozilla-mobile/fenix/issues/11286.
