### ISSUE TITLE
Update Firebase Cloud Messaging dependencies to 25.0.0+

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4819]
There were breaking changes involved in 19.0.0 that provided better support for Kotlin<sup>[1]</sup>, bettter API annotations, and also stability/bug fixes.

Current version: 17.3.4

[1]: https://firebase.google.com/support/release-notes/android#2019-06-17

**Comment by jonalmeida** [comment]
The setup instructions<sup>[1]</sup> also indicate that we no longer need to include the core library any more.

[1]: https://firebase.google.com/docs/android/setup?authuser=1#available-libraries

**Comment by pocmo** [comment]
See https://github.com/mozilla-mobile/android-components/issues/8459 - It looks like we are far behind now (latest version 25) and the library we use is depending on an old support library version.

**Comment by jonalmeida** [comment]
Thanks, adding to sprint planning.

**Comment by jonalmeida** [comment]
Looks like the FCM library is only on 20.3.0 but a new versioning system has Firebase SDK set as 25.0.0.

**Comment by jonalmeida** [comment]
According to [the changelog](https://firebase.google.com/support/release-notes/android#2020-02-27):

> The Firebase Cloud Messaging and Firebase Instance ID SDKs now transitively depend on the Firebase installations SDK. If you use Cloud Messaging and update your dependencies to their latest versions, make sure that push notifications still work as expected. 
>  - The FCM registration tokens of installed instances of your apps **might change once after updating dependencies to their latest versions**.

With the bug https://github.com/mozilla-mobile/android-components/issues/7143 still open, we have the potential to lose our existing Send Tab and web content push users.

**Comment by jonalmeida** [comment]
In [this document](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-installations/FCM_TOKENS_CHANGE.md#how-do-i-find-out-if-my-applications-are-affected), if we use a custom name during init we may be affected (we do not). So we are potentially safe if we risk it.

> If you use a custom name during initialization of the Firebase application your application might be affected.

**Comment by jonalmeida** [comment]
To historical context, we now see that there was another effect from upgrading: the Firebase Instance ID service was replaced with a dependency on the Firebase Installations API.

This required a server-side configuration update.
