### ISSUE TITLE
AutopushFeature: Rename DeliveryManager extension function

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#4822]
In the AutopushFeature: `DeliveryManager.with` -> `DeliverManager.runWithInitialized`

**Comment by binc0** [comment]
Could you please assign this to me ☺️

**Comment by binc0** [comment]
#4825

**Comment by apoorv9990** [comment]
Seems like the previous PR was closed. I have created a new PR that closed this  issue https://github.com/mozilla-mobile/android-components/pull/6706
