### ISSUE TITLE
Fix test using apparently base64-encoded string in SessionUseCasesTest

### ISSUE THREAD

**Issue by espertus** [mozilla-mobile/android-components#4828]
`SessionUseCasesTest.kt.loadData()` includes these statements:

```
useCases.loadData("ahr0cdovl21vemlsbgeub3jn==", "text/plain", "base64", selectedSession)
verify(selectedEngineSession).loadData("ahr0cdovl21vemlsbgeub3jn==", "text/plain", "base64")
```
Because "ahr0cdovl21vemlsbgeub3jn==" looks like a base64-encoded string (although it isn't), it gives the mistaken impression that one should pass base64-encoded strings to `loadData()`. 

@jonalmeida suggested I file this issue.

**Comment by jonalmeida** [comment]
Closing for https://github.com/mozilla-mobile/android-components/issues/4827
