### ISSUE TITLE
PromptFeature may use invalid request code

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#4854]
Looks like we're using `IDs` as request codes and there's no guarantee that they are valid: R.id.mozac_feature_prompts_file_picker_activity_request_code

See Sentry:
java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode

https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6540015/?environment=fenixNightly

**Comment by Amejia481** [comment]
cc: @NotWoods

**Comment by NotWoods** [comment]
Argh, I tried to use ids to manage our request codes. I'll revert these changes.
