### ISSUE TITLE
Move the tracking proteciton policy class to a per engine variants model

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4857]
Right now, the `TrackingProtectionPolicy` class lives inside of the `concept.engine` package, which cause a bit of difficulty to customize different policies (RECOMMENDED,STRICT) per engine variants.  As FireFox desktop has different policies per engine variants we should follow the same approach.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4108)

**Comment by pocmo** [comment]
Does this still allow us to build an app against multiple engines if we do not have an abstraction over the policies?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795127

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
