### ISSUE TITLE
BrowserIcons.loadIntoView unable to load icon from AMO API

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4867]
I was trying to load this icon[1] from the AMO API but it always returns the generated version

Icon[1]
https://addons.cdn.mozilla.net/user-media/addon_icons/607/607454-64.png?modified=mcrushed

**Comment by pocmo** [comment]
`BrowserIcons` is the wrong choice for this. You are not trying to load an icon for a website. You are trying to load an image and display it. That's a different use case and not the responsibility of `BrowserIcons`.

See #4175

**Comment by csadilek** [comment]
@Amejia481 @pocmo @psymoon  

Looks like the new `GeckoImageDecoder` could be useful here:
https://phabricator.services.mozilla.com/D49038#change-LT5VVNKwBVL8
https://bugzilla.mozilla.org/show_bug.cgi?id=1530402

**Comment by pocmo** [comment]
What's the conclusion here. I think we should WONTFIX this issue (at least with the current description). If we want a generic image loader based on concept-fetch then we should pick up #4175.

**Comment by Amejia481** [comment]
I agree

**Comment by Amejia481** [comment]
I opened https://github.com/mozilla-mobile/android-components/issues/4983 to address the icon issue in the add-on management UI
