### ISSUE TITLE
Fennec migration: "status" observable interface

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4872]
Now that I'm trying out migrations against real profiles, it's obvious that they this stuff will take quite a long time to run.

From slack:
> Note the timing. It took 6 seconds to migrate history, then 5 seconds to migrate bookmarks, then finally we got to FxA migration which took 2-3 seconds

I'm pretty sure we'll have some kind of a special "first run after Fenix upgrade" UI, and part of that UI could indicate progress of our migrations as they execute.

We could expose an observable interface, which UI can use to display real-time migration state.

**Comment by pocmo** [comment]
This also means we should be careful with the order of things. For example we should migrate the open tabs first, so that the user can use/see them asap.

**Comment by pocmo** [comment]
@grigoryk I was thinking a bit about that and potential solutions. Right now I'm leaning towards using `lib-state` for that. We could have a migration-specific store - It's a proven pattern and it allows the background service to update the state and the UI to react to updates and render the state. Does this make sense to you?

**Comment by pocmo** [comment]
The initial implementation for that landed. Let's iterate on that if needed.

**Comment by ebalazs-sv** [comment]
This is in preparation for the upcoming UI and there is nothing observable until the UI lands. Due to this I am moving this to Done.
