### ISSUE TITLE
Fennec migration: run in a foreground service

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4879]
Related to https://github.com/mozilla-mobile/android-components/issues/4872 - our migrations are potentially slow, which creates a large window of time for things to go wrong (OS killing us, user killing us, some bad interaction with Fenix occuring, etc).

To get an additional margin of safety, we could wrap our migration code in a foreground service.

**Comment by pocmo** [comment]
@grigoryk Are you working on this? Otherwise I may pick that up. :)

**Comment by pocmo** [comment]
Just landed in Fenix and should go into the next builds.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release, Beta, Nightly 12/13 migration builds with Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0).
A notification is displayed while migration, and this contains:
warning sign Firefox Preview now
"Migrating" title
"Migrating user data." text
The notification disappears after the migration is done.
