### ISSUE TITLE
Secure proxy: Handle "Firefox Private Network" rejected access in "Devices & Apps"

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4883]
Since FPN will show up as a separate entry in Devices & Apps account management view, it's possible for it to be rejected access, while Fenix itself (as a host app) retains access. The reason for this is that our current plan calls for FPN being authorized as a separate client.

While this split does point out architectural holes in our current design, for the short-term we can focus on addressing these edge cases in a sensible way.

The way a rejection will present itself is via FPN servers being unable to issue new proxy tokens when asked for them by Fenix.

There are a few things that need to happen here:
- rest API FPN servers publishes needs to communicate auth problems back to the client
- we need to pipe up those auth problems back into the Fenix UI, as an SP-specific "need to re-connect" state. We already have this for Sync/FxA, so this could be similar. However, since Sync isn't actually affected by this auth problem, our error UI needs to be SP specific
- if user decides to re-enable SP, we should be able to retrigger the regular "authorize SP" flow - request a new status from FPN, issue a new auth code, and send that back along with status to FPN

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4129)

**Comment by rfk** [comment]
I believe the current FPN integration also has some logic to tie the FPN login state to a particular source IP address and user-agent header. I'm not sure how that will work out in practice, but if it results in the user having to re-authenticate to FPN whenever their IP address changes, we might end up with *multiple* FPN instances in the "devices and apps" view.
