### ISSUE TITLE
Investigate why videos of bbc.com are not playing with strict tracking protection policy

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4898]

**Comment by ehsan** [comment]
It happens on desktop as well as mobile, see this example link: https://www.bbc.com/persian/afghanistan-50254430 or this one: https://www.bbc.com/news/av/world-us-canada-50241252/toronto-handcuffed-man-reveals-gun-in-police-car

**Comment by Amejia481** [comment]
I'm able to playing them on desktop nightly with the strict policy.

https://www.bbc.com/persian/afghanistan-50254430
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/773158/67967872-be901000-fbdc-11e9-86e6-d5fcfc24574b.png">

https://www.bbc.com/news/av/world-us-canada-50241252/toronto-handcuffed-man-reveals-gun-in-police-car
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/773158/67968035-0b73e680-fbdd-11e9-8575-59b1a3a85f8f.png">

**Comment by Amejia481** [comment]
Where I have some issues it is when I switch to the mobile panel under the dev tools menu. It takes a long time to load but after while I'm able to play it.

<img width="883" alt="image" src="https://user-images.githubusercontent.com/773158/67968609-1b3ffa80-fbde-11e9-8859-343c1498b23b.png">

**Comment by ehsan** [comment]
That is extremely strange...  I can certainly not play them (even after waiting for tens of minutes, see the screenshot below).

![image](https://user-images.githubusercontent.com/168508/67971661-90fa9500-fbe3-11e9-8bb6-1540139e5ab9.png)

Can you try with a new profile?

**Comment by elcste** [comment]
BBC videos also aren't playing for me in desktop Firefox with strict tracking protection. I've tried stable channel on Mac and Beta and Nightly on Ubuntu. FWIW I also tried Chromium with the Disconnect.me extension installed, and it also doesn't work unless I whitelist the site.

Might it depend on your physical location? I'm in the US, and when the videos do play — with tracking protection off — I see a pre-roll ad. But I think BBC doesn't show ads in the UK, and maybe other locations, so then it not matter if tracking protection is on or not.

**Comment by Amejia481** [comment]
After updating to the latest version of FireFox desktop (73.0a1 (2019-12-03) (64-bit)) nightly is not playing in strict.

**Comment by elcste** [comment]
BBC videos are playing for me OK now in Fenix and desktop, with no change on my part.

**Comment by Amejia481** [comment]
It looks like this issue has been fixed it was also verified by QA on https://github.com/mozilla-mobile/fenix/issues/7055
