### ISSUE TITLE
[Bug]"Search or enter address" strings improperly positioned in RTL

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#4907]
## Prerequisites
Have RTL enabled in Developer options

## Steps to reproduce
1. Tap on the search bar
2. Check the position of the "Search or enter address" from the search bar

### Expected behavior
Should be properly positioned 

### Actual behavior
"Search or enter address" string to close to the left edge of the search box

### Device information

* Android device: 
• Google Pixel 3a XL (Android 9)
• Samsung Galaxy Note 9 (Android 8.1.0)
• Samsung Galaxy S7 (Android 7)
• LG Nexus 4 (Android 5.1.1)

* Fenix version:  Nightly Build #12980627 from 25/10

[Related to #6269 from Fenix](https://github.com/mozilla-mobile/fenix/issues/6269)

![rsz_rsz_screenshot_20191025-143102](https://user-images.githubusercontent.com/51314259/67572721-72a61c80-f73f-11e9-8e2b-b9f4799b40d8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4156)

**Comment by boek** [comment]
@BranescuMihai it looks like you wrote some code for this. Did it ever make it into a-c?

**Comment by darkwing** [comment]
Pinging again @BranescuMihai :) . Hoping to fix https://github.com/mozilla-mobile/fenix/issues/6269 ASAP!

**Comment by BranescuMihai** [comment]
@boek  @darkwing I'm sorry for not responding faster, somehow I didn't get a notification. There is a PR open on this, I also forgot about it until recently. Feel free to review it, there are 4 possible scenarios mentioned in the description that had to be taken into account.
[https://github.com/mozilla-mobile/android-components/pull/4946](https://github.com/mozilla-mobile/android-components/pull/4946)
