### ISSUE TITLE
Expose background messaging support in support-webextensions

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#4913]
The Secure Proxy WebExtension depends upon sending messages to background WebExtension scripts that are not associated with an `EngineSession`. This is supported by GeckoView currently, but not by the `WebExtensionController` class in `support-webextensions`.

Several methods will need to change to accept a null `EngineSession` and a few methods will be added to register a background message handler or to send a background message where the `EngineSession` is null.

**Comment by csadilek** [comment]
Just adding a note that this is already supported by A-Cs engine and web extension wrappers, so this is specifically to add a utility method to `support-webextensions`.
