### ISSUE TITLE
Allow toolbar menu buttons to determine their state asynchronously (or provide alternative)

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/android-components#4915]
### Use case
As part of https://github.com/mozilla-mobile/fenix/issues/4281, determining whether or not the current site is bookmarked needs to happen within `TwoStateButton#isInPrimaryState`.  Because of how `TwoStateButton` works, this call must be synchronous.  Unfortunately checking if the site is bookmarked is very slow (10-50MS in my tests).

The best fix would be for bookmark checks to be faster (and I've notified the perf team), but I also don't think it is unreasonable to expect that menu items may need to make slow calls to determine their state in the future.  It would be good to have a canonical way of handling this case.

### Fenix workaround
https://github.com/mozilla-mobile/fenix/pull/6310/commits/572e2f6762ebeb5c6d8b65d4d676cb85288a6530

**Comment by Baron-Severin** [comment]
It's also worth noting that, since all the logic is driven by the component, the current toolbar API doesn't play particularly well with LibState.  One possible solution to this could be to have the toolbar handle its presentation details, but to expose `fun update(state: ToolbarState)` and allow client code to drive the logic.  This could also help pave the way for [a future Fenix issue](https://github.com/mozilla-mobile/fenix/issues/6275) that will require updating the toolbar menu while it is open.

**Comment by NotWoods** [comment]
Closing because this is offered in menu2 (#5373)
