### ISSUE TITLE
Tracking protection is not working without an AppRequestInterceptor in fenix

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#4935]
We have to investigate why tracking protection is not working without [reapplying the tracking protection policy per session.](https://github.com/mozilla-mobile/fenix/blob/a7e139da8eb74722aaab1aae7fde927e0e16e97d/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt#L23)

**Comment by jonalmeida** [comment]
I recall seeing related issues with the request interceptor a while back as well: https://github.com/mozilla-mobile/android-components/issues/2794

**Comment by colintheshots** [comment]
In 23.0.0 A-C, this still isn't working it seems.

**Comment by Amejia481** [comment]
I was testing on Fenix and it's working. It looks like it could be another issue that is causing it. Could you please open another issue and include a reference of the app that you are using to test, this way we can try to replicated with the same source code.
