### ISSUE TITLE
Add request code helper

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#4942]
We use request codes for pending intents and requesting permissions, and they're currently hardcoded. We should create a helper similar to the existing `NotificationIds` class.

The `SharedIds` class is fairly generic and will probably work for this purpose too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4195)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793172

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
