### ISSUE TITLE
Enable round-trip encryption tests

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#4956]
Currently they're "ignored" (both in dataprotect Keystore and in the new KeySharedPreferences) due to "mac check in GCM failed".

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4207)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795959

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
