### ISSUE TITLE
Clipboard suggestion icon is white

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#4963]
It's very difficult to see the default suggestion in Sample Browser because the icon is white. 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/68229021-4f833480-ffab-11e9-9f40-20c25e06158c.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4219)

**Comment by sblatz** [comment]
Fixed: 
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/68229205-ad178100-ffab-11e9-9496-ede5c77a7a45.png">

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796455

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
