### ISSUE TITLE
Fennec migration: The Home Screen icon is deleted

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#4978]
## Preconditions:
Have Firefox Release icon on Home Screen.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Observe Fennec's home screen icon.
### Expected behavior
Fennec's home screen icon is replaced with Fenix's icon.
### Actual behavior
Fennec's home screen icon is deleted.
### Notes:
[Video
](https://drive.google.com/file/d/16TlmuvX7viqDOPvMC0_N5m2eEs7xlbrl/view?usp=sharing)
Not reproducible on Google Pixel 3 (Android 10) - ARM64
### Device information

* Android device: Samsung Galaxy S8 (Android 9) - ARM64; Nexus 6P (Android 8.1.0) - ARM
* Fenix version: Nightly 191102 GV 71

**Comment by pocmo** [comment]
This is still a task in our backlog:
- https://github.com/mozilla-mobile/fenix/issues/4976
- https://github.com/orgs/mozilla-mobile/projects/40

**Comment by ebalazs-sv** [comment]
Verified as Fixed on today's Release, Beta, Nightly migration build 12/18 with the devices:
- Google Pixel (Android Q) - ARM64;
- Google Pixel 2 (Android 9) - ARM;
- Samsung Galaxy S8 (Android 9) - ARM64;
- Nexus 6P (Android 8.1.0) - ARM;
- Xiaomi Mi Pad 2 (Android 5.1) - x86.

@pocmo Fenix's icon is displayed on homescreen after migration.
Also the mozilla-mobile/fenix#4976 issue is fixed and verified.

**Comment by pocmo** [comment]
Thanks!
