### ISSUE TITLE
Add support for taking (fullscreen) screenshots

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#498]
Related to #495. However here we want to have the ability to create a screenshot of the whole page - not only the visible parts.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4300)

**Comment by jonalmeida** [comment]
[Bug 1462018][0] is used for both, fulscreen screenshots and thumbnails.

[0]: https://bugzilla.mozilla.org/show_bug.cgi?id=1462018

**Comment by cpeterso** [comment]
The GV API for taking viewport screenshots (for page thumbnails in tab switcher UI) has landed ([bug 1462018](https://bugzilla.mozilla.org/show_bug.cgi?id=1462018)). Support for full page shots is now tracked in a new bug: [bug 1530967](https://bugzilla.mozilla.org/show_bug.cgi?id=1530967). It's still planned but it will be more work.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796371

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
