### ISSUE TITLE
GeckoInputStream read() method not throwing IOException

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#4999]
This bug is related to [6434](https://github.com/mozilla-mobile/fenix/issues/6434) from Fenix.

I narrowed the problem down to the copyInChunks() method from AbstractFetchDownloadService. Here, I tested with Fenix, Reference Browser and samples-browser from a-c. From my tests I observed that samples-browser, which uses the [okio](https://github.com/square/okio) source as an inputStream, returns the appropriate IOException when WiFi connection is interrupted mid-download, while Fenix and Reference Browser, which both use the GeckoInputStream instead, return -1 (which is considered as EOF, so a success response).

As per [java documentation](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#read-byte:A-), an input stream implementation should throw an IOException "if the first byte cannot be read for any reason other than the end of the file", so this behaviour should be fixed in GeckoInputStream.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4316)

**Comment by sblatz** [comment]
Wow, good work for finding this, @BranescuMihai! 

Is this something that we need to change in GV, then, @cpeterso?

**Comment by cpeterso** [comment]
I filed a new GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1594905

The GV fix sounds easy. How urgent is the Fenix Wi-Fi download bug?

**Comment by sblatz** [comment]
@cpeterso I would say the fix is pretty urgent. It's currently allowing users to get in a state where they will crash the app (file looks to be downloaded, they press open, it crashes). I'd like to get this in sooner than later especially if it's an easy fix :)

**Comment by sblatz** [comment]
@csadilek is there a reason Fenix & Sample browser are not in sync on which `InputStream` they're using? It seems like this could lead to other inconsistencies in functionality. This is why this issue slipped past me in development 😕

**Comment by csadilek** [comment]
@sblatz yes, sample browser is using `HttpUrlConnectionClient`, not the `GeckoViewFetchClient`. 

We already have different build variants for `engine-system` (webview) and `engine-gecko` and can override individual components. Since this was a footgun, and we both tested with the sample browser when working on this, let's fix it right away. Here's a PR: https://github.com/mozilla-mobile/android-components/pull/5003

**Comment by cpeterso** [comment]
snorp says this is an A-C bug, not a GV bug:

> EOF does not mean success, it just means there's no more data. For an HTTP[S] response, you have to do more work to determine if the download is complete by checking against the Content-length header or sometimes verifying checksums. You have to do that work whether GeckoInputStream throws IOException or not.

GV bug https://bugzilla.mozilla.org/show_bug.cgi?id=1594905#c2 has been closed as WONTFIX.

**Comment by sblatz** [comment]
"by checking against the Content-length header" We can't do this for all downloads, as not every response gives us content-length. 

I'm not sure how to verify the checksums, but I will touch base with Snorp.

**Comment by cpeterso** [comment]
snorp has reopened the GV bug, saying:

> There is some value in doing what we can here, and plenty of evidence in Gecko that using the OnStopRequest() status is helpful.

https://bugzilla.mozilla.org/show_bug.cgi?id=1594905#c3

**Comment by sblatz** [comment]
In the meantime, I'm going to take his advice and still give a "failed" notification for cases where there **is** a content-length and it is not equal to bytes read.

**Comment by fluffyemily** [comment]
Fix landed in GeckoView on 2019-11-27

**Comment by st3fan** [comment]
> "by checking against the Content-length header" We can't do this for all downloads, as not every response gives us content-length.
> 
> I'm not sure how to verify the checksums, but I will touch base with Snorp.

Just want to add here that a best effort is good enough. This even happens on Desktop in Safari and Firefox: sometimes a download is 'complete' but the file is actually not. If the server does not tell us a Content-Length then we simply can't know for sure.

The user will find out when they try to use the download. It is not the best experience, but at least is similar to other browsers.

**Comment by fluffyemily** [comment]
This issue is marked as `needs:gv` despite all Bugzilla bugs referenced being marked as resolved. Is further GeckoView work required here?

**Comment by sblatz** [comment]
@fluffyemily the GV work on this is done as far as I'm aware :)
