### ISSUE TITLE
Add TabsStorage to concept-storage

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5006]
Adding an interface for `TabsStorage` to the `concept-storage` component, similar to the `HistoryStorage`.

This allows us to support the feature components,  and also be a provider for the AwesomeBar.

**Comment by jonalmeida** [comment]
This should allow for storing open tabs and retrieving them. Probably identified to know which ones are device tabs vs. sync'd ones. 

Not sure yet what that should look like.

**Comment by eoger** [comment]
Side-note: Synced Tabs might evolve to group tabs per-window in the future, maybe there's a way to accommodate for that?

**Comment by jonalmeida** [comment]
How would you identify a window in the sync data? Currently, we don't have a concept of a "window". The closest thing we'd have in Fenix are Collections and those are still quite detached from the rest of the tab paradigm (also undergoing user studies on their usefulness).
