### ISSUE TITLE
Secure version of SecureAbove22Preferences checks for key presence on every access

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5018]
In both `getString` and `putString` we perform a `keystore.available` check, which seems unnecessary - but unclear to me (haven't looked through it) if the overhead here is a problem; we're going to load the keystore anyway right after. Alternative is to perform `keystore.available` check during `init`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4335)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796431

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
