### ISSUE TITLE
Pinned AC snapshot builds

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/android-components#5023]
Currently, AC publishes Snapshot releases twice a day. Fenix master branch uses these snapshots, which pull from the most recently published snapshot.

However, this means that we're missing:
- Reproducibility of builds (because we can't pinpoint what AC version is being used)
- We can pick up random API breakage because the changes aren't built and then merged in

@pocmo brought this up during our Android meeting, and we concluded that: AC should come up with a proposal of how to do this (maybe automated PRs that get merged if CI passes) + talk to releng about the propsal.

**Comment by pocmo** [comment]
We use a similar approach in this repository to automatically update the GV version. I want to use this as a starting point to come up with a proposal. At the same time we should look into getting our GV -> AC automation from manual merge to fully automated merge.

**Comment by pocmo** [comment]
RelEng is currently looking at this problem too and hopefully we can solve this in Q1. :)

**Comment by liuche** [comment]
Only tangentially related to snapshots, but pulling in Nightly GV builds, putting here for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1605402

**Comment by MihaiTabara** [comment]
I'm currently working on this in bug https://bugzilla.mozilla.org/show_bug.cgi?id=1615248

**Comment by pocmo** [comment]
@MihaiTabara Let's chat about the version names and location of the "nightly builds" to avoid our build system getting confused by them. :)

**Comment by MihaiTabara** [comment]
@pocmo Sounds good! I'm still playing with them locally, I hope to have something to show on staging today or tomorrow.

**Comment by MihaiTabara** [comment]
Chatted earlier today with both @pocmo and @JohanLorenzo. We're going to ramp-up https://nightly.maven.mozilla.org/ in order to support the future nightlies that are to replace snapshots. In the meantime, I'm polishing the PR to be ready to test as soon as we have some staging buckets to play against.
