### ISSUE TITLE
Method to check if a Session can be installed

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#5027]
Return some enum saying if a Session/SessionState can be installed to the homescreen as a PWA, Bookmark shortcut, or not at all. This will make it easier to change the "Add to home screen"/"Install to home screen" menu option in Fenix.

We can already query this information as separate methods but I think it would be easier to have a single method to use with Flow.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4342)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796441

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
