### ISSUE TITLE
Truncate file name if it will stop download MB from showing

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#5030]
Currently it's possible for a long download name to make it so the user cannot see the size of the file. We should truncate the file name in the download notification so it always shows file size if it's available.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4346)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792948

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
