### ISSUE TITLE
Fennec migration: Fenix crashes at start

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5041]
## Preconditions:
Have Firefox Release installed and logged in.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix.
### Expected behavior
Fenix opens.
### Actual behavior
Fenix crashes.
### Notes:
[logcat-crash.txt](https://github.com/mozilla-mobile/android-components/files/3840189/logcat-crash.txt)
[Video](https://drive.google.com/file/d/1ERAMHz0FlvcAbjgXUoOEF19udlHCZI4s/view)
### Device information

* Android device: Nexus 6P (Android 8.1.0) - ARM; Samsung Galaxy S8 (Android 9) - ARM; Google Pixel 2 (Android 9) - ARM64.
* Fenix version: Nightly 191109 GV 71

**Comment by grigoryk** [comment]
@ebalazs-sv attached logs don't cover the migration. Is it possible to get full, unfiltered device logs, that start just before you launch the app?

**Comment by ebalazs-sv** [comment]
Hello! Here is the Debug, no filters logcat from Nexus 6P (Android 8.1.0) - ARM:
[startupcrash.txt](https://github.com/mozilla-mobile/android-components/files/3845547/startupcrash.txt)

**Comment by grigoryk** [comment]
Thank you!

Relevant bits, happens sometime after sync executes:
```
2019-11-14 10:54:07.279 17781-17941/? E/AndroidRuntime: FATAL EXCEPTION: Firebase-FirebasePush
    Process: org.mozilla.firefox, PID: 17781
    java.lang.IllegalStateException: You need to call initialize() on your Push instance from Application.onCreate().
        at mozilla.components.concept.push.PushProcessor$Companion.getRequireInstance(PushProcessor.kt:1)
        at org.mozilla.fenix.components.FirebasePush.onMessageReceived(FirebasePush.kt:9)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:175)
        at com.google.firebase.iid.zzg.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:764)
2019-11-14 10:54:07.280 17781-17941/? I/mozac/CrashReporter: Received crash: UncaughtExceptionCrash(throwable=java.lang.IllegalStateException: You need to call initialize() on your Push instance from Application.onCreate()., breadcrumbs=[Breadcrumb(message=Changing to fragment homeFragment, isCustomTab: false, data={}, category=DestinationChanged, level=INFO, type=DEFAULT, date=Thu Nov 14 10:53:58 GMT+02:00 2019)])
```

**Comment by grigoryk** [comment]
There's definitely another startup crash here, which I can reproduce locally - and we've seen it in Sentry. I will use this bug as a placeholder for that crash.

```
                         E  java.lang.RuntimeException: Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.IllegalStateException: Unrecognized migration type: Mig
                            ration$FxA
                         E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
                         E      at android.app.ActivityThread.-wrap1(Unknown Source:0)
                         E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                         E      at android.os.Handler.dispatchMessage(Handler.java:106)
                         E      at android.os.Looper.loop(Looper.java:164)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6494)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                         E  Caused by: java.lang.IllegalStateException: Unrecognized migration type: Migration$FxA
                         E      at mozilla.components.support.migration.MigrationResultsStore.fromJSON(MigrationResultsStore.kt:12)
                         E      at mozilla.components.support.base.utils.SharedPreferencesCache.getCached(SharedPreferencesCache.kt:2)
                         E      at mozilla.components.support.migration.FennecMigrator.migrateAsync(FennecMigrator.kt:3)
                         E      at org.mozilla.fenix.MigratingFenixApplication.setupApplication(MigratingFenixApplication.kt:144)
                         E      at org.mozilla.fenix.MigratingFenixApplication.onCreate(MigratingFenixApplication.kt:2)
                         E      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
                         E      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
                         E      ... 8 more
    mozac/CrashReporter  I  Received crash: UncaughtExceptionCrash(throwable=java.lang.RuntimeException: Unable to create application org.mozilla.fenix.MigratingFenixApplication: java.lang.Illega
                            lStateException: Unrecognized migration type: Migration$FxA, breadcrumbs=[])
```

**Comment by ebalazs-sv** [comment]
@grigoryk Hello!
This is still reproducible on Fenix Nightly 191121 GV 71, build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration, with Google Pixel (Android Q), Google Pixel 2 (Android 9), Huawei Honor 8 (Android 7.0).
[2ndstartupcrash.txt](https://github.com/mozilla-mobile/android-components/files/3879422/2ndstartupcrash.txt)
[Video](https://drive.google.com/file/d/158dQp7_pIunLk3gMF2HGL9nuu77RTEYz/view?usp=sharing)

**Comment by pocmo** [comment]
Re-opening, but I think the patch just may not have made it into the fenix build yet. @grigoryk?

**Comment by ebalazs-sv** [comment]
This is reproducible on today's build, Nightly 191125 GV 71, with Google Pixel 2 (Android 9), Nexus 6P (Android 8.1.0), Huawei Honor 8 (Android 7.0).

**Comment by grigoryk** [comment]
Reading through the log, I see a successful migration - the original problem isn't there.

Both logs have the same crash at the start, which is a new issue I haven't seen yet:

```
2019-11-25 10:36:16.196 17918-18174/? E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
    Process: org.mozilla.firefox, PID: 17918
    java.util.NoSuchElementException: Array contains no element matching the predicate.
        at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invokeSuspend(AutoPushFeature.kt:27)
        at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invoke(Unknown Source:10)
        at mozilla.components.feature.push.AutoPushFeatureKt$launchAndTry$1.invokeSuspend(AutoPushFeature.kt:5)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by grigoryk** [comment]
Seems like the same problem reported in https://github.com/mozilla-mobile/android-components/issues/5134

**Comment by pocmo** [comment]
@grigoryk So this issue can be closed again?

**Comment by jonalmeida** [comment]
I think we need to talk about push migration soon. :)

> 2019-11-25 10:36:16.196 17918-18174/? E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
>     Process: org.mozilla.firefox, PID: 17918
>     java.util.NoSuchElementException: Array contains no element matching the predicate.
>         at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invokeSuspend(AutoPushFeature.kt:27)
>         at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invoke(Unknown Source:10)
>         at mozilla.components.feature.push.AutoPushFeatureKt$launchAndTry$1.invokeSuspend(AutoPushFeature.kt:5)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
>         at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:15)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)

These logs don't make much sense. 

The `NoSuchElementException` is thrown [here](https://searchfox.org/mozilla-mobile/source/android-components/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#382), which iterates through the enum `PushType` that compares the UUID from the message received (from autopush servers) to the UUID of the enum value (which is a [deterministic UUID value](https://searchfox.org/mozilla-mobile/source/android-components/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#366) right now).

My guess is, we've somehow migrated from Fennec, received a push message with a Fennec chid which doesn't match our services chid (e.g. when we get a new service token from FxA, wouldn't that count as a new device registration which triggers a push message immediately to be sent? See https://github.com/mozilla/application-services/issues/2282).

I'm not sure how else we could have a received a message for a subscriber that never existed otherwise.

**Comment by grigoryk** [comment]
> My guess is, we've somehow migrated from Fennec, received a push message with a Fennec chid which doesn't match our services chid (e.g. when we get a new service token from FxA, wouldn't that count as a new device registration which triggers a push message immediately to be sent? See mozilla/application-services#2282).

This sounds very likely. `serviceForChannelId` needs to be more defensive.

**Comment by grigoryk** [comment]
https://github.com/mozilla-mobile/android-components/pull/5232 landed, which should improve the situation somewhat.

But we still need https://github.com/mozilla-mobile/fenix/issues/6954 in place to stop crashing - or to just disable push support on fennecProduction* fenix builds until that's in place.

**Comment by ebalazs-sv** [comment]
Hi! I retested this on today's build 12/9, with 
- Google Pixel 2 (Android 9) - ARM64;
- Nexus 6P (Android 8.1.0) - ARM;
- Xiaomi Mi Pad 2 (Android 5.1) - x86 

and Fenix does not crash anymore after startup.

**Comment by ebalazs-sv** [comment]
This is verified as fixed on Fenix Release migration build 12/11 also with the devices:
- Samsung Galaxy S8 (Android 9) - ARM64;
- Huawei Honor 8 (Android 7.0) - ARM;
- Xiaomi Mi4i (Android 5.0.2).
@grigoryk The two issues mentioned in your last comment, are fixed now, and the start-up crash is not reproducible. Can this issue be moved at Done?

**Comment by ebalazs-sv** [comment]
This is verified as fixed, see previous comments. 
I will mark this as Done. Thanks!
