### ISSUE TITLE
[Bug] Downloading files overrides older versions of that file

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#5046]
## Steps to reproduce
1. Navigate to www.thinkbroadband.com/download
2. Click to download any file (let's say 5mb, because it's faster)
3. Wait until it has downloaded
4. Click to download that file again

### Expected behavior
The download popup should display the name followed by the number of same files. Example: 5mb (1)
Also in the download folder, it should display the file followed by the number in parenthesis, and not override the same file with each download

### Actual behavior
The download popup shows the same name, regardless of how many times you download. Also, every time you download the file, it overrides the file with the same name in the Downloads folder

* Fenix version: 
• Develop from 13/11

### Notes
[Video with issue](https://drive.google.com/file/d/10ANoROFo7GooE1OUno5FGLz9jqWJsBgQ/view?usp=sharing)

**Comment by pocmo** [comment]
CC @sblatz

**Comment by sblatz** [comment]
This bug has been fixed in AC (as evidenced by this not being broken in Sample Browser); I believe this is only happening because Fenix is on an old Snapshot because they're not being published right now 😕

**Comment by sblatz** [comment]
I'm going to close this as it's not happening on master in AC: 
![demo](https://user-images.githubusercontent.com/4400286/68786992-8da8d580-05f5-11ea-99eb-12877ca39001.gif)

Please re-open once we get the new build if it's still happening.

**Comment by BranescuMihai** [comment]
@sblatz I reopened it because I pulled the latest AC, and it seems that from all types of files I tried to download, only for those apks it works, for pdfs and zips it doesn't.

**For however picks this up, some helpful points.**

I looked into it a little bit, turns out there is a method in DownloadsFeature.kt called uniqueFileName() which should handle the file versioning correctly.
However, this method is called sometimes on a null filename, because the DownloadState created in the EngineObserver.onExternalResource() returns null for some files. 

As a side note, both **DownloadDialogFragment.setDownload()** and **DownloadState.withResponse()** try to re-compute the filename received from gecko using **DownloadUtils.guessFileName()**, which make me think they are quick fixes exactly for this specific problem, when the filename was null. However in these two places they don't use **DownloadsFeature.uniqueFileName()**, which leads to this bug.

So my conclusion is probably the problem is somewhere in Gecko

**Comment by sblatz** [comment]
@cpeterso does it make sense that this would be GV related?

**Comment by sblatz** [comment]
I bet we need to call `uniqueFileName()` inside of `guessFileName()`

**Comment by sv-ohorvath** [comment]
@sblatz FYI: I'm seeing 3 different behaviors on 3 different devices:
Pixel 3 (Android 10): files are saved as file(1), file(2).
Samsung Galaxy S8 (Android 9), Sony Xperia Z5 (Android 7.1.1): the file is overwritten, so there are no duplicates.
Nexus 5 & HTC Desire 820 (Android 6.0.1): the files are duplicated, saved with the same filename, no (1) added.
