### ISSUE TITLE
Component Idea: Crash reporting (Sentry / Socorro)

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#506]
In Firefox for iOS we have a small wrapper around Sentry. Not super big but enough to add some more functionality.

* it will check the build you are on
* it will grab the Sentry DSN from a standard place
* it makes sure to not enable it when running in the simulator
* it implements its own device id generation to avoid a sticky ID

See also https://github.com/mozilla-mobile/firefox-ios/blob/master/Shared/SentryIntegration.swift

**Comment by pocmo** [comment]
I'll turn this into a more generic crash reporter component: The integration of GeckoView (and reporting crashes in native code) introduce some new issues that we may be able to work around with a component.

**Comment by pocmo** [comment]
Summary / Notes from @cpeterso:
https://docs.google.com/document/d/1aZUSOMjUUm1_v7oLCL4SrCvGdNhU-7x7CzrRNx8oYto/edit?ts=5b6ddc66#heading=h.l3xul066671j

**Comment by pocmo** [comment]
Crash handling API in GeckoView: https://bugzilla.mozilla.org/show_bug.cgi?id=1483329
