### ISSUE TITLE
IllegalStateException in FennecMigrator$runMigrationsAsync

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5063]
Three different stacktraces with multiple reports:

https://crash-stats.mozilla.com/report/index/c2929c40-54fa-4140-8e99-93bad0191112

https://crash-stats.mozilla.com/report/index/6935abd3-27e1-4805-9f7b-dc39c0191112

https://crash-stats.mozilla.com/report/index/881be396-038a-49f2-aa99-3121b0191112

**Comment by pocmo** [comment]
Exceptions happening in different lines:
* at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:36)
* at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:15)
* at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:26)

**Comment by grigoryk** [comment]
... and all of those line numbers are wrong :( That's annoying.

Socorro doesn't display exception's message, either. But Sentry has them:
- `FennecMigrator.kt:15` is `Missing DB path during history migration` (https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/6625642/events/34946314/)
- `FennecMigration.kt:26` is `Missing DB path during bookmark migration` (https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/6625642/events/34946313/)
- `FennecMigration.kt:36` is `Missing Profile path` (https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/6625642/events/34946312/)

**Comment by grigoryk** [comment]
`missing DB path` ones would be explained by the `missing profile path` exception (`dbPath = profile?.let { ... }` - so, `profile` is `null`.

`findDefaultProfile` can return `null` in two cases: IOException from `findProfiles`, or `profiles.isEmpty()`.

Latter is a legit case (fresh install of `fennecProduction`), so we should make sure to not log these errors in that case. I bet this is where most of these exceptions are coming from.

Otherwise, we're hitting some IO exception, and will need to land more detailed probes to make progress here (unless we can get a failing profile to run this against).

**Comment by grigoryk** [comment]
Speaking of Socorro not displaying exception's messages - if we can't fix that, let's just switch to using explicit exception classes for all the things that we're logging via crashReporter. That will make our lives easier. @pocmo thoughts?

**Comment by ebalazs-sv** [comment]
Starting with the 22nd of November, there are no more reports containing these stacktraces:
[search1](https://crash-stats.mozilla.com/search/?signature=%3D%5BINFO%5D%20java.lang.IllegalStateException%3A%20at%20mozilla.components.support.migration.FennecMigrator%24runMigrationsAsync%241.invokeSuspend%28FennecMigrator.kt%3A26%29&product=Fenix&date=%3E%3D2019-11-22T13%3A54%3A00.000Z&date=%3C2019-11-25T13%3A54%3A00.000Z&_facets=signature&page=1&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature)
[search2](https://crash-stats.mozilla.com/search/?signature=%3D%5BINFO%5D%20java.lang.IllegalStateException%3A%20at%20mozilla.components.support.migration.FennecMigrator%24runMigrationsAsync%241.invokeSuspend%28FennecMigrator.kt%3A36%29&product=Fenix&date=%3E%3D2019-11-22T13%3A56%3A00.000Z&date=%3C2019-11-25T13%3A56%3A00.000Z&_facets=signature&page=1&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature)
[search3](https://crash-stats.mozilla.com/search/?signature=%3D%5BINFO%5D%20java.lang.IllegalStateException%3A%20at%20mozilla.components.support.migration.FennecMigrator%24runMigrationsAsync%241.invokeSuspend%28FennecMigrator.kt%3A15%29&product=Fenix&date=%3E%3D2019-11-22T13%3A57%3A00.000Z&date=%3C2019-11-25T13%3A57%3A00.000Z&_facets=signature&page=1&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature)
I will mark this as Done. Thanks!
