### ISSUE TITLE
Support more necessary hooks via cron.yml taskgraph.

### ISSUE THREAD

**Issue by Callek** [mozilla-mobile/android-components#5069]
Multiple hooks that android-components uses from taskcluster should be defined via cron.yml rather than using custom logic in the taskcluster hooks service

**Comment by Callek** [comment]
This came out of the change https://phabricator.services.mozilla.com/D52449 where we created these hooks manually

**Comment by Callek** [comment]
@MihaiTabara @JohanLorenzo - Just as an FYI - feel free to close this if no longer needed/wanted.

**Comment by MihaiTabara** [comment]
> @MihaiTabara @JohanLorenzo - Just as an FYI - feel free to close this if no longer needed/wanted.

Thanks for resurfacing it, I just mentioned this a couple days ago in an AC bug! Will add it to the backlog.

**Comment by JohanLorenzo** [comment]
I'm taking this issue. I don't think it'll take too much time to solve and it will be less of a surprise to our future selves. I was surprised when I couldn't find when the "bump geckoview" hooks were scheduled, yesterday.
