### ISSUE TITLE
Component idea: Adjust Wrapper

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#507]
We have code in Focus and Fennec to deal with Adjust, which could probably become a component:

  https://github.com/mozilla-mobile/focus-android/blob/master/app/src/focusRelease/java/org/mozilla/focus/utils/AdjustHelper.java

On iOS we even have some more logic in there since the usage there used to be more restricted:

  https://github.com/mozilla-mobile/firefox-ios/blob/0f8e4df0377d1995cb06f78228edd7c0ef1a56f1/Client/Application/AdjustIntegration.swift

I think the nice thing of having this in a component is also that it is easier to keep up to date with the Adjust SDK. Sometimes they introduce breaking changes, which are nice to have to deal with in just one place.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4392)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794672

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
