### ISSUE TITLE
Use `hasUserGesture` in Release GeckoEngineSession

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#5074]
When Android Component GeckoEngineSession release uses v72 of GeckoView, integrate the changes in https://github.com/mozilla-mobile/android-components/issues/3857 to release.

**Comment by pocmo** [comment]
You do not need to do this.

When GeckoView versions move up a channel then we also in move our code up. So for example code you land in `browser-engine-gecko-nightly` using GV Nightly 72 today, will get copied over to `browser-engine-gecko-beta` once GV Beta becomes 72.

More about this here:
Currently its in GV v72. We're not using that version in Beta. Do you want me to update GV version in Beta?
