### ISSUE TITLE
AddOnCollectionProvider.getAddOnIconBitmap to use diskCache

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#5075]
Similarly to `AddOnCollectionProvider.getAvailableAddOns`

**Comment by pocmo** [comment]
Note that by default `useCaches` is `true` on `Request` and your icon may come from Gecko's cache.

**Comment by psymoon** [comment]
Confirmed the icon comes from Gecko's file cache on `Request`.
