### ISSUE TITLE
Make `onDownloadCompleted` name more accurate

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#5077]
As seen in https://github.com/mozilla-mobile/fenix/issues/6434#issuecomment-554288688, this name can be confusing since `onDownloadCompleted` gets called even when a download is simply paused. 

Perhaps we should say something like `onDownloadStreamClosed`

**Comment by pocmo** [comment]
`onDownloadStopped` may be a neutral option too.
