### ISSUE TITLE
Adding a URL shortner would be helpfull

### ISSUE THREAD

**Issue by shikhart98** [mozilla-mobile/android-components#509]
Adding URL shorter in the options menu in URL bar would be a great idea. 
If you like this idea I would like to assign this to myself.

**Comment by shikhart98** [comment]
@pocmo Can I start working on it or does it require any other permission?

**Comment by pocmo** [comment]
@shikhart98 Yes, if this is a feature request for Focus then please file it there too - it will need to get prioritized and product/ux need to make a decision on whether that's something to ship. Some of the code may still land in this repository here so that it can be used by our other apps too.

**Comment by shikhart98** [comment]
@pocmo  Sure :)

**Comment by pocmo** [comment]
Looking through old issues and closing them if they are not applicable anymore.

There's currently no need for this.
