### ISSUE TITLE
Sanitize exceptions for PII before submitting them via CrashReporter

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5095]
We're seeing some PII leaking into Sentry in form of exception messages. This issue tracks sanitizing our exceptions to remove any PII prior to submission.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4416)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792914

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
