### ISSUE TITLE
Add Site Domain for Autofill to AuthenticationDialogFragment in feature-prompts

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#5097]
Currently the Fenix chrome in `AuthenticationDialogFragment` doesn't know anything about the website underneath, and thus shows only app ID related password autofill suggestions (ie shows only suggestions related to mozilla.org or firefox for every dialog). 

## Steps to reproduce
Using device with 3rd party password manager installed and logged in (Lastpass, Lockwise, etc).
Open `https://jigsaw.w3.org/HTTP/Basic/` in Samples Browser/Fenix/RB

### Expected behavior
Any saved credentials for the `w3.org` website should be shown

### Actual behavior
Saved credentials for `mozilla.org` are shown

See: https://github.com/mozilla-mobile/fenix/issues/4205

In theory we should follow @jhugman 's suggestion there to add the domain to the dialog view so the system password manager's know what to fill.

> This is a missing feature of Fenix's BasicAuth dialog. Android triggers an autofill request when an `EditText` is entered, and guesses at the autofill `ViewStructure` that password managers will use.
> 
> The password managers use the package name to find the account to offer to autofill.
> 
> For browsers, it needs to add the [`webDomain` property](https://developer.android.com/reference/android/view/ViewStructure#setWebDomain(java.lang.String)) for page specific text boxes. GeckoView is already doing this, so this is why it works in web content already, but not in Fenix's chrome.
> 
> You need to implement [`onProvideAutofillStructure`](https://developer.android.com/reference/android/view/View#onProvideAutofillStructure(android.view.ViewStructure,%20int)) on the dialog, and the set the [`webDomain` property](https://developer.android.com/reference/android/view/ViewStructure#setWebDomain(java.lang.String)).
> 
> This will fix the problem in all password managers, including Lockwise. Until then, it's impossible for them to know the correct hostname.
> 
> The Android doc [Optimize your app for autofill](https://developer.android.com/guide/topics/text/autofill-optimize) seems to be pretty comprehensive.

One caveat - I timeboxed this to a few hours and tried to make custom edit texts for the dialog that overrode `onProvideAutofillStructure` and set the domain passed into the dialog, and I couldn't get it to work.

**Comment by colintheshots** [comment]
I tried to get it working by setting a webDomain with onProvideAutofillStructure on every `View` or `ViewGroup` for the AuthenticationDialogFragment basically. I always get a notification that "LastPass was unable to Autofill this app." I also tried using the org.mozilla.firefox build variant with a release build, since that app id worked for Fennec to enabled Autofill.

I don't believe Fennec is using Digital Asset Links based upon its AndroidManifest.xml. It seems like LastPass would want DAL working though. I reached out to LastPass engineers to see if I could get any ideas on what might be missing still.

**Comment by rocketsroger** [comment]
Looks like `setWebDomain` works if I do it on the `EditText`.  However, could not test with LastPass because it refuse to autofill a debug browser.  Once this change in nightly I'll retest https://github.com/mozilla-mobile/fenix/issues/4205
