### ISSUE TITLE
Persist state machine's state

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5102]
Our account state machine's state is currently derived from scratch upon initialization, based on the state of our persisted account, and how the interaction with the server goes.

This has been mostly fine so far, but if the state is persisted, we can short-circuit into `AuthenticationProblem` state and prevent us from hitting the servers when we know for certain our interaction will result in 401 errors.

This is a follow-up to https://github.com/mozilla-mobile/android-components/issues./5050#issuecomment-555296800.

To deal with a case when we fail to reliably determine if we can recover or not from our auth problems (that's #3347), we may need to consider another state here - `MaybeAuthenticationProblem`, perhaps. In which case, we can avoid short-circuiting and go through the full state machine, to essentially "try again" and see if we can recover.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4422)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794212

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
