### ISSUE TITLE
Migrate client's telemetry ID and profile creation date

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5114]
We want to fish these out from Fennec and add them into Fenix's core ping as additional fields. This will let associate Fennec's telemetry w/ Fenix telemetry for the same user.

Details TBD.

**Comment by magorlick** [comment]
This ticket says that you are adding to the core ping, however there isn't a core ping in Fenix GLEAN telemetry.  Do you know what ping we plan on using (metrics, baseline, events, custom...)?  This work is a need to have if we want to untangle continuing Fennec users from other Fenix users across the Transition.  I would like to template some code for our analysis so we will be ready at launch.

**Comment by magorlick** [comment]
Just to capture our slack discussion - it sounds like the custom ping we are making to monitor the data migration is a good candidate for inclusion of the fennec client_id and the fenix client_id.  Including both ids here will allow us to map continuing users and will not persist the fennec client_id in other telemetry moving forward.

**Comment by grigoryk** [comment]
👍 Thank you for documenting this here. If that works for you (including these bits of data in the migration ping), that's what we'll do.

**Comment by fbertsch** [comment]
Just confirming from Stefan's email, this is indeed what we want.

**Comment by magorlick** [comment]
@grigoryk Can you help me understand when we fire this telemetry? Does this only fire after the data has successfully migrated or does it indicate an attempt at data migration or simply indicate someone has installed Fenix?  Something else?  Thanks!

**Comment by abodea** [comment]
Hello @grigoryk, I tried to test this on the Fennec-Fenix migrations builds.

I was able to find the id on Fennec by accessing `about:telemetry`, after that I updated to Fenix migration build and I triggered a `baseline ping` where I can see the `Client_id` but they didn't match.
Note that I verified in logcat and glean dashboard for the `Client_Id` but I couldn't find something that matches the telemetry id from Fennec.

Will there be a new extra field for the `migration_telemetry_id`? If yes where it will be displayed so I can compare the Fennec-Fenix telemetry ids?
![Screenshot_20200115-101907 (1)](https://user-images.githubusercontent.com/42831109/72421658-9353a080-3789-11ea-831e-18769b39ea6e.png)

Also, Is this ready for QA, I'm asking because I didn't saw any patch regarding this issue.
If my test method is not the right one, please let us know how we should test this issue.

**Comment by st3fan** [comment]
@grigoryk can probably confirm but I am fairly sure that we are not including the fennec client id in this ping, but in the migration ping instead.

**Comment by grigoryk** [comment]
@st3fan that's correct, it's under `migration` ping, listed as `migration.telemetry_identifiers.fennec_client_id`. The other relevant item to this ticket is `migration.telemetry_identifiers.fennec_profile_creation_date`

**Comment by grigoryk** [comment]
This was done in https://github.com/mozilla-mobile/android-components/pull/5483.

**Comment by AndiAJ** [comment]
Hi, I've just re-tested the above mentioned matter using the bellow builds and devices:

<details>
    <summary> ✔️ Google Pixel XL (Android Q) ARM64 Fennec Nightly 68.5a1 ---> Fenix Nightly Build #2015717651</summary>
• Fennec launch date and time : **1/20/2020 01:53 PM** 

• Fennec client_id : **e411bf9d-bf99-45dc-a9b4-9730701ba674**

![rsz_screenshot_20200120-135458](https://user-images.githubusercontent.com/51314259/72733461-96db9300-3ba0-11ea-8107-b03b058fdfc5.png)

• Migration ping: **83a079f5-f3ed-4405-8af1-3ea8dc0baf6b**
```
2020-01-20 13:55:55.476 20127-20418/? D/glean/BaseUploader: Glean ping to URL: /submit/org-mozilla-fennec-aurora/migration/1/83a079f5-f3ed-4405-8af1-3ea8dc0baf6b
    {
      "client_info": {
        "android_sdk_version": "29",
        "app_build": "2015717651",
        "app_channel": "fennecNightly",
        "app_display_version": "Nightly 200117 18:00",
        "architecture": "arm64-v8a",
        "client_id": "0d1cc4c1-f00b-44ca-8baa-afa1ca466142",
        "device_manufacturer": "Google",
        "device_model": "Pixel XL",
        "first_run_date": "2020-01-20+02:00",
        "os": "Android",
        "os_version": "10",
        "telemetry_sdk_build": "24.0.0"
      },
      "metrics": {
        "datetime": {
          "migration.telemetry_identifiers.fennec_profile_creation_date": "2020-01-20T13:53:29.622+02:00"
        },
        "labeled_string": {
          "migration.migration_versions": {
            "telemetry_identifiers": "1"
          }
        },
        "uuid": {
          "migration.telemetry_identifiers.fennec_client_id": "e411bf9d-bf99-45dc-a9b4-9730701ba674"
        }
      },
      "ping_info": {
        "end_time": "2020-01-20T13:55+02:00",
        "ping_type": "migration",
        "seq": 7,
        "start_time": "2020-01-20T13:55+02:00"
      }
    }
2020-01-20 13:55:55.478 20127-20418/? D/glean/ConceptFetchHttpUploader: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fennec-aurora/migration/1/83a079f5-f3ed-4405-8af1-3ea8dc0baf6b
```

[Logcat](https://github.com/mozilla-mobile/android-components/files/4086585/A10ARM64.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2001000)

</details>

<details>
    <summary> ✔️ Samsung Galaxy Note 9 (Android 9) ARM64 Fennec Nightly 68.5a1 ---> Fenix Nightly Build #2015717651</summary>

• Fennec launch date and time : **1/20/2020 02:00 PM** 

• Fennec client_id : **134c387e-1d61-4a90-a0e3-887abdbfadb6**

![rsz_screenshot_20200120-140142_firefox_nightly](https://user-images.githubusercontent.com/51314259/72734099-cb038380-3ba1-11ea-9a0f-5e493a58cb85.jpg)

• Migration ping: **2d367c04-f65d-4405-b696-16e8cead8cd2**

```
2020-01-20 14:02:40.827 31217-31495/? D/glean/BaseUploader: Glean ping to URL: /submit/org-mozilla-fennec-aurora/migration/1/2d367c04-f65d-4405-b696-16e8cead8cd2
    {
      "client_info": {
        "android_sdk_version": "28",
        "app_build": "2015717651",
        "app_channel": "fennecNightly",
        "app_display_version": "Nightly 200117 18:00",
        "architecture": "arm64-v8a",
        "client_id": "84a26ce0-1669-4f07-81d1-4476c3c1c872",
        "device_manufacturer": "samsung",
        "device_model": "SM-N960F",
        "first_run_date": "2020-01-20+02:00",
        "os": "Android",
        "os_version": "9",
        "telemetry_sdk_build": "24.0.0"
      },
      "metrics": {
        "datetime": {
          "migration.telemetry_identifiers.fennec_profile_creation_date": "2020-01-20T14:00:01.931+02:00"
        },
        "labeled_string": {
          "migration.migration_versions": {
            "telemetry_identifiers": "1"
          }
        },
        "uuid": {
          "migration.telemetry_identifiers.fennec_client_id": "134c387e-1d61-4a90-a0e3-887abdbfadb6"
        }
      },
      "ping_info": {
        "end_time": "2020-01-20T14:02+02:00",
        "ping_type": "migration",
        "seq": 7,
        "start_time": "2020-01-20T14:02+02:00"
      }
    }
2020-01-20 14:02:40.829 31217-31495/? D/glean/ConceptFetchHttpUploader: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fennec-aurora/migration/1/2d367c04-f65d-4405-b696-16e8cead8cd2
```
[Logcat](https://github.com/mozilla-mobile/android-components/files/4086611/A9ARM64.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2001001)

</details>

<details>
    <summary> ✔️ Google Pixel 3a (Android 9.0) ARM Nightly 68.5a1 ---> Nightly Build #2015717649</summary>

• Fennec launch date and time : **T-10 (1/10/2020 09:00 AM)** 

• Fennec client_id : **3ca94426-cfbe-4edc-8f8f-c5be45843cb2**
![rsz_screenshot_20200110-090138](https://user-images.githubusercontent.com/51314259/72734719-fcc91a00-3ba2-11ea-9344-bc5c5c58128f.png)

• Fenix launch date and time : **T+3 (1/23/2020 08:00 AM)**

• Migration ping: **c0a70e72-2c68-49b6-b65b-e27a9114b67a**

```
2020-01-23 08:01:00.811 28969-29277/? D/glean/BaseUploader: Glean ping to URL: /submit/org-mozilla-fennec-aurora/migration/1/c0a70e72-2c68-49b6-b65b-e27a9114b67a
    {
      "client_info": {
        "android_sdk_version": "28",
        "app_build": "2015717649",
        "app_channel": "fennecNightly",
        "app_display_version": "Nightly 200117 18:00",
        "architecture": "arm64-v8a",
        "client_id": "91f8f741-7e66-463d-a526-f1775a0d4be5",
        "device_manufacturer": "Google",
        "device_model": "Pixel 3a",
        "first_run_date": "2020-01-23+02:00",
        "os": "Android",
        "os_version": "9",
        "telemetry_sdk_build": "24.0.0"
      },
      "metrics": {
        "datetime": {
          "migration.telemetry_identifiers.fennec_profile_creation_date": "2020-01-10T09:00:16.924+02:00"
        },
        "labeled_string": {
          "migration.migration_versions": {
            "telemetry_identifiers": "1"
          }
        },
        "uuid": {
          "migration.telemetry_identifiers.fennec_client_id": "3ca94426-cfbe-4edc-8f8f-c5be45843cb2"
        }
      },
      "ping_info": {
        "end_time": "2020-01-23T08:00+02:00",
        "ping_type": "migration",
        "seq": 7,
        "start_time": "2020-01-23T08:00+02:00"
      }
    }
2020-01-23 08:01:00.813 28969-29277/? D/glean/ConceptFetchHttpUploader: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fennec-aurora/migration/1/c0a70e72-2c68-49b6-b65b-e27a9114b67a
```
[Logcat](https://github.com/mozilla-mobile/android-components/files/4086645/A9ARM.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2001003)

</details>

<details>
    <summary> ✔️ Huawei Mate 20 Lite (Android 8.1.0) ARM Nightly 68.5a1 ---> Nightly Build #2015717649</summary>

• Fennec launch date and time : **T-3 (1/17/2020 06:00 AM)** 

• Fennec client_id : **91011fb8-9fdf-4a5c-af10-beb04e7555bb**
![rsz_screenshot_20200117-060212 (1)](https://user-images.githubusercontent.com/51314259/72735082-c770fc00-3ba3-11ea-93a2-d7bfa15c46eb.jpg)

• Fenix launch date and time : **T (1/20/2020 02:25 PM)**

• Migration ping: **8c34143d-5f84-4644-b876-f9ff26d5a428**
```

2020-01-20 14:28:18.372 32583-760/? D/glean/BaseUploader: Glean ping to URL: /submit/org-mozilla-fennec-aurora/migration/1/8c34143d-5f84-4644-b876-f9ff26d5a428
    {
      "client_info": {
        "android_sdk_version": "27",
        "app_build": "2015717649",
        "app_channel": "fennecNightly",
        "app_display_version": "Nightly 200117 18:00",
        "architecture": "arm64-v8a",
        "client_id": "94c7558d-58f5-4e11-b853-07d1783fd924",
        "device_manufacturer": "HUAWEI",
        "device_model": "SNE-LX1",
        "first_run_date": "2020-01-20+02:00",
        "os": "Android",
        "os_version": "8.1.0",
        "telemetry_sdk_build": "24.0.0"
      },
      "metrics": {
        "datetime": {
          "migration.telemetry_identifiers.fennec_profile_creation_date": "2020-01-17T06:00:19.393+02:00"
        },
        "labeled_string": {
          "migration.migration_versions": {
            "telemetry_identifiers": "1"
          }
        },
        "uuid": {
          "migration.telemetry_identifiers.fennec_client_id": "91011fb8-9fdf-4a5c-af10-beb04e7555bb"
        }
      },
      "ping_info": {
        "end_time": "2020-01-20T14:28+02:00",
        "ping_type": "migration",
        "seq": 7,
        "start_time": "2020-01-20T14:28+02:00"
      }
    }
2020-01-20 14:28:18.374 32583-760/? D/glean/ConceptFetchHttpUploader: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fennec-aurora/migration/1/8c34143d-5f84-4644-b876-f9ff26d5a428
```

[Logcat](https://github.com/mozilla-mobile/android-components/files/4086671/A8.1ARM.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2001002)

</details>

<details>
    <summary> ✔️ Samsung Glaxy S7 (Android 7.0) ARM Nightly 68.5a1 ---> Nightly Build #2015717649</summary>

• Fennec launch date and time : **T (1/20/2020 03:19 PM)** 

• Fennec client_id : **2a4310cf-cc2c-4e7f-aa26-e75bb4080741**
![rsz_screenshot_20200120-152101](https://user-images.githubusercontent.com/51314259/72735544-b1b00680-3ba4-11ea-829d-9ea91d43c122.png)


• Fenix launch date and time : **T+1 (1/21/2020 11:00 PM)**

• Migration ping: **6a939aac-6499-4523-b6a0-5f5b884da89e**
```

2020-01-21 23:01:08.789 20103-20493/? D/glean/BaseUploader: Glean ping to URL: /submit/org-mozilla-fennec-aurora/migration/1/6a939aac-6499-4523-b6a0-5f5b884da89e
    {
      "client_info": {
        "android_sdk_version": "24",
        "app_build": "2015717649",
        "app_channel": "fennecNightly",
        "app_display_version": "Nightly 200117 18:00",
        "architecture": "arm64-v8a",
        "client_id": "bb477157-2c03-45cc-abf8-04c0c6998fd7",
        "device_manufacturer": "samsung",
        "device_model": "SM-G930F",
        "first_run_date": "2020-01-21+02:00",
        "os": "Android",
        "os_version": "7.0",
        "telemetry_sdk_build": "24.0.0"
      },
      "metrics": {
        "datetime": {
          "migration.telemetry_identifiers.fennec_profile_creation_date": "2020-01-20T15:19:27.554+02:00"
        },
        "labeled_string": {
          "migration.migration_versions": {
            "telemetry_identifiers": "1"
          }
        },
        "uuid": {
          "migration.telemetry_identifiers.fennec_client_id": "2a4310cf-cc2c-4e7f-aa26-e75bb4080741"
        }
      },
      "ping_info": {
        "end_time": "2020-01-21T23:01+02:00",
        "ping_type": "migration",
        "seq": 7,
        "start_time": "2020-01-21T23:01+02:00"
      }
    }
2020-01-21 23:01:08.791 20103-20493/? D/glean/ConceptFetchHttpUploader: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fennec-aurora/migration/1/6a939aac-6499-4523-b6a0-5f5b884da89e
```

[Logcat](https://github.com/mozilla-mobile/android-components/files/4086687/A7ARM.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2001004)

</details>

<details>
    <summary> ✔️ OnePlus A3 (Android 6.0.1) ARM Nightly 68.5a1 ---> Nightly Build #2015717649</summary>
   
• Fennec launch date and time : **T-1 (1/19/2020 07:00 AM)** 

• Fennec client_id : **7c1b6763-b152-458a-919f-5e1955c30947**
![rsz_screenshot_20200119-070144](https://user-images.githubusercontent.com/51314259/72736110-c80a9200-3ba5-11ea-84f0-6630942eb97c.png)

• Fenix launch date and time : **T+1 (1/21/2020 07:00 AM)**

• Migration ping: **949802ff-8223-4b3a-b040-9d35e0290982**
```

01-21 07:00:41.812 12939-13251/? D/glean/BaseUploader: Glean ping to URL: /submit/org-mozilla-fennec-aurora/migration/1/949802ff-8223-4b3a-b040-9d35e0290982
    {
      "client_info": {
        "android_sdk_version": "23",
        "app_build": "2015717649",
        "app_channel": "fennecNightly",
        "app_display_version": "Nightly 200117 18:00",
        "architecture": "arm64-v8a",
        "client_id": "ae2f7ccb-978e-4a86-b35f-62ba60f278d5",
        "device_manufacturer": "OnePlus",
        "device_model": "ONEPLUS A3000",
        "first_run_date": "2020-01-21+02:00",
        "os": "Android",
        "os_version": "6.0.1",
        "telemetry_sdk_build": "24.0.0"
      },
      "metrics": {
        "datetime": {
          "migration.telemetry_identifiers.fennec_profile_creation_date": "2020-01-19T07:00:21.963+02:00"
        },
        "labeled_string": {
          "migration.migration_versions": {
            "telemetry_identifiers": "1"
          }
        },
        "uuid": {
          "migration.telemetry_identifiers.fennec_client_id": "7c1b6763-b152-458a-919f-5e1955c30947"
        }
      },
      "ping_info": {
        "end_time": "2020-01-21T07:00+02:00",
        "ping_type": "migration",
        "seq": 7,
        "start_time": "2020-01-21T07:00+02:00"
      }
    }
01-21 07:00:41.816 12939-13251/? D/glean/ConceptFetchHttpU: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fennec-aurora/migration/1/949802ff-8223-4b3a-b040-9d35e0290982
```
[Logcat](https://github.com/mozilla-mobile/android-components/files/4086736/A6ARM.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2001005)

</details>

<details>
    <summary> ✔️ LG Nexus 4 (Android 5.1.1) ARM Nightly 68.5a1 ---> Nightly Build #2015717649</summary>

• Fennec launch date and time : **T (1/20/2020 03:45 PM)** 

• Fennec client_id : **e9404766-268d-4615-b263-559e90e1dbc3**
![rsz_screenshot_2020-01-20-15-46-31](https://user-images.githubusercontent.com/51314259/72736517-862e1b80-3ba6-11ea-93a0-f052d5a89aa2.png)

• Fenix launch date and time : **T+3 (1/23/2020 05:30 PM)**

• Migration ping: **c3cb5368-84ea-4d06-9798-4dead3f0ae19**

```
01-23 17:32:19.480 13727-14092/? D/glean/BaseUploader: Glean ping to URL: /submit/org-mozilla-fennec-aurora/migration/1/c3cb5368-84ea-4d06-9798-4dead3f0ae19
    {
      "client_info": {
        "android_sdk_version": "22",
        "app_build": "2015717649",
        "app_channel": "fennecNightly",
        "app_display_version": "Nightly 200117 18:00",
        "architecture": "armeabi-v7a",
        "client_id": "5898a856-e69f-4c0a-aae2-f60748f35c95",
        "device_manufacturer": "LGE",
        "device_model": "Nexus 4",
        "first_run_date": "2020-01-23+02:00",
        "os": "Android",
        "os_version": "5.1.1",
        "telemetry_sdk_build": "24.0.0"
      },
      "metrics": {
        "datetime": {
          "migration.telemetry_identifiers.fennec_profile_creation_date": "2020-01-20T15:45:06.491+02:00"
        },
        "labeled_string": {
          "migration.migration_versions": {
            "telemetry_identifiers": "1"
          }
        },
        "uuid": {
          "migration.telemetry_identifiers.fennec_client_id": "e9404766-268d-4615-b263-559e90e1dbc3"
        }
      },
      "ping_info": {
        "end_time": "2020-01-23T17:32+02:00",
        "ping_type": "migration",
        "seq": 7,
        "start_time": "2020-01-23T17:32+02:00"
      }
    }
01-23 17:32:19.485 13727-14092/? D/glean/ConceptFetchHttpU: Submitting ping to: https://incoming.telemetry.mozilla.org/submit/org-mozilla-fennec-aurora/migration/1/c3cb5368-84ea-4d06-9798-4dead3f0ae19
```

[Logcat](https://github.com/mozilla-mobile/android-components/files/4086765/A5ARM.txt)
[Glean dahboard](https://debug-ping-preview.firebaseapp.com/pings/aj-test2001006)

</details>

Both **"migration.telemetry_identifiers.fennec_profile_creation_date"** and  **"migration.telemetry_identifiers.fennec_client_id"** are correctly generated in the migration ping.

For more info's please review the above drop-down's .
Based on this I'll close this ticket.

**Comment by ebalazs-sv** [comment]
This issue was verified in the previous comment, so I will move it to Done. Thanks!
