### ISSUE TITLE
Fennec migration: ability to detect that we're not in a migration scenario

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5115]
We need to be able to tell that we're not migration, and simply have a fresh Fenix install. This is particularly important to avoid displaying migration UI when it's not necessary, but will also benefit our startup times by avoiding doing unnecessary migration attempts.

**Comment by pocmo** [comment]
I'm building something similar already for the background service. Because I only want to run the service if we have actually migration work to do!

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Migration Build 7 on Google Pixel XL (Android Q) and Sony Xperia Z5 (Android 7).
