### ISSUE TITLE
WorkManagerSyncManager.getLastSynced doesn't return sync times for different accounts

### ISSUE THREAD

**Issue by keianhzo** [mozilla-mobile/android-components#5118]
After logging into a second account and before a sync has been completed, `getLastSynced`returns the previous account sync time. It seems that we are storing sync times in a common preference to all accounts:

```
fun getLastSynced(context: Context): Long {
    return context
        .getSharedPreferences(SYNC_STATE_PREFS_KEY, Context.MODE_PRIVATE)
        .getLong(SYNC_LAST_SYNCED_KEY, 0)
}
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4441)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796492

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
