### ISSUE TITLE
Pinned sites migration

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5126]
Now that Fenix is starting to work on Top Sites, we can feed it with migrated pinned sites.

This issue is a placeholder for figuring that out.

Currently, we get pinned sites back from the bookmarks migration.

**Comment by grigoryk** [comment]
Renamed this issue. We now have a distinct "pinned sites migration" API from appservices. Once Top Sites work lands, we will have a "sink" for migrating pinned sites.

**Comment by sv-ohorvath** [comment]
Verified pinned sites on migration build #8 and found no issues.
