### ISSUE TITLE
Downloading apk file is not recognized as Android application File

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#5132]
> From https://bugzilla.mozilla.org/show_bug.cgi?id=1598530

Downloading apk file is not recognized as Android application File.
The downloaded file cannot be executed.

STR:

download a .apk file
cannot executed .apk file

Source: https://dev-builds.libreoffice.org/daily/master/Android-ARM@24-Bytemark-Hosting/current/

**Comment by st3fan** [comment]
These files have a `~` in the filename and a `@` in the path. Maybe that is problematic?

**Comment by hakkikaancaliskan** [comment]
> These files have a `~` in the filename and a `@` in the path. Maybe that is problematic?

You can try with downloading [fenix from github](https://github.com/mozilla-mobile/fenix/releases). Same result without ~ and @.

**Comment by baffclan** [comment]
Can download a firefox_preview_v3.0.0-beta.1_arm64.apk, and can install it.
I try download a LibO-master apk file using firefox_preview_v3.0.0-beta.1 .
Can download, but cannot install...

**Comment by jonalmeida** [comment]
Looks like this is filed in Fenix already: https://github.com/mozilla-mobile/fenix/issues/4044

**Comment by jonalmeida** [comment]
I can reproduce this in r-b and it seems like we're probably not invoking the right intent for the installer.

From a brief inspection, the content type is correctly `"application/vnd.android.package-archive"` in the Download Service's [`openFile`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L493-L496).

The file path is also correct: `/storage/emulated/0/Download/install.apk`

**Comment by jonalmeida** [comment]
Comparing this [to Focus](https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/IntentUtils.kt#L135-L143) (where it works), I'm seeing the file path set with a `content` URI: `content://org.mozilla.focus.debug.fileprovider/Download/Download/install.apk`

I wonder if that makes a difference..

**Comment by jonalmeida** [comment]
The AndroidManifests were missing the relevant permission 🙃 :
```xml
<uses-permission-sdk-23 android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
```

**Comment by kbrosnan** [comment]
This opens up an attack vector for drive by malware. I understand that there are legitimate uses for wanting to launch APKs. We should be somewhat cautious about trusting applications that have been downloaded. Gecko/Desktop have a list of dangerous file types to warn the user about. https://searchfox.org/mozilla-central/source/xpcom/io/nsLocalFileCommon.cpp#23

**Comment by jonalmeida** [comment]
@kbrosnan hmm.. I initially thought this was a regression from Fennec behaviour, but it seems like Fennec doesn't handle opening APKs either. The notification delegates it to apps that can handle wildcard mime types `*/*` and those don't necessarily have the permissions to open APKs.

This was added a top bug to fix for Fenix so I imagine this is a conscious decision to change the behaviour.

We can revert it if we decide otherwise or want to change the behaviour to something else.
