### ISSUE TITLE
Provide mechanism to trigger Addon updates

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#5143]
GV will provide an `update` call on the web extension controller to check for updates for all installed addons, and automatically install them, if available. We should provide a mechanism to call this method e.g. when the device is idle or periodically in the background?

One complexity here is that the permissions of addons could have changed, requiring a new confirmation from the user. So, we'd have to display our permission confirmation dialog and have users confirm for every addon that has changed permissions. GV will provide a callback for that.

**Comment by csadilek** [comment]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1599581

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/android-components/commit/e2ac3d169f4dfc40400bd099096554b88a112c9d
