### ISSUE TITLE
"malformed" crash reports

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/android-components#5145]
The top crasher for Fenix in crash-stats is marked as "malformed"[1]. The crash reporter is probably doing something wrong with those types of crashes.

[1] https://crash-stats.mozilla.com/report/index/c7c343dd-5728-4c41-b0f0-13a5f0191125

**Comment by pocmo** [comment]
CC @rocketsroger 

Nominating for triage today.

**Comment by rocketsroger** [comment]
Reopen to monitor the issue

**Comment by rocketsroger** [comment]
From recent crashes looks like this is not related to the [INFO] tag.  From Sentry's side I can see some crashes that doesn't have a stacktrace.  
https://sentry.prod.mozaws.net/operations/fenix-nightly/issues/6758032/?query=is:unresolved

**Comment by rocketsroger** [comment]
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1607519.  Will monitor after fixed.

**Comment by rocketsroger** [comment]
Confirmed "malformed" crash reports are not on the "Top Crashers" list.  This is now fixed.
