### ISSUE TITLE
Get rid of NotificationIds

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5148]
I implemented `NotificationIds` and the extension method helpers, so that we could get a unique id for a `tag`. It turns out `NotificationManager` already has methods to additionally accept a tag: https://developer.android.com/reference/android/app/NotificationManager#notify(java.lang.String,%20int,%20android.app.Notification)

This means we could get rid of NotificationIds and the extension methods and use that directly.

**Comment by pocmo** [comment]
This existed since API 5 and I didn't know about it until @rocketsroger started using it. :)

**Comment by rocketsroger** [comment]
related issue to take a look at when removing `NotificationIds`
https://github.com/mozilla-mobile/android-components/issues/5375

**Comment by rocketsroger** [comment]
Have to add the cancel and notify extension functions for `NotificationManagerCompat` since Fenix is using it.
