### ISSUE TITLE
Improve FxaMigrationException error reporting

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5155]
Currently we loose details of the `cause` in FxaMigrationException when it's submitted to Sentry.

https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/6633797/?query=is:unresolved is a good example.

**Comment by ebalazs-sv** [comment]
Hi! I don't have access to Sentry to verify this issue. @kbrosnan Can you help with giving access to Sentry or should I skip this issue? Thanks!

**Comment by ebalazs-sv** [comment]
st3fan confirmed that we can move this to Done. Thanks!
