### ISSUE TITLE
Consider removing calls to `uniqueFileName` in `guessFileName`

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#5162]
Currently we're calling `uniqueFileName` in both the `useFileStream` and `guessFileName`. In **theory** we should only need it in one of these places. 

We should test on github.com (download releases), thinkbroadband.com, and saving an image to verify all cases are handled :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4483)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792946

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
