### ISSUE TITLE
Switch to published .aar for JNA

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#517]
There is in fact a published .aar that contains libjnidispatch for various supported architectures. Not sure how I missed that 🙈.

So, we can remove our Ivy config for fetching it and replace it with e.g:
`implementation 'net.java.dev.jna:jna:4.5.1@aar'`

**Comment by ncalexan** [comment]
I'm trying to integrate a sample application for the Rust logins API component we're building over in https://github.com/mozilla/application-services.  That app depends on the logins API and the FxA client library, and both of those depend on JNA.  I'm getting duplicate dex errors, like:
```
D8: Program type already present: com.sun.jna.CallbackParameterContext
```
I'm hoping that correctly labeling the Android dependency will allow the regular Maven/Gradle dependency resolution to determine that the underlying JNA classes.jar needs to be dexed only once.  Let us hope!

**Comment by ncalexan** [comment]
While I'm here, I'll link to Mentat's JNA configuration, which allows for unit testing with Robolectric and running on Android devices.  See https://github.com/mozilla/mentat/blob/f8478835a2052a0857f1052105676747fdd2cc6e/sdks/android/Mentat/library/build.gradle#L71-L92.

**Comment by pocmo** [comment]
#583 -> Follow-up?
