### ISSUE TITLE
Crash Reporter: Allow collecting crash metrics without confirmation in the crash prompt

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5174]
Our other products send crash statistics based on the telemetry setting. However in our case `GleanCrashReporterService` pretends to be a crash reporter and therefore only gets triggered if the user decides to send a crash report (and has telemetry enabled).

We should make it possible to trigger a service without showing the prompt first (for that particular service).

**Comment by Dexterp37** [comment]
Fly-by nit: this is not about sending `crash pings` as `lib-crash` does not send pings. It rather records data in `crash metrics` sent by the [metrics ping](https://mozilla.github.io/glean/book/user/pings/metrics.html). See the [data docs](https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/docs/metrics.md)

**Comment by pocmo** [comment]
Renamed!
