### ISSUE TITLE
Crash reporter: Allow to distinguish between main process and other process crashes.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5175]
To measure stability and compare with Fennec we want to know whether a crash happened in the main process (and therefore takes down the whole app) or whether it happened in another process (e.g. the content process).

**Comment by liuche** [comment]
@st3fan do you have thoughts on whether this and #5174 should be done by eng on AC or Fenix teams? I know we're going to talk about it soon as a group, so just want to make sure I add the right people from my team if needed.

**Comment by snorp** [comment]
Not sure if folks are aware or not, but GV delivers this in the crash service intent. https://searchfox.org/mozilla-central/source/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/ExampleCrashHandler.java#49

**Comment by liuche** [comment]
Happy to see you're working on this, @rocketsroger! could you give me an update on when we'd have this? I want to make sure we have enough time for Data Science to receive and process the data from here.

**Comment by rocketsroger** [comment]
> could you give me an update on when we'd have this?

Will do.  The pr is up but there's another pr that might affect this one.  I am waiting for the other pr to merge so I can continue working on this issue.  I'll update.  Thanks,
