### ISSUE TITLE
Add iconURL to ContentState

### ISSUE THREAD

**Issue by eoger** [mozilla-mobile/android-components#5179]
Synced tabs need to send the URL of the current favicon for a tab. `ContentState` has a `icon` field but it is a `Bitmap`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4501)

**Comment by liuche** [comment]
Hey @Vishwa-Mozilla is this something that you're still working on? if not, push a WIP PR so it's linked to this issue, and thanks for your help!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793192

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
