### ISSUE TITLE
Improve build speed

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#5188]
To improve the speed of our builds lets use the follow tips recommended by [this I/O talk](https://youtu.be/7ll-rkLCtyk), as an initial guideline.

- [ ] [Use the latest Android Studio Cradle plugin](https://youtu.be/7ll-rkLCtyk?t=261)
- [ ] [Avoid legacy multidex](https://youtu.be/7ll-rkLCtyk?t=370) 
- [ ] [Disable multi-APK for DEV builds](https://youtu.be/7ll-rkLCtyk?t=456)
- [ ] [Include minimal resources](https://youtu.be/7ll-rkLCtyk?t=578)
- [ ] [Disable png crunching](https://youtu.be/7ll-rkLCtyk?t=647)
- [ ] [Use instant run/Apply Changes](https://youtu.be/7ll-rkLCtyk?t=785)
- [ ] [Avoid inadvertent changes](https://youtu.be/7ll-rkLCtyk?t=931)
- [x] [Don't use dynamic versions](https://youtu.be/7ll-rkLCtyk?t=1077)
- [ ] [Watch the memory](https://youtu.be/7ll-rkLCtyk?t=1131)
- [x] [Enable Gradle cache](https://youtu.be/7ll-rkLCtyk?t=1187)

Other related issues: https://github.com/mozilla-mobile/android-components/issues/1290 https://github.com/mozilla-mobile/android-components/issues/2738

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4506)

**Comment by Amejia481** [comment]
if nothing of the above works (it's still slow 🐌 ) [let's try ✨](https://youtu.be/7ll-rkLCtyk?t=2024)

**Comment by Amejia481** [comment]
> - [ ] Use the latest Android Studio Cradle plugin
Related https://github.com/mozilla-mobile/android-components/pull/5181

**Comment by csadilek** [comment]
Closing as stalled and not actionable right now. We're making improvements and setting up a new repo. Can revisit after.
