### ISSUE TITLE
Add support for modifying WebView settings from EngineSession

### ISSUE THREAD

**Issue by carolkng** [mozilla-mobile/android-components#521]
Currently, the WebView inside the EngineSession is internal, so external applications can't modify the settings on it. I'm not sure how this is implemented in GeckoView.

The Firefox Accounts login page requires Javascript and DOM storage to be enabled, so in order to incorporate EngineView into the component, would it be possible to open up some public methods for those settings?

**Comment by carolkng** [comment]
(At the same time, it would probably be a huge hassle to write those public methods for _all_ the settings, since I'm not familiar with how similar the GeckoView and WebView settings API are)

**Comment by pocmo** [comment]
Is the goal to replace `WebView` with the/an abstract `engine` component?

**Comment by carolkng** [comment]
Yes, the idea is to be able to give an example of how to spawn a configurable Webview/Geckoview with the login page through the engine componeny

**Comment by pocmo** [comment]
Ah, got it! I'll move this into our next sprint and then we can see!
