### ISSUE TITLE
Handle multiple supported apps in app-links

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5216]
If we have multiple apps that support the same link, we should handle that case to choose between them. Right now, we show the default app chooser if there is more than one supported app, which contains other browsers as well.

In Fennec, this shows a custom app chooser that filters out non-browser apps. This might be a fair intermediate solution when clicking on the 'Open in App' use case option:
<img width="422" alt="Screen Shot 2019-12-02 at 1 36 39 PM" src="https://user-images.githubusercontent.com/1370580/69985300-ea1e5700-1508-11ea-9b11-bac29413bbd2.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4538)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793134

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
