### ISSUE TITLE
Use FxA.checkAuthorizationStatus() to check the auth status

### ISSUE THREAD

**Issue by eoger** [mozilla-mobile/android-components#5234]
Currently the implementation of `FirefoxAccount.checkAuthorizationStatusAsync` checks the auth status by trying to grab a token using `inner.getAccessToken()`:  https://github.com/mozilla-mobile/android-components/blob/1dcfb602ab301c5eacc6c26bc8cc092b56038ddb/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt#L186-L211

It is now possible to check for the authorization status directly by calling `inner.checkAuthorizationStatus()` now that https://github.com/mozilla/application-services/pull/2321 has landed.

cc @grigoryk

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4550)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795125

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
