### ISSUE TITLE
Investigate alternative solution to intercept load requests for AppLinksFeature

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#5243]
Current `AppLinksFeature` is a observer.  However, this is not the best design.  There are issues with the observer architecture that needs to be fixed.  Investigate into how this issue can be solved.

**Comment by rocketsroger** [comment]
@AmyYLee, Now with the new "Launch in App" from mozilla-mobile/fenix#4312, the user will be manually opting in to launch the site in third party app. Should we still keep the dialog in private mode that asks the user if they want to launch in app every time?

**Comment by AmyYLee** [comment]
> @AmyYLee, Now with the new "Launch in App" from [mozilla-mobile/fenix#4312](https://github.com/mozilla-mobile/fenix/issues/4312), the user will be manually opting in to launch the site in third party app. Should we still keep the dialog in private mode that asks the user if they want to launch in app every time?

@rocketsroger Hi, yes we should keep this dialogue in PBM even if the user opts to open links in app in non-private browsing mode. We shouldn't assume user intent is the same in PBM and this provides a stop gap in that scenario. We should also provide a checkbox option to remember the user's choice in PBM if they don't want to be asked every time. Thanks!
