### ISSUE TITLE
Prototype Addon integration in Fenix

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#5247]
We want to try and bring all our existing addon functionality to Fenix to verify everything will work as planned, and file follow-ups for the integration problems we find.

https://github.com/mozilla-mobile/android-components/issues/5354 (Add-on manager)
https://github.com/mozilla-mobile/android-components/issues/5355 (BrowserAction in ContextMenu)

**Comment by psymoon** [comment]
Initial add-on manager and web extensions integration boilerplate issues are in place, filed 
https://github.com/mozilla-mobile/android-components/issues/5354, https://github.com/mozilla-mobile/android-components/issues/5382, https://github.com/mozilla-mobile/android-components/issues/5382, https://github.com/mozilla-mobile/android-components/issues/5356, https://github.com/mozilla-mobile/android-components/issues/5374 as follow-ups
