### ISSUE TITLE
 Pasting/getting redirected to extremely-long data URI in the address bar will hang the UI

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/android-components#5249]
## Steps to reproduce
1. Launch sample-browser.
2. Open a website that redirects using a Data URI* (for an example, please refer to this test page I made when I was testing: https://github.com/MarcLeclair/DataURIStaticTestPage if you want to test using a data:application/json;base64 and get redirected) 
3. Click on the element that redirects to Data URI

OR

1. Launch sample-browser
2. paste long data URI* in the address bar ( keep in mind that copying something that's bigger than the allowed clipboard size might crash the application on an emulator). 

*: If you want to see noticeable lag, using a URL > 25k chars

### Expected behavior
The load time shouldn't be different 
### Actual behavior
The webpage loads in ~156 seconds when the data URI is extremely long (The example using my test webpage above  was 65k characters)
### Device information

* Android device: **Google Pixel 1(Android 10).** and **Moto G5 plus(Android 7)**

### Notes

It was loading all fine in Fennec because we actually limited the URL length in Browser.js  as seen here: 

 `let message = {
      [...]
      uri: truncate(fixedURI.displaySpec, MAX_URI_LENGTH),
     [...]
    };`

where the MAX_URI_LENGTH was 25000

This image below shows the stack call when loading the 65k character URL.
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/16614353/70356964-a8144e80-1843-11ea-9875-72c66b45e752.png">

I'd like to highlight a few  possible solutions:

1. We could cache the full URL and use `ellipsize()` from android to set the text in the TextView. However, to allow users to copy the  full URL (if the devices' clipboard allows it), the cache version can be copied to the clipboard by setting a `OnPrimaryClipChangedListener` on the edit state of the toolbar. 

2. Since the issue is the StaticLayout builder, we could do all the lifting on our own and try to work through the `breakstrategy` set by the layout itself. However, that's a lot of work for such a small edge case

I've also attached the trace as a zip if anyway is interested in seeing it. To open it, just open it with android studio after unzipping it.

[java-trace-sample-uri-motog5-dec4.trace.zip](https://github.com/mozilla-mobile/android-components/files/3934043/java-trace-sample-uri-motog5-dec4.trace.zip)

**Comment by espertus** [comment]
See also my bugzilla report. https://bugzilla.mozilla.org/show_bug.cgi?id=1598481

**Comment by csadilek** [comment]
Cause of: https://github.com/mozilla-mobile/fenix/issues/1824
