### ISSUE TITLE
Does Experiment need to be a data class?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#525]
Nowadays we override equals() and hashCode() in `Experiment`. Does it still need to be a data class? Are there other convenient things we get from a data class that we actually need?

https://kotlinlang.org/docs/reference/data-classes.html

**Comment by fercarcedo** [comment]
I think the only advantages we get from it being a data class are the `toString` (which might be useful for debugging) and the `componentN()` functions, which might be useful for someone using the library (although we don't use any of those internally). 

What do you think about it @pocmo?

**Comment by pocmo** [comment]
Okay, let's keep that! :)
