### ISSUE TITLE
Fennec migration: Start browsing button is not responding

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5261]
## Preconditions:
Have Firefox Release installed and logged in.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix;
3. Tap on the Start Browsing button from the Onboarding screen.
### Expected behavior
The Onboarding flow is dismissed and the Home screen is displayed.
### Actual behavior
The Onboarding screen is scrolled up, displaying the Firefox logo.
### Notes:
This is also reproducible after clearing data from the Android settings.
[Video](https://drive.google.com/file/d/15FKKhLzmKt7d65adYm68YIYThNAy5OKy/view)
### Device information

* Android device: Google Pixel 2 (Android 9) - ARM64; Nexus 6P (Android 8.1.0) - ARM; Xiaomi Mi Pad 2 (Android 5.1) - x86.
* Fenix version: Nightly 191209 GV 71

**Comment by pocmo** [comment]
I just saw that too and then realized I had a non-migration build installed. I wonder if that is happening for all Fenix versions (Nightly too?).

**Comment by ebalazs-sv** [comment]
This is not reproducible on Fenix Nightly 191205 with Google Pixel 2 (Android 9), Nexus 6P (Android 8.1.0), Xiaomi Mi Pad 2 (Android 5.1).

**Comment by ebalazs-sv** [comment]
I see that the same issue was opened here: https://github.com/mozilla-mobile/fenix/issues/7026 and its already fix. I will verify it on the migration builds as well and ad a comment with the results.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly 191210 GV 71, migration build, with Samsung Galaxy S8 (Android 9) - ARM64, Nexus 6P (Android 8.1.0) - ARM, Xiaomi Mi Pad 2 (Android 5.1) - x86.

**Comment by pocmo** [comment]
Great! :)

**Comment by ebalazs-sv** [comment]
Moving this to Done, since this is already verified.
