### ISSUE TITLE
Fennec migration: Migrate Telemetry opt-in status

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#5267]
Mirroring https://github.com/mozilla-mobile/fenix/issues/5525

When migrating from Fennec to Fenix we want to retain the telemetry setting.
Fenix uses a unified telemetry setting (like Firefox desktop), while Fennec still has two: `Firefox Health Report` and `Telemetry`.
`FHR` is considered a superset of `telemetry` and as such only this value will be used to set the telemetry status on Fenix.

**Comment by grigoryk** [comment]
This landed.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release, Beta, Nightly migration build 12/16 with Huawei Honor 8 (Android 7.0), Samsung Galaxy S8 (Android 9).
The Fennec "Firefox Health Report" setting Enabled/Disabled is migrated on Fenix Data Collection -> "Usage and technical data" as Enabled/Disabled.
I will move this to Done.
