### ISSUE TITLE
Expose GeckoSession#onFirstComposite

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5269]
Implement [`GeckoSession.ContentDelegate.onFirstComposite`](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/GeckoSession.ContentDelegate.html#onFirstComposite-org.mozilla.geckoview.GeckoSession-) for consumers that want to know when a first paint is complete.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4591)

**Comment by jonalmeida** [comment]
One of the criteria for [knowing when to sync tabs](https://searchfox.org/mozilla-central/source/services/sync/modules/engines/tabs.js#299) on desktop is [`pageshow`](https://developer.mozilla.org/en-US/docs/Web/API/Window/pageshow_event), which may be satisfied with this API.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796489

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
