### ISSUE TITLE
Sync Tabs: Observe store changes when any tab is done loading

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5271]
In the ~`SyncTabsFeature`~ [`SyncedTabsStorage`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt#L37) now, a native Rust call is invoked every time a tab state has changed and this causes a lot traffic taking place.

What we really want, is to get the full tab state when **any** open tab is done loading, and then sync.

I think we have most of that API available through the `BrowserStore` but I'm wondering if there is an easy way to observe changes to multiple tabs?

```kotlin
store.flowScoped { flow ->
  flow.ifChanged { 
    // If loading state changes for any tabs..
    it.tabs.any { !it.loading }
  }.collect { tabs ->
    // Take tabs.
  }
}
```

My understanding of the Flow API and our extension functions are a bit limited right now. @pocmo is this something that's possible today?

**Comment by MatthewTighe** [comment]
I'm not sure if this has changed since the OP, but the `RemoteTabsStorage` used by `SyncedTabsStorage` does not actually cause increased (network) traffic. Syncs are now handled by a separate component - a `SyncManager` which will sync what has been locally stored in the `RemoteTabsStorage`.

#11776 will reduce the number of writes to the local storage. I'm planning to add behavior to the patch that will allow for the ability to optionally sync on the appropriate state changes.

**Comment by jonalmeida** [comment]
We may need to double-check, but I think at one point we were calling syncNow after the tabs were stored because that store was in-memory only.

**Comment by MatthewTighe** [comment]
Interestingly, I can only see [history](https://github.com/mozilla-mobile/android-components/commits/main/components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt) for this file back a couple years, but the first visible commit doesn't seem to be the one that created the file. Did something happen that would cause us to lose history?

@grigoryk and I discussed this more offline, and it sounds like we'll move forward with syncing from within the `SyncedTabsStorage` as well. There'll be a couple more additions to the logic on when storing and syncing occur, including [debouncing](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/debounce.html) the flow collection to ensure we only use the latest values.

To anyone's knowledge, are we at a risk for race conditions if we `store` the tabs and then immediately initiate a `sync`?

**Comment by jonalmeida** [comment]
> Interestingly, I can only see [history](https://github.com/mozilla-mobile/android-components/commits/main/components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt) for this file back a couple years, but the first visible commit doesn't seem to be the one that created the file. Did something happen that would cause us to lose history?

It wasn't in this file, but part of the Sync Tabs mechanism - I could possibly be mis-remembering too, so I'll trust your investigation that ensured there is no added functionality there.

> To anyone's knowledge, are we at a risk for race conditions if we store the tabs and then immediately initiate a sync?

The only thing I can think about is to await for the `store` coroutine before initiating a sync.

**Comment by MatthewTighe** [comment]
Tabs will now be updated any time one finishes loading, is accessed, or the active tab is changed.
