### ISSUE TITLE
Sync Tabs: Rename RemoteTabsFeature to SyncTabsFeature

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5272]
"Remote" was an internal component name and probably shouldn't change the feature name.

Things to change:
 - `RemoteTabsFeature` -> `SyncedTabsFeature`.
 - `RemoteTabsStorageSuggestionProvider` -> `SyncedTabsStorageSuggestionProvider`.
 - `mozilla.components.feature.remotetabs` -> `mozilla.components.feature.syncedtabs`.
 - Component README.
 - Project README.

**Comment by jonalmeida** [comment]
This has potential for a good first bug, but will wait for comment from @eoger to see how they feel about this.

**Comment by eoger** [comment]
Minus nit would be `synced` versus `sync`, but yeah I'm ok with the rename!

**Comment by espertus** [comment]
I can do this.

**Comment by espertus** [comment]
@eoger @jonalmeida Should I also change `mozilla.appservices.remotetabs.RemoteTab` and `mozilla.components.browser.storage.sync.RemoteTabsStorage`?

**Comment by jonalmeida** [comment]
> `RemoteTab`

`mozilla.appservices.remotetabs` lives in the app services project, and the `RemoteTabsStorage` is the entry point for that dependency into the a-c FxaAccounts which is the naming convention that's followed there, so let's leave those as is. SyncTabs is the feature that it supports, which was my internal reasoning for renaming the feature (which I forgot to document). 🙂

**Comment by SubhrajyotiSen** [comment]
This issue can be closed since https://github.com/mozilla-mobile/android-components/commit/1ff8b84ec75d5dce4b46a5546477ca73d0395776
