### ISSUE TITLE
Fennec migration: about:home is restored in Open Tabs after reopening the app

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5278]
## Preconditions:
Have Firefox Beta/Nightly installed and logged in.
## Steps to reproduce
1. Replace Fennec Beta/Nightly with Fenix using a Beta/Nightly build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix and remove about:home from open tabs;
3. Close the app from Recent app and reopen it;
4. Observe the Open tabs section,
### Expected behavior
The Open tabs section is empty.
### Actual behavior
The about:home page is displayed in Open tabs.
### Notes:
[Video](https://drive.google.com/file/d/1DpHLjhuTQ1cyTXZA7FFuggOMDvmrfInh/view?usp=sharing)

### Device information

* Android device: Samsung Galaxy S8 (Android 9) - ARM64; Motorola Nexus 6 (Android 7.1.1); Xiaomi Mi Pad 2 (Android 5.1).
* Fenix version: Beta 12/10 GV 71; Nightly 191210 GV 72

**Comment by codrut-topliceanu** [comment]
@ebalazs-sv 
I'm unable to reproduce the issue. (Pixel 4 Android 10 & LG K4 Android 6)
Is the issue still present for you?

**Comment by pocmo** [comment]
I can still reproduce that (I think the key is that the tab needs to have more history than only `about:home` which will otherwise not kept by Fennec and therefore can't be restored) and will provide a patch.

**Comment by sflorean** [comment]
Verified as fixed on Fennec Nightly Migration build 8. about:home tabs are not migrated or displayed after migration. 
Devices: 
- Google Pixel 3 (Android Q)
- Nexus 6P (Android 8.1.0)
- Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture
