### ISSUE TITLE
Fennec migration: Beta/Nightly builds are crashing when opening a new tab

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5279]
## Preconditions:
Have Firefox Beta/Nightly installed and logged in.
## Steps to reproduce
1. Replace Fennec Beta/Nightly with Fenix using a Beta/Nightly build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix;
3. Open a new page or browse to a different page in the already imported tabs;
4. Observe the behavior;
### Expected behavior
The required page is loaded.
### Actual behavior
Fenix crashes.
### Notes:
[crashtab.txt](https://github.com/mozilla-mobile/android-components/files/3945449/crashtab.txt)

### Device information

* Android device: Samsung Galaxy S8 (Android 9) - ARM64; Motorola Nexus 6 (Android 7.1.1); Xiaomi Mi Pad 2 (Android 5.1).
* Fenix version: Beta 12/10 GV 71; Nightly 191210 GV 72

**Comment by st3fan** [comment]
@ebalazs-sv We still had this one in the beta migration backlog. Can we close this?

**Comment by ebalazs-sv** [comment]
This is not reproducible anymore in the latest Nightly migration build 7 and build 8.
I will close this. Thanks!
