### ISSUE TITLE
Expose LocaleManager clear() method

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#5280]
Related to [Fenix-220](https://github.com/mozilla-mobile/fenix/issues/220), we need to manually clear the locale storage when the user selected the default from the locale list (so the app will follow the system one)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4605)

**Comment by csadilek** [comment]
This landed back in https://github.com/mozilla-mobile/android-components/pull/5282.
