### ISSUE TITLE
Add Invisible State to Toolbars

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/android-components#534]
I ran into a use case where I needed a Toolbar.Action to be invisible to the user, but I did not want other Actions to change their layouts when it disappeared.  I would normally set its visibility to invisible to achieve this, but instead I was forced to hack around it by replacing it with an invisible placeholder.

Suggest to update toggleable Actions to accept paramater ```visibility: ()->Int``` instead of ```visibility: ()->Boolean``` to allow usage of View.INVISIBLE.

**Comment by Baron-Severin** [comment]
This work in progress PR shows my intended approach.

https://github.com/mozilla-mobile/android-components/pull/535

**Comment by pocmo** [comment]
Thanks for filing this.

I think I named this poorly by choosing `visible`. A better name may be `attach` or something similar. It controls whether this action should be part of the toolbar or not. It doesn't really control visibility.

I commented on the other project too: I think you can implement such a behavior by overriding `bind()` for your specific action and then setting the view to visible/invisible. `bind` should get called for every _attached_ action after invalidateActions() (like `visible`).

**Comment by Baron-Severin** [comment]
That solution seems to work well, thanks for the reply!  I'll close the PR.

**Comment by pocmo** [comment]
Ah great! :)
