### ISSUE TITLE
Web Extensions Fenix integration - BrowserAction in Menu

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#5355]
Similarly to `WebExtensionToolbarFeature`, Fenix mockup requires browser action exposure in context menu

**Comment by csadilek** [comment]
One more drive-by comment: Unlike the toolbar, I don't think the context menu needs to support live updates. So, this should be simpler. When opened, it should display the global browser action state with the tab-specific overrides of the selected session applied.
