### ISSUE TITLE
Web Extensions Fenix integration - Add-on installation

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#5356]
Need UI flow for add-on installation for fenix.

**Comment by csadilek** [comment]
I don't understand what is tracked by this issue. We already have the installation UI flow in A-C / Sample Browser and once that's integrated in Fenix, as tracked by both https://github.com/mozilla-mobile/android-components/issues/5374 and https://github.com/mozilla-mobile/android-components/issues/5247, what is left to do here? :)

@psymoon @Amejia481

**Comment by psymoon** [comment]
@csadilek breaking apart the integration pieces as incremental as possible for others to work on it

**Comment by csadilek** [comment]
@psymoon OK, makes sense, if this is about the *actual* integration work. The word "prototype" scared me a bit in all those new issues (let's rephrase?), because if all those are done, we should be good to land :)

![Alt Text](https://i.imgur.com/HoYp1cA.gif)

**Comment by psymoon** [comment]
Fixed in https://github.com/mozilla-mobile/fenix/commit/71a6b86cef713fa51e9b44baef9dd944d4d290d0
