### ISSUE TITLE
Detect self-hosting FxA/Sync configurations, do not auto-migrate FxA for these users

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5359]
For self-hosting users, we need to ensure we won't accidentally start uploading their data to our own storage servers (as will currently happen if user is using mozilla's FxA server but their own sync storage servers via tokenserver url config in Fennec).

Ideal version of this is https://github.com/mozilla-mobile/android-components/issues/5358 (full support for these users), but as Step 1, let's disable the FxA migration if we detect this scenario.

Related: https://github.com/mozilla-mobile/android-components/issues/3729

**Comment by LaurentiuApahideanSV** [comment]
@grigoryk Hello! Can you please provide steps to reproduce this? Thanks!

**Comment by st3fan** [comment]
The test plan for this roughly looks like this:

- Configure Fennec to use a custom server
- Migrate
- Check if Sync is unconfigured. We should not inherit the custom settings and instead have sync unconfigured and not syncing.

There are hints on https://mozilla-services.readthedocs.io/en/latest/howtos/run-fxa.html about how to configure Fennec to use a custom server. However, I am not sure what a good custom server would be. I _think_ we could probably test with our own FxA Staging setup.

**Comment by grigoryk** [comment]
As Stefan said above, the steps are:

- Configure fennec to use a self-hosting sync server: In Fennec's `about:config`, _before_ signing in (while there's no account present in Fennec), customize this value: `identity.sync.tokenserver.uri`. Simply adjusting the URL with some extra symbols should be enough.

- Migrate

- Verify that Sync isn't configured.

**Comment by rfk** [comment]
> I am not sure what a good custom server would be. I think we could probably test with our own FxA Staging setup.

Using stage for this sounds fine to me.

**Comment by ebalazs-sv** [comment]
@grigoryk Thanks for the detailed steps to reproduce.
I had tested this on Nighly Migration Build 02/27, Beta Migration Build 02/27 with Google Pixel 2 (Android 9) and LG G7 fit (Android 8.1) following the all 4 possible scenarios and the results are:
- FxA is not migrated and that sync is not configured in Fenix, when both or one of the specified values are customized by adding some extra symbols to the URL.
- FxA is migrated and the sync is on when the specified values are not customized.

The identity.sync.tokenserver.uri or identity.fxaccounts.auth.uri values are reset after migration.

I will move this to Done.
