### ISSUE TITLE
Fix AbstractCustomTabService API breaking change

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#5367]
In AbstractCustomTabService `extraCommand` should have a default implementation.

**Comment by rocketsroger** [comment]
This was introduced inadvertently in https://github.com/mozilla-mobile/android-components/issues/3963

**Comment by rocketsroger** [comment]
Not an issue anymore

**Comment by jonalmeida** [comment]
> Not an issue anymore

Why is no longer an issue? I can still see [r-b builds failing](https://firefox-ci-tc.services.mozilla.com/tasks/cL4rZkxzTsqFrWsnsLb7HA/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FcL4rZkxzTsqFrWsnsLb7HA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) from this API not being implemented.

**Comment by jonalmeida** [comment]
For the ticket, this was closed because it seems like there's a caching issue on TC that might be the cause of the r-b build not picking up the changes from https://github.com/mozilla-mobile/android-components/commit/08aac59e1e6fd0050e2428af2fcb2f51eacaaeea.
