### ISSUE TITLE
Batch download notifications into one notification or implement priority queue

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#5369]
In https://github.com/mozilla-mobile/android-components/pull/5285 we implemented a partial solution for handling Android's silent failure when too many notifications are sent in quick succession. 

Chrome does something pretty smart here by implementing a [priority queue](https://source.chromium.org/chromium/chromium/src/+/master:chrome/android/java/src/org/chromium/chrome/browser/download/SystemDownloadNotifier.java;l=28-30?hl=en&originalUrl=https:%2F%2Fcs.chromium.org%2F) so that notifications with PAUSE or RESUME are considered "high priority" and always processed. 

As discussed with @pocmo we could also just batch the downloads into a single notification to make managing them easier.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4639)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792945

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
