### ISSUE TITLE
Android Components Sticker - Jan 2020

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5370]
Sticker research ticket!

**Comment by jonalmeida** [comment]
@st3fan had a neat idea to make a "Mozilla Technology" sticker like the one below:

![Screen Shot 2019-12-19 at 2 21 14 PM](https://user-images.githubusercontent.com/1370580/71203148-7b146280-226b-11ea-9cfb-d41703d128e1.png)

**Comment by pocmo** [comment]
![rb](https://user-images.githubusercontent.com/89638/71248930-5cba6f80-231c-11ea-9775-c43e52152ad3.png)

**Comment by rocketsroger** [comment]
![ReferenceBrowserStickerJan2020](https://user-images.githubusercontent.com/6579541/72750478-f62ea880-3b8a-11ea-91c4-1df85d2bf3a9.png)

**Comment by rocketsroger** [comment]
Unfortunately the 🚢 has sailed for ordering the stickers.  Closing.
