### ISSUE TITLE
Web Extensions Fenix integration - Follow Fenix architecture

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#5374]
- [x] Using [the Navigation library](https://www.youtube.com/watch?v=JFGq0asqSuA) and [single activity model](https://youtu.be/2k8x8V77CrU)
- [x]  ~[Should] Move LEARN_MORE_URL in AddonPermissionsDetailsFragment into SupportUtils~
- [x]  [Should] Refactor the `rootView` naming to `view` in addon fragments to be consistent with Fenix
- [x]  [Could] Move constants into companion object
- [x]  ~[Needs Judgement Call] There is a potential use case for having an interactor and controller that revolves around the `addonManager` in AddonsManagementFragment and InstalledAddonDetailsFragment. We would need a main view that initializes the interactor and controller.
    - In AddonsManagementFragment, we would refactor the onClick code to call an interactor method and move `showPermissionDialog`, `showInstalledAddonDetailsFragment` and `showDetailsFragment` into the controller.
    - In InstalledAddonDetailsFragment, we would refactor the `switch.setOnCheckedChangeListener` and all the `setOnClickListener` code to call an interactor method~
- [x] Move AddonsAdapter in AddonsManagementFragment to A-C
- [x] Move PermissionsDialogFragment to A-C
- [x] Use Snackbar instead of Toasts
- [x] ~Make sure we open add-on UI as tab in correct mode (private|normal) or switch to a popup directly instead of using tabs~ Addressed in https://github.com/mozilla-mobile/android-components/issues/5572

**Comment by Amejia481** [comment]
> [Should] Refactor the rootView naming to view in addon fragments to be consistent with Fenix

https://github.com/mozilla-mobile/fenix/pull/7655

**Comment by gabrielluong** [comment]
Closing this issue as done.
