### ISSUE TITLE
AbstractFetchDownloadService.copyInChunks() creates new byte arra in loop

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5380]
I just saw that we create a new `ByteArray` for every read in `copyInChunks`. This is wasteful (memory and potentially performance). The idea of `InputStream.read(ByteArray)` is that you can reuse the same array. Let's just create it once before we loop.

https://github.com/mozilla-mobile/android-components/blob/2e5be4985c5304db274c2e7d54bd81deb5afd885/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L315-L328

**Comment by sblatz** [comment]
This will be fixed by https://github.com/mozilla-mobile/android-components/pull/5452

**Comment by csadilek** [comment]
Closed by https://github.com/mozilla-mobile/android-components/pull/5452.
