### ISSUE TITLE
Request: Smaller ripple radius on appbar items (and other places)

### ISSUE THREAD

**Issue by Poopooracoocoo** [mozilla-mobile/android-components#5388]
so um. Android 6 made it so that the ripple radius is small enough to fit in the app/action bar and obviously the touch target is not the same. Here's a screenshot of the current behaviour on Fenix Nightly on Android 10 with the toolbar set to the top. 
![image](https://user-images.githubusercontent.com/51363864/71303910-45aa7900-2413-11ea-8f2e-746141d3b665.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4649)

**Comment by Poopooracoocoo** [comment]
aaaannnnd i quickly realised that this is a bit problematic: 
![image](https://user-images.githubusercontent.com/51363864/71304169-01b97300-2417-11ea-9ed6-18334312eb5a.png)
here, only the (duplicate) back button could be highlighted but then the select all button (which there is an icon for in the Material Design library) would look really odd with a smaller radius:
![image](https://user-images.githubusercontent.com/51363864/71304209-b9e71b80-2417-11ea-914c-3da317c22f28.png)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795123

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
