### ISSUE TITLE
Kotlin: treat warnings as errors

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#54]
Kotlin 1.2 introduces a compiler flag to treat warnings as errors: https://kotlinlang.org/docs/reference/whatsnew12.html#warnings-as-errors

**Comment by pocmo** [comment]
From other projects I was expecting that something like this would do the trick:

```Groovy
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        allWarningsAsErrors = true
    }
}
```

However I still see the warnings for #39 and the build does not fail.

**Comment by mcomella** [comment]
@pocmo If you add that block inside of the `subprojects` block, it appears to work:
```kotlin
subprojects {
    tasks.withType(...
    ...
```

I think the reason for that is the base project doesn't have any tasks running with KotlinCompile but the subprojects, which are compiling Kotlin code, do.

**Comment by mcomella** [comment]
When I run this, I get the following errors:
```
gr assemblegeckonightlyx86debug
Local configuration: loaded local.properties
Local configuration: application-services substitution path missing. Specify it via 'substitutions.application-services.dir' setting.

> Task :tooling-lint:compileKotlin FAILED
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/mcomella/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.2.71/5470d1f752cd342edb77e1062bac07e838d2cea4/kotlin-stdlib-jdk8-1.2.71.jar (version 1.2)
    /Users/mcomella/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.21/d207ce2c9bcf17dc8e51bab4dbfdac4d013e7138/kotlin-stdlib-jdk7-1.3.21.jar (version 1.3)
    /Users/mcomella/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.2.0/4bbda3b5425aa38a9f6960468a29c5ef3e8a28c9/kotlin-reflect-1.2.0.jar (version 1.2)
    /Users/mcomella/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.21/4bcc2012b84840e19e1e28074284cac908be0295/kotlin-stdlib-1.3.21.jar (version 1.3)
    /Users/mcomella/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.21/f30e4a9897913e53d778f564110bafa1fef46643/kotlin-stdlib-common-1.3.21.jar (version 1.3)
w: Consider providing an explicit dependency on kotlin-reflect 1.3 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
e: warnings found and -Werror specified
```

We're apparently having some dependency version clashes that I'm not sure how to resolve, otherwise I might consider submitting a PR.

**Comment by pengrad** [comment]
Hi @mcomella, incompatible kotlin version comes with "26.2.1" version of lint
https://github.com/mozilla-mobile/android-components/blob/ab634b8a3efe503ae4be12f81d1a89dabccabf90/buildSrc/src/main/java/Dependencies.kt#L27

Update to `lint = 26.3.2` will solve it, but need to update gradle plugin as well.
Or temporarily exclude transitive kotlin dependency in `tooling-lint` module:
```
compileOnly(Dependencies.tools_lintapi) {
    exclude group: 'org.jetbrains.kotlin'
}
```
There will be more warnings after that, but hope it helps :)

**Comment by mcomella** [comment]
Thanks pengrad! I can confirm that I no longer see cryptic classpath errors when I upgrade the lint version but see other warnings. Maybe I'll timebox this...

**Comment by mcomella** [comment]
I decided to enable warnings as errors only the modules that don't have any warnings because I don't always know how we want to handle the errors: I'll leave that up to the components team.
