### ISSUE TITLE
GeckoEngine: WebExtensions startup after first page load

### ISSUE THREAD

**Issue by sammacbeth** [mozilla-mobile/android-components#5400]
When installing a webextension in an `Engine` (via `engine.installWebExtension`), the installation is does not happen until the first `Session` is created. As this process is lazy, extension installation is pushed back to the same time as the first URL is loaded by the session. This leads to a race condition between page load and extension startup. In my testing, (using fenix as a base), the extension always loses this race, and therefore will miss the first page load of the session.

Is it/would it be possible to block the start of page loading until extensions have been loaded.

**Comment by csadilek** [comment]
@sammacbeth Thanks for filing! This is very likely due the same problem described in https://bugzilla.mozilla.org/show_bug.cgi?id=1595176 (web extension background script wasn't running until a Session was created). So, worth checking again with the latest GeckoView Nightly or in a few days once Android Components is upgraded.

**Comment by sammacbeth** [comment]
Thanks for the quick response. This does sound like my use-case too, so hopefully this was fixed on nightly. I'll test it out and then update here.

**Comment by csadilek** [comment]
We haven't seen this since the GV bug above was fixed. Closing...please re-open if you're still experiencing problems.
