### ISSUE TITLE
Unit tests for AbstractFetchDownloadService

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5420]
AbstractFetchDownloadService only has 55% code coverage with new feature additions which is lower than current average (~80%).

Following the guide to generating a code coverage report will give more insight: https://mozac.org/contributing/code-coverage

cc: @sblatz

**Comment by sblatz** [comment]
Going to look at this in the next couple days :)

**Comment by jonalmeida** [comment]
Re-assigning to @R4md4c since they have a PR up already. :)
