### ISSUE TITLE
Notify user when previously unsupported addons become available

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#5434]
See: https://miro.com/app/board/o9J_kw8Lt8g=/?moveToWidget=3074457347099638860

During migration we disable unsupported addons. Once these addons become available we should notify the user and provide a simple UX flow for installation.

As a Fennec user migrated to Fenix, I want to know when my previously supported add-ons become available in product, and where to go to install them.

**Comment by vesta0** [comment]
@brampitoyo we discussed the user flow for when unsupported add-ons become available a couple of weeks ago and made the following decisions:

-Show users a notification that new add-ons are available
-The notification will link to the Add-ons Manager. Users see newly available add-ons there and will be able to install them (one by one, not multiple at once).

I believe the only outstanding task was to consult with Content Strategy to finalize strings such as 

"not yet supported add-ons" and
"One / Some of your add-ons are now available"

@brampitoyo if this is ready, please post the mocks here (just the mocks for this particular user story) so ENG can pick it up ASAP.

**Comment by brampitoyo** [comment]
@Amejia481 @csadilek

@betsymi and I had a meeting earlier today. Although our strings are not yet finalised – @betsymi will post them on this issue before the end of the week – we’ve decided on a few things to further simplify our notification system.

<img width="1680" alt="Screen Shot 2020-03-05 at 12 27 42 PM" src="https://user-images.githubusercontent.com/51007/75936667-ac561380-5ee7-11ea-870c-080ef1be2987.png">

1. To minimise interruption and distraction, we’ve decided not to show a snackbar or CFR bubble on the browser view. Just using the notification dot is enough.
2. Instead, we’ll show a CFR bubble inside the main menu. This is the first string that Betsy is working on.
    - If the user has zero add-ons, the main menu item doesn’t go through the submenu. It goes directly to Settings.
    - If the user has at least 1 add-ons installed, the main menu item will open the submenu. From here, the Add-ons Settings page can be reached easily
3. In the Add-ons Settings page, there’s a space for “Not yet supported” add-ons. This is the second string that will be posted on this issue.

**Comment by betsymi** [comment]
For system notification:

**New add-ons available**
Add [add-on name], [add-on name], and [add-on name] to Firefox.

**Comment by brampitoyo** [comment]
Really big thanks, @betsymi, for working on the strings!

We can now close this issue.

**Comment by Amejia481** [comment]
Re-opening as https://github.com/mozilla-mobile/android-components/pull/6123 hasn't landed yet
