### ISSUE TITLE
ReaderViewControlsBar should not unconditionally inflate

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#5436]
This is the A-C companion bug to fenix#4309.

The ReaderViewControlsBar unconditionally inflates, taking an extra 50ms on slower devices even on warm starts of Fenix from an external link. There is no reason this UI element needs to be visible immediately. It's infrequently used on any given session as it only appears when the reader view appearance button is pressed. Therefore, it makes sense to inflate this lazily only when needed. It certainly shouldn't delay our warm startup time from a link.

**Comment by jonalmeida** [comment]
@colintheshots we should try to re-use the InflationAwareFeature abstraction we created for FindInPage since that gives us a unified solution.

It might require a bit more work though to also address [Sebastian's comment](https://github.com/mozilla-mobile/android-components/pull/4664#pullrequestreview-298237945) here which seems reasonable.

**Comment by colintheshots** [comment]
@jonalmeida `ReaderViewControlBar` uses a merge tag layout and inflates itself. `ViewStub` has always been incompatible with merge tags. This means I'd have to add a wasteful, extra `ViewGroup` as a wrapper in order to use `ViewStub` here.

`InflationAwareFeature` is currently only available inside Fenix. This means any external users of readerview would pass need to pass a `ViewStub` into the feature that wouldn't get inflated unless they also wrote an `InflationAwareFeature` class.

It seems like the current PR here is closer to what Sebastian is suggesting. It was self-contained and relied on no external magic. It was only a small change, since the custom view was already inflating itself on instantiation.

I see why you would like a better, systemic fix for all of these cases though. We should have a clear means to lazily inflate features that doesn't rely upon the client implementing something so complex.

In the case of `ReaderViewControlsBar`, we don't want to inflate it when the feature starts, but only when the user presses the Appearance button. This can happen very seldom and very late, after the rest of the feature must be fully initialized and working. In this case, fragment lifecycle and the feature starting are completely disconnected from the instant when inflation is needed.

Let's discuss this.
