### ISSUE TITLE
Add invokable methods of SendTabFeature and FxaPushSupportFeature

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5449]
With these features, the existence of a instance has the side effect of observing things like FxaAccountManager. What we could try to do better, is come up with a pattern that does these things on a function call (e.g. init() but not `init` the block).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4670)

**Comment by salpiras** [comment]
Hi! Is this up for grabs?

**Comment by jonalmeida** [comment]
I think this is more of a naming problem now. What pattern do you want to establish for features that only need to initialized to work?

Some suggestions and examples we've seen around this codebase.
 - `initialize`
 - `launch`
 - `invoke`

@csadilek might have a more opinions on this, but I'm leaning towards `launch` since it's a term similar to coroutines that gives the impression of something being init'd and async actions taking place.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796430

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
