### ISSUE TITLE
Fennec migration: Disable (currently) unsupported add-ons

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#5460]
This is for https://github.com/mozilla-mobile/fenix/issues/4983 to disable all (currently) unsupported add-ons.

Depends on: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1599585
https://bugzilla.mozilla.org/show_bug.cgi?id=1604222

**Comment by csadilek** [comment]
@pocmo I have a draft ready for this to discuss.

**Comment by ebalazs-sv** [comment]
@csadilek Hi! Can you please provide details to reproduce this so it can be verified? Thanks!

**Comment by csadilek** [comment]
@ebalazs-sv Hi, we still need https://github.com/mozilla-mobile/fenix/pulls/csadilek to land and the GV fix (https://bugzilla.mozilla.org/show_bug.cgi?id=1604222). We'll follow-up once that's done (hopefully tomorrow).

**Comment by csadilek** [comment]
@ebalazs-sv sorry for the delay here. We have verified this using the following steps:

- In Fennec Nightly, install any add-on that affects content. This makes it easy to verify that the add-on is disabled after migration. For instance the Framed! (https://addons.mozilla.org/en-US/firefox/addon/frameyourhosts/) add-on can be configured to draw a border around www.mozilla.org.

- Verify that the add-on is active (e.g. a border is drawn around www.mozilla.org)

- Replace Fennec Nightly with a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4)

- Post migration verify the add-on is disabled (e.g. no border drawn around www.mozilla.org)

There's currently no other add-on UI or support in Nightly (coming soon).

**Comment by ebalazs-sv** [comment]
@csadilek Thank you for the detailed steps to reproduce.
I had tested this on Fennec Nightly migration build 2 with OnePlus 5T (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2) and the installed add-on from Fennec, are disabled on Fenix after migration.
I will move this to Done.
