### ISSUE TITLE
Browser also loaded the URL when tap launches third party app

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#5471]
Currently in some cases (Reddit and Facebook search results).  If the user turns on `Open links in  apps` preference, the third party app is launched but the page is also loaded on the browser side.

This is not reproducible on search results for Twitter posts.  Investigate what's causing this issue.

**Comment by Sangeppato** [comment]
It looks like YouTube is affected as well

**Comment by rocketsroger** [comment]
Looks like after tapping on the search result, A-C get 2 `onLoadRequest`.  The first one is a google redirect and the second one is m.youtube.com.  However, even though the second `onLoadRequest` was denied with `AllowOrDeny.DENY` the URL was still loaded.

**Comment by rocketsroger** [comment]
Will need help from GV to understand why this is happening.  Issue opened https://bugzilla.mozilla.org/show_bug.cgi?id=1608985

**Comment by rocketsroger** [comment]
Confirmed on nightly that this is fixed.  Adding QA to verify.
