### ISSUE TITLE
"What's New" menu item to link to the FAQ Page

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/android-components#5481]
1 - The migrated is what will be NEW for migrated users.
2 - It’s more prominent and discoverable VS an FAQ that would live on the About page

**Comment by pocmo** [comment]
Landed in Fenix and should be in the next migration builds.

**Comment by ebalazs-sv** [comment]
I had tested this on Release, Beta, Nightly migration builds 01/14 with Samsung Galaxy S8 (Android 9), Huawei Honor 8 (Android 7.0), Xiaomi Mi4i (Android 5.0.2) and the "What's New" page opened from the main menu is https://support.mozilla.org/en-US/kb/firefox-preview-upgrade-faqs with the "Firefox Preview Upgrade FAQs" title.
The "What's new in Firefox Preview" page from About Firefox Preview is still https://support.mozilla.org/en-US/kb/whats-new-firefox-preview-30?as=u&utm_source=inproduct with the "What's new in Firefox Preview 3.0" title.
@vesta0 @pocmo Is this expected or the same page must be in both places? Thanks!

**Comment by ebalazs-sv** [comment]
I had opened an issue for the behavior described in in previous comment: https://github.com/mozilla-mobile/android-components/issues/5621. 
Due to that I will move this to Done. Thanks!
