### ISSUE TITLE
AddonsFragment to refresh recyclerView after uninstall

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#5488]
- Go to `AddonsFragment`
- Install an addon
- Go to` InstalledAddonDetails`
- Remove the addon
- Navigate back

Expected: Removed addon is in uninstalled state (should be able to install again)
Actual: Removed addon is in installed state (no action to install unless the fragment is recreated)

**Comment by Amejia481** [comment]
I added something to fix the issue on my [previous push ](https://github.com/mozilla-mobile/fenix/blob/8a1db9e7f4d01acb67cf4434b42cf0119f74473e/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt#L145). When you click remove it should go back to the previous screen.

**Comment by psymoon** [comment]
Verified this is no longer reproducible.
