### ISSUE TITLE
Create a concept to lazily inflate views needed by features

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5491]
We've seen [two][0] [cases][1] so far where we want to lazy inflate views that features need. However, it our current feature APIs, we accept a View interface that expects the instance to always be there.

For the Find In Page example, we were able to mitigate this by initializing the feature _after_ the view was inflated and creating the [`InflationAwareFeature`][2].

For `ReaderViewControlsBar`, we always need the feature running (so that we know when a page is readerable™), so we can't use the above abstraction for all features.

What we need is an abstraction that covers both these cases.

[0]: https://github.com/mozilla-mobile/fenix/issues/4307
[1]: https://github.com/mozilla-mobile/fenix/issues/4309
[2]: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/InflationAwareFeature.kt

**Comment by jonalmeida** [comment]
This is a concept I started with:

```kotlin
class LazyFeatureViewWrapper<T> {
    private var view: View? = null
    private var viewStub: ViewStub? = null
    private var isViewInflated = true
    ​
    constructor(view: View) : super() {
        this.view = view
    }
    ​
    constructor(viewStub: ViewStub) : super() {
        this.viewStub = viewStub
        this.isViewInflated = false
    }
    ​
    @Synchronized
    fun tryInflate() : Boolean {
        return if (viewStub == null && isViewInflated == false) {
            this.view = viewStub.inflate()
            this.isViewInflated = true
            true
        } else if (isViewInflated) {
            false
        } else {
            throw IllegalStateException("We shouldn't be here.")
        }
    }
    ​
    fun withView(block: (T) -> Unit) {
        tryInflate()
        block(view as T)
    }
}
​
// Usage example
fun main() {
    private val somefeature = ViewBoundFeatureWrapper<SomeFeature>()
    ​
    fun onCreate() {
        somefeature.set(
            feature = SomeFeature(
                    view = LazyFeatureViewWrapper<SomeFeatureView>(layout.someView) // ViewStub
                ),
            owner = this,
            view = layout.someView
        )
    }
}
```

**Comment by pocmo** [comment]
With `View` going away soon, I assume we will never end up building this. Closing for now.
