### ISSUE TITLE
Fennec migration: Blocking migration UI

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5509]
Feature: https://github.com/mozilla-mobile/fenix/issues/7092
Designs: https://miro.com/app/board/o9J_kw1CGow=/

While a migration is taking place, we want to block all entry points to the browser until the migration is complete as it would be in a volatile state.

#### Browser Entry Points
- Sharing
- Voice Search
- Custom Tabs
- Send Tab

**Comment by jonalmeida** [comment]
We probably need a combination of things below:

- Disable the intentprocessors or make one that would consume and drop intents if we're migrating and takes you to the migration screen.
  - Covers sharing, but maybe not voice search?
- Custom Tabs
  - Should we disable the service?
  - Drop the intent and/or redirect to the migration UI?
- Push
  - Should be disable from working via FxaAccountManager during migration?
- Fullscreen app activity.
  - Can we lock it so you can't come out?

**Comment by jonalmeida** [comment]
> Disable the intentprocessors or make one that would consume and drop intents if we're migrating and takes you to the migration screen. 

This is being done in https://github.com/mozilla-mobile/android-components/issues/5537.

> Fullscreen app activity. 

This will be an `AbstractMigrationProgressActivity` to make it simple for apps to extend and implement the UI updates when the relevant callbacks are invoked for in-progress and completed states.

> Search Widget
>   - These go directly to the HomeActivity and not through the IntentReceiverActivity.

This seems to be accurate - in Fenix's [`SearchWidgetProvider`][0], it creates an intent to go straight to the `HomeActivity` and therefore by-passing our Intent Processor. A better change would be to refactor that code so that it does go through the intent processor and make a `SearchWidgetIntentProcessor` to handle this intent mutation.

We need to make this change in:
 1. [`createTextSearchIntent`][1]
 2. [`createVoiceSearchIntent`][2]

Maybe we can live without this for nightly if we run out of time.

[0]: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt
[1]: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt#L106
[2]: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/gecko/search/SearchWidgetProvider.kt#L116

**Comment by liuche** [comment]
hey @jonalmeida is this migration state API from AC going to be finished in time to be integrated by Fenix this week?

**Comment by jonalmeida** [comment]
@liuche Yes, I was going to do the Fenix integration as well that involves a few pieces (https://github.com/mozilla-mobile/fenix/issues/7647 and https://github.com/mozilla-mobile/fenix/issues/7645).

**Comment by liuche** [comment]
Okay, so does that mean you're also planning on doing the Fenix migration screen? https://github.com/mozilla-mobile/fenix/issues/7092 I asked @sblatz to handle that part bc we were halfway through our sprint, but if you're doing it, please coordinate w/ him!

**Comment by ebalazs-sv** [comment]
jonalmeida Hi! Can you please provide steps to reproduce this issue? Thanks!

**Comment by jonalmeida** [comment]
@ebalazs-sv this change hasn't reached Fenix yet with a corresponding change there too.

**Comment by ebalazs-sv** [comment]
@jonalmeida The issue https://github.com/mozilla-mobile/fenix/issues/7788 is verified as fixed. Is there other scenario that we need to verify here? Thanks!

**Comment by jonalmeida** [comment]
@ebalazs-sv I don't think there is anything else to test for this ticket. :)

**Comment by ebalazs-sv** [comment]
Since mozilla-mobile/fenix#7788 is verified as fixed and no other testing scenario is needed, I will move this to Done. Thanks!
