### ISSUE TITLE
Experiments do not support server-side feature flags

### ISSUE THREAD

**Issue by colintheshots** [mozilla-mobile/android-components#5528]
The FxA team was using Fretboard to provide Fenix with server-side feature flags. Notably, the three following flags were being used to control client features inside Fenix.

```
    // application services flag to disable the Firefox Sync syncManager
    val asFeatureSyncDisabled = ExperimentDescriptor("asFeatureSyncDisabled")
    // application services flag to disable Firefox Accounts pairing button.
    val asFeatureFxAPairingDisabled = ExperimentDescriptor("asFeatureFxAPairingDisabled")
    // application services flag to disable Firefox Accounts WebChannel integration.
    val asFeatureWebChannelsDisabled = ExperimentDescriptor("asFeatureWebChannelsDisabled")
```

As of today, it appears Experimenter only supports a single experiment running at a time on a client. This precludes using the tool for server-side control of client features for non-experiment purposes. There may well be an important data science reason for this, but we need to understand whether the tool is also capable of handling use cases like this or if they are impractical.

Fretboard is getting retired for redundancy and performance reasons inside Fenix, but we have no option currently to support these server-side flags.

**Comment by mythmon** [comment]
Given the resources available, I think it is impractical to adapt the existing Experiments component to serve as a general purpose flag flipping tool. The idea that there is exactly one experiment active is pretty ingrained in the code from what I can tell, and adapting the code to something else would be tough.
