### ISSUE TITLE
History of Single Session Saved in Collection Does Not Restore

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#5529]
Originally filed in Fenix: https://github.com/mozilla-mobile/fenix/issues/5208

We are still _trying_ to save with [`addTabsToCollection`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/tab-collections/src/main/java/mozilla/components/feature/tab/collections/TabCollectionStorage.kt#L51) and [restore](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt#L174) and it looks like page and loading state is restored correctly, but history no longer is. 

Did something change in the save/restore of individual sessions that would remove history?

**Comment by ekager** [comment]
Just checked this today and looks like loading state is no longer restored either. Logging showed we _are_ restoring. 

I also wonder if this has to do with: https://github.com/mozilla-mobile/fenix/issues/9039

**Comment by pocmo** [comment]
Ah, yeah, it looks like we restore the session and the engine state and then only return the pure session while dropping the engine state on the floor. I'll prepare a patch.
