### ISSUE TITLE
Duplicate GV autofill support

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/android-components#5530]
GV Nightly currently exposes code for use in login autofill, that is not yet available in beta/stable builds.  Once it has been added to them, the following changes will need to be made:

#### Impact
Until this is done, autofill will not work builds that rely on beta/stable GV.

#### Acceptance Criteria
- [ ] `GeckoLoginDelegateWrapper` should be triplicated in `engine-gecko-beta` and `engine-gecko`.
- [ ] `GeckoPromptDelegate` should implement `onLoginStoragePrompt` in `engine-gecko-beta` and `engine-gecko`.

**Comment by pocmo** [comment]
Once GeckoView code is getting merged from nightly to beta and beta to release, we, in AC, also follow that and uplift all code from nightly to beta and beta to release. So if this is already in `engine-gecko-nightly` then it will automatically be available in `engine-gecko-beta` and `engine-gecko` together with the functionality in GeckoView. So we only need to wait.

Also see:
https://mozac.org/contributing/merge-day
