### ISSUE TITLE
Measure perf impact of GeckoLoginStorageDelegate#onLoginFetch

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/android-components#5531]
GV `LoginStorage.Delegate#onLoginFetch` requires a synchronous response, but retrieving that information requires unlocking and querying storage backed by a DB.  This performance hit could be mitigated by changing the GV API to expect a Future, or potentially by doing some complex caching in `LoginsStorage`.  Both of these options would require substantial work.  First, we should measure the impact of the current solution (wrap the call in runBlocking) in order to determine 

#### Acceptance Criteria
- [ ] Add a probe to determine time spent in `GeckoLoginStorageDelegate#onLoginFetch`
- [ ] File a follow-up to analyze resulting telemetry and determine whether or not further work is required

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4708)

**Comment by ekager** [comment]
We removed the `runBlocking` so we are not as concerned about the perf now. Maybe would still be good to add probes, but not urgent

**Comment by grigoryk** [comment]
While this is useful, the impact of these calls is greatly reduced after https://github.com/mozilla-mobile/android-components/pull/6128 - we no longer have an overhead of unlocking the store, or needing to key material.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796417

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
