### ISSUE TITLE
Create a MigrationIntentProcessor that handles intents when migration is active

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5537]
We want to handle incoming intents gracefully while the migration is still taking place and the browser is in a volatile state.

Any incoming intents we should either drop and/or redirect you to the blocking Migration UI.

**Comment by jonalmeida** [comment]
Looking at all the intent processors we currently have in a-c and Fenix:

| Intent Processor                      | `matches` criteria                                                                           | Notes                                                                                   |
| ------------------------------------- | -------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |
| Custom Tabs                           | `ACTION_VIEW && isCustomTabIntent(safeIntent)`                                               |                                                                                         |
| Tab                                   | `ACTION_VIEW || ACTION_SEND || ACTION_NDEF_DISCOVERED || ACTION_SEARCH || ACTION_WEB_SEARCH` |                                                                                         |
| TWA                                   | `ACTION_VIEW && isTrustedWebActivityIntent(safeIntent)`                                      |                                                                                         |
| FennecBookmarkShortcuts | `ACTION_FENNEC_HOMESCREEN_SHORTCUT`                                                          | Resolves to: `org.mozilla.gecko.BOOKMARK`. Doesn't do any migration bookmark shortcuts. |
| WebApp                                | `ACTION_VIEW_PWA`                                                                            |                                                                                         |

We should just match for `ACTION_VIEW` and set a flag if migrating, then let the app launch the activity.

**Comment by jonalmeida** [comment]
Fenix also does some interesting things in their [`IntentReceiverActivity`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt#L65-L66) that we need to bypass.

```kotlin
val intentProcessorType =
    components.intentProcessors.getType(intentProcessors.firstOrNull { it.matches(intent) })

intent.setClassName(applicationContext, intentProcessorType.activityClassName)
intent.putExtra(HomeActivity.OPEN_TO_BROWSER, intentProcessorType.shouldOpenToBrowser(intent))
```

**Comment by jonalmeida** [comment]
> Fenix also does some interesting things in their [`IntentReceiverActivity`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt#L65-L66) that we need to bypass.

The `OPEN_IN_BROWSER` code is misleading. It has nothing to do with the HomeActivity. Just a flag for telling the browser fragment to open in it. Not sure why this is needed though.

**Comment by ebalazs-sv** [comment]
The incoming intents are redirected to the blocking Migration UI when the migration is in progress, as was verified in https://github.com/mozilla-mobile/android-components/issues/5509 and https://github.com/mozilla-mobile/fenix/issues/7788. 
I will move this to Done. Thanks!
