### ISSUE TITLE
Update FxaAccountManager tests to interact with Rust libraries (not mocks)

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5561]
We recently saw high consequence bugs that made it into a released build, which would have been caught by our slightly modified test suite if it was build against real fxa client library, and not mocks.

This issue is to track a transition towards that. We can tackle it progressively, starting with tests that do not involve any network interactions (such as account restore). Those should be easiest to transition, since we won't need to mock server-side API responses.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4737)

**Comment by grigoryk** [comment]
> slightly modified test suite

This refers to adding old versions of persisted FxA state to our test suite, to exercise the app upgrade scenarios.

**Comment by jonalmeida** [comment]
We are using the `full-megazord-forUnitTests` in `service-firefox-accounts` so closing this as won't fix unless we find there are more tests we want to write that make use of the native code paths.
