### ISSUE TITLE
Fennec migration: IllegalStateException: You need to call PushProcessor.install()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5586]
Follow-up from https://github.com/mozilla-mobile/android-components/issues/5276. The original crash was fixed but this one has happened instead:

> FATAL EXCEPTION: Firebase-FirebasePush Process: org.mozilla.firefox_beta, PID: 13979 java.lang.IllegalStateException: You need to call PushProcessor.install() on your Push instance from Application.onCreate(). at mozilla.components.concept.push.PushProcessor$Companion.getRequireInstance(PushProcessor.kt:1) at org.mozilla.fenix.components.FirebasePush.onMessageReceived(FirebasePush.kt:8) at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:178) at com.google.firebase.iid.zzg.run(Unknown Source:5) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:2) at java.lang.Thread.run(Thread.java:764)

Log in: https://github.com/mozilla-mobile/android-components/issues/5276#issuecomment-572952782

**Comment by jonalmeida** [comment]
This _should_ be fixed if we have the Firebase keys in the APK at launch.

**Comment by jonalmeida** [comment]
This also looks like a duplicate of https://github.com/mozilla-mobile/android-components/issues/5044.

**Comment by pocmo** [comment]
Okay, closing in favor of #5044.

**Comment by ebalazs-sv** [comment]
The issue https://github.com/mozilla-mobile/android-components/issues/5044 is verified as fixed, and Fenix does not crash at startup or at sync. Due to that I will move this to Done. Thanks!
