### ISSUE TITLE
bestWebURL() is slow

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/android-components#5594]
The implementation of `bestWebUrl` relies on the same expensive-to-compile regular expression that we worked around for #5376. One of the calls to this method in Fenix is on the main thread and blocks user interaction. Improving the performance of `bestWebUrl` would result in a very significant improvement to user satisfaction. (alert: n=3)

If I may be so bold, I will submit a patch to fix this issue and then act on your feedback. As usual, thanks for everything!

Will

**Comment by csadilek** [comment]
Closed by: https://github.com/mozilla-mobile/android-components/pull/5596
