### ISSUE TITLE
Dark migration UI background

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5597]
I just tested the migration on my Pixel 3 and got a dark background in the migration UI. This didn't happen on my emulator yesterday. I think my device is using a dark theme, so maybe our background is adapting to it while everything else is not. We probably should just hard-code a light background?

**Comment by pocmo** [comment]
![Screenshot_20200116-092855](https://user-images.githubusercontent.com/89638/72509026-04a55900-3847-11ea-93ee-6510fa53c544.png)

**Comment by jonalmeida** [comment]
This will be done on the fenix side, we don't show any content view in the a-c part.

**Comment by jonalmeida** [comment]
PR: https://github.com/mozilla-mobile/fenix/pull/7764

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Nightly migration build 2, 01/17 with Samsung Galaxy S8 (Android 9) - ARM64. With Fenix on Dark mode, the migration screen is on white background.
I will move this to Done. Thanks!
