### ISSUE TITLE
Fennec migration: When rotating the device, the migrated items disappear from the migration screen

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5601]
## Preconditions:
Have Fennec installed and logged in. Have the app open.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4).
2. Observe the migration screen B UI;
### Expected behavior
The migration screen B is displayed as in the [abstract](https://app.abstract.com/share/b1b9f719-fbb5-4c94-b45d-556232a3cd52?collectionLayerId=024aafa7-97b7-4a18-8673-9f3189b8f641&present=true&preview=false&sha=87a74c3651c6a5f2af3e74888ab119f9b25f5dd7).
### Actual behavior
The migrated items list in not displayed.
### Notes:
[Screenshot](https://drive.google.com/file/d/1ccy1L596MzR18_JSoIqEI3ZGRt_kRF9z/view?usp=sharing)
### Device information

* Android device:  Samsung Galaxy S8 (Android 9) - ARM64;
* Fenix version: Nightly migration build 01/16.

**Comment by st3fan** [comment]
Can we do the simple thing here and just lock that activity to portrait? Is that possible on Android?

**Comment by jonalmeida** [comment]
We're not restoring state from the migration on to the screen, but locking to portrait is a small patch right now.

**Comment by pocmo** [comment]
Fixed in the new build.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Nightly migration build 2, 01/17 with Samsung Galaxy S8 (Android 9) - ARM64, Xiaomi Mi Pad 2 (Android 5.1) - x86, Motorola G4 (Android 6.0.1).
The migrated items are kept, but they overlap the text when the device is rotated, a new issue was filed for that https://github.com/mozilla-mobile/android-components/issues/5625.
I will move this to Done. Thanks!
