### ISSUE TITLE
Fennec migration: view-source URLs cannot be opened in Fenix("Cannot Complete Request)" error displayed

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/android-components#5602]
## Preconditions:
Have tabs opened in view source in Fennec (Menu-> Page -> View Page Source).
## Steps to reproduce
1. Replace Fennec Nightly with Fenix using a [Nightly build.](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4)
2. Launch Fenix.
3. Access the tab opened in `view-source`
### Expected behavior
The tab is correctly displayed in `view-source`.
### Actual behavior
The tab cannot be opened and the `Cannot Complete Request` error is displayed.

### Device information

* Device: **OnePlus 6T(Android 9).**
* Build: **Nightly migration build 01/16.**
![Screenshot_20200116-130436](https://user-images.githubusercontent.com/42831109/72524034-b48bbe00-3869-11ea-90b9-048d6338380d.jpg)

**Comment by st3fan** [comment]
I don't think this we should consider this a migration issue and instead turn this into a feature request / enhancement for Fenix. I will call out view-source URLs in the document that we have, next to reader-mode: URLs. Both as unsupported and accepted.

**Comment by pocmo** [comment]
Not supported by Fenix. We decided to ignore that for the migration. Let's file a feature request.

**Comment by ebalazs-sv** [comment]
Since this is not supported by Fenix, I will move this to Done. Thanks!
