### ISSUE TITLE
Fennec migration: No notification displayed when the migration is complete

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/android-components#5603]
## Preconditions:
Have Fennec installed and logged in.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Observe the ongoing notification while the migration is in progress.
3. Observe the notification change when the migration is complete
### Expected behavior
The notification is displayed and the Firefox logo is visible, [specs](https://app.abstract.com/share/b1b9f719-fbb5-4c94-b45d-556232a3cd52?collectionLayerId=8170061f-90bc-400b-b505-3e59d89d4c8a&present=true&preview=false&sha=87a74c3651c6a5f2af3e74888ab119f9b25f5dd7).
### Actual behavior
The notification is not displayed.

### Device information

* Android device: Samsung Galaxy S8 (Android 9), HTC Desire 820 (Android 6.0.1)
* Fenix version: Nightly migration build 01/16

**Comment by Sparky93** [comment]
Hello, I'd like to work on this, can someone assign me please?

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Migration Build 7 on Samsung Galaxy Tab A SM-T515 (Android 9) and Sony Xperia Z5 (Android 7).
