### ISSUE TITLE
Fennec migration: Tapping on the ongoing notification doesn't display the loading screen

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/android-components#5605]
## Prerequisites
- Have Fennec installed and logged in.

## Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Put the browser in the background while the migration is running;
3. Open notification bar;
4. Tap on the notification.

### Expected behavior
The loading screen is displayed.

### Actual behavior
The screen is not displayed.

### Device information
* Android device: Google Pixel (Android Q), HTC Desire 820 (Android 6.0.1), Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture.
* Fenix version: Nightly migration build 01/16.

**Comment by st3fan** [comment]
@ebalazs-sv I think this was fixed with https://github.com/vmbaicu/fenix/commit/a5cf0cf8c6a6b73be68aa522c818749a298770c1 so this should work in the Build 7.

**Comment by st3fan** [comment]
Oh it looks like that patch never landed? @vmbaicu ?

**Comment by pocmo** [comment]
In review here: https://github.com/mozilla-mobile/android-components/pull/5774

**Comment by pocmo** [comment]
Patches landed in AC and Fenix.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Migration Build #9 (Build #2015722947) 2/14 using a Pixel 3a XL (Android 10) and Samsung Galaxy Note9 (Android 9).
