### ISSUE TITLE
Fennec migration: Connected devices shows the same device with both Fennec and Fenix after migration

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/android-components#5606]
STR: 
1. Connect to sync on Fennec. Check the devices list on desktop, in account settings.
2. Migrate to Fenix.
3. Check the devices list on desktop, in account settings.

Expected results:
The device list shows the current mobile device only once. 

Actual results:
The list still shows the device both with Fennec and Fenix: https://www.screencast.com/t/aOAYlRMquh

**Comment by grigoryk** [comment]
This is the expected outcome of https://github.com/mozilla-mobile/android-components/pull/5576, we'll fix this in time for `beta` rollout.

**Comment by rfk** [comment]
The fix here is to revert https://github.com/mozilla-mobile/android-components/pull/5576, setting `reuseAccount=true` (although seeing this with fresh eyes, the name is a bit weird, it's the sessionToken that we're re-using, not the account).

Before we can do so, we need to wait for FxA train-155 to be deployed. I don't have a deploy bug yet, but an easy way to check whether the required FxA fixes are in production is to visit [https://accounts.firefox.com/\_\_version\_\_](https://accounts.firefox.com/__version__); if it says `version: "1.155.0"` or high then we should be OK to proceed with the fix.

**Comment by abodea** [comment]
Verified as fixed on **Migration Build #9 (Build #2015722947)** **2/14** using a Samsung Galaxy S8+(Android 8).
Note that only one device is displayed after migration.
Based on my comment I will move this issue to the `Done` column.
![download (3)](https://user-images.githubusercontent.com/42831109/74520458-4695ed80-4f20-11ea-9feb-ec4b6fa68f1d.png)
