### ISSUE TITLE
When creating a new site permission take into consideration the sitePermissionsRules

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#5616]
Related issue https://github.com/mozilla-mobile/fenix/issues/4554

https://github.com/mozilla-mobile/android-components/blob/ebf112c3ec10a0bf5924bba117cac96da68873a4/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt#L174

**Comment by darkwing** [comment]
Hello!  What's the status of this?  It's been prioritized for the Fenix launch :)

**Comment by Amejia481** [comment]
We could work on it next spring, but feel free to take it before it.

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/android-components/pull/6166
