### ISSUE TITLE
Fennec migration: "What's new in Firefox" page from About Firefox is not about Upgrade FAQs

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5621]
## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4).
2. Launch Fenix;
3. Go to Settings -> About Firefox -> What's new in Firefox;
4. Observe the opened page;
### Expected behavior
The opened page is https://support.mozilla.org/en-US/kb/firefox-preview-upgrade-faqs with the "Firefox Preview Upgrade FAQs" title.
### Actual behavior
The opened page is https://support.mozilla.org/en-US/kb/whats-new-firefox-preview-30?as=u&utm_source=inproduct with the "What's new in Firefox Preview 3.0" title.

### Device information

* Android device:  Samsung Galaxy S8 (Android 9) - ARM64;
* Fenix version: Nightly migration build 1, 01/16.

**Comment by pocmo** [comment]
Implemented in #5481. I only replaced the link in the menu and didn't know there was a second entry point.

**Comment by pocmo** [comment]
Fixed in the next migration build.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly migration build 4 with Samsung Galaxy S8 (Android 9) - ARM64, HTC Desire 820 (Android 6.0.1), Nokia 6 (Android 7.1.1) - ARM.
I will move this to Done. Thanks!
