### ISSUE TITLE
Fennec migration: Homescreen shortcuts are opened in the background when the app is open

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5623]
## Preconditions:
Have homescreen shortcuts added to Fennec Nightly.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.17.revision/e4eba42b93d58586b2afb6e13d3e57b37a5209c3).
2. Tap a homescreen shortcut.
### Expected behavior
The homescreen shortcut opens.
### Actual behavior
The homescreen shortcut is opened in the background.

### Notes
This is not reproducible when the app is closed.
[Video](https://drive.google.com/file/d/12xW6cwQywYBWA4kBUQEEezBCnBDFH1VY/view?usp=sharing)

### Device information

* Android device:  Samsung Galaxy S8 (Android 9) - ARM64; Xiaomi Mi Pad 2 (Android 5.1) - x86;
* Fenix version: Nightly migration build 2, 01/17.

**Comment by pocmo** [comment]
🤔 We may need to instruct Fenix to switch the tab.

@Mugurell Do you have time to look into this? Otherwise I will try later.

**Comment by pocmo** [comment]
Looking into this too now.

**Comment by pocmo** [comment]
Fixed with the next build.

**Comment by sv-ohorvath** [comment]
@pocmo This is still reproducible on today's build (1/21).

**Comment by ebalazs-sv** [comment]
Verified as fixed on Nightly migration build 4 with Samsung Galaxy S8 (Android 9) - ARM64, HTC Desire 820 (Android 6.0.1), Nokia 6 (Android 7.1.1) - ARM, Motorola Moto G6 (Android 8) - ARM.
I will move this to Done. Thanks!
