### ISSUE TITLE
RecordNotFoundError: Error No record for uaid:chid

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5627]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7091294/

```
RecordNotFoundError: Error(

No record for uaid:chid "[..]")
    at mozilla.appservices.push.RustError.intoException(RustError.kt:6)
    at mozilla.appservices.push.PushManager.decrypt(PushManager.kt:16)
    at mozilla.components.feature.push.RustPushConnection.decrypt(Connection.kt:3)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invokeSuspend(AutoPushFeature.kt:15)
    at mozilla.components.feature.push.AutoPushFeature$onMessageReceived$1.invoke
...
(6 additional frame(s) were not displayed)

Error(

No record for uaid:chid "[..]":"[..]")
```

**Comment by st3fan** [comment]
This is https://github.com/mozilla-mobile/android-components/issues/4893

**Comment by jonalmeida** [comment]
Re-opening this since #4893 reads like it's related to the push keys missing and not the `RecordNotFoundError`.

**Comment by ebalazs-sv** [comment]
I see this is an error logged in Sentry. @pocmo Can we test this manually, if yes, can you please provide some details, so we can verify it, since is in Ready for QA? Thanks!

**Comment by pocmo** [comment]
I don't think there's anything to manually verify here for us. I'll move this over to "done".
