### ISSUE TITLE
Replace deprecated updateConfiguration() method 

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#5631]
Using the current locale aware classes, we are able to change:
- the app's base configuration locale at app startup

- all activities context configuration when they restart

However, in Fenix we have some singleton classes(ex:Settings.kt) that get their strings from appContext, which will be unchanged during app runtime, even though we selected a new locale from our language list. 

**The workaround in Fenix was to add a deprecated method** 
 (`resources.updateConfiguration`) that updates the appContext. However, this method might be removed in next Android version, so we need to search for **a long-term solution**.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4782)

**Comment by yagnik1997** [comment]
alternative of deprecated updateConfiguration()?

**Comment by csadilek** [comment]
This never landed in A-C so closing this here: https://github.com/mozilla-mobile/android-components/pull/5633
