### ISSUE TITLE
Crash in sample browser when launching MarketplaceIntent

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#5637]
Sample browser does not use `AppLinksFeature` to launch market place intents.  Crash occurs when `AppLinksFeature` is not being used.

**Comment by masi456** [comment]
To reproduce this enable "Open links in apps" in the menu, go to https://paul.kinlan.me/sharing-natively-on-android-from-the-web/ and click on the link `intent:paul.kinlan.me#Intent;scheme=https;package=com.chrome.beta;end`.

**Comment by masi456** [comment]
I think you just need to add `FLAG_ACTIVITY_NEW_TASK` to the intent before calling `openAppLink`. See https://github.com/masi456/android-components/commit/04603594aba635516499aa272edef682372b4f60.

But then there is still the problem that there are no context menu entries for these links.
