### ISSUE TITLE
Lower `minSdkVersion` at least to 19 (but even lower is better) to support unupgradeable devices

### ISSUE THREAD

**Issue by KOLANICH** [mozilla-mobile/android-components#5640]
Blocks https://github.com/mozilla-mobile/fenix/issues/2100

**Comment by pocmo** [comment]
Sorry, this unfortunately will not happen any time soon - likely never. We are depending on some API 21+ (Android 5+) APIs and just do not have the resources to invest the time to potentially go lower than 21.

**Comment by KOLANICH** [comment]
Thanks for the answer.
1. Can I expect a PR implementing 19 be accepted if I or someone else crafted one or is it a principial position that legacy is dropped to just force people to buy new phones? Does it make sense to do these changes at all, the main aim is to support fenix on my device, which is also 21+.
2. How much effort would it take to implement 19 support? What 21-specific API do you depend on and why?
3. How can I start experimenting with bringing it support? I have completely no positive Android experience (the last time I have tried to write an app for Android the IDE had eaten all the RAM on my Windows machine + 5 GiB of swap on a with lot of swapping and freezes, now I am on Linux, so the conditions are even more harsh, so I cannot use IDE sand stuff like GUI editors) and a quite a weak machine (not very much of ram, no SSD), so I wonder if I can do modifications to some small part only without rebuilding the whole app (using some prebuilt artifacts built on something other than my PC, for example on CI)?
