### ISSUE TITLE
FennecMigrator/MigrationStore: Report state after every step.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5644]
Currently `FennecMigrator` sets the state of the migration in `MigrationStore` after everything has completed. However to show an ongoing state in the UI we should update the store after every step.

**Comment by ebalazs-sv** [comment]
@pocmo Where can we verify this state after every step? Thanks!

**Comment by pocmo** [comment]
@ebalazs-sv This is the fix for migration steps appearing in the migration UI as soon as they are completed instead of at the end once everything is completed.

**Comment by ebalazs-sv** [comment]
Thank you! Then this is verified as fixed on Fennec Migration Nightly build 4, 01/22, with Samsung Galaxy S8 (Android 9) - ARM64, HTC Desire 820 (Android 6.0.1), Nokia 6 (Android 7.1.1) - ARM. 
I will move it to Done.
