### ISSUE TITLE
Do not call into history/bookmarks migration code if `browser.db` doesn't exist

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5653]
Currently we are calling these import functions as long as profile exists. We're seeing these issues in https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6963673/?query=is:unresolved - my assumption is that `browser.db` is simply missing, so let's just log this as a `success` (or `failure`?) reason without logging to Sentry.

**Comment by grigoryk** [comment]
Since this is going to require changes to `metrics.yaml`, triggering a data review, let's just add any missing failure/success reason codes as part of this work.

**Comment by pocmo** [comment]
This is somewhat related to #5115: Currently we will always start the migration once, even if we are not coming from fennec. If we use `browser.db` as indicator that we used to be fennec then we wouldn't run migrations without it existing.

**Comment by ebalazs-sv** [comment]
@grigoryk Hello! Can you please provide steps to reproduce this? Thanks!

**Comment by ebalazs-sv** [comment]
Since this is an issue that needs Sentry access, st3fan confirmed that we can move this to Done. Thanks!
