### ISSUE TITLE
Know which PWAs are installed

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#5667]
We want to be able to check if a PWA is installed for a couple different use cases:
- Open notification in corresponding installed PWA
- Display PWA's Web Share Target
- Open corresponding PWA when on a website in the browser

On Android 7.1 and above, we can get a list of pinned shortcuts and use that to figure out which PWAs are installed. On older devices, we could come up with some creative solution or just fallback to different behaviour. (For example, opening notifications in the browser instead.)

**Comment by TitanNano** [comment]
> On Android 7.1 and above, we can get a list of pinned shortcuts and use that to figure out which PWAs are installed. On older devices, we could come up with some creative solution or just fallback to different behaviour. (For example, opening notifications in the browser instead.)

@NotWoods I spent some time pondering about this. As there is no possibility to know the installed shortcuts, there would be only the option to manually track the installation, but I think this has a very high chance to be wrong.

So I came up with the following solution. We introduce a tri-state, `IS_NOT_INSTALLED`, `IS_INSTALLED` and `IS_POSSIBLY_INSTALLED`. The first two work as expected, the third though would actually be more of a suggestion. Once the user adds the shortcut on android <= 7.1 this information is stored somewhere and from now on the state of that PWA scope is `IS_POSSIBLY_INSTALLED`. 
This would enable us to cover the following situations:

- opening a notification:
  - if `IS_NOT_INSTALLED` just open the page in a browser tab
  - if `IS_INSTALLED` open the page in the PWA
  - if `IS_POSSIBLY_INSTALLED` tapping the notification still opens a browser tab, but the notification also has an action "open in PWA"
- display web share target:
  - if `IS_NOT_INSTALLED` no target is shown
  - if `IS_INSTALLED` show target
  - if `IS_POSSIBLY_INSTALLED` we could show a target, but it would never go away anymore
- open PWA when entering it's scope while navigating in the browser
  - if `IS_NOT_INSTALLED` nothing
  - if `IS_INSTALLED` launch PWA in standalone mode (like the Fenix setting "Open links in apps")
  - if `IS_POSSIBLY_INSTALLED` do nothing, but provide a button or menu entry to launch PWA

In adition to the described above, we could also create a cool down for the `IS_POSSIBLY_INSTALLED` state so it disappears after the user didn't launch the PWA in standalone mode for some time. This would particularly improve the "display web share target" situation as the target would eventually disappear again, if the user doesn't use the PWA. But other situations could also benefit from it, as they would at some point revert to their non PWA  behavior.

What do you think of this?

**Comment by NotWoods** [comment]
I like the idea of the "maybe" state. I'd prefer to have some timeout (perhaps 30 days since the icon was last opened). However, I don't think we should make special UI for it. Tapping the notification should align with either the installed or not installed state, rather than having a special button to open fullscreen. I think its fine to always or never open as a PWA within that time period.

**Comment by TitanNano** [comment]
@NotWoods I think we have to reconsider this. I just had an additional look into the shortcut APIs because I noticed I couldn't remember who shortcuts are removed from the system `ShortcutManager`. 

The thing is that [`LauncherApps`](https://developer.android.com/reference/android/content/pm/LauncherApps#public-methods) has no method to inform the system that the launcher removed a pinned shortcut. The only way to "remove" a pinned shortcut is to call [`ShortcutManager.disableShortcuts()`](https://developer.android.com/reference/android/content/pm/ShortcutManager.html#disableShortcuts(java.util.List%3Cjava.lang.String%3E,%20java.lang.CharSequence)) from inside the shortcut publishing app (i.e. Fenix). So [`ShortcutManager.getPinnedShortcuts()`](https://developer.android.com/reference/android/content/pm/ShortcutManager.html#getPinnedShortcuts()) is pretty much as useful to us as not having it at all. It only lists which shortcuts have been published by the app and doesn't tell which shortcuts are actually used by the user.
Therefore, I guess we will have to either let users manually uninstall shortcuts from inside the browser or always work with a timeout, like on <= 7.1

**Comment by NotWoods** [comment]
Let's go with a timeout for now, and we can investigate manual removal later on.

**Comment by TitanNano** [comment]
@NotWoods okay sure, sound fine to me. I got a couple of questions about how I should implement this:

- Where should I integrate this? It kind of could be a part of the [WebAppShortcutManager](https://github.com/mozilla-mobile/android-components/blob/e1d27a294eeeb6b5664571931e3e3f431690520f/components/feature/pwa/src/main/java/mozilla/components/feature/pwa/db/ManifestEntity.kt) but it's not really just about the fact that a user created a shortcut. 
- Should I create a new DB model to store the usage / timeout information?
- based on what do we recognize a PWA? At the moment it seems that everything is associated with the manifest, but in this case we will want to know if a page is part of an installed PWA before we navigate to that page, so we won't know what the manifest for that page is. Therefore, I assume I have to store these things, when the shortcut request is accepted.
    - scope
    - last time of usage
    - maybe a reference to the manifest?

**Comment by NotWoods** [comment]
I think we can update `ManifestEntity` with some new `lastAccess` date field. I'm not sure how to best combine that with looking up based on scope. We probably want to expose scope as an index and figure out some query to match it to a path.

I think `WebAppShortcutManager` is the best place to store this. The DB calls should be in `ManifestStorage`, which we mock in tests to avoid directly using the database.

**Comment by TitanNano** [comment]
@NotWoods I have this #5724 draft PR, but I think it won't really work. It appears that manifests members are never [properly processed following the spec](https://www.w3.org/TR/appmanifest/#scope-member). 
We would need `scope` to be processed, so we get a valid URL and this in turn requires `start_url` to be [processed](https://www.w3.org/TR/appmanifest/#start_url-member) into a valid URL. How do we deal with this?

**Comment by NotWoods** [comment]
The JSONObject that we create `WebAppManifest` from in Android Components isn't what the website provides. Gecko does some pre-processing for us first, including turning all URLs into absolute URLs (with domain, etc.). I need to add docs for this, sorry about the confusion! I'll go through your PR soon :)

**Comment by TitanNano** [comment]
@NotWoods Oh I see, okay then I will turn my draft into a proper PR. At the moment `WebAppManifest` defines the `scope` as optional, which is a bit a problem for this feature as every PWA must have a scope, and we need it, so we can match URLs against it. But I guess this is actually also already covered by Gecko then?

**Comment by NotWoods** [comment]
I'm not sure. We could potentially set the scope based on the [notes in the specification](https://www.w3.org/TR/appmanifest/#navigation-scope). I'll check the Gecko codebase and get back to you.

**Comment by NotWoods** [comment]
Filed #5725 for investigation work

**Comment by NotWoods** [comment]
Confirmed that Gecko [always sets the scope property](https://searchfox.org/mozilla-central/source/dom/manifest/ManifestProcessor.jsm#209)

**Comment by TitanNano** [comment]
Should we then open a new issue to change `scope` from `String?` to `String`?

**Comment by NotWoods** [comment]
I've put up a PR for it: #5734

**Comment by TitanNano** [comment]
We can close this now. 🎉
