### ISSUE TITLE
Open notifications in the corresponding PWA, if installed

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#5668]
Site developers can prompt users of their website or PWA to accept web push notifications. If accepted, the service in question can send notifications to the end user, pretty much at any chosen time, and irregardless of whether the browser is running or not.

One notable annoyance is that because "classic" PWAs don't really have deep system integration (unlike WebAPKs), web push notifications open in the browser by default, rather than in the PWA. 

It might be possible to find a creative solution for this problem, as we can check which shortcuts are installed on Android 7.1. See #5667.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4798)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796440

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
