### ISSUE TITLE
Request for major ui change (slim)

### ISSUE THREAD

**Issue by AnikHasibul** [mozilla-mobile/android-components#567]
Please make the progress bar of Firefox Android slim (1.5px or 2px).
And please change the icon borders as well.

Bold looks dumb and not so attractive.

**Comment by pocmo** [comment]
Sorry, this is not the bug tracker for Firefox for Android. Please file Firefox for Android issues here:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android
