### ISSUE TITLE
New Lenient URL Recognition Methods Are Very Lenient

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/android-components#5673]
I know that we want to make URL detection as fast as possible, but in our effort to do so, we settled on a regular expression that is very, very lenient. For instance, 

`ß.de/........$$$$$$` 

is considered a valid URL. 

I blame myself, obviously, because I am the one who wrote it. I have a WIP patch available if we want to make detection more strict. That said, the more strict we become, the closer we get to returning back to the original problem of a heavyweight, strict URL detection algorithm. 

Let me know how best to proceed.

**Comment by hawkinsw** [comment]
Interestingly enough, our very own Mozillian's tool to validate URLs (https://quuz.org/url/uri-validate.html) believes that  `ß.de/........$$$$$$` could be a valid URL.

**Comment by pocmo** [comment]
I can load http://ß.de/........$$$$$$ in my browser - seems valid... :)

**Comment by csadilek** [comment]
@hawkinsw I think your current approach is fine, given the performance gains. `ß.de/........$$$$$$` is also a URL in Fennec and Chrome :).

**Comment by hawkinsw** [comment]
Referencing mozilla-mobile/fenix#7800 from here for future reference. The PR to "resolve" this issue will resolve that issue as well.

**Comment by csadilek** [comment]
Closed by: https://github.com/mozilla-mobile/android-components/pull/5717
