### ISSUE TITLE
Deprecate/Remove URLStringUtils.isURLLikeStrict

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#5680]
This function is no longer being used so we should deprecate and remove it so it doesn't get re-introduced by accident.

It uses a regex that takes > 500ms to compile. More details:
https://github.com/mozilla-mobile/android-components/issues/5376
https://github.com/mozilla-mobile/android-components/issues/5594

**Comment by mcomella** [comment]
Deprecation completed. We'll need to follow up with deprecation in a https://github.com/mozilla-mobile/android-components/issues/6815
