### ISSUE TITLE
fxa: don't expect versioned .so names

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/android-components#569]
Right now, the `libfxa_client.so` shipping in `org.mozilla.components.fxa:0.17` appears to expect to dynamically link against `libssl.1.0.0.so`.  Per https://groups.google.com/d/msg/android-ndk/_UhNpRJlA1k/hbryqzEgN94J and conventional wisdom, Android just doesn't support versioned .so names, so we should expect to dynamically link against `libssl.so`.

Now, what confuses me is that this is clearly working in some situations!  The Notes App is shipping, and @thomcc appears to have gotten the test Logins API App to work with FxA (version 0.14, but still).  So clearly something delicate is going on, perhaps with explicit `System.loadLibrary` calls in just the right places -- but that's not working for me locally.

**Comment by ncalexan** [comment]
Locally, I find:
```
/Users/nalexander/.mozbuild/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/arm-linux-androideabi/bin/readelf -d /Users/nalexander/.m2/repository/org/mozilla/components/fxa/0.17/fxa-0.17.aar:jni/armeabi-v7a:libfxa_client.so

Dynamic section at offset 0x1b8c80 contains 27 entries:
  Tag        Type                         Name/Value
 0x00000003 (PLTGOT)                     0x1b9dc0
 0x00000002 (PLTRELSZ)                   1128 (bytes)
 0x00000017 (JMPREL)                     0xfc20
 0x00000014 (PLTREL)                     REL
 0x00000011 (REL)                        0x1c30
 0x00000012 (RELSZ)                      57328 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffa (RELCOUNT)                   7162
 0x00000006 (SYMTAB)                     0x1cc
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000005 (STRTAB)                     0xbec
 0x0000000a (STRSZ)                      2568 (bytes)
 0x00000004 (HASH)                       0x15f4
 0x00000001 (NEEDED)                     Shared library: [libssl.so.1.0.0]
 0x00000001 (NEEDED)                     Shared library: [libcrypto.so.1.0.0]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x0000001a (FINI_ARRAY)                 0x1a67c0
 0x0000001c (FINI_ARRAYSZ)               4 (bytes)
 0x0000001e (FLAGS)                      BIND_NOW
 0x6ffffffb (FLAGS_1)                    Flags: NOW
 0x6ffffff0 (VERSYM)                     0x1a90
 0x6ffffffc (VERDEF)                     0x1bd4
 0x6ffffffd (VERDEFNUM)                  1
 0x6ffffffe (VERNEED)                    0x1bf0
 0x6fffffff (VERNEEDNUM)                 2
 0x00000000 (NULL)                       0x0
```

**Comment by ncalexan** [comment]
This might just be [hard with OpenSSL 1.0.2*](https://github.com/openssl/openssl/issues/3902).  Given changes to the [Android linker in 24](https://android-developers.googleblog.com/2016/06/android-changes-for-ndk-developers.html) I think we need the .so files to have the ELF SONAME be exactly the filename; we can't change the ELF SONAME in OpenSSL, so we change the filenames.

**Comment by thomcc** [comment]
If worst comes to worse, You can also use a tool like [`patchelf`](https://www.mankier.com/1/patchelf). E.g. `patchelf --replace-needed libssl.so.1.0.0 libssl.so libfxa_client.so`

**Comment by csadilek** [comment]
Thanks! We've upgraded to 0.2.2 of fxa_client.so now which statically links openSSL. So, closing this issue...
