### ISSUE TITLE
Add better error handling for onMessageReceived events in Push

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#5691]
Based on discussions [in this thread][0], we should handle push messaging failures better without crashing the entire app when messages come in.

A possible solution is to have an error type for messaging that wraps around all throwables so that we can long them in Sentry.

[0]: https://github.com/mozilla-mobile/android-components/pull/5679#discussion_r369746505

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4809)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796429

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
