### ISSUE TITLE
Support specifying the custom domain list in DomainAutoCompleteProvider.kt

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#57]
With the current implementation of [`DomainAutoCompleteProvider.kt`](https://github.com/mozilla-mobile/android-components/blob/master/components/browser/domains/src/main/java/mozilla/components/domains/DomainAutoCompleteProvider.kt) it is loading the list of custom URLs from disk. 

While working on mozilla-mobile/focus-android#2000I'm running into a problem where I want to be able to save the full URL in `CustomDomains` but be able to strip out the protocol and `www` to allow the user to continue to autocomplete without having to type out the protocol first. 

<img width="615" alt="image" src="https://user-images.githubusercontent.com/1250545/38710303-833337b6-3e74-11e8-92f0-e45e3cf20494.png">

But be able to switch to the full URL they saved when they submit the field.

**Comment by pocmo** [comment]
I think it makes sense to modify the component to support (partial) URLs instead of just domains. Ideally we could continue using the storage of CustomDomains and be smart when loading a domain (which is a partial URL).

@csadilek What do you think?

**Comment by pocmo** [comment]
@boek @csadilek We can close this issue now, right?

**Comment by csadilek** [comment]
Yes, I think so, we have the functionality now, thanks to @boek.

**Comment by boek** [comment]
🙌
