### ISSUE TITLE
Browser/Page actions don't have stable ordering in toolbar and menu

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#5708]
STR
- Start sample app
- Install multiple web extensions
- Click on first web extension browser action in the toolbar (from the left)
- Transition to another screen (enabling action popup or background/foreground app or transition to addons list fragment)
- Go back to browser screen

Expected
- Browser actions stay the same in the toolbar

Actual
- Browser actions order changed in the toolbar

**Comment by csadilek** [comment]
This happens for both the toolbar and the browser menu as we're just iterating over a map right now. We should sort by actions by name for now to not see them move around when the menu or toolbar gets re-rendered. Preparing a PR.
