### ISSUE TITLE
Do less while recovering from authentication problems

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#5716]
When we recover from authentication problems, we'll currently execute `initDeviceAsync`, `refreshDevicesAsync` and `pollForEventsAsync` - as we're just going through the regular motions of being logged-in.

It's possible that due to currently unknown server-side issues, clients sometimes could get into a loop of failed to sync (401), tried to recover, recovered successfully (got a new access token), repeat. This loop will generate a lot of extra traffic to our FxA servers that we can easily avoid without any real downsides (I think!).

**Comment by ebalazs-sv** [comment]
@grigoryk Hi! Can you please provide steps to reproduce this issue so we can verify it in the next Beta Migration build? Thanks!

**Comment by grigoryk** [comment]
@ebalazs-sv the simplest way to verify this is to probably by looking at the logcat output as device automatically recovers from an authentication problem - there shouldn't be `Refreshing device list` present during recovery.

Getting an authentication problem manually is a little tricky. Simplest way is to sign-in on the device, then turn it off, then come back to it in a couple of days and try to sync. At that point, access tokens would have expired, and the recovery flow should be triggered.

**Comment by ebalazs-sv** [comment]
@grigoryk Thanks for the details. We will verify this scenario and come back with the result.

**Comment by LaurentiuApahideanSV** [comment]
I tested the issue on Firefox Preview Beta 75.0.0-beta.2 using a OnePlus 6T (Android 9). Restarting the device after 2 days did not show "Refreshing device list" in the logcat output.
