### ISSUE TITLE
BrowserToolbar styleable attribute colours for icons not working

### ISSUE THREAD

**Issue by wax911** [mozilla-mobile/android-components#5720]
**Defective versions**: 13.0.0+
**Current version**: 23.0.0, 28.0.3

Thank you for the wonderful components! Recently found that the following attributes no longer work since upgrading from [v13.0.0](https://github.com/mozilla-mobile/android-components/blob/master/docs/changelog.md#1300):

![image](https://user-images.githubusercontent.com/7859175/73120736-4edeb680-3f7a-11ea-99c3-6f779692e89b.png)

```
browserToolbarInsecureColor
browserToolbarSecureColor
browserToolbarMenuColor
browserToolbarSuggestionBackgroundColor
browserToolbarSuggestionForegroundColor
browserToolbarClearColor
browserToolbarTrackingProtectionAndSecurityIndicatorSeparatorColor
```

![image](https://user-images.githubusercontent.com/7859175/73120750-95341580-3f7a-11ea-90dc-f41951e0755c.png)

The colours in the above screenshot are day/night configuration dependant which worked fine initially when I set up the project with v13.0.0 but after upgrading to other versions the attributes don't seem to have any effect on presentation. Currently this is what I have when using a light theme:

![image](https://user-images.githubusercontent.com/7859175/73120778-e8a66380-3f7a-11ea-9bb4-3400affd6b33.png)

When I switch to a dark theme I have the following: (which behaves as expected)

![image](https://user-images.githubusercontent.com/7859175/73120791-112e5d80-3f7b-11ea-8b7f-ba3c51f8f055.png)

This only seems to happen with `mozilla.components.browser.toolbar.BrowserToolbar` while the rest of the components like `CustomTabs` work as expected, as seen below:

![image](https://user-images.githubusercontent.com/7859175/73120840-8d28a580-3f7b-11ea-9f3f-9e21e9d9717a.png) 
![image](https://user-images.githubusercontent.com/7859175/73120877-01fbdf80-3f7c-11ea-84f8-f1263dc702dd.png)

Any idea as to what might be the cause? Thank you all in advance!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4822)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795134

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
