### ISSUE TITLE
Add comments about what Gecko manifest processing is performed

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#5725]
Usually when working with the manifest parser, we assume the JSONObject is identical to whatever the website provides. However, Gecko and GeckoView do some processing first before giving the object to Android Components. Let's write down the adjustments somewhere.

- Changes URLs to be absolute
- Changes some space-separated strings into arrays
- Changes colors to follow Android format (`#AARRGGBB`)
- Removes invalid enum values (ie: `display: halfscreen`)
- Ensures `display`, `dir`, `start_url`, and `scope` always have a value
- Trims most strings (`name`, `short_name`, ...)

**Comment by NotWoods** [comment]
Let's add the above list and the following link into the comments for `WebAppManifestProcessor`.

https://searchfox.org/mozilla-central/source/dom/manifest/ManifestProcessor.jsm

**Comment by pocmo** [comment]
Patch in PR #5734.
