### ISSUE TITLE
Provide API to cancel add-on installation

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#5748]
We currently have no way of cancelling after installation of an add-on has started. 

This requires:
https://bugzilla.mozilla.org/show_bug.cgi?id=1612097

**Comment by agi90** [comment]
FYI the API landed in GV

**Comment by csadilek** [comment]
Found a crash which we're blocked on now: https://bugzilla.mozilla.org/show_bug.cgi?id=1629952

We can't land the UI integration, but let's land the API bits.
