### ISSUE TITLE
Menu items with switches do not properly focus

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#5757]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/73443680-74433a00-4357-11ea-924f-00615ac70adb.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4835)

**Comment by csadilek** [comment]
This looks to be fixed.
