### ISSUE TITLE
[Bug] Crash dialog message truncated on Nexus 6P

### ISSUE THREAD

**Issue by sflorean** [mozilla-mobile/android-components#5759]
## Steps to reproduce
1. Open 1-2 tabs.
2. Go to about:crashparent.
3. Check the crash dialog message.

### Expected behavior
No visual issue is displayed and the message is readable. 

### Actual behavior
"Problem" word is truncated. 

### Device information
* Android device: Nexus 6P(Android 8.1)
* Fenix version: Nightly 1/29.

![Screenshot_20200129-162359](https://user-images.githubusercontent.com/58466444/73371207-05fe6900-42be-11ea-96a0-892d185ae750.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4836)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795133

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
