### ISSUE TITLE
[Bug] No padding in left boundary of URL bar in RTL

### ISSUE THREAD

**Issue by eeejay** [mozilla-mobile/android-components#5762]
With an RTL locale padding seems wrong for text in address bar's left boundary.

![Screenshot_20200130-113759](https://user-images.githubusercontent.com/5764/73442690-26ecab80-430a-11ea-913b-cdd9a88dcb95.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4839)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796301

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
