### ISSUE TITLE
[Bug] Unknown Protocol Error Page when Attempting to Open Reddit App via in-page Links

### ISSUE THREAD

**Issue by pwd-github** [mozilla-mobile/android-components#5786]
## Steps to reproduce
1. Load a Reddit thread
2. Press open in app 

### Expected behavior
Reddit app opens

### Actual behavior
Unknown Protocol Error

### Device information

* Android device: Pixel 4XL
* Fenix version: Nightly 200202 06:01 (Build #20330607)
30.0.0, 4f306089f
GV: 74.0a1-20200129093157

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4849)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793133

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
