### ISSUE TITLE
Support viewport-fit descriptor via `onMetaViewportFitChange`

### ISSUE THREAD

**Issue by makotokato** [mozilla-mobile/android-components#5795]
Spec: https://drafts.csswg.org/css-round-display/#viewport-fit-descriptor

I have added `<meta name="viewport" content="viewport-fit=cover">` support to GV by https://bugzilla.mozilla.org/show_bug.cgi?id=1574307. ac should override `onMetaViewportFitChange` of `ContentDelegate`, then ac should set `layoutInDisplayCutoutMode` by `viewport-fit value`.

GVE implementation for example is https://bugzilla.mozilla.org/show_bug.cgi?id=1612785

**Comment by rocketsroger** [comment]
Test pages used to confirm the implementation:
viewport-fit=contain: https://makotokato.github.io/demo/cutout-contain.html
viewport-fit=cover: https://makotokato.github.io/demo/cutout-cover.html
