### ISSUE TITLE
Migrate default search engine

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5818]
Currently we do not migrate the default search engine when a user updates from Fennec to Fenix. This means that a user will get the default search engine for that configuration after the upgrade.

We want to try a "best effort" migration:
- Get the name of the default search engine from Fennec
- Try to find a match in the list of search engines for this Fenix installation
- If a match is found set the default to the matching

This will only work in cases where the previous search engine name is still in the list of search engines Fenix has determined for this installation. This can fail for custom search engines or when the user is in a completely different region that does not offer the previous choice. However the approach looks very promising and should migrate a decent chunk of defaults.

**Comment by pocmo** [comment]
This is in the latest build.

**Comment by sflorean** [comment]
Verified as fixed for the default search engine added in Fennec and Fenix. Areas tested:
- search widget
- settings
- URL bar 
- performed different searches 
Environment: 
- Migration build 7 - 02/06
- Google Pixel XL (Android Q)
- Samsung Galaxy Note 8 (Android 9)
- Motorola Moto G6 (Android 8.0)
- Sony Xperia Z5 Lite (Android 7)
- LG G4  Android 6.0.1)
- Xiaomi Mi Pad 2 (Android 5.1) - x86 architecture
