### ISSUE TITLE
Remove setSdkInt from WebAppShortcutManagerTest

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#5825]
I wrote this as a hack to set the `SDK_INT` in tests, but its properly supported using the `@Config(sdk = [Build.VERSION_CODES.X])` annotation. The function should be replaced with the annotation and removed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4869)

**Comment by waahm7** [comment]
I would love to do this. Can you please assign this to me?

**Comment by waahm7** [comment]
Hi @NotWoods, Thank you for assigning the issue to me. I was succesfully able to use @Config in most tests but in some it was being called in the middle of function. So I tried to split those tests into two seperate tests to provide different SDK versions for each of them. All the test cases are passing except one. If I use setStaticField to set SDK to 0 [here ](https://github.com/waahm7/android-components/blob/711094a811291e16c4c924c732a6b2c8e9121518/components/feature/pwa/src/test/java/mozilla/components/feature/pwa/WebAppShortcutManagerTest.kt#L299) it passes but fails if I set it with @Config. Can you give me an idea on how to tackle this? I narrowed down the issue to if I use setStaticField it executes the test with default SDK but gets default value (0) of SDK_INT in uninstallShortcuts function in the WebAppManager.kt  but if I set it with @Config it tries to execute the test with Api level 0 which results in the following error "java.lang.UnsupportedOperationException: Robolectric does not support API level 0."

**Comment by NotWoods** [comment]
Any SDK level lower than `N_MR1` should work fine. `L`/`LOLLIPOP` would be good to use as its the lowest version we support.

**Comment by waahm7** [comment]
@NotWoods Thank you for the response. If I set a level less than N_MR1 it results in the following error "java.lang.NoSuchMethodError: android.content.pm.ShortcutManager.disableShortcuts(Ljava/util/List;Ljava/lang/CharSequence;)" and if I set it to N_MR1 it results in "never wanted but invoked" error.

**Comment by waahm7** [comment]
@NotWoods what should I do?

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796439

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
