### ISSUE TITLE
Fennec migration: Tapping on the "Update complete" notification doesn't bring Fenix in focus

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/android-components#5831]
# Prerequisites
* Have Fennec installed and logged in.
# Steps to reproduce
1. Replace Fennec with Fenix using a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Wait until the migration is complete
3. Open the notification bar;
4. Tap on the notification.
# Expected behavior
Fenix should be brought into focus and the Push Notification dismissed

# Actual behavior
Tapping the notification performs no action and opening or closing the browser does not dismiss it.

# Device information
* Android device: Google Pixel XL (Android Q), Galaxy Tab A SM-T515 (Android 9).
* Fenix version: Nightly migration build 2/6.

**Comment by vmbaicu** [comment]
https://github.com/mozilla-mobile/android-components/pull/5774 fixes the missing action

**Comment by pocmo** [comment]
Patches landed in AC and Fenix. This should be fixed in the next build.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Migration Build #9 (Build #2015722947) 2/14 using a Pixel 3a XL (Android 10) and Samsung Galaxy Note9 (Android 9).
