### ISSUE TITLE
A few messages reference "computer"

### ISSUE THREAD

**Issue by flodolo** [mozilla-mobile/android-components#5861]
https://transvision.mozfr.org/?recherche=computer&repo=android_l10n&sourcelocale=en-US&locale=en-US&search_type=strings_entities

For example: 

```
<p>The browser is operating in its offline mode and cannot connect 
to the requested item.</p> <ul> <li>Is the computer connected to 
an active network?</li> <li>Press “Try Again” to switch to online 
mode and reload the page.</li> </ul> 
```

Not sure *computer* is the best choice for Android, *device* is probably safer? 4 out of 6 have this problem.

To avoid losing all these long translations, I'd go as far as fixing these strings without new IDs, and then communicating the change to localizers, in case they want to update their translations.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4884)

**Comment by st3fan** [comment]
https://github.com/mozilla-mobile/android-components/pull/5981

**Comment by st3fan** [comment]
I created a PR for Android Components here at https://github.com/mozilla-mobile/android-components/pull/5981

The last two results in the search in the previous message are correct and do not need to be changed. Those are about generating the pairing QR code on Desktop, so that correctly refers to _computer_.

**Comment by st3fan** [comment]
@mheubusch  @flodolo does this look good?

**Comment by mheubusch** [comment]
Looks good to me. Thanks.

**Comment by st3fan** [comment]
@flodolo the patch is in review - how do we contact the localizers? Is that something you can do?

**Comment by flodolo** [comment]
> @flodolo the patch is in review - how do we contact the localizers? Is that something you can do?

I'll coordinate with @guerojeff, he's taking care of the comms part while Delphine is out.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796470

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
