### ISSUE TITLE
`ContextMenuFeature` and `DownloadsFeature` not working for PWA and some special cases

### ISSUE THREAD

**Issue by JasonHK** [mozilla-mobile/android-components#5865]
These two features use `BrowserState.findCustomTabOrSelectedTab` extension method to find the active tab. But in some cases, the extension method will not work and makes the feature not able to find the active tab.

These special cases including:

- The tab is a PWA that was started by clicking the shortcut on the home screen.
- You always supplied an identical session ID for a tab-less browser.

Since these tabs are all normal tabs but not custom tabs, `BrowserState.findCustomTabOrSelectedTab` will not return these tabs when a tab ID was provided. That's why `ContextMenuFeature` and `DownloadsFeature` not working properly.

**Comment by pocmo** [comment]
#5864
