### ISSUE TITLE
Weird highlighting on error pages

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#5876]
When hovering over the "advanced" portion of error pages, there is a weird highlighting of the text.

@darkwing mentioned this is because we're emitting a `<label>`

Example: 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4400286/74183202-5c8e7000-4bf9-11ea-8f68-ffa5e4e48f2e.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4893)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796469

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
