### ISSUE TITLE
High risk error pages do not have URI's for "url encoded" error pages

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#5878]
We need to pass the URI of the error page to the string

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4894)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796468

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
