### ISSUE TITLE
Improved PWA install prompt

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [mozilla-mobile/android-components#5883]
### Why/User Benefit/User Problem

Currently, PWA install prompt expose only name and icon.

It would be really nice to improve the PWA install UX by exposing more fields from web app manifest.

Related equivalent Chrome bug: https://crbug.com/1050311.

### Acceptance Criteria (how do I know when I’m done?)

The following fields from web app manifest should be exposed to PWA install prompt:

* description (https://w3c.github.io/manifest/#description-member)
* screenshots (https://w3c.github.io/manifest/#screenshots-member)
* categories (https://w3c.github.io/manifest/#categories-member)
* iarc_rating_id (https://w3c.github.io/manifest/#iarc_rating_id-member)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4896)

**Comment by NotWoods** [comment]
This includes UI work that may live in Fenix

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796438

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
