### ISSUE TITLE
Fennec migration: The "Update complete" notification remains displayed until dismissed

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5886]
## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix;
2. Launch Fenix;
3. Observe the "Update complete" notification.
### Expected behavior
The "Update complete" notification is dismissed.
### Actual behavior
The "Update complete" notification is dismissed only by swipe.
### Notes:
[Video](https://drive.google.com/file/d/17ucg44xRAgt5ETOIFIfIwO0xPPkWtpIV/view?usp=sharing)
### Device information

* Android device: Nexus 6P (Android 8.1.0);
* Fenix version: Nightly migration build 8, 02/10.

**Comment by pocmo** [comment]
Will be fixed in the next Beta build.

**Comment by ebalazs-sv** [comment]
I had tested this on Fennec Beta Migration 02/18 from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration with Samsung Galaxy Note 8 (Android 9) and the "Update complete" notification is dismissed after is tapped once or when the "Start Firefox" button is tapped.
I will leave this on Ready for QA until it will be verified on the official Beta Migration build.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Beta Migration Build #1, Firefox Preview Beta 74.0.0-beta.1 (Build #2015724883) using a Samsung Galaxy S5 (Android 6.0.1) and OnePlus 6T (Android 9). The "Update complete" notification is dismissed after tapping on it or the "Start Firefox" button.
