### ISSUE TITLE
Fennec migration: The Done signs are removed when reopening the app and tapping on the "Update complete" notification

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5907]
## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix with a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix and tap on "Start browsing";
3. Close the app from Recent apps;
4. Tap the "Update complete" notification and observe the migration UI;
### Expected behavior
The Done signs are displayed like in the [specs](https://miro.com/app/board/o9J_kw1CGow=/).
### Actual behavior
The Done signs are removed.
### Notes:
[Video](https://drive.google.com/file/d/1BaSscquYWcVp0bjpzdYf8CgbwRUPgWXm/view)
### Device information

* Android device: OnePlus 5T (Android 9), Nexus 6P (Android 8.1.0), Huawei Honor 8 (Android 7.0);
* Fenix version: Beta migration build 2/12

**Comment by ebalazs-sv** [comment]
This is also reproducible on Nightly Migration Build 9, 02/14.

**Comment by ebalazs-sv** [comment]
This is also reproducible when you install Nightly Migration Build 9 over Build 6 .

**Comment by ebalazs-sv** [comment]
This is reproducible on Fennec Beta Migration 02/18 from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration with Samsung Galaxy Note 8 (Android 9), following the steps:
1. Replace Fennec with Fenix with a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Close the app from Recent apps while the onboarding migration screen is displayed;
3. Tap the "Update complete" notification and observe the migration UI;

The Done signs are removed in this case.

**Comment by Sparky93** [comment]
Hello, thanks for reporting this, it helped me find another issue, tl;dr you shouldn't even be able to see that screen after tapping the update complete notification so this should be closed after we merge #5996

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed in Beta Migration Build 2 using a Pixel XL (Android 9) and OnePlus 6T (Android 9). After tapping the "Migration Complete" Notification the Fenix onboarding screen is shown.

**Comment by ebalazs-sv** [comment]
This was verified as fixed in the previous comment. I will move it to Done.
