### ISSUE TITLE
Fennec migration: The "Updating Firefox..." and "Start Firefox" buttons have a different text than in the specs

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5922]
## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix with a build from https://github.com/mozilla-mobile/fenix/wiki/Fennec-Migration;
2. Launch Fenix;
3. Observe the "Updating Firefox..." and "Start Firefox" buttons from the onboarding migration screen.
### Expected behavior
The "Updating Firefox..." and "Start Firefox" buttons are displayed at the bottom of the page, like in the [specs](https://miro.com/app/board/o9J_kw1CGow=/).
### Actual behavior
The "Updating Firefox..." and "Start Firefox" buttons are displayed as "Updating Firefox Preview..." and "Start Firefox Preview".
### Notes:
Screenshots:
[Updating button on Beta](https://drive.google.com/open?id=1aVnVU0RdCrO4yE-I5jVGVJDcieoXOSCc)
[Start button on Beta](https://drive.google.com/file/d/1Q1BZMpztokp1vDvx2BtOCx8LlUKeHtb8/view)
[Updating button on Nightly](https://drive.google.com/open?id=1scyA_wWWZ-7HNEJOBbXUtTYeOOK93UvD)
[Start button on Nightly](https://drive.google.com/file/d/1jItRLmU1eR5Tv9sxJv3BiMm0bPHkOoqy/view?usp=sharing)

Also reproducible on Nightly.
### Device information

* Android device: OnePlus 5T (Android 9), Nexus 6P (Android 8.1.0), Huawei Honor 8 (Android 7.0);
* Fenix version: Beta migration build 02/13, Nightly migration build 02/10.

**Comment by pocmo** [comment]
This is because we haven't landed the new branding yet (which also updates the app name: https://github.com/mozilla-mobile/fenix/issues/8277

**Comment by pocmo** [comment]
This landed and should be fixed in the next beta build. For production builds this will depend on #8278 landing first.

**Comment by ebalazs-sv** [comment]
I tested this on Nightly Migration build 9, 02/14 and Beta Migration build 02/19 with Samsung Galaxy Note 8 (Android 9) and for Nightly the buttons have the "Updating Firefox Nightly... ", "Start Firefox Nightly" text and for Beta the buttons have the "Updating Firefox Beta... ", "Start Firefox Beta" text.
I will leave this on Ready for QA until it will also be verified on the official Beta migration build.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Beta Migration Build 1, 02/24 with LG G7 fit (Android 8.1), Google Pixel 2 (Android 9). I will move this to Done. Thanks.
