### ISSUE TITLE
Recent apps feature

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#5923]
As part of a related [ Fenix issue](https://github.com/mozilla-mobile/fenix/issues/4231), the functionality to store/sort recent apps will be moved to AC as a new module so it can be usable in other apps.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4916)

**Comment by csadilek** [comment]
This landed in https://github.com/mozilla-mobile/android-components/pull/5924.
