### ISSUE TITLE
Emit migration state Fact

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#5929]
context: https://github.com/mozilla-mobile/fenix/pull/8208/files#r379019076

In Fenix we would like to get a `Fact` to know when the migration process has been completed 👍

**Comment by ebalazs-sv** [comment]
The issue https://github.com/mozilla-mobile/fenix/issues/8172#issuecomment-588315672 is verified as fixed and the Fennec to Fenix event was created.
@jonalmeida Is there some other scenario that we have to test on this issue? Thanks!

**Comment by jonalmeida** [comment]
@ebalazs-sv I don't think there is anything for QA to test here. :)

**Comment by ebalazs-sv** [comment]
Thanks! I will move this issue to Done.
