### ISSUE TITLE
Fennec migration: Long addons titles push the delete icon out of view

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/android-components#5937]
STR:
1. Install "Ghostery" add-on on Fennec.
2. Install the migration build (from 2/14)
3. Go to Settings>Addons>Not yet supported list.

Expected results:
The long titles are maybe cut-off or wrapped.

Actual results:
Long titles push the delete icon beyond the screen margin.
![Screenshot_20200214-140026](https://user-images.githubusercontent.com/4037709/74530804-a77af100-4f33-11ea-80ee-f026a8013dd7.png)

**Comment by Diana-Rus** [comment]
Hi, the issue also reproduces with LG K4(2017) (Android 6.0.1).
