### ISSUE TITLE
FennecMigratorException$MigrateBookmarksException: mozilla.appservices.places.PlacesException: Database versions,  NULL parentGuid, CHECK constraint, FOREIGN KEY constraint, [..]

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5938]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/

```
PlacesException: Database version 25 is not supported
    at mozilla.appservices.places.RustError.intoException(RustError.kt:4)
    at mozilla.appservices.places.PlacesApi.importBookmarksFromFennec(PlacesConnection.kt:11)
    at mozilla.components.browser.storage.sync.RustPlacesConnection.importBookmarksFromFennec(Connection.kt:2)
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:75)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
...
(4 additional frame(s) were not displayed)

FennecMigratorException$MigrateBookmarksException: mozilla.appservices.places.PlacesException: Database version 25 is not supported
    at mozilla.components.support.migration.FennecMigrator$runMigrationsAsync$1.invokeSuspend(FennecMigrator.kt:94)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
...
(1 additional frame(s) were not displayed)

[INFO] mozilla.appservices.places.PlacesException: Database version 25 is not supported
```

**Comment by pocmo** [comment]
Something is suspicious here: We saw 74 users with this exception. And all of them with version  25. All kinds of devices from Android 5 to 10. It seems super unlikely that all those users were on 25 and just now updated/launched for the first time?

**Comment by pocmo** [comment]
Flagging some people: @grigoryk @rfk @linacambridge @mhammond Any idea why we may be seeing so "many" with version 25? Are we sure we are reporting the version correctly?

**Comment by grigoryk** [comment]
v25 shipped in Fx44, and v26 shipped in Fx46. Fx45 was an ESR version from 2016-06-07 to 2017-04-19 according to https://wiki.mozilla.org/Release_Management/Calendar.

Perhaps we're seeing users stuck on Fx45 ESR suddenly upgrading? I'm not sure why that would be the case though.

Alternatively, maybe we're not reporting version number currently?

**Comment by rfk** [comment]
> Alternatively, maybe we're not reporting version number currently?

FWIW, the code for checking the db version number seems pretty straightforward to me, inasmuch as it's hard to imagine a way we might be doing this wrong:

```
let db_version = conn.db.query_one::<i64>("PRAGMA fennec.user_version")?;
if db_version != FENNEC_DB_VERSION {
  return Err(ErrorKind::UnsupportedDatabaseVersion(db_version).into());
}
```

(And the code inside `UnsupportedDatabaseVersion` does a simple string-format with the number passed in its first argument).

I wonder if these users could have had some other problem with their `browser.db` that prevented the upgrade from v25 from occurring..?

**Comment by pocmo** [comment]
I just noticed that multiple `FennecMigratorException$MigrateBookmarksException` are grouped together. Not all of them are users with database v25. In fact a bunch of them have a different cause and just got grouped into the same error:

* `mozilla.appservices.places.PlacesException: Error executing SQL: unwinding panic`
* `mozilla.appservices.places.PlacesException: Error merging: Item [..] can't contain itself`
* `mozilla.appservices.places.PlacesException: Error executing SQL: NOT NULL constraint failed: moz_bookmarks_synced_structure.parentGuid`
* `mozilla.appservices.places.PlacesException: Database version 38 is not supported`
* `mozilla.appservices.places.PlacesException: Error executing SQL: database disk image is malformed`
* `mozilla.appservices.places.PlacesException: Database version 37 is not supported`
* `mozilla.appservices.places.PlacesException: Database version 24 is not supported`
* `mozilla.appservices.places.PlacesException: Error executing SQL: CHECK constraint failed: moz_bookmarks`
* `mozilla.appservices.places.PlacesException: Error executing SQL: unable to open database: [..]`
* `mozilla.appservices.places.PlacesException: Error executing SQL: FOREIGN KEY constraint failed`

This means we do not have a version 25 mystery to solve. But I wonder if any other error here needs to be addressed? Is the `moz_bookmarks_synced_structure.parentGuid` error anything that we expect?

@grigoryk In any case it looks like we do not count those errors as failures? But we should.

**Comment by grigoryk** [comment]
https://github.com/mozilla/application-services/issues/2660 marked most of these as "non-actionable"... Unless we disagree (due to volume, or other considerations), let's close this.

**Comment by kbrosnan** [comment]
> v25 shipped in Fx44, and v26 shipped in Fx46. Fx45 was an ESR version from 2016-06-07 to 2017-04-19 according to https://wiki.mozilla.org/Release_Management/Calendar.
> 
> Perhaps we're seeing users stuck on Fx45 ESR suddenly upgrading? I'm not sure why that would be the case though.

Fennec has never had ESR releases. Twice we have used the ESR code base to support big rewrites, ESR 10 and currently ESR 68.

**Comment by ebalazs-sv** [comment]
This was closed without a fix, as per comment https://github.com/mozilla-mobile/android-components/issues/5938#issuecomment-594256424. Due to this, I will move this to Done. Thanks.

**Comment by pocmo** [comment]
`FOREIGN KEY constraint` error in beta migration build (2 users so far).

Sentry issue: [FENIX-FENNEC-BETA-1W](https://sentry.prod.mozaws.net/operations/fenix-fennec-beta/issues/7660252/)
