### ISSUE TITLE
Record SecureStorage migration failures in Sentry 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#5950]
We have the ability to flip back and forth between insecure/secure storage in `SecureAbove22Preferences` and `AccountStorage` but because of hardware specific KeyStore errors, we are currently catching these failures instead of crashing. Let's add Sentry logging of those errors and failures to migrate.
See https://github.com/mozilla-mobile/android-components/pull/5902

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-4933)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795132

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
