### ISSUE TITLE
feature-accounts webchannel status handshake seems broken, due to interference from Gecko

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/android-components#5969]
The FxA "status handshake" between the browser and web content does not seem to be working correctly on Fenix, due to what I suspect is a bad interaction with Gecko's native `WebChannel` feature.

I think this is the underlying cause of [Choose What To Sync not being shown for new FxA users in Fenix](https://github.com/mozilla-mobile/fenix/issues/6737), and that it is in turn caused by a bad interaction between [FxaWebChannelFeature](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FxaWebChannelFeature.kt) and GeckoView. See https://github.com/mozilla/application-services/issues/2650 for some additional investigation.

**STR:**

* Build and install Fenix, and dump logcat somewhere for later reference.
* Enable remote debugging in Fenix
* Go into Fenix settings, select "Turn on Sync", and wait for the resulting page to load. You don't need to actually try to sign in.
* On a desktop browser, connect to Fenix via remote debugging and inspect the accounts page that was loaded by the above.

**Expected Result:**

No webchannel-related errors in logcat output, and no errors logged by the accounts page.

If you proceed to turn on sync by creating a new account, it will ask you to choose what datatypes you want to sync.

**Actual Result:**

Logcat output shows the following:

```
02-18 13:02:57.945  9030  9092 E GeckoConsole: [JavaScript Error: "account_updates error message. No Such Channel" {file: "resource://gre/actors/WebChannelParent.jsm" line: 94}]
02-18 13:02:57.945  9030  9092 E GeckoConsole: _sendErrorEventToContent@resource://gre/actors/WebChannelParent.jsm:94:8
02-18 13:02:57.945  9030  9092 E GeckoConsole: receiveMessage@resource://gre/actors/WebChannelParent.jsm:50:16
02-18 13:02:57.945  9030  9030 D mozac-fxawebchannel: Processing WebChannel command: FXA_STATUS
02-18 13:02:57.945  9030  9030 D mozac-fxawebchannel: Responding to WebChannel status command with {"id":"account_updates","message":{"messageId":"15819913779461","command":"fxaccounts:fxa_status","data":{"capabilities":{"engines":["history","bookmarks","passwords"],"choose_what_to_sync":true},"signedInUser":null}}}
```

The accounts page logs an error saying `WebChannel error: No Such Channel`.

If you proceed to turn on sync by creating a new account, it will default you into syncing all available datatypes without asking you which ones you want to sync (an experience that we like to call the "Surprise Sync!").

---

I've reached the limits of my ability to debug or fix this, but my theory based on the above logcat lines is as follows:

* When the FxA login page loads, it fires a custom `WebChannelMessageToChrome` event to ask the browser about its capabilities, to find out if there's already a signed-in user, and so-on.
* Fenix apparently has two things that are listening for this event:
    * The [`fxawebchannel` webextension](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/accounts/src/main/assets/extensions/fxawebchannel/fxawebchannel.js).
    * The [native `WebChannel` infrastructure built in to Gecko](https://dxr.mozilla.org/mozilla-central/source/toolkit/actors/WebChannelChild.jsm).
* The native `WebChannel` infrastructure in Gecko is the first to respond, and it (quite rightly) returns an error message to the page saying that it's not expecting any webchannel messages.
* The accounts page receives the error, assumes that there must be some configuration problem with the browser, and downgrades the user's sign-in experience accordingly. The lack of Choose What to Sync is the most obvious symptom of this.
* The fxawebchannel webextension responds second, and it (correctly) sends a successful response to the page to advertise its capabilities, including support for Choose What to Sync.
* The accounts page ignores this second response, since it does not have any in-flight webchannel messages that are expecting a response.

I tried to prevent the native Gecko handler from running by adding various combinations of `e.stopImmediatePropagation` and `e.preventDefault` inside the handler in the webextension [here](https://github.com/mozilla-mobile/android-components/blob/82c84b3b8170239442d687216f91ed5387b8fde9/components/feature/accounts/src/main/assets/extensions/fxawebchannel/fxawebchannel.js#L26), but they didn't seem to help. If I were set up to hack on GeckoView, I would try adding various attempts at `if (!e.defaultPrevented)` on the Gecko side [here](https://dxr.mozilla.org/mozilla-central/rev/114d8b270dbb4d512650b3918b87d71dbc83ad50/toolkit/actors/WebChannelChild.jsm#). But at this point I figure it's probably time to call in the experts.

@csadilek @vladikoff @snorp, does the above diagnosis make sense, and do you see a clear way forward to resolve it? I'm happy to try hacking on this further if you can point me in a good direction.

**Comment by rfk** [comment]
High-level, I feel like the best option here would be to disable Gecko's builtin `WebChannel` stuff when we're building for GeckoView, since IIUC none of that is exposed to the application, so no good can come of it. But I've no idea how feasible that would be.

**Comment by csadilek** [comment]
Filed GV bug to remove/disable the builtin `WebChannel`: https://bugzilla.mozilla.org/show_bug.cgi?id=1616635

**Comment by csadilek** [comment]
Also linking @vladikoff's PR with the short-term fix: https://github.com/mozilla/fxa/pull/4188

**Comment by rfk** [comment]
Thanks for digging in to this @csadilek!

**Comment by csadilek** [comment]
> Thanks for digging in to this @csadilek!

Sharing w/ @vladikoff @grigoryk :)

**Comment by csadilek** [comment]
@rfk looks like the short-term fix landed. Can we close this issues and track the remainder in https://bugzilla.mozilla.org/show_bug.cgi?id=1616635?

**Comment by rfk** [comment]
> Can we close this issues and track the remainder in https://bugzilla.mozilla.org/show_bug.cgi?id=1616635?

SGTM
