### ISSUE TITLE
FileNotFoundException: /data/data/org.mozilla.fennec_aurora/files/mozilla/y6vzzsen.default/manifests/C2dWGyUpaf5+pzHQl49...

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#5974]
https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/7287348/

```
FileNotFoundException: /data/data/org.mozilla.fennec_aurora/files/mozilla/y6vzzsen.default/manifests/C2dWGyUpaf5+pzHQl49BDQ==.json (No such file or directory)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:231)
    at java.io.FileInputStream.<init>(FileInputStream.java:165)
    at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:2)
    at org.mozilla.fenix.customtabs.FennecWebAppIntentProcessor.fromFile$app_geckoNightlyFennecNightly(FennecWebAppIntentProcessor.kt:2)
...
(11 additional frame(s) were not displayed)

/data/data/org.mozilla.fennec_aurora/files/mozilla/y6vzzsen.default/manifests/C2dWGyUpaf5+pzHQl49BDQ==.json (No such file or directory)
```

**Comment by unicorn-io** [comment]
can i try this?

**Comment by st3fan** [comment]
This is a really odd filename ... `.../C2dWGyUpaf5+pzHQl49BDQ==.json` .. are we sure that is correct? @NotWoods does that Base64 encoded name look correct to you?

**Comment by NotWoods** [comment]
I think the old Fennec code may hash the filenames

**Comment by pocmo** [comment]
Looking at Fennec's code it also protects against the manifest not being loadable anymore and then falls back to just launching Fennec. I guess that's the best we can do here too.
https://searchfox.org/mozilla-esr68/source/mobile/android/base/java/org/mozilla/gecko/webapps/WebAppActivity.java#172-179

**Comment by st3fan** [comment]
Should this move to the general PWA board? Or is this actionable for the migration?

**Comment by pocmo** [comment]
Fixed in Fenix. Since this is not really something we can reproduce I'll move this directly to the "Done" column. Locally I did test this by pretending the manifest file does not exist.
