### ISSUE TITLE
When trying to captureThumbnail on firstContentfulPaint == false, no callback happens

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#5978]
We should just be doing a callback with null. Otherwise those who call into this will never get a response.

**Comment by pocmo** [comment]
Are you planning to use thumbnails in Fenix? I remember we disabled auto-thumbnails for some reason (need to look that up) ... and I wonder if there's an issue if we start using thumbnails. 🤔

**Comment by sblatz** [comment]
@pocmo we are going to use them for an animation when navigating away from GV to avoid the "black flash" users currently see. 

https://github.com/mozilla-mobile/fenix/issues/1901
