### ISSUE TITLE
RegionSearchLocalizationProvider is slow on builds without MLS key

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#5989]
`MozillaLocationService.fetchRegion` caches a result, but if it doesn't get a result it will continue to to make that request every single time we use the RegionSearchLocalizationProvider

**Comment by pocmo** [comment]
Afaik you should also get a result with a dummy key - but it is rate limited. Are you sure you do not get anything back? 🤔

**Comment by boek** [comment]
Oops! We were using an empty string. I will try a dummy key and close this out!

**Comment by boek** [comment]
@pocmo Is there a specific dummy key to use? I am getting this response  `{"error":{"errors":[{"domain":"usageLimits","reason":"keyInvalid","message":"Missing or invalid API key."}],"code":400,"message":"Missing or invalid API key."}}` so it always returns null bypassing the cache

**Comment by pocmo** [comment]
I'll take a look.

**Comment by pocmo** [comment]
* I prepared a patch that moves the location service behind an interface. So in situations where we do not want to use it we can use a dummy location service (and AC will provide one).

* `SearchEngineManager` is doing only one request to determine the location. And this is done from `loadSearchEngines()` which is supposed to be called only once (or if the configuration changes). Where are the additional calls into `RegionSearchLocalizationProvider` coming from?
