### ISSUE TITLE
Fennec migration: Auto-sign in card is not displayed on the onboarding screen

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#5991]
## Preconditions:
Login on Fennec Release.
## Steps to reproduce
1. Replace Fennec Beta/Nightly with Fenix Beta/Nightly;
2. Launch Fenix and go to the onboarding screen;
3. Observe the Sign in card from the onboarding screen.
### Expected behavior
On the Sign in card from the onboarding screen, the "Yes, sign me in" button is displayed to sign in automatically with the same account. [screenshot](https://drive.google.com/file/d/1nHuFtffPA_JgNC6heJ317VPO_kEAXf3Y/view)
### Actual behavior
On the Sign in card from the onboarding screen, the app doesn't detect that you are signed in on Fennec. [screenshot](https://drive.google.com/file/d/1SjAu9l3ybCk0jFGt8jsN0JWDUBFbD4Ki/view)
### Notes:
Not reproducible on Fenix RC 3.2.1 1/25 GV 73, Fenix Nightly 2/13 GV 74;
On Fenix Beta 3.2.0-beta.3 1/25 GV 73, there is issue https://github.com/mozilla-mobile/fenix/issues/6521 filed, but since this is reproducible on the all Migration builds, I filed a separate issue for this.
### Device information

* Android device: Samsung Galaxy Note 8 (Android 9);
* Fenix version: 
 Fennec Nightly Migration build 9 2/14 GV 75; 
 Fennec Release Migration 2/19 GV 74;
 Fennec Beta Migration build 2/19 GV 74;

**Comment by Sparky93** [comment]
Tested this multiple times on Nightly with Samsung S8+ (Android 8.0.0), Google Pixel 3 (Android 10) and Samsung S8 (Android 9) and I couldn't reproduce this, not even once.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/20266431/75450233-19f9c100-5977-11ea-9578-26e5e9316640.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/20266431/75450279-2aaa3700-5977-11ea-8230-87996ea8b4f6.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/20266431/75450298-3695f900-5977-11ea-96e6-4546b1f524f4.png">

**Comment by ebalazs-sv** [comment]
This is still reproducible on Fennec Beta Migration Build 2 from 02/27 with LG G7 fit (Android 8.1).
As I mentioned in the description, if Fennec Release is logged in and Fennec Beta is not logged in, after migration on the Fenix Beta onboarding an auto-sign in card must be displayed [screenshot](https://drive.google.com/file/d/11PdhqKXgDim96O0Vx_xO5bs8Lt4qCO0T/view) detecting that you are already connected with an account on Fennec Release.
Due to that, I will reopen the issue.

**Comment by Sparky93** [comment]
I'm a bit stuck with this issue, for the moment I concluded that this content provider is **null**,
https://github.com/mozilla-mobile/android-components/blob/db07d45ddbcf5a8338f80f9236b3dce37cb36cba/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sharing/AccountSharing.kt#L94-L98 with the current **authStateUri**, but if we get rid of the **content://** scheme we receive an IllegalStateEx with a weird reason (it's obvious that is the same authority)
![image](https://user-images.githubusercontent.com/20266431/76196987-f98dfa00-61f3-11ea-9f78-4b2a3531dc4e.png)

If someone has a better approach, please let me know or feel free to tackle this issue.

**Comment by st3fan** [comment]
This does not apply to the release migration.

**Comment by ebalazs-sv** [comment]
Moving this to Done, since there is no fix to be verified.
