### ISSUE TITLE
[A-C] Update complete notification is not routing to onboarding screen

### ISSUE THREAD

**Issue by Sparky93** [mozilla-mobile/android-components#5996]
1. Update from Fennec to Fenix
2. Place the app in the background
3. Tap on "Update complete" notification

Expected behavior:
Onboarding screen is being shown.

Actual behavior:
Migration progress screen is being shown.

**Comment by jonalmeida** [comment]
@Sparky93 if you're working on this, I'll close the other issue as a duplicate. 🙂

**Comment by Sparky93** [comment]
@jonalmeida Agree, but also I talked with @pocmo and this ticket is being to be closed by his work on [#8488](https://github.com/mozilla-mobile/fenix/issues/8488)

**Comment by Sparky93** [comment]
Sorry @jonalmeida , I misunderstood, both of the tickets are required.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Beta Migration Build 2, 02/27 with LG G7 fit (Android 8.1), Samsung Galaxy S5 (Android 6.0.1) and tapping the "Update complete" notification displays the onboarding screen.
I will move this to Done. Thanks.
