### ISSUE TITLE
Update to application-services v0.52.0

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/android-components#5999]
We should get the previous update in https://github.com/mozilla-mobile/android-components/pull/5882 landed first, but filing this for tracking since there are quite a few important changes in this release.  I think it would be reasonable for someone from the a-s team to pick this up.

Here's my android-specific summary of the changelog:

Sync:
* Significantly reduced network activity during the normal course of syncing, thanks to:
    * Better caching of the tokenserver token and info/configuration response.
    * Less network requests will be made in the case nothing has changed on the server.

Places:
* Added a new field reasons which is a List of SearchResultReasons in SearchResult.
* Some places import related issues fixed
* **Breaking change**: The PlacesWriterConnection.resetHistorySyncMetadata and PlacesWriterConnection.resetBookmarkSyncMetadata methods have been moved to the PlacesApi class.

FxA:
* **Breaking change**: A few changes were made in order to decouple device commands from "account events":
        * The AccountEvent enum has been refactored: .TabReceived has been replaced by .IncomingDeviceCommand(IncomingDeviceCommand), IncomingDeviceCommand itself is another enum that contains TabReceived.
        * FirefoxAccount.pollDeviceCommands now returns an array of IncomingDeviceCommand.
* FirefoxAccount.handlePushMessage now handles all possible FxA push payloads and will return new AccountEvents:
        * .ProfileUpdated which should be handled by fetching the newest profile.
        * .AccountAuthStateChanged should be handled by checking if the authentication state is still valid.
        * .AccountDestroyed should be handled by removing the account information (no need to call FirefoxAccount.disconnect) from the device.
        * .DeviceConnected can be handled by showing a " is connected to this account" notification.
        * .DeviceDisconnected should be handled by showing a "re-auth" state to the user if isLocalDevice is true. There is no need to call FirefoxAccount.disconnect as it will fail.

* Added a deviceId property to the AccountEvent.deviceDisconnected enum case.
* Added context=oauth_webchannel_v1 in getManageDevicesURL methods for WebChannel redirect URLs.

Push:
* Android: Exposed GeneralError to the Kotlin layer.

**Comment by mhammond** [comment]
I'm having a bash at this.
