### ISSUE TITLE
Update manifests to match package name

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#60]
After PR #55 lands update all manifests to match the package name of the code.

For example: org.mozilla.toolbar should match mozilla.components.toolbar

**Comment by pocmo** [comment]
Android package names need to be unique (when merged together). So if we want them to match the source packages then we need to make them unique too. So this means we can't have concept-toolbar and browser-toolbar have both use "mozilla.components.toolbar".

Maybe it makes sense to add the same prefix we use in the module names in the packages too (and eventually in the artifact/group ids), e.g.:

* concept-toolbar => mozilla.components.concept.toolbar
* browser-toolbar => mozilla.components.browser.toolbar
* concept-engine => mozilla.components.concept.engine
* browser-engine-gecko => mozilla.components.browser.engine.gecko (Does it make sense to drop "engine" here? ~browser-gecko => mozilla.components.browser.gecko ?

**Comment by csadilek** [comment]
We decided mozilla.components.browser.engine.gecko is fine and consistent.
