### ISSUE TITLE
Fennec migration: The migration steps are overlapping the text in split mode landscape view

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#6001]
## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix using a build from [here](https://firefox-ci-tc.services.mozilla.com/tasks/index/project.mobile.fenix.v2.fennec-nightly.2020.01.16.revision/9c25d274d0d3c6549f607ce1298471ca6627a8d4).
2. With the onboarding migration screen displayed, long tap the Recent apps button;
3. In split view, rotate the device in landscape mode;
4. Observe the migration steps from the migration onboarding screen;
### Expected behavior
The migration steps are displayed when scrolling the list.
### Actual behavior
The migration steps are overlapping the text.
### Notes:
[Video](https://drive.google.com/file/d/1qSfCEHMH6zyDhL0MmCQg_Ru-CSq78Pe4/view);
Not reproducible on LG G7 fit (Android 8.1), 1440 x 3120 pixels, 19.5:9 ratio (~563 ppi density);
### Device information

* Android device: Huawei P9 Lite (Android 7), resolution 1080 x 1920 pixels;
* Fenix version: Beta migration build 02/19.

**Comment by Sparky93** [comment]
![image](https://user-images.githubusercontent.com/20266431/75345093-b1daaa80-58a4-11ea-8b37-9829fa48c9e0.png)

**Comment by Sparky93** [comment]
Also screenshot in landscape 
![image](https://user-images.githubusercontent.com/20266431/75345771-0fbbc200-58a6-11ea-97cd-477fe2fa1926.png)

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta Migration build 2 with Huawei P9 Lite (Android 7), resolution 1080 x 1920 pixels. The migration steps are not overlapping the text in split view when in landscape mode.
I will move this to Done. Thanks!
I filed a new related issue: https://github.com/mozilla-mobile/android-components/issues/6113
