### ISSUE TITLE
"Start Firefox Nightly" button shown after migration does not launch Firefox

### ISSUE THREAD

**Issue by andreasbovens** [mozilla-mobile/android-components#6003]
After my Fennec Nightly build has been migrated to Fenix, a "Welcome to an all-new Firefox Nightly" is shown. 

Tapping on the purple "Start Firefox Nightly" button just closes that screen but it does not launch the updated app.

Launching Fennec/Fenix from the home screen however results in the new UI being shown, with all data migrated. 

[20200219_185854.mp4.zip](https://github.com/mozilla-mobile/android-components/files/4231170/20200219_185854.mp4.zip)

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta Migration Build 1 with LG G7 fit (Android 8.1), following the steps:

1. Replace Fennec with Fenix;
2. Launch Fenix and tap the "Start Firefox" button from the migration onboarding screen.

Expected result:
The migration onboarding screen is dismissed and the onboarding screen with the "Start browsing" button is displayed.

Actual result:
Fenix closes and when the app is relaunched, the migration onboarding screen is displayed.

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/fenix/commit/388c7017d8378500eb986e5473465572055d804a

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Beta Migration Build 2, 02/27 with LG G7 fit (Android 8.1). Tapping the "Start Firefox Beta" button displays the onboarding screen.
I will move this to Done. Thanks.
