### ISSUE TITLE
Add support for FxA staging servers to fxawebchannel extension

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#6012]
The extension's content script currently doesn't run for the pages returned from the staging server.

**Comment by csadilek** [comment]
@rfk: @vladikoff and I talked about this. QA has integration tests running against staging and currently needs to turn off web channel support. Any concerns adding the staging URL to the manifest of fxawebchannel extension?

**Comment by rfk** [comment]
> Any concerns adding the staging URL to the manifest of fxawebchannel extension?

Sorry, but yes, I do have concerns - I don't think it should be possible for our stage environment to interrogate or influence the signed-in state of users of our production browser.

I don't have a specific vulnerability in mind, but if there were some unforeseen consequence that put users data at risk, I really don't want to have to write a press release that includes the words "we gave elevated production permissions to our stage environment".

Would it be possible to instead make a copy of the webextension that is configured to run in the stage environment, and choose which one to activate based on some config option?

**Comment by csadilek** [comment]
> Would it be possible to instead make a copy of the webextension that is configured to run in the stage environment, and choose which one to activate based on some config option?

@rfk Definitely possible, yes, but would require a bigger refactoring. We could have a `feature-accounts` (which contains the web ext. currently) and a `feature-accounts-staging` then we can could isolate on the classpath e.g. when running tests `feature-accounts-staging` would be used.

**Comment by vladikoff** [comment]
if we are talking about a bigger refactoring, @rfk should we have the webchannel support for other envs, like self-hosters and dev.lcip boxes? currently this requires a rebuild of a-c

**Comment by rfk** [comment]
> should we have the webchannel support for other envs, like self-hosters and dev.lcip boxes?
> currently this requires a rebuild of a-c

This would be good if possible, ref https://github.com/mozilla-mobile/fenix/issues/3762#issuecomment-587250065.

But IIUC supporting arbitrary domains could be much more complicated, because you'd need to get some value out of config and put it into the manifest for the webextension. So I wouldn't want to hold up support for the stage environment if it's a smaller patch.
