### ISSUE TITLE
Use PackageManager.MATCH_DEFAULT_ONLY in Browsers resolveActivity() calls

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#6041]
Following https://github.com/mozilla-mobile/fenix/issues/8631 it was discovered that on certain devices we need to set the [MATCH_DEFAULT_ONLY](https://developer.android.com/reference/android/content/pm/PackageManager#MATCH_DEFAULT_ONLY) flag for the [PackageManager#resolveActivity (Intent intent, int flags)](https://developer.android.com/reference/android/content/pm/PackageManager#resolveActivity(android.content.Intent,%20int)) we do in `components.support.utils.Browsers`
Otherwise it was seen that `PackageManager#resolveActivity(intent, 0)` would have the side effect of resetting the default browser status.

**Comment by pocmo** [comment]
Calling `resolveActivity(intent, 0)` clears the default??? Is that what we have been seeing on Huawei devices?

**Comment by Mugurell** [comment]
> Calling `resolveActivity(intent, 0)` clears the default??? Is that what we have been seeing on Huawei devices?

Yup, this is one part of the problem (the other being the need to also have the same exact activity as the one declared to handle the http/s schemes).
Although Chrome / Opera don't have a "Set app as default" setting
I saw that navigating on certain screens on Chrome/Opera also resets the default browser so I'm guessing they use the same `resolveActivity(intent, 0)` call.

**Comment by Mugurell** [comment]
[Video](https://drive.google.com/file/d/1hX0bjtfBT5dTrq9w-z_MakECWmmI10-Q/view?usp=sharing) showing that 
- Chrome also resets the default browser status
- Fenix used to reset the default browser status when opening HomeActivity / DefaultBrowserSettingsFragment
- Fenix Beta (local build using the above patch) does not anymore resets the default browser status.

**Comment by pocmo** [comment]
@Mugurell Hm, but this also means that we can really protect against this - assuming that *any* app calling `resolveActivity(intent, 0)` will reset the default state. Or does this only affect the calling app?

**Comment by Mugurell** [comment]
> @Mugurell Hm, but this also means that we can really protect against this - assuming that _any_ app calling `resolveActivity(intent, 0)` will reset the default state. Or does this only affect the calling app?

Indeed, in my tests I saw that any app calling `resolveActivity(intent, 0)` will reset the default browser irrespective of what the default was.
This happens with Fennec, Chrome, Opera (and so probably many others)
I think this is just the best we can do though to protect against unintentional resets from our app.

An important thing to note is that without similar user reports this issue seems to be affecting only a very small part of the users. I can reproduce this on the only Huawei device I have (Huawei Honor 5X with Android 6.0.1 - 100% of the times) but QA can't on other Huawei devices. Also other devices from other OEMs seem to be unaffected.
