### ISSUE TITLE
Add forceExpand to BrowserToolbarBottomBehavior

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/android-components#6048]
We need to be able to force open the toolbar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5033)

**Comment by liuche** [comment]
As part of our Toolbar improvements, can we prioritize this in the AC backlog? cc @snorp

**Comment by snorp** [comment]
Yes, this is pretty critical IMHO.
