### ISSUE TITLE
Engine: Add loadData() functionality

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#605]
Currently we can just load URLs. However WebView and GeckoView also have the ability to load HTML directly. That's something we use in our apps to display internal pages or custom error pages.

That's the API in the Focus abstraction layer:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/web/IWebView.java#L143

Let's compare GeckoView and WebView and try to find a good API that works for both.

**Comment by jonalmeida** [comment]
Default encoding for Android is UTF-8: https://developer.android.com/reference/java/nio/charset/Charset#defaultCharset()

Focus always calls `loadData` with the `historyUrl` as the same value as `baseUri`. So far, this has only been used for `about:home` and `about:blank`:
```java
public static final String URL_ABOUT = "focus:about";

webView.loadData(URL_ABOUT, data, "text/html", "UTF-8", URL_ABOUT);
```
Fennec however doesn't add anything to history at all when loadData is called (from testing in Nightly). Created [bug 1483677][1] to track adding this to GeckoView, but for now we don't need to add it.

[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1483677
