### ISSUE TITLE
Missing persistence callback while going through "can retry migration" flow

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#6053]
We're not registering an account state persistence callback while going through the recovery part of the offline fxa migration flow, which is causing us to endlessly loop in it. Investigation notes in https://bugzilla.mozilla.org/show_bug.cgi?id=1616498

**Comment by ebalazs-sv** [comment]
@grigoryk On this issue do we have to verify if after migration we receive more than one "New sign-in to Firefox" email/device? Thanks!

**Comment by st3fan** [comment]
@ebalazs-sv that was one of the symptoms of this bug - but not all users reported it, and I think we also did not hear about it from QA, so maybe it is a hard to reproduce case?

One thing that could help reproducing this is to migrate and then cold start Fenix a couple of times. I am pretty sure it only happens on cold start. But you would have to test with an older Nightly build to reproduce.

**Comment by ebalazs-sv** [comment]
I tested this on Nightly migration and Beta migration builds from 02/27 with Pixel 2 (Android 9) and LG G7 fit (Android 8.1) and there is one "New sign-in to Firefox" email for each complete migration.

**Comment by ebalazs-sv** [comment]
I tried to reproduce this on Nightly migration build 5 with Pixel 2 (Android 9) and could not reproduce it by cold starting the app multiple times.
@st3fan Since one of the mentioned scenarios was verified in the previous comment, can this issue be moved to Done? Thanks.

**Comment by st3fan** [comment]
@ebalazs-sv Yes lets move it.
