### ISSUE TITLE
Stop using IntentService in lib-crash

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#6058]
From https://developer.android.com/reference/android/app/IntentService

> IntentService is subject to all the background execution limits imposed with Android 8.0 (API level 26). Consider using WorkManager or JobIntentService, which uses jobs instead of services when running on Android 8.0 or higher. 

Update to use `JobIntentService`

**Comment by pocmo** [comment]
@rocketsroger CrashHandlerService also gets called by GeckoView if it catches a crash. Does this still work if it is a `JobIntentService`?

https://github.com/mozilla-mobile/fenix/blob/39db8c9557dcd55a987e073744a2f63c052a1203/app/src/geckoNightly/java/org/mozilla/fenix/engine/GeckoProvider.kt#L49

**Comment by rocketsroger** [comment]
> @rocketsroger CrashHandlerService also gets called by GeckoView if it catches a crash. Does this still work if it is a `JobIntentService`?

Yes, I've tested with both `about:crashparent` and `about:crashcontent` to make sure when GeckoView looks for the CrashHandlerService it will work the same way.

**Comment by rocketsroger** [comment]
Reverting the change.  Reopen to be implemented once a better solution can be found.

**Comment by rocketsroger** [comment]
related: https://github.com/mozilla-mobile/android-components/issues/8511

**Comment by rocketsroger** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/issues/8511
