### ISSUE TITLE
Notifications for PWAs should be high priority; others should be low

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6081]
For WebNotifications that are meant for PWAs, we want push notifications to show up with [PRIORITY_HIGH][0] since they are more important for users to see them.

For the rest, we should use the regular priority level as web content can cause unnecessary alerts.

[0]: https://developer.android.com/reference/android/support/v4/app/NotificationCompat#priority_high

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5062)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796437

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
