### ISSUE TITLE
Detect when we change a database schema without adding a migration for it

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#6093]
Let's discuss about which possible solutions we can have to prevent early this issue.

**Comment by Amejia481** [comment]
cc @pocmo @jonalmeida @rocketsroger @csadilek @psymoon @grigoryk

**Comment by Amejia481** [comment]
I was thinking about a possible lint rule that help us with that, it is weird that there is not something already in room for that.

**Comment by pocmo** [comment]
A lint rule would be nice. But I assume writing a lint rule is pretty hard since it is hard to know whether a migration will be needed by just looking at the code?

Room supports writing schema migration tests, e.g.:
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/pwa/src/androidTest/java/mozilla/components/feature/pwa/db/ManifestDatabaseMigrationTest.kt
I wonder if we can use that to write a more generic test that performs all the migrations? And then tries to read/write data?

Or maybe a combined approach. If the tests follow a strict naming convention then a lint rule could be triggered if there is no migration test for every schema version?

**Comment by Amejia481** [comment]
> Or maybe a combined approach. If the tests follow a strict naming convention then a lint rule could be triggered if there is no migration test for every schema version?

Yes, I think have a generic test that read and write could be a good alternative!
I will also take a look to the "Android Study Group" slack group to see if there is something mentioned there too.

**Comment by Amejia481** [comment]
Another thing that I noticed that could help us to spot a missing migration is that  file `schemas/#.json` has changed but file is not committed

**Comment by Amejia481** [comment]
There is a way to run all the migrations to check for integrity  https://developer.android.com/training/data-storage/room/migrating-db-versions#all-migrations-test I'm not sure how we can make that generic for all components that are using room, unless we enforce some strict naming convention or an `is a` relationship between all the classes that use room.

**Comment by Amejia481** [comment]
After we build every component we can run a script that verifies if there are none untracked files, if there are we fail the tests.

```bash
set -ex
OUTPUT=$(git status) 

if [[ "$OUTPUT" == *"Untracked"* && "$OUTPUT" == *".json"* ]]; then
    echo '"Possible missing migration, there is a room untracked file'
    exit 0
fi
```

Another line of defence is to create a test that test run all the migrations as [shown here](https://developer.android.com/training/data-storage/room/migrating-db-versions#all-migrations-test).

What do you think? @pocmo

**Comment by grigoryk** [comment]
> After we build every component we can run a script that verifies if there are none untracked files, if there are we fail the tests.

Would that live in a task that's similar to `complete-pr`?

This would make a good pre-push hook (and have it emit a warning?), to help shorten the cycle a bit. Locally, I think you'd want a slightly more specific check than `*".json"*` though.

**Comment by Amejia481** [comment]
> Would that live in a task that's similar to complete-pr?

Yes.

> This would make a good pre-push hook (and have it emit a warning?), to help shorten the cycle a bit. Locally, I think you'd want a slightly more specific check than *".json"* though.

Having it as a pre-push will be a great idea, additionally  I think we could need a way to verify on CI too :)
Yes we can improve the check by adding a number as part of the file `*"([0-9]*).json"*`.
If we have it on CI any untracked file could be a possible red flag.

**Comment by pocmo** [comment]
If you want to be super strict then we probably should also not allow the modification of an already commited schema. That would imply that someone modified the schema and did not set a new version and create a migration. We probably should consider everything that landed in the repo as published (which with out nightly builds is not that unlikely) and therefore requiring a new schema version and migration when changed.

**Comment by Amejia481** [comment]
> If you want to be super strict then we probably should also not allow the modification of an already commited schema. That would imply that someone modified the schema and did not set a new version and create a migration. We probably should consider everything that landed in the repo as published (which with out nightly builds is not that unlikely) and therefore requiring a new schema version and migration when changed.

I like the idea, this way we can enforce that every time someone modifies the schema **MUST** update the db version and subsequently create a migration.

**Comment by Amejia481** [comment]
@pocmo  I'm working on generic test to run all the migrations but I noticed that we are not running Android tests on CI this is one prerequisite for this ticket, maybe this is one of the reasons why we didn't caught some issues before. I thought we were already doing that, do you know why it is that?

**Comment by pocmo** [comment]
We are running Android instrumentation tests on Firebase for components configured here:
https://github.com/mozilla-mobile/android-components/blob/9987b74993340250e88bfa7fc11530d07c2caf08/taskcluster/ci/test/kind.yml#L51-L72

If there are more/new components with tests to run there then let's add them. :)

**Comment by Amejia481** [comment]
Oh I didn't know that, thanks :) 
There are other components that have android instrumentation tests that are not added there, this is the reason why they are failing locally.

**Comment by Amejia481** [comment]
We haven't has any recent incidents, so far adding instrumentation tests for migrations have been sufficient. I'll close the issue for now. Please feel to re-open if it's needed.
