### ISSUE TITLE
DownloadUtilsTest: Use org.junit.*

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#61]
In DownloadUtilsTest we import "junit.framework.Assert.assertEquals" which is deprecated. This should use org.junit.Assert.

**Comment by shikhart98** [comment]
@pocmo I think by just including `import org.junit.Assert.assertEquals` instead of `junit.framework.Assert.assertEquals` works.

**Comment by pocmo** [comment]
@shikhart98 Yep. That's exactly what is needed here! :)
