### ISSUE TITLE
Upstream WebExtension changes from Fenix to AC

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#6108]
As the WebExtension feature is polished in Fenix, we should consider upstreaming the changes back to the sample-browser and reference-browser.

I am using this issue to keep track of Fenix PRs that might be a candidate for upstream:
https://github.com/mozilla-mobile/fenix/pull/8829

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5091)

**Comment by csadilek** [comment]
Agreed for r-b, but we don't really need all fixes for UI edge cases in sample browser I think. It exists for demo and quick testing purposes.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796321

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
