### ISSUE TITLE
Rewrite TypographyEllipsis to be only performed on source language?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6118]
In #6117 we are disabling `TypographyEllipsis` because we do not want it to affect all translations. 

Can we implement our own version of that check that only performs this check on the source language?

Implementation:
https://cs.android.com/android/platform/superproject/+/master:tools/base/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/TypographyDetector.java;l=252-259

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5096)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795354

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
