### ISSUE TITLE
preferred color scheme suddenly dooesn't change

### ISSUE THREAD

**Issue by tmdwns7809** [mozilla-mobile/android-components#6132]
I'm sure like two days ago i saw it working perfectly
if i change color scheme to PreferredColorScheme.Dark or GeckoRuntimeSettings.COLOR_SCHEME_DARK
it changed web paege color to dark but today i checked it suddenly doesn't work anymore
Could you please check this? thank you so much

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5107)

**Comment by csadilek** [comment]
This seems to work now. Please re-open if you still experience problems.
