### ISSUE TITLE
Add setter for toolbar menu dismiss action

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#6140]
Related to : https://github.com/mozilla-mobile/fenix/issues/7408

We require a way to listen to the dismissal of the menu, so that we can perform some action in Fenix.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5114)

**Comment by csadilek** [comment]
This landed in https://github.com/mozilla-mobile/android-components/pull/6141.
