### ISSUE TITLE
Tabs tray closes when tab switcher is pressed and no tabs open

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6145]
Related: https://github.com/mozilla-mobile/reference-browser/issues/1033

## STR:
1. Open Sample or Reference Browser.
2. Close all tabs.
3. Toggle between the browser view and the tabs tray view.

## Expected
 - Toggling works seamlessly without any non-user interacted changes.

## Actual
 - Clicking on the menu, flashes the tabs tray and switches back to the browser view.

**Comment by pocmo** [comment]
Ah, that is probably caused by my refactoring to use `browser-state`.
