### ISSUE TITLE
Capture geckoview version for Fenix baseline ping

### ISSUE THREAD

**Issue by wcbeard** [mozilla-mobile/android-components#6152]
geckoview version is currently not available in the `org_mozilla_fenix` or `org_mozilla_fenix_nightly` baseline table. If possible, could this be added to the baseline ping? 

This would allow for Fenix baseline pings to be tied to Socorro data.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5127)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795130

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
