### ISSUE TITLE
Call speculativeConnect() only once for search engine

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6154]
With the change in PR #6111 we will call `speculativeConnect()` for the search URL whenever the user changes the text in the URL bar.

This seems over-eager since those connect calls are all for the same host anyways.

Looking at Firefox code it seems like they do a speculative connect for the search URL and suggest URL once the toolbar gets focused. This seems a good place to do an early connect since we will need suggestions once the user starts typing and if the user performs a search we already have a connection too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5128)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795154

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
