### ISSUE TITLE
Fennec migration: A second Fenix Beta is launched after tapping on the "Update complete" notification in split view

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#6158]
## Preconditions:
Have Fennec Beta installed.
## Steps to reproduce
1. Replace Fennec Beta with Fenix Beta;
2. Long tap the Recent apps button to go in to split view.
3. Tap the "Update complete" notification;
4. Long tap the Recent apps button to go in to exit the split view;
5. Tap the Recent apps button and observe the Fenix Beta;
### Expected behavior
Fenix Beta is displayed in the Recent apps once.
### Actual behavior
Fenix Beta is displayed in the Recent apps twice.
### Notes:
[Video](https://drive.google.com/file/d/1-1NUbW3md0e-EgFVZkz0pVKPvPPtoIIb/view)
[logcat](https://github.com/mozilla-mobile/android-components/files/4281224/splitview.txt)
This is reproducible only when the "Update complete" notification is tapped.
When the migration onboarding screen is dismissed by tapping the "Start Firefox" button, this is not reproducible.
One of the instances remains stuck on the migration onboarding screen.
Not reproducible on Beta migration build 1, 02/24.
### Device information

* Android device: Motorola Nexus 6 (Android 7.1.1); LG G7 fit (Android 8.1);
* Fenix version: Beta migration build 2, 02/27; Nightly migration build 3/3;

**Comment by ebalazs-sv** [comment]
This is reproducible on Beta Migration Build 3, 3/4 with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
This is still reproducible on Beta Migration build 4, 3/24, with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
@Sparky93 Hi! Can you please provide a code change link? Thanks!

**Comment by st3fan** [comment]
Too much of an edge case.

**Comment by ebalazs-sv** [comment]
Moving this to Done, since there is no fix to be verified.
