### ISSUE TITLE
"1 new permissions are required"

### ISSUE THREAD

**Issue by cadeyrn** [mozilla-mobile/android-components#6168]
https://github.com/mozilla-mobile/android-components/blob/0ac705bd955064efe384a125be72db9b37c01309/components/feature/addons/src/main/res/values/strings.xml#L113

(Picture stolen from Twitter, https://twitter.com/FirefoxPreview/status/1235150342893056002):

![ESQisD1XcAAnCRV](https://user-images.githubusercontent.com/1100614/75874078-51ea8380-5e11-11ea-92f6-1b4f95343d95.jpg)

"1 new permissions are required" should be "1 new permission is required"

**Comment by hackel** [comment]
Shouldn't the notification also list _which_ new permissions are required?  Tapping the main notification just opens Fenix and the notification goes away without updating the addon.

**Comment by cadeyrn** [comment]
@hackel yes, but it has nothing to do with this report. Can you please file a separate issue for that? Thank you.

**Comment by Amejia481** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/6262
