### ISSUE TITLE
Store non-persistent site permission requests until the session is refreshed

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#6173]
After a non-persistent site permission request is allowed/denied  do not accept more requests of the same type until the session is refreshed.  For more context refer to https://github.com/mozilla-mobile/fenix/issues/5256

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5145)

**Comment by Amejia481** [comment]
Related https://bugzilla.mozilla.org/show_bug.cgi?id=1619678

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796461

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
