### ISSUE TITLE
Use app version for Socorro crash reports

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#6186]
Currently GeckoView version is used for Socorro crash reports.  The correct version number should be the app version.

**Comment by ebalazs-sv** [comment]
I can reproduce this on Beta Migration build 3 with Pixel 2 (Android 9), following the steps:
1. Replace Fennec with Fenix;
2. Open some web pages;
3.Use about:crashparent to crash the app;
4. Go to https://crash-stats.mozilla.com/, find the crash and observe the version;

The version is 74.0b0.
This will be verified in the next Beta Migration build 4.

**Comment by LaurentiuApahideanSV** [comment]
Currently in Beta Migration Build (75.0.0-beta.1) when a crash is encountered the version found at https://crash-stats.mozilla.com/ is 75.0.0-beta.1b0. @rocketsroger Is this the correct app version?

**Comment by rocketsroger** [comment]
@LaurentiuApahideanSV It should be the application version.  Here's an example that I just createded using `about:crashparent`.  https://crash-stats.mozilla.com/report/index/1395e666-cba2-4fa5-b089-ed23e0200325.  The version is 1.0.2013.

**Comment by rocketsroger** [comment]
Dashboard is now updated with the new version numbers.  For example 1.0.2013: https://crash-stats.mozilla.com/topcrashers/?product=Fenix&version=1.0.2013

**Comment by LaurentiuApahideanSV** [comment]
@rocketsroger I tested the issue on the latest Beta migration build

On our current build when a crash is performed the version found in https://crash-stats.mozilla.com/ is 75.0.0-beta.2b0 which correlates with what is found in the "About Firefox" section (75.0.0-beta.2), however we were unable to generate a crash with a version of 1.0.2013.

Our question is where can the app version be found in Firefox Preview? Is it the first line found in the "About Firefox" section?

Crash example: https://crash-stats.mozilla.com/report/index/cd13d054-e071-42fd-b7c2-b73cf0200326
![Screenshot_20200326-162623](https://user-images.githubusercontent.com/50983519/77667274-a43f4000-6f8a-11ea-8be1-6788873609ab.jpg)

**Comment by rocketsroger** [comment]
> Our question is where can the app version be found in Firefox Preview? Is it the first line found in the "About Firefox" section?

I get the version number from application info in Android Settings.  But it is interesting that I can see the crash you triggered have the release channel fix (shows beta) but the version is still incorrect.  (shows 75.0.0-beta.2b0)

**Comment by LaurentiuApahideanSV** [comment]
@rocketsroger 
Currently the crash version generated for Firefox Preview Beta Migration build 75.0.0-beta.2 (Build #2015730659) is "75.0.0-beta.2b0" (https://crash-stats.mozilla.com/report/index/21826731-a315-45f0-9ac6-c0c880200327).

I also checked the version of Firefox Preview in the Settings -> Application -> App info and it is "75.0.0-beta.2".
Is this the correct version that should be found when searching for a crash on https://crash-stats.mozilla.com/ for this particular build?

Also, what build are you using that generates crash signatures with version  1.0.2013?

![Screenshot_20200327-171312](https://user-images.githubusercontent.com/50983519/77774177-54787b80-7053-11ea-9f63-eee7fb9d93e1.jpg)

**Comment by rocketsroger** [comment]
@LaurentiuApahideanSV I'm using a build from nightly.  I suspect different way of crashing at the end got a different version depending on which process crashed.  How are you crashing Fenix to reproduce the report?

I've also started changes in A-C so we can pass application version from Fenix directly so its always the right value.  https://github.com/mozilla-mobile/android-components/pull/6410.  I'll open a Fenix PR today.

**Comment by rocketsroger** [comment]
@LaurentiuApahideanSV Looks like I've made a mistake.  Versions with `1.0.2013` can only show up on local developer build.  `75.0.0-beta.2` is the correct version in crash reports.  I'll update the Socorro dashboard.

**Comment by ebalazs-sv** [comment]
@rocketsroger Thank you for you reply. Since 75.0.0-beta.2 is the correct version, this was verified in https://github.com/mozilla-mobile/android-components/issues/6186#issuecomment-604511159. Due to that we can move this to Done.

**Comment by rocketsroger** [comment]
> @rocketsroger Thank you for you reply. Since 75.0.0-beta.2 is the correct version, this was verified in [#6186 (comment)](https://github.com/mozilla-mobile/android-components/issues/6186#issuecomment-604511159). Due to that we can move this to Done.

Thanks!
