### ISSUE TITLE
Create assertion to execute only in the main process

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6188]
It seems like a pitfall for projects that need to execute code only in the main app process that every app needs to write.

For example: https://github.com/mozilla-mobile/reference-browser/blob/master/app/src/main/java/org/mozilla/reference/browser/BrowserApplication.kt#L34-L40

We could make this easier by either writing some sort of assertion, lint check, or extension function.

**Comment by psymoon** [comment]
Something like this https://github.com/mozilla-mobile/android-components/blob/master/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt#L136?

Possibly related:
https://github.com/mozilla-mobile/android-components/issues/2312, https://github.com/mozilla-mobile/android-components/issues/2207

**Comment by jonalmeida** [comment]
Nice find! I should have done a grep first before filing. I'll file separate issues for each repo do use them then.
