### ISSUE TITLE
SessionManager.onTrimMemory(): Do not close playing session

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6192]
If we are currently playing media in the background then let's not close this session (like the selected session) in `onTrimMemory()` - except if the level is very high.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5170)

**Comment by pocmo** [comment]
I would like to do this after the media feature was migrated to `browser-state`: #4287

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796226

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
