### ISSUE TITLE
Add duration measurement for each migration

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6196]
To better understand the per-type and total time of the migration process, we would like to add a duration in milliseconds field to the migration ping. Similar to the `duration` field we have for _bookmarks_ and _history_ currently.

This will allow us to better understand the time it takes to run the migration and compare that against other metrics.

cc @ecsmyth

**Comment by AndiAJ** [comment]
Hi, I've just checked this matter on Fenix 74.0.0-beta.3 migration build using a Google Pixel 3a (Android 10)

I've noticed that the **"timespan"** (duration in milliseconds) **is displayed only for the history and bookmarks migration pings**, on the other hand **no "timespan" is displayed for the rest of the migration pings**.

History migration - Ping 90b28a17-4250-48cd-b826-2e629edc82ba
Bookmarks migration - Ping a989d075-4eeb-48d2-b6a8-80dbffe2b44b

[Logcat](https://github.com/mozilla-mobile/android-components/files/4354581/BeMgr.txt) 
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-testMigr19030)

@grigoryk - Shouldn't this be applicable to the rest of the migration pings?
Please review and share your thoughts. ☺️

**Comment by AndiAJ** [comment]
Hi, **verified as fixed** on the latest **`75.0.0-beta.2 (Build #2015730659) from 3/25`** using the following devices:
• Google Pixel 3a (Android 10)
[Logcat](https://github.com/mozilla-mobile/android-components/files/4381741/pix.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-testMigra2503000)

• OnePlus A3 (Android 6.0.1)
[Logcat](https://github.com/mozilla-mobile/android-components/files/4381740/one.txt)
[Glean dashboard](https://debug-ping-preview.firebaseapp.com/pings/aj-testMigra2503001)
