### ISSUE TITLE
Autocomplete is not generated on first key press

### ISSUE THREAD

**Issue by codrut-topliceanu** [mozilla-mobile/android-components#6202]
[Original issue](https://github.com/mozilla-mobile/fenix/issues/8560)

## Steps to reproduce
- Click URL bar
- Type fivethirtyeight.com and hit enter
- Click URL bar
- Type "f"

### Expected behavior
"fivethirtyeight.com" autocompletes. If I visited rockpapershotgun.com and typed "r", this would be the behavior.

### Actual behavior
"fivethirtyeight.com" does not autocomplete as this works for other pages. Even if I type "fiv" for which there is no built-in autocomplete, nothing completes.

### Device information

* Android device: P2
* Fenix version: Nightly 200219

**Comment by rocketsroger** [comment]
@codrut-topliceanu This issue is now fixed?

**Comment by codrut-topliceanu** [comment]
Just did a quick test on the latest nightly from Google Play and indeed it is. Thanks for all your help :D

**Comment by rocketsroger** [comment]
Confirmed fixed.  Closing.
