### ISSUE TITLE
`ShiftDrawable$1.onAnimationUpdate`, `performTraversals` uses CPU during idle

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#622]
Running samples-toolbar, using the Android CPU profiler in instrumented mode, the flame chart shows `onAnimationUpdate` uses a lot of CPU:
![screen shot 2018-08-15 at 16 33 58](https://user-images.githubusercontent.com/759372/44178913-5ae9f780-a0a9-11e8-93af-6b488e234716.png)

It uses ~15% of the CPU used during this time which seems like a lot given there are no animations occurring. Other large CPU use during this time is `performTraversals`, which this might be causing (or maybe vice versa!).

**Comment by pocmo** [comment]
This is in ui-progress - which is used by browser-toolbar but which you do not even use/need in your app. I'll investigate.

**Comment by pocmo** [comment]
@walkingice FYI: Either this is only in our component version or Fennec and Rocket may be affected too.

**Comment by pocmo** [comment]
> @walkingice FYI: Either this is only in our component version or Fennec and Rocket may be affected too.

Rocket is affected too. They use the original Java implementation so this is at least not caused by our Kotlin-ified version. The animator in ShiftDrawable seems to be causing this. It should only invalidate the drawable if it's visible. But isVisible returns always true.

**Comment by pocmo** [comment]
Explicitly setting AnimatedProgressBar to GONE (so that the Drawable is invisible) and not starting the animator from init() reduces the CPU usage to 1-3% (from about 12-15%). It's still higher than what we get if we remove `ui-progress` completely (which is 0-1%).

**Comment by pocmo** [comment]
It seems like the animator does never stop. I wonder if we should switch to Android's `ProgressBar` in `browser-toolbar` for now. We can debug `AnimatedProgressBar` separately but this will unblock shipping an app with `browser-toolbar`.

**Comment by pocmo** [comment]
> It seems like the animator does never stop. I wonder if we should switch to Android's ProgressBar in browser-toolbar for now. We can debug AnimatedProgressBar separately but this will unblock shipping an app with browser-toolbar.

I'd still land the `ui-progress` improvements to improve the situation for Focus (and potentially Rocket).

**Comment by pocmo** [comment]
tbh even if we are animating then 15% CPU usage seems high: That's 15% we can't use for actually loading, parsing and rendering the page.

**Comment by pocmo** [comment]
I'll use this issue to land a fix for 0.19.1 (not using `ui-progress` in `browser-toolbar`) and continue with `ui-progress` in #631.
