### ISSUE TITLE
Add doc file to track all extra crash info sent to Socorro server

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#6223]
Currently we add app information and some extra information to Socorro during a crash.  These are not tracked in a central location.  Add a file that will specify all extra information on top of the information from GeckoView.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5196)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795148

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
