### ISSUE TITLE
Simplify display URL

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/android-components#6245]
See https://github.com/mozilla-mobile/fenix/issues/7077

Given the limited space for displaying a URL, we would like to remove omit `https://www` where possible, and scroll to the end of the eTLD.  Security is OK with this, so long as we satisfy some requirements (see https://github.com/mozilla-mobile/fenix/issues/7077#issuecomment-592674049).

Looking through the code, my (uninformed) partial implementation would be:

URLStringUtils.kt in support-utils
```kotlin
data class DisplayUrl(val originalUrl: CharSequence, val displayUrl: CharSequence) {

    companion object {
        fun from(url: CharSequence): DisplayUrl = TODO()
    }
}
```

DisplayToolbar in browser-toolbar
```kotlin
private var _url: DisplayUrl? = null
internal var url: CharSequence
    get() = _url?.originalUrl ?: ""
    set(value) {
        val transformedUrl = DisplayUrl.from(value)
        _url = DisplayUrl.from(value)
        views.origin.url = transformedUrl.displayUrl
        updateIndicatorVisibility()
    }
```

So my questions are:
1) Is this a decent approach?  Is there something else we should be doing instead?
2) Is there existing code we should be using for the logic in `DisplayUrl#from`
3) This implementation does not handle scrolling to the end of the eTLD.  How could we approach that?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5224)

**Comment by csadilek** [comment]
Landed as part of https://github.com/mozilla-mobile/android-components/pull/6232.
