### ISSUE TITLE
Upgrade to a-s v0.55

### ISSUE THREAD

**Issue by linacambridge** [mozilla-mobile/android-components#6253]
The next version of Application Services (tentatively 0.55.0) will have these breaking changes:

- [ ] `PlacesConnection.deletePlace` is renamed to `deleteVisitsFor`, matching the a-c method name, and to reflect its [new behavior](https://github.com/mozilla/application-services/pull/2695) when the page is bookmarked or has a keyword or tags. I think we'll only need to change [this function](https://github.com/mozilla-mobile/android-components/blob/7659534d26e3f0065c6df193c52194279943b606/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt#L152-L159) in a-c to reference the new method name.

**Comment by pocmo** [comment]
@jonalmeida Is that something you wanted to take over?

**Comment by jonalmeida** [comment]
> @jonalmeida Is that something you wanted to take over?

Sure!

Thanks for letting us know @linacambridge !

**Comment by jonalmeida** [comment]
0.55.0 was released, so we can do this upgrade now.
