### ISSUE TITLE
Unsupported add-ons became enabled (weeks) after migration

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#6255]
Report from slack:

I sync'ed my FxA account with Fenix on my Android phone lately. My addons are synchronized (mostly to use the same on my different laptops). Now I have PrivacyBadger enabled in Fenix, although it is not supposed to be compatible/available.

![Screenshot_20200313-140147_Firefox_Nightly](https://user-images.githubusercontent.com/472523/76628679-7f22ea00-6513-11ea-9111-1d567da311eb.png)
![Screenshot_20200313-143124_Firefox_Nightly](https://user-images.githubusercontent.com/472523/76628683-7fbb8080-6513-11ea-8769-ee53a9de4283.png)
![Screenshot_20200313-140133_Firefox_Nightly](https://user-images.githubusercontent.com/472523/76628686-80541700-6513-11ea-9493-80bac146212f.png)

**Comment by csadilek** [comment]
When investigating we found that, after a recent change, we're now triggering updates for unsupported add-ons as well. Not sure if that can cause this, but will put up a fix.

**Comment by csadilek** [comment]
Other report of this in Fenix: https://github.com/mozilla-mobile/fenix/issues/9145

**Comment by csadilek** [comment]
In mozilla-mobile/fenix#9145, we know it was not migration-related. Add-ons were disabled correctly during migration and somehow got enabled prematurely. We still need to confirm if the temporary bug we had that triggered updates for those add-ons is the cause before closing this.

**Comment by madb1lly** [comment]
Hi @csadilek,
Even if this was a bug it was a good test to see which extensions were working 😄 
Cheers 🙂

**Comment by csadilek** [comment]
GV bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1623173

**Comment by csadilek** [comment]
Changes landed in beta and nightly and A-C versions upgraded.

**Comment by csadilek** [comment]
Note to QA to reproduce / verify this:

- Install Fennec
- Install an unsupported add-on (anything but uBlock at this point)
- Migrate to a Fenix Nightly build that uses Gecko 75
- Start Fenix: the add-on will show up as unsupported

--> Up until this point, the steps were already verified in the past and have always worked

- Now update Fenix Nightly so Gecko 76 is used

Without the fix, the add-on is in an inconsistent state i.e. it's active and might send browser actions, but shows as unsupported in the add-on manager.

With the fix, the add-on is still correctly disabled and marked as unsupported after upgrading to a new major Gecko version.

**Comment by ebalazs-sv** [comment]
Hi! I could reproduce this on Pixel 2 (Android 9) and Huawei P9 Lite (Android 7) following the steps:
1. Install Fennec Nightly;
2. Install unsupported add-ons, Privacy Badger, Ghostery, NoScript;
3. Migrate to Fenix Nightly from 3/4 GV 75;
4. Update to a build from 3/15 GV 76;

Using the latest Fennec Nightly Migration build from 3/23 GV 76, the unsupported add-ons are not active and are not displayed in the menu.
Note: The issue is still reproducible when updating from GV 76 to the latest GV 76 build. @csadilek Is this expected? Thanks!

**Comment by csadilek** [comment]
> Note: The issue is still reproducible when updating from GV 76 to the latest GV 76 build. @csadilek Is this expected? Thanks!

Thank you for verifying! We talked about this offline. This is as expected, as between steps 3. and 4. using the unfixed GV 76, the `embedderDisabled` state is lost, so upgrading to the latest GV 76 (with the fix) won't help at this point. This is not an issue though as it will be fixed for upgrades going forward.

**Comment by ebalazs-sv** [comment]
Since this is verified as fixed in the previous comment, I will move this to Done. Thanks!
