### ISSUE TITLE
Implement a BrowserMenuText item

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#6259]
In Fenix, we would like to be able to display a Text label in the BrowserMenu. As seen in the screenshot below ("Gmail", "mail.google.com/mail"):

<img width="211" alt="Screen Shot 2020-03-13 at 12 23 14 PM" src="https://user-images.githubusercontent.com/1190888/76641558-2873db00-6528-11ea-8a33-f37f8facae44.png">

The proposal is to introduce a new item in BrowserMenu called "BrowserMenuText", which will provide the ability to display a header and an optional sub header in a BrowserMenu item.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5234)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793144

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
