### ISSUE TITLE
Create new concept component for menu

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6261]
We have several use cases where our current `browser-menu` component isn't compatible with our architecture:
 - We want to add menus to other APIs.
 - Multiple menu implementations that inherit from each other but do not use a common API.

We should introduce a new component `concept-menu` that moves the `browser-menu` APIs to it's own place.

**Comment by jonalmeida** [comment]
Needed for #2103.

**Comment by jonalmeida** [comment]
I'm taking this off current work since it's not in my critical path for landing #6375 any more.

**Comment by NotWoods** [comment]
`browser-menu2` is meant to solve the issues you listed in the OP, was it insufficient here? I'm happy to help work on a concept component if needed but the menu2 items are already all plain data classes.

**Comment by jonalmeida** [comment]
> `browser-menu2` is meant to solve the issues you listed in the OP, was it insufficient here? I'm happy to help work on a concept component if needed but the menu2 items are already all plain data classes.

Breaking the dependency of `browser-menu2` needed for `browser-menu` is where creating `concept-menu` would come in handy. Moving those data classes, APIs, etc.

For #2103, it would be better to not depend on our specific implementation of `browser-menu`/`browser-menu2` but on the concept so that consumers can replace those implementations with easy.

> In the PR you mentioned the pattern that web extensions use, but that was added just as a quickfix until menu2 lands. I'd be happy to tweak the component if its not solving these use cases.

I'd be happy to put off this PR if it means landing a better fix for the menu problems.

**Comment by jonalmeida** [comment]
Closing this as completed since it landed.
