### ISSUE TITLE
some GIF pictures aren't played in reference browser but it's okay in firefox focus

### ISSUE THREAD

**Issue by tmdwns7809** [mozilla-mobile/android-components#6265]
for example if i open this site in reference browser

https://gall.dcinside.com/mgallery/board/view/?id=tottenham&no=1000038&s_type=search_subject&s_keyword=gif&page=1

there is nothing but the dark picture until i long press the dark picture,
and if i long press the dark picture it gets played finally.

on the other hand if i open the page in firefox focus, it gets played right after loading finished.

I found out one more difference between those.

if i open this site

https://www.fmkorea.com/best/2825029618

 in reference browser, the media contents won't get played until i press the play button.
on the other hand in firefox focus, the contents played right after loading finish

I tried to change some settings but i couldn't find how to fix this

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5244)

**Comment by csadilek** [comment]
> there is nothing but the dark picture until i long press the dark picture,
and if i long press the dark picture it gets played finally.

This seems to work now. Please file a ticket [here](https://github.com/mozilla-mobile/reference-browser) if still a problem.
