### ISSUE TITLE
ANR: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{615109 u0 org.mozilla.fennec_aurora/mozilla.components.lib.crash.handler.CrashHandlerService}

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6272]
Google Play has been warning us about a peak in ANRs. Looking at the list this is by far the one with the most reports:

> Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{615109 u0 org.mozilla.fennec_aurora/mozilla.components.lib.crash.handler.CrashHandlerService}

**Comment by pocmo** [comment]
@rocketsroger This may be caused by our refactoring in #6058? It was very low volume and then started peaking at March 13th, but then again the patch landed end of February already. 🤔 Did we (or Fenix!) change the version of androidx that supplies `JobIntentService`? Or did GeckoView change the way it invokes the service?

**Comment by pocmo** [comment]
![Screenshot_2020-03-16 ANRs crashes - Firefox Nightly for Developers - Google Play Console](https://user-images.githubusercontent.com/89638/76762842-59efdf00-6792-11ea-98d6-95995571ec34.png)

**Comment by pocmo** [comment]
The annoying thing here is that this could also be caused by something else blocking the UI thread, causing this to time out? 🤔

**Comment by snorp** [comment]
GeckoView has always started the crash service with `startForegroundService()`, so no changes there.

**Comment by rocketsroger** [comment]
Confirmed its my change that caused this.  Long running work can only be used inside `onHandleWork` not in `onStartCommand`.

**Comment by rocketsroger** [comment]
Reverted the change that caused this issue https://github.com/mozilla-mobile/android-components/pull/6282.  Closing as fixed.
