### ISSUE TITLE
Publishing local tooling-glean-gradle doesn't use component versioning

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6288]
The `tooling-glean-gradle` plugin version that is published locally by using [the recommended guide](https://mozac.org/contributing/testing-components-inside-app) doesn't use the versioning as expected.

There are two issues here:
 1. The version from `componentVersion` in the `.buildconfig.yml` is not used.
 2. Setting flag `snapshot` in `gradle.properties` doesn't use the `-SNAPSHOT` prepended to the version number as the [other components](https://github.com/mozilla-mobile/android-components/blob/master/publish.gradle#L36) do.

Looking into my `~/.m2/repository/android-components/tooling-glean-gradle/maven-metadata-local.xml` the version number is set as `unspecified`:

```xml
<metadata>
  <groupId>android-components</groupId>
  <artifactId>tooling-glean-gradle</artifactId>
  <versioning>
    <latest>unspecified</latest>
    <release>unspecified</release>
    <versions>
      <version>unspecified</version>
    </versions>
    <lastUpdated>20200317032711</lastUpdated>
  </versioning>
</metadata>
```

When I try to build Fenix with a local a-c, I see this:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all artifacts for configuration ':app:classpath'.
   > Could not find org.mozilla.components:tooling-glean-gradle:0.0.0-SNAPSHOT.
     Searched in the following locations:
       - https://snapshots.maven.mozilla.org/maven2/org/mozilla/components/tooling-glean-gradle/0.0.0-SNAPSHOT/maven-metadata.xml
       - https://snapshots.maven.mozilla.org/maven2/org/mozilla/components/tooling-glean-gradle/0.0.0-SNAPSHOT/tooling-glean-gradle-0.0.0-SNAPSHOT.pom
       - https://snapshots.maven.mozilla.org/maven2/org/mozilla/components/tooling-glean-gradle/0.0.0-SNAPSHOT/tooling-glean-gradle-0.0.0-SNAPSHOT.jar
       - https://maven.mozilla.org/maven2/org/mozilla/components/tooling-glean-gradle/0.0.0-SNAPSHOT/maven-metadata.xml
       - https://maven.mozilla.org/maven2/org/mozilla/components/tooling-glean-gradle/0.0.0-SNAPSHOT/tooling-glean-gradle-0.0.0-SNAPSHOT.pom
       - https://maven.mozilla.org/maven2/org/mozilla/components/tooling-glean-gradle/0.0.0-SNAPSHOT/tooling-glean-gradle-0.0.0-SNAPSHOT.jar
       - https://plugins.gradle.org/m2/org/mozilla/components/tooling-glean-gradle/0.0.0-SNAPSHOT/maven-metadata.xml
       - https://plugins.gradle.org/m2/org/mozilla/components/tooling-glean-gradle/0.0.0-SNAPSHOT/tooling-glean-gradle-0.0.0-SNAPSHOT.pom
     Required by:
         project 🍎 
```

That said, it seems like the right place the plugin should be pulled from is: `~/.m2/repository/org/mozilla/components/tooling-glean-gradle/0.0.0-SNAPSHOT/maven-metadata-local.xml`

**Comment by jonalmeida** [comment]
Not sure if this releng work or something @mdboom / @travis79 would be familiar with.

**Comment by jonalmeida** [comment]
Doing an internet search around (which is what I should have started with!), shows that we need to edit out `settings.gradle` to also include `mavenLocal` there for plugins to be resolved:

```groovy
pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
}

```

**Comment by mdboom** [comment]
Is it not publishing *also* under the correct version?  That's what I see on my machine.  We never did figure out how to not get it to publish the `unspecified` version as well, but we just filter that out when we deploy.

In any event, your suggested change makes sense in order to make locally deployed plugins work.

**Comment by pocmo** [comment]
I have been publishing and consuming locally (in Fenix) without issues? 🤔

**Comment by pocmo** [comment]
> I have been publishing and consuming locally (in Fenix) without issues? 🤔

Except that I had to add `mavenLocal()` to Fenix `buildscript { repositories { .. } }` too in order to resolve the plugin.

**Comment by mdboom** [comment]
Ah -- would there be any harm to adding `mavenLocal()` in Fenix as a matter of course... or is that something to document for people building against a local android-components (I ask out of ignorance).

**Comment by jonalmeida** [comment]
> > I have been publishing and consuming locally (in Fenix) without issues? 🤔
> 
> Except that I had to add `mavenLocal()` to Fenix `buildscript { repositories { .. } }` too in order to resolve the plugin.

Ah, I guess we need to add `mavenLocal()` to both places now. I'll update the docs after testing this.



> Ah -- would there be any harm to adding `mavenLocal()` in Fenix as a matter of course... or is that something to document for people building against a local android-components (I ask out of ignorance).

This could lead to confusion if a local cache of a-c is pulled in when the user isn't expecting it to be. It's probably better to document it instead or use the `autoPublish` helper tool.
