### ISSUE TITLE
Relax StringFormatCount lint rule if possible

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6294]
See https://github.com/mozilla-mobile/android-components/pull/6197 for details.

`StringFormatCount` has been causing issues since in some translations it is totally fine to omit a placeholder at times. I think we have been seeing issues for some permutations of that (e.g. argument in translation but not in source string).. let's verify and if possible relax that rule to be less strict.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5278)

**Comment by csadilek** [comment]
It doesn't look like we can relax this. We could remove, but it seems valuable in many cases, and we haven't seen failures in a long time. I will close and we can reconsider if we see it again.
