### ISSUE TITLE
Browser sample: Smoketest-loadWebsiteTest: memory leaks were detected failure

### ISSUE THREAD

**Issue by isabelrios** [mozilla-mobile/android-components#6297]
Emulator: Pixel 2, API 28. 
Device: Pixel 3, API 29

Run [loadWebsiteTest](https://github.com/mozilla-mobile/android-components/blob/master/samples/browser/src/androidTest/java/org/mozilla/samples/browser/SmokeTests.kt#L53) 

The test fails with error: 
```
Test failed because memory leaks were detected, see leak traces below.
######################################
In org.mozilla.samples.browser.test:null:0.
* org.mozilla.samples.browser.BrowserActivity has leaked:
* SessionAccessibility$NativeProvider.!(this$0)!

```
See full logs here: 
[loadWebSiteTest.docx](https://github.com/mozilla-mobile/android-components/files/4345082/loadWebSiteTest.docx)

It works on emulators: Pixel and Pixel 3, API28, and on Firebase on Pixel API25 and Pixel API28

On firebase it fails for: Nexus 6, API Level 21, with a different error though. See [logs](https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.9f526cd30412cc12/matrices/7800073812871741146/executions/bs.8acb730110295a0d)

Please let me know if there is something else that you may need to help with this issue. 
Thanks!

**Comment by pocmo** [comment]
```
In org.mozilla.samples.browser.test:null:0.
* org.mozilla.samples.browser.BrowserActivity has leaked:
* SessionAccessibility$NativeProvider.!(this$0)!
* ↳ SessionAccessibility.!(mSession)!
* ↳ GeckoSession.!(mSelectionActionDelegate)!
* ↳ GeckoSession$9.!(mDelegate)! (anonymous subclass of org.mozilla.geckoview.GeckoSessionHandler)
* ↳ GeckoSelectionActionDelegate.!(mActivity)!
* ↳ BrowserActivity
```

Looks like this could be a problem with `SelectionActionDelegate`.

**Comment by pocmo** [comment]
I see us set a `GeckoSelectionActionDelegate` in `GeckoEngineView`, but we never clear it. I thought that may cause the leak - but even if I remove that code I still get that leak reported by leak canary. Maybe this is one layer lower in GeckoView? Continuing to investigate...

**Comment by pocmo** [comment]
Running bisect I end up in e372ef1822b9c5def7b1622c2366b7df2f1c59bd again. So it seems like our own delegate implementation is causing this.
