### ISSUE TITLE
Make propagation of menu items highlight optional

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#6308]
This is related to [a Fenix issue](https://github.com/mozilla-mobile/fenix/issues/9109), where one of the menu items has a highlight, but the three-dot menu shouldn't take it into account when displaying its own highlight.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5292)

**Comment by csadilek** [comment]
Landed in https://github.com/mozilla-mobile/android-components/pull/6309.
