### ISSUE TITLE
Fenix will crash if a page is opened in custom tab and in the browser

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla-mobile/android-components#6328]
### Preconditions
Have Fennec installed.
### Steps to reproduce
1. Add a few page shortcuts using Fennec;
2. Replace Fennec with Fenix;
3. Tap on the any of the homescreen shortcuts added in step 1;
4. The homescreen shortcut is opened in a custom tab;
5. Open Fenix;
6. Tap on the new tab has just opened in Fenix.

### Expected behavior
The website is displayed.
### Actual behavior
Fenix crashes when a page is opened in custom tab and in the browser.
### Notes
Homescreen page shortcuts should open directly in Fenix and not in custom tabs, issue [6327](https://github.com/mozilla-mobile/android-components/issues/6327)has been submited regarding this and may be related.

### Device information
- Android device: Huawei MediaPad M3 Lite 10 (Android 7.0)
- Fenix version: Beta migration 2 build 03/19
![crash](https://user-images.githubusercontent.com/50983519/77168918-52497680-6ac1-11ea-8804-006dfba12cff.gif)
[logcat.txt](https://github.com/mozilla-mobile/android-components/files/4359840/logcat.txt)

**Comment by ebalazs-sv** [comment]
This is still reproducible on Beta Migration build 4, 3/24, with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
This is reproducible on 
- Beta migration build 75.0.0-beta.4 with OnePlus 6T (Android 9), Huawei MediaPad M3 Lite (Android 7.0);
- Release migration build 4.0.0-beta.2 GV 76 4/8 with Motorola G6 (Android 8), Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta migration build 75.0.0-beta.5, 4/14, with Huawei P9 Lite (Android 7).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Release Migration (Build #2015737139) 4/28 with Pixel 2 (Android 9).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration Build 76.0.0-beta.1, from 5/1, with Nexus 5 (Android 6.0.1).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration Build 76.0.0-beta2, from 5/14 with Motorola Moto G6 (Android 8).

**Comment by Mugurell** [comment]
With the patch from https://github.com/mozilla-mobile/fenix/issues/10844 now being merged this situation (shortcut being opened in both the app and a custom tab) should not be possible anymore and as such this crash should not occur anymore.
Please verify.

**Comment by ebalazs-sv** [comment]
Verified as fixed on the latest Nightly Migration Build 2015742513 GV 78, from 5/26, with Nexus 5 (Android 6.0.1), Motorola Moto G6 (Android 8), Pixel 2 (Android 9).
The migrated homescreen page shortcuts are opened in Fenix when tapped and they do no crash.
I will move this to Done. Thanks!

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration build 5.1.0-beta.2 with Motorola Moto G6 (Android 8).

**Comment by ebalazs-sv** [comment]
Verified as fixed on Beta Migration Build 5.1.0-beta.3 with Motorola Moto G6 (Android 8), Google Pixel 3XL (Android 9), Huawei MediaPad M3 lite (Android 7).
The homescreen shortcuts are opened in Fenix in a new tab and they do not crash the app.
