### ISSUE TITLE
Dev tools extension to observe internal state of components

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6341]
Some what related to #455.

**Problem**
There's a lot of state in our components. We are unifying on using `browser-state` which operates on a large, redux-style, state tree. Understanding how this tree looks like and how it changes it key in debugging issues. The debugger sometimes is helpful here, but we are never interested in observing all state changes - and it only works for debug builds.

**Idea**
We already support connecting to remote devices via `about:debugging` on a desktop computer. And (at least on desktop) there is a webextension API that allows us to extend the functionality of dev tools. Would it be possible to use dev tools from a desktop computer to inspect the state of `browser-state`? If this is a feasible approach then we could step by step add more helpful tools using that bridge.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5312)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794660

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
