### ISSUE TITLE
Use license rule from Detekt instead of custom one

### ISSUE THREAD

**Issue by dector** [mozilla-mobile/android-components#6351]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5322)

**Comment by dector** [comment]
@pocmo Should we remove/deprecate whole `tooling-detekt` package?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795140

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
