### ISSUE TITLE
Follow URL Rendering recommendations

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6357]
Consider this a meta bug from which more issues can sprout.

There is now a specification that recommends how URLs are rendered in the location bar.

https://url.spec.whatwg.org/#url-rendering

Following the recommendations in this specification will probably prevent common url spoofing attempts and gives us more parity with other (mobile) browsers.

Since visual tests are tough, we should also turn this into a QA (testrail) test plan to confirm that we do the right thing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5333)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793201

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
