### ISSUE TITLE
Move ThrowProperty delegate to support-test

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6369]
This is a handy helper when you need to create a stub implementation of an API.

It might be handy to move this to the `support-test` component` with some docs.

https://github.com/mozilla-mobile/android-components/blob/d4d1449f15c64d51469a7a517de9ea912561f32e/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt#L90-L96

**Comment by waahm7** [comment]
@jonalmeida I would love to do this. Can you please assign this to me?

**Comment by levimatheri** [comment]
@jonalmeida I have a pending PR on this already

**Comment by jonalmeida** [comment]
I saw! Left a review comment. 🙂
