### ISSUE TITLE
Evaluate Gradle Enterprise

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#638]
Gradle Enterprise looks interesting:
https://gradle.com/#play-video

It seems to provide a build cache that can be accessed by developers and CI systems and with that speeds up builds. It also offers a lot of analytics that help improving the build system in general.

Teng-Pao introduced me to someone working for Gradle Inc. and I'm interested in evaluating how this could help us and whether this would work in a public open-source setting.

Demo: https://go.gradle.com/watch-demo-gradle-enterprise

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5350)

**Comment by pocmo** [comment]
The results of my tests were very mixed.

I ran a gradle cache node on a machine in my local network (WiFi). This and my limited internet connection (~80 Mbit/s down / ~28 Mbit/s up) have skewed the results on taskcluster.

### Taskcluster

On Taskcluster builds with an empty cache where a bit slower (because they needed to upload things to the cache). For single components that was almost not noticeable (< 1 min). However the sample browser uploaded the largest chunk to the cache and the whole build took about 40 minutes (currently ~25 minutes without that).

A full build of everything created about 1265 entries in the cache with a total size of 421.92 MB.

A full build with a warm cache on taskcluster was noticeable slower (~4-5 mins for a component; a lot for the sample browser). That was pretty disappointing and very likely caused by my slow upstream.

## Local network

Since I couldn't do much with that setup I went on to test locally: I ran the cache node on a separate machine but accessed it through the local network (WiFi; ~450Mbps).

A local build with no caching at all on my machine took **6m, 22s**.

A local build with remote cache enabled on my machine took **7m, 22s**. This is still **slower** than building with no cache at all. That was rather surprising. It looked like the build was busy extracting artifacts from the remote cache.

A local build with remote cache enabled and a local (warm) cache (-> No downloading) took **4m, 43s**. That's now significantly faster than without cache.

## Conclusion

For automation the hope was to trade build speed (slow) against download speed (fast). However in my tests this didn't seem to have a positive impact. Downloading artifacts slowed down the builds.

For local development (with an additional local cache) there's a significant improvement. This improvement comes when not having to re-download artifacts and after they are in the local cache already. A local cache is something that we may be able to use without the remote part (#1290).

It would be interesting to look at those numbers with parallel builds enabled again (#1293). Locally I saw build times go down from **3m, 1s** (no cache, parallel) to only **2m, 51s** (warm local cache, parallel). Unfortunately I do not have the numbers for an empty cache. Downloading and extracting artifacts from the remote cache may speed up the whole build and maybe this will give us the required improvements.

**Comment by grigoryk** [comment]
Wouldn't we mostly have a warm cache in automation though, if we play our cards right? (our own worker-type, etc).

**Comment by pocmo** [comment]
> Wouldn't we mostly have a warm cache in automation though, if we play our cards right? (our own worker-type, etc).

If we place the build cache into a worker cache: Yes! Back when I read that only one worker can use a cache at the same time I assumed that the (single) cache would be the bottle neck. However it seems like there will just be multiple caches and with that one per worker shouldn't be a problem.
