### ISSUE TITLE
Fix on-device tests in feature-tab-collections

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6380]
I noticed that some of the on-device tests in `feature-tab-collections` are failing. Since we are not running those tests in automation yet, we may just have missed those failures. Let's fix them!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5352)

**Comment by pocmo** [comment]
Once they are fixed let's also add tests for the `SessionManager.restore()` extension methods.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795373

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
