### ISSUE TITLE
Error page for malicious website warning does not properly substitute website hostname

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6384]
> See https://bugzilla.mozilla.org/show_bug.cgi?id=1624329

Reported for an Italian locale, but probably safe to assume it doesn't work in general then?

![Screenshot_20200324-193439](https://user-images.githubusercontent.com/28052/77466936-6f43b980-6de1-11ea-8386-73be58dad5de.jpg)

**Comment by mcarare** [comment]
@jonalmeida AFAIK Fenix uses a different method from `ErrorPages`, that is `createUrlEncodedErrorPage`. I think this Fenix issue can be fixed in AC.
Original Fenix reported issue:  https://github.com/mozilla-mobile/fenix/issues/9158.

**Comment by jonalmeida** [comment]
> @jonalmeida AFAIK Fenix uses a different method from `ErrorPages`, that is `createUrlEncodedErrorPage`. I think this Fenix issue can be fixed in AC.
> Original Fenix reported issue: [mozilla-mobile/fenix#9158](https://github.com/mozilla-mobile/fenix/issues/9158).

Yes, you're right! Thank you for catching that. 

I'll transfer the issue back and file an issue to avoid the divergence. Maybe R-B should use the new API instead to avoid confusion.
