### ISSUE TITLE
Add delete functionality to Recent Share apps Feature

### ISSUE THREAD

**Issue by DrCesar** [mozilla-mobile/android-components#6388]
Add Delete functionality for recent apps. Mostly that someone in fenix can delete the recently used apps from the list.

mozilla-mobile/fenix#8759

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5360)

**Comment by cadeyrn** [comment]
@jonalmeida I see there was some work on the AC side. Do you know the current state / what is needed on the Fenix side to finish this feature?

It was asked in the Firefox support today how to remove an app from the recently shared items. The question was about Fennec and as far as I know it's not possible in Fennec. But it would be great if I could say that it will be possible in Fenix. 😊

**Comment by jonalmeida** [comment]
Hey @cadeyrn , it looks like the solution in the Fenix feature request was to correct the scrolling of the recent apps and limit the total number you can have.

You can find that here: https://github.com/mozilla-mobile/fenix/issues/8759

That said, Fennec does have a version of a recent share menu. Maybe they were referring to that? Although I don't think we support removing items there either.

![Screenshot_20200602-110159](https://user-images.githubusercontent.com/1370580/83536068-c4c2d380-a4c0-11ea-9d94-48e316bf15e1.png)

**Comment by cadeyrn** [comment]
> Maybe they were referring to that? Although I don't think we support removing items there either.

Yes, this is what the user in the support was referring to and it's not possible to remove recently shared items in Fennec. But I hoped it will be possible in the new implementation in Fenix. Even if mozilla-mobile/fenix#8759 will solve the original issue by allowing to scroll the recent apps it would still be useful to be able to remove items from the list. And since a AC API landed for that I hoped it will be used in Fenix to offer this feature. :)

**Comment by jonalmeida** [comment]
> Maybe I should open a new issue in the Fenix issues tracker. :)

Yes, please! This bug/solution was filed before we wanted to address that feature request. It's always best to separate the problem from the solution. :)

Thank you!

**Comment by cadeyrn** [comment]
@jonalmeida Thanks. I filed https://github.com/mozilla-mobile/fenix/issues/11566.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794882

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
