### ISSUE TITLE
Use createUrlEncodedErrorPage for Sample Browser

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6389]
..and R-B too.

This is what Fenix uses and can help us do better comparison testing if we're using the same APIs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5362)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795369

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
