### ISSUE TITLE
Fennec migration: Remove the "preview" from the What's New article

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#6400]
@vesta0 I filed this issue based on your requirement from the Slack migration channel.

## Preconditions:
Have Fennec installed.
## Steps to reproduce
1. Replace Fennec with Fenix;
2. Launch Fenix and go to the 3 dots menu;
3. Tap the "What's New" option;
4. Observe the "preview" word from the article;
### Expected behavior
The "preview" word from "What's New" article must be deleted, since Firefox Beta is not called "preview" in the app.
### Actual behavior
The "preview" word is displayed in the "What's New" article, although Firefox Beta is not called "preview" in the app.

### Notes
"Preview" word is also present in the "What's new in Firefox Beta" from About Firefox Beta page. 
[Screenshot](https://drive.google.com/open?id=1dbRJQ2w-SaQkXeie5-Lpv1z29THOSspU)
### Device information

* Android device: all
* Fenix version: Beta migration 75.0.0-beta.2 build, 03/25 and all the previous migration builds.

**Comment by ebalazs-sv** [comment]
This is also reproducible on Beta Migration build 75.0.0-beta.4 with Pixel 2 (Android 9).

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration Build 76.0.0-beta2, from 5/14 with Motorola Moto G6 (Android 8).

**Comment by st3fan** [comment]
@jonichan is this something you can pick up? I think this may just be a rewording of the article so that it applies to all migration builds. We can also link to different articles from different builds of course.

**Comment by jonichan** [comment]
We've removed the word "Preview" referred to it as the updated Firefox. I've also updated the linked articles to just Firefox. I think that should be okay but if we see people getting confused it might make more sense to link to different articles from different builds. I'll keep an eye on it.

**Comment by ebalazs-sv** [comment]
I had tested this issue on the Beta Migration build 5.1.0-beta.3 with Motorola Moto G6 (Android 8) and the "Preview" word is removed from the What's New article.

There are still links that when opened, they refer to Firefox Preview. For example: "Enhance Tracking Protection", "knowledge base", "Set Firefox Preview as your default browser", "Update Firefox Preview to the latest version" links.

@st3fan Do we need to change the links from the What's New article as well, so they don't have the "Preview" word in them?

**Comment by jonichan** [comment]
I've changed the article titles so they wouldn't have Preview but I left the linked article bodies the same since there's still an app called Firefox Preview in the store.

**Comment by vesta0** [comment]
Thank you @jonichan :) We can remove "Preview" from everywhere by July 7.

**Comment by st3fan** [comment]
@jonichan @vesta0 can we close this ticket?

**Comment by st3fan** [comment]
The support article does not mention Preview anymore so I will close this bug.
