### ISSUE TITLE
[Bug] Dark Reader “Help” (Read the manual) does not redirect to manual page

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/android-components#6419]
**Steps to reproduce:**
1. Install Dark Reader
2. Open any page
2. Tap on the three-dot menu
3. Scroll to the top of the menu list and select Dark Reader
4. Notice that an options page will open
5. Tap on the “Settings” button at the bottom of the page
6. Tap on the “Help” button (Read the manual)
7. Observe that the user is not redirected to the manual page but to the page from Step 2

**Expected behavior:**
The “Help” button should open the add-on’s manual page.

**Actual behavior:**
Tapping the “Help” button will direct the user to the page from which the add-on dashboard has been accessed instead of the manual page.

**Device information:**
- Android device: Samsung Galaxy S7 Edge (Android 8.0.0), Samsung Galaxy A5 (2016) (Android 7.0)
- Fenix version: 3/26 Nightly build

**Note:**
Does not reproduce on Fennec 68.6.0

![Help - wrong redirect](https://user-images.githubusercontent.com/50236075/77754306-bf19bf00-7033-11ea-9224-a666fd60153c.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5392)

**Comment by csadilek** [comment]
This the same as https://github.com/mozilla-mobile/android-components/issues/6422

GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1626356

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796320

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
