### ISSUE TITLE
[Bug] Dark Reader “Donate” does not redirect to donation page

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/android-components#6422]
**Steps to reproduce:**
*A.*
1. Install Dark Reader
2. Open any page
2. Tap on the three-dot menu
3. Scroll to the top of the menu list and select Dark Reader
4. Notice that an options page will open
5. Tap on the “Donate” button at the bottom of the page
6. Observe that the user is not redirected to the donation page but to the page from Step 2

*B.*
1. Install Dark Reader
2. Open any page
2. Tap on the three-dot menu
3. Scroll to the top of the menu list and select Dark Reader
4. Notice that an options page will open
5. Tap on the “Settings” button at the bottom of the page
6. Tap on the “Donate” button
7. Observe that the user is not redirected to the donation page but to the page from Step 2

**Expected behavior:**
The “Donation” button should direct the user to the add-on’s donation page.

**Actual behavior:**
Tapping the “Donate” button will direct the user to the page from which the add-on dashboard has been accessed instead of the donation page.

**Device information:**
- Android device: Samsung Galaxy S7 Edge (Android 8.0.0), Samsung Galaxy A5 (2016) (Android 7.0)
- Fenix version: 3/26 Nightly build

**Note:**
Does not reproduce on Fennec 68.6.0

![Donate - wrong redirect](https://user-images.githubusercontent.com/50236075/77756254-7fed6d00-7037-11ea-8480-21aa80164597.gif)

**Comment by agi90** [comment]
This looks like some sort of timing issue with the `NavigationDelegate`: https://bugzilla.mozilla.org/show_bug.cgi?id=1626356

**Comment by csadilek** [comment]
This was fixed in dark reader: https://github.com/darkreader/darkreader/issues/2464

Will roll out with next update, but I don't think we need to track this here, as it was a fix in the add-on itself.
