### ISSUE TITLE
[Bug] Add-on settings opened in a new tab everytime

### ISSUE THREAD

**Issue by DanielOrban** [mozilla-mobile/android-components#6424]
### Prerequisites
- Privacy Badger is installed and enabled in Fenix
## Steps to reproduce
1. Open Fenix.
2. Navigate to "Settings-> Add-ons-> Privacy Badger".
3. Tap the "Settings" button.
4. Repeat the steps above and notice the open tabs.
### Expected behavior
The page is redirected to the "Privacy Badger Options" tab.
### Actual behavior
Another identical page is opened in a new tab.
### Device information
- Android device:
-Samsung Galaxy A5(2016) (Android 7.0)
-Samsung Galaxy S7 Edge (Android 8.0.0)
- Fenix version:
- 3/26 Nightly build (#20861010)

![The Privacy Badger Option settings is opened in a new tab eveytime](https://user-images.githubusercontent.com/43445968/77760977-ee362d80-703f-11ea-8c2a-7f22360b60c7.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5398)

**Comment by csadilek** [comment]
This is the case for all add-on options/settings pages, so updating the title, and it's currently as designed. We could consider implementing this using https://github.com/mozilla-mobile/android-components/issues/6399 once that lands.

**Comment by opusforlife2** [comment]
#6399 is fixed now. Is this still the plan?
> We could consider implementing this using #6399 once that lands.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796319

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
