### ISSUE TITLE
Add container icon in the browser toolbar

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#6429]

**Comment by jonalmeida** [comment]
I realize now that this is probably something you can do as part of a feature integration with the toolbar. Adding a 'page action' icon for the container type.

See this nice ascii art of where page actions ago: https://searchfox.org/mozilla-mobile/source/android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt#34-37

**Comment by gabrielluong** [comment]
I actually did this similar to the Indicators (Tracking Protection, Site Security), but could revisit this again as we define this feature more and move this into being a Page Action icon. 

<img width="441" alt="Screen Shot 2020-03-26 at 12 17 49 PM" src="https://user-images.githubusercontent.com/1190888/77805099-8855a000-7057-11ea-84f5-882cf58a1d95.png">

**Comment by liuche** [comment]
@vesta0 and @gabrielluong will talk about this priority in this sprint - is this a specific design decision?

**Comment by vesta0** [comment]
@liuche no we haven't had any design/UX work done on this yet.

**Comment by gabrielluong** [comment]
We can reuse the icons and colors from the desktop implementation for the time being and provide a way for the applications to customize this. https://hg.mozilla.org/mozreview/gecko/rev/e3d9c852a8410beb6c606e4fc2febab6a76590dc#l1.25
