### ISSUE TITLE
Engine/Session: Fullscreen mode

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#643]
There are a lot of things needed for fullscreen mode. For this issue I propose to only focus on the `browser-session` and `browser-engine` components and ignore the actual UI pieces. We will need the `browser-session` implementation for Focus parity (#200). We should do the `browser-engine` work too to come up with the right state representation in `browser-session`.

The APIs of GeckoView and WebView are fundamentally different which will make this more difficult to implement:
* WebView will return a `View` object that needs to be added to the view root and that replaces/overlays the app UI. In addition to that it returns a Callback object that the app needs to use if it wants to leave full screen mode.
https://developer.android.com/reference/android/webkit/WebChromeClient.html#onShowCustomView(android.view.View,%20android.webkit.WebChromeClient.CustomViewCallback)
* GeckoView will switch itself into fullscreen mode and the app just needs to hide all other UI. Fullscreen mode can be left by calling a method. No callback is needed.

I think we should hide this callback nonsense and everything related inside the `engine-*` component. And just provide a method on the EngineSession to exit full screen mode. Internally the component can do that with the callback or on whatever it needs.

We should add some flag to `browser-session` for the full screen mode. We do not do that in Focus - but it will be needed to correctly restore the full screen state.

**Comment by jonalmeida** [comment]
^ Pushing the wrong commit to the wrong branch. 🤦‍♂️
