### ISSUE TITLE
Expose OAuthAccount.getPairingAuthorityURL

### ISSUE THREAD

**Issue by eoger** [mozilla-mobile/android-components#6435]
`getPairingAuthorityURL` is available from the `OAuthAccount`, but the consuming app has no way to get the account when they are not authenticated (`authenticatedAccount` will return `null`). We should expose `getPairingAuthorityURL` in the manager maybe? cc @grigoryk

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5409)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794211

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
