### ISSUE TITLE
[Bug] Search by Image "Options" button should re-direct to Settings.

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6444]
## Prerequisites
Have Search by Image installed.

## Steps to reproduce
1. Navigate to any web page
2. Tap the ⋮ Main menu button and open Search by Image
3. In the upper right side tap the ⋮ button
4. Tap "Options"

### Expected behavior
Tapping the "Options" button should re-direct the user to Search by Image settings.

### Actual behavior
Nothing happens

### Device information
* Android device: Google Pixel 3a (Android 10)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
► Video Fenix
![20200330-112628](https://user-images.githubusercontent.com/51314259/77892268-047bfd80-727b-11ea-82dc-cb887d43dc4f.gif)

► Video Fennec
![20200330-112704](https://user-images.githubusercontent.com/51314259/77892422-44db7b80-727b-11ea-89a9-58f6dd12959c.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5421)

**Comment by csadilek** [comment]
This will need a fix in GV: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1619766
```
BrowserApp.selectOrAddTab is not a function ext-android.js:61
    openOptionsPage chrome://geckoview/content/ext-android.js:61
    openOptionsPage chrome://extensions/content/parent/ext-runtime.js:154
    openOptionsPage self-hosted:873
    result resource://gre/modules/ExtensionParent.jsm:960
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:592
    result resource://gre/modules/ExtensionParent.jsm:960
    callAndLog resource://gre/modules/ExtensionParent.jsm:922
    recvAPICall resource://gre/modules/ExtensionParent.jsm:959
    InterpretGeneratorResume self-hosted:1156
    AsyncFunctionNext self-hosted:695
```

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796324

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
