### ISSUE TITLE
[Bug] Search by Image cut off Search engine list

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6446]
## Prerequisites
Have Search by Image installed.
From the Add-on's settings enable all Search engine options.

## Steps to reproduce
1. Navigate to any web page
2. Tap the ⋮ Main menu button and open Search by Image
3. Swipe to the bottom of the featured Search engines

### Expected behavior
The search engines should be displayed on the entire screen.

### Actual behavior
The list seems to be cut off (bottom side)

### Device information
* Android device: Google Pixel 3a (Android 10)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
► Video Fenix
![20200330-120027](https://user-images.githubusercontent.com/51314259/77901282-03050200-7288-11ea-893e-567e0cdbf55f.gif)

► Video Fennec
![20200330-115848](https://user-images.githubusercontent.com/51314259/77900993-8b36d780-7287-11ea-87fb-19f421d503a2.gif)

**Comment by csadilek** [comment]
That's not something we can fix. This needs to be investigated / addressed in the add-on by the add-on developer specifically for Fenix. Please add to list to relay to add-on developer for improvement.
