### ISSUE TITLE
[Bug] Dynamic toolbar should be disabled while Search by Image in capture mode 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6450]
## Prerequisites
Have Search by Image installed.
Set the search mode to "Capture"

## Steps to reproduce
1.Navigate to any web page
2. From the  ⋮ Main menu open Search by Image and select a search engine
3. Make a selection
4. Move the selection

### Expected behavior
Can properly move the desired selection.
The dynamic toolbar should be disabled, no animation issues.

### Actual behavior
Animation issues.
Most likely caused by the fact that the dynamic toolbar is active.

### Device information
* Android device: Google Pixel 3a (Android 10)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
►Video Fenix
![20200330-153014](https://user-images.githubusercontent.com/51314259/77915987-0d7fc580-72a1-11ea-83e3-17de5fb3c342.gif)

►Video Fennec
![20200330-153441](https://user-images.githubusercontent.com/51314259/77917976-ebd40d80-72a3-11ea-9c7c-c490aab7f099.gif)

**Comment by agi90** [comment]
This was fixed by the recent dynamic toolbar fixes!

**Comment by csadilek** [comment]
@AndiAJ can you verify, please :).

**Comment by AndiAJ** [comment]
Hi @csadilek ,**verified as fixed** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

►Video
![20200406-133052](https://user-images.githubusercontent.com/51314259/78550376-a9af4c80-780c-11ea-8272-df748bcd8bf7.gif)
