### ISSUE TITLE
Two instances of Fenix are available in the Send to device section

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#6452]
### Preconditions:
Logged in on two devices.
## Steps to reproduce
1. Launch Fenix and open one page;
2. Tap on the three dot menu; 
3. Choose Share;
4. Observe the Fenix versions available in the "Send to device" list;
### Expected behavior
One instance of each Fenix version is available in the "Send to device" section.

### Actual behavior
Two instances of Fenix are available in the "Send to device" section.

### Notes
Only one of the two instances is usable.
This is also reproducible when sending tabs to Fennec.
### Device information

* Android device: Huawei P9 Lite (Android 7); Nexus 5 (Android 6.0.1).
* Fenix version: 
 Beta migration 75.0.0-beta.2 build, 03/25; 
Fenix Beta 4.2.0-beta.3 GV 75, 3/25; 
Fenix Nightly 200330 GV 76, 3/30.

![20200330-171530](https://user-images.githubusercontent.com/42831109/77925483-93097280-72ad-11ea-96f9-47bbb44f6d6c.gif)
[video](https://drive.google.com/file/d/1MqwflzxXcG9gBXjeYbSRea33-EjGCwE_/view)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5430)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795368

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
