### ISSUE TITLE
Failed to resolve: org.mozilla.components:tabcounter:0.19

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/android-components#646]
### Steps to reproduce

1. Add `implementation "org.mozilla.components:tabcounter:{latest-version}` to app/build.gradle
2. Sync the project and I got the error 

> Failed to resolve: org.mozilla.components:tabcounter:0.19

Is there anything else I should do to make it work? Other componets worked as expected.

**Comment by pocmo** [comment]
Oh! It seems like I forgot to whitelist this new component for sync with jcenter. I'll do that and report back once it's online.

**Comment by pocmo** [comment]
Requested sync. This usually takes < 24h until approved.

**Comment by cnevinc** [comment]
Still can't find them even though the dependency resolved completed. 
Did I miss something?
![image](https://user-images.githubusercontent.com/1287363/45027757-e20d0880-b074-11e8-9e96-aca6a37d75dc.png)

**Comment by pocmo** [comment]
Proguard is enabled for the module: `minifyEnabled true`

With that the class gets removed from the release package... :)

**Comment by pocmo** [comment]
Also noticed that the package name is wrong: `org.mozilla.components.ui.tabcounter` -> `mozilla.components.ui.tabcounter`. I'll update that too.
