### ISSUE TITLE
[Bug] Search by Image seems to be reloading in landscape mode

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6462]
## Prerequisites
None of the listed add-ons should be installed.

## Steps to reproduce
1. Navigate to the Add-ons manager and rotate the device to landscape view
2. Swipe down reaching the end of the list
3. Check the Search by Image icon
4. Swipe up
5. Swipe down again
6. Check the Search by Image icon

### Expected behavior
The icons for each Add-on should be loaded once opening the Add-ons manager. 

### Actual behavior
At Step 3 & Step 6 the Search by image icon is re-loaded.
Each time you swipe down the Search by image icon seems to be reloading (based on the animation)

### Device information
* Android device: Huawei Mate 20 Lite (Android 9)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
►Video
![20200331-092739](https://user-images.githubusercontent.com/51314259/78018863-51cd9d00-7357-11ea-829a-441d546f4ea3.gif)

**Comment by csadilek** [comment]
This has the same cause as https://github.com/mozilla-mobile/android-components/issues/6481#issuecomment-607297946.
