### ISSUE TITLE
[Bug] Can't export (download) user data in Privacy Badger

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6463]
## Prerequisites
Privacy Badger should be installed.

## Steps to reproduce
1. Open Privacy Badger's settings
2.  Tap on the Manage Data tab
3.  From the "Export user data" section tap the "Download" button

### Expected behavior
The user should be able to export the desired user data (downlaod a .json file)

### Actual behavior
The user is redirected to a "Cannot complete Request page"

### Device information
* Android device: Huawei Mate 20 Lite (Android 9)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
►Video Fenix
![20200331-094519](https://user-images.githubusercontent.com/51314259/78020451-28fad700-735a-11ea-9564-9ddedc70f3c1.gif)

►Video Fenec
![20200331-094711](https://user-images.githubusercontent.com/51314259/78019955-35cafb00-7359-11ea-96f6-88d0e7a33cf5.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5441)

**Comment by csadilek** [comment]
This is blocked on https://github.com/mozilla-mobile/android-components/issues/1159

**Comment by jonalmeida** [comment]
I verified this is a blob that we're trying to download, so it should be blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1501735.

```
blob:moz-extension://f3f76f55-82ec-436a-b746-167eddd2f33e/0da2de66-cfc1-46b9-af6b-aea50d0bb6b0
```

**Comment by Amejia481** [comment]
Related issue https://github.com/mozilla-mobile/android-components/issues/1159

**Comment by csadilek** [comment]
Looks like this works now with latest Privacy Badger as the download is now a JSON file. @AndiAJ can you verify when you get a chance, thanks! :)

**Comment by AndiAJ** [comment]
Hi @csadilek , I've just checked this matter on the latest **`Nightly 201124`** using the following devices:
• Google Pixel 3a (Android 11)
• Huawei Mate 20 Lite (Android 10)
• OnePlus A3 (Android 6.0.1)

✔️ The user data is properly exported from: Add-ons Manager → Settings → Manage Data → Export user data
❌ On the other hand, it doesn't work when trying to export them VIA the Privacy Badger dashboard.
⋮ Main menu → Add-ons → Tap on Privacy Badger → Select the upper right Gear Icon→ Manage Data → Export user data

**✅  Checked on Fennec as well, and the user can export their data from there as well.**

► Video
![20201124-095530](https://user-images.githubusercontent.com/51314259/100064609-7113c000-2e3b-11eb-8512-b01eb89c2c5f.gif)


Please review and share your thoughts. ☺️

**Comment by csadilek** [comment]
Thanks, @AndiAJ for catching this. The remaining case is a different issue. The options UI / settings page should be opened in a tab, but clicking on the gear icon opens it directly in the browser action popup where we don't have support for downloads.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796313

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
