### ISSUE TITLE
[Bug] The enable/disable globally Privacy Badger turns green 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6464]
## Steps to reproduce
1. While Privacy Badger is being verified and installed exit to the device home screen
2. Force close Fenix (swipe from the Recent apps manager)
3. Re-open Fenix 
4. Open Privacy Badger check the enable/disable button 

### Expected behavior
Properly displayed enable/disable button
![rsz_1screenshot_20200331_142456_orgmozillafenixnightly](https://user-images.githubusercontent.com/51314259/78021805-86902300-735c-11ea-9776-adb88c99d483.jpg)

### Actual behavior
The enable/disable button turn green
![rsz_screenshot_20200331_142631_orgmozillafenixnightly](https://user-images.githubusercontent.com/51314259/78021886-ac1d2c80-735c-11ea-92de-aab0a6d0052c.jpg)

### Device information
* Android device: Huawei Mate 20 Lite (Android 9)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
►Video Fenix
![20200331-132703](https://user-images.githubusercontent.com/51314259/78021952-cbb45500-735c-11ea-8e4d-7e4ae248ce30.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5442)

**Comment by mcarare** [comment]
As a note: This happens with many other switch in the app, on different Huawei devices.
