### ISSUE TITLE
[Bug] Privacy Badger tracker counter color inconsistency when opening a link in a private tab 

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6470]
## Prerequisites
Privacy Badger should be installed.

## Steps to reproduce
1. Navigate to theverge.com
2. Tap the  ⋮ Main menu button and check the tracker counter color
3. Long tap on any of the featured articles
4. Tap "Open link in private tab" and switch from the snackbar
5. Tap  ⋮ Main menu button and check the  tracker counter color

### Expected behavior
In both browsing modes the tracker counter should have an orange background.

### Actual behavior
After switching to the private tab the tracker counter is red.
Turns to orange after opening the 2nd time the ⋮ Main menu

### Device information
* Android device: Huawei Mate 20 Lite (Android 9)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
►Video Fenix
![20200331-165030](https://user-images.githubusercontent.com/51314259/78035396-b85fb480-7371-11ea-8f4c-34725447f426.gif)

**Comment by psymoon** [comment]
@AndiAJ is this still reproducible with the latest nightly? The add-ons menu have updated since and I can't seem to reproduce this.

**Comment by AndiAJ** [comment]
Hi @psymoon , **verified as fixed** on the latest **`Nightly Build 200609 from 6/9`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Video
![20200609-113939](https://user-images.githubusercontent.com/51314259/84126885-2cd86300-aa47-11ea-945f-fc5c6fcbed0d.gif)
