### ISSUE TITLE
[Bug] NoScript version number gets displayed for a couple of seconds in the ⋮ Main menu

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6478]
## Steps to reproduce
1. Install NoScript
2. Open a website
3. Open the ⋮ Main menu
4. Check the NoScript Add-on

### Expected behavior
The NoScript version number shouldn't be displayed in the ⋮ Main menu

### Actual behavior
The NoScript version number is displayed for a couple of seconds in the ⋮ Main menu 

### Device information
* Android device: OnePlus A3 (Android 6.0.1)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
►Video Fenix
![20200401-094814](https://user-images.githubusercontent.com/51314259/78108135-6feed800-73ff-11ea-85a8-f74db91a2864.gif)

**Comment by csadilek** [comment]
That's not something we can fix. This needs to be addressed in the add-on by the add-on developer specifically for Fenix. Please add to list to relay to add-on developer for improvement.

In this case it seems that the add-on is sending a browser action that includes the version string.
