### ISSUE TITLE
[Bug] Cant export NoScript data

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6479]
## Prerequisites
NoScript  should be installed.

## Steps to reproduce
1. Open NoScript's settings
2.  Tap the "Export" button

### Expected behavior
The user should be able to export the desired noscript_data (download a .txt file)

### Actual behavior
Nothing happens

### Device information
* Android device: OnePlus A3 (Android 6.0.1)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
►Video Fenix
![20200401-105435](https://user-images.githubusercontent.com/51314259/78115438-7be09700-740b-11ea-9c0b-ea3f45d7a106.gif)

►Video Fenec
![20200401-105506](https://user-images.githubusercontent.com/51314259/78115813-088b5500-740c-11ea-9b13-537c962759c3.gif)

**Comment by csadilek** [comment]
Like same as https://github.com/mozilla-mobile/fenix/issues/8155 -> https://bugzilla.mozilla.org/show_bug.cgi?id=1626349.

**Comment by csadilek** [comment]
Took a look now. The download is nor triggered properly, but this is blocked on:
https://bugzilla.mozilla.org/show_bug.cgi?id=1501735

We currently have no API to get to the bytes of a blob:// URL.

**Comment by AndiAJ** [comment]
Hi @csadilek , **verified as fixed** on the latest **`Nightly Build 200609 from 6/9`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)

► Video
![20200609-112950](https://user-images.githubusercontent.com/51314259/84125386-2517bf00-aa45-11ea-8e4a-3d0aa0eaa451.gif)


❗  Bumped into a crash while testing it on the OnePlus A3 (Android 6.0.1) I've bumped in [#11358](https://github.com/mozilla-mobile/fenix/issues/11358)
