### ISSUE TITLE
Convert Strings to URIs at the edge of our apps

### ISSUE THREAD

**Issue by severinrudie** [mozilla-mobile/android-components#648]
#### Overview
We're working with URIs as strings across a lot of our apps.  Standardizing all of our repos to use one URI implementation, and then parsing strings at the edges of our apps and internally using this URI type would yield benefits.

#### Benefits
- Stricter type safety
- Function signature expressiveness
- Less repetition of parsing and error handling

#### Potential Class Candidates
- android.net.Uri
- java.net.URI - unintuitive interface
- java.net.URL - lots of landmines in the implementation (e.g. #equals makes a blocking network call)
- okhttp3.HttpUrl - doesn't cover our use cases, and library is not used by all of our repos
- Potentially more options?

Internal conversations have pointed to android.net.Uri being the best fit, for the above reasons.

#### Proposed Next Steps
- Finalize decision on which class to standardize around
- Identify files where this change could be made in small steps

**Comment by pocmo** [comment]
Another interesting data point may be all our UrlUtils classes, here for example the one in Focus:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/utils/UrlUtils.java#L23

It would be nice if we could get rid of that and offer this functionality either in a wrapper or as an extension function on what we'd pick.

**Comment by pocmo** [comment]
WebView internally uses `Uri` too, like here in WebResourceRequest:
https://developer.android.com/reference/android/webkit/WebResourceRequest

**Comment by Baron-Severin** [comment]
The more I look at this the more I think `Uri` with some extension functions is the way to go.  I don't think we have enough custom behavior to even make a wrapper worth the effort.

**Comment by NotWoods** [comment]
Reviving this conversation. If we want to converge on `Uri` let's ask contributors to help convert internal functions to use it instead of `String`. Should I open an issue for this?

**Comment by pocmo** [comment]
Looking through old issues and closing them if they are not applicable anymore.

This is still interesting, but not something we will look at anytime soon, I think.
