### ISSUE TITLE
[Bug] Add-ons icons flicker after Dark Reader add-on is installed

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/android-components#6480]
### Steps to reproduce
1. Go to Settings - Add-ons.
2. Install Dark Reader add-on and observe the icons of all the add-ons.

### Expected behavior
There is an animation while the icons are loading.

### Actual behavior
The animation flickers. Please see the attached short video.

### Device information
* Android devices: OnePlus 5T (Android 8), Samsung Galaxy Tab A6 (Android 5.1.1), and Google Pixel (Android 10)
* Fenix version: Nightly build (#20861010) 38.0.20200325130041, c580c22, GV: 76.0a1-20200324093140, AS: 0.55.0

![icon-flicker](https://user-images.githubusercontent.com/40694158/78120191-2f4c8a00-7412-11ea-83c0-ba9c893c3d98.gif)

**Comment by csadilek** [comment]
This is not specific to one add-on. So duping to https://github.com/mozilla-mobile/android-components/issues/6481.
