### ISSUE TITLE
[Bug] Delay in displaying the actual status of  HTTPS Everywhere

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6485]
## Prerequisites
HTTPS Everywhere should be installed.

## Steps to reproduce
1. Repeatedly disable/enable HTTPS Everywhere  

### Expected behavior
When disabled the status should be immediately set  to OFF

### Actual behavior
HTTPS Everywhere is disabled, the status remains set to ON for a couple of seconds

### Device information
* Android device: Google Pixel 3a (Android 10)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
►Video 
![20200401-140214](https://user-images.githubusercontent.com/51314259/78131939-8bb8a500-7424-11ea-9f3f-93fdfc5e93f9.gif)

**Comment by csadilek** [comment]
Thanks for filing! I don't think there's anything we can do here. enable/disable may take "some" time especially if toggled as quickly as in this video. As the state is consistent, I am closing this. However, they may be a better UX design for these operations. We'll discuss...
