### ISSUE TITLE
[Bug] Remove the "(.." from the ⋮ Main menu

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6488]
## Prerequisites
HTTPS Everywhere should be installed.

## Steps to reproduce
1. Navigate to any website
2. Tap the ⋮ Main menu
3. Check the HTTPS Everywhere Add-on
4. Tap on HTTPS Everywhere 
5. Enable "Encrypt All Sites Eligible is OFF" and tap the device back button
6. Tap the ⋮ Main menu and check the HTTPS Everywhere Add-on
7. Tap on HTTPS Everywhere 
8. "Disable HTTPS Everywhere on this site"
9. Tap the ⋮ Main menu and check HTTPS Everywhere 

### Expected behavior
Make it more like the desktop version.
The user can identify the changes based on the color of the HTTPS Everywhere icon from the ⋮ Main menu

### Actual behavior
 "(.." is displayed in the ⋮ Main menu

### Device information
* Android device: Google Pixel 3a (Android 10)

* Fenix version: Custom Nightly(Build #20861010) 38.0.20200325130041, c580c2293
GV: 76.0a1-20200324093140 AS: 0.55.0

### Notes
► How HTTPS Everywhere is displayed on desktop
• HTTPS Everywhere is ON ![ena](https://user-images.githubusercontent.com/51314259/78145866-18ba2900-743a-11ea-9ea6-1b16ee6e23a8.JPG)
• "Encrypt All Sites Eligible is ON" ![turbo](https://user-images.githubusercontent.com/51314259/78145895-2079cd80-743a-11ea-9922-8eb2b25b8625.JPG)
• HTTPS Everywhere is disabled on this site ![dis](https://user-images.githubusercontent.com/51314259/78145923-28397200-743a-11ea-8989-869e67d206a3.JPG)

► How they are displayed in Fenix's  ⋮ Main menu
![rsz_fin](https://user-images.githubusercontent.com/51314259/78147119-bc580900-743b-11ea-8efb-0547bbfc1889.png)

**Comment by csadilek** [comment]
That's not something we can fix. This needs to be addressed in the add-on by the add-on developer specifically for Fenix. Please add to list to relay to add-on developer for improvement.
