### ISSUE TITLE
Implement private browsing mode for system engine

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#649]
This is a bigger task, not covered by #499.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5471)

**Comment by marekchen** [comment]
any progress?

**Comment by marekchen** [comment]
has some progress?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794671

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
