### ISSUE TITLE
Add Pocket endpoint component

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#651]
On Fire TV, we access the Pocket APIs to get a trending video content list: we could componentize this access, as well as any other Pocket APIs other teams use.

We could also consider:
- Wrapping this in a caching layer
- Fetching related resources (e.g. thumbnails from the thumbnail url param)

Benefits:
- Only have to write this code once
- Easy to use one Pocket API if you're using another
- Teams don't need to deal with a REST API: they make a function call and get Kotlin objects back
- If the Pocket API version gets updated, everyone can update for free(ish)

**Comment by pocmo** [comment]
Following the pattern of other components `services-pocket` would be a good home for that. I'll ping the Pocket Android team to see what they think. :)

**Comment by mcomella** [comment]
We have an unsolved problem: **the Pocket API versions each URL** via GET params (e.g. `.../video-recs?version=4` and `.../article-recs?version=2`). Because these APIs are internal to Mozilla, they are liable to change. If the APIs change between versions, we'll likely need to update this module too. However, in a native solution, the updates to this module **are likely breaking changes.**

@pocmo To save time, you may wish to jump to my opinion on the solution before reading through all of the options.

## Background context
- It's unclear how long the Pocket server team will support each API version

## Existing solutions
When REST APIs introduce breaking changes, the major version number is bumped and the client libraries (e.g. for the JVM) will release an entirely new library for the new version (e.g. Yelp API). This is infrequent so is not a problem. This solution doesn't really apply to us.

## Potential solutions
#### 1) Naive solution: do not handle multiple versions, i.e. introduce breaking changes in a-c when changing versions.
- Only known Pocket consumer atm is APT Amazon team so easier to coordinate upgrades

Pros:
- Least work from a-c developer perspective

Cons:
- More potential for a-c breaking changes, forcing work on consumers
- Worst case: the Pocket API is broken for some consumers in a new version so they want to stay on an old a-c. However, old a-c has bugs. They are stuck!
  - Potential solution: temporarily copy entire `:service-pocket` module into a new a-c module until the bug is fixed in the Pocket API

#### 2) Provide a method (and returned data type) for each API URL
e.g. `getGlobalVideoRecommendationsV2(): GlobalVideoRecommendationV2`

Pros:
- All API versions remain available (assuming the server supports them)
- No breaking changes

Cons:
- A lot of redundant code, types, methods, and tests and a lot of work to share code with private functions

#### 3) Endpoint methods take version parameter, return castable type
e.g.: `val recs = getGlobalVideoRecommendations(version = 2) as List<GlobalVideoRecommendationsV2>`

- Even adding fields to a Kotlin data type is a breaking change because it breaks equals comparisons (e.g. if a data type is persisted between versions)

Pros:
- API has fewer methods so is less confusing

Cons:
- Need to support multiple versions with same code path
- Consumers need to cast to get up-to-date type: unintuitive, not type safe, and slighly underperformant

#### 4) Returned objects support "expansion field"
e.g.
```kotlin
val videoRecommendation: GlobalVideoRecommendation = endpoint.get...(version = 2)
val expandedVideoData = videoRecommendation.expansionSlot.expandV2()
```

- Like 2) but a-c adds less global methods to handle new versions rather than expanding the existing `pocketEndpoint` API

Pros:
- Less confusing to call Pocket API directly than similar approach 2)

Cons:
- Assuming `endpoint.get...` sends a default version, if the server stops supporting these versions, then the intuitive way to call (with the default version) will break
- Confusing API to get expansion data
- Still need to maintain code to handle multiple versions

## My opinion
After writing this up, I'm leaning towards 1): don't handle multiple versions of a single URL in a version of components. _We don't know for sure that we will ever encounter this problem_ so we may be prematurely optimizing by trying to fix it. We can **document this shortcoming in the module README** and **implement a complex solution only if we run into this** a handful of times.

@pocmo What are you thinking?

**Comment by pocmo** [comment]
@mcomella I have been thinking about this and came to the same conclusion: I think we should try to track the latest version only. And your conclusion makes sense to me too: Let's tackle the problem once it arises - we gain almost nothing dealing with it now: The cost to change is low.

And let's think about the changes that may happen:
* If the new version add something (e.g. adding `tv_url`) then we can just add this too and use the latest version, yay.
* If the new version removes something (e.g. removing `tv_url`): If it wasn't used by us then we can just remove it and use the latest version. If this was actually used then we should communicate that back to Pocket and try to find a solution instead of depending on some old version.
* If things get moved/renamed/changed (e.g. different names, different parameters, different enum values, ..) we can migrate to the latest version and (if we want to) try to hide some of that change behind our interfaces..

Overall the number of consumers is manageable and if a bigger migration is happening then we can communicate that and plan that to reduce the friction with the app teams. It's not like the component will have to change randomly. :)

**Comment by mcomella** [comment]
> If the new version add something (e.g. adding tv_url) then we can just add this too and use the latest version, yay.

If the consumer is persisting and constructing new instances of our data types, they'll have to handle the possibility of the persisted data missing the newly introduced field. @pocmo How should we handle this? Should we:
1. Prevent consumers from using our data types by hiding constructors? (this will force them to duplicate the subset of the data types they want to use)
1. Provide code to persist and restore our data types (e.g. as JSON)?
1. Something else...?

1) seems the most decoupled and technically correct but forces the consumer to do more work to use our APIs. 2) forces the work into components but we may never use this functionality.

Maybe we should go the same route as general versioning: do nothing until someone actually needs to persist these data types and then identify what the optimal solution is for that use case. I'll likely need to persist on Echo Show so... I guess we'll figure it out then! It seems safe enough to mark the constructors as `internal` in the mean time.

> Overall the number of consumers is manageable and if a bigger migration is happening then we can communicate that and plan that to reduce the friction with the app teams. 

I'm concerned there may be consumers we're not aware of but maybe that's unwarranted.

**Comment by mcomella** [comment]
I didn't mean to close this in https://github.com/mozilla-mobile/android-components/commit/742786c25f88ce8ab9dd3203a04104082e67eca0 – @pocmo can you reopen?
