### ISSUE TITLE
Always set a locale in updateResources

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#6517]
For mozilla-mobile/fenix#220

When Fenix gets created with the system default locale we are unable to change the locale without restarting the app. If the application is created with a locale the locale switcher works 🤷‍♂

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5507)

**Comment by csadilek** [comment]
This landed in https://github.com/mozilla-mobile/android-components/pull/6518.
