### ISSUE TITLE
BrowserIcons leaks URLs to Logcat

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#6519]
Release builds should not log URLs to logcat. Using Fenix 4.2.1 I am seeing lines like

`D/BrowserIcons: Loaded icon (source = MEMORY): https://app.starbucks.com/?utm_source=homescreen`

**Comment by csadilek** [comment]
In https://github.com/mozilla-mobile/fenix/pull/15747 we've removed all debug logs from Fenix release builds to cover both A-C and GV.  Closing.
