### ISSUE TITLE
Error page not working properly

### ISSUE THREAD

**Issue by egorstepanov** [mozilla-mobile/android-components#6529]
Sample: [SystemEngineView](https://github.com/egorstepanov/SystemEngineView)

**Case 1:**
If used as is, it does not work
`
val errorPageUri = ErrorPages.createUrlEncodedErrorPage(
            context = context,
            errorType = improvedErrorType,
            uri = uri,
            htmlResource = riskLevel.htmlRes
        )
return RequestInterceptor.ErrorResponse.Uri(errorPageUri)
`
![Screenshot_1586100817](https://user-images.githubusercontent.com/9015108/78503535-d9f4dd80-776f-11ea-8f11-a9120d240516.png)

**Case 2:**
Replace resource://android/assets to file:///android_asset
`return RequestInterceptor.ErrorResponse.Uri(errorPageUri.replace("resource://android/assets", "file:///android_asset"))`
The error page reloads and the site does not load

![Untitled](https://user-images.githubusercontent.com/9015108/78503513-b03bb680-776f-11ea-88a3-049555cd8187.gif)

**Case 3:**
Use default content error page
`return RequestInterceptor.ErrorResponse.Content(ErrorPages.createErrorPage(context, improvedErrorType, uri))`
![Untitled2](https://user-images.githubusercontent.com/9015108/78503716-0d843780-7771-11ea-9a4f-6bae9caeb4c6.gif)
The error page just disappeared.
GeckoView might be the same.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5515)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795137

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
