### ISSUE TITLE
Camera permission dialog looks cut off

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6532]
Reference Browser, Pixel 2 Emulator (Android 5, API 21).

![Screenshot_1586163023](https://user-images.githubusercontent.com/89638/78540493-88dafd00-77f4-11ea-8756-8343dd19f697.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5516)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796462

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
