### ISSUE TITLE
Add option for adding bread crumbs to CrashReporting interface

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6535]
For debugging some crashes it would be very helpful if components could add breadcrumbs too.

**Comment by pocmo** [comment]
@rocketsroger What do you think? Afaik we added a limit for breadcrumbs, so I am not sure how helpful it really will be.

**Comment by rocketsroger** [comment]
> @rocketsroger What do you think? Afaik we added a limit for breadcrumbs, so I am not sure how helpful it really will be.

I agree that this will be helpful.  I'll look into it.
