### ISSUE TITLE
Remove unique identifiers from Sentry reports

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6577]
Sentry is not very good at understanding that the following reports are really all the same:

```
IllegalStateException
androidx.fragment.app.Fragment in setOnStartEnterTransitionListener
Trying to set a replacement startPostponedEnterTransition on HomeFragment{2b916fc} (66d6e8b1-e1dd-4a10-b54d-f03f7003a312) id=0x7f090170}
```

```
IllegalStateException
androidx.fragment.app.Fragment in setOnStartEnterTransitionListener
Trying to set a replacement startPostponedEnterTransition on HomeFragment{55af279} (b5a85f9a-a118-45cf-9314-620f1801bbe9) id=0x7f090170}
```

It groups exceptions with a similar type and message pretty well, but when UUIDs or pointer addresses are in the message, that process fails and results in a very large number of reports that we need to group manually.

This ticket is to run an experiment where we try to write a `preSubmit` Sentry hook that blanks out UUIDs and Pointer addresses. I think a simply regular expression can probably catch those pretty easily.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5575)

**Comment by st3fan** [comment]
I don't really understand how Sentry decided to de-dupe reports. For example, the following two are clearly the same (same exception, message, trace) but are reported separately:

 * https://sentry.prod.mozaws.net/operations/fenix/issues/7680944
 * https://sentry.prod.mozaws.net/operations/fenix/issues/7680945

While this one is grouped and if you browse through the exceptions under it, you can definitely see exception messages with different pointer addresses in it:

 * https://sentry.prod.mozaws.net/operations/fenix/issues/7676199

These exceptions have different tags, different breadcrumbs. And yet some group and some don't.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792913

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
