### ISSUE TITLE
Update sentry-android to latest release

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6579]
We are a bit behind with the Sentry Android SDK. Let's upgrade it to the latest release.

Also filed in Fenix at https://github.com/mozilla-mobile/fenix/issues/9803

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5578)

**Comment by ekager** [comment]
In the latest releases (2.x+) there are now automatic breadcrumbs for app, activity and sessions lifecycles and system events and the ability to view ANRs. Seems like the value of updating would be helpful. 🙏
