### ISSUE TITLE
Add more specific messages for bad SSL certificate errors

### ISSUE THREAD

**Issue by owlishDeveloper** [mozilla-mobile/android-components#6600]
Desktop Firefox can display various messages specific to the kind of the bad SSL certificate error that occurred. It would be nice if Android Components also supported this functionality. Currently there is only one error message that is displayed in all cases; however, in some cases it may not be informative enough for the app user.

For the context and more information, [see this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1622805)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5599)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795155

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
