### ISSUE TITLE
Don't require icon view within the tabs tray items

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/android-components#6610]
The new tabs tray in reference browser and fenix may not rely on the icon view so for now we shouldn't assume it exists.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5603)

**Comment by csadilek** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/6611.
