### ISSUE TITLE
Domain autocompletion results in duplicated characters when a keyboard suggestion is used

### ISSUE THREAD

**Issue by Rob--W** [mozilla-mobile/android-components#6618]
The location bar autocompletes popular(?) domains when it is typed, but the implementation seems to have a bug when a suggestion from the keyboard is used. When I choose a suggestion from the keyboard (e.g. Android's default keyboard, Gboard) that overlaps with the suggested domain, then the autocompletion result is not updated, which results in some duplicated characters.

STR:
1. Type `Disn`
2. Observe that Fenix/RB will autocomplete to `disn[ey.go.com]` (`[` and `]` mark the autocompletion suggestion)
3. The keyboard suggests `Disney`, tap on it to fill it in.
4. Look at the location bar.

Expected:
- `Disney[.go.com]`

Actual:

- `Disney[ey.go.com]`

When I typed `disne` before autocompleting to `Disney`, the result becomes `Disney[y.go.com]`. It seems that the implementation fails to detect the suggested word.

Reproduced with the latest versions of Firefox Preview, Firefox Beta (both based on Fenix) and Reference browser. E.g. Firefox Preview 4.2.1 (build #20941431).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5609)

**Comment by csadilek** [comment]
I can not reproduce this anymore. Rob, please re-open if you still see this. Thanks!

**Comment by Rob--W** [comment]
I can still reproduce with a different STR.

Instead of the autocompletion of the browser, use the keyboard's completion.

STR:
1. type wiki. Firefox Focus shows wiki[pedia.org].
2. Keyboard (e.g. Gboard) shows Wikipedia as one of the suggested words. Tap on it.

Firefox focus now shows Wikipedia[pedia.org], instead of Wikipedia[.org]
