### ISSUE TITLE
Provide API to set session defaults

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#662]
Currently there's no way for an application to specify default session characteristics e.g. that all sessions should be private and have tracking protection enabled.

We need to look into building out an API for this.

**Comment by pocmo** [comment]
While working on the `browser-engine` integration into Firefox for Fire TV I noticed that they have a quite complex settings setup for every WebView:
https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/amazonWebview/java/org/mozilla/focus/iwebview/WebViewProvider.kt#L63-L100

This may be something for a follow-up. I just wanted to bring it up here in case your implement something that configures engine (views) too.
