### ISSUE TITLE
Reduce AMO read timeout to 5s for migration

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#6633]
Our current timeout is 20s. Let's reduce to speed up migration runs.

**Comment by ebalazs-sv** [comment]
I had tested this on Nexus 5 API 23 (Android 6) - x86_64 with the cellular signal strength set on "Poor" and the Beta migration build 75.0.0-beta.5 did not encounter any issues while migrating. The migration time was ~20 seconds.
@grigoryk Is there other scenario that could be tested here?
Thanks!

**Comment by grigoryk** [comment]
@ebalazs-sv this is a little tricky to QA, but we're seeing in migration data that it had a desired impact (reduced total average migration duration).
