### ISSUE TITLE
Support migrating history and bookmarks on Fennec v49+

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#6637]
Currently we support migrating history and bookmarks on Fennec v57+.

We can easily go down to v49+. For bookmarks, we can go down to v30, but that starts to introduce some difficulties, since currently history and bookmark migrations are potentially intertwined. For now, it's simpler to just this support at the same version.

To test this, try migrating Fennec version that are newer than 49 but older that 57. Both history and bookmark migrations should work.

When migrating versions older than 49, history and bookmarks are expected to not be migrated as part of this ticket.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Fennec Beta Migration 75.0.0-beta.3, from 4/14, with Fennec Beta version between 49 and 57. The Bookmarks and History are migrated and functional.
Devices used for testing:
- Xiaomi Mi Pad 2 (Android 5.1)- x86 on 55.0b5;
- Samsung Glaxy Note 10 (Android 10) on 56.0b7;
- OnePlus 6T (Android 9) on 50.0b12, 51.0b15, 52.0b8, 53.0b11, 55.0b8;
- Huawei P9 Lite (Android 7) on 50.0b1, 51.0b1, 51.0b13, 52.0b2, 53.0b1, 53.0b4, 56.0b11, 58.0b11.

**Comment by ebalazs-sv** [comment]
This was verified in the previous comment, so I will move this to Done.
