### ISSUE TITLE
Simplify initialization of UI components

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#665]
Especially in Focus I noticed the following pattern in UI components:

* (1) Set values on view from `Session`
* (2) Update views when data in `Session` changes

Previously with `LiveData` in Session in Focus' code (1) and (2) were the same operation. When subscribing to `LiveData` the observer is immediately invoked with the current value. This is different in our implementation where only _changes_ invoke the observer callbacks.

This causes some duplication like:

```Kotlin
viewA.setText(session.url)
viewB.setText(session.title)
...
session.observer(...
   onUrlChanged(session, url) {
     viewA.setText(url)
   }

  onTitleChanged(session, title) {
     viewB.setText(title)
  }
...
}
```

An app needs to define the relationship between data and view twice - once for initialization and then a second time for updates. Often that feels needlessly verbose.

This is slightly related to #400 where I have been looking at different ways to represent an immutable state.

**Comment by jonalmeida** [comment]
Something that notifies observers when they first register? This might have to be an init flag. 🤔 

Maybe something worth looking RxJava/RxKotlin to see how they solve this.

**Comment by pocmo** [comment]
Closing: This is going to be fixed by `browser-state` to. :)
