### ISSUE TITLE
Restoring source should be optional in SnapshotSerializer 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#6651]
When we save to a collection and then restore the tab, it's strange behavior to keep the source, but there's currently no way to strip the source when the session is already created AFAIK

**Comment by ekager** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/9938

**Comment by pocmo** [comment]
Good point. I wonder why we even decided to restore the source. I can only think of downsides. Maybe we should just replace it with a "restore" source.
