### ISSUE TITLE
Remove DOWNLOAD_WITHOUT_NOTIFICATION permission

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6656]
Currently `feature-downloads` adds `DOWNLOAD_WITHOUT_NOTIFICATION` to the manifest. Afaik this is not needed in apps that use a non-"android downloadmanager" implementation like Fenix? Let's remove it if possible and instead add something to the README explaining when it is needed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5656)

**Comment by djhango** [comment]
I believe this permission is required to prevent the `DownloadManager.addCompletedDownload` method from throwing a `SecurityException` when `false` is supplied as the value for the `showNotification` property. [StackOverflow Question regarding this exception](https://stackoverflow.com/questions/35741042/downloadmanager-addcompleteddownload-method-not-working-gives-securityexcepti)

The `addCompletedDownload` method is called within the `addToDownloadSystemDatabaseCompat` method of the `AbstractFetchDownloadService` class in `feature-downloads`. 

The `showNotification` property seems to be `false` when the `Downloads` notification channel is enabled.

This seems to provide backwards compatibility for Android 9 and earlier devices as the `addCompletedDownload` method is deprecated in Android API 29.

**Comment by csadilek** [comment]
Duping to https://github.com/mozilla-mobile/android-components/issues/10858.
