### ISSUE TITLE
glean/experiments: Hard dependency on lib-httpurlconnection

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6660]
I was investigating why we still see (I think unused) fragments of `lib-httpurlconnection` in Fenix APKs. I noticed that `service-glean` as well as `service-experiments` have a hard (non-test) dependency on `lib-httpurlconnection`.

* https://github.com/mozilla-mobile/android-components/blob/7b25cd702dcfc5e22be436d6c5c39fb8249e5a9c/components/service/glean/build.gradle#L56

* https://github.com/mozilla-mobile/android-components/blob/7b25cd702dcfc5e22be436d6c5c39fb8249e5a9c/components/service/experiments/build.gradle#L33

My assumption is that we can get rid of that dependency and instead always enforce passing in a `lib-fetch` implementation.

**Comment by travis79** [comment]
Sorry we missed this getting filed.  I filed [Bug 1634068](https://bugzilla.mozilla.org/show_bug.cgi?id=1634068) in Bugzilla so that this will be triaged in our next meeting.

**Comment by badboy** [comment]
Glean does _actively_ depend on `HttpURLConnectionClient` to [implement its uploader](https://github.com/mozilla-mobile/android-components/blob/208a9500f4024ad57e09a6633b180387b4263df8/components/service/glean/src/main/java/mozilla/components/service/glean/config/Configuration.kt#L7). [Same for experiments](https://github.com/mozilla-mobile/android-components/blob/208a9500f4024ad57e09a6633b180387b4263df8/components/service/experiments/src/main/java/mozilla/components/service/experiments/Configuration.kt#L8).

Both want to provide a default, so users don't need to care about it (but can still change it).

@pocmo: What do you propose as the way forward if a hard dependency on `lib-fetch-httpurlconnection` is not desired?

**Comment by pocmo** [comment]
I think we should avoid having a default inside `android-components` (`glean` of course can have a default itself). We desperately want to avoid using anything but Gecko for networking and those defaults just hide what is being used. It is so easy to not know about them.
