### ISSUE TITLE
Add custom search engine provider

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#6662]
We pulled the [`CustomSearchEngineStore`](https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/components/searchengine/CustomSearchEngineStore.kt)  from Focus into Fenix and we want to uplift this functionality to a-c

**Comment by levimatheri** [comment]
Hello @boek, I would like to work on this issue. Thanks!

**Comment by psymoon** [comment]
Closing as the new restructuring around search is being made: https://github.com/orgs/mozilla-mobile/projects/63
