### ISSUE TITLE
Loading error pages always returns invalid address 

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6689]
This can be seen in R-B ~and Fenix~ this is NOT Fenix-related.

### STR
1. Open a new private tab in R-B.
2. Observe the error page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5694)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795403

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
