### ISSUE TITLE
Bottom toolbar has instances where it where it will not reappear after hiding on scrolls

### ISSUE THREAD

**Issue by JLRoberts** [mozilla-mobile/android-components#6712]
https://drive.google.com/file/d/12NPXnk_Bu77Y6RA6zQWjMhRo6vaKki4M/view?usp=sharing

Current behavior scrolling sites in video above. Also reported in fenix issues:

https://github.com/mozilla-mobile/fenix/issues/10045
https://github.com/mozilla-mobile/fenix/issues/10040

**Comment by jonalmeida** [comment]
Closing based on the discussion in the PR.
