### ISSUE TITLE
FxA login should redirect to an error page even if finishAuthenticationAsync returns error

### ISSUE THREAD

**Issue by keianhzo** [mozilla-mobile/android-components#6727]
Related https://github.com/mozilla/application-services/issues/2995

During a FxA login flow, in case `finishAuthenticationAsync` returns error the redirect still goes to the success page. We should be redirected to an error page in that case and ideally be notified of the authentication error.

This can be easily reproduced if the login flow is completed with an invalid token for example.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5727)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796502

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
