### ISSUE TITLE
Cookie information not passed to DownloadState.

### ISSUE THREAD

**Issue by tirkkant** [mozilla-mobile/android-components#6735]
Cookie information is extracted in SystemEngineView but is not utilized in the EngineObserver.
This information is needed for authenticated download.

override fun onExternalResource(
        url: String,
        fileName: String?,
        contentLength: Long?,
        contentType: String?,
        **cookie: String?,**
        userAgent: String?
    ) {
        val download = DownloadState(
            url,
            fileName,
            contentType,
            contentLength,
            userAgent,
            Environment.DIRECTORY_DOWNLOADS
        )

        store?.dispatch(ContentAction.UpdateDownloadAction(
            session.id,
            download
        ))
    }

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5732)

**Comment by pocmo** [comment]
Hm, yeah, seems like we missed that. Probably because Gecko does not provide any cookies here and instead will use matching cookies when performing the download.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796476

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
