### ISSUE TITLE
Engine: add executeJavascript integration test

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#677]
We have an integration test (from a regression) on Firefox TV, `IWebViewExecuteJavascriptTest`, to ensure the javascript injection code we rely on so heavily doesn't break. Since executeJavascript will reply on the components' engine, it seems like it'd be more appropriate for the test to be in android-components. Here's the code: https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/androidTest/java/org/mozilla/focus/integration/IWebViewExecuteJavascriptTest.kt

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5752)

**Comment by pocmo** [comment]
Thank you for filling this.

One thing I am not sure about yet is whether we should add public evalJS/JavaScriptInterface methods to the engine component. GeckoView most likely won't add them (a WebExtension API is more likely). I wonder if instead we should add the functionality (e.g. media-session) to browser-engine-system and inject JS internally when needed.

**Comment by mcomella** [comment]
I think that sounds great from a correctness perspective but it sounds
impractical. It'll be slow to implement features that integrate with page
content (either if we have to add JS to the components repo or wait for
GeckoView to add this functionality): this is especially important because
injected javascript often relies on the page's specific DOM and if that DOM
changes, we'll want to move quickly to update our JS.

Fire TV, in particular, seems to have a lot of use cases for interacting
with page content so I think it'd be really difficult if we we required to
wait for the next components version to update our JS.
