### ISSUE TITLE
SwipeRefreshFeature should be triggered only by vertical scrolls

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#6781]
### Expected behavior
SwipeRefreshFeature should only be triggered by vertical swipe gestures.

### Actual behavior
Pull down to refresh is trggered also by
- pinch / spread zoom
- horizontal swipes

See Fenix - https://github.com/mozilla-mobile/fenix/issues/10241

We could make use of the same detector proposed for the dynamic bottom bar (https://github.com/mozilla-mobile/android-components/issues/2930)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5764)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795392

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
