### ISSUE TITLE
Publish git tags for nightly builds or otherwise publish commit information

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#6786]
I'm building fenix with a local a-c. a-c did not compile with the version of Fenix I'm using so I wanted to check out the last known version of a-c that worked with Fenix to mitigate. The last known version is `39.0.20200424130104` but [it's not present in the android-components` git tags](https://github.com/mozilla-mobile/android-components/tags). Therefore, in order to build locally, my options are to:
- Dig through the a-c commits to find the nightly revision I'm looking for
- Pull in the open PRs to Fenix to match my local Fenix master to a-c master

These are both time consuming. Ideally, we could publish the git tags for nightly revisions or publish the top-most commit in each nightly revision somewhere else so that I could have a simpler process for resolving this conflict.

**Comment by pocmo** [comment]
The way GitHub mixes releases and tags makes nightly tags pretty awkward. The Kotlin project on GitHub does that and it is impossible to find the last stable release in all those nightly (dev) tags.

GeckoView seems to publish the git revision inside the POM file, which is not super handy but at least makes it discoverable:
https://maven.mozilla.org/maven2/org/mozilla/geckoview/geckoview-nightly/79.0.20200603092905/geckoview-nightly-79.0.20200603092905.pom

As a workaround, in situations where you happen to have a build with this AC version locally, you can navigate to the `mozilla.components.Build` class, which will have a `gitHash` property that points to the commit this AC version was built from.

**Comment by mcomella** [comment]
pocmo suggested another work around: the latest nightly's about page points to a page with the a-c commit.

**Comment by mcomella** [comment]
I wrote a script that gets current ac -> a valid mc hash. It doesn't solve fenix -> ac (yet) but it prints the workaround pocmo suggested above. To specifically address the problem described by this bug, I think this script is a better solution than publishing the information online though there may be alternative use cases for the commit (e.g. we might have to decompile the APK to automate fenix -> ac - it'd be easier if it was published).

I didn't see anyone else agreeing with me that this information was important to post so I'll close this in favor of the script and whatever direction it takes: feel free to reopen.

**Comment by mcomella** [comment]
As part of enabling the fenix -> ac part, I wrote a PR to publish the hash the same way GV does, in pom.xml: https://github.com/mozilla-mobile/android-components/pull/8384 This satisfies the request underlying this ticket.
