### ISSUE TITLE
Refresh components website theme

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6789]
mozac.org could use a refresh to make our component's status/guides/blog standout more.

There are some free Jekyll themes we could check out:
 - https://jekyllthemes.io/
 - http://jekyllthemes.org/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5770)

**Comment by NotWoods** [comment]
I attempted to build our site with Jekyll locally to test out, but it takes hours with all the generated documentation. We may want to explore moving to Netlify/using CI to build a gh-pages branch, then using Hugo as its significantly faster.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795401

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
