### ISSUE TITLE
Update component status page

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#6790]
We could consider removing it since it's duplicate or keeping it in sync with some automated way to reflect the components.

Alternatively, find a better way to display our structure.

https://mozac.org/components/

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5773)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795149

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
