### ISSUE TITLE
Fennec migration: The build version is displayed as null on Release migration

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#6793]
## Preconditions:
Have Fennec Release installed.
## Steps to reproduce
1. Replace Fennec Release with Fenix Release;
2. Go to Settings -> About Firefox Preview;
3. Observe the build version.
### Expected behavior
The build version is displayed, containing numbers.
### Actual behavior
The build version is displayed as "null".
### Notes:
[Screenshot](https://drive.google.com/open?id=1SJ_e-CuBxhecdxbhd3YNpn0Gwybybhbp)
### Device information

* Android device: Google Pixel 2 (Android 9);
* Fenix version: Release Migration (Build #2015737139) 4/28;

**Comment by Mugurell** [comment]
I understand from `build.py` that versionName is to be provided as a build parameter.
I see atm the "Firefox Preview" branding is still used so maybe this is still work in progress.
Maybe @JohanLorenzo can offer a bit more insight if there's anything to do here.

**Comment by JohanLorenzo** [comment]
Hi there! I'm sorry about the confusion. This issue shares the same root cause as https://github.com/mozilla-mobile/android-components/issues/5262. The full explanation is at https://github.com/mozilla-mobile/android-components/issues/5262#issuecomment-584559951. Good news is: it won't impact the build we'll send to end-users.

**Comment by Mugurell** [comment]
Thank you Johan.
In this case, I'll do the same as per [Sebastian's comment](https://github.com/mozilla-mobile/android-components/issues/5262#issuecomment-585642944) and move this issue to the QA column.
Only to be verified before the actual release in which time the correct versionName will be set.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release Migration 79.0.0 (Build #2015753313) GV 79 from 7/21 with Google Pixel 4XL (Android 11), Motorola Moto G6 (Android 8), Huawei MediaPad M3 lite (Android 7), Samsung Galaxy Tab S6 (Android 9).
