### ISSUE TITLE
Intermittent test failure java.lang.instrument.IllegalClassFormatException: mozilla.components.feature.addons.update.AddonUpdaterWorkerTest: Error while instrumenting mozilla/components/browser/state/store/BrowserStore.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#6796]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=299790699&repo=android-components

[task 2020-04-28T13:35:57.653Z] SUITE: mozilla.components.feature.addons.update.AddonUpdaterWorkerTest
[task 2020-04-28T13:35:57.653Z]   TEST: doWork - will return Result_success when SuccessfullyUpdated
[task 2020-04-28T13:35:57.753Z]     [Robolectric] mozilla.components.feature.addons.update.AddonUpdaterWorkerTest.doWork - will return Result_success when SuccessfullyUpdated: sdk=28; resources=binary
[task 2020-04-28T13:35:57.753Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-04-28T13:35:57.753Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@4668f946', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@4668f946'
[task 2020-04-28T13:35:57.853Z]     java.lang.instrument.IllegalClassFormatException: Error while instrumenting mozilla/components/browser/state/store/BrowserStore.
[task 2020-04-28T13:35:57.853Z]     at org.jacoco.agent.rt.internal_43f5073.CoverageTransformer.transform(CoverageTransformer.java:94)
[task 2020-04-28T13:35:57.853Z]     at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
[task 2020-04-28T13:35:57.853Z]     at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
[task 2020-04-28T13:35:57.853Z]     at java.lang.ClassLoader.defineClass1(Native Method)
[task 2020-04-28T13:35:57.853Z]     at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
[task 2020-04-28T13:35:57.853Z]     at java.lang.ClassLoader.defineClass(ClassLoader.java:636)
[task 2020-04-28T13:35:57.853Z]     at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:134)
[task 2020-04-28T13:35:57.853Z]     at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:111)
[task 2020-04-28T13:35:57.853Z]     at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
[task 2020-04-28T13:35:57.853Z]     at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:110)
[task 2020-04-28T13:35:57.853Z]     at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[task 2020-04-28T13:35:57.853Z]     at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[task 2020-04-28T13:35:57.853Z]     at mozilla.components.feature.addons.update.AddonUpdaterWorkerTest.initWebExtensionSupport(AddonUpdaterWorkerTest.kt:50)
[task 2020-04-28T13:35:57.853Z]     at mozilla.components.feature.addons.update.AddonUpdaterWorkerTest.setUp(AddonUpdaterWorkerTest.kt:46)
[task 2020-04-28T13:35:57.853Z]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-04-28T13:35:57.853Z]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-04-28T13:35:57.853Z]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-04-28T13:35:57.853Z]     at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-04-28T13:35:57.853Z]     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-04-28T13:35:57.853Z]     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-04-28T13:35:57.853Z]     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-04-28T13:35:57.853Z]     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
[task 2020-04-28T13:35:57.853Z]     at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[task 2020-04-28T13:35:57.853Z]     at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
[task 2020-04-28T13:35:57.853Z]     at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[task 2020-04-28T13:35:57.853Z]     at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2020-04-28T13:35:57.853Z]     at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2020-04-28T13:35:57.853Z]     at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2020-04-28T13:35:57.853Z]     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2020-04-28T13:35:57.853Z]     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2020-04-28T13:35:57.853Z]     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2020-04-28T13:35:57.853Z]     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2020-04-28T13:35:57.853Z]     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2020-04-28T13:35:57.853Z]     at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2020-04-28T13:35:57.853Z]     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2020-04-28T13:35:57.853Z]     at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
[task 2020-04-28T13:35:57.853Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2020-04-28T13:35:57.853Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2020-04-28T13:35:57.853Z]     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2020-04-28T13:35:57.853Z]     at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2020-04-28T13:35:57.853Z]     at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)

and many, many more lines

**Comment by jonalmeida** [comment]
I'm going to close this since I don't think we see this failure any more. Please re-open if I'm wrong.
