### ISSUE TITLE
Firefox Preview says camera on when it's not. Have to reboot phone to get rid of it.

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/android-components#6810]
Original issue filed under GeckoView as [Bug 1630137](https://bugzilla.mozilla.org/show_bug.cgi?id=1630137). Please see issue for more details, including lots of contextual screenshots.

This was determined to be an AC (or Fenix) issue, not a GeckoView one.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5797)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795391

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
