### ISSUE TITLE
when using short numbers `sms:` scheme link creates a message to a wrong recipient

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#6816]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1626288

Steps to reproduce:

    Create a web page that contains an sms scheme hyperlink.
    Hyperlink should contain a short phone number and a body (Exact example used to reproducce: <a href='sms:13033?body=two or more words'>Click for SMS</a>)
    Load this web page in Firefox for Android.
    Click (tap) on the 'Click For SMS' link.

Actual results:

The number pre-populated in the message is '//13033'

Expected results:

The number should have been '13033'

**Comment by rocketsroger** [comment]
Looks like the formatting that works with Android is:
`<a href="sms:/* phone number here */?body=/* body text here */">Link</a>`

**Comment by rocketsroger** [comment]
A good test site for both Android and iOS
https://bradorego.com/test/sms.html

**Comment by rocketsroger** [comment]
Tested with the following and it works fine.  The issue here is probably the single quote vs double quote.  Won't fix.  Closing.
`<a href="sms:13033?body=two or more words">Click for SMS</a>`
