### ISSUE TITLE
Document process to land new component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#685]
Document the process to land a new component. In theory we could even write a small bootstrap script.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5831)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794670

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
