### ISSUE TITLE
Fennec migration: List of unavailable add-ons is not refreshed

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#6855]
## Preconditions:
Have unavailable add-ons for Fenix Beta added to Fennec Beta.
## Steps to reproduce
1. Replace Fennec Beta with Fenix Beta;
2. Launch Fenix and go to the Add-ons list;
3. Scroll to the end of the list and tap the "Not yet available" section;
4. Delete one add-on from the list and tap the back button;
5. Tap the "Not yet available" and observe add-ons from the list; 
### Expected behavior
The deleted add-on is not displayed in the list.
### Actual behavior
The deleted add-on is displayed in the list and cannot be deleted, the "Failed to remove" pop-up message is displayed.
### Notes:
[Video](https://drive.google.com/open?id=1A81so8pvA8NIgBpm6OxGvc7KwaZ3zCKD)
The list is refreshed after leaving the Add-ons list and then going back.
### Device information

* Android device: Nexus 5 (Android 6.0.1); Motorola Moto G6 (Android 8), Huawei MediaPad M3 lite (Android 7).
* Fenix version: Beta migration build 76.0.0-beta.1 from 5/1.

A similar issue was filed by @csadilek in https://github.com/mozilla-mobile/android-components/issues/5815, that is fixed.

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration Build 76.0.0-beta2, from 5/14 with Motorola Moto G6 (Android 8).

**Comment by softvision-miralobontiu** [comment]
This is still reproducible with the latest migration build 5.1.0-beta.2 with OnePlus 5T (Android 9).

**Comment by Diana-Rus** [comment]
Hi, this is still reproducible with the latest migration build 5.1.0-beta.3 with Google Pixel 3XL (Android 9).

**Comment by Amejia481** [comment]
> Hi, this is still reproducible with the latest Beta migration build -> 5.1.0-beta.3 with Google Pixel 3XL (Android 9).
> GIF:
> ![20200602-144314](https://user-images.githubusercontent.com/49859863/83516414-ac15e600-a4df-11ea-9c3f-7db82f18eb4d.gif)

Thanks for verifying @Diana-Rus
We need to wait for the new version of AC to land on Fenix https://github.com/mozilla-mobile/fenix/pull/11142 :) the fix will be available on nightly. I created a new Fenix bug to test https://github.com/mozilla-mobile/fenix/issues/11144
