### ISSUE TITLE
a-c files busted crash reports to crash-stats

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/android-components#6903]
While looking into [GeckoView Bug 1633786](https://bugzilla.mozilla.org/show_bug.cgi?id=1633786), I noticed the crashes have a "CrashType" set to "caught excepetion". This seems to be a string from the a-c crash reporter. It looks like a-c is sending either malformed or incomplete reports in some cases.

**Comment by liuche** [comment]
We're seeing a lot of comments about "Nightly crashing all the time" on [reddit](https://www.reddit.com/r/firefox/comments/gf46bg/firefox_preview_nightly_keeps_crashing_on_android/) and matrix, and [crash-stats](https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=0.0a1).

Also suspicious that the version reported is `0.0a1` rather than `78.0.0a1` or `77.0.0a1`.

I'd like to get this fix before we make our next Fenix release.

**Comment by rocketsroger** [comment]
`0.0a1` is a work around for Socorro.  Any Fenix nightly build (version starts with Nightly) will have the version `.0.0a1`.  From the meta data we can see that the version is `Nightly 200427 06:01`.

**Comment by rocketsroger** [comment]
https://crash-stats.mozilla.org/report/index/b08f818e-f4ca-4436-b94f-75b9e0200428

**Comment by rocketsroger** [comment]
This is a caught request.  So Fenix didn't actually crash.  The exception was caught in a try catch and the report was sent so we can keep an eye on it.  I'll have to look into which part of the code is sending this report without forwarding the crash stack properly.

**Comment by rocketsroger** [comment]
Looks like some of the components in A-C is calling `submitCaughtException` without passing in a throwable with a stack.  I think lib-crash will probably have to create the stack before submission so the report makes sense.

**Comment by liuche** [comment]
Is this [other report also a caught exception](https://crash-stats.mozilla.org/signature/?product=Fenix&signature=EMPTY%3A%20no%20crashing%20thread%20identified%3B%20ERROR_NO_MINIDUMP_HEADER&version=0.0a1&date=%3C2020-05-12T02%3A58%3A01%2B00%3A00&date=%3E%3D2020-05-05T02%3A58%3A01%2B00%3A00), not a real crash? 

Will the new stacks show that this is a caught exception, vs a crashing one? (such as some of the other ["top crashers" that show INFO](https://crash-stats.mozilla.org/topcrashers/?product=Fenix&version=0.0a1) so it's easy to tell).
