### ISSUE TITLE
Port over showing test results in UI test TaskCluster tasks

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/android-components#6904]
Same as https://github.com/mozilla-mobile/fenix/pull/10089

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5885)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795365

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
