### ISSUE TITLE
Dokka: Generate aggregated API docs

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#691]
Currently we create separate API docs for all modules. Because of that you can't jump between modules in the documentation. For example if you are on the page about `GeckoEngine` you can't get to `Engine` because this class is in a different module.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5891)

**Comment by pocmo** [comment]
I wasn't able to come up with a satisfying solution on Friday.

The only thing about generating a multi module documentation is this issue in the dokka repository:
https://github.com/Kotlin/dokka/issues/157

One of the mentioned solutions is to create a module just for generating the documentation and letting this module depend on all other modules. This sounds like it's too hacky for us and I was trying to avoid this.

I pushed my state here:

This branch does:
* Generate a multi-module documentation
* Links from classes to the source code on GitHub
* Links to the Android documentation for Android classes
* Links to the Kotlin documentation for Kotlin classes

It does not:
* Major: Know about dependencies. For example the GeckoRuntime parameter in GeckoEngine is labelled as: `runtime: <ERROR CLASS>`
* Minor: Group by "module"/"artifact" somewhere. You can only browse by package.

Also: telemetry has a different package layout and looks a bit weird in that mix: #698.

**Comment by pocmo** [comment]
Dokka has a classpath parameter:

```
    // Manual adding files to classpath
    // This property not overrides classpath collected from kotlinTasks but appends to it
    classpath = [new File("$buildDir/other.jar")]
```

I assume that setting this to the "classpath" needed to compile the modules would resolve the issue of unknown classes. However I was unable to build this classpath dynamically.

Another thing I tried was adding GeckoView as a dependency to `dokkapath` but this didn't help resolving the classes.
https://github.com/pocmo/android-components/commit/f2df8f2c4319e1e4b15175fb54e939e7af99017e#diff-c197962302397baf3a4cc36463dce5eaR93

**Comment by csadilek** [comment]
> Major: Know about dependencies. For example the GeckoRuntime parameter in GeckoEngine is labelled as: runtime: <ERROR CLASS>

I managed to solve this by dynamically constructing the classpath. The main piece of the puzzle was `evaluationDependsOnChildren` which makes sure the subprojects are evaluated before the `dokka` task runs. I have not been able to make this work in any other way. Now references to GV and Android SDK types are resolved properly. Sent #723 containing the changes.

**Comment by csadilek** [comment]
Here's an example site for `GeckoEngine`:
![screen shot 2018-09-06 at 17 54 34](https://user-images.githubusercontent.com/472523/45187208-f4ff1480-b1fd-11e8-94d7-bf60ffdcf14a.png)

**Comment by pocmo** [comment]
@csadilek Awesome. Well done :)
