### ISSUE TITLE
CrashReporter: Log correct variable

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6914]
This should actually log the size of `telemetryServices` and not `services`:

https://github.com/mozilla-mobile/android-components/blob/9db12cb22bd0a4b70d1932f79d69b60432c32bc7/components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt#L119

**Comment by HaripriyaB** [comment]
Can I work on this issue?

**Comment by pocmo** [comment]
@HaripriyaB Sure! :) Let us know if you need any help. Either here or on Riot/Matrix: chat.mozilla.org "Android Components" room.
