### ISSUE TITLE
SessionManager.add should support insert position

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/android-components#6921]
In implementing the Undo Snackbar within Fenix (https://github.com/mozilla-mobile/fenix/pull/10456/files), we're adding a closed tab back into the tab tray when the user taps "Undo".  

AR:
Unfortunately that adds the item back to the bottom of the tab tray

ER:
The tab should be added back at its previous position.

I believe the `add` method should support an index which represents the index which the tab should be added.

**Comment by darkwing** [comment]
@jonalmeida Thoughts on how we can implement this?

**Comment by pocmo** [comment]
Are we certain that we absolutely need this **now**? Since we are migrating from `SessionManager` to `BrowserStore` we would like to not add anything to `SessionManager` anymore. And that is not a small change.

**Comment by jonalmeida** [comment]
I'm going to close this as won't fix in place of #7205 based on Sebastian's comment in the other ticket:

> We cannot change the position in BrowserStore only while we keep both (SessionManager) in sync because that would break the sync in certain situations.
