### ISSUE TITLE
Scroll to selected tab when opening the tab tray

### ISSUE THREAD

**Issue by darkwing** [mozilla-mobile/android-components#6922]
When opening a tab tray with many tabs, the tab tray does not scroll the selected tab into view, which can confuse users about where the tab they were just look at went.

We tried implementing this functionality in Fenix ourselves, but we ran into a timing issue in `onResume` where we were trying to do the scrolling before the tab tray had finished rendering.  @boek and I concluded that it's probably best we implement this feature in AC, as we'll have more control over the current state of rendering.

**Comment by darkwing** [comment]
@jonalmeida Thoughts on how we can implement this?

**Comment by jonalmeida** [comment]
This seems reasonable to have the selected tab always visible. You have the adapter you know the selected tab. So it should be possible to `scrollToPosition` when the tabs are updated.

**Comment by jonalmeida** [comment]
Closing this since we realized it's not something we can reasonably give to apps for free because it depends on when the TabsTray is visible to know when we want to scroll.
