### ISSUE TITLE
Record crash-stats id in Sentry crashes

### ISSUE THREAD

**Issue by snorp** [mozilla-mobile/android-components#6926]
It would be useful to be able to tie a Sentry crash to one in crash-stats. We could do this if we submit to crash-stats first, then record the crash id in the Sentry report. That would allow us to figure out which native Sentry crashes are caused by which GeckoView bugs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5914)

**Comment by pocmo** [comment]
Interesting idea. Not straight-forward to implement though since the library is crash service agnostic. Will have to think about this. 🤔

**Comment by pocmo** [comment]
Adding to our triage. Something I could add next sprint.

**Comment by csadilek** [comment]
Tracked in: https://bugzilla.mozilla.org/show_bug.cgi?id=1792901
