### ISSUE TITLE
Evaluate StateFlow

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#6934]
I just saw that the Coroutines library introduces a `StateFlow`:

> We need to be able to conveniently use Flow to represent an updateable state in applications. This change introduces StateFlow -- an updateable value that represents a state and is a Flow. The design is flexible to fit a variety of needs:
> 
>  -  StateFlow<T> interface is a read-only view that gives access to the current value and implements a Flow<T> to collect updates to the values.
>  - MutabaleStateFlow<T> interface adds value-modification operation.

That looks like it could be something we would want to use in `lib-state`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5923)

**Comment by pocmo** [comment]
> - StateFlow is simpler because it does not have to implement all the Channel APIs, which allows for faster, garbage-free implementation, unlike ConflatedBroadcastChannel implementation that allocates objects on each emitted value.
> - StateFlow always has a value that can be safely read at any time via value property. Unlike ConflatedBroadcastChannel, there is no way to create a state flow without a value.
> - StateFlow has a clear separation into a read-only StateFlow interface and a MutableStateFlow.
> - StateFlow conflation is based on equality, unlike conflation in ConflatedBroadcastChannel that is based on reference identity. It is a stronger, more practical conflation policy, that avoids extra updates when data classes are emitted. You can consider it to have an embedded distinctUntilChanged out-of-the-box.
> - StateFlow cannot be currently closed like ConflatedBroadcastChannel and can never represent a failure. This feature might be added in the future if enough compelling use-cases are found.

**Comment by NotWoods** [comment]
Those first two properties highlighted were the only reasons to keep `LiveData` around in AC and Fenix. With this addition we can pull it out.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793191

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
