### ISSUE TITLE
AddonCollectionProvider should use .current_version.files[0].created instead of .last_updated

### ISSUE THREAD

**Issue by Rob--W** [mozilla-mobile/android-components#6935]
See https://github.com/mozilla/addons-server/issues/14209 and https://github.com/mozilla-mobile/fenix/issues/10489 for more context

The update field should reflect the date of the add-on file update, not of an arbitrary other last modification date:

https://github.com/mozilla-mobile/android-components/blob/6ae25079c9e5386353ddcf6b0810a34be9dd2649/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AddonCollectionProvider.kt#L176

To fix that, replace `last_updated` with `current_version.files[0].created` from the response (
https://addons.mozilla.org/api/v4/accounts/account/mozilla/collections/7e8d6dc651b54ab385fb8791bf9dac/addons/?lang=en-US )

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5925)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796311

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
