### ISSUE TITLE
[Bug] Rotating screen causes crash in samples-firefox-accounts

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#6965]
On activity recreation `RustLogAdapter.enable` is called and throws `LogAdapterCannotEnable` error, as the adapter is already enabled.
Temporary fix in testing https://github.com/mozilla-mobile/android-components/pull/6939 was to call disable, but a better approach would be to catch the exception (or investigate if is it absolutely necessary for a-s to throw it? )

**Comment by drigio** [comment]
Similar issue at #4859.

**Comment by kbrosnan** [comment]
This looks like a duplicate of #4859
