### ISSUE TITLE
Fennec migration: Update the info on addons.mozilla.org for the available addons

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#6967]
## Preconditions:
On Fennec add some add-ons that are also available on Fenix. (uBlock Origin, HTTP Everywhere, Dark Reader, NoScript Security Suite).
Have addons.mozilla.org tabs open with the added add-ons.
## Steps to reproduce
1. Replace Fennec with Fenix;
2. Launch Fenix and go to the addons.mozilla.org tabs;
3. Observe the information for the add-ons that are available on Fenix;
### Expected behavior
The migrated add-ons have the information that are not available on Firefox for Android.
### Actual behavior
The migrated add-ons have the information that are available on Firefox for Android and they can be managed at the Add-ons section.
### Notes
![20200513_153307](https://user-images.githubusercontent.com/48799384/81812771-42816800-952f-11ea-9223-ca125f1ec45b.gif)
### Device information

* Android device: all
* Fenix version: all

**Comment by Amejia481** [comment]
The add-ons website is out of our control this bug is going to be addressed here https://github.com/mozilla/addons-frontend/issues/9360
