### ISSUE TITLE
SessionUseCases may be unnecessarily complicated

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#697]
Currently:
```kotlin
class SessionUseCases(
    sessionManager: SessionManager
) {

    class LoadUrlUseCase internal constructor(
        private val sessionManager: SessionManager
    ) {
        /**
         * Loads the provided URL using the provided session (or the currently
         * selected session if none is provided).
         *
         * @param url url to load.
         * @param session the session for which the URL should be loaded.
         */
        fun invoke(url: String, session: Session = sessionManager.selectedSessionOrThrow) {
            sessionManager.getOrCreateEngineSession(session).loadUrl(url)
        }
    }

    // ...

    val loadUrl: LoadUrlUseCase by lazy { LoadUrlUseCase(sessionManager) }
```

But why not this?
```kotlin
class SessionUseCases(
    private val sessionManager: SessionManager
) {
    fun loadUrl(url: String, ...) { ... }
}
```

**Comment by csadilek** [comment]
IIRC, We wanted to be able to pass both individual use cases and groups of use cases to components. So components can depend only on the use cases they need and don't get access to use cases they shouldn't know about. A single use case type wouldn't satisfy that, but, of course, we could alternatively introduce more types or interfaces. What I like about the current solution is that use cases are easily discoverable when implementing a new component...

**Comment by pocmo** [comment]
Looking through old issues and closing them if they are not applicable anymore. I think we can close this one. Eventually we may rethink our use cases, but right now that's not actionable.
