### ISSUE TITLE
[Bug]Horizontals scrolls should not trigger a page scroll

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#6986]
## Steps to reproduce
1. Navigate to https://www.cnn.com/2019/04/09/tech/locked-ipad-boy-trnd/index.html
2. Swipe horizontally through the image slider.

### Expected behavior
No scrolling while swiping through the image slider.

### Actual behavior
Seems to be scrolling while swiping through the image slider.
❗ Happens while using both the Top and Bottom dynamic toolbar.

### Device information
* Android device: 
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Nightly Build 200515 from 5/15

### Notes
Based on my findings from [#1506](https://github.com/mozilla-mobile/fenix/issues/1506)

► Video
![20200515-095345](https://user-images.githubusercontent.com/51314259/82024381-61e7d480-9698-11ea-8c8b-1dae763fb8d7.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5971)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795377

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
