### ISSUE TITLE
Crash reporter: Retry uploading to crash reporting service

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7006]
We still do not retry uploading crash reports. Now that we start to have a database for crashes, we could consider using it as a queue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-5988)

**Comment by pocmo** [comment]
Actually, I think sentry will handle this on its own. So we may only need to add this to the socorro service implementation.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792909

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
