### ISSUE TITLE
Desktop mode not exposed in browser-session

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#701]
c854509a704af24738c3097611547793a25193ee introduced desktop mode. However there's no flag on `Session` for the application to observe.

* In `Session` we want to add a property for desktop mode.
* In `EngineObserver` we want to implement `onDesktopModeEnabled` and update the field in `Session`

**Comment by jonalmeida** [comment]
I'll take this because I also wanted to change `EngineSession#setDesktopMode` to `EngineSession#desktopMode` to be consistent.. and I also forgot to add desktop mode to browser-session.  :disappointed:
