### ISSUE TITLE
Add share option to crash list

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7012]
Often you may not want to read the crash report on a phone on crash-stats/sentry, but instead share/copy all information to post it somewhere or open an issue. This is especially annoying with Sentry because it will always redirect you to a login page (if you are not logged in already) and that makes it impossible to copy the link for anyone that does not have Sentry access. So let's add a share option! :)

**Comment by st3fan** [comment]
Can this be a standard Android share sheet so that you can share to anything you have on your device, including GMail, Slack, etc.

**Comment by pocmo** [comment]
Yeah, this is the plan! Not gonna write my own here 😅
