### ISSUE TITLE
Remove setActive calls in engine-gecko-*

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#703]
Just saw this referencing a slack conversation:
https://github.com/mozilla-mobile/focus-android/pull/3314

We just introduced the setActive calls in:
https://github.com/mozilla-mobile/android-components/pull/694

**Comment by csadilek** [comment]
@snorp can you confirm we shouldn't be calling this (neither on start/stop or pause/resume)? 

What's the best way of tracking GeckoView API changes? I want to subscribe :).

**Comment by pocmo** [comment]
> What's the best way of tracking GeckoView API changes? I want to subscribe :).

+1 :)
