### ISSUE TITLE
Gradle configuration avoidance API 

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7034]
It seems like a lot of our gradle tasks are "eager" - see [Task Configuration Avoidance docs](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) which is slowing down the configuration phase of our builds. This issue is to track switching to making our tasks "lazy", allowing tasks that aren't necessary during a build (like publication tasks) to be omitted.

Here's a build scan, running `./gradlew help --scan` - https://scans.gradle.com/s/dfvk5nfbjqax6/performance/configuration:
```
Total tasks 24074  
Created immediately 410 --- bad!
Created during configuration 23519 --- very, very bad!
Created during task execution 1  
Created during task graph calculation 14   --- should be close to "total tasks"
Not created 130  
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6012)

**Comment by csadilek** [comment]
This landed back in https://github.com/mozilla-mobile/android-components/pull/7036.
