### ISSUE TITLE
Update android gradle plugin to 4.0.0

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7035]
Release notes: https://developer.android.com/studio/releases/gradle-plugin#3-6-0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6013)

**Comment by pocmo** [comment]
Plugin <-> Gradle compatibility: https://developer.android.com/studio/releases/gradle-plugin#updating-gradle

Also looked at this briefly yesterday and saw that there's already RC 1 of version 4.0.0 of the plugin. So maybe it's worth waiting a bit? :)

**Comment by pocmo** [comment]
4.0.0 was just released and is compatible with 6.1.1. I'll take a quick look if we can update easily.

**Comment by mcarare** [comment]
This was completed long ago.
