### ISSUE TITLE
RecentAppsDao isn't async

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#7046]
We should switch it to use suspend/flow

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6028)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794881

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
