### ISSUE TITLE
Move all download state to browser store

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#7050]
We currently keep additional application state for downloads in the `DownloadService` (see `downloadJobs`) and `DownloadManager` (see `queuedDownloads`).

Having all this state in the store will make it easier to implement additional download UI in the future. It also solves the problem described in https://github.com/mozilla-mobile/android-components/issues/5217 where we have to pass the download object (and the full URL) to the download intent which may be too large in case of data URIs. If the service has access to the store it can simply read the state from there.

**Comment by csadilek** [comment]
This is a bigger refactoring and we may need to be broken down more once work starts.

**Comment by csadilek** [comment]
First part here is done in: https://github.com/mozilla-mobile/android-components/issues/7103

**Comment by codrut-topliceanu** [comment]
Changes made for this have affected the fix for https://github.com/mozilla-mobile/fenix/issues/9044 . I'll take a look on the Fenix side and see how I can resolve those conflicts.

**Comment by Amejia481** [comment]
> Changes made for this have affected the fix for [mozilla-mobile/fenix#9044](https://github.com/mozilla-mobile/fenix/issues/9044) . I'll take a look on the Fenix side and see how I can resolve those conflicts.
> 
> Edit: Or should I wait for this to be finished?

I think you could continue on Fenix, Is there something in particular that it's blocking you?

**Comment by codrut-topliceanu** [comment]
@Amejia481 Yeah, you're right, if the `DownloadState` move has been completed, I should be able to make the needed changes in https://github.com/mozilla-mobile/fenix/issues/11371 without any conflicts from the proposed changes in https://github.com/mozilla-mobile/android-components/issues/7227 .

**Comment by marekchen** [comment]
I want to add a Download Manager Center Activity in my browser powered by android-components.
I want show all download tasks' progress in my activity.But now DownloadState in BrowserState's queuedDownloads don't include download progress.
So I can wait this change to be done.Then I can get download progress from BrowserState?
English is not my mother  tongue, if you have any doubt about what I say,please comment me. Thank you very much.

**Comment by Amejia481** [comment]
> I want to add a Download Manager Center Activity in my browser powered by android-components.
> I want show all download tasks' progress in my activity.But now DownloadState in BrowserState's queuedDownloads don't include download progress.
> So I can wait this change to be done.Then I can get download progress from BrowserState?
> English is not my mother tongue, if you have any doubt about what I say,please comment me. Thank you very much.

We are going to work on a similar feature on Fenix https://github.com/mozilla-mobile/fenix/issues/349
This looks like a great starting issue.

cc @kglazko

**Comment by Amejia481** [comment]
I filed https://github.com/mozilla-mobile/android-components/issues/7673 for it

**Comment by Amejia481** [comment]
> I want to add a Download Manager Center Activity in my browser powered by android-components.
> I want show all download tasks' progress in my activity.But now DownloadState in BrowserState's queuedDownloads don't include download progress.
> So I can wait this change to be done.Then I can get download progress from BrowserState?
> English is not my mother tongue, if you have any doubt about what I say,please comment me. Thank you very much.

@marcinwiacek now https://github.com/mozilla-mobile/android-components/pull/7698 landed this should include the values that you need. We are going to work on https://github.com/mozilla-mobile/android-components/issues/7761 next as we want downloads to be on memory in the store even if they are completed, after that we want to work on https://github.com/mozilla-mobile/android-components/issues/7762 for this data to be persisted on disk.

**Comment by jonalmeida** [comment]
We have downloads in the browser store now, so I'm going to close this. 🙂
