### ISSUE TITLE
PWA ManifestDatabase.instance memory leak

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7051]
From LeakCanary:

┬───
│ GC Root: Global variable in native code
│
├─ dalvik.system.PathClassLoader instance
│    Leaking: NO (ManifestDatabase↓ is not leaking and A ClassLoader is never leaking)
│    ↓ PathClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│    Leaking: NO (ManifestDatabase↓ is not leaking)
│    ↓ Object[].[2655]
├─ mozilla.components.feature.pwa.db.ManifestDatabase class
│    Leaking: NO (a class is never leaking)
│    ↓ static ManifestDatabase.instance
│                              ~~~~~~~~
├─ mozilla.components.feature.pwa.db.ManifestDatabase_Impl instance
│    Leaking: UNKNOWN
│    ↓ ManifestDatabase_Impl.mOpenHelper
│                            ~~~~~~~~~~~
├─ androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper instance
│    Leaking: UNKNOWN
│    ↓ FrameworkSQLiteOpenHelper.mDelegate
│                                ~~~~~~~~~
├─ androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper instance
│    Leaking: UNKNOWN
│    ↓ FrameworkSQLiteOpenHelper$OpenHelper.mContext
│                                           ~~~~~~~~
╰→ mozilla.components.feature.pwa.WebAppLauncherActivity instance
​     Leaking: YES (ObjectWatcher was watching this because mozilla.components.feature.pwa.WebAppLauncherActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     key = eb395b4f-aa99-49f0-b4a8-8187bc8be4cd
​     watchDurationMillis = 318041
​     retainedDurationMillis = 313040

**Comment by NotWoods** [comment]
We have lots of Room databases held as singletons like this, does it need to be adjusted?
