### ISSUE TITLE
Crash in [@ [INFO] MalformedMessage(message=parsing encrypted message failed: at mozilla.components.lib.push.firebase.AbstractFirebasePushService.onMessageReceived(AbstractFirebasePushService.kt:14)]

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/android-components#7063]
Originally filed under GeckoView as https://bugzilla.mozilla.org/show_bug.cgi?id=1639891 but this is not a GeckoView issue. Refiling here, although as it is an `[INFO]` I'm not sure if that is the right solution....

**Comment by jonalmeida** [comment]
Copying my comment from the Bugzilla here on why we can close this:

> 
> I can confirm, this isn't a bug but a info (as noted by the `[INFO]` in the trace) which seems to show up as a crash in Socorro. After May 13th we no longer even send this. 
> 
> After speaking with Roger, it seems the reason this is marked as a top crash is because we're discarding crash info for anything longer than 2 weeks ago, so the "crash" rate of 50+% in Fenix 5.0.0 is misleading.
