### ISSUE TITLE
Synced Tab suggestions are overwritten by history suggestions

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7084]
It seems like we're not seeing Synced Tab suggestions when we type a term in the awesome bar verbatim. Instead we see the history suggestion for it.

## Steps to reproduce
 1. Ensure tabs have been synced.
 1. Enter a site url from an open tab on desktop verbatim.

## Expected
 - To see an entry for a synced tab on top.

## Actual
 - You see entries of the history item instead.

If you turn off history syncing and then retry, this issue is no longer seen.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6058)

**Comment by liuche** [comment]
I remember @jonalmeida said he did'nt have time to continue this.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794232

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
