### ISSUE TITLE
Support for custom image notification icon on menu button

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7086]
We have support for a notification icon on the menu button as seen here:
<img width="248" alt="Screen Shot 2020-05-23 at 4 23 16 AM" src="https://user-images.githubusercontent.com/1370580/82725751-2c04aa80-9cad-11ea-814b-d05a7525858f.png">

In Focus, we need support for adding a custom icon. This can be used for displaying when Tracking Protection is disabled:
<img width="293" alt="Screen Shot 2020-05-23 at 3 58 16 AM" src="https://user-images.githubusercontent.com/1370580/82725764-49d20f80-9cad-11ea-8157-ef5f48502797.png">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6059)

**Comment by pocmo** [comment]
I wonder if instead we should just show the TP shield indicator in the toolbar like Fenix does.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793143

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
