### ISSUE TITLE
ToolbarPresenter should use findTabOrCustomTabOrSelectedTab

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7087]
In Focus, we want to observe a particular session ID first before checking if it's a custom/selected tab.

We should fix our presenter to replace `BrowserState.findCustomTabOrSelectedTab` usages with `BrowserState.findTabOrCustomTabOrSelectedTab`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6060)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796291

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
