### ISSUE TITLE
Add tests for crash list UI

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7095]
We added some new UI for displaying the list of crashes. But we do not have any tests for that yet. Let's add some!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6065)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792908

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
