### ISSUE TITLE
Move active web app manifest to BrowserStore

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#7115]
We're currently seeing some crashes with downloads due to large parcelable objects in intents. Right now, the web app manifest for an opened PWA is also stored inside intents and may create the same problems.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6090)

**Comment by jonalmeida** [comment]
This was done as part of the BrowserStore migration.
