### ISSUE TITLE
context.filesDir violates strict mode in TabCollectionStorage

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#7116]
We may want to make it be lazily accessed or accessed on an IO thread.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6091)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796252

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
