### ISSUE TITLE
Telemetry: Expose list of active experiments in event pings

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#713]
Currently we expose the list of active experiments in the "core ping" only. To make it easier to analyze things on the server side we should add the same list to the "focus event ping".

And while we are doing that we can do it for the "mobile event ping" too. (History: We created "focus event ping" first. Then later we launched more apps and created "mobile event ping" which is a copy of "focus event ping". Focus is still using "focus event ping". A client and server side migration would be needed to switch Focus to "mobile event ping".)

* Focus Event Ping Schema: https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/focus-event/focus-event.1.schema.json#L66
* Mobile Event Ping Schema: https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/mobile-event/mobile-event.1.schema.json#L66

We added the experiments list to `TelemetryCorePingBuilder` here:
* https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryCorePingBuilder.java#L57
* Commit: https://github.com/mozilla-mobile/android-components/commit/0a22a10b5ee7aa081996992aa1567e9abca17105

We'd need to add it to `TelemetryEventPingBuilder` (focus event) and `TelemetryMobileEventPingBuilder`:
* https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryEventPingBuilder.java
* https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryMobileEventPingBuilder.java

An app using the library passes the list of active experiments to `recordActiveExperiments()`:
https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/src/main/java/org/mozilla/telemetry/Telemetry.java#L194-L213

We'd need to extend `recordActiveExperiments()` to add it to `TelemetryEventPingBuilder` or `TelemetryMobileEventPingBuilder` too if they are registered.

And finally: There are a bunch of tests for the telemetry library. Let's make sure they still pass and let's add some new ones for this functionality.

**Comment by colintheshots** [comment]
Maybe I have time. It might not be soon. I'm getting out the 7.0 release and then heading over to Europe for awhile for vacation and KotlinConf, followed by the work week.

**Comment by pocmo** [comment]
The `service-telemetry` is deprecated.
