### ISSUE TITLE
Stop delegating uncaught exceptions to Android system

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#7131]
Current uncaught exceptions are delegated to Android after the lib-crash handled them.  This reports the crash to Google as well.  However, in some cases, the user gets confused by two dialogs. (one from us and one from Android)

Stop delegating uncaught exceptions to Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6111)

**Comment by rocketsroger** [comment]
Related to https://github.com/mozilla-mobile/fenix/issues/1407

**Comment by csadilek** [comment]
@rocketsroger we backed this out today due to #7829.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792907

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
