### ISSUE TITLE
Fix Gecko Login prompt API breaking changes

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7132]
GeckoView nightly introduced some [new api changes](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/doc-files/CHANGELOG#v78), we need to adapt our code for it.

> ⚠️ Refactored LoginStorage to the Autocomplete API to support login form autocomplete delegation. Refactored ‘LoginStorage.Delegate’ to ‘Autocomplete.LoginStorageDelegate’. Refactored GeckoSession.PromptDelegate.onLoginStoragePrompt to GeckoSession.PromptDelegate.onLoginSave. Added GeckoSession.PromptDelegate.onLoginSelect. (bug 1618058)

**Comment by jonalmeida** [comment]
Closing as this was fixed with #7133.
