### ISSUE TITLE
Tweak the desired sizes of the thumbnail to make them less blurry

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#7138]
I noticed the icons are noticeably blurry when comparing from the cache to the ones fresh in-memory. Maybe we need to change the scaling value?

<img width="523" alt="Screen Shot 2020-05-27 at 1 30 10 PM" src="https://user-images.githubusercontent.com/1370580/83053134-411b6980-a01e-11ea-90ee-7012895de004.png">

_Originally posted by @jonalmeida in https://github.com/mozilla-mobile/android-components/pull/7127_

**Comment by jonalmeida** [comment]
This should include changing this value to something that uses a dp value as a fallback.
