### ISSUE TITLE
Consider moving GeckoViewPrompt into browser-engine-gecko-* modules

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#714]
Focus uses a `GeckoViewPrompt` class to implement `GeckoSession.PromptDelegate`. This class is quite generic and was copied over from mozilla-central:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java

We may want to move this functionality into `browser-engine-gecko-*`. Currently `GeckoViewPrompt` depends on an Activity ... this makes it hard to just drop it in.

This issue may require a lot of work - so let's split it into smaller issues once we know what we actually want.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6121)

**Comment by csadilek** [comment]
See `feature-prompts` for a now shared implementation between Fenix and Focus.
