### ISSUE TITLE
Glean telemetry for CI

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7146]
It'd be very nice to monitor performance of our CI via telemetry; especially helpful to see impact of changes such as https://github.com/mozilla-mobile/android-components/pull/7118.

This issue is to add basic telemetry to our CI builds. We can start this off by tracking total duration of all our tasks, and perhaps a few percentiles points to track outliers.

We can use something like a `complete-pr` task, or introduce a new task, and query the taskcluster API to get details of runtime of our tasks.

**Comment by pocmo** [comment]
This is btw., like hosted caches, another Gradle Enterprise feature :)
https://gradle.com/build-scans/

**Comment by grigoryk** [comment]
Turns out, we already track most of what I care about with jobs telemetry via treeherder databases, and the data is already available in redash. This is probably "good enough" for now. See a [fenix status CI dashboard](https://sql.telemetry.mozilla.org/dashboard/fenix-ci-status?p_w57980_time_period=3&p_w57980_with_tasks=OR%20job_type.symbol%20%3D%20%27gradle-dependencies%27%20OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57985_time_period=3&p_w57985_with_ui_tests=OR%20job_type.symbol%20%3D%20%27gradle-dependencies%27%20OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57988_time_period=3&p_w57988_with_tasks=OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57990_time_period=3&p_w57990_with_tasks=OR%20job_type.symbol%20%3D%20%27gradle-dependencies%27%20OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w57991_time_period=3&p_w57991_with_tasks=OR%20job_type.symbol%20%3D%20%27ui-test-x86%27&p_w58003_task=T&p_w58003_time_period=3&p_w58004_task=ui-test-x86&p_w58004_time_period=3&p_w58006_task=gradle-dependencies&p_w58006_time_period=3&p_w58007_task=Bat&p_w58007_time_period=3&refresh=43200) as an example of these queries.

**Comment by pocmo** [comment]
@grigoryk Should we close this issue for now?

**Comment by grigoryk** [comment]
Yeah, I think so!
