### ISSUE TITLE
Include more device data when sharing crash report?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7148]
We added an option to share crash reports and this will include the stacktrace and the links to the reports on Socorro and Sentry.

Seeing this crash report from Jonathan, https://github.com/mozilla-mobile/reference-browser/issues/1205, I was wondering whether we should include more device information.

The issue contains
>  Android device: Pixel 4, Android 10
> Reference Browser version: 1.0.2022 (Build #21480608 GV: 78.0a1-20200525093440)
>  📦: 43.0.20200526130035, 7e7e1ea5a
>  🚢: 0.59.0

Most of that we should be able to collect and include.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6131)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792906

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
