### ISSUE TITLE
Retry git commands in automation

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7149]
Just saw a PR merge fail because in one task the git checkout failed. Maybe it's worth adding some retry mechanism for the git commands. In that case it worked in all other tasks. So maybe just trying again in the same task would have helped.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6132)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795375

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
