### ISSUE TITLE
SimpleDownloadDialogFragment memory leak

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#7180]
I've seen this once but wasn't able to reproduce. 

<img width="402" alt="Screen Shot 2020-05-29 at 11 16 03 AM" src="https://user-images.githubusercontent.com/472523/83275904-d2651a00-a19d-11ea-8e83-a6c13f9604cb.png">

**Comment by cadeyrn** [comment]
> I've seen this once but wasn't able to reproduce.

I tried it five times and was able to reproduce it five times. I reproduced it with downloading the .apk file from https://github.com/mozilla-tw/FirefoxLite/releases/tag/v2.5.1.
