### ISSUE TITLE
Move initialized logic in AutoPushFeature to native wrapper.

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7184]
We wrap all our API calls in `connection.ifInitialized` blocks before we execute them, but we can do better by hiding this in the native wrappers before the actual call is made a reduce the probability of reaching a race condition if in a bad state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6173)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796428

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
