### ISSUE TITLE
Delete thumbnails when a session is removed

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7185]
If we continue to follow the direction of using the session ID for identifying tabs, we should also make sure we remove the thumbnails for the tab when the tab is removed.

We can do this using the same `ThumbnailMiddleware` we added for getting new thumbnails.

**Comment by gabrielluong** [comment]
We want to support this when we have a solution for https://github.com/mozilla-mobile/android-components/issues/3265.
