### ISSUE TITLE
Give option to receive latest event with the state in consumeFrom

### ISSUE THREAD

**Issue by boek** [mozilla-mobile/android-components#7190]
When I'm consuming state changes it would also be cool to know the event that caused the state to change

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6181)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793190

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by boek** [comment]
@csadilek 👀
