### ISSUE TITLE
Telemetry: Report all experiments

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#720]
The data team wants to see all experiments in the pings.

There's an `experiments` object in the ping:
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/telemetry/focus-event/focus-event.1.schema.json#L66 

I just do not know how it should look like. :)

**Comment by fbertsch** [comment]
Should just be a Map[String, String], with keys being `experiment_id` and values being `experiment_branch`. E.g.
```
{
  "use-gecko": "true",
  "a-a": "branch-1"
}
```

**Comment by pocmo** [comment]
@fbertsch Fretboard doesn't support multiple branches per experiment. A client is either part of an experiment or not. In Fennec we modeled multi-branch experiments by having one experiment per branch (e.g. experiment-a 0-25, experiment b 25-50, experiment c 50-75, control group 75-100). Would it make sense to always use true/false here?

So for [the current configuration](https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/focus-experiments/records) this may look like: 

```JavaScript
{
  "use-gecko": "true",
  "use-homescreen-tips": "false",
  "use-gecko-nightly": "false",
  "use-homescreen-tips-nightly": "false"
}
```

**Comment by pocmo** [comment]
That's a bigger architectural change that we'd need to file separately and estimate - this may result in / require a new experiment configuration format.

**Comment by fbertsch** [comment]
Let's hold off until we have a need for it. @mmccorks are you aware of any possible experiments that may require more than a branch and control?

**Comment by pocmo** [comment]
@fbertsch Given that Focus wants to move ahead with the A/A test. What do you think we should do here?

**Comment by fbertsch** [comment]
@pocmo I think I would prefer to see `control` and `branch`, but only if it's easy.

**Comment by pocmo** [comment]
@fbertsch Yep, that should work! :)
