### ISSUE TITLE
Cannot substitute GeckoView with API change

### ISSUE THREAD

**Issue by agi90** [mozilla-mobile/android-components#7204]
Hello! I've been using `dependencySubstitutions` successfully and it's great. One problem we've found though is that it does not let you use a GeckoView API that's defined locally only, is this a limitation of the current system? could we work around it somehow? This is a very common case for us as GeckoView engineers.

**Comment by Amejia481** [comment]
cc @grigoryk

**Comment by grigoryk** [comment]
@agi90 thanks for filing!

I'll play around with GV locally. My first thought is that we can probably re-use the autoPublication approach that we have now for a-c and a-s. With autoPublications enabled, you can use locally defined APIs. Unless GV case is somehow meaningfully different, it should probably work there as well.
