### ISSUE TITLE
Investigate if BrowserStore can handle undo at index

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7205]
Based on Fenix's tabs tray implementation, we want to make sure we have all the requirements to support this feature.

**Comment by pocmo** [comment]
Same as #6921 (and same concern).

**Comment by jonalmeida** [comment]
I filed this separately for BrowserStore to check if we can add a tab to specific position. We need this so that the undo tab to stop the tab being added to the end of the list. I'd like to eventually close #6921 as won't fix once I can confirm Fenix has the API to do this.

I can see `AddTabAction` let's us add re-add a tab to it, but we can't choose it's position.

**Comment by pocmo** [comment]
We cannot change the position in `BrowserStore` only while we keep both (`SessionManager`) in sync because that would break the sync in certain situations.

Once that is no longer the case we can implement undo directly in AC (#3265) and would not need to expose those low level APIs.

**Comment by jonalmeida** [comment]
That makes sense, thanks for explaining! I'm going to close this then as a duplicate of #3265.
