### ISSUE TITLE
RegExp, lookbehind assertions

### ISSUE THREAD

**Issue by leela52452** [mozilla-mobile/android-components#7208]
i have been [adviced](https://github.com/mozilla-mobile/fenix/issues/10882) to report here.

all i know `Notably, Firefox currently does not support lookbehinds, and therefore is not able to perform as many typo fixes as other browsers.` given at [jwb](https://en.m.wikipedia.org/wiki/User:Joeytje50/JWB). see also [some browsers not supporting Regex lookbehinds](https://caniuse.com/#search=lookbehind)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6199)

**Comment by zivian** [comment]
@st3fan @data-sync-user 
[Lookbehind in JS regular expressions](https://caniuse.com/?search=lookbehind) shows as available from **version 87**

**Comment by csadilek** [comment]
This should be working now, please re-open if not.
