### ISSUE TITLE
Remove suspend modifier on IntentProcessor

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7217]
We should remove the `suspend` keyword modifier on the `process` method when we have https://github.com/mozilla-mobile/android-components/issues/7214 fixed.

We've had issues in the passed with coroutine's needing to yield the main thread, that cause a perf loss when processing intents.

https://github.com/mozilla-mobile/android-components/blob/master/components/feature/intent/src/main/java/mozilla/components/feature/intent/processing/IntentProcessor.kt#L19

Reference Fenix issue: https://github.com/mozilla-mobile/fenix/issues/7818

**Comment by jonalmeida** [comment]
cc: @NotWoods

**Comment by NotWoods** [comment]
It should be OK to remove the modifier before the service lands. We can always show a toolbar until verification completes.
