### ISSUE TITLE
Speculative GeckoSession cannot be configured

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7223]
At first I thought I saw the following issue in Focus for Android after integrating the engine, but this is not the case since Focus doesn't use any code that creates a speculative `GeckoSession`. However it still looks like this could be a problem. I am not sure whether this is only theoretically possible or whether this can actually happen in Fenix right now.

Our Engine allows it to create a speculative `EngineSession` that will be used later when`createSession()` is called:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt#L177

The `SettingsUseCases` class is a helper to apply a settings change to the engine and all its engine sessions. For example `UpdateTrackingProtectionUseCase` updates the tracking protection policy for all engine sessions. It does so by looping over all available engine sessions and applying the new policy:
* https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/src/main/java/mozilla/components/feature/session/SettingsUseCases.kt#L75-L77
* https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/src/main/java/mozilla/components/feature/session/SettingsUseCases.kt#L42-L46

`UpdateSettingUseCase.forEachSession` does not update the speculative `EngineSession`. So if the settings change after the speculative `EngineSession` then the change will not apply to that session since `createSession()` will not create an engine session with the new settings but instead return the speculative engine session with the old settings.

Not sure if other code is affected that tries to do things with "all engine sessions".

What are our options to fix that? Should we allow to access the speculative engine session so that the use case can change it? Should we add a way to "drop" or "recreate" the speculative session?

**Comment by csadilek** [comment]
Ultimately, we should move the speculative session to the store, once the engine has access to it. Then all use cases have access to the session and can remove it or cause "recreation". In the short-term, let's verify if we need to fix this for Fenix. If so, adding a method to engine seems like the right solution. Will take a look.
