### ISSUE TITLE
Check subscription verification immediately after getting a new push token

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7237]
When we get a push token, we wait to check our subscriptions when we next re-open the app (with `initialize`) and we haven't done a check recently (~24 hours). We could consider doing this check immediately after updating the token in the native layer in `onNewToken`.

I'm a little unsure if we should do this now. If we can verify the system works as expected after https://github.com/mozilla-mobile/android-components/issues/7143 is fixed, we can consider doing this after the Fenix release.

We do however have our [`VerificationDelegate`](https://searchfox.org/mozilla-mobile/rev/f1321a39b6154079614c894c01df30cba1fac16f/android-components/components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt#224) to avoid us DDOS-ing our push servers if something goes wrong with our FxA servers, so there is safety there.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6222)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796427

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
