### ISSUE TITLE
Intermittent loadWebsiteTest java.lang.RuntimeException: android.os.DeadObjectException

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#7250]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=305070679&repo=android-components
Logcat: 
https://storage.cloud.google.com/android-components_test_artifacts/2020-06-04_15-51-35.220000_AzOz/Nexus6-21-en-portrait/logcat

06-04 08:56:22.029: E/BufferQueueProducer(1342): [com.google.android.apps.mtaas.backdrop/com.google.android.apps.mtaas.backdrop.BackdropActivity] dequeueBuffer: BufferQueue has been abandoned
06-04 08:56:22.029: E/BufferQueueProducer(1342): [com.google.android.apps.mtaas.backdrop/com.google.android.apps.mtaas.backdrop.BackdropActivity] query: BufferQueue has been abandoned
06-04 08:56:22.029: E/BufferQueueProducer(1342): [com.google.android.apps.mtaas.backdrop/com.google.android.apps.mtaas.backdrop.BackdropActivity] query: BufferQueue has been abandoned
06-04 08:56:22.029: E/libGLES_CM_swiftshader(5819): badness: err createDepthStencil external/swiftshader/src/OpenGL/libGLES_CM/Texture.cpp:825 (Invalid parameters: -1237320780x-1425007692)
06-04 08:56:22.029: E/swiftshader(5819): AndroidEnterDebugger
06-04 08:56:22.029: E/libEGL_swiftshader(5819): badness: err initialize external/swiftshader/src/OpenGL/libEGL/Surface.cpp:98 (Could not create depth/stencil buffer for surface)
06-04 08:56:22.029: E/swiftshader(5819): AndroidEnterDebugger
06-04 08:56:22.089: D/AndroidRuntime(2886): Shutting down VM
06-04 08:56:22.089: D/AndroidRuntime(2886): --------- beginning of crash
06-04 08:56:22.092: E/AndroidRuntime(2886): FATAL EXCEPTION: main
06-04 08:56:22.092: E/AndroidRuntime(2886): Process: com.android.phone, PID: 2886
06-04 08:56:22.092: E/AndroidRuntime(2886): java.lang.RuntimeException: android.os.DeadObjectException
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.net.TrafficStats.getMobileIfaces(TrafficStats.java:624)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.net.TrafficStats.getMobileTcpTxPackets(TrafficStats.java:368)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at com.android.internal.telephony.dataconnection.DcTrackerBase$TxRxSum.updateTxRxSum(DcTrackerBase.java:472)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at com.android.internal.telephony.dataconnection.DcTrackerBase.updateDataActivity(DcTrackerBase.java:1430)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at com.android.internal.telephony.dataconnection.DcTrackerBase$3.run(DcTrackerBase.java:374)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.os.Handler.handleCallback(Handler.java:739)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.os.Looper.loop(Looper.java:135)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at java.lang.reflect.Method.invoke(Native Method)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
06-04 08:56:22.092: E/AndroidRuntime(2886): Caused by: android.os.DeadObjectException
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.os.BinderProxy.transactNative(Native Method)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.os.BinderProxy.transact(Binder.java:496)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.net.INetworkStatsService$Stub$Proxy.getMobileIfaces(INetworkStatsService.java:232)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	at android.net.TrafficStats.getMobileIfaces(TrafficStats.java:622)
06-04 08:56:22.092: E/AndroidRuntime(2886): 	... 12 more
06-04 08:56:22.100: E/AndroidRuntime(2886): Error reporting crash
06-04 08:56:22.100: E/AndroidRuntime(2886): android.os.DeadObjectException
06-04 08:56:22.100: E/AndroidRuntime(2886): 	at android.os.BinderProxy.transactNative(Native Method)
06-04 08:56:22.100: E/AndroidRuntime(2886): 	at android.os.BinderProxy.transact(Binder.java:496)
06-04 08:56:22.100: E/AndroidRuntime(2886): 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4100)
06-04 08:56:22.100: E/AndroidRuntime(2886): 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:89)
06-04 08:56:22.100: E/AndroidRuntime(2886): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
06-04 08:56:22.100: E/AndroidRuntime(2886): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
06-04 08:56:22.100: I/Process(2886): Sending signal. PID: 2886 SIG: 9

**Comment by jonalmeida** [comment]
I'm going to close this since I don't think we see this failure any more. Please re-open if I'm wrong.
