### ISSUE TITLE
Sync ping telemetry for the Synced Tabs engine

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7254]
Seems like adding telemetry for the tabs engine was omitted during sync tabs work.

cc @eoger @jonalmeida

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6240)

**Comment by grigoryk** [comment]
You'd need to expand SyncTelemetry.kt: https://github.com/mozilla-mobile/android-components/blob/master/components/support/sync-telemetry/src/main/java/mozilla/components/support/sync/telemetry/SyncTelemetry.kt (and adjust its tests for the new data).

**Comment by grigoryk** [comment]
Also, new metrics will need to be defined in https://github.com/mozilla-mobile/android-components/blob/master/components/support/sync-telemetry/metrics.yaml - this will require requesting a data review.

**Comment by jonalmeida** [comment]
Thanks for catching!

**Comment by jonalmeida** [comment]
I see the synced tabs telemetry there already. Closing as fixed.
