### ISSUE TITLE
Consider Logins UI for "Add a username" case

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#7256]
Currently, when we find a "matching" login with a blank username we tell the user we can "update" it via the login dialog UI, but on desktop, they distinguish between "update" and "add a username". We should consider doing the same and if not, get confirmation from UX that this is correct behavior for mobile. 
cc @AmyYLee

**Comment by betsymi** [comment]
Just realized I made a mistake with casing, it should be Don't save, Don't update, Don't update. I believe those should also be hyperlinked text, not buttons.

**Comment by ekager** [comment]
Updated!
![Screenshot_20200604-210825](https://user-images.githubusercontent.com/25442310/83825549-7d8a3d80-a68e-11ea-9262-7d6750ff26c9.png)
![Screenshot_20200604-210718](https://user-images.githubusercontent.com/25442310/83825550-7e22d400-a68e-11ea-8045-1c9541458222.png)
![Screenshot_20200604-210708](https://user-images.githubusercontent.com/25442310/83825552-7e22d400-a68e-11ea-9e42-3153a9427a60.png)
