### ISSUE TITLE
Make noticiable that operations on SitePermissionsStorage must be performed on a background thread

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7265]

**Comment by jonalmeida** [comment]
Maybe adding the `@WorkerThread` annotation could be a good start?

**Comment by Amejia481** [comment]
Agree!

**Comment by Shubhamurkade** [comment]
@Amejia481 can I take this up?

**Comment by Amejia481** [comment]
Sure :)

**Comment by Shubhamurkade** [comment]
@Amejia481 I tried adding the '@WorkerThread' annotation to SitePermissionsStorage class but I get this error during compilation - 'error: incompatible types: NonExistentClass cannot be converted to Annotation'. Could you please give me some pointers on how to fix this?

**Comment by RotBolt** [comment]
Can I work on this? @Amejia481

**Comment by Amejia481** [comment]
> @Amejia481 I tried adding the '@workerthread' annotation to SitePermissionsStorage class but I get this error during compilation - 'error: incompatible types: NonExistentClass cannot be converted to Annotation'. Could you please give me some pointers on how to fix this?

Sorry, it looks like I just missed this message, I think the annotation should be on a function for more info see https://developer.android.com/reference/kotlin/androidx/annotation/WorkerThread

**Comment by Amejia481** [comment]
> Can I work on this? @Amejia481

Yes, no problem

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/android-components/pull/11712#issuecomment-1040841175
