### ISSUE TITLE
Remove the isAutofillEnabled lambda in GeckoLoginStorageDelegate on next GV merge day

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#7290]
Now that GV is giving us the runtime setting for `loginAutofillEnabled` we can remove the `isAutofillEnabled` param in `GeckoLoginStorageDelegate` once this is in all GV builds.

**Comment by pocmo** [comment]
Next merge day means we can remove this starting with GV 78 (which is currently beta and will then be release)?

**Comment by ekager** [comment]
Oops sorry missed this! We can do this now that `loginAutofillEnabled` has landed in the beta dimension
