### ISSUE TITLE
Glean Crasher sent as Native crash when the stack in logcat looks to be a Java crash

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#7303]
Looks like there is something incorrect when Glean crashes are sent. The first user submitted a log that points to Glean. In the next comment a user links the crash-stats report that contains a native stacktrace.

https://github.com/mozilla-mobile/fenix/issues/11335

https://crash-stats.mozilla.org/report/index/5c5c669a-99e2-46de-aa33-3e9c50200608

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6294)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792905

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
