### ISSUE TITLE
Have EngineView push handled MotionEvents to clients

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#7307]
This needs a bit of investigations but might help simplify things in [BrowserToolbarBottomBehavior]( https://github.com/mozilla-mobile/android-components/blob/ebec562345af549ce2996d677e1f51761fd7b1e4/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt) and other parts where we have to sync gestures with what happens in GV.

Giving that [NestedGeckoView overrides onTouchEventForResult](https://github.com/mozilla-mobile/android-components/blob/cd134a34c94a4419167aa55b7c09babc9b6f60d8/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt#L57) to get the MotionEvent based on which GeckoView discerns user interactions this should be simple enough and would help removing the synchronization needed in AC between GeckoView and other widgets that should respond to the same user gesture.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6299)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796303

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
