### ISSUE TITLE
Intermittent test failure Execution failed for DexingWithClasspathTransform: /builds/worker/checkouts/src/components/concept/engine/build/intermediates/runtime_library_classes/debug/classes.jar.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#7322]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=305685168&repo=android-components

[task 2020-06-09T19:55:50.629Z] > Task :feature-tabs:generateDebugAndroidTestResources UP-TO-DATE
[task 2020-06-09T19:55:51.120Z] 
[task 2020-06-09T19:55:51.120Z] > Task :feature-tab-collections:kaptDebugKotlin
[task 2020-06-09T19:55:51.120Z] [WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).
[task 2020-06-09T19:55:51.420Z] 
[task 2020-06-09T19:55:51.420Z] > Task :feature-tab-collections:compileDebugKotlin
[task 2020-06-09T19:55:51.420Z] > Task :feature-tab-collections:mergeLibDexDebugAndroidTest FAILED
[task 2020-06-09T19:55:51.820Z] > Task :feature-tabs:mergeDebugAndroidTestResources
[task 2020-06-09T19:55:51.920Z] > Task :feature-tab-collections:javaPreCompileDebug
[task 2020-06-09T19:55:52.025Z] > Task :feature-tab-collections:processDebugAndroidTestResources
[task 2020-06-09T19:55:53.120Z] > Task :feature-tab-collections:mergeExtDexDebugAndroidTest
[task 2020-06-09T19:55:53.220Z] 
[task 2020-06-09T19:55:53.220Z] FAILURE: Build failed with an exception.
[task 2020-06-09T19:55:53.220Z] 
[task 2020-06-09T19:55:53.220Z] * What went wrong:
[task 2020-06-09T19:55:53.220Z] Execution failed for task ':feature-tab-collections:mergeLibDexDebugAndroidTest'.
[task 2020-06-09T19:55:53.220Z] > Could not resolve all files for configuration ':feature-tab-collections:debugAndroidTestRuntimeClasspath'.
[task 2020-06-09T19:55:53.220Z]    > Failed to transform artifact 'classes.jar (project :concept-engine)' to match attributes {artifactType=android-dex, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.api.attributes.VariantAttr=debug, com.android.build.gradle.internal.dependency.AndroidTypeAttr=Aar, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
[task 2020-06-09T19:55:53.220Z]       > Execution failed for DexingWithClasspathTransform: /builds/worker/checkouts/src/components/concept/engine/build/intermediates/runtime_library_classes/debug/classes.jar.
[task 2020-06-09T19:55:53.220Z]          > Error while dexing.
[task 2020-06-09T19:55:53.220Z] 
[task 2020-06-09T19:55:53.220Z] * Try:
[task 2020-06-09T19:55:53.220Z] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[task 2020-06-09T19:55:53.220Z] 
[task 2020-06-09T19:55:53.220Z] * Get more help at https://help.gradle.org

**Comment by jonalmeida** [comment]
I'm going to close this since I don't think we see this failure any more. Please re-open if I'm wrong.
