### ISSUE TITLE
Provide id from which the thumbnail load request was made

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7333]
We should pass the association of the thumbnail bitmap along with the ID in which the request came from.

```kotlin
data class Thumbnail(
  val image: Bitmap,
  val id: String
)
```

We may need to better refine this to support top site thumbnails as well where the `id` can be replaced by a `url`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6323)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796256

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
