### ISSUE TITLE
Evaluate the ThumbnailStorage thread pool needs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7334]
When initially adding support for browser thumbnails, we created a coroutine dispatcher with a fixed size thread pool, similar to `BrowserIcons`.

We should evaluate if we need [these many threads](https://searchfox.org/mozilla-mobile/rev/7cfc88aaee89e7c10c9109ddf330ea4c2f9ac9c2/android-components/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/storage/ThumbnailStorage.kt#27) and/or if we should share the same pool with `BrowserIcons`.

```kotlin
    jobDispatcher: CoroutineDispatcher = Executors.newFixedThreadPool(THREADS)
        .asCoroutineDispatcher()
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6325)

**Comment by mcomella** [comment]
@jonalmeida Why do we need a separate thread pool from `Dispatchers.IO`?

**Comment by jonalmeida** [comment]
@mcomella we reasoned that a separate dispatcher was better since we make a lot more writes and even more reads to disk that we would not want to block from other IO scheduled on the same dispatcher.

We could evaluate if this is effectively needed, and/or share a dispatcher with BrowserIcons that might have similar needs as well.

Changing the dispatcher in Fenix to use `Dispatchers.IO` and then trying to run other tasks that use the same dispatcher, we can compare the results to see if we're losing or gaining perf.

**Comment by jonalmeida** [comment]
Considering this ticket today: we could still try the IO dispatcher or reduce the number of threads in this particular pool. We could also think about used the `Cached` dispatcher, but that might be a foot-gun based on some offline conversations with Christian/perf team that we can end up starving the dispatcher if we aren't careful.

The tabs tray has become an important and highly used surface in the browser so keeping it fast is important - if that means having a dedicated thread pool, then it might be worth it.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796255

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
