### ISSUE TITLE
Connecting to sync immediately syncs twice

### ISSUE THREAD

**Issue by mhammond** [mozilla-mobile/android-components#7335]
I'm still diagnosing this, but thought I'd get it out there for comments.

STR:
* Start Fenix without an fxa user
* Sign in to FxA
* Observe via logcat that 2 syncs immediately (but sequentially) happen

I see `syncNow:161, WorkManagerSyncDispatcher` called twice in quick succession - the first time, `reason` says FirstSync (which seems reasonable). However, the second time has `reason` as Startup - even though the app has been started long enough to complete the sign in flow.

It smells as though that second sync should not be happening in this case, but I'm yet to work out exactly why it does.

(And unsurprisingly given that "startup" sync, it doesn't reproduce when disconnecting then reconnecting - once it has reproduced once, you need to uninstall and start fresh to reproduce again)

cc @grigoryk

**Comment by mhammond** [comment]
When tracking down that "declined" issue, I think there's another latent bug here. I believe that the persisted state for syncing was fetched at the time the sync call was *queued*, not when it was executed. So if there's one sync running and one sync queued, and the first sync changes (say) the declined engines, it seems likely that second sync will execute with the old state, not new state as updated by that first sync.

(This is basically a note-to-self and should possibly be a different issue - I'll try and ping @grigoryk tomorrow)

**Comment by grigoryk** [comment]
Filed https://github.com/mozilla-mobile/android-components/issues/7874 for the second issue.

I figured out the double-sync issue while working on #7856, will land a fix there. Rough summary is that periodic sync would get scheduled when everything is initialized, and in practice the first one would run pretty much "right away". This coincided with a manual request to "sync now" from the account manager during startup. There's debouncing logic in place but it didn't work in this particular case.
