### ISSUE TITLE
Provide request interceptor to automatically navigate into PWAs

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/android-components#7366]
For mozilla-mobile/fenix#5772 a request interceptor is needed that will launch a PWA intent when the user navigates to a URL which falls into the scope of a PWA.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6356)

**Comment by csadilek** [comment]
Landed back in https://github.com/mozilla-mobile/android-components/pull/7367.
