### ISSUE TITLE
Let EngineSessions request release from their EngineView

### ISSUE THREAD

**Issue by TitanNano** [mozilla-mobile/android-components#7380]
In mozilla-mobile/fenix#11543 we encounter a situation where one PWA activity would supersede another one, and they both should use the same session, but neither `onDestroy` nor `onStop` will be called until the new activity has started. The best solution here would be to let a `EngineSession` use it's `observer` to notify observing `EngineView`s that this session has to be released. We then can safely use the session in a new `EngineView`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6370)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796436

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
