### ISSUE TITLE
[Bug] "Google search fix" icon not displayed while using the Dark theme

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#7383]
## Prerequisites
Have the **Dark** theme selected 

## Steps to reproduce
1. Open the Add-ons manager
2. Check "Google search fix" Add-on

### Expected behavior
Properly displayed, visible icon

### Actual behavior
The icon isn't displayed

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

* Fenix version: **Debug build from Master**

### Notes
❗ Works properly while using the **Light** theme

► Video
![20200615-102955-1](https://user-images.githubusercontent.com/51314259/84632065-0c9d1e00-aef7-11ea-92f0-99d82125789d.gif)

**Comment by csadilek** [comment]
Closing. See: https://github.com/mozilla-mobile/android-components/issues/7405#issuecomment-645419326
