### ISSUE TITLE
[Bug] "Downloading and verifying add-on" snackbar is bigger

### ISSUE THREAD

**Issue by softvision-miralobontiu** [mozilla-mobile/android-components#7385]
## Steps to reproduce
1. Go to three-dot menu - Add-ons.
2. Install any of the recommended add-ons.
3. Observe the "Downloading and verifying add-on" snackbar.

### Expected behavior
"Downloading and verifying add-on" snackbar has the correct UI.

### Actual behavior
"Downloading and verifying add-on" snackbar is bigger.

### Device information
* Android device: all
* Fenix version: Nightly debug build, GV 79.0a1-20200612094620, AS: 60.0.0

![Untitled](https://user-images.githubusercontent.com/40694158/84634334-53d8de00-aefa-11ea-8686-15aaee6a31f1.png)

**Comment by csadilek** [comment]
@softvision-miralobontiu this is on purpose as we now have support for cancellation. Original UX design is here: https://miro.com/app/board/o9J_kw8Lt8g=/?moveToWidget=3074457347043892302&cot=3

So, the cancel button and tap area need some more space. I am closing this, but feel free to re-open if I misunderstood :).
