### ISSUE TITLE
[Bug] Inaccessible settings due to misaligned tap areas in “YouTube High Definition” dashboard

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/android-components#7386]
**Steps to reproduce:**
1. Install YouTube High Definition add-on
2. Access any site
3. Tap the three dot menu → Add-ons → YouTube High Definition icon and access the add-ons settings
4. Attempt to modify the settings

**Expected behavior**
Users should be able to properly change the add-on’s settings

**Actual behavior**
1. Tapping the drop down menu of a setting or on a particular cassette will open the options for another setting
Ex 1: Tapping the “Video Size” drop down will open the options for “Video Quality”
Ex 2: Tapping on the “Embedded Video” cassette will open the options for “Video Size”
2. Tapping on the area beneath the actual settings will open the options for “Video Size” or sometimes for “Video Speed”
3. Zooming in will let users change the wanted settings more precisely
Ex: Tapping “Video Quality” drop down while zoomed in will open the corresponding settings
4. The settings for Volume, Auto Play, Embedded Video and Generic are inaccessible

**Device information**
Android device:
• Samsung Galaxy S7 Edge (Android 8.0.0)

Fenix version: Nightly debug build, GV 79.0a1-20200612094620, AS: 60.0.0 from 6/15

![20200615_115638](https://user-images.githubusercontent.com/50236075/84642501-3b21f580-af05-11ea-9a57-40e8eee24a59.gif)

**Comment by acornestean** [comment]
Issue seems to no longer occur in build GV: 79.0a1-20200615092624, AS: 60.0.0 from 6/17.
Will not close the issue for the moment unless specified otherwise.

**Comment by csadilek** [comment]
@acornestean Thanks! If this works now in latest Nightly, it's OK to close this ticket.

**Comment by acornestean** [comment]
As the issue no longer occurs on the latest Nightly (GV: 79.0a1-20200615092624, AS: 60.0.0 from 6/17) and based on the above comment, will close the issue. Thanks !
