### ISSUE TITLE
[Bug] White edges round the "Privacy Possum" icon in Add-ons sub-menu

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#7387]
## Prerequisites
"Privacy Possum" should be installed 

## Steps to reproduce
1. Open a websites
2. Tap the ⋮ Main menu and open the Add-ons
3. Check the "Privacy Possum" icon in the Add-ons sub-menu

### Expected behavior
Properly displayed

### Actual behavior
White edges round the icon

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

* Fenix version: **Debug build from Master**

### Notes
►  Screenshot
![rsz_screenshot_20200619-045347](https://user-images.githubusercontent.com/51314259/84642794-a4a20400-af05-11ea-8d80-f5f7d37ac3db.png)

**Comment by csadilek** [comment]
@AndiAJ Can we put this into the doc for the add-on developer to get an updated icon? This is not actionable for us. Feel free to open if I misunderstood.
