### ISSUE TITLE
[Bug] “Decentraleyes” tapping gear button does not open add-on settings

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/android-components#7388]
**Steps to reproduce:**
1. Install Decentraleyes add-on
2. Access any site
3. Tap the three dot menu → Add-ons → Decentraleyes icon and access the add-on dashboard
4. Tap on the gear button to open the add-on’s settings

**Expected behavior:**
Tapping the gear button should open the add-on’s settings

**Actual behavior:**
The add-on’s settings page is not opened. The user is redirected to the page from Step 2.

Device information
Android device:
• Samsung Galaxy S7 Edge (Android 8.0.0)

Fenix version: Nightly debug build, GV 79.0a1-20200612094620, AS: 60.0.0 from 6/15

![20200615_125235](https://user-images.githubusercontent.com/50236075/84644052-4fff8880-af07-11ea-89cc-8b2ab0e5405a.gif)

**Comment by csadilek** [comment]
This depends on: https://github.com/mozilla-mobile/android-components/issues/7397

**Comment by csadilek** [comment]
@acornestean @AndiAJ This should work now on latest Fenix master (you'd have to rebase your local build).

**Comment by AndiAJ** [comment]
Hi @csadilek , **verified as fixed** on latest **`Debug Build from Master`** using the following devices:
• Google Pixel 3a (Android 10)
• Huawei Mate 20 Lite (Android 9)
• OnePlus A3 (Android 6.0.1)

► Video
![20200619-124820](https://user-images.githubusercontent.com/51314259/85120839-7b96b180-b22c-11ea-8fd0-912c5205da88.gif)
