### ISSUE TITLE
[Bug] Use the same "Privacy Possum" icon everywhere for better visibility and consistency

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#7389]
## Prerequisites
Use the Dark theme
"Privacy Possum" should be installed

## Steps to reproduce
1. Check the "Privacy Possum" icon from the Add-ons manager
2. Check the "Privacy Possum" icon in the  ⋮ Main menu → Add-ons sub-menu

### Expected behavior
Visible "Privacy Possum" icon in the Add-ons manager while using dark theme

### Actual behavior
Different icons 
Poor visibility of the icon in the Add-ons manager

### Device information

* Android device: all
* Fenix version: Debug build from Master

### Notes
► Screenshots
![rsz_screenshot_20200619-045943](https://user-images.githubusercontent.com/51314259/84644486-e764db80-af07-11ea-80fa-b89761b89a16.png)

**Comment by csadilek** [comment]
@AndiAJ The icons would need to be updated by the add-on developer. This is not actionable in A-C or Fenix directly. Can we add this to the document we collect for add-on devs and close here?
