### ISSUE TITLE
[Bug] Can't enable/disable "Privacy Possum" for specific web sites

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#7390]
## Prerequisites
Privacy Possum should be installed

## Steps to reproduce
1. Navigate to any web site
2. Tap the ⋮ Main menu → Add-ons sub-menu
3. Tap and open Privacy Possum
4. Tap the Enable/Disable button
![rsz_screenshot_20200615-133941](https://user-images.githubusercontent.com/51314259/84648787-2d24a280-af0e-11ea-8b0a-692d5911a0e0.png)

### Expected behavior
Properly working Enable/Disable button

### Actual behavior
Can't Enable/Disable  "Privacy Possum" for a specific web site

### Device information

* Android device: 
• Google Pixel 3a (Android 10)
• OnePlus A3 (Android 6.0.1)

* Fenix version: Debug build from Master

### Notes
❗ Works if you zoom in the page, but still, it's **highly dependable on how much you zoom in**
► Video
![20200615-135007](https://user-images.githubusercontent.com/51314259/84649622-80e3bb80-af0f-11ea-858b-b03d2602ead9.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6387)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796310

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
