### ISSUE TITLE
[Bug] “YouTube High Definition” lower resolution icon used in three dot menu vs. Add-ons Manager

### ISSUE THREAD

**Issue by acornestean** [mozilla-mobile/android-components#7391]
**Steps to reproduce:**
1. Install YouTube High Definition add-on
2. Check add-on icon in Add-ons Manager
3. Access any site
4. Tap the three dot menu → Add-ons
5. Check the add-on icon in three dot menu
6. Observe that the icon from the three dot menu is lower resolution than the one in Add-ons Manager 

**Expected behavior:**
The same, higher resolution icon should be used for the three dot menu as well.

**Actual behavior:**
The icon from the three dot menu is lower resolution than the one in Add-ons Manager. 

Device information
Android device:
• Samsung Galaxy S7 Edge (Android 8.0.0)

Fenix version: Nightly debug build, GV 79.0a1-20200612094620, AS: 60.0.0 from 6/15

![20200615_140646](https://user-images.githubusercontent.com/50236075/84650991-e89b0600-af11-11ea-91a6-e5f5727505bb.jpg)

**Comment by csadilek** [comment]
@AndiAJ The icons would need to be updated by the add-on developer (and in AMO). This is not actionable in A-C or Fenix directly. Can we add this to the document we collect for add-on devs and close here?
