### ISSUE TITLE
PromptFeature requires camera permission instead of using runtime permission

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7399]
During PromptFeature integration into Focus, testing the example file input API [here](https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications), we are never able open a file uploader because we need to add a manifest permission for camera access.

We should make this request a runtime permission instead, otherwise it would be weird for a browser to have camera permissions when installed.

Original review comment: https://github.com/mozilla-mobile/focus-android/pull/4562#discussion_r439938634

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6398)

**Comment by jonalmeida** [comment]
Spoke to Arturo about this offline. We shouldn't need the manifest permission any more because we are checking for [file access](https://github.com/mozilla-mobile/android-components/blame/53c39c44aa2630b68b4122f437aced158933bc69/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt#L94). Did we need to add camera permissions to this as well (if so, why)?

**Comment by Amejia481** [comment]
It would be good to test in a device with an OS before Android M, as I'm an not sure if we have to add the permission in the manifest for these devices.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796494

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
