### ISSUE TITLE
[Bug] "Google search link fix" doesn't work

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/android-components#7405]
### Prerequisites
Install "Google search link fix" 
Google should be set as default search engine
"Show clipboard suggestions" should be enabled

## Steps to reproduce
1. Search for "Firefox"
2. Long tap on the first search result
3. Select "Copy link" from the context menu
3. Tap the Tabs counter and Tap the  New Tab FAB
4. Tap the Search bar
5. Check the Fill link address from the search view

### Expected behavior
The mozilla.org link should be copied

E.g.
https://www.mozilla.org/en-US/firefox/new/?redirect_source=firefox-com

### Actual behavior
The google.com Firefox search related link is copied

E.g.
https://www.google.com/url?q=https://www.firefox.com/&sa=U&ved=2ahUKEwiFvcm7rYbqAhWMBhAIHS3LDy0QFjAAegQIBRAB&usg=AOvVaw1B7XOcRNBrBOR6kjb9-olB

### Device information

* Android device: all
* Fenix version: Debug build from Master

### Notes
❗ Noticed the following in the **"Limitations"** in the **details** section
![rsz_screenshot_20200616-155616](https://user-images.githubusercontent.com/51314259/84777697-9d085b00-afea-11ea-9e1e-ecbf2f9602ab.png)

❗ Also, doesn't seem to be working when opening Google or Yandex search results (compared it against the behavior from Desktop) 

► Video
![20200616-155205](https://user-images.githubusercontent.com/51314259/84777414-3aaf5a80-afea-11ea-8e24-9a55b83b8a84.gif)

**Comment by fluffyemily** [comment]
We have had updates from the add on developer here that suggest that Google Search Link Fix is not operational on phones, only tablets. Due to this Philipp has decided to remove Google Search List Fix from the M3 add on list.

**Comment by AndiAJ** [comment]
Thanks @fluffyemily ! ☺️ 
In this case I'll go ahead and close this issue
