### ISSUE TITLE
Sample Browser: Clicking the tab menu icon freezes the entire app with SystemEngine

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#743]
Steps to reproduce:
1. Load https://www.microsoft.com/en-ca/
2. Click the tab menu icon.
3. Observe the delay in switching from the current tab to the tab view.

GIF of the issue: https://gfycat.com/UnluckyLikelyIggypops

**Comment by jonalmeida** [comment]
Looking at the memory profiler, there's a large de-allocation taking place when we click the tab icon.
In the image below, every dot is a click on the tab icon, and every other dot is a click on the thumbnail back to the WebView.

<img width="1721" alt="screen shot 2018-09-10 at 6 09 02 pm" src="https://user-images.githubusercontent.com/1370580/45327305-03626e80-b525-11e8-9282-f93472728062.png">

**Comment by jonalmeida** [comment]
It looks like the issue is related to the allocations from the `TabsAdapter`. There are a lot of [`Rect`][1] objects being created from the view inflation.

My guess is that our implementation of the tabs with the lazy initialization might be related to this.

[1]: https://developer.android.com/reference/android/graphics/Rect.html

**Comment by csadilek** [comment]
Hm I am actually not able to switch between tabs more than once with SystemEngine (Gecko is fine.)...

**Comment by pocmo** [comment]
When adding the tabs fragment and removing the browser fragment we save the state of the sessions to disk (`BrowserFragment.onStop() -> SessionFeature.stop() -> SessionStorage.persist()`). Can this be causing this?

**Comment by jonalmeida** [comment]
We should get this fixed soon since more and more people are using the reference browser.

**Comment by pocmo** [comment]
> We should get this fixed soon since more and more people are using the reference browser.

As long as it is in the Gecko builds too.. :)

**Comment by pocmo** [comment]
Okay, I have an idea and a prototype. Will propose something. :)
