### ISSUE TITLE
EditToolbar close button does not have content description

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#744]
- Enable Talkback or other screen reader
- Click url bar to open toolbar
- Highlight close button

## Expected
"Close, button"

## Actual
"button"

fwiw, we need this for the next release but I assume you don't have time to translate strings so we'll have to work around it.

**Comment by Sdaswani** [comment]
Note we have until the 21st to ship our product so maybe the localization can happen while we work on a fix this week?
