### ISSUE TITLE
Provide API call to fetch top sites

### ISSUE THREAD

**Issue by MarcLeclair** [mozilla-mobile/android-components#7459]
We added a `prefetch` for topsites that uses `observerForever` from the `FenixApplication` class. The hiccup here is that it doesn't seem very clean and using `LiveData` doesn't return our data quick enough (as in, the coroutine doesn't dispatch on the main thread since its busy doing other things). The goal of prefetching was to draw everything on the first pass instead of having to wait for a callback.  Here's the issue associated with the prefetch : https://github.com/mozilla-mobile/fenix/issues/11660

The goal of this ticket would be to ideally have a query that doesn't return liveData  in order to control the flow of our fragment creation. 

I'm not sure how feasible this is, this was just an idea to avoid using `observeForever` in Fenix.

Edit: Just an aside, this is important from the product perspective since it allows us to get faster to our "final" state of our homescreen, and therefore speeds our start up time.

**Comment by data-sync-user** [comment]
➤ Patricia Lawless commented:

The GH ticket was moved to "Done" 2 weeks ago.

**Comment by mcomella** [comment]
@csadilek Can you confirm this was addressed and put it back into the Top 10 issues column if not? The GH history implies this was moved via JIRA but may not actually have been fixed.

**Comment by mcomella** [comment]
Actually, I did that steps – please close if it's actually done.

**Comment by csadilek** [comment]
@mcomella nope, this issue was somehow eaten by Jira / closed by mistake.

**Comment by csadilek** [comment]
Talked to @gabrielluong about this. He is very likely going to address this as part of https://github.com/mozilla-mobile/fenix/issues/10342.

I think we can just turn `getTopSites` into a `suspend` function and not have it return livedata, which would fix this issue here as well.

**Comment by csadilek** [comment]
Closing as we have a suspend function for this now: `TopSitesStorage.getTopSites`
