### ISSUE TITLE
[Bug] On certain devices Fenix crashes when starting a video - android.widget.RemoteViews$ActionException

### ISSUE THREAD

**Issue by SamuXzX** [mozilla-mobile/android-components#7468]
## Steps to reproduce

1. Open Firefox Preview
2. Enter some website that shows a video (e.g. Youtube, Reddit, Facebook...)
3. Start the video

### Expected behavior
The video should reproduce.

### Actual behavior
Firefox Preview crashes instantly.

### Device information

* Android device: Huawei p8 lite smart (Android 5.1, EMUI 3.1).
* Fenix version: 3.1.0 (Build #20212102)
27.0.4, cc336f32f
GV: 72.0.1-20200107212822

![ezgif-7-6347a051597a](https://user-images.githubusercontent.com/30182251/73258298-b0469580-41c5-11ea-8621-a841c060dc2a.gif)

**Comment by ekager** [comment]
Hey @SamuXzX thanks for your help investigating this! I'm going to try to fix this but found 2 other possible issues while searching. Could you also tell me if your device crashes while downloading files or while updating an add on? Thank you!

**Comment by SamuXzX** [comment]
I tried to download a file. It started the download at first, but it failed soon. I touched "Retry" and it restarted it, but got stuck in an endless download without progress. Here the [Log](https://gist.github.com/SamuXzX/be2634b4260ca042471e47e0da80f9dd) and a screencast:
![screen-recording_20200625-193900](https://user-images.githubusercontent.com/30182251/85771128-e9a31300-b71b-11ea-81fd-d48d159d5c48.gif)

I installed a lot of extensions, I'll let you know when one needs to be updated.

**Comment by ekager** [comment]
@SamuXzX are you still seeing this in the latest Fenix nightly? Thanks!

**Comment by SamuXzX** [comment]
@ekager it seems fixed, I just watched a video with the latest Fenix nightly! Thank you.
Do you need something?
When will this be avaliable in the stable version?

**Comment by kbrosnan** [comment]
Verified by the reporter. Not a device that we have.
