### ISSUE TITLE
PWA Telemetry - ability to count total number of installed PWAs

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7474]
When PWAs are installed, we save their manifest into a local DB. If there's an equivalence between number of saved manifests and installed PWAs, we can simply count number of manifests and expose that as an API.

One possible bit of additional work here is to ensure that we've actually installed the shortcut between saving the manifest. Currently, we first save a manifest, and then request a shortcut installation (which could, in theory, fail?). If the failure is possible, we'll over-count number of PWAs we have installed, and will display wrong states for them in the UI, as well.

**Comment by NotWoods** [comment]
Since there's no way to check if shortcuts are removed, we just check if the PWA was used recently. `hasRecentManifest` already implements this behaviour.

**Comment by grigoryk** [comment]
@NotWoods i see, so we never end up using `uninstallShortcuts`? There's no callback to us from the OS when user removes a shortcut?

"used within last 30 days" seems reasonable as a proxy for "installed". I guess we'll name it something like "number of PWAs in active use".

**Comment by NotWoods** [comment]
Yes, we use the time as a proxy since there is no OS callback.

**Comment by grigoryk** [comment]
> Yes, we use the time as a proxy since there is no OS callback.

Do we need the `uninstallShortcuts` api then?

**Comment by NotWoods** [comment]
It's currently unused but available in case we want to expose a manual uninstall UI in the future.
