### ISSUE TITLE
What's up with CoordinateScrollingFeature?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7482]
Looks like this is only used in sample browser. RB doesn't seem to use it. Fenix doesn't seem to use it. Should they? Or can we get rid of it?

**Comment by jonalmeida** [comment]
I was looking at that today as well! 😄 

I thought it would help with the scrolling behaviour in Focus. It looks like it was added for SystemEngineView so I imagine that might still apply.
