### ISSUE TITLE
SendCrashTelemetryService should use a different notification text

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7483]
Currently `SendCrashTelemetryService` uses the same notification has the service that sends crash reports:
https://github.com/mozilla-mobile/android-components/blob/master/components/lib/crash/src/main/java/mozilla/components/lib/crash/service/SendCrashTelemetryService.kt#L30

This is slightly confusing since we will show the crash reporter prompt (where we ask the user whether they want to send a crash report) and at the same time the notification says "Sending crash report to Mozilla". Maybe we could use a string like "Collecting crash data" or something like that?

**Comment by pocmo** [comment]
CC @rocketsroger Maybe a quick improvement.

**Comment by rocketsroger** [comment]
Reverting the string.  Will put up the change after code/string freeze
