### ISSUE TITLE
NewTabSearchUseCase should set parent session as current selected session

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#7512]
Currently if you select text and "search" and then press back, you go back to the Fenix homescreen. A new tab search conducted on a website should use that session as the parent session.

See: https://github.com/mozilla-mobile/fenix/issues/11953

**Comment by SS1113** [comment]
**ekager** you already added a commit to fix this issue?! How can Fenix/A-C development team be so fast?! Great work! Please keep it up. And thanks for your hard work!
