### ISSUE TITLE
Investigate/fix why warnings are not marked as errors

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#752]
We have #750 which should have been caught with a build failure since we have the lint option to convert warnings to errors:
```groovy
subprojects {
  afterEvaluate {
    if (it.hasProperty('android')) {
      android {
        lintOptions {
          warningsAsErrors true
          abortOnError true
        }
      }
    }
  }
}
```
In our IDE we can see that it's marked as an error but we need to have the build fail because of this.

**Comment by jonalmeida** [comment]
FWIW, we can see the red squiggly under the `.forEach` for that issue in Android Studio 3.3 Canary 8, but we're not seeing it on the stable version of Android Studio 3.2.

We need to figure out what AS 3.3 is doing that we aren't catching in our CLI builds.

**Comment by jonalmeida** [comment]
@mcomella I tried this out and in my test where I'm using a Java 8 `forEach` (which the IDE points out as a new API) doesn't show up as an error.

As I typed that out, I guess it doesn't show up as a warning either, which is why I started off with trying to get Android Lint to fail with it. 🤔

**Comment by mcomella** [comment]
wrt avoiding Java 8 features, I think you can explicitly define your Java
support version in your gradle files, something like:
```groovy

android {
  ...
  // Configure only for each module that uses Java 8
  // language features (either in its source code or
  // through dependencies).
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}
```

But for Java 7. via https://developer.android.com/studio/write/java8-support

**Comment by jonalmeida** [comment]
We have this enabled already with source and target compatibility set as 1.7.

**Comment by mcomella** [comment]
Is it set in each of your modules? Perhaps it needs to be set individually.
/me doesn't know gradle

**Comment by jonalmeida** [comment]
> I'll confirm if it doesn't but manually applying the source and target compatibility and checking if it fails as I expect it should. It should be clear if that was the cause then.

So I tried this and I'm still seeing the build pass.

My next guess is that we can keep a `lint.xml` to apply (similar to fennec) and make those into errors).

**Comment by jonalmeida** [comment]
I tried adding a `lint.xml` that contains error handling for just `NewApi` and all warnings to no avail:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<lint>
   <issue id="MissingTranslation" severity="warning" />

   <!-- The following must be at the bottom of your file!
        All lint issues (not listed above) will be treated as errors. -->
   <issue id="all" severity="error" />
</lint>
```
Added it the `tooling-lint` module and the individual module. I was able to get unused parameters to turn into errors with mcomella's solution since they were showing up as warnings already. Which leads me to think about another problem: why don't `NewApi` issues show up in the gradle output like the unused parameters?

**Comment by jonalmeida** [comment]
You can include the `lint.xml` file as well to used as part of the gradle task as well.
```gradle
lintOptions {
    lintConfig file("lint.xml")
    warningsAsErrors true
    abortOnError true
}
```

Also, Android Lint integrates with gradle to run with it when you write `./gradlew lint`
```bash
$ANDROID_SDK_HOME/tools/bin/lint --check NewApi components

android-components: Error: "android-components" is a Gradle project. To correctly analyze Gradle projects, you should run "gradlew :lint" instead. [LintError]
1 errors, 0 warnings
```

**Comment by csadilek** [comment]
This was a confusing one. Here's what's happening:

- Lint warnings **are** correctly marked as errors. This can be verified by introducing an unused resource in a component or sample app, which will cause the build to fail, as configured.

- The reason this (`NewApi`) lint rule doesn't cause a failure is that it's not supported / detected in Kotlin code, only in Java code. So, this is simply not working in the Android Gradle lint plugin, only in Android Studio. 
This can be verified by adding `Html.fromHtml("", Html.FROM_HTML_MODE_LEGACY, null, null)` to both a Java and Kotlin file in our repo. In Android Studio, this will show a lint error (call only available in API 24) in both files, but running `gradle lint` on the command line will only show a problem in the Java file. 

So, I think, we can close this issue, as lint warning are correctly marked as errors. The original problem (incorrect use of `forEach`) is now also highlighted in AS 3.2+. The only downside is that the Android Gradle lint plugin doesn't support these checks in Kotlin code...

**Comment by jonalmeida** [comment]
That's an interesting find that explains a lot. Thanks! We can investigate a better solution to get the builds to fail in the future. Having AS 3.2+ show the issues for now is good enough for me.
