### ISSUE TITLE
Fennec migration: (Regression) Tapping the app icon dismisses the migration onboarding screen

### ISSUE THREAD

**Issue by ebalazs-sv** [mozilla-mobile/android-components#7526]
## Steps to reproduce
1. Install the Fenix migration build over Fennec. Open the updating app.
2. Wait for the migration complete screen, with the "Start Firefox Beta" button;
3. Minimize the app by pressing the home button;
4. Tap the app icon to return to Fenix. 
### Expected behavior
The migration complete onboarding screen is still shown.
### Actual behavior
The migration onboarding is dismissed when you return to the app and the Fenix onboarding screen is displayed. Also, the migration complete notification remains displayed until dismissed.

### Notes:
![20200626_151324](https://user-images.githubusercontent.com/48799384/85857285-38a38380-b7c2-11ea-9c26-00af57283726.gif)

Seem to be a regression of [#7980](https://github.com/mozilla-mobile/fenix/issues/7980).

### Device information

* Android device: Motorola Moto G6 (Android 8), Huawei MediaPad M3 lite (Android 7), Xiaomi Mi Pad 2 (Android 5.1)
* Fenix version: Beta Migration 78.0.0-beta.1 from 6/26

**Comment by ebalazs-sv** [comment]
This issue is reproducible on Beta Migration 78.0.1-beta.1 GV 78 from 6/27 with Motorola Moto G6 (Android 8).

**Comment by ekager** [comment]
Also see https://github.com/mozilla-mobile/fenix/pull/8723

**Comment by st3fan** [comment]
This is as designed.
