### ISSUE TITLE
Share build code, e.g. codecov configuration

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#753]
How can we share build code? As gradle plugins? Or import the scripts directly?

Focus recently fixed an issue in their codecov configuration – https://github.com/mozilla-mobile/focus-android/issues/3029 – and Fire TV was left without them. I recently copied the changes in a new PR: https://github.com/mozilla-mobile/firefox-tv/issues/1008

Ideally, this code would be shared so we would never have two projects be out-of-sync.

**Comment by pocmo** [comment]
This was one of my goals with this separate repository. And I was hoping that there would be a mobile release engineer to own it at some point. But so far this hasn't happened and I do not have the capacity to move more things to be reusable.

https://github.com/mozilla-mobile/android-automation-tools

**Comment by mcomella** [comment]
Sounds like this issue is unnecessary then.

I filed https://github.com/mozilla-mobile/android-automation-tools/issues/17 for codecov.
