### ISSUE TITLE
View.dp has nothing to do with View

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#754]
We have a function `View.dp()` that converts px to dp:
https://github.com/mozilla-mobile/android-components/blob/d055cc58566737697b360bd08728b80a7bffa91c/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/View.kt#L32-L33

However, this has nothing to do with a View, which makes it hard to find and clutters View with confusing methods. I would propose one of:
```kt
fun Int.pxToDp(context: Context)
fun Resources.pxToDp(pixels: Int)
```

**Comment by SubhrajyotiSen** [comment]
`fun Resources.pxToDp(pixels: Int)` sounds better. 
Can I submit a PR for this?

**Comment by mcomella** [comment]
@csadilek ^

**Comment by pocmo** [comment]
fwiw this extension method was on `View` because it was used a lot *inside* views.

**Comment by mcomella** [comment]
On Mon, Sep 24, 2018 at 6:04 AM Sebastian Kaspari <notifications@github.com>
wrote:

> fwiw this extension method was on View because it was used a lot *inside*
> views.
>

In that case, I'd suggest writing `Resources.dpToPx` and either 1) having
`View.dpToPx` delegate to Resources or 2) adding it as a private function
in places where the alias is convenient. I prefer having it on Resources
because it's more discoverable, more "correct", and there are potentially
use cases where a view is not directly involved (e.g. maybe measuring
device width).
