### ISSUE TITLE
Refactor `MainCoroutineRule` to use `TestCoroutineDispatcher` by default.

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#7556]
This makes it easier to use methods like `advanceUntilIdle()`. I'm unsure if we need to change the parameter type to coroutine rule or test coroutine rule.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6533)

**Comment by csadilek** [comment]
Closing as outdated. `TestCoroutineDispatcher` is deprecated and we've switched to `UnconfinedTestDispatcher`.
