### ISSUE TITLE
Use different naming for whitelist/blacklist

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7557]
Taking a page from iOS, in addition branch name changes, we should rename our blacklist/whitelist naming as well to something like allow/deny list:

Search queries of references:
 - blacklist: https://searchfox.org/mozilla-mobile/search?q=blacklist&path=android-components
 - whitelist: https://searchfox.org/mozilla-mobile/search?q=whitelist&path=android-components

**Comment by morrme** [comment]
has the terminology been agreed upon? i've also seen 'blocklist'

**Comment by jonalmeida** [comment]
@morrme `blocklist` sounds good to me, I see iOS used that too: https://github.com/mozilla-mobile/firefox-ios/pull/6783
