### ISSUE TITLE
Expose getBookmarkUrlForKeyword A-S api

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7558]
https://github.com/tinoism/application-services/commit/faaa8aba4dc95de9b7e5e8fd0e0ab1f89acec4a7 added this API, but we never exposed it in A-C. Let's do that, so we can add keywords support to the fenix awesomebar.

**Comment by Mugurell** [comment]
Based on https://github.com/mozilla-mobile/android-components/pull/8375#issuecomment-704144847 this won't be needed. Closing the ticket.
