### ISSUE TITLE
Provide a way to customize Toolbar url bar text

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#756]
In particular, we need to change the:
- Color
- Text size
- Hint color

We also managed to change the font family by setting the default font family across our app but for other apps, it could be customized more directly.

**Comment by jonalmeida** [comment]
@mcomella that's a nice idea that should maybe come in a separate issue. If we move this into a subobject `text`, then I'd argue, so should `hint` move there too and I don't want to break APIs for other apps just yet. :)
