### ISSUE TITLE
Add circuit-breaker to prevent FxA auth recovery loop

### ISSUE THREAD

**Issue by rfk** [mozilla-mobile/android-components#7570]
In [this reddit thread](https://www.reddit.com/r/firefox/comments/hi79tg/firefox_beta_sync_issues/) the user reports a very strange behaviour from Fenix, saying that it "tries to sync, signs out, re-connects automatically and signs out automatically once every second". There is a similar report [here](https://www.reddit.com/r/firefox/comments/hhp7a4/sync_acting_buggy_in_android_andor_windows/) saying that a "purple notification kept floating up from the bottom of the app (repeatedly/non-stop) saying that sync was on".

From discussion with @grigoryk, we suspect these users are somehow stuck in an FxA "auth problem recovery" retry loop, going roughly like:

1. A request using FxA state in the browser fails with an auth error, pushing the FxaAccountManager into the `AuthenticationProblem` state.
2. The FxaAccountManager tries to get a fresh auth token from the FxA server, succeeds, and transitions back to its happy `AuthenticatedNoProfile` state.
    * As part of this, it fires a `AuthType.Recovered` notification to observers, causing Fenix to show a little notification about the account being connected
3. The thing that failed at (1) tries again, but still fails.
    * We go to (1), and repeat indefinitely.

We have this theory that such a loop *should* never happen, and that whatever triggered the failure at step (1) *should* always recover if we are able to get a fresh OAuth token from FxA. But it appears this is not happening for at least two users in the wild, and I'm worried it could happen for more when we roll this out to the Fenix release population.

Could we please consider adding some sort of circuit-breaker here to prevent an infinite loop of retries? Even better if we're able to log the cause of the infinite loop to sentry, but if that's not possible, just being able to avoid DoSing the FxA servers would be excellent :-)

I'm not entirely sure what the implementation of this would look like. Perhaps it would suffice to keep a last-successful-retry timestamp in the in-memory state of FxaAccountManager, and refuse to loop again if we already retried recently, instead driving to the persistent "need to reconnect" state.

**Comment by rfk** [comment]
Fenix emits an event whenever it shows that "sync is connected" notification, and I am seeing a *gigantic* spike in "sync_auth - recovered" events over the last few days:


  https://sql.telemetry.mozilla.org/queries/72373#181485

I don't want to put the raw counts in a public bug, but here's the graph to give you an idea of the spike:

![Capture](https://user-images.githubusercontent.com/34695/86088476-cb596080-bae9-11ea-9354-d45eb26f70eb.PNG)

It seems to have begun very suddenly on June 27, does this correspond to a Fenix update?

**Comment by rfk** [comment]
Digging in a bit more, it seems that there is a small number of clients stuck in this state and responsible for logging a very large number of these events. In [this graph](https://sql.telemetry.mozilla.org/queries/72373/source#181488) I look at the number of unique client_ids that report more than 100 "sync_auth - recovered" events in a day. Prior to the 27th this was hovering in low single digits, but it is now high double digits, and I'm worried that it might continue to grow over the coming days.

**Comment by rfk** [comment]
Peeking in the FxA server logs in bigquery, there are indeed users who are requesting many thousands of access tokens per day from Fenix, suggesting that the "recovery" part of the loop here is working as intended (and that this could start to become a real issue for the FxA server if the volume of users continues to climb)

**Comment by rfk** [comment]
Let's incident-response this thing; I started a doc here: https://docs.google.com/document/d/1dYHO1RYFVy9O-nqxXSz7GOi1xiJweVZQY4WgaOqeAtg/

**Comment by st3fan** [comment]
Marking this as  Fenix release blocker. Unclear right now if it should be or not, but since this is turned into an incident, I assume the chances are pretty high.

**Comment by grigoryk** [comment]
Thanks for digging into this, @rfk ! This does _feel_ like a server-side issue of sorts, given the sudden impact on all release channels.

> Could we please consider adding some sort of circuit-breaker here to prevent an infinite loop of retries? Even better if we're able to log the cause of the infinite loop to sentry, but if that's not possible, just being able to avoid DoSing the FxA servers would be excellent :-)

Yup.

> I'm not entirely sure what the implementation of this would look like. Perhaps it would suffice to keep a last-successful-retry timestamp in the in-memory state of FxaAccountManager, and refuse to loop again if we already retried recently, instead driving to the persistent "need to reconnect" state.

Something like that, yeah. Seems like these loops are very tight, so perhaps a small time-window should suffice so that we're not affecting regular recoveries.

And just to be clear, from the doc:
> In the reddit threads, users report that signing out and signing back in, or even deleting and reinstalling Fenix, does not resolve the issue. This again points to some sort of server-side issue.

... this suggests that we'll need a follow-up to this, maybe a server-side or client-side or both.

**Comment by st3fan** [comment]
@grigoryk do you think this should be a release blocker?

**Comment by grigoryk** [comment]
@st3fan yeah, let's not DDOS ourselves :) I'll push out the minimal patch for this soon.

**Comment by rfk** [comment]
> this suggests that we'll need a follow-up to this, maybe a server-side or client-side or both.

Agreed. One of the reddit users has suggested that they'll try to get some logs off their Android device for us to investigate, which if they succeed in doing so will hopefully give a really good clue about what needs fixing on the server.

**Comment by pocmo** [comment]
✅ Landed on master.
✅ Cherry-picked onto `releases/48.0` branch.

**Comment by performation9** [comment]
Hello,
I am one of the reddit users mentioned. Opened a bug here and will provide a log tomorrow: https://bugzilla.mozilla.org/show_bug.cgi?id=1649730
