### ISSUE TITLE
Intermittent java.lang.IllegalStateException: toolResultsStep must not be null

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#7584]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=308035574&repo=android-components

[task 2020-06-30T16:05:01.516Z]   https://console.developers.google.com/storage/browser/android-components_test_artifacts/2020-06-30_16-04-47.958000_blzj/
[task 2020-06-30T16:05:01.516Z] 
[task 2020-06-30T16:05:01.517Z] Matrices webLink
[task 2020-06-30T16:06:18.987Z]   matrix-2miohe67m0s4n Unable to get web link
[task 2020-06-30T16:06:18.988Z] 
[task 2020-06-30T16:06:18.988Z] PollMatrices
[task 2020-06-30T16:06:19.089Z]   0m  0s matrix-2miohe67m0s4n Nexus6-21 Error: Internal error during validation
[task 2020-06-30T16:06:19.089Z]   0m  0s matrix-2miohe67m0s4n Nexus6-21 ERROR
[task 2020-06-30T16:06:19.089Z]   0m  0s matrix-2miohe67m0s4n walleye-28 Error: Internal error during validation
[task 2020-06-30T16:06:19.089Z]   0m  0s matrix-2miohe67m0s4n walleye-28 ERROR
[task 2020-06-30T16:06:19.090Z]   0m  0s matrix-2miohe67m0s4n ERROR
[task 2020-06-30T16:06:19.090Z] 
[task 2020-06-30T16:06:19.091Z] FetchArtifacts
[task 2020-06-30T16:06:19.092Z]   
[task 2020-06-30T16:06:19.187Z] java.lang.IllegalStateException: toolResultsStep must not be null
[task 2020-06-30T16:06:19.187Z] 	at ftl.reports.api.CreateTestExecutionDataKt.createTestExecutionData(CreateTestExecutionData.kt:31)
[task 2020-06-30T16:06:19.187Z] 	at ftl.reports.api.CreateTestExecutionDataKt$createTestExecutionDataListAsync$1$1$1.invokeSuspend(CreateTestExecutionData.kt:22)
[task 2020-06-30T16:06:19.187Z] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[task 2020-06-30T16:06:19.187Z] 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
[task 2020-06-30T16:06:19.187Z] 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
[task 2020-06-30T16:06:19.187Z] 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
[task 2020-06-30T16:06:19.187Z] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
[task 2020-06-30T16:06:19.187Z] 	Suppressed: java.lang.IllegalStateException: toolResultsStep must not be null
[task 2020-06-30T16:06:19.187Z] 		... 7 more
[task 2020-06-30T16:06:19.210Z] + exitcode=1

**Comment by jonalmeida** [comment]
I'm going to close this since I don't think we see this failure any more. Please re-open if I'm wrong.
