### ISSUE TITLE
pageYOffset and viewport height styling issues

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#7585]
Filed from https://bugzilla.mozilla.org/show_bug.cgi?id=1649837

Steps to reproduce:

Visit example site: https://jonohewitt.github.io/pixel-scroller/ with Firefox Nightly 200630 06:01, version 79.0a1

Scroll down the page and back up. 

Actual results:

window.pageYOffset is giving values >1 when scrolling back to the very top of the page. Maybe related to the very thin white line at the top of the window that appears immediately on scroll?

Also, if you scroll down to the bottom of the page, the 100vh CSS styling for the bottom pink section is not taking up the whole window height. It has a section of blue at the top.

Expected results:

window.pageYOffset should be giving a 0 value when scrolled back to the very top. 

The bottom section should fill the window with pink.

![topbottom](https://user-images.githubusercontent.com/250273/86286606-a291a380-bb9b-11ea-8c88-92742bba4256.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6558)

**Comment by kbrosnan** [comment]
This happens on Fenix and Reference browser. Geckoview Example browser does not display this problem.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796302

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
