### ISSUE TITLE
Rename context menu actions for search to simply "Search" without app name

### ISSUE THREAD

**Issue by sblatz** [mozilla-mobile/android-components#7588]
For https://github.com/mozilla-mobile/fenix/issues/10466#issuecomment-652100817

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6561)

**Comment by csadilek** [comment]
Landed in https://github.com/mozilla-mobile/android-components/pull/7589.
