### ISSUE TITLE
Strange behaviour in extension function String.isUrl()

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#760]
The expected behavior for this extension function is determining,  if a string is a url or not, 
but right now is returning true to whatever input that contains a **"."** or **":"** on it.

[/components/support/ktx/kotlin/String.kt](https://github.com/mozilla-mobile/android-components/blob/master/components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt)

```Kotlin
fun String.isUrl(): Boolean {
    val trimmedUrl = this.trim()
    if (trimmedUrl.contains(" ")) {
        return false
    }

    return trimmedUrl.contains(".") || trimmedUrl.contains(":")
}
```
For example:
  ```Kotlin
  @Test
    fun testIsUrl() {
        ///Those are not urls
        assertFalse(" : ".isUrl()) // Returns true
        assertFalse(" . ".isUrl()) // Returns true
        assertFalse(" .: ".isUrl() )// Returns true

    }

```

**Comment by pocmo** [comment]
Heh, yeah. That is code from Focus to determine if we should try to load a URL or perform a search. It works reasonably well for real-world user input. :)

This is the implementation of Firefox for Android:
https://searchfox.org/mozilla-central/rev/0640ea80fbc8d48f8b197cd363e2535c95a15eb3/mobile/android/geckoview/src/main/java/org/mozilla/gecko/util/StringUtils.java#32-71
