### ISSUE TITLE
Improve AppLinksInterceptor readability

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#7614]
Currently `AppLinksInterceptor` have complicated checks that are not easy to read/maintain.  Simplify `doNotIntercept` to make it easier to read.  Update `doNotIntercept` to make it `shouldIntercept`.  Add docs for readability.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6583)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793131

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
