### ISSUE TITLE
Sync.Logins: lockStore is not thread safe

### ISSUE THREAD

**Issue by vladikoff** [mozilla-mobile/android-components#762]
Ref: https://github.com/mozilla-mobile/android-components/pull/676/files#r215348272

**Comment by csadilek** [comment]
We used to have logic here that stored a field (`this.lockStore`) and checked whether or not it was initialized. The field wasn't volatile nor was there a lock.

This logic was removed in a recent refactoring. We now have `DatabaseLoginsStorage` instance from `mozilla.appservices.logins` which does protect its methods with a lock. So, I am closing this issue.
