### ISSUE TITLE
Improving SessionManager's interface

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#764]
(cross-posted, with slight modifications, from https://github.com/mozilla-mobile/fenix/issues/63)

There is a bit of an "action at a distance" problem with how session manager's state as it is perceived by various components. A specific example is the tabs tray interaction with the toolbar in Fenix. If one tab is currently opened (one session is present in the manager), closing that tab will leave session manager with no sessions.
However, toolbar component assumes presence of a selected session - so if you were to open a url, it'll crash as it hits a null session.

At first glance, this seems like a problem at an interface level between the session manager and its consumers. There are two methods to get a session, one of which will throw if set of sessions is empty. So the implicit contract of the manager to its consumers is "you decide if I may be empty". Inevitably this leads to problems like the one I described above, where two parts of the system make different assumptions.

As consuming application grows in complexity, I imagine these kinds of issues will keep popping up, and if not addressed at a lower level will require bunch of cumbersome state management boiler plate code.

I'd be nice if the interface between components made it impossible to represent an illegal state.

One way to address this would be to enforce a behaviour at the manager level - i.e. a "must have a default session" type of a session manager, which would be responsible for enforcing the correct behaviour. ISTM that we'd need this anyway for something like a "new tab" panel, but more generally it should help avoid having components step on each other's toes.

This kind of pattern likely generalizes to other types of "in-between" components.

**Comment by grigoryk** [comment]
`sample-browser` deals with this specific issue via `onTabsTrayEmpty = ::createNewTab` passed into TabsFeature. To me this seems like an illustration of the problem - components that use SessionManager and that are unaware of the TabsFeature are relying on side-effects of its internal state.

**Comment by csadilek** [comment]
Thank you for filing this. When we added `selectedSessionOrThrow` we didn't consider not having a (selected) session to be an illegal state for the `SessionManager`. Instead, we had the consuming components decide whether that's a problem for them or not. I understand the point you're making about this causing unintentional dependencies between otherwise unrelated components (e.g. tabs and toolbar). I think this needs some investigation on how to best solve/avoid this. What would be a good API for that e.g. a separate type of `SessionManager` as you suggest...

**Comment by grigoryk** [comment]
First thing that comes to mind is having two types of managers that applications may consume - one that allows absence of sessions, and one that doesn't. Their corresponding APIs will reflect this - `selectedSession` will return `Session?` in the former, and `Session` in the latter case, for example. `selectedSessionOrThrow` disappears, since we either can't have absence, or must deal with it.

The "can't be empty" manager can be configured with a "default session provider" or something along those lines, which it can invoke when it's about to go empty in response to removal of the last session. This might be easier than shifting responsibility for maintaining presence of the default session onto consuming components.

I can take a stab at this to learn my way around the components.

Also, is it assumed that an application can only have one active `SessionManager`?

**Comment by grigoryk** [comment]
I suppose my comment above is conflating two types of things - concept of having a "selected" session and concept of an empty/never-empty manager.

Do we always have a selected session, or is there sometimes a valid third state?

Do custom tabs and general browser share their session managers?

**Comment by csadilek** [comment]
>Also, is it assumed that an application can only have one active SessionManager?

Yes, correct.

>Do we always have a selected session, or is there sometimes a valid third state?

When we designed this, not having a selected session was considered a valid state (no open tab).

> Do custom tabs and general browser share their session managers?

Yes, we talked about this quite a bit and decided a single session manager instance is the way to go. Otherwise, eventually, we'd need a manager of SessionManagers :)
