### ISSUE TITLE
Add generic key value sync storage

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#7640]
We want to be able to store arbitrary data that will be synced to a user's Firefox Account, with an API similar to the [sync storage in WebExtensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync). 

Work needed:
- Expose webext-storage as an Android API in A-S
- Add feature in A-C
- Use to sync collections in Fenix

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6601)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796375

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
