### ISSUE TITLE
Document and validate service-level assumptions made by FxA/Sync components

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7642]
In https://github.com/mozilla-mobile/android-components/issues/7570 we landed a fix for an incorrect implicit assumption about the overall architecture of the FxA/Sync systems. Let's comb through the codebase, look out for other similar assumptions, document and validate them from an "end-to-end" perspective.

Output of this issue should be comments in the code, reaching out to folks from A-S for correctness checks, and a discoverable document outlining the overall implementation alongside key assumptions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6604)

**Comment by jonalmeida** [comment]
Closing this as won't fix for now. If a discussion arises with the A-S team again, let's re-open/file an issue then.
