### ISSUE TITLE
Ability to capture and share logs via Logger

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7643]
It is very useful to be able to read device logs in order to investigate problems that may arise in various parts of our applications. For example, "get the logs" is the first order of business for investigating any FxA/sync related problems. Most recently, ability to easily investigate device logs (on Firefox Desktop) helped us discover root cause of https://github.com/mozilla-mobile/android-components/issues/7570.

On mobile, this is a little tricky to do. Regular applications can't hold the READ_LOGS permission, since it's a `signature|privileged|development` kind of a permission.

However, we already have a `Logger` component that is used throughout our codebase, and by our consuming applications. We can lean into that and keep a tally of logs that we emit ourselves. Once we're collecting them, these logs can be easily exported.

Things to consider:
- tags and severity are extremely useful for allowing filtered exports
- only keep recent logs, for some useful definition of "recent". Past few days?
- provide export APIs for consuming applications to tap into. We'd want to build a nice "export logs" UI in Fenix on top of this
- ensure that our consuming applications always go through `Logger` for their logging needs
- ensure that GV and A-S code emits their logs via `Logger`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6605)

**Comment by grigoryk** [comment]
I now have a Room-based prototype of this which works pretty well. I've implemented it as a new LogSink, so enabling log persistence in the application is a a matter of `Log.addSink(StorageLogSink(context))`.

Currently it's one log, one insert. We'll probably want to bundle a few log statements together before inserting them altogether, that should speed things up.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793171

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
