### ISSUE TITLE
Add FxA identifier(s) to the glean deletion-request ping

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7646]
Placeholder issues, details to be hashed out.

This is an a-c version of https://bugzilla.mozilla.org/show_bug.cgi?id=1604844 - most of that discussion applies here as well (e.g. sending `sync_uid` and `sync_device_id` values, possible race b/n the deletion ping and these values becoming available, etc).

cc @rfk @mhammond

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6610)

**Comment by grigoryk** [comment]
Pipeline side of things: https://bugzilla.mozilla.org/show_bug.cgi?id=1651236

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794225

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
