### ISSUE TITLE
Wormanager is not working on some devices.

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7659]
We have [a bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1643898) where any component that uses work manager is not working for the user, this include impact features like new add-ons checker, add-ons updater, [sync](https://bugzilla.mozilla.org/show_bug.cgi?id=1646992) and glean.

**Comment by ekager** [comment]
Might not fix it, but have you considered updating the androidx work manager version? Looks like we're on `2.2.0` and a few stable version behind https://developer.android.com/jetpack/androidx/releases/work

**Comment by Amejia481** [comment]
> Might not fix it, but have you considered updating the androidx work manager version? Looks like we're on `2.2.0` and a few stable version behind https://developer.android.com/jetpack/androidx/releases/work

Thanks that could be an alternative to test.

**Comment by ekager** [comment]
Just a bump on this - looks like 2.5.0 is out and includes a fix to "greatly improves job execution reliability".
https://developer.android.com/jetpack/androidx/releases/work#2.5.0

**Comment by jonalmeida** [comment]
We have this working now, so we can consider this fixed I think.
