### ISSUE TITLE
Expose GeckoSession.goToHistoryIndex

### ISSUE THREAD

**Issue by person808** [mozilla-mobile/android-components#7664]
For mozilla-mobile/fenix#1048, we need a way to jump to an arbitrary index in a session's history. It looks like GeckoView already provides the API, it just isn't surfaced in A-C.

**Comment by jonalmeida** [comment]
This PR that added the initial History API support might give you some hints on the different places you would need to make changes to support this feature.

For the navigation API that a consumer would use, you could look into adding a use case in [`SessionUseCases`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt).
