### ISSUE TITLE
Faulty logic for determining presence of an account in synced tabs UI 

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7667]
From https://github.com/mozilla-mobile/fenix/issues/12431:

```
So Synced Tabs logic for determining if account is present or not seems wrong.

Specifically, it's looking at a presence of a an fxa profile, and assumes that there's no account available if that profile is missing. This is wrong - profile may be present or absent, it doesn't affect our ability to sync tabs.
Furthermore, the account observers appear wrong to me, as well. We're probably not re-triggering the UI state correctly in response to account manager events.
```

**Comment by grigoryk** [comment]
Granted, that `profile` API could be pretty misleading! So as part of this, let's document the account API surface a bit better.

**Comment by grigoryk** [comment]
cc @jonalmeida

**Comment by jonalmeida** [comment]
If I remember correctly, this case is what lead to the issue being filed: https://github.com/mozilla-mobile/android-components/issues/6879

We want to know when the account is idle and we have a constellation to call refreshDeviceConstellation, but we can't do that safely without running into complicated callbacks that are unsafe.

**Comment by grigoryk** [comment]
I agree that #6879 is a problem, but I think this is a simpler problem (e.g. we should just switch to checking against `authenticatedAccount` method).
