### ISSUE TITLE
Update KDoc styling and theme

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7669]
There isn't a concrete style and theme, but we should check if there are more accessible versions that we could use.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6624)

**Comment by jonalmeida** [comment]
We should also consider if we can add our site headers to the docs and generate them into HTML so that we do not have rely on Github Pages to generate our KDocs for us - this would have the side-effect of reducing the timeouts we currently see from it.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795374

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
