### ISSUE TITLE
Add simple search for API documentation

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7670]
We could try to add something similar to the [`Android SDK Search`](https://github.com/pocmo/AndroidSDKSearchExtension-Firefox) that keeps a statically generated [list of APIs](https://github.com/pocmo/AndroidSDKSearchExtension-Firefox/blob/master/extension/android-ref.js) and wrap it in some JS within a search bar to begin with.

Ideally, maybe something that uses reverse indexing to make the search results find more relevant docs. In the future, we can add guides and other non-API doc content. :)

**Comment by csadilek** [comment]
@jonalmeida we also have https://github.com/mozilla-mobile/android-components/issues/2609 on file. Close as dupe or merge?

**Comment by jonalmeida** [comment]
Yes, thanks for finding it!
