### ISSUE TITLE
Add Profiler interface to support-base

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7689]
Similar to `CrashReporting` let's create a `Profiler` interface to `support-base`. An `Engine` now exposes an optional `Profiler`... when using this from other components then we do not want to pass an `Engine` to everything, which would mean that everything depends on `concept-engine`. Instead let's create an interface in `support-base`.

Maybe it's even possible to move the `Profiler` interface from `concept-engine` ... since that is already an interface.

**Comment by pocmo** [comment]
Hm, this is actually not as easy as I thought: Moving `Profiler` to `support-base` means that `concept` components (like `concept-engine` would need to depend on something that is not a `concept`. That seems wrong. We may need something like `concept-base`? Which may be a good place for other interfaces that currently live in `support-base` like `CrashReporting` or `MemoryConsumer`.

@csadilek What do you think?

**Comment by pocmo** [comment]
Actually, I'll type an RFC for that :)

**Comment by csadilek** [comment]
> @csadilek What do you think?

Sorry, I missed this. Responded on the RFC PR :).
