### ISSUE TITLE
Move DownloadJobState to its own separate separete file

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7695]
Right now [DownloadJobState](https://github.com/mozilla-mobile/android-components/blob/b54541be152f25fb3471fff28a263b1297503c11/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L102) is holding multiple information some related to the DownloadJob and the UI notification we should make it to have a single responsibility

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6648)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792942

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
