### ISSUE TITLE
Rename EngineSession.enableTrackingProtection(policy) to EngineSession.updateTrackingProtection(policy)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7696]
related issue https://github.com/mozilla-mobile/android-components/issues/7262#issuecomment-657744470

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6650)

**Comment by csadilek** [comment]
Let's track this in https://bugzilla.mozilla.org/show_bug.cgi?id=1794935.
