### ISSUE TITLE
Add support for the TrackingProtectionExceptionStorage on SystemEngine

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7699]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6652)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796475

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
