### ISSUE TITLE
Enlarged Icons Andriod 9

### ISSUE THREAD

**Issue by turtlelovesshoes** [mozilla-mobile/android-components#770]
Forgive me if this the wrong place to report this. It looks like after updating some of the icons are showing pretty off sizes. 
https://twitter.com/TheGayTrader/status/1039694132799664128/photo/1
I can troubleshoot with the user, but wanted to file a bug in the right place.

**Comment by csadilek** [comment]
@turtlelovesshoes this seems to be about Firefox for Android which currently isn't using Android components (a fairly new project).

The bug should be filed over at: https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android

I am closing this issue here. Thanks!
