### ISSUE TITLE
Downloads from Firefox not tagged as downloads on Samsung My Files

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#7715]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1652034

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:79.0) Gecko/20100101 Firefox/79.0

Steps to reproduce:

    Download a file using Firefox
    Open Samsung My Files and choosing "Downloads" (its a tag, not a shortcut to the actual Downloads folder)

Actual results:

Downloads from Firefox did not show up in that category. They do show up if I navigate to sdcard/downloads.

Expected results:

Downloads from Firefox should have been tagged as Downloads and showed in that tag.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6665)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792941

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
