### ISSUE TITLE
The top toolbar behavior should be consistent with the bottom toolbar's behavior in terms of whether the content is vertially scrollable or not

### ISSUE THREAD

**Issue by hiikezoe** [mozilla-mobile/android-components#7718]
Steps to see the issue

1) Open https://bugzilla.mozilla.org/show_bug.cgi?id=1652190
2) Try to scroll down the content

The result with the top toolbar;
 the toolbar moves

The result with the bottom toolbar;
 the toolbar never moves

I believe the behavior with the bottom toolbar is the right behavior here in the bugzilla case.
@Mugurell

**Comment by Mugurell** [comment]
Hello,

Thank you for the report.
This is indeed a known issue which needs more investigation for a proper solution.

**Comment by jonalmeida** [comment]
We briefly looked at this report in the AC triage and we didn't have capacity for it - @Mugurell would have ideas on what could be done next for investigating this further?

**Comment by Mugurell** [comment]
I also filed https://github.com/mozilla-mobile/fenix/issues/10686 and looked into it a little.
After checking in with Sawyer it seemed like we have different solutions for top / bottom toolbar because GV doesn't also clips from the top.

**Comment by hiikezoe** [comment]
With top __dynamic__ toolbar, the metric looks like this;
```
+-----------------+
|     toolbar     |
+-----------------+  <= (0, 0)
|                 |
|                 |
|                 |
|                 |
+-----------------+  <= 100% in CSS units

                     <= 100vh in CSS units
```

With bottom __dynamic__ toolbar, it looks like this;
```
+-----------------+  <= (0, 0)
|                 |
|                 |
|                 |
|                 |
+-----------------+  <= 100% in CSS units
|     toolbar     |
+-----------------+  <= 100vh in CSS units
```

That means the top toolbar doesn't cover web contents at all, it looks as shifting the content offset.

**Comment by Mugurell** [comment]
Thank you hiro!
I've looked a bit into this and indeed, I think it should be pretty straightforward.

The way I see it we need to:
- anchor the engineView to the top toolbar 
while also using `setDynamicToolbarMaxHeight` (with the current height of the toolbar) to make sure webpages with hardcoded / 100% vh are displayed correctly. 
Can you please confirm @hiikezoe that we'd still need to use `setDynamicToolbarMaxHeight` ?

If we need both of the above we'd need a custom behavior.
If we need just the anchoring we can use the default `com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior` in Fenix.

- a new CoordinatorLayout.Behavior<BrowserToolbar> similar to `BrowserToolbarBottomBehavior` to actually translate the *top* toolbar in response to user touches and depending on if GV handled the gesture or not.

Would be great if we would not add to the existing behavior to make it also work for the top toolbar (code there is pretty ugly already) but maybe extract what would be duplicated code.

@jonalmeida I think this is all we'd need (of course with also some wiring in Fenix).
If AC doesn't have the capacity for this I'd hope we can take it in the next sprint.

**Comment by hiikezoe** [comment]
>     * anchor the engineView to the top toolbar
>       while also using `setDynamicToolbarMaxHeight` (with the current height of the toolbar) to make sure webpages with hardcoded / 100% vh are displayed correctly.
>       Can you please confirm @hiikezoe that we'd still need to use `setDynamicToolbarMaxHeight` ?

Yes, we definitely need it for __dynamic__ toolbar regardless where it's positioned.

> If we need both of the above we'd need a custom behavior.
> If we need just the anchoring we can use the default `com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior` in Fenix.
> 
>     * a new CoordinatorLayout.Behavior similar to `BrowserToolbarBottomBehavior` to actually translate the _top_ toolbar in response to user touches and depending on if GV handled the gesture or not.

Yes, FWIW here is a change what I did before against Fenix https://github.com/hiikezoe/fenix/commit/ffa236ec7eb1e8ef4a69718ba313a088b2e94f3c

**Comment by sflorean** [comment]
Didn't encounter any issue while testing this on latest Nightly build. Closing as fixed.
