### ISSUE TITLE
BrowserToolbar.Button adds inconvenient padding around image

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#772]
I found my toolbar butons assets were offset when I changed the toolbar height and it seems the reason for that is that there is padding added to the view:

https://github.com/mozilla-mobile/android-components/blob/f93998788c670b86707d8dee9451a81198a5f15c/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt#L311-L316

I want to be able to declare the assets to be a specific size (with #741?) and center them in the toolbar, rather than having confusing padding added.

---

fwiw, this padding seems to be set in proportion to the toolbar height (which I changed):
https://github.com/mozilla-mobile/android-components/blob/f93998788c670b86707d8dee9451a81198a5f15c/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt#L363-L364

**Comment by pocmo** [comment]
Yeah, `BrowserToolbar.Button` adds default padding to match the default configuration of the toolbar. You may want to override `Toolbar.ActionButton` for your own behavior?

**Comment by mcomella** [comment]
That was my workaround. Unfortunately, it requires knowing the
implementation and could theoretically break in future components versions.

**Comment by Amejia481** [comment]
@mcomella Having a boolean `addDefaultPadding` in the constructor that allows you to add or not the padding is flexible enough for you?

``` kotlin
    open class Button(
        imageResource: Int,
        contentDescription: String,
        visible: () -> Boolean = { true },
        @DrawableRes background: Int? = null,
        listener: () -> Unit,
        val addDefaultPadding: Boolean = false
    ) : Toolbar.ActionButton(imageResource, contentDescription, visible, background, listener) {
        override fun createView(parent: ViewGroup): View {
            val view = super.createView(parent)

            if(addDefaultPadding) {
                val padding = view.resources.pxToDp(ACTION_PADDING_DP)
                view.setPadding(padding, padding, padding, padding)
            }
            return view
        }
    }
```

**Comment by pocmo** [comment]
I think a more flexible solution would be to allow setting padding and setting it to `ACTION_PADDING_DP` by default.

**Comment by Amejia481** [comment]
👍

**Comment by mcomella** [comment]
I agree with Sebastian's suggestion: I don't want to have to override the
"view" in order to change the padding.
