### ISSUE TITLE
Logging fatal exceptions

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7722]
Since we stopped passing caught exceptions to the default exception handler of the system I no longer see the full stacktrace in the log.

Only when disabling the crash reporter I see them again:
<img width="1108" alt="Screenshot 2020-07-15 at 12 24 06" src="https://user-images.githubusercontent.com/89638/87534292-1badf200-c696-11ea-9a32-a7e65e11f209.png">

We should consider logging the stacktrace ourselves if we do not pass the exception to the system anymore.

**Comment by pocmo** [comment]
CC @rocketsroger Noticed this in Fenix and it was quite annoying. :D

**Comment by rocketsroger** [comment]
Sure, I'll take a look.
