### ISSUE TITLE
Expose more data about why sharing a tab failed

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#7725]
Needed for Fenix -  https://github.com/mozilla-mobile/fenix/issues/10662

I see the call to share a tab getting to [sendCommandToDeviceAsync](https://github.com/mozilla-mobile/android-components/blob/df80cf4173680a77e8e8807975a04f42400bdaa8/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt#L105) and then to a rust call.
Unfortunately `sendCommandToDeviceAsync` returns a boolean so we'd only know if the operation succeeded or not, but in the case it failed, we would not know the reason.

Depending on the fail reason we might want to start a different flow (maybe one for authentication?), use different ux - different error messages, or log errors with better granularity.

**Comment by Mugurell** [comment]
CCing @mhammond and @grigoryk since the changes needed to support this are to be done in A-S.
It would be great if instead of a boolean we would get a bigger payload with both the status and some message, details about the result of the operation.

**Comment by mhammond** [comment]
I think that change would be in the android-components link above - the rust code will throw an exception if it fails, which  sendCommandToDeviceAsync converts to the bool - but IIRC, `handleFxaExceptions` should log the reason and also handle account state reasons, but @grigoryk can tell you more about that.

**Comment by grigoryk** [comment]
@Mugurell take a look at https://github.com/mozilla-mobile/android-components/blob/df80cf4173680a77e8e8807975a04f42400bdaa8/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Utils.kt#L19

This is what happens during that call. In case of auth problems, the account state machine will attempt automatic recovery, and if that fails will switch into a "auth problems" state, which is exposed to the app via AccountObserver events. Currently in Fenix that will trigger a "yellow" account state in the UI.

Most common failures you'll see here are network failures. Other than auth problems, those are the only ones actionable by the user.

We already throw in case we see an "fxa panic" exception. It may be worth it to log `FxaException.Unspecified` to Sentry, that's our only "blind spot" right now here.

**Comment by Mugurell** [comment]
Thank you @grigoryk !

I see though that on iOS some specific failures are logged
- [no tabs were sent](https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/Extensions/NotificationService/NotificationService.swift#L196) (Don't really know how this could happen)
- [account not verified](https://github.com/mozilla-mobile/firefox-ios/blob/76faae8c6c94e22c8fbc0de72e2d06f615738e2c/Extensions/NotificationService/NotificationService.swift#L144)

I understand this granularity is not available atm for Android, but we could log
- general authentication issues
- unknown issues

If you have any other suggestions for events that may help tracking down sync issues/usages feel free to share.

I was thinking also that these kinds of errors should be logged as higher up as possible, not in every client like Fenix, what do you recommend?

**Comment by Amejia481** [comment]
@Mugurell should we close this issue as https://github.com/mozilla-mobile/android-components/commit/8b94efe3963905fc29b5344622b618d2d536257e landed or do we need to add more data? :)

**Comment by Mugurell** [comment]
I was looking into testing this and saw https://github.com/mozilla-mobile/android-components/issues/8877.
With the patch for that and also for https://github.com/mozilla-mobile/fenix/issues/16339 it worked locally so I guess we can close this, thanks!
