### ISSUE TITLE
Migrate AddonManager to WebExtensionRuntime

### ISSUE THREAD

**Issue by keianhzo** [mozilla-mobile/android-components#7726]
The `AddonManager` is still using engine as the WebExtension management entry point:

https://github.com/mozilla-mobile/android-components/blob/732ac7dcbac61d84c709837d324c3ed46186e6c5/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt#L36-L41

Consider migrating it to use `WebExtensionRuntime` so consumers that not implementing the Concept Engine interface can still use it without needing to provide their own `AddonManager` implementation.

**Comment by csadilek** [comment]
@keianhzo ah good catch. Did you want to open a PR for this? Otherwise, I can work on this today.
