### ISSUE TITLE
Surface entrypoint as part of the FxA API

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7729]
In https://github.com/mozilla-mobile/android-components/pull/7694 we're upgrading to a version of A-S which makes `entrypoint` a required part of the APIs that initialize an auth flow.

We now need to sensibly surface this parameter so that applications are able to set it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6687)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794206

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
