### ISSUE TITLE
Run Android Lint on TaskCluster

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#774]
We currently only run `ktlint` on TaskCluster and Travis CI. We should _at least_ run android lint on TC.

This should involve only editing the `.taskcluster.yml` and/or `.travis.yml` files to include `lint` in the gradle command.

**Comment by pocmo** [comment]
We are running lint on taskcluster:
https://github.com/mozilla-mobile/android-components/blob/master/automation/taskcluster/decision_task_pull_request.py#L89

This is now running lint for releases. Do we really want to block a **release** for that?

**Comment by jonalmeida** [comment]
@pocmo whoops, you're right, we probably don't want to! I'll revert this then.
