### ISSUE TITLE
Correct toolbar URL gradient

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#775]
~~There seems to be a problem with the overlay gradient between the URL and the reload button. In the UX spec, the gradient covers just the URL, but in product the gradient also covers and blurs the reload button.~~

The above problem description is not up to date. The actual problem is that there may be an off-by-one error in the bounding box for the gradient: the very last column of pixels in the address bar does not seem to be covered by the gradient.

Ask @st3fan or @mcomella for visuals if needed.

> **It is important that the fix for this issue is also backported to a 0.19.2 release, to minimize risk on the product that currently uses 0.19.1**

**Comment by st3fan** [comment]
@mcomella can you let us know if this is what you want us to work on?

**Comment by mcomella** [comment]
This is correct.

**Comment by Amejia481** [comment]
The issue is only happening in Android API 23.

We found a workaround:

 Avoid to add extra padding to the right on: 
`        toolbar.setUrlTextPadding`

We're investigating if there is something on components that is causing that.
