### ISSUE TITLE
Revise Uri.isUnderPrivateAppDirectory logic when Android 11 is launched

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7750]
On early builds of Android 11 we were seeing that `data/user/0` symlink were not resolved to `data/data` causing the logic of `isUnderPrivateAppDirectory` to not behave as expected for this reason we did some manual check  https://github.com/mozilla-mobile/android-components/pull/7736#discussion_r4559807791, to revise as soon as Android 11 is out.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6705)

**Comment by pocmo** [comment]
Did we find a related bug in the beta bug tracker? Should we file one?

**Comment by Amejia481** [comment]
I filed https://issuetracker.google.com/issues/161486113 on Android 11 issue tracker

**Comment by kanytu** [comment]
I've tested this in a real device and it seems to be an emulator-specific issue. In physical devices, `File("/data/user/0").canonicalPath` is resolving correctly to `/data/data/`.

**Comment by Amejia481** [comment]
Thanks!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795385

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
