### ISSUE TITLE
DisplayToolbar.invalidateActions adds/removes views instead of changing visibility; efficienct? Intuitive?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#776]
https://github.com/mozilla-mobile/android-components/blob/b11f01ca896cde4c25a1b7c94b0f4a5654314773/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt#L232-L240

I wonder if this is efficient? It requires the view to be reallocated and recreated any time the toolbar changes, which can be often.

Similarly, this is unexpected. For example, I'm trying to work around #755 but `setImageTintList` is only applied to views whose images are present at the time it's called: `applyImageTint` is only called when the drawable is set http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/widget/ImageView.java#applyImageTint

**Comment by pocmo** [comment]
The behavior was definitely intended - to be able to permanently add/remove actions. I don't see a performance issue with adding/removing views. However the name `visible()` was chosen poorly. I should have used something like that says **attach**.

We may want to introduce a separate API for visibility. However right now you should be able to implement this yourself by extending the action and overriding `bind` which will be called for every `invalidateActions` call.

**Comment by mcomella** [comment]
> extending the action and overriding bind which will be called for every invalidateActions call.

This is how I worked around this but it took me a while before I realized I could do this. Is there a way we can make this more intuitive to users? If not, we can probably close this because it sounds like it's working as expected.

**Comment by mcomella** [comment]
Closing: we can reopen/revisit if we see this a problem in profiles; we have too many other priorities to dive into every investigation.
