### ISSUE TITLE
Rename BrowserState.queuedDownloads to BrowserState.downloads

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7761]
For supporting the download manger we want to expose all the downloads via the browser store not only the ones that are queued

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6714)

**Comment by Amejia481** [comment]
Additionally we don't want to remove downloads from `BrowserState.downloads` when they are completed lets find all the places where we are dispatching [RemoveQueuedDownloadAction](https://github.com/mozilla-mobile/android-components/blob/a62cb8ff5c972f400ace21fc056fd42a248a1ffe/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt#L580) and not dispatch the action when the download is completed.

**Comment by csadilek** [comment]
This happened :).
