### ISSUE TITLE
Clear mozac_browser_icons resources when clearing private data

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#7766]
Favicon and resources folder are not cleared when clearing private data. This leaks websites that the user visits.

![Annotation 2020-07-18 003815](https://user-images.githubusercontent.com/250273/87847717-27183d80-c88f-11ea-946d-62e25af3e19e.png)

**Comment by pocmo** [comment]
Looks like we need to expose this in `browser-icons`. Currently we only have an internal clear method that we use for unit tests in AC.

I wonder what checkbox in Fenix would map to icons... "Browsing history and site data" or "Cached images and files"?

**Comment by pocmo** [comment]
API is about to land. Filed a Fenix issue for integration:
https://github.com/mozilla-mobile/fenix/issues/12980
