### ISSUE TITLE
Introduce an interface that components can use to provide objects to LeakCanary's objectWatcher

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7775]
By default LeakCanary only detects leaks of Activity, Fragment, View and ViewModel. For custom objects we need to tell LeakCanary that we think that there will be no references to a specific object anymore and then LeakCanary will notify about a leak if this object does not get garbage collected.

For example the SessionManager could notify LeakCanary about a removed `Session` if we expect it to get garbage collected.

Since we do not want to depend on LeakCanary in AC and since apps may not use LeakCanary (or maybe something else) we would want to hide this behind an interface that interested components can depend on.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6725)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793170

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
