### ISSUE TITLE
Android build fails after a fresh clone

### ISSUE THREAD

**Issue by gilbsgilbs** [mozilla-mobile/android-components#7779]
I'm trying to build this project for android after a fresh clone. I followed [these instructions](https://github.com/mozilla/application-services/blob/f5c5a436a1adc9d3599e061f1cc225556b379e79/docs/building.md) but the  `full-megazord:cargoBuildLinux` task failed for the `x86-64` architecture with the following message:

```
> Task :full-megazord:cargoBuildLinux-x86-64 FAILED
   Compiling nss_sys v0.1.0 (/fenix/application-services/components/support/rc_crypto/nss/nss_sys)
error: failed to run custom build command for `nss_sys v0.1.0 (/fenix/application-services/components/support/rc_crypto/nss/nss_sys)`

Caused by:
  process didn't exit successfully: `/fenix/application-services/target/release/build/nss_sys-c32f8f7442e3ee88/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=NSS_DIR

--- stderr
thread 'main' panicked at 'It looks like NSS is not built. Please run `libs/verify-[platform]-environment.sh` first!', components/support/rc_crypto/nss/nss_build_common/src/lib.rs:56:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':full-megazord:cargoBuildLinux-x86-64'.
> Process 'command 'cargo'' finished with non-zero exit value 101
```

It turns out for this specific architecture, [lib.rs](https://github.com/mozilla/application-services/blob/main/components/support/rc_crypto/nss/nss_build_common/src/lib.rs) looks for NSS in `/path/to/application-services/libs/desktop/linux-x86-64/nss` instead of `/path/to/application-services/libs/android/x86_64/nss`. After setting things up for desktop, build can move on. I suppose this happens because the script falls back on dekstop when the target architecture matches the local one 😕 ?

Then the build fails for other unrelated reasons:
```
> Task :logins:compileReleaseKotlin FAILED
e: /path/to/application-services/components/logins/android/src/main/java/mozilla/appservices/logins/DatabaseLoginsStorage.kt: (78, 47): Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

> Task :logins:compileReleaseKotlin FAILED
e: warnings found and -Werror specified
w: /path/to/application-services/components/logins/android/src/main/java/mozilla/appservices/logins/DatabaseLoginsStorage.kt: (429, 45): Extension is shadowed by a member: public final inline fun <U> measure(funcToMeasure: () -> U): U

> Task :places:compileDebugKotlin FAILED
e: /path/to/application-services/components/places/android/src/main/java/mozilla/appservices/places/PlacesConnection.kt: (306, 52): Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

> Task :places:compileDebugKotlin FAILED
e: warnings found and -Werror specified
w: /fenix/application-services/components/places/android/src/main/java/mozilla/appservices/places/PlacesConnection.kt: (1283, 45): Extension is shadowed by a member: public final inline fun <U> measure(funcToMeasure: () -> U): U
```

They are easy to patch, but I wonder why they aren't patched upstream and how people working on this project on a daily basis build this project for Android. Is it supposed to work out of the box? Should I create separate issues/patches for those? Thanks.

**Comment by jonalmeida** [comment]
Hi @gilbsgilbs , this looks like an issue with the build system/instructions with app-services, so I've re-filed your bug there to follow-up on: https://github.com/mozilla/application-services/issues/3383

Thanks for filing a bug!

**Comment by gilbsgilbs** [comment]
Oops, that's my mistake, sorry. Thanks for moving the issue :+1: .
