### ISSUE TITLE
Use App process exit reasons from Android 11 for crash/oom telemetry

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#7783]
This could provide some better info on why the App exits.

https://developer.android.com/preview/features#app-process-exit-reasons

> Android 11 introduces the ActivityManager.getHistoricalProcessExitReasons() method, which reports the reasons for any recent process terminations. Apps can use this method to gather crash diagnostic information, such as whether a process termination is due to ANRs, memory issues, or other reasons. Additionally, you can use the new setProcessStateSummary() method to store custom state information for later analysis.

> The getHistoricalProcessExitReasons() method returns instances of the ApplicationExitInfo class, which contains information related to an app process's death. By calling getReason() on an instance of this class, you can determine why your app's process was killed. For example, a return value of REASON_CRASH indicates that an unhandled exception occurred in your app. If your app needs to ensure uniqueness for exit events, it can maintain an app-specific identifier, such as a hash value based on the timestamp from the getTimestamp() method.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6730)

**Comment by kbrosnan** [comment]
Same bug but at the GV level bz-1664679

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792903

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
