### ISSUE TITLE
Cannot upload immediately after granting storage permission

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#7788]
Reported on Fenix - https://github.com/mozilla-mobile/fenix/issues/11150

## Steps to reproduce
- fresh install so that no permission is granted for the app
- go to a site that allows file uploads (ex: https://viljamis.com/filetest/)
- press the picker button (usually titled "Browse")
- the permission dialog appears, press "Allow" to grant storage permission
- the file picker opens, pick any file

When returning to the website
### Expected behavior
The picked file appears as selected and ready to be upload

### Actual behavior
No file is ready to be uploaded, Browser must be pressed again.

### Device information
Seems like an old issue happening on all devices.

**Comment by sv-ohorvath** [comment]
This was verified in https://github.com/mozilla-mobile/fenix/issues/11150 on Nightly and now on RC 79.0.5 & Beta 80.0.1. I'll close the issue.
