### ISSUE TITLE
Intermittent failure FragmentKtTest. consumeFrom reads states from store

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#7800]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=310557457&repo=android-components

[task 2020-07-21T14:44:59.939Z] SUITE: mozilla.components.lib.state.ext.FragmentKtTest
[task 2020-07-21T14:44:59.939Z]   TEST: consumeFrom does not run when fragment is not added
[task 2020-07-21T14:45:02.339Z]   SUCCESS
[task 2020-07-21T14:45:02.339Z] 
[task 2020-07-21T14:45:02.339Z]   TEST: consumeFrom reads states from store
[task 2020-07-21T14:45:04.339Z]   FAILURE
[task 2020-07-21T14:45:04.339Z] 
[task 2020-07-21T14:45:04.339Z] java.lang.AssertionError
[task 2020-07-21T14:45:04.339Z] 	at org.junit.Assert.fail(Assert.java:86)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.Assert.assertTrue(Assert.java:41)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.Assert.assertFalse(Assert.java:64)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.Assert.assertFalse(Assert.java:74)
[task 2020-07-21T14:45:04.339Z] 	at mozilla.components.lib.state.ext.FragmentKtTest.consumeFrom reads states from store(FragmentKtTest.kt:90)
[task 2020-07-21T14:45:04.339Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-07-21T14:45:04.339Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-07-21T14:45:04.339Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-07-21T14:45:04.339Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2020-07-21T14:45:04.339Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2020-07-21T14:45:04.339Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-07-21T14:45:04.339Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-07-21T14:45:04.339Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-07-21T14:45:04.339Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2020-07-21T14:45:04.339Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2020-07-21T14:45:04.339Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-07-21T14:45:04.339Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-07-21T14:45:04.339Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-07-21T14:45:04.339Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2020-07-21T14:45:04.339Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-07-21T14:45:04.339Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-07-21T14:45:04.339Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[task 2020-07-21T14:45:04.339Z] 	at java.lang.Thread.run(Thread.java:748)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6739)

**Comment by jonalmeida** [comment]
Do we still see this happening?
