### ISSUE TITLE
Fennec migration: Search widget Leanplum pop-up shown on the migration on-boarding screen

### ISSUE THREAD

**Issue by sv-ohorvath** [mozilla-mobile/android-components#7802]
STR:
1. Just install the Fennec to Fenix migration build (Fenix 79.0.0 over Fennec 68.11)
2. Don't close/restart the app, just open it from recent apps.

Expected results:
No pop-up message to cover the migration screen.

Actual results:
This pop-up is displayed while the migration is ongoing. If you tap Add widget it just dismisses it, doesn't actually work.
![1595343809825](https://user-images.githubusercontent.com/4037709/88073838-54ab0280-cb7f-11ea-818b-2f5acb7c5bd1.JPEG)

Build: 79.0.0

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6741)

**Comment by pocmo** [comment]
Hm, this needs to be addressed in Leanplum. @lwa-moz can you help us find someone that can configure this to not run on the first launch?

**Comment by liuche** [comment]
I'll ping mei, and see what her github is.

**Comment by liuche** [comment]
I talked to @cbonacuse and she said that they will be turning off all Leanplum automations this week so that nothing will be running on Leanplum during the migration period. So this should be fixed by the Mobile Engagement team.

**Comment by cbonacuse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Turn Off Fennec Automations](https://trello.com/c/tN3IPjFq/767-turn-off-fennec-automations)

**Comment by liuche** [comment]
hey @cbonacuse I don't think I have access to that board, is there some context from there that you could paste such as a date after which QA could test?

**Comment by st3fan** [comment]
Looping in @jhugman to confirm that this is indeed the result of a campaign and not a code issue.

**Comment by cbonacuse** [comment]
@st3fan & @liuche confirming this was a message from our New User Journey in Leanplum. These have now been turned off in Fennec, so you can retest and should not see that message.
