### ISSUE TITLE
Improve component dependency parsing in taskcluster config

### ISSUE THREAD

**Issue by bhearsum** [mozilla-mobile/android-components#7814]
In #7617 we're doing some pretty hacky parsing of gradle output to determine a component's dependencies, and allow us to optimize away unneeded builds based on the contents of a push or a PR. Eg:
```
    for line in subprocess.check_output(['./gradlew', '%s:dependencies' % component, '--configuration', 'implementation']).splitlines():
        if line.startswith("+--- project"):
            deps.add(line.split(" ")[2])
```

This is pretty hacky, and it would be nicer if we could get something machine readable. @johanlorenzo has a suggestion below:

`gradle` allows us to define custom tasks. We made `printVariants` in Fenix, for instance: https://github.com/mozilla-mobile/fenix/blob/667261f511b7fdd7f45e289502fa7a481512b108/app/build.gradle#L660.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6751)

**Comment by jonalmeida** [comment]
Maybe we could write our own [`DependencyReportRender`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/diagnostics/AbstractDependencyReportTask.html#setRenderer-org.gradle.api.tasks.diagnostics.internal.DependencyReportRenderer-)?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795152

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
