### ISSUE TITLE
Introduce a better strategy for adding A-C changelog entries

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7816]
This is following a discussion on Slack about conflicts in PRs when editing the changelog.

In order to reduce friction when submitting a PR, we run into issues where a changelog entry has conflicts from multiple editos

The idea is solve issues around adding a changelog entry:
 - Reduce the friction for contributors that want to submit a patch but now require to fix conflicts in the patch because of conflicts from a changelog by another PR having recently merged.
 - Changelog entries sometimes end up under the wrong release. This usually happens when an entry was added under a version X, followed by a release for X, a new version Y is added, the PR entry lands under version X instead of Y.
 - It's easy to forget adding a changelog entry when first publishing your changes. The [checklist in our PR template](https://github.com/mozilla-mobile/android-components/blob/master/.github/pull_request_template.md#pull-request-checklist) is a good reminder to do this, but requires you to re-push again to add an entry.
 - Adding meaningful changelog entries - this isn't a quantitative issue: changelog entries can be more meaningful with more examples of code changes .

Some possible solutions discussed:
 - Add a pre-push hook to check if a public API has changed, and fail the push if an edit to the `docs/changelog.md` was not added.
 - Add a build script that extracts a section from a PR format in the opening Pull Request comment that will added to the changelog as part of a pre-merge step from bors.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6753)

**Comment by grigoryk** [comment]
> Add a build script that extracts a section from a PR format in the opening Pull Request comment that will added to the changelog as part of a pre-merge step from bors.

doesn't have to be the opening comment, either - just the first comment which begins with some marker.

**Comment by jonalmeida** [comment]
> doesn't have to be the opening comment, either - just the first comment which begins with some marker.

Yeah, I imagined it would be something like the text between two horizontal lines (`---`) starting with a keyword.

I just realized the overall automation could also fix a small pet peeve I have for ordering the components alphabetically. 😄

**Comment by pocmo** [comment]
Also see #3623 and #954 for previous discussions about that.

**Comment by mcomella** [comment]
(ignore this: commenting so it surfaces in my notifications)

**Comment by jonalmeida** [comment]
> Also see #3623 and #954 for previous discussions about that.

Thanks! The previous discussions suggest that we should go with the second solution since we've tried the route of editing the changelog manually. In the comments for #3623, we can address the concerns to make the changelog richer with the second solution as well.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795071

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
