### ISSUE TITLE
Package Visibility changes in Android 11

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7827]
There are new package visibility changes coming to Android 11 that will limit the access that apps have to information about other apps installed on a device. More [info here](https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6774)

**Comment by Amejia481** [comment]
cc @rocketsroger

**Comment by rocketsroger** [comment]
Looks like the fall back change here is to add the `QUERY_ALL_PACKAGES` permission.  https://developer.android.com/reference/kotlin/android/Manifest.permission#query_all_packages

**Comment by pocmo** [comment]
Do we know if there is any downside to using `QUERY_ALL_PACKAGES`? For the autofill service I need to query some parameters about the calling app from package manager and currently I get blocked by the system on Android 11.

**Comment by mcarare** [comment]
see also: https://github.com/mozilla-mobile/fenix/issues/18223.

**Comment by mcarare** [comment]
See also: https://github.com/mozilla-mobile/focus-android/issues/5334

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793130

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
