### ISSUE TITLE
Break Kinto support into a separate component

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#784]
Currently it's written into fretboard, e.g.:

https://github.com/mozilla-mobile/android-components/blob/d8d31b340217361dc746876bd87ea6d7cd7461e7/components/service/fretboard/src/main/java/mozilla/components/service/fretboard/source/kinto/KintoClient.kt

afaik, Kinto could be used generically to configure clients so it'd be nice to have that functionality available when we need it (blocklists?).

**Comment by st3fan** [comment]
@mcomella do you already have a concrete use-case for it or would you classify this as a future improvement? I think this makes a lot of sense, just trying to understand the priority.

**Comment by mcomella** [comment]
Nothing too specific: PaaS systems these days, like Firebase, are so good and it's frustrating we don't have our own ready-to-use solution for it. Examples where this could come in handy:
- Update Disconnect blocklists via the cloud
- Set up a safe browsing blocklist for devices that don't support the Google/WebView safe browsing APIs yet.

**Comment by pocmo** [comment]
fretboard itself is no longer supported.

Closing this until we have a stronger need for writing such a generic client.
