### ISSUE TITLE
Tab counter should report number of tabs based on its container

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#7852]
After upstreaming the tab counter component from Fenix to AC in https://github.com/mozilla-mobile/android-components/issues/2743, we should look into reporting the correct tab count based on the selected container.

We should also consider the case where all tabs including containers tab are all reported in a single tabs panel.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6796)

**Comment by pocmo** [comment]
Related RB issue: https://github.com/mozilla-mobile/reference-browser/issues/498
(We are showing the count of all tabs and do not distinguish between normal and private tabs.)
