### ISSUE TITLE
Fix dataprotect tests on TaskCluster

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#786]
We currently have a test on `@Ignore` because it fails on TaskCluster with a `javax.crypto.AEADBadTagException`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6801)

**Comment by pocmo** [comment]
I wonder whether this has something to do with OpenJDK (on taskcluster) vs. Oracle JDK (locally?). Or in the past some things required the Java Cryptography Extension JAR to be installed manually?

An alternative would be to run those tests on an actual device (#414).

**Comment by csadilek** [comment]
Duping to https://github.com/mozilla-mobile/android-components/issues/4956. The original test this was filed for doesn't exist anymore, but there are others we have on `@ignore`.
