### ISSUE TITLE
Closing last tab via `browser.tabs.close` leaves stale engine view

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#7868]
This is due the workaround we landed to prevent "white pages": https://github.com/mozilla-mobile/android-components/pull/7759

As we're no longer releasing the engine view and not switching to a different view, the view shows the closed tab's content when it's the last tab.

**Comment by csadilek** [comment]
See also: https://github.com/mozilla-mobile/android-components/issues/7753

**Comment by csadilek** [comment]
@pocmo fix for this specific problem would be to change the workaround so we release the view when there are no more tabs around. This happens as we don't switch views when using `browser.tabs.close`: https://github.com/csadilek/android-components/commit/69c0a76596dbeafbf009912b88690e2eac4f0755

Let's hold back and revisit after we land the refactoring though?

**Comment by pocmo** [comment]
Yeah, we need to investigate this more. Even after not releasing anymore the original problem of random white pages is still reproducible (just less often it seems like). So maybe we can get back to releasing anyways (and fixing the root cause... but I start to think it is in GV).

**Comment by csadilek** [comment]
This will be fixed in https://github.com/mozilla-mobile/android-components/issues/7867.

Specifically by this commit: https://github.com/mozilla-mobile/android-components/commit/fe28146c6f8050da30f7eb4db9674752257cb741
