### ISSUE TITLE
GeckoEngineView HomeActivity memory leak 

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#7871]
┬───
│ GC Root: Global variable in native code
│
├─ org.mozilla.geckoview.GeckoEditable instance
│    Leaking: UNKNOWN
│    ↓ GeckoEditable.mListener
│                    ~~~~~~~~~
├─ org.mozilla.geckoview.GeckoInputConnection instance
│    Leaking: UNKNOWN
│    ↓ GeckoInputConnection.mSession
│                           ~~~~~~~~
├─ org.mozilla.geckoview.GeckoSession instance
│    Leaking: UNKNOWN
│    ↓ GeckoSession.mPromptDelegate
│                   ~~~~~~~~~~~~~~~
├─ mozilla.components.browser.engine.gecko.prompt.GeckoPromptDelegate instance
│    Leaking: UNKNOWN
│    ↓ GeckoPromptDelegate.geckoEngineSession
│                          ~~~~~~~~~~~~~~~~~~
├─ mozilla.components.browser.engine.gecko.GeckoEngineSession instance
│    Leaking: UNKNOWN
│    ↓ GeckoEngineSession.delegate
│                         ~~~~~~~~
├─ mozilla.components.support.base.observer.ObserverRegistry instance
│    Leaking: UNKNOWN
│    ↓ ObserverRegistry.observers
│                       ~~~~~~~~~
├─ java.util.LinkedHashSet instance
│    Leaking: UNKNOWN
│    ↓ LinkedHashSet.map
│                    ~~~
├─ java.util.LinkedHashMap instance
│    Leaking: UNKNOWN
│    ↓ LinkedHashMap.table
│                    ~~~~~
├─ java.util.HashMap$Node[] array
│    Leaking: UNKNOWN
│    ↓ HashMap$Node[].[0]
│                     ~~~
├─ java.util.LinkedHashMap$LinkedHashMapEntry instance
│    Leaking: UNKNOWN
│    ↓ LinkedHashMap$LinkedHashMapEntry.key
│                                       ~~~
├─ mozilla.components.browser.engine.gecko.GeckoEngineView$observer$1 instance
│    Leaking: UNKNOWN
│    Anonymous class implementing mozilla.components.concept.engine.EngineSession$Observer
│    ↓ GeckoEngineView$observer$1.this$0
│                                 ~~~~~~
├─ mozilla.components.browser.engine.gecko.GeckoEngineView instance
│    Leaking: YES (View.mContext references a destroyed activity)
│    mContext instance of org.mozilla.fenix.HomeActivity with mDestroyed = true
│    View#mParent is set
│    View#mAttachInfo is null (view detached)
│    View.mID = R.id.engineView
│    View.mWindowAttachCount = 1
│    ↓ GeckoEngineView.mContext
╰→ org.mozilla.fenix.HomeActivity instance
​     Leaking: YES (ObjectWatcher was watching this because org.mozilla.fenix.HomeActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     key = a0792e3d-a769-405c-8831-3a53a538b6f7
​     watchDurationMillis = 57798
​     retainedDurationMillis = 52798

METADATA

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Google
LeakCanary version: 2.4
App process name: org.mozilla.fenix.debug
Analysis duration: 21686 ms

**Comment by pocmo** [comment]
This should already be fixed. After https://github.com/mozilla-mobile/android-components/commit/cbbc80e8b8707167e12fe801a3d4c9f797d7bc12#diff-10dcc2790844034d137c9b6d5cedf429 landed in AC we no longer register an `EngineSessionObserver` in `GeckoEngineView`.
