### ISSUE TITLE
Invalidate a thumbnail if a page origin changes and we're not the selected session

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7872]
This needs more investigation to avoid potential UI bugs: if a page takes long to load when we leave a tab, our tabs tray will show an out of date thumbnail with the page title of a different page.

## STR (in Fenix)
 - Load page abc.com
 - Load page xyz.com and before the page is done loading, switch tabs.
 - Open the tabs tray.
 - Observe the title change's to that of XYZ, but we still show the screenshot of ABC.

![image](https://user-images.githubusercontent.com/1370580/88593832-22d9e600-d02e-11ea-8bab-4520403b164b.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6822)

**Comment by pocmo** [comment]
Didn't we initially clear the thumbnail on location changes?

Do we know what the behavior in Fennec was?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796253

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
