### ISSUE TITLE
Possibly incorrect handling of persisted engine state during closely spaced, subsequent syncs

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7874]
Splitting from https://github.com/mozilla-mobile/android-components/issues/7335, in which @mhammond notes:

> I believe that the persisted state for syncing was fetched at the time the sync call was queued, not when it was executed. So if there's one sync running and one sync queued, and the first sync changes (say) the declined engines, it seems likely that second sync will execute with the old state, not new state as updated by that first sync.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6823)

**Comment by mhammond** [comment]
To be clear, the reason I "believe" that is due to the observed behaviour, not from evidence. IOW, if the state was re-fetched after the sync completed, things should be capable of syncing immediately and forever without observing this specific behaviour.

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794224

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
