### ISSUE TITLE
Remove info logging for SearchEngineMigrationResult

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7876]
We send telemetry for those and that is the only important metric to look at (overall success rate). The individual log messages in Sentry are not helping us.

* https://sentry.prod.mozaws.net/share/issue/e02aae082d0f404d817fc49cdb20dbbd/
* https://sentry.prod.mozaws.net/share/issue/f854493cd8624c1b805d65d554eb0552/

**Comment by ebalazs-sv** [comment]
Confirmed with pocmo, that this issue is not to be verified and will be visible after the rollout, since it makes the error messages better in Sentry.
