### ISSUE TITLE
OutOfMemoryError: SnapshotSerializer.toJSON

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7886]
We have the following issue for `restore()`:
https://github.com/mozilla-mobile/android-components/issues/3909

Of course the same problem can happen for the write, and that is the issue here.

**Comment by pocmo** [comment]
https://sentry.prod.mozaws.net/share/issue/30ed982e3ff64746b0f4481641ae1146/

**Comment by liuche** [comment]
we're doing a crash sprint, so will sync up to see if there is any division of work that can happen? @eliserichards

**Comment by pocmo** [comment]
Moving this into the next AC sprint.

Planning to write two patches here:
* Catch and log OutOfMemoryError. Forward crash to Sentry. (Needs `CrashReporting` instance from Fenix)
* Rewrite `SessionStorage.save()` to write JSON directly to the file stream without building a JSON model in memory first.
