### ISSUE TITLE
IllegalStateException: No camera found on device

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#7893]
In theory, apps should check if the device has a camera using our extension function `Context.hasCamera`. Looks like in Fenix we forgot to do that for the `PairFragment` and we're seeing quite a few crashes: https://github.com/mozilla-mobile/fenix/issues/13037

We could handle the exception and show an empty screen / log instead.

**Comment by LaurentiuApahideanSV** [comment]
Verified as fixed on Release migration 79.0.1 (Build #2015755155) GV 79 from 7/31 on the following emulators with the camera disabled: Nexus 6P (Android 8.1), wsvga tablet (Android 5.1), Google Pixel C (Android 10).

**Comment by sv-ohorvath** [comment]
Double-checked on 80.0-beta3 and no issues found.
