### ISSUE TITLE
Add a space after appending search term to the search bar

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#7895]
When we landed https://github.com/mozilla-mobile/android-components/pull/6824, clicking the append button added a new space every time.

We should re-add this part of the feature without that bug. See: https://github.com/mozilla-mobile/android-components/pull/6824#discussion_r460235082

cc: @cypressious

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6848)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796454

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
