### ISSUE TITLE
Consider switching AutoPushFeature.Observer functions to be suspend

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7899]
This will probably let us clean up some suspend context switching, e.g. https://github.com/mozilla-mobile/android-components/pull/7856#discussion_r461870287

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6852)

**Comment by grigoryk** [comment]
cc @jonalmeida

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796426

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
