### ISSUE TITLE
Migration telemetry settings 

### ISSUE THREAD

**Issue by vesta0** [mozilla-mobile/android-components#7917]
If a Fennec user has disabled FHR in their privacy settings, we want to disable all 3 telemetry options (usage & technical data, marketing data, experiment) in Fenix during the migration.

**Comment by ebalazs-sv** [comment]
Verified as fixed on Release migration 79.0.1 (Build #2015755155) GV 79 from 7/31 with Pixel 2 (Android 9), Huawei MediaPad M3 lite (Android 7) and when the FHR from Privacy setting in Fennec is disabled, after migration, all the Data collection options (Usage and technical data, Marketing data, Experiments) are disabled.
