### ISSUE TITLE
Firefox offers to open the Play Store for a given intent: URL, while Chrome redirects to another page

### ISSUE THREAD

**Issue by wisniewskit** [mozilla-mobile/android-components#7930]
As seen in https://github.com/webcompat/web-bugs/issues/55998, Firefox seems to not be falling back to the same URL Chrome does for this `intent:` link:
```
intent://hotel/Jetwing Blue/247454?adults=2&af_deeplink=true&af_dp=agoda%3A%2F%2Fhotel%2FJetwing%20Blue%2F247454&af_force_dp=true&af_r=https%3A%2F%2Fwww.agoda.com%2Fjetwing-blue%2Fhotel%2Fnegombo-lk.html&af_web_id=f975673a-6824-4be6-8d07-cdf13ee6314a-o&campaign=Property_Sharing&checkIn=2020-08-02&checkOut=2020-08-03&childs=0&cid=1770664&los=1&media_source=Mobile_App&rooms=1&site_id=1770664#Intent;scheme=agoda;package=com.agoda.mobile.consumer;S.browser_fallback_url=https://www.agoda.com/jetwing-blue/hotel/negombo-lk.html?childs=0&af_dp=agoda%253A%252F%252Fhotel%252FJetwing%2520Blue%252F247454&los=1&checkOut=2020-08-03&pid=Mobile_App&adults=2&cid=1770664&checkIn=2020-08-02&c=Property_Sharing&rooms=1&site_id=1770664;S.market_referrer=af_tranid%3Dwnb_-PURtEzhwA4a81lsqA%26af_r%3Dhttps%3A%2F%2Fwww.agoda.com%2Fjetwing-blue%2Fhotel%2Fnegombo-lk.html%26childs%3D0%26af_dp%3Dagoda%253A%252F%252Fhotel%252FJetwing%2520Blue%252F247454%26los%3D1%26checkOut%3D2020-08-03%26pid%3DMobile_App%26adults%3D2%26af_web_id%3Df975673a-6824-4be6-8d07-cdf13ee6314a-o%26cid%3D1770664%26checkIn%3D2020-08-02%26c%3DProperty_Sharing%26rooms%3D1%26site_id%3D1770664;l.appsflyer_click_ts=1596134718926;end
```

That is, Chrome redirects to `https://www.agoda.com/jetwing-blue/hotel/negombo-lk.html?childs=0&af_dp=agoda%3A%2F%2Fhotel%2FJetwing%20Blue%2F247454&los=1&checkOut=2020-08-03&pid=Mobile_App&adults=2&cid=1770664&checkIn=2020-08-02&c=Property_Sharing&rooms=1&site_id=1770664`, while Firefox shows a blank page and offers to open the Play Store.

**Comment by rocketsroger** [comment]
Looks like this is a use case where the app is not installed but we have both the market intent and fallback URL.  My original thought was that if there is a market intent we should always take the user to the market app.  However, that is the wrong assumption.  Fallback URL should be used if the user preference is not to launch in external app.  I'll fix this.
