### ISSUE TITLE
Support dynamic width in menu2

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#7932]
Menu1 issue: #3703

This feature was added to menu1 but not ported to menu2. Allows for a menu's width to be set by the content instead of being hard coded.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6874)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793142

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
