### ISSUE TITLE
Allow to store the user's preferred app when downloading a file with a third party

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#7943]
Our [current implementation allows the user to select which app they want to use for downloading a file](https://drive.google.com/file/d/1ytdoSFvwHAusvYN8Cqh7PiTf7r6tDrMT/view?usp=sharing), but[ Fennec offered an additional functionality](https://drive.google.com/file/d/1JMbQ_ac46xGGLv6OD2GVyeJ_p3e8Lqf0/view?usp=sharing), it allowed the user to select and save this app as the preferred option for downloading this type of files in the future, that means when the user tries to download a similar type of file this app will automatically be selected without showing the dialog.  We didn't implement this functionality as Fennec never exposed a UI for changing the preferred app to be used with an specific file type, leaving the user with only one preferred app per file type for ever, we need user feedback to know how the UI for managing the preferred app per file type should look like and implement that functionality.

- [Fennec implementation](https://drive.google.com/file/d/1JMbQ_ac46xGGLv6OD2GVyeJ_p3e8Lqf0/view?usp=sharing)
- [AC feature](https://drive.google.com/file/d/1ytdoSFvwHAusvYN8Cqh7PiTf7r6tDrMT/view?usp=sharing)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6882)

**Comment by Daplugg23** [comment]
@Amejia481 **preferred** is misspelled in the title.

**Comment by Amejia481** [comment]
Thanks @Daplugg23 fixed :)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792939

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
