### ISSUE TITLE
Leaving the pairing flow before its full completion results in a crash

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#7944]
Split from https://github.com/mozilla-mobile/android-components/issues/7536#issuecomment-667049532

Reported by @Diana-Rus :
As long as you leave the "Approval now required" page, after a second or two and before on desktop is displayed "Firefox Account is connected with Firefox for Android."

Crash link - Samsung Galaxy S9 (Android 8): https://crash-stats.mozilla.org/report/index/25257b31-c0f6-49ec-9892-2b4df0200731
Crash link - google Pixel 3 XL (Android 9): https://crash-stats.mozilla.org/report/index/b4d6be88-4130-4bf7-96cb-e4b8d0200731

Same STR, exception is the timing in step 6:

1. Open browser go to Settings/ Sign in with a QR code.
2. Tap on the "Allow" button from the dialog box.
3. On Firefox Nightly desktop go to firefox.com/pair and tap on the "Show code" button.
4. Scan the provided QR code.
5. Confirm pairing on both mobile and desktop.
6. Leave "Approval now required" page by tapping on deivce back button, after 1 or 2 seconds.
7. Go to Settings/Synced tabs.
8. Wait a couple of seconds.

**Comment by grigoryk** [comment]
We're hitting https://github.com/mozilla-mobile/android-components/issues/2437 here. The PR fixes the affected observers to run on the main thread, but we need a more holistic solution for this.

**Comment by Diana-Rus** [comment]
Hi, didn't encounter any crash on Firefox 79.0.2, AC: 48.0.12, verified with:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3 XL (Android 9) 
- Sony Xperia Z5 (Android 7)

**Comment by Diana-Rus** [comment]
While testing this on 80.0.0-beta.3 a new crash has been encountered, similar to this one agreed with @pocmo that a new ticket should be created for tracking the crash #8036 .
