### ISSUE TITLE
Redefine type for SearchEngine

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#7946]
Ref: https://github.com/mozilla-mobile/android-components/pull/7929#discussion_r463561092

Current `SearchEngine` structure in `browser-state` has a `type` property to differentiate between custom and provided default search engines. This results in type-specific actions/operations (i.e. `UpdateCustomSearchEngineAction`) having to taken in generic `SearchEngine` as a parameter. This can get confusing and cause potential overhead for having to reference internal type property.

**Comment by pocmo** [comment]
For now the `type` parameter seems good enough.
