### ISSUE TITLE
Add a Setup/FAQ guide

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#796]
We should create a getting started or FAQ for new contributors to easily get ready. This can mostly be a document outlining different situations and how to fix them, but it would be nice to also have configurations that auto-apply to follow our requirements for a patch.

A list of things to add:
- [x] Pre-push hooks
  - Add `./gradlew ktlint detekt`.
- [ ] ~Test locally using `-Pcoverage` flag to make sure coverage is at an acceptable rate.~ Already exists, point to the doc [here][2].
- [ ] `ktlint` formatting enabled in the project by default.
  - [ ] Also include a section for `ktlint --apply-to-idea-project --android` if needed.
- [ ] (Optional) apply our formatting on a patch as a pre-commit change if it's easier.
- [ ] Naming of tests to follow the convention (use backticks with descriptive names) unless a test file already follows the old format (e.g. `fun test*()`).
  - Write a lint check for it!
- [ ] #846 New files added should have the license headers on top.
  - Write a lint check for it!
- [ ] Restarting TaskCluster if a build fails due to intermittent issues.
  - This should go away if we fix the root cause of this issue (caching dependencies).
- [ ] Add a contributing work flow guide (e.g. create an issue first explaining the problem, then create a PR).
  - Refer to [this guide][1] as well.
- [ ] Squash commits.
  - ~Can this be a pre-push hook?~ Can this be a pre-push reminder message incase someone forgets (without being obstructive)?

[1]: https://github.com/mozilla-mobile/shared-docs/blob/master/android/CONTRIBUTING.md
[2]: https://mozilla-mobile.github.io/android-components/contributing/code-coverage

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6902)

**Comment by pocmo** [comment]
> Pre-push hooks 

Firefox for Fire TV keeps the script for the hook inside the repository, which is quite nice:
https://github.com/mozilla-mobile/firefox-tv/blob/master/quality/pre-push-recommended.sh

> Test locally using -Pcoverage

This is mentioned here:
https://mozilla-mobile.github.io/android-components/contributing/code-coverage

> Naming of tests to follow the convention (use backticks with descriptive names) unless a test file already follows the old format (e.g. fun test*()).

If possible we should add an automated check for that - so that PRs fail automatically.

>  New files added should have the license headers on top. 

An automated check for that would be nice too. :)

> This should go away if we fix the root cause of this issue (caching dependencies).

I filed #844 and https://bugzilla.mozilla.org/show_bug.cgi?id=1493626

I'll also work on getting #641 in.

> Squash commits.
> - Can this be a pre-push hook?

That's not **always** desired though.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795073

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
