### ISSUE TITLE
Correcting built-in search engine (DIEC) for Catalan

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/android-components#7963]
The Catalan localizer has reached out to l10n-drivers, as it seems the current search engine for Catalan is not working.
The search engine is DIEC2.
**Wrong URL:** https://dlc.iec.cat/?txtEntrada=|{searchTerms}|&operEntrada=0
**Correct URL:**
https://dlc.iec.cat/results.asp?txtEntrada=|{searchTerms}|&OperEntrada=0

More info from Axel: 
The engine is in a-c:
https://github.com/mozilla-mobile/android-components/blob/master/components/browser/search/src/main/assets/searchplugins/diec2.xml.
Maybe a redirect on the site broke? As it's using the `mdlc` host (note the leading `m`).

**Comment by Pike** [comment]
Yeah, I think this just needs the removal of the `m` in the engine.

**Comment by jordis** [comment]
> 
> 
> Yeah, I think this just needs the removal of the `m` in the engine.

I agree. I went ahead and removed the `m` in the engine in pull request https://github.com/mozilla-mobile/android-components/pull/8111
I'm not sure whether pull request this is the right way to go. Apologies if it is not.

**Comment by Delphine** [comment]
This has been fixed
