### ISSUE TITLE
Intermittent test task failure: [taskcluster:error] Task timeout after 2400 seconds. Force killing container.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#7970]
Log with failure: https://treeherder.mozilla.org/logviewer.html#?job_id=312031091&repo=android-components

[task 2020-08-04T19:15:31.796Z]   3m 50s matrix-2qpukqas88rsc Nexus6-21 Retrieving Post-test Package Stats information from the device.
[task 2020-08-04T19:15:31.796Z]   3m 50s matrix-2qpukqas88rsc Nexus6-21 Logging out of Google account on device.
[task 2020-08-04T19:15:31.796Z]   3m 50s matrix-2qpukqas88rsc Nexus6-21 Stopped logcat recording.
[task 2020-08-04T19:15:31.796Z]   3m 50s matrix-2qpukqas88rsc Nexus6-21 Done. Test time = 12 (secs)
[task 2020-08-04T19:15:31.796Z]   3m 50s matrix-2qpukqas88rsc Nexus6-21 Starting results processing. Attempt: 1
[task 2020-08-04T19:15:36.931Z]   3m 56s matrix-2qpukqas88rsc Nexus6-21 Completed results processing. Time taken = 3 (secs)
[task 2020-08-04T19:15:36.931Z]   3m 56s matrix-2qpukqas88rsc Nexus6-21 FINISHED

[taskcluster:error] Task timeout after 2400 seconds. Force killing container.
[taskcluster 2020-08-04 19:32:36.497Z] === Task Finished ===
[taskcluster 2020-08-04 19:32:36.498Z] Unsuccessful task run with exit code: -1 completed in 2425.656 seconds

In the log of a successful task, this follows:
> 4m  5s matrix-o93lv91lyrepa FINISHED

Successful log: https://treeherder.mozilla.org/logviewer.html#?job_id=312020862&repo=android-components

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6917)

**Comment by rpappalax** [comment]
see also: [Intermittent fenix ui-test-x86 [taskcluster:error] Task timeout after 7200 seconds. Force killing container.](https://bugzilla.mozilla.org/show_bug.cgi?id=1619060
may be related)

**Comment by jonalmeida** [comment]
Not new reports for a while. Re-open if they return. This is also tracked on the linked bugzilla above.
