### ISSUE TITLE
Intermittent task hang Exception in thread "DefaultDispatcher-worker-3" java.lang.NoClassDefFoundError: Could not initialize class kotlinx.coroutines.CoroutineExceptionHandlerImplKt

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#7974]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=312031886&repo=android-components

[task 2020-08-04T19:04:14.535Z]   TEST: broadcastReceiver handles ACTION_TRY_AGAIN
[task 2020-08-04T19:04:14.535Z]     [Robolectric] mozilla.components.feature.downloads.AbstractFetchDownloadServiceTest.broadcastReceiver handles ACTION_TRY_AGAIN: sdk=28; resources=binary
[task 2020-08-04T19:04:14.535Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-08-04T19:04:14.535Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@167446a9', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@167446a9'
[task 2020-08-04T19:04:14.535Z]     D [AbstractFetchDownloadService] Starting download for https://example.com/file.txt
[task 2020-08-04T19:04:14.535Z]     D [AbstractFetchDownloadService] Fetching download for https://example.com/file.txt
[task 2020-08-04T19:04:14.535Z]     D [AbstractFetchDownloadService] verifyDownload for https://example.com/file.txt COMPLETED
[task 2020-08-04T19:04:14.535Z]     D [AbstractFetchDownloadService] ACTION_TRY_AGAIN for https://example.com/file.txt
[task 2020-08-04T19:04:14.535Z]     D [AbstractFetchDownloadService] Starting download for https://example.com/file.txt
[task 2020-08-04T19:04:14.535Z]     D [AbstractFetchDownloadService] Fetching download for https://example.com/file.txt
[task 2020-08-04T19:04:14.535Z]     D [AbstractFetchDownloadService] starting copyInChunks https://example.com/file.txt currentBytesCopied 0
[task 2020-08-04T19:04:49.535Z]     Exception in thread "DefaultDispatcher-worker-3" java.lang.NoClassDefFoundError: Could not initialize class kotlinx.coroutines.CoroutineExceptionHandlerImplKt
[task 2020-08-04T19:04:49.535Z]     at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
[task 2020-08-04T19:04:49.535Z]     at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:95)
[task 2020-08-04T19:04:49.535Z]     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
[task 2020-08-04T19:04:49.535Z]     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[task 2020-08-04T19:04:49.535Z]     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
[task 2020-08-04T19:04:49.535Z]     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[task 2020-08-04T19:04:49.535Z]     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

[taskcluster:error] Task timeout after 1200 seconds. Force killing container.
[taskcluster 2020-08-04 19:21:45.388Z] === Task Finished ===

**Comment by jonalmeida** [comment]
@Amejia481 do you think this should be closed since there have been many changes in downloads since we last saw this?

**Comment by jonalmeida** [comment]
Looks like it might be related to: https://github.com/mozilla-mobile/android-components/issues/8091

**Comment by Amejia481** [comment]
I will take a quick look at it later in the day, to check if we can close this! :)

**Comment by jonalmeida** [comment]
🦗 

Sounds like we can close it. :)
