### ISSUE TITLE
MediaService: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#7984]
```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{98e2814 u0 org.mozilla.firefox/org.mozilla.fenix.media.MediaService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:198)
    at android.app.ActivityThread.main(ActivityThread.java:6729)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

We **always** call startForegroundService and immediately with the first state:
https://github.com/mozilla-mobile/android-components/blob/master/components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaServiceDelegate.kt#L106

This could be a side effect from a blocked UI thread (ANR) and not a problem with our code.

**Comment by jonalmeida** [comment]
I've run into this a few times last week in R-B when scrolling through auto-playing media sites like Instagram.

R-B sentry issue: https://github.com/mozilla-mobile/reference-browser/issues/1384

**Comment by rocketsroger** [comment]
> I've run into this a few times last week in R-B when scrolling through auto-playing media sites like Instagram.
> 
> R-B sentry issue: [mozilla-mobile/reference-browser#1384](https://github.com/mozilla-mobile/reference-browser/issues/1384)

You're seeing this issue with the new Media Session API implementation.  It will be fixed with https://github.com/mozilla-mobile/android-components/issues/9086

**Comment by rocketsroger** [comment]
The fix will be in the new MediaSession API implementation.  Closing this as won't fix since we will be switching to the new implementation soon.
