### ISSUE TITLE
GeckoEngine: Remove try/catch block in automaticFontSizeAdjustment 

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8005]
For the crash in https://github.com/mozilla-mobile/android-components/issues/7922 we added a temporary try/catch block to `GeckoEngine`:
https://github.com/mozilla-mobile/android-components/commit/f3e91d4e038927395cb21d5c7fae9607f0a1fec1

Since the GeckoView team fixed this issue in Nightly (https://bugzilla.mozilla.org/show_bug.cgi?id=1656078) we can now remove this workaround from `browser-engine-gecko-nightly`.

**Comment by pocmo** [comment]
@Bawya1098 Great! 👍 Do you need any further hints? :) Make the changes as described in the first comment (removing the try/catch block from `GeckoEngine` in `components/browser/engine-gecko-nightly` (watch out there are others in different folders that we do not need to change) and then open a pull request referencing this issue. :)

**Comment by Aditya-Srivastav** [comment]
Does it still needs help ?
I would like to do this one .

**Comment by pocmo** [comment]
Yes, this still needs to be done. :) Do you need any help? :)

**Comment by Aditya-Srivastav** [comment]
Hey, 
Can you help me with the checks , I have removed the try catch and the checks are failing .
Would love to make any required changes. Thanks  **;D**
