### ISSUE TITLE
Add 36dp icons

### ISSUE THREAD

**Issue by aminalhazwani** [mozilla-mobile/android-components#802]
For Amazon products we need larger Android icons, this PR https://github.com/FirefoxUX/photon-icons/pull/38 adds the minimum necessary to move the project forward. Once the PR is merged you can pull the latest icons into `android-components`. We will add the missing 36dp icons later on.

**Comment by aminalhazwani** [comment]
Hey @pocmo thanks for the feedback, I think that scaling dynamically makes sense but only when the screen density allows it. The android icons were originally drawn at 20x20dp in a 24x24dp bounding box, and the icon stroke was set to 2dp, here an example:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/1721875/45880811-7f707800-bda9-11e8-80b1-f261e5499117.png">

For the Echo Show we had to scale the bounding box up to 36x36dp, so by 1.5x factor. This scaling makes the icon 30x30dp large and the sets the stroke to 3dp.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1721875/45880988-0f162680-bdaa-11e8-9de5-d4b8a3f2dac8.png">

But a simple scale would not snap the icon to the pixel grid - see half pixel in the image above - and on the 72dpi Echo Show screen would display the icon blurred. So that's why we had to redraw them at 36x36dp and align the 30dp icon to the pixel grid.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/1721875/45881164-ad09f100-bdaa-11e8-8029-082120bef7b0.png">
 
Here another example:

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1721875/45881360-3faa9000-bdab-11e8-8316-82d8a8499cad.png">

And here the pixel preview:

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/1721875/45881411-5f41b880-bdab-11e8-9f73-94fbaed327c3.png">

**Comment by pocmo** [comment]
@aminalhazwani Ah. Thanks for the explanation! :)
