### ISSUE TITLE
Add 'remove' and 'contains' operations to EditToolbar

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla-mobile/android-components#8034]
This is required for a Fenix ticket: https://github.com/mozilla-mobile/fenix/issues/12617, in order to be able to switch between two actions on the `EditToolbar`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6953)

**Comment by csadilek** [comment]
Closing based on https://github.com/mozilla-mobile/android-components/pull/8035#discussion_r466955769.
