### ISSUE TITLE
[Regression] Crash when pairing flow is interrupted

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-mobile/android-components#8036]
## Steps to reproduce:
1. Open browser go to Settings/ Sign in with a QR code.
2. Tap on the "Allow" button from the dialog box.
3. On Firefox Nightly desktop go to firefox.com/pair and tap on the "Show code" button.
4. Scan the provided QR code.
5. Confirm pairing on both mobile and desktop.
6. Leave "Approval now required" page by tapping on device back button, after 1 or 2 seconds.
7. Go to Settings/Synced tabs.
8. Wait a couple of seconds.

### Actual Result: Crash is displayed.

Crash link - Samsung Galaxy S9 (Android 8): https://crash-stats.mozilla.org/report/index/8b6f7540-bd9f-4b80-ac04-8cc450200806
Crash link - Google Pixel 3XL (Android 9): https://crash-stats.mozilla.org/report/index/73d7cd8c-68e0-4108-9398-744fe0200806

Note:
- Similar STR's as for #7536 and #7944
- For step 6 - As long as you leave the "Approval now required" page, after a second or two and before on desktop is displayed "Firefox Account is connected with Firefox for Android."

Firefox Build:  Firefox Beta 80.0.0-beta.3

**Comment by grigoryk** [comment]
This is a dupe of https://github.com/mozilla-mobile/android-components/issues/7944

**Comment by liuche** [comment]
This didn't get picked up in the 52.0.1 AC release, but it's in the 52.0.2 AC that we're picking up right now!

**Comment by Diana-Rus** [comment]
Hi, didn't encounter any crash on Firefox Beta 80.0.0-beta.4 (AC: 52.0.2) and Nightly 8/7 AC: 53.0.20200804130112, with the STR's from description verified with:
- Samsung Galaxy S9 (Android 8)
- Google Pixel 3 XL (Android 9)
- Sony Xperia Z5 (Android 7)
