### ISSUE TITLE
Add RequestInterceptor handling of SSL errors

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#804]
FireTV need to handle SSL errors separately from regular errors (e.g. Telemetry for SSL errors).

Currently, we combine the `WebView#onReceivedError` and `WeView#onSslError` and make a single interceptor call with `RequestInterceptor#onErrorRequest`.

The problem with this is that the constant error values for WebView _can_ overlap with [`SslError`][0] if they start using them.

I don't currently have one solution. It could be that we can separate `onErrorRequest` into two callbacks and have GeckoView's single error callback split into those two. Or we could do the opposite, by multiplexing SslError and WebView errors into one errorCode.

In both solutions we would also need to map into a unified errorCode to work with GeckoView.

[0]: https://developer.android.com/reference/android/net/http/SslError

**Comment by pocmo** [comment]
Afaik we agreed on not sending the SSL telemetry anymore?

**Comment by pocmo** [comment]
Looks like this is not needed anymore.
