### ISSUE TITLE
Move ImageLoader API to a concept component

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8040]
The `ImageLoader` API is shared between `browser-thumbnails` and `browser-icons` but requires consumers to explicitly include `support-images` to use things like `browser-tabstray`.

We should try to move this to a concept component. Maybe `concept-base`?

**Comment by jonalmeida** [comment]
cc @pocmo for reference ❄️ 🐜

**Comment by pocmo** [comment]
Great :) 👍
