### ISSUE TITLE
Refactor feature-applinks to use Browsers for finding browsers intents

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8041]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6961)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793129

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
