### ISSUE TITLE
AddonCollectionProvider hardcodes "mozilla" as the collection owner, limiting reusability

### ISSUE THREAD

**Issue by interfect** [mozilla-mobile/android-components#8051]
Right now, the `AddonCollectionProvider` allows overriding the server URL and collection name, but it hardcodes `mozilla` as the account that owns the collection it reads from:

https://github.com/mozilla-mobile/android-components/blob/f5d1ecc9c13bb5ff30b039f4e5607f678fc9cfb9/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AddonCollectionProvider.kt#L84

The hardcoded `mozilla` should be replaced by a `DEFAULT_COLLECTION_ACCOUNT` constant, and a `collectionAccount` constructor argument that defaults to it.

This is important because otherwise, to ship an `android-components`-based browser with a different list of supported extensions than the default in `android-component` of just uBlock Origin, you have to do one of:
* Be Mozilla
* Host the list on your own server and pretend to be Mozilla there
* Reimplement `AddonCollectionProvider` or your own `AddonsProvider` implementation from scratch

Fixing this would add another option: create your own collection on the real AMO under a non-Mozilla user account, and point `AddonCollectionProvider` at it.

**Comment by csadilek** [comment]
I will close this and land in a new PR that also makes the account and ID mutable for debugging/testing purposes.
