### ISSUE TITLE
UX changes for addons - unsupported item

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#8054]
Based on @brampitoyo's comment from https://github.com/mozilla-mobile/fenix/issues/8578#issuecomment-652167232
and
https://app.abstract.com/share/28d0811b-ffed-4863-89c8-8aaa10acb528?mode=build&selected=3739771863-5D69D8D0-1838-4F55-B7BA-6EE363185D86&sha=e00d4f002ecef58f001903d9111f95b864daa8ae\
we need the following changes:
- use the same style as for the other favicons - [Mozac.Widgets.Favicon](https://github.com/mozilla-mobile/android-components/blob/297ed9f1fdbce91c934de824af412df2934c8074/components/ui/widgets/src/main/res/values/styles.xml#L37)
- ensure the addon icon has 24 dp width/height and uses the same glyph as the other addons icons used in menus, one that has inherent padding.
- ensure the remove icon has 20dp height.
`mozac_ic_delete` [actually has a 24dp size set](https://github.com/mozilla-mobile/android-components/blob/daa3595a9130d3b28f0fea64d5094762be2abd58/components/ui/icons/src/main/res/drawable/mozac_ic_delete.xml) but also an innate padding so it can be used as is.

**Comment by brampitoyo** [comment]
@Mugurell Sorry to change the icon spec one more time. Our add-ons icon should follow the same guidelines as favicons (see https://github.com/mozilla-mobile/fenix/issues/7992).

Unfortunately, in the past, favicons look different on Top Sites, Bookmarks, History and Search Results. Sometimes they have a square background, or round background, or sometimes they have no background at all.

Now that the specs have been unified, we should follow it.

**Comment by Mugurell** [comment]
To be verified in Fenix - https://github.com/mozilla-mobile/fenix/issues/8578
