### ISSUE TITLE
Addon manager: add addon collection setting to about:config

### ISSUE THREAD

**Issue by dbenjaminmiller** [mozilla-mobile/android-components#8058]
If I'm not mistaken, the addons collection which is consulted to produce the list of addons for the addons manager is currently hardcoded in; in order to add another addon to the manager, one presently needs to modify that in the android-components side in order to change it in the product. This makes things harder for those who are rolling out a browser which should be polling a different collection, and those users of browsers who want to change the collection to enable easier testing of addons which they know are supported (or which they can guarantee on their own basis).

So, to remedy this, the collection URL which is polled by the addons manager — and which (I believe, correct me if I'm wrong) provides both the list of installable addons and the internally-used list of compatible addons (which determines if an addon installed even temporarily via `web-ext` or via migration is listed in the incompatible addons list) can be set by the addon developer wishing to test who has a knowledge of `about:config`, or by the browser developer who wishes to change the default list (say, in order to add a set of corporate addons to an internal-user browser) without having to modify `android-components`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6976)

**Comment by csadilek** [comment]
A-C has API to configure the collection, and consuming application can set it at runtime e.g., based on a build flag: https://github.com/mozilla-mobile/fenix/blob/main/app/build.gradle#L50

We don't intend to expose this via about:config.
