### ISSUE TITLE
android-components/automation/publish_to_maven_local_if_modified.py does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by interfect** [mozilla-mobile/android-components#8072]
The `android-components/automation/publish_to_maven_local_if_modified.py` script, required to build Fenix with a modified `android-components`, crashes on Ubuntu 18.04, where the default Python 3 is only Python 3.6. The `capture_output` keyword argument it uses has not yet been introduced in the Python 3.6 version of Subprocess.

Either the script needs to be backported to Python 3.6, or the script needs a `#!/usr/bin/env python3.7` shebang to articulate what Python it needs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-6988)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795400

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
