### ISSUE TITLE
Grouped download notification should be dismissable if all downloads are completed.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8073]
When downloading multiple files then we group the notifications together on newer Android versions. When all downloads are completed then the notification is still not dismissable. This can get quite annoying because with that you need to expand the notification and dismiss every child notification.

**Comment by Amejia481** [comment]
This was addressed on https://github.com/mozilla-mobile/android-components/commit/4c7ff86d01d6a4f0a98d05070bd10fdfff9843d9 :)
