### ISSUE TITLE
AddonCollectionProvider can only fetch a single page of Add-ons (25)

### ISSUE THREAD

**Issue by interfect** [mozilla-mobile/android-components#8076]
This code here doesn't handle the case of the collection having multiple pages:

https://github.com/mozilla-mobile/android-components/blob/f5d1ecc9c13bb5ff30b039f4e5607f678fc9cfb9/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AddonCollectionProvider.kt#L82-L102

As soon as more than 25 add-ons are in the collection it fetches, only the first page of 25 are visible to the user, and add-ons that were showing as supported but get pushed to the next page show up as unsupported again.

It should fetch all the pages that there are, merge them all up into one JSON for the cache, and use the full list.

**Comment by csadilek** [comment]
As a short-term solution we can increase the page size to 50 using `?page_size=50`, and deal with pagination later.
