### ISSUE TITLE
Investigate potential risks with Android 11

### ISSUE THREAD

**Issue by psymoon** [mozilla-mobile/android-components#8088]
With Android 11 coming out, let's make sure nothing will break.

**Comment by Amejia481** [comment]
Maybe QA can do some testing using Android 11

**Comment by jonalmeida** [comment]
Did a short round of testing based on some of the components we have their features. So far there haven't been any issues in the follow list:

Android 11 Testing (RPB3.200720.005)
  - [x] QR code pairing
  - [x] One-time app permissions - camera and location tested.
  - [x] Text fields in web content.
  - [x] Long presses.
  - [x] Web Push/Send Tab
  - [x] Web notifications - works, but may need to revisit and test again.
  - [x] Site permissions.
  - [x] Installing addons.
  - [x] PIP.
  - [x] Private browsing.
  - [x] Session restore.
  - [x] Downloads - not sure what all there is to try?
  - [x] Media
  - [ ] Private browsing - `SecureWindowFeature`
  - [ ] App links
  - [ ] Logins

**Comment by jonalmeida** [comment]
> Maybe QA can do some testing using Android 11

QA did a round of testing with Fenix, but that didn't find any issues with the components at this moment. You can find the list [here](https://github.com/mozilla-mobile/fenix/issues?q=is%3Aissue+label%3AAndroid%3A11+is%3Aopen).

**Comment by pocmo** [comment]
The package visibility changes looks like they may affect us (app links, download managers, ..?):
https://developer.android.com/preview/privacy/package-visibility

**Comment by Amejia481** [comment]
We opened an issue for the visibility changes https://github.com/mozilla-mobile/android-components/issues/7827 :)

**Comment by rocketsroger** [comment]
We should make a build targeting Android 11 API for QA to test

**Comment by pocmo** [comment]
Building with a new SDK and targeting it always reveals a bunch of additional problems, let's file those separately. :)

**Comment by Amejia481** [comment]
I created this https://github.com/mozilla-mobile/android-components/issues/8519 meta issue where we can see all the issues that we have to fix/test before targeting Android 11.

**Comment by jonalmeida** [comment]
Closing, see above comment.
