### ISSUE TITLE
Camera doesn't auto-focus when setting up Firefox Sync

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#8097]
> From https://bugzilla.mozilla.org/show_bug.cgi?id=1655341

Steps to reproduce:

Firefox Nightly. Android 5.1.1 Samsung Galaxy j1. Camera not auto-focusing when setting up Firefox Sync. That's why you can't read the qr code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7000)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795381

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
