### ISSUE TITLE
State restore: Session.url and EngineSessionState may disagree

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8100]
STR:
* Load website A
* Load website B
* Immediately minimize and close browser
* Restart browser

Expected:
* Website B or website A is getting restored (depending on how far we have been with loading website B)

Actual (depending on timing of course):
* The toolbar says website B, but then website A gets restored and the toolbar changes to website A.

--

What's happening under the hood is that (in the STR) the navigation already happened and we've set the URL on `Session/SessionState`, but we didn't get a new `EngineSessionState` from `Gecko` yet. So if we persist in that situation then we have the new URL in the session and the old engine state.

On restore we now create a new Session (with the new URL) and then instead of loading the URL restore the engine state, which is pointing to the old website. This will update the Session and everything is consistent again. But it looks weird, especially on slow loads where you think we may be loading website B, but then its website A.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7004)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796223

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
