### ISSUE TITLE
Intermittent test failure: Adding a Download with skipConfirmation flag will start download immediately

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#8102]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=312845539&repo=android-components

[task 2020-08-12T16:24:04.008Z]   TEST: Adding a Download with skipConfirmation flag will start download immediately
[task 2020-08-12T16:24:04.008Z]     [Robolectric] mozilla.components.feature.downloads.DownloadsFeatureTest.Adding a Download with skipConfirmation flag will start download immediately: sdk=28; resources=binary
[task 2020-08-12T16:24:04.008Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-08-12T16:24:04.008Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@173049a4', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@173049a4'
[task 2020-08-12T16:24:04.108Z]   FAILURE
[task 2020-08-12T16:24:04.108Z] 
[task 2020-08-12T16:24:04.108Z] java.lang.AssertionError: expected null, but was:<DownloadState(url=https://www.mozilla.org, fileName=null, contentType=null, contentLength=null, currentBytesCopied=0, status=INITIATED, userAgent=null, destinationDirectory=Download, referrerUrl=null, skipConfirmation=true, id=-5016493265276608841, sessionId=test-tab)>
[task 2020-08-12T16:24:04.108Z] 	at org.junit.Assert.fail(Assert.java:88)
[task 2020-08-12T16:24:04.108Z] 	at org.junit.Assert.failNotNull(Assert.java:755)
[task 2020-08-12T16:24:04.110Z] 	at org.junit.Assert.assertNull(Assert.java:737)
[task 2020-08-12T16:24:04.110Z] 	at org.junit.Assert.assertNull(Assert.java:747)
[task 2020-08-12T16:24:04.110Z] 	at mozilla.components.feature.downloads.DownloadsFeatureTest.Adding a Download with skipConfirmation flag will start download immediately(DownloadsFeatureTest.kt:226)
[task 2020-08-12T16:24:04.110Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-08-12T16:24:04.110Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-08-12T16:24:04.110Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-08-12T16:24:04.110Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-08-12T16:24:04.110Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[task 2020-08-12T16:24:04.111Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[task 2020-08-12T16:24:04.111Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[task 2020-08-12T16:24:04.111Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[task 2020-08-12T16:24:04.111Z] 	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:601)
[task 2020-08-12T16:24:04.111Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[task 2020-08-12T16:24:04.111Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[task 2020-08-12T16:24:04.111Z] 	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
[task 2020-08-12T16:24:04.111Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
[task 2020-08-12T16:24:04.112Z] 	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
[task 2020-08-12T16:24:04.112Z] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[task 2020-08-12T16:24:04.112Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[task 2020-08-12T16:24:04.112Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[task 2020-08-12T16:24:04.112Z] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[task 2020-08-12T16:24:04.112Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[task 2020-08-12T16:24:04.112Z] 	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
[task 2020-08-12T16:24:04.112Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[task 2020-08-12T16:24:04.112Z] 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
[task 2020-08-12T16:24:04.113Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
[task 2020-08-12T16:24:04.113Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
[task 2020-08-12T16:24:04.113Z] 	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
[task 2020-08-12T16:24:04.113Z] 	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
[task 2020-08-12T16:24:04.113Z] 	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[task 2020-08-12T16:24:04.113Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-08-12T16:24:04.113Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-08-12T16:24:04.113Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-08-12T16:24:04.113Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-08-12T16:24:04.114Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-08-12T16:24:04.114Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-08-12T16:24:04.114Z] 	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[task 2020-08-12T16:24:04.114Z] 	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[task 2020-08-12T16:24:04.114Z] 	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[task 2020-08-12T16:24:04.114Z] 	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
[task 2020-08-12T16:24:04.114Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[task 2020-08-12T16:24:04.114Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[task 2020-08-12T16:24:04.114Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[task 2020-08-12T16:24:04.114Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[task 2020-08-12T16:24:04.114Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[task 2020-08-12T16:24:04.114Z] 	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[task 2020-08-12T16:24:04.115Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[task 2020-08-12T16:24:04.115Z] 	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[task 2020-08-12T16:24:04.115Z] 	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
[task 2020-08-12T16:24:04.115Z] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[task 2020-08-12T16:24:04.115Z] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[task 2020-08-12T16:24:04.115Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[task 2020-08-12T16:24:04.115Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[task 2020-08-12T16:24:04.115Z] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7006)

**Comment by jonalmeida** [comment]
Not new reports for a while. Re-open if they return.
