### ISSUE TITLE
Provide ability to customize length of gradient in urlView

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#814]
I want it to be 64dp but it's specified as 24dp in the code:
https://github.com/mozilla-mobile/android-components/blob/e0433e6aff8f4764f3fac10ed725394fad7050d9/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt#L405

**Comment by mcomella** [comment]
I tried working around this by setting the fading edge length to 64dp but setting the value to 24 and 64 seems to have the same effect. Perhaps the fading edge length is not the proper way to add a gradient to a TextView or I'm doing something incorrectly.

**Comment by pocmo** [comment]
Unassigning myself: @jonalmeida @Amejia481 You have been both working on the toolbar this sprint. Maybe you have time to pick this up in the next sprint?

**Comment by Amejia481** [comment]
Sure no problem!
