### ISSUE TITLE
Make AddonCollectionProvider more resilient to network failures

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8147]
We are seeing an increase of network issues related to fetching add-ons https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9291499/

**Comment by csadilek** [comment]
Let's expand the scope of this ticket to make our AMO `AddonCollectionProvider` more resilient to network issues. I think the main change we should apply is to return the cached result if we hit a network problem, even if the cache is "expired." 

We're currently too conservative about the cache.

We're refreshing the cache once a day in Fenix, which is fine, but we should allow users to navigate to the Addon screen even if they have no network connection. There's no reason to show a failure in this case (if we haven't refreshed the cache on that day yet).
