### ISSUE TITLE
Fetch `org.mozilla.fxa_client:fxa_client` for FxA client native libraries

### ISSUE THREAD

**Issue by ncalexan** [mozilla-mobile/android-components#815]
Right now, we use the TC index to pull a ZIP of FxA client native libraries.  As of https://github.com/mozilla/application-services/pull/248 we should be publishing a well-formed AAR with these dependencies to bintray (and jcenter, eventually) and no longer publishing the ZIP file.  This ticket tracks updating and testing the update.

/cc @vladikoff

**Comment by vladikoff** [comment]
PR here: https://github.com/mozilla-mobile/android-components/pull/818
