### ISSUE TITLE
Remove / replace firebase testing on Firebase walley devices

### ISSUE THREAD

**Issue by rpappalax** [mozilla-mobile/android-components#8150]
@grigoryk do you mind if we replace the Pixel 2 (walleye API 28) on Firebase for a more available one in the Firebase test farm: Pixel 3 (blueline/28) or Pixel 4 (flame/29)?

The walleye is the cause of many timeouts that are happening more frequently.  

see:
Intermittent test task failure: [taskcluster:error] Task timeout after 2400 seconds. Force killing container. #7970
@Archaeopteryx ^

config:
https://github.com/mozilla-mobile/android-components/blame/master/automation/taskcluster/androidTest/flank-arm.yml#L39-L40

**Comment by grigoryk** [comment]
If it helps make things stable, please go ahead!

**Comment by rpappalax** [comment]
merged
