### ISSUE TITLE
Simplify AbstractFetchDownloadService

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8151]
`AbstractFetchDownloadService` has grown a lot making it pretty difficult to maintain, we should find a way to simplify it.

 
As @NotWoods  commented, we could take a look at `WorkManager`:

> `WorkManager` can now handle immediate execution, it might be worth looking into using it for download in the future.
> https://medium.com/androiddevelopers/use-workmanager-for-immediate-background-execution-a57db502603d
>

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7054)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792938

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
