### ISSUE TITLE
Intermittent decision task CalledProcessError: Command '[u'./gradlew', u'browser-thumbnails:dependencies', u'--configuration', u'implementation']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#8154]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=313372238&repo=android-components

[task 2020-08-18T23:14:59.289Z] 2020-08-18 23:14:59,289 - INFO - writing artifact file `parameters.yml`
[task 2020-08-18T23:14:59.295Z] 2020-08-18 23:14:59,295 - INFO - writing artifact file `actions.json`
[task 2020-08-18T23:14:59.298Z] 2020-08-18 23:14:59,298 - INFO - Loading kinds
[task 2020-08-18T23:14:59.391Z] 2020-08-18 23:14:59,391 - INFO - Generating full task set
[task 2020-08-18T23:14:59.412Z] 2020-08-18 23:14:59,412 - INFO - Generated 3 tasks for kind docker-image
[task 2020-08-18T23:14:59.421Z] 2020-08-18 23:14:59,421 - INFO - Generated 1 tasks for kind fetch
[task 2020-08-18T23:15:03.351Z] 2020-08-18 23:15:03,351 - INFO - Generated 2 tasks for kind toolchain
[task 2020-08-18T23:15:03.353Z] 2020-08-18 23:15:03,353 - INFO - Processing push for commit range c117eb2985fa813405daf999da59f9a8fcc9d15a -> 876d5e73f4a8284a5778b274e2410ac9bccb3ce8
[task 2020-08-18T23:16:50.967Z] The message received from the daemon indicates that the daemon has disappeared.
[task 2020-08-18T23:16:50.968Z] Build request sent: Build{id=0764f41c-69cb-49e2-9f68-b85b2cf4e71f, currentDir=/builds/worker/checkouts/src}
[task 2020-08-18T23:16:50.968Z] Attempting to read last messages from the daemon log...
[task 2020-08-18T23:16:50.968Z] Daemon pid: 145
[task 2020-08-18T23:16:50.968Z]   log file: /builds/worker/.gradle/daemon/5.6.4/daemon-145.out.log
[task 2020-08-18T23:16:50.968Z] ----- Last  20 lines from daemon log file - daemon-145.out.log -----
[task 2020-08-18T23:16:50.968Z] 23:15:07.821 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
[task 2020-08-18T23:16:50.968Z] 23:15:07.821 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
[task 2020-08-18T23:16:50.968Z] 23:15:07.870 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
[task 2020-08-18T23:16:50.968Z] 23:15:07.870 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] resetting idle timer
[task 2020-08-18T23:16:50.968Z] 23:15:07.870 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
[task 2020-08-18T23:16:50.968Z] 23:15:07.871 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=0764f41c-69cb-49e2-9f68-b85b2cf4e71f, currentDir=/builds/worker/checkouts/src}. Dispatching build started information...
[task 2020-08-18T23:16:50.968Z] 23:15:07.871 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 17: dispatching class org.gradle.launcher.daemon.protocol.BuildStarted
[task 2020-08-18T23:16:50.968Z] 23:15:07.872 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: {PATH=/builds/worker/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, TASKCLUSTER_PORT_80_TCP_PROTO=tcp, MOBILE_BASE_REV=c117eb2985fa813405daf999da59f9a8fcc9d15a, TASKCLUSTER_ROOT_URL=https://firefox-ci-tc.services.mozilla.com, TASKCLUSTER_PORT_80_TCP_ADDR=172.17.0.2, TASKCLUSTER_NAME=/quizzical_albattani/taskcluster, TERM=xterm, MOBILE_HEAD_REV=876d5e73f4a8284a5778b274e2410ac9bccb3ce8, TASKGRAPH_BASE_REPOSITORY=https://hg.mozilla.org/ci/taskgraph, TASKCLUSTER_PORT_80_TCP=tcp://172.17.0.2:80, TASKGRAPH_HEAD_REPOSITORY=https://hg.mozilla.org/ci/taskgraph, MOBILE_BASE_REPOSITORY=https://github.com/mozilla-mobile/android-components, TASKCLUSTER_PORT=tcp://172.17.0.2:80, MOBILE_HEAD_REPOSITORY=https://github.com/mozilla-mobile/android-components, PWD=/builds/worker/checkouts/src, _=/builds/worker/.local/bin/taskgraph, TASKCLUSTER_PORT_80_TCP_PORT=80, TASKCLUSTER_PROXY_URL=http://taskcluster, SHELL=/bin/bash, MOBILE_REPOSITORY_TYPE=git, TASKCLUSTER_WORKER_LOCATION={"availabilityZone":"us-west-2a","cloud":"aws","region":"us-west-2"}, TASKCLUSTER_INSTANCE_TYPE=c5d.large, OLDPWD=/builds/worker/checkouts/src, ANDROID_SDK_ROOT=/builds/worker/android-sdk, TASKCLUSTER_WORKER_GROUP=us-west-2, RUN_ID=0, TASKCLUSTER_WORKER_TYPE=decision, TASKCLUSTER_PUBLIC_IP=54.218.75.190, REPOSITORIES={"mobile":"android-components","taskgraph":"Taskgraph"}, HOSTNAME=9bb7e8c75011, MOBILE_HEAD_TAG=, HG_STORE_PATH=/builds/worker/checkouts/hg-store, TASKGRAPH_REPOSITORY_TYPE=hg, TASK_ID=bFNGYD_jQUGXxIg3HwO-DA, HOME=/builds/worker, SHLVL=1, TASKGRAPH_HEAD_REV=cab4565345d0d0effa66f18fe91335dd6d744031, MOBILE_HEAD_REF=refs/heads/master}
[task 2020-08-18T23:16:50.968Z] 23:15:08.133 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start relaying all logs to the client via the connection.
[task 2020-08-18T23:16:50.968Z] 23:15:08.133 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 145). The daemon log file: /builds/worker/.gradle/daemon/5.6.4/daemon-145.out.log
[task 2020-08-18T23:16:50.968Z] 23:15:08.415 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting build in new daemon [memory: 3.8 GB]
[task 2020-08-18T23:16:50.968Z] 23:15:08.478 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
[task 2020-08-18T23:16:50.968Z] 23:15:08.479 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=dd9c5d75-9ec5-438f-a18e-32179064f75a,javaHome=/usr/lib/jvm/java-8-openjdk-amd64,daemonRegistryDir=/builds/worker/.gradle/daemon,pid=145,idleTimeout=10800000,priority=NORMAL,daemonOpts=-Xmx4096m,-Dfile.encoding=US-ASCII,-Duser.country=US,-Duser.language=en,-Duser.variant]
[task 2020-08-18T23:16:50.968Z] This version of Gradle expects version '1.2.9' of the `kotlin-dsl` plugin but version '1.3.6' has been applied to project ':buildSrc'. Let Gradle control the version of `kotlin-dsl` by removing any explicit `kotlin-dsl` version constraints from your build logic.
[task 2020-08-18T23:16:50.968Z] WARNING: Unsupported Kotlin plugin version.
[task 2020-08-18T23:16:50.968Z] The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.3.41` that might work differently than in the requested version `1.3.72`.
[task 2020-08-18T23:16:50.968Z] The `kotlin-dsl` plugin applied to project ':buildSrc' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/5.6.4/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
[task 2020-08-18T23:16:50.968Z] :jar: No valid plugin descriptors were found in META-INF/gradle-plugins
[task 2020-08-18T23:16:50.968Z] Local configuration: absent local.properties; proceeding as normal.
[task 2020-08-18T23:16:50.968Z] Configuration on demand is an incubating feature.
[task 2020-08-18T23:16:50.968Z] ----- End of the daemon log -----
[task 2020-08-18T23:16:50.968Z] 
[task 2020-08-18T23:16:50.971Z] 
[task 2020-08-18T23:16:50.971Z] FAILURE: Build failed with an exception.
[task 2020-08-18T23:16:50.972Z] 
[task 2020-08-18T23:16:50.972Z] * What went wrong:
[task 2020-08-18T23:16:50.974Z] Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
[task 2020-08-18T23:16:50.974Z] 
[task 2020-08-18T23:16:50.974Z] * Try:
[task 2020-08-18T23:16:50.975Z] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[task 2020-08-18T23:16:50.975Z] 
[task 2020-08-18T23:16:50.975Z] * Get more help at https://help.gradle.org
[task 2020-08-18T23:16:51.307Z] 2020-08-18 23:16:51,302 - ERROR - Error loading tasks for kind build:
[task 2020-08-18T23:16:51.307Z] Traceback (most recent call last):
[task 2020-08-18T23:16:51.307Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/generator.py", line 261, in _run
[task 2020-08-18T23:16:51.307Z]     new_tasks = kind.load_tasks(parameters, list(all_tasks.values()))
[task 2020-08-18T23:16:51.307Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/generator.py", line 57, in load_tasks
[task 2020-08-18T23:16:51.307Z]     inputs = loader(self.name, self.path, config, parameters, loaded_tasks)
[task 2020-08-18T23:16:51.307Z]   File "taskcluster/ac_taskgraph/loader/build_config.py", line 107, in loader
[task 2020-08-18T23:16:51.307Z]     affected_components = get_affected_components(files_changed, config.get("files-affecting-components"))
[task 2020-08-18T23:16:51.308Z]   File "taskcluster/ac_taskgraph/loader/build_config.py", line 87, in get_affected_components
[task 2020-08-18T23:16:51.308Z]     affected_components.update(get_deps_for_component(c))
[task 2020-08-18T23:16:51.308Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/util/memoize.py", line 25, in __call__
[task 2020-08-18T23:16:51.308Z]     self[args] = self.func(*args)
[task 2020-08-18T23:16:51.308Z]   File "taskcluster/ac_taskgraph/loader/build_config.py", line 55, in get_deps_for_component
[task 2020-08-18T23:16:51.308Z]     for line in subprocess.check_output(['./gradlew', '%s:dependencies' % component, '--configuration', 'implementation']).splitlines():
[task 2020-08-18T23:16:51.308Z]   File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
[task 2020-08-18T23:16:51.308Z]     raise CalledProcessError(retcode, cmd, output=output)
[task 2020-08-18T23:16:51.308Z] CalledProcessError: Command '[u'./gradlew', u'browser-thumbnails:dependencies', u'--configuration', u'implementation']' returned non-zero exit status 1
[task 2020-08-18T23:16:51.309Z] Traceback (most recent call last):
[task 2020-08-18T23:16:51.309Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/main.py", line 481, in main
[task 2020-08-18T23:16:51.310Z]     args.command(vars(args))
[task 2020-08-18T23:16:51.310Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/main.py", line 321, in decision
[task 2020-08-18T23:16:51.311Z]     taskgraph_decision(options)
[task 2020-08-18T23:16:51.311Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/decision.py", line 95, in taskgraph_decision
[task 2020-08-18T23:16:51.311Z]     full_task_json = tgg.full_task_graph.to_json()
[task 2020-08-18T23:16:51.312Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/generator.py", line 149, in full_task_graph
[task 2020-08-18T23:16:51.312Z]     return self._run_until('full_task_graph')
[task 2020-08-18T23:16:51.312Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/generator.py", line 338, in _run_until
[task 2020-08-18T23:16:51.313Z]     k, v = self._run.next()
[task 2020-08-18T23:16:51.313Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/generator.py", line 261, in _run
[task 2020-08-18T23:16:51.313Z]     new_tasks = kind.load_tasks(parameters, list(all_tasks.values()))
[task 2020-08-18T23:16:51.314Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/generator.py", line 57, in load_tasks
[task 2020-08-18T23:16:51.314Z]     inputs = loader(self.name, self.path, config, parameters, loaded_tasks)
[task 2020-08-18T23:16:51.315Z]   File "taskcluster/ac_taskgraph/loader/build_config.py", line 107, in loader
[task 2020-08-18T23:16:51.315Z]     affected_components = get_affected_components(files_changed, config.get("files-affecting-components"))
[task 2020-08-18T23:16:51.315Z]   File "taskcluster/ac_taskgraph/loader/build_config.py", line 87, in get_affected_components
[task 2020-08-18T23:16:51.316Z]     affected_components.update(get_deps_for_component(c))
[task 2020-08-18T23:16:51.316Z]   File "/builds/worker/.local/lib/python2.7/site-packages/taskgraph/util/memoize.py", line 25, in __call__
[task 2020-08-18T23:16:51.317Z]     self[args] = self.func(*args)
[task 2020-08-18T23:16:51.317Z]   File "taskcluster/ac_taskgraph/loader/build_config.py", line 55, in get_deps_for_component
[task 2020-08-18T23:16:51.319Z]     for line in subprocess.check_output(['./gradlew', '%s:dependencies' % component, '--configuration', 'implementation']).splitlines():
[task 2020-08-18T23:16:51.319Z]   File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
[task 2020-08-18T23:16:51.319Z]     raise CalledProcessError(retcode, cmd, output=output)
[task 2020-08-18T23:16:51.319Z] CalledProcessError: Command '[u'./gradlew', u'browser-thumbnails:dependencies', u'--configuration', u'implementation']' returned non-zero exit status 1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7056)

**Comment by jonalmeida** [comment]
> Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

This happens intermittently on TC but isn't unique to browser-thumbnails.

**Comment by jonalmeida** [comment]
Not new reports for a while. Re-open if they return.
