### ISSUE TITLE
Adding a new device capabilities: considerations

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#8164]
In https://github.com/mozilla-mobile/android-components/pull/7856 we're changing how `ensureCapabilities` is treated: as a method which isn't expected to do any networking (and thus, randomly fail) during regular account rehydration flow (e.g. startup). All of the work is done within `initializeDevice`. See https://github.com/mozilla/application-services/issues/3474.

However, this assumption breaks if we've added a new device capability. Then we probably _do_ need to do some fallible work as part of `ensureCapabilities`, which introduces a failure point to our startup path. This issue is to think about how to handle that best, when the time comes.

cc @rfk @eoger

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7062)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794205

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
