### ISSUE TITLE
Browser hangs on rapdily loading the page from JavaScript

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#8166]
> Taken from https://bugzilla.mozilla.org/show_bug.cgi?id=1653570

##Summary:

Basically the function location.reload() is causing browser to hang as browser is not able to handle multiple reloads but similar issue cannot be seen in (Mi browser,Safari Browser, Mint Browser and Oppo Web Browser) as i am able to close the current tab.
Products affected:

Latest FIREFOX Browser in Android.
##Steps To Reproduce:

Use the below code and save it as html file and then open it up on browser :-
TEST

LINK:-- https://silentmode.000webhostapp.com/dos.html

<script>
open("");
setInterval('location.reload()',1);
</script>

Or

open up pop.html that i have attached
##Supporting Material/References:

i have attached html file that contains the code causing denial of service,

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7064)

**Comment by st3fan** [comment]
Posting this to A-C because I maybe this is something we can intercept? If this is a GV issue then we can move the Bugzilla bug there.

**Comment by csadilek** [comment]
This no longer reproduces. Closing.
