### ISSUE TITLE
Automatically synchronize photon assets with upstream photon design lib

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#817]
The canonical source for photon assets is here: https://github.com/FirefoxUX/photon-icons/ These get pulled into the android-components. However, sometimes changes are made in this repository on these assets that don't get reflected upstream, e.g. #766 and #778.

We should come up with a system that either:
- Prevents changes to these assets directly in this repository, encouraging users to contribute upstream (maybe [a Danger check](https://danger.systems/js/) to add a warning if the photon module is modified?)
- Automatically synchronizes any changes in this repository to the photon assets upstream

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7067)

**Comment by pocmo** [comment]
This is tracked "upstream" here:
https://github.com/FirefoxUX/photon-icons/issues/23

**Comment by pocmo** [comment]
Note that *photon-icons* uses an automated process to generated the XML drawables while multiple of our icons are manually optimized to fix various issues.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793167

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
