### ISSUE TITLE
Refactor PromptFeature to clean up logins params into one object

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#8192]
Login select and save code need certain dependencies from Fenix that are unslightly and growing in the param list. To clean this up, we can create an object to pass all the login setups we need from the app (if the app wants to use the logins features).

See https://github.com/mozilla-mobile/android-components/pull/8178#discussion_r474708398

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7087)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796493

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
