### ISSUE TITLE
Navigation bar color for PWA

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/android-components#8193]
The status bar and the navigation bar color on a PWA doesn't match the color scheme of the PWA (not sure if this is a bug in the PWA, or in Fenix)

Chrome has a dark color for the status bar but not the navigation bar:

<img src="https://user-images.githubusercontent.com/69051186/90919140-bfc44080-e39a-11ea-95e1-3ad138ecb365.jpg" width="300px">

On Fenix both bars are white which is quite jarring

<img src="https://user-images.githubusercontent.com/69051186/90919184-d8345b00-e39a-11ea-9ddc-994d05d5eb54.jpg" width="300px">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7089)

**Comment by agi** [comment]
Maybe I misunderstand what you mean, but this _was_ definitely the PWA (both on Fenix and Chrome). I.e. I tapped on "install" and then opened the website from the shortcut.

**Comment by jonalmeida** [comment]
My mistake. :)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796435

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
