### ISSUE TITLE
Handling opening browser from custom tab in AC

### ISSUE THREAD

**Issue by NotWoods** [mozilla-mobile/android-components#8210]
Currently, apps need to handle "Open in \<browser>" themselves and add that to the custom tab menu. Fenix creates an intent and has code to handle releasing the session then move the tab.

Ideally this code should live in AC. We would need to store the target intent/activity somehow and pass it around.

This would also enable us to handle various custom tab features that open a new tab in AC:
- Context menu (current solution: disable open in new tab option)
- Search (current solution: handled in Fenix)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7103)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796213

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
