### ISSUE TITLE
Use JSON tracking protection blocklists from Shavar

### ISSUE THREAD

**Issue by say-yawn** [mozilla-mobile/android-components#8228]
# About this Issue
Shavar currently have a version control system on files we store on S3 for tracking protection blocklists. To get the latest list a GET request to S3 can be done like:
```
http://tracking-protection.stage.mozaws.net/tracking/<latest release Firefox version>/base-fingerprinting-track.json
```
If all the Android component is interested on is retrieving the latest tracking protection lists through a simple automation of incrementing one part of the path (the Firefox version in this case), this could suffice. But if you want to download and be able to always download the given file for the build we can instead use a link formatted like:
```
http://tracking-protection.stage.mozaws.net/base-fingerprinting-track-digest256/<latest release Firefox version>/<timestamp of when the file was generated>.json
```
As such, to retrieve the latest “timestamp of when the file was generated” you would be able to ping an endpoint like:
```
https://shavar.stage.mozaws.net/downloads?client=navclient-auto-ffox&appver=<latest Firefox desktop release version>&pver=2.2
```
which would return:
```
n:3600
i:base-fingerprinting-track-digest256
u:tracking-protection.stage.mozaws.net/base-fingerprinting-track-digest256/74.0/1591205756
```
which you can then grab the url from and add .json to.
The content of the tracking protection blocklist JSON file will look like [this](https://github.com/mozilla-services/shavar-prod-lists/blob/76.0/normalized-lists/base-fingerprinting-track.json)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7112)

**Comment by say-yawn** [comment]
@Amejia481 and I agreed to revisit this around Sept 18th.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795379

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
