### ISSUE TITLE
When committing an inline autocomplete suggestion, search suggestions are not updated

### ISSUE THREAD

**Issue by miDeb** [mozilla-mobile/android-components#8247]
If you type "g" into the toolbar, it will autocomplete **g**oogle.com. However, when committing that suggestion by tapping after the "g", search suggestions don't update (search suggestions for "g" are shown, instead of search suggestions for "google.com")

**Comment by jonalmeida** [comment]
@miDeb is there a bug in a product that you're referencing this fix for? A Fenix issue probably?

**Comment by miDeb** [comment]
I noticed this when I was implementing a fix for a different issue. Yes this happens in fenix. Should I first open an issue there?

**Comment by jonalmeida** [comment]
I misread your issue, it sounds reasonable. 🙂 I'll have a look at your PR.
