### ISSUE TITLE
Intermittent failure ui-test unit-logins Could not resolve all files for configuration ':feature-tab-collections:debugAndroidTestRuntimeClasspath'.

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#8263]
Log: https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=314157509&repo=android-components&lineNumber=4643

[task 2020-08-27T08:14:55.226Z] > Task :feature-tab-collections:mergeExtDexDebugAndroidTest
[task 2020-08-27T08:14:55.426Z] 
[task 2020-08-27T08:14:55.426Z] FAILURE: Build failed with an exception.
[task 2020-08-27T08:14:55.426Z] 
[task 2020-08-27T08:14:55.427Z] * What went wrong:
[task 2020-08-27T08:14:55.427Z] Execution failed for task ':feature-tab-collections:mergeLibDexDebugAndroidTest'.
[task 2020-08-27T08:14:55.427Z] > Could not resolve all files for configuration ':feature-tab-collections:debugAndroidTestRuntimeClasspath'.
[task 2020-08-27T08:14:55.427Z]    > Failed to transform artifact 'classes.jar (project :browser-state)' to match attributes {artifactType=android-dex, com.android.build.api.attributes.BuildTypeAttr=debug, com.android.build.api.attributes.VariantAttr=debug, com.android.build.gradle.internal.dependency.AndroidTypeAttr=Aar, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
[task 2020-08-27T08:14:55.427Z]       > Execution failed for DexingWithClasspathTransform: /builds/worker/checkouts/src/components/browser/state/build/intermediates/runtime_library_classes/debug/classes.jar.
[task 2020-08-27T08:14:55.427Z]          > Error while dexing.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7151)

**Comment by jonalmeida** [comment]
Not new reports for a while. Re-open if they return.
