### ISSUE TITLE
List engine features and min version (gecko) + feature components

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#827]
We do not really have a good list of features our engine abstraction supports (e.g. "find in page"). For GeckoView it would be helpful to know the first version that supports it (e.g. 63). And if there's a matching feature component then it would be super helpful to know about that too (e.g. `feature-findinpage`).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7160)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794669

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
