### ISSUE TITLE
AddonsManagerAdapter and AddonInstallationDialogFragment can only take a AddonCollectionProvider, which is final, and won't work with any other AddonsProvider

### ISSUE THREAD

**Issue by interfect** [mozilla-mobile/android-components#8289]
The `AddonsManagerAdapter` demands to have exactly an `AddonCollectionProvider` and not any other implementation of an `AddonsProvider`.

https://github.com/mozilla-mobile/android-components/blob/5c2559da76130619601902d22603083c39e45550/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt#L57

But `AddonCollectionProvider` is final (as is the default in Kotlin), and so can't be subclassed to modify its behavior.

So `AddonsManagerAdapter` is completely unusable with any other implementation of that component.

This is giving me trouble in my browser project, which wants to take the list of available add-ons from a different source that `AddonCollectionProvider` doesn't support.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7173)

**Comment by interfect** [comment]
It looks like the right fix here might be to make `AddonCollectionProvider` not `final`, or to pull out the interface that `AddonsManagerAdapter` really needs (including e.g. add-on icons) and have it implement that.

**Comment by interfect** [comment]
This also affects `AddonInstallationDialogFragment`.

https://github.com/mozilla-mobile/android-components/blob/c8bcd3a542f4064d5d69247917787382f707c15a/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt#L65-L68

There I think you can at least leave it out, but then it looks like you'll get no icons.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795156

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
