### ISSUE TITLE
DownloadMiddleware dispatches on wrong thread via context.dispatch

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#8292]
Cause of: https://github.com/mozilla-mobile/fenix/issues/14486

`restoreDownloads` switches to an IO thread and can't use `context.dispatch` which is synchronous on the store thread.  Regression of: https://github.com/mozilla-mobile/android-components/issues/8271

**Comment by Amejia481** [comment]
Same as https://github.com/mozilla-mobile/android-components/issues/8290
