### ISSUE TITLE
Limit title length in HitResult for encoded images

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#8298]
This causes crashes like this one https://github.com/mozilla-mobile/fenix/issues/13027 due to the fact that the title can be too long for setting it as title dialog, in the case of encoded images. 
Also, using share or other options from the context menu can crash the app, so just limiting the title set to the dialog is not sufficient, and this actions should be investigated and fixed.

**Comment by mcarare** [comment]
@jonalmeida While I can limit the title : https://github.com/mcarare/android-components/commit/95bfb028efe07ffbcd9159826c7e536a3726bd37
The problem still remains for the `createShareImageCandidate`. When the image is a base64 encoded image, even if we would not have a limit for the src, sharing a string would be useless for the user. 
Alternatives are : 
1. Do not create share image candidate for these images. 
2. Share the image file, like other browser do. This might imply two steps, downloading the file and sharing it.  

Any ideas on how to approach this? A simple patch to avoid crashing would be checking the size of the intent in `Context.share` but, again, is sharing just a bunch of random characters in a string useful for the user?

**Comment by jonalmeida** [comment]
> Share the image file, like other browser do. This might imply two steps, downloading the file and sharing it ?!

This seems reasonable given the constraints you mentioned. A base64 encoded URL is pretty useless.

Looking at chrome, that seems to be exactly what they do as well. We could probably use the GeckoFetchClient to download the image and it could potentially use it's own cache for ensuring that we don't re-download the image again.

Limiting the displayed title to n characters though seems like a reasonable fix to also have.

**Comment by jonalmeida** [comment]
@mcarare I just remembered that we did the same thing for the tabs tray as well: https://github.com/mozilla-mobile/fenix/blob/68d3d85ec39a6c8ff857d61f69fd8c523cc03970/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayViewHolder.kt#L152-L159

**Comment by mcarare** [comment]
Verified as fixed in Fenix: https://github.com/mozilla-mobile/fenix/issues/13027#issuecomment-704956675.
