### ISSUE TITLE
Move LastAccessMiddleware

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8304]
I saw that `LastAccessMiddleware` is in `mozilla.components.browser.session.engine.middleware` and gets added to `EngineMiddleware`. This is technically not correct. This has nothing to do with the `Engine` and should probably be moved somewhere else.

**Comment by pocmo** [comment]
CC @jonalmeida - Not urgent. :)

**Comment by jonalmeida** [comment]
I came back today to do this, but it looks like I was 2 months too late. 😆
