### ISSUE TITLE
Lateinit property browserToolbar has not been initialized

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#8305]
Following Fenix - https://github.com/mozilla-mobile/fenix/issues/13957

`lateinit property browserToolbar has not been initialized`

It [should have been initialized in a CoordinatorLayout call](https://github.com/mozilla-mobile/android-components/blob/4f8ae49dff1db9e4a72b5713244a0756641e878e/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt#L137).

Interestingly this only happens on Android 8 devices and is not a perma crash so I think this shows an issue in either Android 8 framework or in ConstraintLayout.

**Comment by jonalmeida** [comment]
This is still an issue that we can see in Reference Browser today: https://github.com/mozilla-mobile/reference-browser/issues/1339

**Comment by Mugurell** [comment]
This shows that we'd better wrap all sensitive code with null checks.

**Comment by liuche** [comment]
Did we figure out what the problem is for this issue?

I'm seeing it in Release 82.1.1, but only for Android 8 devices
https://bugzilla.mozilla.org/show_bug.cgi?id=1660065
https://sentry.prod.mozaws.net/operations/firefox/issues/9821089/

**Comment by Mugurell** [comment]
> Did we figure out what the problem is for this issue?
> 
> I'm seeing it in Release 82.1.1, but only for Android 8 devices
> https://bugzilla.mozilla.org/show_bug.cgi?id=1660065
> https://sentry.prod.mozaws.net/operations/firefox/issues/9821089/

Based on the Reference Browser issue referenced above that showed the toolbar could definitely be null even in normal usecases I added some null checks that should fix all these situations.

**Comment by Mugurell** [comment]
https://github.com/mozilla-mobile/reference-browser/issues/1339 seems to now be fixed.
I see on https://bugzilla.mozilla.org/show_bug.cgi?id=1660065 that recent beta show 0 reports of this.

Closing this as such.
