### ISSUE TITLE
Let AutoSave respond to state changes

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8308]
Issue #8255 will change how we deal with `EngineSessionState`. Instead of requesting it from an `EngineSession` via `saveState()`, we will get it via `Observer.onState()` whenever there is a new state.

This means that in `AutoSave` we can react to this change and can save the state to disk when it changed. Some other `AutoSave` options like `periodicallyInForeground` may no longer be needed since there's no need to save an unchanged state again.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7196)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793188

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
