### ISSUE TITLE
GeckoView Nightly update failing: GeckoEngineSessionTest.kt: (279, 31): 'onExternalResponse(GeckoSession, GeckoSession.WebResponseInfo): Unit' is deprecated.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8313]
> w: /build/android-components/components/browser/engine-gecko-nightly/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt: (279, 31): 'onExternalResponse(GeckoSession, GeckoSession.WebResponseInfo): Unit' is deprecated. Deprecated in Java

https://firefox-ci-tc.services.mozilla.com/tasks/eG7aFmbUSmWmZChQRCydXw/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FeG7aFmbUSmWmZChQRCydXw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7200)

**Comment by csadilek** [comment]
Fixed by https://github.com/mozilla-mobile/android-components/pull/8314.
