### ISSUE TITLE
Create a DebugServerMiddleware

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8345]
Somewhat related: #455.

I have been prototyping an IntelliJ / Android Studio plugin that let's you look at the `Action`s dispatched on `Store` and how they change the `State` on a connected device.

For that I wrote a `DebugServerMiddleware` that starts a server and sends debug information to connected clients (e.g. the plugin). Let's find a home for that and land it in the repository.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7217)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793243

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
