### ISSUE TITLE
Upstream WifiConnectionMonitor functionality

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8349]
Fenix uses a generic `WifiConnectionMonitor`. This looks like the kind of thing we'd provide in AC.

https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/wifi/WifiConnectionMonitor.kt

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7219)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793174

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
