### ISSUE TITLE
Re-order tabs in tabs tray

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8376]
In Fenix (and also with Fennec), we want to be able to re-order tabs (private as well) manually or chronologically. You can see the UX designs here ([goabstract.com](https://share.goabstract.com/cde37d18-4bd4-4ec1-a7ef-df7a2be0e0bd?mode=design&sha=d2b3e7c964153fbef0dc3b616649ad41f13a00f7)). We should support the ability to move tabs around from the app side.

This may need an RFC..

**Comment by jonalmeida** [comment]
Jotting down some ideas..

Reorder should be as simple as `store.dispatch(BrowserAction.UpdateTabPosition(tabId, new_position))`. 

 1. Find tab with ID.
 2. Remove tab.
 3. (Maybe not needed?) coerce `new_position` to within `tab.size` range.
 3. Put tab at `new_position`.

Note that this should work for private tabs too by default since we have them both in one list.

This should suffice for now and if we need more complex automatic sorting, we can look into exposing a sorting predicate like we do for filtering tabs.

**Comment by pocmo** [comment]
We can't remove tabs in BrowserStore as long as SessionManager is authoritative afaik. 🤔

**Comment by pocmo** [comment]
> When the app wants to switch back to chronological order, we could do store.dispatch(BrowserAction.SortChronologically) that applies the sort order by lastUsed

Note that currently tabs are not just sorted chronologically. Child tabs are getting opened next to their parent.

**Comment by jonalmeida** [comment]
Closing. This work was completed.

**Comment by gaul** [comment]
@jonalmeida How do I rearrange tabs in the tray in either grid or list mode?  I am running 98.0a1 (Build #2015857515).

**Comment by teohhanhui** [comment]
@gaul:
> How do I rearrange tabs in the tray in either grid or list mode? 

Hold (long press) and drag.

**Comment by gaul** [comment]
> You must disable tab grouping ("search groups") for it to work.

Disabling this allows me to rearrange tabs.  Thanks!
