### ISSUE TITLE
DownloadUtils.guessFileName has reversed arguments from URLUtil

### ISSUE THREAD

**Issue by gaul** [mozilla-mobile/android-components#838]
Compare:

```java
public static final String guessFileName(String url, @Nullable String contentDisposition, @Nullable String mimeType)
```

with:

```kotlin
fun guessFileName(contentDisposition: String?, url: String?, mimeType: String?): String
```

Should we reverse these to prevent confusion when callers migrate from one to another?

**Comment by pocmo** [comment]
> Should we reverse these to prevent confusion when callers migrate from one to another?

We probably should have. Unfortunately all parameters are `String?` .. so we can't communicate the change via a compile error. It will most likely break silently for consuming apps.

**Comment by gaul** [comment]
I reversed the arguments when migrating so I feel like we should address this somehow.  Perhaps deprecate the existing method and add another called `guessFileNameRfcCompliant` which does what its name suggests?  Otherwise I can add a warning in Javadoc.

**Comment by pocmo** [comment]
> I reversed the arguments when migrating so I feel like we should address this somehow.

What did you migrate? Focus to use this?

**Comment by gaul** [comment]
Yes while working on mozilla-mobile/focus-android#3462.
