### ISSUE TITLE
Missing equals in Tab class (probably)

### ISSUE THREAD

**Issue by TrianguloY** [mozilla-mobile/android-components#8385]
While investigating the issue https://github.com/mozilla-mobile/fenix/issues/14954 I found that the main problem was that the updated tab was detected as a new tab, because the Tab object doesn't override the equals method
https://github.com/mozilla-mobile/android-components/blob/f93ad419789d1e02db6ab52e2f6326d79e0b1a44/components/concept/tabstray/src/main/java/mozilla/components/concept/tabstray/Tab.kt#L20-L27

This means that a tab with any of these different properties (url, title, icon, thumbnail or mediastate) are detected as different tabs, where probably only the id property should be checked. (the issue above explains steps for a changing title, but it is inmmediate to test with changing url, and also happens for the thumbnail update). I'm aware that a change of this magnitude could break other parts of the code, and maybe other proyects. I've tried to fix it from the fenix side (by adding filters and 'any' with id checks) but the number of instances where an equality is performed is high and difficult to find. I also tried to add the equals method to test, but since it is a library I'm having issues changing it with a custom editable version.

I leave this issue open in case someone else wants to check, and also in case other issues arise for the fact that two tabs with the same id but different properties are treated as different.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7242)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795157

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
