### ISSUE TITLE
Permanent failure of unit-feature-top-sites

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#8387]
Log: https://treeherder.mozilla.org/logviewer.html#?job_id=315476155&repo=android-components

Permafails since #8300 landed.

@gabrielluong can you take a look at this next week?

**Comment by jonalmeida** [comment]
Sorry @Archaeopteryx , this issue got lost and was never addressed. I've put up a change for this attached as part of #8471 so I'll close this as a duplicate of that issue.
