### ISSUE TITLE
Undo: Keep & restore thumbnail

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8395]
Follow-up from: #3265.

Keep thumbnail in `ClosedTab` to restore it too. Without that the restored tab is blank the tabs tray and that's not nice. But this means we may need to make `TrimMemoryMiddleware` to drop those thumbnails too on memory pressure.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7262)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793187

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
