### ISSUE TITLE
Intermittent test doWork - will return Result_success when SuccessfullyUpdated

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8398]
[task 2020-09-14T14:00:37.733Z] SUITE: mozilla.components.feature.addons.update.AddonUpdaterWorkerTest
[task 2020-09-14T14:00:37.733Z]   TEST: doWork - will return Result_success when SuccessfullyUpdated
[task 2020-09-14T14:00:37.733Z]     [Robolectric] mozilla.components.feature.addons.update.AddonUpdaterWorkerTest.doWork - will return Result_success when SuccessfullyUpdated: sdk=28; resources=binary
[task 2020-09-14T14:00:37.733Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-09-14T14:00:37.733Z]     I/MonitoringInstr: Setting context classloader to 'org.robolectric.internal.bytecode.SandboxClassLoader@61acd9b5', Original: 'org.robolectric.internal.bytecode.SandboxClassLoader@61acd9b5'
[task 2020-09-14T14:00:38.032Z]     I [AddonUpdaterWorker] Trying to update extension addonId
[task 2020-09-14T14:00:38.032Z]     I [AddonUpdaterWorker] Extension addonId SuccessFullyUpdated
[task 2020-09-14T14:00:38.132Z]   FAILURE
[task 2020-09-14T14:00:38.133Z] 
[task 2020-09-14T14:00:38.133Z] Wanted but not invoked:
[task 2020-09-14T14:00:38.133Z] updateAttemptStorage.saveOrUpdate$feature_addons_release(
[task 2020-09-14T14:00:38.133Z]     <any>
[task 2020-09-14T14:00:38.133Z] );
[task 2020-09-14T14:00:38.133Z] -> at mozilla.components.feature.addons.update.DefaultAddonUpdater$UpdateAttemptStorage.saveOrUpdate$feature_addons_release(AddonUpdater.kt:518)
[task 2020-09-14T14:00:38.133Z] Actually, there were zero interactions with this mock.

**Comment by Archaeopteryx** [comment]
Covered by https://github.com/mozilla-mobile/android-components/issues/8172
