### ISSUE TITLE
Support custom tabs color scheme

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8408]
I saw that they introduced a color scheme option that lets the app tell us whether it prefers a light or dark version of the interface:

https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent.Builder#setColorScheme(int)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7280)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796210

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
