### ISSUE TITLE
GleanGeckoMetricsMapping.kt: Duplicate label in when

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8413]
The GV nightly build task seems to have failed from a generated class in Glean:
```
> Task :browser-engine-gecko-nightly:compileDebugKotlin FAILED
e: warnings found and -Werror specified
w: /build/android-components/components/browser/engine-gecko-nightly/build/generated/source/glean/debug/kotlin/GleanGeckoMetricsMapping.kt: (95, 13): Duplicate label in when

> Task :service-glean:generateReleaseRFile
```
Task: https://firefox-ci-tc.services.mozilla.com/tasks/groups/DDM8oIucQRyivl5-c5GUgQ
Logs: https://firefoxci.taskcluster-artifacts.net/DDM8oIucQRyivl5-c5GUgQ/0/public/logs/live_backing.log

cc: @Dexterp37 (apologises if I'm pinging the wrong person)

**Comment by Dexterp37** [comment]
> cc: @Dexterp37 (apologises if I'm pinging the wrong person)

Nope, I'm the right person :) [I filed a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1665284) on our end: that's either due to some issue with the metrics defined in Gecko itself, or a subtle bug in the Glean SDK.

We're taking a look soon.

**Comment by mdboom** [comment]
The issue is that a duplicate telemetry id was introduced in the GV metrics.yaml file here:

https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/geckoview/streaming/metrics.yaml#1082

I think this needs `TIME_TO_LOAD_EVENT_END_NO_PRELOAD_MS` -> `TIME_TO_LOAD_EVENT_START_NO_PRELOAD_MS`.

**Comment by pocmo** [comment]
Fixe in m-c and MickeyMoz opened a PR: https://github.com/mozilla-mobile/android-components/pull/8438
