### ISSUE TITLE
SessionStorage: BrowserState with selected tab id for tab that doesn't exist

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8417]
We switched from saving a `SessionManager.Snapshot` to a `BrowserState` in #7867 / 9e60a62119e4d0cb352642940faaec9da00fe1e1.

We now see the "selected tab" check fail. As a workaround I'll write a patch that clears the selected tab id in the state we are writing to disk, in that situation.

Nevertheless we should investigate how we end up in such a situation. Our reducer definitely doesn't do any checks when setting the selected tab id. But maybe this is intentional for "out of order" actions? Let's find out.

https://sentry.prod.mozaws.net/operations/firefox-beta/issues/9527493

```Kotlin
        if (state.normalTabs.isEmpty()) {
            clear()
            return true
        }

        if (state.selectedTabId != null) {
            requireNotNull(state.selectedTab) {
                "Selected session must exist"
            }
        }
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7291)

**Comment by pocmo** [comment]
Related: https://github.com/mozilla-mobile/fenix/issues/15008

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793186

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
