### ISSUE TITLE
Migrate to androidx

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#842]
https://developer.android.com/topic/libraries/support-library/androidx-rn?linkId=57203177

- [ ] Remove Custom Tabs Jetifier hack: https://github.com/mozilla-mobile/android-components/issues/1884

**Comment by pocmo** [comment]
I tested this with our reference browser: It's a pain and doesn't work yet.

After changing the dependencies and all imports I had to use a bleeding edge (alpha) Android gradle plugin and the latest Gradle version to get it working.

And at the end I got stuck with:

```
> Transform browser.aar (androidx.browser:browser:1.0.0-rc01) with DexingTransform
AGPBI: {"kind":"error","text":"Class descriptor \u0027Landroid/support/customtabs/ICustomTabsCallback/;\u0027 cannot be represented in dex format.","sources":[{}],"tool":"D8"}

> Task :app:mergeExtDexGeckoBetaArmDebug FAILED
AGPBI: {"kind":"error","text":"Class descriptor \u0027Landroid/support/customtabs/ICustomTabsCallback/;\u0027 cannot be represented in dex format.","sources":[{}],"tool":"D8"}

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:geckoBetaArmDebugRuntimeClasspath'.
> Failed to transform file 'jetified-classes.jar' to match attributes {artifactType=android-dex, dexing-is-debuggable=true, dexing-min-sdk=21} using transform DexingTransform
   > Error while dexing.
```

**Comment by jonalmeida** [comment]
There's no solution here, but at least we're not the only ones running into this? 

https://stackoverflow.com/questions/52639577/class-descriptor-landroid-support-customtabs-icustomtabscallback-cannot-be-r

**Comment by pocmo** [comment]
I'm thinking about moving the service to a feature component for a variety of reasons. Currently the service doesn't do match. As soon as we implement more we may not want that to stay in `browser-session`.

**Comment by Amejia481** [comment]
We also  should a look at `androidx.webkit.WebViewCompat`

References:
[WebViewCompat class](https://developer.android.com/reference/androidx/webkit/WebViewCompat)
[Modern WebView Best Practices Android Dev Summit '18](https://youtu.be/HGZYtDZhOEQ)

**Comment by pocmo** [comment]
Update:

On AndroidX:
* Reference Browser
* Fenix
* Firefox Reality
* Lockbox

On support libraries:
* Firefox Focus/Klar
* Firefox for Fire TV
* Firefox for Echo Show
* Firefox Lite
