### ISSUE TITLE
Allow the application to also be part of the User Agent for A-C initiated API calls

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#8421]
For debugging purposes it would be very useful if the User Agent for API calls to MLS do not just contain the `'MozAC/51.0.0` part, but also the application like `Fenix/79.0.5', including the channel (Beta, Night, Release).

Currently in a situation where we see some interesting behaviour around calls to a service but it is hard to understand which specific build of the application is causing these.

May need a data review if we send version numbers?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7296)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795405

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
