### ISSUE TITLE
parseContentDisposition fails to parse inline; filename*=UTF-8''success.html

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8425]
We need to take a look to `DownloadUtils.parseContentDisposition` as it's failing to find the filename on `inline; filename*=UTF-8''success.html`. This string is the content disposition header from an attachment on bugzilla.
Causing that we are no finding the right file name of a download.

https://github.com/mozilla-mobile/android-components/blob/2e087b32deeb6877b6ae8b9d636521f72b27e8eb/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt#L116

**Comment by Amejia481** [comment]
Very likely we have some issues with the regular expression 

```koltin
Pattern.compile("(inline|attachment)\\s*;" +
            "\\s*filename\\s*=\\s*(\"((?:\\\\.|[^\"\\\\])*)\"|[^;]*)\\s*" +
            "(?:;\\s*filename\\*\\s*=\\s*(utf-8|iso-8859-1)'[^']*'(\\S*))?",
            Pattern.CASE_INSENSITIVE)
```

**Comment by Amejia481** [comment]
It looks like our regex doesn't support `filename*`

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
> The parameters filename and filename* differ only in that filename* uses the encoding defined in RFC 5987. When both filename and filename* are present in a single header field value, filename* is preferred over filename when both are understood.

**Comment by lnicola** [comment]
That regex seems to require `filename` to be present, too, even if `filename*` is already there.

**Comment by Amejia481** [comment]
> That regex seems to require `filename` to be present, too, even if `filename*` is already there.

Exactly this issue 👍🏽 thanks
