### ISSUE TITLE
Fail on the MLS API requests if the API key is empty

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#8429]
We are seeing a large number of requests being made the MLS service with an empty API key. Let's confirm we have a check in place that makes sure we do not make these calls if the API key is missing or empty.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7302)

**Comment by pocmo** [comment]
Yeah, so, our `MozillaLocationServices` takes any non-null String:
> https://github.com/mozilla-mobile/android-components/blob/master/components/service/location/src/main/java/mozilla/components/service/location/MozillaLocationService.kt#L53-L56

On the Fenix side it is filed with `MLS_TOKEN` from the `BuildConfig`:
https://github.com/mozilla-mobile/fenix/blob/d449184faa95fcf0f2c2bf1b34ebc54b2973378e/app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt#L38

At build time this build flag is set from the value inside `.mls_token`. If the file does not exist it is filled with the empty string:
https://github.com/mozilla-mobile/fenix/blob/master/app/build.gradle#L301-L308

So, as is, every non-debug build would use MLS without a key (assuming we fix the bug that we actually use MLS..).

**Comment by pocmo** [comment]
Which also means every fork that left that code untouched ended up using MLS without a key (back when MLS was used).

**Comment by st3fan** [comment]
@boek we are thinking this could be part of the fix in Fenix. What do you think? Can you pick this up?

**Comment by boek** [comment]
@st3fan @pocmo yes!

**Comment by csadilek** [comment]
This was fixed in Fenix.
