### ISSUE TITLE
Request.CookiePolicy.OMIT name is misleading

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8430]
[Request.CookiePolicy.OMIT](https://github.com/mozilla-mobile/android-components/blob/a1a5c582c28386a55f9dcc50f10f4a3011dd3742/components/concept/fetch/src/main/java/mozilla/components/concept/fetch/Request.kt#L149) is indicating that we are not going to include any cookies with the request but in reality we are using it to indicate the `Client` that [the request is associated with a private session](https://github.com/mozilla-mobile/android-components/blob/a1a5c582c28386a55f9dcc50f10f4a3011dd3742/components/browser/icons/src/main/java/mozilla/components/browser/icons/loader/HttpIconLoader.kt#L46).

**Comment by pocmo** [comment]
No, I think we are indeed not attaching any cookies at all.

**Comment by pocmo** [comment]
Private -> #8693
