### ISSUE TITLE
Get rid of jetifier

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8459]
GeckoView completed the migration from the legacy support libraries to Android X:
https://bugzilla.mozilla.org/show_bug.cgi?id=1553459

The assumption is that GeckoView was the last library using the support libraries, so we could start getting rid of jetifier and hopefully improve the speed of our builds (with cold cache).

The change landed in 82, which is now in beta. So I assume we will have to wait one more train cycle until it is removed from all GeckoView builds we use.

**Comment by mcomella** [comment]
I see log statements about mismatching androidx + support library when building fenix now:
```
WARNING: [Processor] Library '/Users/mcomella/.gradle/caches/modules-2/files-2.1/org.mozilla.components/feature-media/63.0.20201019143159/2daeecf360567378b69504c7e28906209a6d44e3/feature-media-63.0.20201019143159.aar'
...
WARNING: [Processor] Library '/Users/mcomella/.gradle/caches/modules-2/files-2.1/org.mozilla.geckoview/geckoview/81.0.20200930150533/a1134f4d3219f6cb78d15741a11638fe943f4a3e/geckoview-81.0.20200930150533.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
```

**Comment by mcomella** [comment]
It's curious it's still pulling from GV 81 even though ac seems to have merged to GV 82.

**Comment by mcomella** [comment]
> It's curious it's still pulling from GV 81 even though ac seems to have merged to GV 82.

The merge happened yesterday so perhaps fenix hasn't been updated yet.

**Comment by mcomella** [comment]
I changed the jetifier flag and ran `./gradlew compiledebugkotlin` but it failed:
```
* What went wrong:
Execution failed for task ':lib-push-firebase:generateDebugRFile'.
> Could not resolve all files for configuration ':lib-push-firebase:debugCompileClasspath'.
   > Could not resolve com.android.support:support-v4:26.1.0.
     Required by:
         project :lib-push-firebase > com.google.android.gms:play-services-basement:16.0.1
      > No such property: support_libraries for class: Versions
```

**Comment by mcomella** [comment]
It looks like it's a direct dependency from `com.google.firebase`:
```
\--- com.google.firebase:firebase-messaging:17.3.4
     +--- com.google.android.gms:play-services-basement:16.0.1
```

**Comment by mcomella** [comment]
They have a very different mechanism to apply firebase now and it looks like it's on version 25 rather than the version 17 that we're on: https://firebase.google.com/docs/cloud-messaging/android/client#add_firebase_sdks_to_your_app

**Comment by mcomella** [comment]
Blocked on https://github.com/mozilla-mobile/android-components/issues/4819 (thanks pocmo)

**Comment by pocmo** [comment]
The Firebase dependency was updated. Now we can try again. :)

**Comment by pocmo** [comment]
> I changed the jetifier flag and ran `./gradlew compiledebugkotlin` but it failed:

I gave this a try locally and the build passed. I'll push a PR and then let's see what taskcluster thinks.

**Comment by pocmo** [comment]
Filed Fenix follow-up: #16855.
