### ISSUE TITLE
Add metrics re tab unloading

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/android-components#8466]
We see a lot of complaints regarding tab unloading too often. We should collect some data so that we know how often this happens and if our improvements have any measurable effect.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7335)

**Comment by csadilek** [comment]
We landed this telemetry, next steps will be discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1752594.
