### ISSUE TITLE
Perma failure: test-android-feature-top-sites : testAddingAllDefaultSites

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8471]
https://firefox-ci-tc.services.mozilla.com/tasks/bPNz_VmqTDSEA3NX6Mnp5A/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FbPNz_VmqTDSEA3NX6Mnp5A%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

https://console.firebase.google.com/project/moz-android-components-230120/testlab/histories/bh.9f526cd30412cc12/matrices/5172220622059758972

It looks like the test just hangs and never completes?

**Comment by pocmo** [comment]
> It looks like the test just hangs and never completes?

Which I guess also means we are blocking and paying for two devices for 30 minutes each?

**Comment by pocmo** [comment]
CC @rpappalax for visibility.
CC @gabrielluong Looks like you wrote the test.

**Comment by pocmo** [comment]
Looking through the "merge" commits only on master it seems like this has been a problem for a long time?

**Comment by pocmo** [comment]
Just looking at the merge commits it looks it may have been the case since we landed the test:
https://github.com/mozilla-mobile/android-components/commit/69745dda54cc1598d45c4180138321e9823c8f38

... on all following merge commits on master the test is red - it never was on PRs. 🤔

**Comment by pocmo** [comment]
Duplicate #8533.

We probably should just kill the test for now.

**Comment by jonalmeida** [comment]
The test seems to be failing because of the `withTransaction` function that acts on the database directly instead of the DAO. We can fix this by moving the transaction to be in the PinnedSitesDao abstract instead.

**Comment by jonalmeida** [comment]
Looks like this issue was filed already and got lost..

https://github.com/mozilla-mobile/android-components/issues/8387
