### ISSUE TITLE
Implemente onRepostConfirmPrompt

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8478]
An example of how can be implemented can be found here https://searchfox.org/mozilla-central/source/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/BasicGeckoViewPrompt.java#127

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7348)

**Comment by csadilek** [comment]
This was implemented.
