### ISSUE TITLE
Use HTTPS for search templates where possible

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#8482]
In A-C there are some search templates that use http it would be better to use https where possible. The work here would be to verify that the engine accepts queries on the https protocol and then create a pr which changes the http call to https

https://github.com/mozilla-mobile/android-components/search?q=%22template%3D%5C%22http%22&unscoped_q=%22template%3D%5C%22http%22

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7352)

**Comment by mathcodes** [comment]
I'd like to take care of this if its available. Thanks!

**Comment by Mugurell** [comment]
> I'd like to take care of this if its available. Thanks!

It is available and yours if you want it.
If you need any help please leave a comment.

**Comment by mathcodes** [comment]
Thanks. Will do.

**Comment by Mugurell** [comment]
@mathcodes Do you need any help with this?
We'd be interested in getting a fix for it soon.

**Comment by mathcodes** [comment]
I forked it and made the changes... whats my next step? Do I create the pull request from my forked version or here?

**Comment by mathcodes** [comment]
Go ahead and hand it over to someone else if you' like as I'm not sure if I've done everything correctly, though I would love to know how. Thanks and I apologize for the delay.

**Comment by Mugurell** [comment]
Sorry for not following up on this.
Searching for `template="http://` in `assets/searchplugins` using Android Studio shows a lot more results than in a Github query.
And some endpoints seem to also have changed over the course of time, for example 
`http://m.map.daum.net/actions/searchPlace` I see now redirecting to 
`https://m.map.kakao.com/actions/searchView` which we should probably use.
It might seem that a review of all endoints is required.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796452

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
