### ISSUE TITLE
Track MLS connections with metrics

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-mobile/android-components#8485]
Firefox Desktop records several metrics to track connections to Mozilla Location Service to determine the user's search region. Most are prefixed with [SEARCH_SERVICE_](https://probes.telemetry.mozilla.org/?search=SEARCH_SERVICE). Two particularly useful ones are:

* [SEARCH_SERVICE_COUNTRY_FETCH_TIME_MS](https://probes.telemetry.mozilla.org/?view=detail&probeId=histogram%2FSEARCH_SERVICE_COUNTRY_FETCH_TIME_MS) - A histogram metric quantifying how long it took for a response
* [SEARCH_SERVICE_COUNTRY_FETCH_RESULT](https://probes.telemetry.mozilla.org/?view=detail&probeId=histogram%2FSEARCH_SERVICE_COUNTRY_FETCH_RESULT) - An enumeration of the type of response, such as ``0=SUCCESS`` and ``2=XHRTIMEOUT``

If Mozilla products using the ``MozillaLocationService`` component recorded these or similar metrics, then it could be used both to determine how active the product is, and to detect issues with a slow MLS service.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7356)

**Comment by jonalmeida** [comment]
Adding this to triage so we can prioritize it.

**Comment by jonalmeida** [comment]
I've added the location label to this for now as it looks there our other related issues that were recently filed with similar context. We can bring this up again when we know what the priority is.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793200

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
