### ISSUE TITLE
Fix CameraDevice.createCaptureSession deprecation in Android 11

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8510]
The documentation indicates which method should be used instead [see
](https://developer.android.com/reference/android/hardware/camera2/CameraDevice#createCaptureSession(java.util.List%3Candroid.view.Surface%3E,%20android.hardware.camera2.CameraCaptureSession.StateCallback,%20android.os.Handler))

**Comment by levimatheri** [comment]
@Amejia481 I'd like to work on this issue. Thanks!

**Comment by Amejia481** [comment]
For sure go for it, please assign it to your self to it and if you need any help we are to help :)

**Comment by levimatheri** [comment]
@Amejia481 Thank you!

**Comment by Amejia481** [comment]
In case you have any question, please feel free to ask :) we have a [Matrix channel](https://chat.mozilla.org/#/room/#android-components:mozilla.org) where the whole team is, and can help.:)
You can find more info about Matrix [here](https://wiki.mozilla.org/Matrix#Connect_to_Matrix).

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/android-components/commit/ac421757271e3ff457541f7c8a2b3c91d490677e
