### ISSUE TITLE
Fix CrashHandlerService#IntentService deprecation in Android 11 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8511]
See the [docs for how to replace it](https://developer.android.com/reference/android/app/IntentService)

**Comment by pocmo** [comment]
@rocketsroger converted the crash handler service into a job service in https://github.com/mozilla-mobile/android-components/issues/6058, but we had to back it out.

**Comment by rocketsroger** [comment]
> @rocketsroger converted the crash handler service into a job service in #6058, but we had to back it out.

Yes it was causing the ANR which it shouldn't be I backed it until I can look into it more
If you want I can take a look at this next week.
