### ISSUE TITLE
Fix webSettings.setAppCacheEnabled deprecation in Android 11 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8512]
Docs
https://developer.android.com/reference/android/webkit/WebSettings#setAppCacheEnabled(boolean)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7372)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796474

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
