### ISSUE TITLE
Fix webSettings.setAllowFileAccessFromFileURLs deprecation in Android 11 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8513]
[Docs](https://developer.android.com/reference/android/webkit/WebSettings#setAllowFileAccessFromFileURLs(boolean))

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7373)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796473

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
