### ISSUE TITLE
Fix SystemEngineView#Handler deprecation in Android 11 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8514]
[Docs](https://developer.android.com/reference/android/os/Handler)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7374)

**Comment by mcarare** [comment]
Note: Only constructors without `Looper` parameter are deprecated.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796472

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
