### ISSUE TITLE
AuthException: Missing key info / ISE: missing OAuthScopedKey

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#8527]
See https://github.com/mozilla-mobile/fenix/issues/15501

https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/6336621/?referrer=github_plugin

```
AuthException: Missing key info
    at mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt:23)
    at mozilla.components.service.fxa.manager.FxaAccountManager$maybeUpdateSyncAuthInfoCache$1.invokeSuspend
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:21)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
...
(2 additional frame(s) were not displayed)

Missing key info
```

Access token we get via getAccessToken doesn't have a sync key...

**Comment by grigoryk** [comment]
https://github.com/mozilla-mobile/android-components/pull/7856/files#diff-b9f70f704cf34d237544a7470a408904L15 removed this exception class entirely, and replaced this particular error with `throw IllegalStateException("missing OAuthScopedKey")`

Volume of the AuthExceptions started to disappear as that PR rolled out, however the ^^ IllegalStateException appeared: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9659200/?query=is%3Aunresolved%20missing%20OAuthScopedKey

**Comment by grigoryk** [comment]
key for the access scope [is obtained](https://github.com/mozilla/application-services/blob/aa493ae84e637a83ea36a16250517b534376d5db/components/fxa-client/src/oauth.rs#L78) via the account state: `state.scoped_keys.get(scope)`

Seems like in this case, the `scoped_keys` map doesn't have an entry for `scope`.

**Comment by grigoryk** [comment]
`scoped_keys` is populated as we're finalizing authentication during `completeOAuthFlow`, in [`handle_oauth_response`](https://github.com/mozilla/application-services/blob/aa493ae84e637a83ea36a16250517b534376d5db/components/fxa-client/src/oauth.rs#L332-L343)

Assuming fxaclient machinery all works as expected, perhaps there's some kind of a race at play here in which we're trying to access scoped_keys before it's populated...?

**Comment by grigoryk** [comment]
We combed through the a-c code together with @csadilek , and best we can tell there shouldn't be any races/etc present that can cause this sort of a failure. One suspect bit of code - a mutable account object - appears to do the right thing. If it can happen that the account will change underneath us (e.g. 'initialization' event is processed twice, somehow..?), than it would explain this failure.

#8650 makes `account` immutable, so that we don't have to consider this case. If the volume for this exception doesn't change once that PR lands, the problem is a layer deeper inside the a-c library.

One thing I haven't traced down yet is the access token caching, and how that's populated.

**Comment by grigoryk** [comment]
Socorro link for this: https://crash-stats.mozilla.org/signature/?signature=java.lang.IllegalStateException%3A%20at%20mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache%28FxaAccountManager.kt%3A24%29&date=%3E%3D2020-10-02T16%3A49%3A00.000Z&date=%3C2020-10-09T16%3A49%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#graphs

**Comment by grigoryk** [comment]
Interesting! Now that #8650 has been out for a few days, we see that the exception volume went down to almost nothing (both in [sentry](https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9659200/?query=is%3Aunresolved%20missing%20OAuthScopedKey) and [socorro](https://crash-stats.mozilla.org/signature/?signature=java.lang.IllegalStateException%3A%20at%20mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache%28FxaAccountManager.kt%3A24%29&date=%3E%3D2020-10-02T16%3A49%3A00.000Z&date=%3C2020-10-23T16%3A49%3A00.000Z#graphs)).

This does suggest that the initialization code was being hit twice, resetting the account state. Now that the account is immutable, this particular exception isn't triggered (since the in-memory account state remains). The problem likely shifted elsewhere...

**Comment by kbrosnan** [comment]
This has not gone away. The date field may have been tripping up your query. There are 800 crashes a day with this signature. 

https://crash-stats.mozilla.org/signature/?signature=java.lang.IllegalStateException%3A%20at%20mozilla.components.service.fxa.manager.FxaAccountManager.maybeUpdateSyncAuthInfoCache(FxaAccountManager.kt%3A24)&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#graphs

**Comment by grigoryk** [comment]
ISE that @kbrosnan linked started to spike in second half of November:

![Screen Shot 2020-11-30 at 11 06 59 AM](https://user-images.githubusercontent.com/465422/100652716-2d69fc00-32fc-11eb-99e4-95f8b4898800.png)

It's a top10 release crash right now.

**Comment by grigoryk** [comment]
The spike corresponds to 83.1.0 release. [Sentry link for release channel](https://sentry.prod.mozaws.net/operations/firefox/issues/10043253/?query=is%3Aunresolved%20missing%20OAuthScopedKey). 100% a-s 63, a-c 63.0.9.

**Comment by grigoryk** [comment]
This crash prior to 83.1.0 in a different form: https://sentry.prod.mozaws.net/operations/firefox/issues/9263988/?query=is%3Aunresolved%20missing%20key%20info - tapers off when 83.1.0 came out.

Volume of the current shape of this crash is 10x what it was before.

**Comment by grigoryk** [comment]
According to Sentry, this didn't happen prior to a-s 61.0.10.

A-S versions that we (may have) shipped: 67 (current nightly), 63.0.0, 61.0.13, 61.0.12, 61.0.10, 61.0.7....

Previous version of this problem was first seen 4 months ago (july 28th). We upgraded to 61.0.10 [5 months ago](https://github.com/mozilla-mobile/android-components/commit/0b3f523028b43508a967178bb0a2a7c063310eb5) - this upgrade first went into a-c v51.0.0. But oddly enough, Sentry says that this was present in a-c v48.0.15...

**Comment by grigoryk** [comment]
There's nothing remotely relevant in a [61.0.7...61.0.10 diff](https://github.com/mozilla/application-services/compare/v61.0.7...v61.0.10) though... This gently suggests that at least the original error wasn't caused by an a-s upgrade.

**Comment by grigoryk** [comment]
As a concrete step forward - let's drive the account into an unauthenticated state.

If we've requested a SCOPE_SYNC, and its associated access token is missing the key, consider ourselves in an inconsistent state and reset the account state to logged out.

**Comment by bendk** [comment]
Maybe all we need to do for this one is to check for the null?

I made 2 branches to test this one out:
  - [An a-s branch that clears the access tokens and scoped keys when we restore the account data from JSON](https://github.com/bendk/application-services/commits/fxa-client-debug), triggering the issue.
  - [An a-c branch that simply adds a check for accessToken.key == null](https://github.com/bendk/android-components/commits/fxa-client-debug)

My goal was to test what happens to work on this further, but that a-c change seems to fix the issue completely for me.  I built Fenix using those 2 branches and did some tests.

## Scenario 1
  - Log into FxA
  - Force-stop Fenix
  - Start it up again
  - On startup, I clicked on settings menu and it had the login to sync message.
  - After a few seconds, that changed to the normal "bdk@mozilla.com"
  - I added a login and clicked sync now
  - Clicked sync now on my Desktop FF and saw the login added.

Here's the logs from `adb logcat | grep FirefoxAccountStateMachine`.  It looks like the account recovery code handled the situation perfectly:

```
11-11 10:38:57.070 18083 18083 I FirefoxAccountStateMachine: Sync is enabled
11-11 10:38:57.306 18083 18217 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Account$Start@d6036a9' for state Idle(accountState=NotAuthenticated). Next state is Active(progressState=Initializing)
11-11 10:38:57.364 18083 18217 I FirefoxAccountStateMachine: Ran 'mozilla.components.service.fxa.manager.Event$Account$Start@d6036a9' side-effects for state Active(progressState=Initializing), got successive event mozilla.components.service.fxa.manager.Event$Progress$AccountRestored@e52218e
11-11 10:38:57.364 18083 18217 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Progress$AccountRestored@e52218e' for state Active(progressState=Initializing). Next state is Active(progressState=CompletingAuthentication)
11-11 10:38:57.364 18083 18217 I FirefoxAccountStateMachine: withServiceRetries: attempt 1/3
11-11 10:38:57.365 18083 18217 W FirefoxAccountStateMachine: Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@d6036a9' for state Active(progressState=CompletingAuthentication).
11-11 10:38:58.192 18083 18217 W FirefoxAccountStateMachine: Couldn't populate SyncAuthInfoCache. Sync may not work.
11-11 10:38:58.192 18083 18217 W FirefoxAccountStateMachine: Is null? - accessToken: false, tokenServerUrl: false, accessToken.key: true
11-11 10:38:58.195 18083 18217 I FirefoxAccountStateMachine: Ran 'mozilla.components.service.fxa.manager.Event$Progress$AccountRestored@e52218e' side-effects for state Active(progressState=CompletingAuthentication), got successive event CompletedAuthentication(authType=mozilla.components.concept.sync.AuthType$Existing@b6d61c8)
11-11 10:38:58.195 18083 18217 I FirefoxAccountStateMachine: Processing event 'CompletedAuthentication(authType=mozilla.components.concept.sync.AuthType$Existing@b6d61c8)' for state Active(progressState=CompletingAuthentication). Next state is Idle(accountState=Authenticated)
11-11 10:39:03.693 18083 18217 I FirefoxAccountStateMachine: Processing event 'AuthenticationError - RustSyncManager.sync' for state Idle(accountState=Authenticated). Next state is Active(progressState=RecoveringFromAuthProblem)
11-11 10:39:03.693 18083 18217 I FirefoxAccountStateMachine: Hit auth problem. Trying to recover.
11-11 10:39:03.808 18083 18217 I FirefoxAccountStateMachine: Able to recover from an auth problem.
11-11 10:39:03.808 18083 18217 I FirefoxAccountStateMachine: Ran 'AuthenticationError - RustSyncManager.sync' side-effects for state Active(progressState=RecoveringFromAuthProblem), got successive event mozilla.components.service.fxa.manager.Event$Progress$RecoveredFromAuthenticationProblem@7a72ea0
11-11 10:39:03.808 18083 18217 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Progress$RecoveredFromAuthenticationProblem@7a72ea0' for state Active(progressState=RecoveringFromAuthProblem). Next state is Idle(accountState=Authenticated)
```

## Scenario 2

  - Started from the end of scenario 1
  - Force-stop Fenix
  - On desktop, change my password
  - Start it up again
  - On startup, I didn't see the login to sync message, but maybe I just missed it
  - What I did see was "reconnect to sync"
  - I clicked that and entered the new password and was logged in
  - Adding a login and syncing with desktop worked successfully

Here are the logs this time around:
```
11-11 10:39:56.019 18302 18302 I FirefoxAccountStateMachine: Sync is enabled
11-11 10:39:56.601 18302 18438 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Account$Start@263c9cf' for state Idle(accountState=NotAuthenticated). Next state is Active(progressState=Initializing)
11-11 10:39:56.643 18302 18438 I FirefoxAccountStateMachine: Ran 'mozilla.components.service.fxa.manager.Event$Account$Start@263c9cf' side-effects for state Active(progressState=Initializing), got successive event mozilla.components.service.fxa.manager.Event$Progress$AccountRestored@3c411a7
11-11 10:39:56.644 18302 18438 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Progress$AccountRestored@3c411a7' for state Active(progressState=Initializing). Next state is Active(progressState=CompletingAuthentication)
11-11 10:39:56.644 18302 18438 I FirefoxAccountStateMachine: withServiceRetries: attempt 1/3
11-11 10:39:56.646 18302 18438 W FirefoxAccountStateMachine: Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@263c9cf' for state Active(progressState=CompletingAuthentication).
11-11 10:39:57.475 18302 18438 I FirefoxAccountStateMachine: Processing event 'AuthenticationError - get access token' for state Active(progressState=CompletingAuthentication). Next state is Active(progressState=RecoveringFromAuthProblem)
11-11 10:39:57.475 18302 18438 I FirefoxAccountStateMachine: Hit auth problem. Trying to recover.
11-11 10:39:57.564 18302 18438 I FirefoxAccountStateMachine: Unable to recover from an auth problem, notifying observers.
11-11 10:39:57.564 18302 18438 I FirefoxAccountStateMachine: Ran 'AuthenticationError - get access token' side-effects for state Active(progressState=RecoveringFromAuthProblem), got successive event mozilla.components.service.fxa.manager.Event$Progress$FailedToRecoverFromAuthenticationProblem@ca1e0
11-11 10:39:57.564 18302 18438 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Progress$FailedToRecoverFromAuthenticationProblem@ca1e0' for state Active(progressState=RecoveringFromAuthProblem). Next state is Idle(accountState=AuthenticationProblem)
11-11 10:39:57.565 18302 18438 W FirefoxAccountStateMachine: Couldn't populate SyncAuthInfoCache. Sync may not work.
11-11 10:39:57.565 18302 18438 W FirefoxAccountStateMachine: Is null? - accessToken: true, tokenServerUrl: true, accessToken.key: true
11-11 10:39:57.568 18302 18438 I FirefoxAccountStateMachine: Ran 'mozilla.components.service.fxa.manager.Event$Progress$AccountRestored@3c411a7' side-effects for state Idle(accountState=AuthenticationProblem), got successive event CompletedAuthentication(authType=mozilla.components.concept.sync.AuthType$Existing@22b3b5e)
11-11 10:39:57.568 18302 18438 W FirefoxAccountStateMachine: Got invalid event 'CompletedAuthentication(authType=mozilla.components.concept.sync.AuthType$Existing@22b3b5e)' for state Idle(accountState=AuthenticationProblem).
11-11 10:40:37.705 18302 18438 W FirefoxAccountStateMachine: Got invalid event 'mozilla.components.service.fxa.manager.Event$Progress$CancelAuth@9fca65e' for state Idle(accountState=AuthenticationProblem).
11-11 10:40:37.706 18302 18438 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Account$BeginEmailFlow@c0cdf0c' for state Idle(accountState=AuthenticationProblem). Next state is Active(progressState=BeginningAuthentication)
11-11 10:40:37.706 18302 18438 I FirefoxAccountStateMachine: withRetries: attempt 1/3
11-11 10:40:38.168 18302 18438 W FirefoxAccountStateMachine: Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@263c9cf' for state Active(progressState=BeginningAuthentication).
11-11 10:40:48.058 18302 18438 I FirefoxAccountStateMachine: Processing event 'AuthData(authData=authType: mozilla.components.concept.sync.AuthType$Signin@280c914, code: XXX, state: XXX, declinedEngines: null)' for state Active(progressState=BeginningAuthentication). Next state is Active(progressState=CompletingAuthentication)
11-11 10:40:48.059 18302 18438 I FirefoxAccountStateMachine: withRetries: attempt 1/3
11-11 10:40:48.879 18302 18438 I FirefoxAccountStateMachine: withRetries: attempt 1/3
11-11 10:40:49.110 18302 18438 I FirefoxAccountStateMachine: Ran 'AuthData(authData=authType: mozilla.components.concept.sync.AuthType$Signin@280c914, code: XXX, state: XXX, declinedEngines: null)' side-effects for state Active(progressState=CompletingAuthentication), got successive event CompletedAuthentication(authType=mozilla.components.concept.sync.AuthType$Signin@280c914)
11-11 10:40:49.110 18302 18438 I FirefoxAccountStateMachine: Processing event 'CompletedAuthentication(authType=mozilla.components.concept.sync.AuthType$Signin@280c914)' for state Active(progressState=CompletingAuthentication). Next state is Idle(accountState=Authenticated)
11-11 10:40:49.177 18302 18438 W FirefoxAccountStateMachine: Got invalid event 'mozilla.components.service.fxa.manager.Event$Account$Start@263c9cf' for state Idle(accountState=Authenticated).
```

**Comment by grigoryk** [comment]
Looking at the logs in scenario 1, it looks like we attempted to sync, which failed due to an auth problem (likely, sync machinery is accessing scoped keys in the persisted state via `from_json` which [you modified](https://github.com/bendk/application-services/commit/08709e1ad04b7316ea38310d7f2361289c26f04b)?), which triggered a recovery flow.

However, I don't think that's not what will actually happen when we encounter this issue in the wild. With the null-check proposed in https://github.com/mozilla-mobile/android-components/pull/11271 we won't populate the auth cache at all, and so we'll never try to sync (see [this check](https://github.com/mozilla-mobile/android-components/blob/72d04d0064d95e58dcad3fde73300aa93c9c0932/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt#L370)). We'll just bail out of the worker.

I suspect in your case a recovery flow worked out well because your device/account isn't affected by the underlying issue. Whatever the issue is, it doesn't _appear_ to be rooted in the clients? At least, I couldn't find a spot where we might be dropping a `key` we're getting from the server on the floor. It really does appear that we're getting access tokens shaped in the way we don't quite expect (e.g. should have a key, but doesn't).

In practice, I think, with the null-check in place, it'll just look like there's a signed-in account, but it would never manage to complete a sync. This null-check would also introduce a loop. If we assume that every time an affected client fetches an access token for `SCOPE_SYNC`, they will get one without a `key`, then this means that on every app startup and a "sync now" attempt we'll try to re-fetch these access tokens, again and again. Before, these clients would just crash at first attempt, but now they'll keep retrying.

**Comment by kbrosnan** [comment]
Not seeing any recent crashes mentioning [OAuthScopedKey](https://crash-stats.mozilla.org/search/?java_stack_trace_raw=~OAuthScopedKey&product=Fenix&date=%3E%3D2022-02-02T21%3A14%3A00.000Z&date=%3C2022-02-09T21%3A14%3A00.000Z&_facets=signature&_sort=-date&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature). Everything seems to be 95 or earlier.
