### ISSUE TITLE
BrowserStore: Dispatch an init action that a Middleware can react to

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8529]
Some `Middleware` needs to do some initialization. For example loading data from disk and then dispatching an action to add the data to the state. The `Middleware` cannot do that on its own because it first needs a reference to the store. We solved this by introducing init actions.. but then every `Middleware` needs its own. Instead the store could dispatch a generic init action that every interested `Middleware` can listen to.

**Comment by pocmo** [comment]
From #8509:
- feature-accounts
- feature-addons
- feature-containers
- feature-readerview
- feature-session
- support-webextensions

**Comment by Amejia481** [comment]
`feature-downloads` it's doing too!
