### ISSUE TITLE
Intermittent-test PinnedSitesStorageTest#testAddingAllDefaultSites

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8533]

**Comment by jonalmeida** [comment]
@Amejia481 do you have a link to a task build and/or logs of the failure?

**Comment by Amejia481** [comment]
Sorry about that https://firefoxci.taskcluster-artifacts.net/WxLyKbCLTju6rspcU6XK_g/0/public/logs/live_backing.log. I try to run  it locally and it run forever

**Comment by pocmo** [comment]
I already filed this: https://github.com/mozilla-mobile/android-components/issues/8471
