### ISSUE TITLE
Optimize multi dispatch, specifically SessionManager.restore()

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8535]
We see `SessionManager.restore()` take quite some time. This is primarily caused by us doing a lot of sync dispatch calls. There are multiple options how we could fix that. The obvious choice is to let restore() use batch actions. Another option may be to have a generic `batch { }` that will group actions together and perform them in order - assuming that most of the overhead comes from the context switches.

**Comment by mcomella** [comment]
iiuc, this work is for addressing the slowdown that occurs for having many tabs open on cold startup https://github.com/mozilla-mobile/android-components/issues/7304
