### ISSUE TITLE
[Bug] Scan message is not cleared when using default scanMessage = null value.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#8537]
Fenix issue:https://github.com/mozilla-mobile/fenix/issues/15431.
We should change the code to allow the `showMessage` to be called for `null` values in order to clear scan message on current instance of `QrFragment`.

**Comment by csadilek** [comment]
Closed by: https://github.com/mozilla-mobile/android-components/pull/8558/
