### ISSUE TITLE
[Spike] Investigate null ACTION_DOWN event in BrowserGestureDetector

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#8552]
In https://github.com/mozilla-mobile/android-components/issues/8356 we saw many reports about the first MotionEvent that started scrolling being null [here](https://github.com/mozilla-mobile/android-components/blob/f93ad419789d1e02db6ab52e2f6326d79e0b1a44/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt#L160).
Something that should be impossible as that event should be the ACTION_DOWN event that precedes all other MotionEvents.

I mainly though about the following scenarios in which this might happen:
- user starts the touch on other apps / widgets (that would get also the ACTION_DOWN) and then slides the finger to our app - possible in "split mode". 
When testing I saw that our app still gets the ACTION_DOWN first before any other events.
- some other part of the app consumes the ACTION_DOWN event.
We send the complete stream of events as received in [BrowserToolbarBottomBehavior#onInterceptTouchEvent](https://github.com/mozilla-mobile/android-components/blob/f93ad419789d1e02db6ab52e2f6326d79e0b1a44/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBottomBehavior.kt#L132) to [BrowserGestureDetector#handleTouchEvent](https://github.com/mozilla-mobile/android-components/blob/f93ad419789d1e02db6ab52e2f6326d79e0b1a44/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt#L100) so ACTION_DOWN should always get passed to the GestureDetector.
- the MotionEvent gets recycled along the way. 
IIUC recycling just means marking the event for reuse, not nulling it.

I could just artificially reproduce this - by not sending ACTION_DOWN but all the other events.
IRL I didn't encountered this as much as I've tried.
There are user reports but no comments in Socorro about possible STRs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7411)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795399

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
