### ISSUE TITLE
Upstream media UI tests from Fenix.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8556]
When trying to bump the AC version in Fenix we found a media regression in GeckoView:
- https://github.com/mozilla-mobile/fenix/pull/15459
- https://github.com/mozilla-mobile/fenix/pull/15517

That's awesome. If we upstream a version of those tests then we may have a chance catching this already when bumping the GV version in AC.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7414)

**Comment by csadilek** [comment]
This will no longer be needed post repo migration. We'll run integration tests with the GV upgrade.
