### ISSUE TITLE
Refactor DownloadMiddleware to use new InitAction

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#8569]
In https://github.com/mozilla-mobile/android-components/issues/8529 we have introduced a new action that can be observed to trigger initialization code in middlewares. Let's refactor `DownloadMiddleware` to use it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7424)

**Comment by pocmo** [comment]
We also have `RecentlyClosedAction.InitializeRecentlyClosedState` and `ContainerAction.InitializeContainerState`.

**Comment by csadilek** [comment]
> We also have RecentlyClosedAction.InitializeRecentlyClosedState and ContainerAction.InitializeContainerState.

@pocmo 👍 Filed https://github.com/mozilla-mobile/android-components/issues/8568 and https://github.com/mozilla-mobile/android-components/issues/8570 as well.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792936

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
