### ISSUE TITLE
Sample Browser sample:about does not work

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#8574]
Was testing this Interceptor response and this doesn't seem to work anyone. 

I think it first needs: 
`override fun interceptsAppInitiatedRequests(): Boolean = true`

But then I'm not sure this type of Content return is valid anymore either... 🤔 

https://github.com/mozilla-mobile/android-components/blob/master/samples/browser/src/main/java/org/mozilla/samples/browser/request/SampleRequestInterceptor.kt#L29

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7428)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795398

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
