### ISSUE TITLE
[Bug] PWA: window.matchMedia('(display-mode: x)').matches doesn't return the correct display-mode

### ISSUE THREAD

**Issue by scanline** [mozilla-mobile/android-components#8584]
### Overview

With the help of a manifest file [manifest file](https://developer.mozilla.org/en-US/docs/Web/Manifest) it's possible to install a website on a device's homescreen.
To further enhance the look and feel of a 'real' application, the manifest accepts a [display](https://developer.mozilla.org/en-US/docs/Web/Manifest/display) member which controls the display mode of the PWA. Possible values are: **fullscreen**, **standalone**, **minimal-ui** and **browser**. For this test case I've used standalone and fullscreen.

To distinguish between the installed application started using the homescreen icon and the website running inside the browser, it is recommended to query [matchMedia ](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) on the window object for display-mode.

### Expected behaviour

The boolean value returned by e.g. `window.matchMedia('(display-mode: standalone)').matches` should return true if the display member has been set to **standalone** in the manifest file.
Likewise `window.matchMedia('(display-mode: fullscreen)').matches` should be true if display has been set to **fullscreen**.

### Actual behavior

Firefox for Android 81.0 returns **false** in both cases. A query for `display-mode: browser` always returns true even though:
- it has been started from the home screen
- display-mode has been set to either fullscreen or standalone

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7434)

**Comment by dlecan** [comment]
Do you know a workaround?

**Comment by scanline** [comment]
Unfortunately I'm not aware of a workaround dlecan.

**Comment by dlecan** [comment]
This is a blocking issue for our app, as the UX is not the same if the application is browsed from the web or from the homescreen.

Our workaround is to provide a specific `start_url` for Firefox users, so the application can detect it is opened from the homescreen.

**Comment by spookylukey** [comment]
Just as a note for anyone searching - this bug also means that display-mode media queries like this have no effect:
```css
@media all and (display-mode: standalone) {
    // rules here
}
```
Only using ``display-mode: browser` will work.

I've confirmed with PWAs using both `standalone` and `fullscreen`.

**Comment by Tardo** [comment]
Any news here? This problem is really annoying and blocking...

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796434

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
