### ISSUE TITLE
Access token is always requested with ttl=0

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#8590]
[getAccessToken](https://github.com/mozilla/application-services/blob/eb929192854b09d5fa06136f754dc8b54ef4b2f1/components/fxa-client/android/src/main/java/mozilla/appservices/fxaclient/FirefoxAccount.kt#L298) in a-s defaults its `ttl: Long? = null` param, and passes on a 0 value if it's null.

In a-c, we're not explicitly passing any value for `ttl`, so we'll end up using 0 for our access token ttl.

[fxa api docs](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-oauthtoken) for this are not very helpful (e.g. what happens when 0 is specified?)
```
ttl: number.integer.min(0), optional The desired lifetime of the issued access token, in seconds. The actual lifetime may be smaller than requested depending on server configuration, and will be returned in the expired_in property of the response.
```

Actual ttl for the granted tokens is probably _not_ zero, since they wouldn't work at all. Perhaps the auth server clamps this to some low value in case it sees 0?

Also, IIUC, this means we're not actually using the scoped access token cache in a-s, or not using it as effectively, since they'll likely always be expired.

TODO verify that we end up requesting new access tokens whenever we need them (e.g. to sync).

cc @rfk

**Comment by rfk** [comment]
IIUC, the FFI bindings [reinterpret zero back into `None`](https://github.com/mozilla/application-services/blob/eb929192854b09d5fa06136f754dc8b54ef4b2f1/components/fxa-client/ffi/src/lib.rs#L344) for the Rust `Option` type, so I think we should be OK here. Worth us double-checking end-to-end though!

**Comment by grigoryk** [comment]
@rfk and it does seem like serde will then omit this value while serializing for the server payload. So what happens in that case, server assumes a default value for ttl?

Once we verify that this does indeed work as expected, let's at least document this at the API layer to avoid confusing ourselves (or, just me!) again in the future :)

**Comment by rfk** [comment]
> So what happens in that case, server assumes a default value for ttl?

Yes; I believe that default can range between 6 hours and 48 hours, and allowing the server to control it seems reasonable to me.

>  let's at least document this at the API layer 

+100

**Comment by rfk** [comment]
I would be happy for this to move to a documentation bug over in a-s if that works for you.

**Comment by grigoryk** [comment]
> I would be happy for this to move to a documentation bug over in a-s if that works for you.

👍 👍
