### ISSUE TITLE
[Spike] Investigate promotion of specific add-ons in main browser menu.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#8593]
For the moment we have only the case of the "Report site issue" add-on: https://github.com/mozilla-mobile/fenix/issues/11631.

Can we expect to have more of this, so we should implement a new property in `WebExtensionState` or should we treat it as an exception and handle it directly in code? 

Either way I think we should use the menu item properties (icon, name, action) in the main browser menu. Although in the case of this add-on we already have an issue related to the icon: (https://github.com/mozilla-mobile/fenix/issues/11367)

@Amejia481 or anyone with knowledge on this subject, I would appreciate an input to make sure we go with the most reliable solution for this.  TY!

**Comment by Amejia481** [comment]
I think is going to depend on from where we are getting the list of important exts.  I think the app (Fenix) is going to be the provide a list of ext ids,  right? In that case, one way could be to add a list of promoted ext ids to [WebExtensionBrowserMenuBuilder](https://github.com/mozilla-mobile/android-components/blob/d96b2318847691afee0dfd2dd1cf8d25c258792a/components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt#L33) and with it give a preferential placement in the menu to all the ids that are in the list.

Also tagging @csadilek for his input :)

**Comment by denschub** [comment]
Two and a half cents from our point of view.

We'd be fine with more Kotlin source in our component to have a native UI integration if that's needed, or if that is what's best. Building the native UI would even have a benefit, as that would allow us to make the menu item more easily translatable. i18n inside WebExtensions isn't too much fun, and our current solution we ship to Desktop relies on build-time magic, so does not work in android-components. Native UI in Kotlin would allow us to use the existing android strings logic, as well as the i18n system y'all have already set up.

But I don't really have a strong opinion either way. The only request I have is to keep changes to the WebExtension code itself minimal. While changes to the "glue code" don't matter, we try to keep the WebExtension source as close to the Desktop sources as possible. We're happy to compromise, though. :)

**Comment by csadilek** [comment]
Yes, I would also try and pass a configuration to `WebExtensionBrowserMenuBuilder`. This configuration needs to map extension IDs to positions in the root menu. Then this configuration, if present, will serve as an override of the default behaviour for the specified extension. (We might also need to differentiate between browser and page actions.)

Either way this should *not* affect add-on/extension code or its feature modules (e.g. feature-webcompat*). This should really be an (optional) application-specific customization.

**Comment by mcarare** [comment]
As a conclusion, I guess the consensus is that the changes should be handled in the app, and not to touch any of the properties of the extension. This would mean that the handling will be made by checking the `id` and assigning a `promotable` property to te `WebExtensionBrowserMenuItem`. 
Is `id` a reliable property of extensions, not subject to frequent changes?

As for the position in the main menu where the extension / extensions should be inserted, at a first glance I think that it s to be handled inside `WebExtensionBrowserMenuBuilder` and not be passed by the client (Fenix). This would, however require a change in AC almost each time the Menu in Fenix adds or removes an element. For the moment, as we have only a extensions that needs to be promoted, I will not add a property for the position the extension is to be promoted. 

I will submit a draft PR soon, any additional thoughts until then? 

Thank you all for your input!

**Comment by Amejia481** [comment]
>  Is id a reliable property of extensions, not subject to frequent changes?

Yes, it's reliable source :)

> As a conclusion, I guess the consensus is that the changes should be handled in the app, and not to touch any of the properties of the extension. This would mean that the handling will be made by checking the id and assigning a promotable property to te WebExtensionBrowserMenuItem.
> Is id a reliable property of extensions, not subject to frequent changes?

Only one comment,I think instead of the `promotable` property  be on `WebExtensionBrowserMenuItem` it should be a list on `WebExtensionBrowserMenuBuilder` as it is the api that Fenix(apps) uses to configure how the extension items should look like in the menu. If I misunderstanding something please let me know.

**Comment by mcarare** [comment]
> 
> Only one comment,I think instead of the `promotable` property be on `WebExtensionBrowserMenuItem` it should be a list on `WebExtensionBrowserMenuBuilder` as it is the api that Fenix(apps) uses to configure how the extension items should look like in the menu. If I misunderstanding something please let me know.

Yes, the list will be in `WebExtensionBrowserMenuBuilder` but the delimitation between promotable extensions and other ones would be made inside `getOrUpdateWebExtensionMenuItems`, based on the `id`. This way we could easily add other extension in the future, if needed. 
I also worked out a way to receive the placement from Fenix by using a custom `BrowserMenuItem` in the  `items` used in `WebExtensionBrowserMenuBuilder`. Otherwise there would be no reliable way to place it in both top and bottom toolbar order of items.

**Comment by Amejia481** [comment]
> > Only one comment,I think instead of the `promotable` property be on `WebExtensionBrowserMenuItem` it should be a list on `WebExtensionBrowserMenuBuilder` as it is the api that Fenix(apps) uses to configure how the extension items should look like in the menu. If I misunderstanding something please let me know.
> 
> Yes, the list will be in `WebExtensionBrowserMenuBuilder` but the delimitation between promotable extensions and other ones would be made inside `getOrUpdateWebExtensionMenuItems`, based on the `id`. This way we could easily add other extension in the future, if needed.
> I also worked out a way to receive the placement from Fenix by using a custom `BrowserMenuItem` in the `items` used in `WebExtensionBrowserMenuBuilder`. Otherwise there would be no reliable way to place it in both top and bottom toolbar order of items.

Thanks for the clarification 👍

**Comment by pocmo** [comment]
Closing: Assuming this is done with the code that landed.
