### ISSUE TITLE
Plural strings are not plural

### ISSUE THREAD

**Issue by SafaAlfulaij** [mozilla-mobile/android-components#8605]
Hi.

The strings with these IDs are not in the plural form:

- mozac_feature_addons_permissions_one_extra_site_description
- mozac_feature_addons_permissions_extra_sites_description
- mozac_feature_addons_permissions_one_extra_domain_description
- mozac_feature_addons_permissions_extra_domains_description_plural
- mozac_feature_addons_updater_notification_content
- recently_closed_tabs
- recently_closed_tab
- history_delete_some
- create_collection_save_to_collection_tabs_selected
- create_collection_save_to_collection_tab_selected
- preferences_delete_browsing_data_tabs_subtitle
- preferences_delete_browsing_data_browsing_data_subtitle
- preferences_delete_browsing_data_browsing_history_subtitle
- about_debug_menu_toast_progress
- tab_counter_content_description_one_tab
- tab_counter_content_description_multi_tab

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7450)

**Comment by pocmo** [comment]
Unfortunately our tooling doesn't support proper plural forms.

(CC @Delphine)

**Comment by Delphine** [comment]
Correct: localizers unfortunately will have to modify plural strings in order to adapt them to their locale. For example an English string such as "Delete %1$d items" (where %1$d is the number of items you have selected), can be adapted to "Items to delete: %1$d".
