### ISSUE TITLE
[Bug] TWA is missing Referrer

### ISSUE THREAD

**Issue by Andrew67** [mozilla-mobile/android-components#8611]
## Steps to reproduce
- Set Firefox as the default web browser.
- Install a TWA (using https://play.google.com/store/apps/details?id=com.andrew67.ddrcalc in this case).
- Open the TWA, which opens in Firefox.
- Tap the 3-dot menu, then tap About.

### Expected behavior
- The version displayed is "Version 4.0.0g". (the g suffix is the important part, version number may differ in the future)

### Actual behavior
- The version displayed is "Version 4.0.0".

### Device information

* Android device: Samsung Galaxy Note 9, Android 10
* Fenix version: 99.2.0

### More details
- The two items in the expected/actual behavior above are controlled by this line of JavaScript: `document.referrer.startsWith('android-app://com.andrew67.ddrcalc/')`.
- Chrome currently sets `android-app://<packageName>/` as the referrer (`/` added in Chrome 81). TWA apps such as mine use that to toggle a boolean to perform modifications that ensure compliance with Google Play (or whichever store the TWA is uploaded to) rules. Some apps may also take this as a sign they can call intents into native code (for things such as taking payments via Google Play Billing).
- Here's an example where the referrer is being added to the WebView fallback for TWAs in Google's `android-browser-helper` library: https://github.com/GoogleChrome/android-browser-helper/issues/15#issuecomment-703217916

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7456)

**Comment by openlex** [comment]
Is there any solution?

**Comment by Andrew67** [comment]
Updated to remove "Privacy Policy" from reproduction steps as I intend to remove that, and updated other numbers (Fenix version number, added `/` to referrer.startsWith blurb).

@openlex yeah I haven't been contacted at all. We could add a query parameter to our TWA launcher but I'm worried that starts appearing in the browser history and I don't want to trigger the store TWA behavior in that case.

**Comment by jonalmeida** [comment]
We never had full TWA support because it required external requirements from Play Services which were never fulfilled so this bug is invalid. We have also removed the TWA pieces from Fenix for now as well.
