### ISSUE TITLE
Reader mode escapes title which displays HTML entities in Fenix

### ISSUE THREAD

**Issue by gaul** [mozilla-mobile/android-components#8622]
@csadilek added HTML escaping to titles in b647b4f06c0a4fd4b791bec449224a05a4afd6dd.  This makes Fenix display the HTML entities in the Fenix tab list.  Is this intentional?  Should Fenix interpret these?

![2020-10-06 11 12 03](https://user-images.githubusercontent.com/848247/95192244-de787c80-080c-11eb-8824-45b7387c5ae5.png)
![2020-10-06 11 12 25](https://user-images.githubusercontent.com/848247/95192248-e0424000-080c-11eb-8da8-d4db4bcf92a0.png)

**Comment by csadilek** [comment]
Thanks for filing @gaul! Yes, escaping was done on purposes an seems to work fine on the reader page itself, but as you pointed out, we need to "unescape" for other components.
