### ISSUE TITLE
Include GV SHA version in AC's .pom repository

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/android-components#8631]
GeckoView's .pom file has the mozilla-central SHA1 commit ID, e.g.

```
<scm>
<connection>scm::hg::https://hg.mozilla.org/mozilla-central</connection>
<tag>5380e007a12cb5081a14736d7e00885c57f42129</tag>
</scm>
```

it would be nice if AC included this piece of information so that we could tell exactly what version of GV is included in an AC build.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7471)

**Comment by mcomella** [comment]
Maybe helpful: this is how we published ac's git hash in its POM: https://github.com/mozilla-mobile/android-components/pull/8384

> it would be nice if AC included this piece of information so that we could tell exactly what version of GV is included in an AC build.

If you check out an ac commit locally, you can also run the `tools/list_compatible_dependency_versions.py` script to determine the GV hash associated with the nightly ac build associated with the currently checked out ac commit.

**Comment by pocmo** [comment]
The AC pom (of the specific gecko-engine package) contains the GV build version, which let's you get the associated GV pom with the commit.

```XML
<dependency>
  <groupId>org.mozilla.geckoview</groupId>
  <artifactId>geckoview-nightly</artifactId>
  <version>83.0.20201006041051</version>
  <scope>compile</scope>
</dependency>
```

It's two steps, but at least possible already.

**Comment by csadilek** [comment]
I think we have everything we need here now. We have since added the GV version to both Fenix and Focus Nightly About screens, and we have `tools/list_compatible_dependency_versions.py` for local development.
