### ISSUE TITLE
getProvidedDefaultSearchEngine raises java.lang.IndexOutOfBoundsException when list is empty

### ISSUE THREAD

**Issue by jwhitlock** [mozilla-mobile/android-components#8638]
There's several instances of ``java.lang.IndexOutOfBoundsException`` raised in Fenix 81.1.x:

https://crash-stats.mozilla.org/signature/?product=Fenix&signature=java.lang.IndexOutOfBoundsException%3A%20at%20java.util.ArrayList.get%28ArrayList.java%29&date=%3E%3D2020-09-29T20%3A03%3A00.000Z&date=%3C2020-10-06T20%3A03%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1

It appears to be this code, which would fail if searchEngineList is empty:

https://github.com/mozilla-mobile/android-components/blob/60c47df97a4aa6eb259892e85bcd6693a70eefdb/components/browser/search/src/main/java/mozilla/components/browser/search/SearchEngineManager.kt#L144-L145

It seems like the intent of the code is to return the default, so it may be a quick fix, for this and ``getProvidedDefaultSearchEngineAsync``:

```kotlin
return searchEngineList.default ?: searchEngineList.list.firstOrNull()
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7475)

**Comment by pocmo** [comment]
The problem with this small change is, that `getProvidedDefaultSearchEngine()` returns `SearchEngine` and not a nullable `SearchEngine?`. If we change that then this may have a ripple effect on other code and Fenix. Afaik Fenix is currently not expecting a default search engine to not exist. So I fear that we may end up refactoring the current mess in Fenix ([which well start to replace soon](https://github.com/orgs/mozilla-mobile/projects/63)).

**Comment by jonalmeida** [comment]
This search engine component no longer exists; so we can close this bug as won't fix.
