### ISSUE TITLE
HTML tags are not stripped from the summary in the add-ons list

### ISSUE THREAD

**Issue by Rob--W** [mozilla-mobile/android-components#8651]
Although there is logic to [strip HTML tags from the add-on description](https://github.com/mozilla-mobile/android-components/blob/6ae25079c9e5386353ddcf6b0810a34be9dd2649/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonDetailsActivity.kt#L126-L129), the same [cannot be said for the addon summary](https://github.com/mozilla-mobile/android-components/blob/5c2559da76130619601902d22603083c39e45550/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt#L210). Consequently, if the summary contains HTML (e.g. `<a>` tags), it will be shown:

![](https://user-images.githubusercontent.com/1365071/95470063-a2662880-0980-11eb-940b-c98e84572781.png)

The fact that the summary can contain HTML is not clearly documented, and I filed an issue for that at https://github.com/mozilla/addons-server/issues/15669

Since I am a co-author of the above recommended extension, I intend to remove the HTML from the summary before the 82 release of Fenix. I'll keep the summary as it is right now, to make it easier to reproduce/test this issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7487)

**Comment by Amejia481** [comment]
Thanks for reporting!

**Comment by Rob--W** [comment]
Can I clean up the add-on summary or would you like to keep it around to make debugging/testing easier?

I'm going to clean the add-on summary before the Fenix 82 release, but if you don't need it or can't work on it now, I may as well clean the summary now.

**Comment by Amejia481** [comment]
> Can I clean up the add-on summary or would you like to keep it around to make debugging/testing easier?
> 
> I'm going to clean the add-on summary before the Fenix 82 release, but if you don't need it or can't work on it now, I may as well clean the summary now.

Thanks @Rob--W, feel free to proceed with the clean up, we have other alternative to reproduce the issue :)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796309

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
