### ISSUE TITLE
send structured java stack trace in crash reports to Socorro

### ISSUE THREAD

**Issue by willkg** [mozilla-mobile/android-components#8653]
Currently, the crash reporter sends a `JavaStackTrace` crash annotation to Socorro which is a single string containing the exception and traceback. I'm pretty sure the structure of that string has changed over the years, I don't have a good parser for it, and it's really hard to extract useful data from it to have parity with C/C++/Rust crashes on Crash Stats.

It'd be great to have a structured form for Java stack traces.

The Sentry Java client sends exception information in a structured form:

* format: https://develop.sentry.dev/sdk/event-payloads/exception/
* stack trace format: https://develop.sentry.dev/sdk/event-payloads/stacktrace/
* notes on variable sizes: https://develop.sentry.dev/sdk/data-handling/#variable-size

Maybe we can re-use that format as a JSON-encoded crash annotation value?

If we add a new crash annotation with a JSON-encoded structure, then we could do things like display the stack better (links to source files?), generate better crash signatures ([bug 1541120](https://bugzilla.mozilla.org/show_bug.cgi?id=1541120)), support Android mappings and retracing ([bug 1642655](https://bugzilla.mozilla.org/show_bug.cgi?id=1642655)), and possibly other things.

**Comment by rocketsroger** [comment]
Server side change https://bugzilla.mozilla.org/show_bug.cgi?id=1671654
