### ISSUE TITLE
Remove log statements introduced for FNPRMS

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#8662]
FNPRMS is relying on log statements emitted from `onPageStart/onPageStop`. These can be removed once FNPRMS is replaced.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXP-1382)

**Comment by mcomella** [comment]
Note: we're still using this to measure timeToNavStart for `fenix/measure_start_up.py`, our temporary replacement for mozperftest while that project is awaitng resources.

**Comment by mcomella** [comment]
Triage: we use these to write low overhead performance measurements in `measure_start_up.py` and I don't see this style of perftest going anywhere soon so closing.
