### ISSUE TITLE
Create a persistent logging component

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8664]
A new component called `lib-log` for recording logs and storing them in a database. ✨

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7493)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793198

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
