### ISSUE TITLE
Create a Room database for storing logs

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8665]
| Columns      | Description                                                  | Type    |
| ------------ | ------------------------------------------------------------ | ------- |
| id    | Primary key for each log line.              | Long    |
| timestamp    | The time when the log event had occurred.                    | Long    |
| recording_id | A random UUID generated at the start of a log recording.     | String  |
| severity     | The priority of the log statement. See Android's [Log](https://developer.android.com/reference/android/util/Log#ERROR) constants. | Char    |
| tag          | Used to identify the source of a log message.  It usually identifies the class or activity where the log call occurs. | String? |
| log          | The message you would like logged.                           | String? |
| throwable    | Optional. An exception to log.                               | String? |

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7494)

**Comment by grigoryk** [comment]
We also probably want a `recordings` table: `id`, `start_timestamp: Long`, `end_timestamp: Long?`

`recording_id` then becomes an FK to this.

This will allow us to eventually expand on the `recordings` concepts, build out some UI around managing them, store additional metadata (such as screenshots), etc.

**Comment by jonalmeida** [comment]
Do we need the start and end timestamp? With a unique ID, we should be able to select all the rows with that ID.

**Comment by jonalmeida** [comment]
Room has useful type converters with examples for Date <-> Long: https://developer.android.com/training/data-storage/room/referencing-data

```kotlin
class Converters {
    @TypeConverter
    fun fromTimestamp(value: Long?): Date? {
        return value?.let { Date(it) }
    }

    @TypeConverter
    fun dateToTimestamp(date: Date?): Long? {
        return date?.time?.toLong()
    }
}
```

**Comment by jonalmeida** [comment]
I added the `id` column to the table since we need that to allow for deleting log lines and we were also missing a primary key for the table.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793197

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
