### ISSUE TITLE
Remove DefaultSearchEngineProvider interface and use BrowserStore directly

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8686]
PR #8680 will introduce a `DefaultSearchEngineProvider` interface to temporarily allow using `SearchEngineManager` or `BrowserStore` as the source for search engines. The goal is to migrate all applications to exclusively use `BrowserStore`. After that we can remove the interface again and make all our components use `BrowserStore` directly as well.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7506)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796451

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
