### ISSUE TITLE
Add Fenix-like StrictMode config to sample browser

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8694]
I just ran into a strict mode violation in Fenix for a new piece of AC code. If we have a similar config for sample browser then the chance is higher that we catch that earlier.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7514)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795394

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
