### ISSUE TITLE
SystemEngineView: Do we need to set WebView to invisible?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#870]
Follow-up from #828: We are setting the WebView to INVISIBLE instead of GONE now. Do we really need that now that we are setting MATCH_PARENT layout params on the fullscreen view?

https://github.com/mozilla-mobile/android-components/blob/master/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt#L301-L321

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7520)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796481

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
