### ISSUE TITLE
Add dividers for sections in add-ons list.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#8703]
Fenix initial issue: https://github.com/mozilla-mobile/fenix/issues/15919

**Comment by mcarare** [comment]
@Amejia481 Should we add dividers by default in AC, or should the client decide if it shows dividers, maybe by passing this choice in `AddonsManagerAdapter`  through `style`?

**Comment by Amejia481** [comment]
We could added it by default have the option to opt-out through style!

**Comment by Amejia481** [comment]
Closed by https://github.com/mozilla-mobile/android-components/commit/2f621b91d3c60b8a350fa27da14bb08d37005671
