### ISSUE TITLE
Update REPLACED_UNSAFE_CONTENT with REPLACED_TRACKING_CONTENT

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8705]
Geckoview renamed REPLACED_UNSAFE_CONTENT to REPLACED_TRACKING_CONTENT, we need to update on gecko nightly for more related info see  https://bugzilla.mozilla.org/show_bug.cgi?id=1669731

**Comment by pocmo** [comment]
Change landed in GeckoView Nightly and I suppressed the warning in https://github.com/mozilla-mobile/android-components/commit/5cd371eebc9e2dfef8cc45472dd52a72b5a36558 to update to the latest GeckoView.

**Comment by pocmo** [comment]
Closing: Looks like this landed.
