### ISSUE TITLE
GeckoView: REPLACED_UNSAFE_CONTENT is deprecated

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8709]
> w: /Users/sebastiankaspari/Projects/Mozilla/android-components/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt: (698, 15): 'REPLACED_UNSAFE_CONTENT: Int' is deprecated. Deprecated in Java

**Comment by pocmo** [comment]
Suppressed deprecation in https://github.com/mozilla-mobile/android-components/pull/8706

**Comment by pocmo** [comment]
@Amejia481 Do you know what the right replacement is? Maybe that's something small for the next sprint? For now I suppressed the warnings.

**Comment by Amejia481** [comment]
The replacement is `REPLACED_TRACKING_CONTENT`, if you want  I can do it or if you prefer to do it either way it's OK for me :) 
I filed this issue for it this morning 😅  https://github.com/mozilla-mobile/android-components/issues/8705

**Comment by Amejia481** [comment]
Suppressing the warnings is OK too!

**Comment by pocmo** [comment]
Okay, in this case I close this issue here in favor of #8705.
