### ISSUE TITLE
Investigate phasing out JavaStackTrace for Socorro crash reports

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#8726]
Recently `JavaException` was added to Socorro crash reports.  We should investigate in if `JavaStackTrace` annotation should be phased out.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7545)

**Comment by rocketsroger** [comment]
related to https://github.com/mozilla-mobile/android-components/issues/8653

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792902

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
