### ISSUE TITLE
Broken Padlock appears briefly for TLS-protected websites

### ISSUE THREAD

**Issue by RussellAult** [mozilla-mobile/android-components#8728]
### Software version

Fennec F-Droid 81.1.3 (which, despite the name, is based on Fenix).

### Steps to Reproduce

Go to a web address starting with "https" (or do a search with any of the built-in search engines).

### Expected results

Padlock icon appears in awesomebar.

### Actual results

Broken Padlock icon appears briefly, and is then replaced by a Padlock icon.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7547)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795393

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
