### ISSUE TITLE
Taskcluster: Current JDK version 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 has a bug

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8735]
Saw this on taskcluster:

> [task 2020-10-19T07:43:28.992Z] warning: Current JDK version 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01 has a bug (https://bugs.openjdk.java.net/browse/JDK-8007720) that prevents Room from being incremental. Consider using JDK 11+ or the embedded JDK shipped with Android Studio 3.5+.

We probably do not care about incremental builds on taskcluster, since we are not using a build cache in automation yet. But maybe we want to update the JDK anyways eventually.

**Comment by jonalmeida** [comment]
JDK updated! 🎉
