### ISSUE TITLE
feature-media: contains references to both AndroidX and old support library.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8739]
Saw this in the Fenix build logs:

> WARNING: [Processor] Library '/Users/sebastiankaspari/.gradle/caches/modules-2/files-2.1/org.mozilla.components/feature-media/63.0.20201019090011/2daeecf360567378b69504c7e28906209a6d44e3/feature-media-63.0.20201019090011.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.

The only dependency I can see is media from Android X. Maybe just a version bump is needed?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7556)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796367

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
