### ISSUE TITLE
Provide API to observe that new add-ons are available

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#8742]
In https://github.com/mozilla-mobile/fenix/issues/11326 we want to use Fenix's CFR functionality to let *all* users know when new add-ons become available. We need to expose some API for this e.g. via the `AddonCollectionProvider` which could relatively easily compare new results with the previous one (we have it cached) and invoke a callback or similar.

**Note**: This is different than the functionality provided by our `SupportedAddonsChecker`, which notifies migrated users via a system notification when previously supported add-ons (which were disabled during migration) become available.

Here we want to use CFR to have a way to indicate to **all users** (not just migrated ones) that new add-ons are available, independent of whether or not users already have this add-on installed.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7561)

**Comment by Amejia481** [comment]
As the `SupportedAddonsChecker` creates a notification, do we want to have a way to disable the notification when this feature is present? Or Doesn't matter to have both at the same time?

**Comment by csadilek** [comment]
@Amejia481 Yes, the two features can co-exist, I think. One is to let the user know that an add-on they have already installed is now enabled and functional, the other feature is more of a general "What's new in Fenix" :).

**Comment by Amejia481** [comment]
Thanks for the clarification!

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795963

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
