### ISSUE TITLE
Remove OneTimeFxaPushReset from FxaPushSupportFeature

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8745]
We needed this in Fenix Nightly to reset our push subscriptions to follow a new FxA push subscription format. Now that we're comfortable with everyone having migrated, we can remove this code from [`FxaPushSupportFeature`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt#L318) and it's usages.

**Comment by asadkhalid305** [comment]
Hey, I would like to work on this. Please assign this to me.
