### ISSUE TITLE
onProgress only called with values 15 and 100

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#8746]
This is a regression in GeckoView 82/83: https://bugzilla.mozilla.org/show_bug.cgi?id=1672046

In 81 and before we would get additional `onProgress` events e.g. for 55 and 80.

Filing this as a placeholder to verify the fix once ready.

**Comment by csadilek** [comment]
In addition this bug causes the progress bar to stick around at 15 longer than before because of `pageShow` events not being processed: https://searchfox.org/mozilla-central/source/mobile/android/modules/geckoview/GeckoViewProgress.jsm#391

**Comment by mcomella** [comment]
Performance label: csadilek mentioned the perceived performance impact of this.

**Comment by csadilek** [comment]
This is fixed now and works in latest Fenix Nightly as well.
