### ISSUE TITLE
Call geckoView.coverUntilFirstPaint immediately after creating the view

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/android-components#8747]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1665068 we made a change so that we don't call `coverUntilFirstPaint` as it was causing flashes since we don't know whether the app is about to replace the session or not (and what the default color should be).

We should set `coverUntilFirstPaint` to the appropriate color for the app immediately after creating the GeckoView to eliminate flashes when first opening the app, here: https://searchfox.org/mozilla-mobile/source/android-components/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt#32

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/android-components/issues/8747

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/android-components/issues/8752
