### ISSUE TITLE
Simplify account delegate chain for auto push

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#8766]
Currently we chain our delegates in an awkward way for the FxaPushSupportFeature, e.g. _inside_ of an `onAuthenticated` callback method we have
`account.deviceConstellation().registerDeviceObserver(...)`  call to actually observe device constellation changes.

But! We _always_ have the same account object around after the recent FxA refactorings, which lets us simplify this quite a bit. In theory we could just expose `registerDeviceObserver` directly on the account manager, which will break the delegate chain.

cc @jonalmeida since I'm sure you already filed a bug for this :)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7584)

**Comment by jonalmeida** [comment]
I was thinking about https://github.com/mozilla-mobile/android-components/issues/6879 which focuses on the effects of the chained observers from the Synced Tabs perspective.

Feel free to close it for this one.

**Comment by grigoryk** [comment]
I started pulling on this a bit. The tread pretty quickly leads to the awkwardness that's the `OAuthAccount` interface, and that whole abstraction layer on top of `FirefoxAccount`. There's a bit of a mismatch - underlying implementation bundles together "account" and "device" stuff, it's all on the same object, which in a-c these are currently split up. We could flatten out the a-c bits, moving most of `concept-sync` into the `services` component and probably combining `account` and `device` concepts to mirror the underlying library. I don't really like the single "god object" of sorts - especially with a somewhat natural split in concepts, but it does simplify things, and is directly derived from the shape of the backing API.

This flatting work would very much benefit from being able to run our test suite directly against the fxaclient library (instead of our interface mocks). But, this is a very useful thing to do regardless of how things end up shaping up, and something we wanted for a while, so perhaps that's a more fruitful direction right now.

**Comment by grigoryk** [comment]
Tests are https://github.com/mozilla-mobile/android-components/issues/5561

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794203

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
