### ISSUE TITLE
Current device in the constellation should not be nullable

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#8768]
I'm not sure why it is nullable now, but that doesn't really make sense.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7587)

**Comment by grigoryk** [comment]
@rfk do you foresee any cases where `GET /account/devices` would return a list without a single `isCurrentDevice=true` object in it?

**Comment by rfk** [comment]
It's possible, if you query that endpoint using a sessionToken that doesn't have a device record (e.g. if it's a web-based signin session).

In theory there should be no clients that would make such a query: `/account/devices` is only accessed by sync clients, and sync client should always have a device record. But I wouldn't be surprised to discover some edge-case that can violate this assumption :-/

I agree it doesn't make sense as a stable state though, if a device finds itself in this state then something has gone wrong and needs to be fixed (e.g. be re-registering its own device record).

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794202

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
