### ISSUE TITLE
Request for the push token on service initialisation

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8777]
We get a new token in the `onNewToken` call when this changes for various Firebase reasons, but we can also request the latest token during startup because:
 - This ensures we have not reached a race condition where the token is out of date.
 - We can rely less on verify_connection needing to tell us token's are out of date.
 - Calling the Rust push API `updateToken` is a cheap (local) call.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7596)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796425

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
