### ISSUE TITLE
Create third party dependency upgrade policy

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#8798]
Without having a regular process or policy to upgrade dependencies, it's easy to get behind. For example, we're currently on version 17 of Firebase but it's on 25. https://github.com/mozilla-mobile/android-components/issues/8459#issuecomment-713965989 This has the following impacts:
- lack of bug and security fixes
- potentially harder to upgrade to the newest version

We should consider creating such a policy. Ideally, we can share this policy with fenix as well because, afaik, they have no such policy.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7608)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795407

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
