### ISSUE TITLE
[Bug] S.browser_fallback_url in intent is braking the behavior.

### ISSUE THREAD

**Issue by matios13** [mozilla-mobile/android-components#8830]
## Steps to reproduce

1. install google maps on android device
1. Go to demo page https://fallbackproblem.glitch.me/ 
1. click on link under "with S.browser_fallback_url" 

OR 
1. embed link to intent in html with `S.browser_fallback_url ` for exemple 
`intent://maps.google.com/geo:0,0?q=mcdonalds;/#Intent;scheme=geo;package=com.google.android.apps.maps;S.browser_fallback_url=https%3A%2F%2Fgoogle.com;end; `
1. click on it
 
### Expected behavior
user should see opened google maps like in second example without  `S.browser_fallback_url `  

### Actual behavior
user is redirected to   `S.browser_fallback_url ` without openning google maps app  in case of demo its google.com
### Device information

* Android device: OnePlus 6t (Android 10) AND Xiaomi Redmi Note 7 (Android 9) AND SM-G950F (android 9)
* Fenix version: 81.1.4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7625)

**Comment by matios13** [comment]
Whats the status of that?

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795161

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Comment by rocketsroger** [comment]
Took a quick look and this is due to "Open links in apps" not turned on in settings.  I have seen similar issues as well where the user doesn't know this switch exists.  I'll start a conversation into how we should surface this functionality better.  That said, this is working as expected.
