### ISSUE TITLE
A-C README has some bad links

### ISSUE THREAD

**Issue by MrCull** [mozilla-mobile/android-components#8842]
The README file in this repo has some bad links - [404:NotFound]

Status code [404:NotFound] - Link: https://mozac.org/api/
Status code [404:NotFound] - Link: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/sync/README.md
Status code [404:NotFound] - Link: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/remotetabs/README.md
Status code [404:NotFound] - Link: https://github.com/mozilla-mobile/android-components/blob/master/components/service/telemetry/README.md
Status code [404:NotFound] - Link: https://github.com/mozilla-mobile/android-components/blob/master/concept/fetch/README.md
Status code [404:NotFound] - Link: https://github.com/mozilla-mobile/android-components/blob/master/concept/push/README.md

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7630)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795455

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
