### ISSUE TITLE
Re-subscribe only FxA push subscription when subscriptionExpired true

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#8846]
This is a short-term fix based on the comment in https://github.com/mozilla-mobile/android-components/issues/7143#issuecomment-718914150 in order to unblock other folks/features. We want to ensure that Send Tab is still able to function after upgrading the FCM SDK version in https://github.com/mozilla-mobile/android-components/issues/4819. 

During the upgrade, there is a chance that users will receive a new FCM push token that will invalidate the existing subscriptions and require a new subscription to be created.

Since Send Tab is a priority feature, we can treat it as a special case with our existing `FxaPushSupportFeature`.

The pseudo-code for the patch, roughly looks like this:
```diff
diff --git a/components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt b/components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
index e0c0277a22..aee1247ab2 100644
--- a/components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
+++ b/components/feature/accounts-push/src/main/java/mozilla/components/feature/accounts/push/FxaPushSupportFeature.kt
@@ -152,7 +152,7 @@ internal class AccountObserver(
  */
 internal class ConstellationObserver(
     context: Context,
-    private val push: PushProcessor,
+    private val push: AutoPushFeature,
     private val verifier: VerificationDelegate = VerificationDelegate(context)
 ) : DeviceConstellationObserver {

@@ -169,7 +169,7 @@ internal class ConstellationObserver(

         logger.warn("We have been notified that our push subscription has expired; renewing registration.")

-        push.renewRegistration()
+        push.subscribe(fxaPushScope)

         verifier.increment()
     }
```

Instead of calling `renewRegistration` and invalidating our push token all our subscriptions, we re-subscribe only our FxA push subscription. This would give us a new _valid_ subscription because our push native client will always have the latest token when we call `updateToken()` in the `onNewToken` call.

**Comment by jonalmeida** [comment]
What this means for FxA and AutoPush is that we won't force push token registration if FxA is unable to communicate with a client via push. Instead, the client will assume that they have a valid push token and [`updateToken`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L149) will never fail.

cc: @rfk , @grigoryk , @eoger

**Comment by rfk** [comment]
This makes sense to me at a high level, thanks for the heads-up.

One thing to check in QA: I expect it will be important that the resubscription actually generates a different subscription URL to send to the FxA server. The FxA server has some logic to avoid writing out spurious changes to the device record, so if `push.subscribe(fxaPushScope)` results in us trying to re-use the same subscription URL that we had previously, it probably won't work as intended.

**Comment by jonalmeida** [comment]
> This makes sense to me at a high level, thanks for the heads-up.
> 
> One thing to check in QA: I expect it will be important that the resubscription actually generates a different subscription URL to send to the FxA server. The FxA server has some logic to avoid writing out spurious changes to the device record, so if `push.subscribe(fxaPushScope)` results in us trying to re-use the same subscription URL that we had previously, it probably won't work as intended.

I ran into some road-blocks while testing out this STR unfortunately that I've documented here https://github.com/mozilla/application-services/issues/3314#issuecomment-720891800.

I'm not sure if we should assume that we do get a new endpoint during the re-subscription state now and go on ahead..

**Comment by jonalmeida** [comment]
> I'm not sure if we should assume that we do get a new endpoint during the re-subscription state now and go on ahead..

I think we have to assume this is this case. If we do not, then that means that we:
 - Have an endpoint that is valid according to Autopush but FxA cannot use it.
 - We need to dig ourselves into a deeper hole and call `renewRegistration` and `subscribe` in a way that re-implements what we need from `verifyConnection`.

**Comment by rfk** [comment]
> I think we have to assume this is this case. If we do not, then that means that we:

Yeah. Having this not be the case seems like bad behaviour in some other part of the system, and we'd probably be doing ourselves a disservice by trying to paper over it here.

**Comment by jonalmeida** [comment]
```
11-18 10:52:37.294 10457 10493 I FxaDeviceConstellation: Refreshing device list...
11-18 10:52:37.294 10457 10493 I FxaDeviceConstellation: Executing: fetching all devices
11-18 10:52:37.634 10457 10493 I FxaDeviceConstellation: Successfully executed: fetching all devices
11-18 10:52:37.634 10457 10493 I FxaDeviceConstellation: Current device needs push endpoint registration
11-18 10:52:37.634 10457 10493 I FxaDeviceConstellation: Refreshed device list; saw 3 device(s).
11-18 10:52:37.634 10457 10493 I FxaDeviceConstellation: Notifying observer about constellation updates.
11-18 10:52:37.634 10457 10493 I ConstellationObserver: onDevicesUpdate triggered.
11-18 10:52:37.634 10457 10493 I ConstellationObserver: Proceeding to renew registration
11-18 10:52:37.634 10457 10493 I ConstellationObserver: We have been notified that our push subscription has expired; re-subscribing.
11-18 10:52:37.636 10457 10493 I ConstellationObserver: Incrementing verifier
11-18 10:52:37.638 10457 10493 I ConstellationObserver: Verifier state before: timestamp=1605656389093, count=1
11-18 10:52:37.638 10457 10493 I ConstellationObserver: Verifier state after: timestamp=1605656389093, count=2
11-18 10:52:37.638 10457 10493 I FxaDeviceConstellation: Notifying observer about constellation updates.
11-18 10:52:37.639 10457 10503 I FxaDeviceConstellation: Executing: polling for device commands
11-18 10:52:37.643 10457 10513 I ConstellationObserver: Created a new subscription: AutoPushSubscription(scope=fxa_push_scope_a883246ee2f64d86b5bc689c753bbb13, endpoint=https://updates.push.services.mozilla.com/wpush/v1/gAAAAABe_4aOtJAHlUeCfFVs2uw_TcWnKIuW0l3eNyP_wOrHIUjxNyu_2jMg5e3SPgp44429O11qUIcZXRapoID0_CJ1k329YQpKPbwuFHqlFHAXnZWUJ8iolOhosOUvyqAptbgDCl1G, publicKey=BGO-fmuG3LhseVGb1ufq1lxrv9dVVv5U0yjFg4PC3AOkhIaK47TInbRpKLIipdHg-_oXpcWldNKWV8CfGrTqn-4, authKey=hXzoVZNKYnodQcUj9QnYuA, appServerKey=null)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: Push endpoints match!
11-18 10:52:37.644 10457 10513 W ConstellationObserver: java.lang.IllegalStateException: New push endpoint matches existing one
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.accounts.push.ConstellationObserver.onSubscribe$feature_accounts_push_release(FxaPushSupportFeature.kt:6)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.accounts.push.ConstellationObserver$onDevicesUpdate$2.invoke(FxaPushSupportFeature.kt:3)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.push.AutoPushFeature$subscribe$$inlined$ifInitialized$lambda$2.invokeSuspend(AutoPushFeature.kt:7)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.push.AutoPushFeature$subscribe$$inlined$ifInitialized$lambda$2.invoke(Unknown Source:10)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.push.ext.CoroutineScopeKt$launchAndTry$2.invokeSuspend(CoroutineScope.kt:5)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at java.lang.Thread.run(Thread.java:923)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: Caused by: java.lang.Throwable: New endpoint: https://updates.push.services.mozilla.com/wpush/v1/gAAAAABe_4aOtJAHlUeCfFVs2uw_TcWnKIuW0l3eNyP_wOrHIUjxNyu_2jMg5e3SPgp44429O11qUIcZXRapoID0_CJ1k329YQpKPbwuFHqlFHAXnZWUJ8iolOhosOUvyqAptbgDCl1G
11-18 10:52:37.644 10457 10513 W ConstellationObserver: Old endpoint: https://updates.push.services.mozilla.com/wpush/v1/gAAAAABe_4aOtJAHlUeCfFVs2uw_TcWnKIuW0l3eNyP_wOrHIUjxNyu_2jMg5e3SPgp44429O11qUIcZXRapoID0_CJ1k329YQpKPbwuFHqlFHAXnZWUJ8iolOhosOUvyqAptbgDCl1G
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	at mozilla.components.feature.accounts.push.ConstellationObserver.onSubscribe$feature_accounts_push_release(FxaPushSupportFeature.kt:5)
11-18 10:52:37.644 10457 10513 W ConstellationObserver: 	... 9 more
11-18 10:52:37.645 10457 10497 I FxaDeviceConstellation: Executing: updating device push subscription
11-18 10:52:37.905 10457 10497 I FxaDeviceConstellation: Successfully executed: updating device push subscription
11-18 10:52:37.933 10457 10503 I FxaDeviceConstellation: Successfully executed: polling for device commands
```

From landing this patch, snorp (who has the exact broken state we are trying to fix) was able to provide some logs.

What I see here is that calling 'subscribe' alone is not enough to fix the subscription. Our old endpoint is identical to the new one that we get from autopush which is what @rfk had concerns about.

Maybe it's time to make the "resubscribe" after all.

The good part though is that we're also able to track how many users are affected by this bug from the exception that we throw: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10062688/

**Comment by rfk** [comment]
> Maybe it's time to make a resubscribe call that unsubscribes first.

I don't like that it's necessary, but I'm leaning towards this as well; is this essentially the same as what's being discussed in https://github.com/mozilla/application-services/issues/3696?

**Comment by rfk** [comment]
Actually, your comments in mozilla/application-services#3696 made me realize that an unsubscribe is likely to be necessary for this to work at all. The rust-component [code for `subscribe()`](https://github.com/mozilla/application-services/blob/52a2c32ddb489f38fc0a4b6efa5ab463916c6844/components/push/src/subscriber.rs#L49) will first check in its local store for an existing subscription before hitting the server, so unless *something* has occurred to clear that local state then it's always going to give back the same subscription URL.

**Comment by jonalmeida** [comment]
Continued the conversation in mozilla/application-services#3696 .
