### ISSUE TITLE
Video autoplay stops working after upgrading after upgrading 0.23 -> 0.25

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#885]
I'm on fire-tv master (e869530c2be44344627723c83defdf3af395a2be) with https://github.com/mozilla-mobile/firefox-tv/pull/1201 applied: this upgrades components from 0.23 to 0.25. Unfortunately, this latest release seems to have broken video autoplay: see https://github.com/mozilla-mobile/firefox-tv/issues/1204 for additional information.

We're setting autoplay enabled through an extension method currently – https://github.com/mozilla-mobile/firefox-tv/blob/e869530c2be44344627723c83defdf3af395a2be/app/src/main/java/org/mozilla/focus/ext/EngineView.kt#L48 – maybe the internals changed which broken our method?

**Comment by mcomella** [comment]
Stefan pointed out new settings code: https://github.com/mozilla-mobile/android-components/commit/b739266c43be1d4aa2aaff122e396a336da18638#diff-b896d57d6810bd5e2ddeccf5efb53932R238

We're not using this class so it's possible this is undoing our extension function.

**Comment by csadilek** [comment]
We need to adjust the default settings in FireTV here: https://github.com/mozilla-mobile/firefox-tv/blob/e4c30248d095a05621a5a83e8c60877e3a6f977f/app/src/main/java/org/mozilla/focus/Components.kt#L24

Now that we have introduced these settings our defaults seem to override the ones provided in FireTV's (temporary) EngineView extension. There are a few settings that have different defaults and now need to be set explicitly:
```Kotlin
mediaPlaybackRequiresUserGesture = false
displayZoomControls = false
loadWithOverviewMode = true
allowFileAccess = false
allowContentAccess = false
```

**Comment by mcomella** [comment]
Christian pointed out that the updated Settings functionality overrides our extension function so we can fix this by duplicating our settings into Components.kt 's DefaultSettings impl.

**Comment by mcomella** [comment]
@csadilek On that note, why is file access and content access defaulted to true? It seems insecure 🤔

**Comment by csadilek** [comment]
@mcomella that's a good question. I defaulted to the WebView defaults :). Let me double-check.

**Comment by mcomella** [comment]
> Of course, we could change that for us.

I filed https://github.com/mozilla-mobile/android-components/issues/886 to start a discussion.
