### ISSUE TITLE
Set Mozilla-centric DefaultSettings instead of defaulting to WebView

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#886]
By default, DefaultSettings enables `fileAccess` and `contentAccess`: Christian mentions this is because we set them to WebView defaults (https://github.com/mozilla-mobile/android-components/issues/885#issuecomment-424913407). However, file access and content access don't seem like good defaults because they have the potential to be insecure: I think it'd make sense to provide more Mozilla-centric defaults rather than defaulting to what WebView does.

*That being said,* setting new defaults may break apps that are moving from a WebView solution to a components solution: perhaps we should provide `DefaultSettings` and `WebViewDefaultSettings` implementations?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7644)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796480

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
