### ISSUE TITLE
All completed downloads must have a size

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8871]
Related issue https://github.com/mozilla-mobile/fenix/issues/14772

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7652)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792935

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
