### ISSUE TITLE
WebView drawing cache is deprecated

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#888]
The drawing cache is deprecated in WebView. We're using it for thumbnail generation. Looks like we can replace it with the PixelCopy API or manually drawing the View? Low priority but filing so we don't forget.

**Comment by anandsingh2903** [comment]
I would like to work on this one.

**Comment by NotWoods** [comment]
@anandsingh2903 thank you for offering your help! @bacecek seems to have already started working on this one. We have added ["good first issue" labels](https://github.com/mozilla-mobile/android-components/labels/good%20first%20issue) to some other issues (more will be added soon). We definitely appreciate your help!
