### ISSUE TITLE
FXP-1489 ⁃ Uploading a large file blocks the Java main thread for a very long time

### ISSUE THREAD

**Issue by padenot** [mozilla-mobile/android-components#8881]
See this [Fenix Nightly profile](https://profiler.firefox.com/public/462vk5zhwsb0jmmp6ex77hdcy74x3csmjtdghr0/stack-chart/?globalTrackOrder=2-0-1&localTrackOrderByPid=5713-3-4-0-1-2~5946-1-2-0~&range=27593m9547&thread=3&v=5), which is me uploading a 1.6GB file on mediafire (I believe the site is irrelevant, but this one allows login-free upload).

It's blocking the java main threads for a very long time, and this file is not particularly big, and this is on a Pixel 4 that is very very fast (and otherwise idle), and the main thread is blocked for about 7.5s.

In terms of UX, this is a black screen for a long time, the browser appears stuck. I've found this when looking at `/r/firefox` on reddit: https://www.reddit.com/r/firefox/comments/jlffed/phone_locks_when_trying_to_upload_large_file/, the reporter might have a different device that is not idle, and possibly slower, resulting in an even worse experience (not usable).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXP-1489)

**Comment by Amejia481** [comment]
Thanks for reporting @padenot!

**Comment by MarcLeclair** [comment]
Duplicate: https://github.com/mozilla-mobile/fenix/issues/8387
