### ISSUE TITLE
nsIFilePicker needed for about pages in Fenix

### ISSUE THREAD

**Issue by nils-ohlmeier** [mozilla-mobile/android-components#8905]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1662191 some about pages save buttons don't work. And it seems the reason is lack of support for nsIFilePicker API.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7679)

**Comment by Amejia481** [comment]
[Waiting to confirm which api](https://bugzilla.mozilla.org/show_bug.cgi?id=1662191#c7) ac has to implement for `nsIFilePicker` to work.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796378

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
