### ISSUE TITLE
Should we expose a propperty for turning  captureThumbnail on/off?

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#891]
We can reduce the performance cost of capturing a thumbnail for consumers that are not interested in it. Right now is capturing a thumbnail either case if the consumer need  it or not. 

If we  Exposing a property  like `shouldCaptureThumbnails = false`, consumers can turn on/off shouldCaptureThumbnails depending on their needs

[SystemEngineView.kt#L136](https://github.com/mozilla-mobile/android-components/blob/f9d2b276ab9ab6c0790e032747fe22cd79a8be65/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt#L136)
```kotlin

       override fun onPageFinished(view: WebView?, url: String?) {
            url?.let {
                val cert = view?.certificate
                session?.internalNotifyObservers {
                    onLocationChange(it)
                    onLoadingStateChange(false)
                    onSecurityChange(
                            secure = cert != null,
                            host = cert?.let { Uri.parse(url).host },
                            issuer = cert?.issuedBy?.oName)

                    if (shouldCaptureThumbnails && !isLowOnMemory()) {
                        val thumbnail = session?.captureThumbnail()
                        if (thumbnail != null)
                            onThumbnailChange(thumbnail)
                    }
                }
            }
        }
```

**Comment by pocmo** [comment]
Yes! Could this be an engine setting? @csadilek?

**Comment by Amejia481** [comment]
Now we are using [ThumbnailsFeature](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/README.md#thumbnailsfeature).
