### ISSUE TITLE
Unify all download dialogs

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#8934]
I'm opening this ticket after talking with @Amejia481 about unifying the UX for download dialogs.
Currently we have 3 types of download dialogs:
- download with the app ([AC](https://github.com/mozilla-mobile/android-components/blob/ecd50c9b0471d2d738e6ce56d5e5610770696271/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadDialogFragment.kt))
- download with a 3rd party app ([AC](https://github.com/mozilla-mobile/android-components/blob/ecd50c9b0471d2d738e6ce56d5e5610770696271/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ui/DownloadAppChooserDialog.kt))
- show a download completed dialog (shown from clients like [Fenix](https://github.com/mozilla-mobile/fenix/blob/b696fc4c4b06da58b2b8e50334d286d4ffedfb0e/app/src/main/java/org/mozilla/fenix/downloads/DynamicDownloadDialog.kt))

They function a bit differently:
- the AC dialogs are modals which prevent other interactions with the app and are anchored to the bottom of the screen
- the Fenix dialog is non-blocking and also scrolls with scrolling in the browser while being placed on top of the bottom toolbar
- being separate implementations they can appear one on top of the other

&nbsp;
What I propose is having a similar behavior for all these 3 types: the UX currently used on Fenix:
- non-blocking
- scrolling with the browser
- appearing above the bottom toolbar

This could be done by having a layout container for just the above behavior, common to all 3 types of dialogs and then having each dialog, now a view inflate inside that container.

&nbsp;
Disadvantages:
- only one type of dialog can be shown at one time (from the 3 possible)

Asking UX if this seems like a good approach and if so how should we handle dialog requests while another one is already showing. 
- should we replace the one currently showing or 
- queue the new dialog for when all previous ones are dismissed?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7696)

**Comment by topotropic** [comment]
@Mugurell I'm currently only aware of the initial download prompt and the "Download completed" one. It would be great to have a list of all relevant cases where we currently use this dialog and based on that we can prioritize the messages. Thanks!

**Comment by Mugurell** [comment]
@topotropic Sorry for not getting to this sooner.

The initial download prompt can come in two forms:
| default | External download manager enabled in Settings |
|---|---|
|<img src="https://user-images.githubusercontent.com/11428869/98906799-6b76bb80-24c6-11eb-8fa1-20dc2eda7632.png" width="75%">|<img src="https://user-images.githubusercontent.com/11428869/98909054-f6a58080-24c9-11eb-8aab-8da474518ff6.png" width="75%">|

&nbsp;
And then there is the "download complete dialog"
<img src="https://user-images.githubusercontent.com/11428869/98909359-64ea4300-24ca-11eb-983e-b3b30a5811fa.png" width="33%">

----
Currently the download prompts are blocking other interactions and are reused if a new download starts (the new one replaces the old one)
So there could be only one of them on the screen / never both types and never more than one such dialog.

The download complete is a separate dialog that can appear on the screen at the same time but always beneath the download prompt.

If we are to refactor them to be of the same type, with only one such dialog appearing on the screen at a time, we'd need to know what to do if we should show more such dialogs and the user hasn't yet dismissed the previous ones (like in the case of starting a new download with the "download complete" one still displayed, or more "download complete" ones, etc)

Not sure if this new behavior will be better than what we have now.
Maybe there are yet other ways to order / show these?

**Comment by lime124** [comment]
hey @Mugurell this is going to need a bit more investigation and thinking than we are able to provide with the design sprint going on. we're going to have to pick this up again after the design sprint finishes. thanks for understanding! /cc @amedyne

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795406

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
