### ISSUE TITLE
Show up the toolbar when hovering over the region where the dynamic toolbar was

### ISSUE THREAD

**Issue by agi** [mozilla-mobile/android-components#8963]
from: https://bugzilla.mozilla.org/show_bug.cgi?id=1676279

> As of now mouse wheel events scroll the contents, but doesn't move the dynamic toolbar, thus there are unreachable contents by wheel events unfortunately.
> 
> Note that on Chrome mouse wheel events don't involve dynamic toolbar movement basically it just scrolls the contents. But in the test case of bug 1663634 comment 5 (that is 100vh with overflow:hidden), the dynamic toolbar is moving by mouse wheel, then once after the toolbar has been completely hidden, the toolbar will never be re-appeared by mouse wheeling. That's a bug on Chrome.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7716)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794934

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
