### ISSUE TITLE
Provide permalinks to CHANGELOG releases

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#898]
So I don't need to take screenshots to link to the CHANGELOG in bugs :)

e.g. https://github.com/mozilla-mobile/firefox-tv/issues/1219

**Comment by pocmo** [comment]
But Firefox has such a nice screenshot tool! :D

**Comment by pocmo** [comment]
It looks like jekyll already creates ids for headers, for 0.25.1 that would be:
https://mozilla-mobile.github.io/android-components/changelog/#0251-2018-09-27

Let's see if we can make them nicer and use the link with anchor in all release announcements.

**Comment by pocmo** [comment]
We pretty much do that with anchors now. :)

**Comment by mcomella** [comment]
On Tue, Jul 2, 2019 at 5:39 AM Sebastian Kaspari <notifications@github.com>
wrote:

> We pretty much do that with anchors now. :)
>

@pocmo Could we add links to the anchors in the changelog HTML document so
I don't need to inspect source, identify the anchor tag, and manually edit
the URL to permalink to a specific revision?

**Comment by pocmo** [comment]
the anchor is just the version e.g. for 2.0.0: #200

**Comment by mcomella** [comment]
On Tue, Jul 2, 2019 at 9:11 AM Sebastian Kaspari <notifications@github.com>
wrote:

> the anchor is just the version e.g. for 2.0.0: #200
> <https://github.com/mozilla-mobile/android-components/issues/200>
>

fwiw, I'll probably forget that and have to look it up while first time
permalinkers probably won't infer that.

Perhaps this could be a `help wanted`?
