### ISSUE TITLE
Better handling of ACTION_DOWN in NestedGeckoView 

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#8987]
Investigating https://github.com/mozilla-mobile/fenix/issues/14527 on `samples-browser`I saw that issue being introduced in `aee2029e`.

Knowing that GV does it's panning based on the ACTION_DOWN MotionEvent apps send it seems like we are not handling this properly in [NestedGeckoView](https://github.com/mozilla-mobile/android-components/blob/a64c68498c92b04c99b2f913ae81ebae51cc8615/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt).

Comparing [our code](https://github.com/mozilla-mobile/android-components/blob/a64c68498c92b04c99b2f913ae81ebae51cc8615/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt#L122) with [the one from GV](https://searchfox.org/mozilla-central/rev/ff82c973f8ccb0475ec32439e9ec07014b3a681f/mobile/android/geckoview_example/src/main/java/org/mozilla/geckoview_example/NestedGeckoView.java#116) where this issue does not reproduce it seems like using a callback system instead of awaiting for a coroutine to complete would fix this (also after testing it).

**Comment by csadilek** [comment]
Closing as PR landed and preparing a release. Please re-open in case there's more to do :).

**Comment by Mugurell** [comment]
Based on user reports this did indeed fix the issue seen on Fenix 🥳.

**Comment by silvaran** [comment]
Is a fix included in 83.1.0/Nov 18 on Android? I checked the changelogs and tried to tie something to the Bugzilla reports but have been unable to do so.

**Comment by cadeyrn** [comment]
No, it's not included in Firefox 83.1.0 but in Firefox 84 Beta and Firefox Nightly.

**Comment by silvaran** [comment]
@cadeyrn Thank you for the quick response!
