### ISSUE TITLE
Queue PromptRequest instead of override them 

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#8989]
When a new prompt request is created we are overwritten the existing one, that could cause some issues as we only are allowing one prompt to be visible at the time, some pages could create other prompt requests without the first one be proceeded and break some functionality for some pages. Below an example:

```html
<!DOCTYPE html>
<html>
<body>

<p>Click the button to wait 3 seconds, then alert "Hello".</p>
<p>After clicking away the alert box, an new alert box will appear in 3 seconds. This goes on forever...</p>
<input type="file" onclick="myFunction()">Try it</button>

<script>
function myFunction() {
  setInterval(function(){ alert("Hello"); }, 2000);
}
</script>

</body>
</html>

```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7729)

**Comment by Mugurell** [comment]
Talked with Arturo a bit more and looked more into the code from PromptFeature.
I was thinking of just having to keep a stack of PromptRequests but saw that we need these mapped to a stack of PromptDialogs (there are also two Views (as opposed to Dialogs) to display 2 specific PromptRequests).
Then this are to be updated - added to / removed from in multiple places in PromptFeature.
Working on this idea I found some issues
- Related to how prompts are restored after the Activity was killed in the background
  - https://github.com/mozilla-mobile/fenix/issues/19481
  - https://github.com/mozilla-mobile/fenix/issues/19479 
- Probably issues seen in code
  - We [always set the last prompt as activePromptRequest](https://github.com/mozilla-mobile/android-components/blob/f9d0f9584d4b26f35becfa75a4a0ed13054bccec/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L292) but in the above `onPromptRequested` that [will not always mean a new prompt shown to the user](https://github.com/mozilla-mobile/android-components/blob/f9d0f9584d4b26f35becfa75a4a0ed13054bccec/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L372-L374)
  - [Here](https://github.com/mozilla-mobile/android-components/blob/a13b2840691b6227415fa15fa0e6ba8db8aad90b/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt#L307-L311) we dismiss the prompt only in specific situations but we always clear the `activePrompt` reference.
  - In the same above code the prompt can be dismissed but the request is not removed from the session.
  
@Amejia481 It's hard to work around these and trying to fix them exceeds the initial scope. To me it seems one of those situations in which a feature needs to get back to the drawing board and rethought/rewritten to best fit the current needs.
