### ISSUE TITLE
MediaSessionFeature, MediaSessionFullscreenFeature: Simplify observer

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8998]
`MediaSessionFeature` and `MediaSessionFullscreenFeature` both observe the store via a `Flow` - however afterwards they reduce the result again to get the right media state. This could happen before `ifChanged()` already and simplify things, I think.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7737)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796366

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
