### ISSUE TITLE
There should be only one MediaSession object

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9000]
The expectation is that there should be only one `MediaSession` attached to one tab. However currently there can be more and we have code that compares them by looking at the timestamp. Let's investigate why we need that and if we can, eventually get rid of it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7740)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796365

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
