### ISSUE TITLE
MediaSessionFeature: Turn into Middleware?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9001]
`MediaSessionFeature`'s only concern is launching a service in certain situations. A `Middleware` may be better suited for that than a feature.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7741)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796364

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
