### ISSUE TITLE
MediaSession in paused mode after going to YouTube home page

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9016]
STR:
* Go to YouTube
* Play a video, notification appears
* Click on YouTube logo at the top to go back to the home page

Expected:
* Playback stops
* Notification disappears

Actual:
* Playback stops
* Notification stays in paused mode, pressing play resumes (audio) playback of the previous video

This doesn't happen with the old implementation when testing in Nightly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7750)

**Comment by rocketsroger** [comment]
From testing looks like this is due to GeckoView side not removing the media when browser is moved to the background.  Confirmed that this is an expected behaviour.

**Comment by rocketsroger** [comment]
Set blocked to GV until we have full confirmation

**Comment by pocmo** [comment]
Is there a related bugzilla bug we can link here?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796361

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
