### ISSUE TITLE
Awkward SessionStorage restore interface

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#904]
Currently `SessionStorage`'s `restore` accepts a `SessionManager`, and is expected to populate it with sessions. Since this action tends to happen at the same time `SessionManager` is create, this interface makes adding concepts like a default or initial sessions (see #826) to `SessionManager` quite awkward since that restore mutation will need to happen in SessionManager's constructor.

One way to approach this would be to change `restore` to `read`, which returns a structure describing currently stored sessions, including their `selected` state. This would allow `SessionManager` to be defined in terms of `initialSessions`, which normally are "sessions to restore". If an application chooses to have an initial session (distinctly different from an optional default one), it may provide one in lieu.

**Comment by pocmo** [comment]
From the Rocket requirements meeting today: They need a method add everything at once after loading (list of sessions + selection; currently they pass this to a `restore` method). Important here is that we wouldn't notify multiple times about an `add` - and only after done.

**Comment by pocmo** [comment]
> Important here is that we wouldn't notify multiple times about an add - and only after done.

Background is: The UI schedules animation based on the events happening (e.g. session added, session removed). You wouldn't want 50 tab animations after restoring 50 tabs. Suddenly the distinction between ´onSessionRemoved` and `onAllSessionsRemoved` made sense too: You want animations for a removed session but you wouldn't want 50 single animations for "clear all" (However the name should be more obvious about, e.g. `onSessionsCleared()`). I think we may need something similar for adding a bunch of sessions at once (including selection). Maybe something like `onSessionsRestored()` and we just call the method to do it something like `restore()` too?

**Comment by grigoryk** [comment]
@pocmo left the renaming of methods for a different issue, but I’ve updated my refactoring PR with a onSessionsRestored observer method and tweaked the restore process to behave sensibly. Take a look if that would suit rocket’s needs?
