### ISSUE TITLE
[Pull To Refresh][Bug] Glitchy behavior when using preventDefault() on a touch event

### ISSUE THREAD

**Issue by mstange** [mozilla-mobile/android-components#9043]
## Steps to reproduce

 1. Load one of these testcases: [scrollable testcase](https://bugzilla.mozilla.org/attachment.cgi?id=9187857) or [non-scrollable testcase](https://bugzilla.mozilla.org/attachment.cgi?id=9187858)
 2. Do a downwards pan gesture on the box with the black border. (no pull to refresh happens so far, good.)
 3. Do a short upwards pan gesture outside the box.

### Expected behavior

The short upwards pan should scroll down (on the scrollable variant) or do nothing (on the non-scrollable variant).

### Actual behavior

Screen recording: [glitchy-pull-to-refresh.mov](https://bugzilla.mozilla.org/attachment.cgi?id=9187865)

During the second pan, the pull-to-refresh arrow appears out of nowhere, and a pull-to-refresh is triggered even though the second pan was in the opposite direction.

### Device information

* Android device: Moto G5
* Fenix version: Nightly 201112

**Comment by Mugurell** [comment]
This should be ready to test now on the latest Nightly.
@abodea Since you looked at the other issue with pull to refresh, can you please also verify this one?

**Comment by abodea** [comment]
Verified as fixed on the latest Nightly 26/11 with Samsung Galaxy S10+ (10).
Note that everything works as expected and the pull to refresh no longer causes any glitchy behavior.
