### ISSUE TITLE
Non-syncing, persistent implementation of an Engine's HistoryTrackingDelegate

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#905]
When need to start storing things such as history, visits, bookmarks, etc., and explore how to best integrate with efforts coming out of https://github.com/mozilla/application-services.

This ticket is a placeholder to track that prototyping work.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7768)

**Comment by grigoryk** [comment]
Three high level goals here:
- provide relevant history information to the engine implementations so that they could do things like link colouring,
- keep track of meta information about visited pages, such as title changes
- provide different types of "read" access for recorded history to power things like history panel UIs, awesomebar, etc.

For link colouring, we need to be close to the Engine implementations - SystemEngine, GeckoEngine.
Both are configured similarly. GeckoView's proposed HistoryDelegate is documented here: https://bugzilla.mozilla.org/show_bug.cgi?id=1494713 - and for WebView we essentially need to override two methods: `doUpdateVisitedHistory` and `getVisitedHistory`. These have sightly different signatures than GeckoView's proposed delegate, but it's close enough.

I've approached this by augmenting `Settings` passed into an Engine on creation with a `historyDelegate`, which is then used internally if present in `SystemEngineView` and in the GeckoView alternative once it has history delegate stuff in place.

As long as engine sessions track enough relevant state - e.g. private mode, current URL - we can capture "meta" updates (e.g. new title) similarly.
I'm not sure there's a good reason to go up the event chain and into something like a SessionManager for this.

For storage side, my current approach is to introduce `browser-storage-*` component(s), which would provide concrete implementations for the history delegate. This would also provide other kinds of "read" access, for awesomebar and such.

An application would then configure its engine with a concrete history delegate implementation.

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796420

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
