### ISSUE TITLE
Investigate crash rate of "display already acquired" crashes

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9081]
Follow-up from #7960.

We fixed multiple "display already acquired" bugs. Let's stop now and investigate if the situation improved and which scenarios still show up in Sentry / Crash stats.

**Comment by csadilek** [comment]
Best time to investigate is after 85 hits release, containing all our fixes. Here's a list of Sentry crashes. Some of them are  trending in the right direction / are not happening on 84 anymore.

https://sentry.prod.mozaws.net/operations/firefox/issues/9257664/
https://sentry.prod.mozaws.net/operations/firefox/issues/9277932/
https://sentry.prod.mozaws.net/operations/firefox/issues/9518775/
https://sentry.prod.mozaws.net/operations/firefox/issues/9603990/
https://sentry.prod.mozaws.net/operations/firefox/issues/9604129/
https://sentry.prod.mozaws.net/operations/firefox/issues/9606806/
https://sentry.prod.mozaws.net/operations/firefox/issues/9619341/
https://sentry.prod.mozaws.net/operations/firefox/issues/9634200/
https://sentry.prod.mozaws.net/operations/firefox/issues/9638365/
https://sentry.prod.mozaws.net/operations/firefox/issues/9911128/
https://sentry.prod.mozaws.net/operations/firefox/issues/10038341/
https://sentry.prod.mozaws.net/operations/firefox/issues/10043245/
https://sentry.prod.mozaws.net/operations/firefox/issues/10052978/

**Comment by pocmo** [comment]
> https://sentry.prod.mozaws.net/operations/firefox/issues/9257664/

Hasn't happened in anything > 80.0. Closed as fixed in current release.

> https://sentry.prod.mozaws.net/operations/firefox/issues/9277932/

Super rare, only see it in 79.x. Closed as fixed in current release.

> https://sentry.prod.mozaws.net/operations/firefox/issues/9518775/

Only 80.x. Closed.

> https://sentry.prod.mozaws.net/operations/firefox/issues/9603990/

81.x. Closed.

> https://sentry.prod.mozaws.net/operations/firefox/issues/9604129/

81.x. Closed.

> https://sentry.prod.mozaws.net/operations/firefox/issues/9606806/

81.x. Closed.

> https://sentry.prod.mozaws.net/operations/firefox/issues/9619341/

Last one in 82. Closed.

> https://sentry.prod.mozaws.net/operations/firefox/issues/9634200/

Last one in 82. Closed.

> https://sentry.prod.mozaws.net/operations/firefox/issues/9638365/

Was always rare. Only in 81. Already closed.

> https://sentry.prod.mozaws.net/operations/firefox/issues/9911128/

**Happened in 85.1.1**

> https://sentry.prod.mozaws.net/operations/firefox/issues/10038341/

**Happened in 85.1.1/2**

> https://sentry.prod.mozaws.net/operations/firefox/issues/10043245/

**Happened in 85.1.1/2**

> https://sentry.prod.mozaws.net/operations/firefox/issues/10052978/

**Happened in 85.1.1/2**

**Comment by pocmo** [comment]
To summarize, for the last four crashes mentioned above I still see reports for 85.x (although it seems like way less?)

https://sentry.prod.mozaws.net/operations/firefox/issues/9911128/
https://sentry.prod.mozaws.net/operations/firefox/issues/10038341/
https://sentry.prod.mozaws.net/operations/firefox/issues/10043245/
https://sentry.prod.mozaws.net/operations/firefox/issues/10052978/

**Comment by pocmo** [comment]
Filtered crashed for 85.1.1:
https://sentry.prod.mozaws.net/operations/firefox/?query=release%3Aorg.mozilla.firefox-85.1.1+hashCode

**Comment by pocmo** [comment]
The good news is, that I only see `HomeActivity` <-> `HomeActivity`? (If the other crashes did not get merged into the other groups. Clicking through some of them I couldn't find others though).

**Comment by csadilek** [comment]
STR for the (or one of the) remaining `HomeActivity` <-> `HomeActivity` crashes: https://github.com/mozilla-mobile/fenix/issues/18127

**Comment by pocmo** [comment]
A new lead:
* https://github.com/mozilla-mobile/focus-android/pull/5911
* https://bugzilla.mozilla.org/show_bug.cgi?id=1741899

**Comment by csadilek** [comment]
Looked over all versions of this crash and not seeing any occurrence in > 99.

See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1741899
