### ISSUE TITLE
DownloadUtils.guessFileName doesn't return right value for hidden files

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#9085]
If you upload a file name `.hidden` to https://send.vis.ee/ the expected file name is `hidden` but instead is `.bin`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7790)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792934

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
