### ISSUE TITLE
Replace deprecated requireFragmentManager API in tests

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#9088]
After https://github.com/mozilla-mobile/android-components/pull/8839 lands, it looks like [all the usages](https://searchfox.org/mozilla-mobile/search?q=requireFragmentManager&path=android-components) would probably need the `parentFragmentManager` or `childFragmentManager`.

Some care needs to be taken to distinguish which is needed.

May need to also open a second PR for [reference-browser](https://searchfox.org/mozilla-mobile/search?q=requireFragmentManager&path=reference-browser) too.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7794)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792933

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
