### ISSUE TITLE
Document how to run the tests, in particularly a subset (if relevant)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#909]
Like #620, it isn't always obvious to new devs how they can run the tests: it'd be a good to document it. It's also helpful to know how to a run a subset of the tests.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7795)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795078

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
