### ISSUE TITLE
Relbot runs against forks because of Github Actions 

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-mobile/android-components#9090]
Fallout of https://github.com/mozilla-mobile/android-components/pull/9032 

While on an unrelated patch, @escapewindow came across these failed runs: 

![image](https://user-images.githubusercontent.com/5907366/100857855-8026ed80-348d-11eb-9ed7-bac208ff0d6c.png)

https://github.com/escapewindow/android-components/actions/runs/394570314

I don't know Github Actions to know what the fix should be. I guess there's a way to avoid runs on forks. What do you think @st3fan?

**Comment by st3fan** [comment]
Oh this is an easy fix, I will put that in today.

**Comment by st3fan** [comment]
Just to be clear, this action does try to run on this fork, but also within the context of that fork. The `GITHUB_TOKEN` that this action gets when run has limited scope and can only work on the fork, not on `mozilla-mobile/android-components`.

**Comment by JohanLorenzo** [comment]
Awesome, thank you @st3fan! 👍
