### ISSUE TITLE
[Bug] Error page -> Advanced -> Accept the Risk sometimes does not work

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#9136]
## Steps to reproduce
1 - Access https://pinning-test.badssl.com/
2 - Press "Advanced"
3 - Press "Accept the Risk and Continue"

### Expected behavior
- User should get pass the error page and to the actual website
This is what happens with other specific broken ssl pages 
or
- The advanced button with the option to "Accept the Risk and Continue" should not appear.
This is what happens on desktop

### Actual behavior
- Tapping "Accept the Risk and Continue" does not change anything in what the user sees as if nothing happens.
- In the js console I see "Unexpected error: InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable"

<img src="https://user-images.githubusercontent.com/11428869/101168233-ccb42980-3643-11eb-89da-3fd7993c5c69.gif" width="33%" />

### Device information
Happening on all current releases. (v83 - v85)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7834)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796467

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
