### ISSUE TITLE
Get rid of kotlin-android-extensions

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9143]
> Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

Not sure if we need either of those plugins, I assume we only used it for view lookups (if at all) that we can just do manually?

**Comment by mawen7** [comment]
In #9314 I noticed kotlin synthetic view binding is used as well as manual lookups.

I think it makes sense to migrate synthetic binding to [Android View Binding](https://developer.android.com/topic/libraries/view-binding) while leaving manual lookups untouched for now (maybe a new issue).

Are you fine with this?

**Comment by mawen7** [comment]
@pocmo Sorry for tagging you but I think you missed above comment

**Comment by mcarare** [comment]
IMO you should continue with just replacing the use of synthetics and leave the `findViewById` calls, as that would be another issue that can be handled in a different PR.

**Comment by pocmo** [comment]
This should be done. :)
