### ISSUE TITLE
Merge day! (84/85/86)

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#9171]
Merge day: Monday, December 14th
Release day: Tuesday, December 15th

- browser-engine-gecko-beta (84) -> browser-engine-gecko-release (84) (**RC only** release build: https://github.com/mozilla-mobile/android-components/pull/9172)
- browser-engine-gecko-nightly (85) -> browser-engine-gecko-beta (85)
- browser-engine-gecko-nightly -> 86

Docs: https://mozac.org/contributing/merge-day

**Comment by pocmo** [comment]
The first item was only done on the release branch so far - with a GV RC! :)

**Comment by jonalmeida** [comment]
Hmm good point. I was going to reference my PR for the release, but that GV release could change.
