### ISSUE TITLE
Assert that network calls are performed off the main thread

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#9180]
To avoid components from performing network calls on the UI thread, we could do some simple checks to throw if we're on the main thread when the call is made.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7865)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793147

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
