### ISSUE TITLE
Change add-on collection endpoint to services.addons.mozilla.org

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#9186]
We're currently using `addons.mozilla.org` which doesn't have the same optimized cache configuration. We should also make sure we use a trailing slash to prevent an additional request / redirect.

**Comment by willdurand** [comment]
Hey @csadilek, it looks like this change is part of AC 70. Do you know Fenix release version will use that?

**Comment by csadilek** [comment]
@willdurand we clarified on Slack, but just to document here. This will be in Fenix 85 which is currently rolling out.
