### ISSUE TITLE
Run feature-tab-collections tests on Firebase

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9200]
It looks like the `androidTest` tests for `feature-tab-collections` do not run in automation / on Firebase yet. They also fail.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7885)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796373

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
