### ISSUE TITLE
Update READMEs to point to maven.mozilla.org and use new artifact names.

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#922]

**Comment by wajahatkarim3** [comment]
I would like to do this. Can you provide more details about this issue? I think currently Mozilla contains Maven URL like this:
```groovy
implementation "org.mozilla.components:domains:{latest-version}
```
But it should be like this:
```groovy
implementation "maven.mozilla.org:domains:{latest-version}
```
Is that correct?

**Comment by wajahatkarim3** [comment]
I just checked the maven URL and it looks like module artifact names have now a prefix of ```browser-```. So, in all these gradle lines for ReadMe files, this is supposed to be updated. 
Can I do this?

**Comment by pocmo** [comment]
> I just checked the maven URL and it looks like module artifact names have now a prefix of browser-. 

Yes, the artifact names are now the same as the gradle module names (e.g. `toolbar` -> `browser-toolbar`) and the group id is always `org.mozilla.components` (e.g. `org.mozilla.photon:colors` -> `org.mozilla.components:ui-colors`.

> So, in all these gradle lines for ReadMe files, this is supposed to be updated.
Can I do this?

Yeah, you can do that. Let's start with updating the artifact names in the READMEs and then let's see what else we can do. :)
