### ISSUE TITLE
SystemEngineSession.exitFullScreenMode() is a no-op

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#923]
I wonder why `SystemEngineSession.exitFullScreenMode()` is not implemented. I was expecting us to remove the full screen view and notifying the callback.

Downstream issue: https://github.com/mozilla-mobile/firefox-tv/issues/1224

**Comment by pocmo** [comment]
@jonalmeida Do you know?

**Comment by pocmo** [comment]
Background: On back press the app needs to decide whether it needs to leave full screen mode.

**Comment by pocmo** [comment]
I'm surprised to see this being a no-op in the WebView version of Focus:
https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/java/org/mozilla/focus/webview/SystemWebView.kt#L206

**Comment by jonalmeida** [comment]
This was definitely an error I caused when I re-wrote my fullscreen implementation again. I'll fix this and write a test for it as well.
