### ISSUE TITLE
Cannot use dependencies with Java 8 bytecode

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#925]
```
The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
android {
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}
```

**Comment by mcomella** [comment]
Are bintray assets distributed by bytecode or source? I assumed the latter but it seems I might be mistaken. It seems like it's a problem for us as an open source organization if they're distributed by bytecode (in addition to problems like these).

**Comment by pocmo** [comment]
AARs contain compiled bytecode. There are a lot of reasons why this is good. Imagine having to build GeckoView from source :)

The problem here is solvable by adding the `compileOptions` above and letting the Android's build tools take care of de-sugaring:
https://developer.android.com/studio/write/java8-support

In the case here we actually own the dependency (`ServoView`) and could change this upstream as well.

What other problems are you seeing?

**Comment by mcomella** [comment]
> AARs contain compiled bytecode. There are a lot of reasons why this is good. Imagine having to build GeckoView from source :)

I talked to Nick about this: see https://github.com/mozilla-mobile/android-automation-tools/issues/21

> What other problems are you seeing?

The problem I was concerned with boils down to the problem [reproducible builds](https://en.wikipedia.org/wiki/Deterministic_compilation) is trying to solve. https://github.com/mozilla-mobile/android-automation-tools/issues/21 covers that so no more concerns from me on this bug.

**Comment by pocmo** [comment]
GeckoView switched to Java 8. We need to follow and apply the same changes:
https://bugzilla.mozilla.org/show_bug.cgi?id=1485439

**Comment by pocmo** [comment]
It may be enough to just add this to `browser-engine-gecko-nightly` and `samples-browser` for now. This avoids that this replicates to all components.
