### ISSUE TITLE
Improve MediaSessionServiceDelegateTest to test for specific calls

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#9260]
Currently `MediaSessionServiceDelegateTest` only test for if `destroy` or `shutdown` is called.  However, the calls inside those functions can be removed without breaking the tests.  Improve these tests so a specific call is tested.  Ex: `audiofocus.abandon()`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7918)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796360

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
