### ISSUE TITLE
[Bug][a11y] Links are too low-contrast in reader mode and hide visited state

### ISSUE THREAD

**Issue by gijsk** [mozilla-mobile/android-components#9272]
Re-posted based on the desktop version: https://bugzilla.mozilla.org/show_bug.cgi?id=1546213

## Steps to reproduce
1. open an article (e.g. https://www.bbc.co.uk/news/business-55357340 )
2. enter reader mode using the icon in the address bar
3. switch between light, dark and sepia modes

### Expected behavior

Links (e.g. the "in a blog" link in the fourth paragraph) should appear with sufficient contrast

### Actual behavior

Link foreground colours are `#00acff` on all themes (even with `!important` set!). Given the background colours used (`#222222` for dark, `#ffffff` for light, and `#f4ecd8` for sepia), this yields contrast ratios of 6.32 (dark), 2.52 (light) and 2.14 (sepia). The minimum per WCAG standards for colour contrasts is 4.5 for AA and 7 for AAA status.

It's also worth noting that the CSS applies for visited links, too, meaning users can't tell whether they've been to a link or not:

https://github.com/mozilla-mobile/android-components/blob/639651b83215cbeed48a085c310674397f8a5e68/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css#L175-L180

Fenix / AC should use higher-contrast foreground colours (see e.g. https://hg.mozilla.org/integration/autoland/rev/d10ecc77057b for what I did on desktop) to help readability, and should ideally distinguish visited links.

If changing this CSS file is all it takes, I can probably provide a PR? Let me know. :-)

### Device information

* Fenix version: Firefox Nightly from Thu Dec 17, 2020.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7925)

**Comment by gijsk** [comment]
Oh, and as an aside, I was initially going to file under the fenix repo - but it seems the code is here so I figured this was the better place. OTOH, I did also spot https://github.com/mozilla-mobile/fenix/issues/16387 which looked like maybe it would also belong in this repo? I'll let you figure that out...

**Comment by csadilek** [comment]
> Oh, and as an aside, I was initially going to file under the fenix repo - but it seems the code is here so I figured this was the better place

@gijsk Thanks for filing. Either repo is fine!

> If changing this CSS file is all it takes, I can probably provide a PR? Let me know. :-)

Yes, that's all it takes :). A PR would be much appreciated. If you don't get to it, I can open one and tag you for review.

**Comment by violasong** [comment]
FYI @topotropic, this sounds like a good one to look at as part of overall quality

**Comment by julienw** [comment]
Hey, @gijsk @csadilek gently ping about this :) 

Is the work about taking the CSS we have in Android and using the same colors as in desktop? Is there a way to reuse the desktop CSS file instead of duplicating it?

Thanks!

**Comment by gijsk** [comment]
> Is the work about taking the CSS we have in Android and using the same colors as in desktop?

Yes.

> Is there a way to reuse the desktop CSS file instead of duplicating it?

I don't know. The desktop stylesheet is currently only shipped on desktop - https://searchfox.org/mozilla-central/rev/ac7da6c7306d86e2f86a302ce1e170ad54b3c1fe/toolkit/themes/shared/desktop-jar.inc.mn#19 - but it'd be straightforward to change that and ship it within geckoview. I don't know if that would be sufficient to be able to use it here though, because I don't know anything about the android-components implementation of reader view.

I haven't been able to find time to do a PR myself here.

**Comment by csadilek** [comment]
> Is there a way to reuse the desktop CSS file instead of duplicating it?

We have a mid-term plan to move the reader mode extension out of Android Components, and consume the functionality via GeckoView instead. At that point, we'd also make sure to use the same styles as desktop.

I did look into fixing this at the time and started unifying, but ran out of time. Maybe we should just apply a fix for this specific issues to our styles in the meantime? @julienw If you have any interest sending us a PR here, please let us know, you're more than welcome!
