### ISSUE TITLE
OutOfMemoryError: Recently Closed Tabs

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#9317]
```
mozilla.components.feature.recentlyclosed.db.RecentlyClosedTabEntity.toClosedTab$feature_recentlyclosed_release(RecentlyClosedTabEntity.kt:8) at
mozilla.components.feature.recentlyclosed.RecentlyClosedTabsStorage$getTabs$$inlined$map$1$2.emit(Collect.kt:10)
```

https://crash-stats.mozilla.org/signature/?product=Fenix&java_stack_trace=~RecentlyClosedTabEntity&signature=java.lang.OutOfMemoryError%3A%20at%20java.util.Arrays.copyOf%28Arrays.java%29#summary

Related to #7886 and tracked also at bz-1652810

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7948)

**Comment by grigoryk** [comment]
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12562234/?query=is%3Aunresolved%20newStringFromChars

**Comment by grigoryk** [comment]
From Sentry, we're trying to allocate on the order of 20-70mb depending on the crash.

**Comment by grigoryk** [comment]
FWIW, this isn't a new problem - the recent spike in crashes appears to come from a single device (or, at least, they're all from the same type of a motorolla device).

**Comment by grigoryk** [comment]
Best I can tell, this is triggered by reading and deserializing persisted tab state from disk.

An interesting aspect recently closed tabs in particular is that we basically never need to have their session state state in memory - the only point in time when it actually matters is when the user is restoring a tab. So, in theory, we could reorganize this code a bit to not eagerly load the state at all, and do it only at the point of restoration.

Doing this should lower our overall memory footprint by quite a bit, in severe cases (lots of recently closed tabs with large sessions), making other OOMs less likely - as well as addressing this specific blow up case.

**Comment by grigoryk** [comment]
https://sentry.prod.mozaws.net/operations/firefox/issues/9259175/?query=is%3Aunresolved%20OOM quite pronounced on release.

**Comment by grigoryk** [comment]
Took a quick stab at this to see how it'll feel separating out `EngineSessionState` from `RecoverableTab`, ended up introducing a `RecoverableTabLite` to keep changes very contained and their impact obvious.

This worked out well, so probably worth getting this over the line: 
https://github.com/grigoryk/android-components/commit/d8c62c9827fd4d0c440380087de4a085c9268ba2
https://github.com/grigoryk/fenix/commit/e6d65c9af2ae156016e1c58cf3a8faa4d208374a

Besides lower memory footprint, we're also gaining a startup perf benefit - we're populating `BrowserState.closedTabs` (currently, instances of `RecoverableTab`) on startup, which involves deserializing this engine sessions state from disk. After this change, that restoration flow no longer needs to read/deserialize anything.
