### ISSUE TITLE
OutOfMemoryError: Session Storage Restore

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#9318]
```
kotlin.io.ExceptionsKt.readText(Exceptions.kt:6) at
androidx.core.app.AppOpsManagerCompat.readSnapshot(AppOpsManagerCompat.java:2) at
mozilla.components.browser.session.storage.SessionStorage.restore(SessionStorage.kt:3) at
org.mozilla.fenix.components.Core$sessionManager$2$$special$$inlined$also$lambda$1$1.invokeSuspend(Core.kt:2) at 
```

https://crash-stats.mozilla.org/signature/?java_stack_trace=~SessionStorage.restore&product=Fenix&signature=java.lang.OutOfMemoryError%3A%20at%20java.lang.StringFactory.newStringFromChars%28StringFactory.java%29#summary

Related to #7886 and tracked also at bz-1652810

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7950)

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796221

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
