### ISSUE TITLE
OutOfMemoryError: Get non autocomplete text

### ISSUE THREAD

**Issue by kbrosnan** [mozilla-mobile/android-components#9319]
```
mozilla.components.ui.autocomplete.InlineAutocompleteEditText$Companion.access$getNonAutocompleteText(InlineAutocompleteEditText.kt:4) at
mozilla.components.ui.autocomplete.InlineAutocompleteEditText$TextChangeListener.afterTextChanged(InlineAutocompleteEditText.kt:2)
```

https://crash-stats.mozilla.org/signature/?product=Fenix&java_stack_trace=~getNonAutocompleteText&signature=java.lang.OutOfMemoryError%3A%20at%20java.lang.StringFactory.newStringFromChars%28StringFactory.java%29#summary

Related to #7886 and tracked also at bz-1652810

**Comment by rocketsroger** [comment]
After investigation,  the OOM at the `substring()` call is not the cause.  This crash occurred because the device was running out of memory.   Closing this issue.
