### ISSUE TITLE
Consider providing pre-tinted photon assets

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#935]
From https://github.com/FirefoxUX/photon-icons/pull/38#discussion_r219156164, @aminalhazwani mentions that there are a limited number of colors android-components assets can be tinted to: is there a way to provide developers with *only those asset choices* so we don't have to screw up tint or modify assets? Traditionally, we would do:

```xml
android:src="@drawable/components_asset
android:tint="@color/photon_grey10"
```

But I wonder if we can do better? Original text:

> @mcomella we have a defined set of fill colors that we currently support, this selection goes across platforms, so not Android-only
>
>    Grey 10
    Grey 10 a80
    Grey 10 a60
    Grey 90 a80
    Grey 90 a60
    Blue 40
    Blue 50
    Green 60
    Red 60
    White 100

> Would be interesting to understand how can we enable engineering to pick only from those colors so that they don't have to manually modify assets 🙂

Action items:
- Is there an easy way to to do this? We have a lot of other things to do so this may not be high priority
- If not, we should consider also providing photon colors with common alpha values (a generated file?)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7969)

**Comment by pocmo** [comment]
I wonder if we need multiple tints in a single app or whether this is a "theme color" that will be consistent in the app.

Meaning, would it be helpful to not define a tint color directly but by a reference the app can override? E.g.

```XML
android:src="@drawable/components_asset
android:tint="@color/mozac_icons_tint"
```

And then in the app

```XML
<color name="mozac_icons_tint">@color/photonGrey10</color>
```

It's a little bit more flexible but of course not helpful if the app needs to define multiple tint colors.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793166

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
