### ISSUE TITLE
Improve user flow when open in app is refused in private browsing

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#9386]
Currently if the user refused open in app dialog while in private browsing, the flow might not be what user expects.  Investigate if we can eliminate the dialog prompt or improve the flow in other ways.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7984)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793128

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
