### ISSUE TITLE
Gradle 7.0: deprecations

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9388]
We currently have a few things in use that are deprecated as of Gradle 7.0:

- [ ] BasePluginConvention.getProject() (removed, see https://docs.gradle.org/6.6.1/userguide/upgrading_version_6.html#discontinued_methods)
- [ ] Project.distsDir (use distsDirectory https://docs.gradle.org/6.6.1/dsl/org.gradle.api.Project.html#org.gradle.api.Project:distsDir)
- [ ] Project.libsDir (use libsDirectory https://docs.gradle.org/6.6.1/dsl/org.gradle.api.Project.html#org.gradle.api.Project:libsDir)
- [ ] Querying the mapped value of map(...) before task '...' has completed - see https://docs.gradle.org/6.6.1/userguide/upgrading_version_6.html#querying_a_mapped_output_property_of_a_task_before_the_task_has_completed

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7986)

**Comment by grigoryk** [comment]
The last one does in more detail:
```
Querying  the mapped value of map(java.io.File  property(org.gradle.api.file.Directory, fixed(class  org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory,  /Users/grishakruglov/Code/android-components/components/browser/storage-sync/build/generated/ap_generated_sources/debug/out))   org.gradle.api.internal.file.DefaultFilePropertyFactory$ToFileTransformer@1a7feafb)  before task ':browser-storage-sync:compileDebugJavaWithJavac' has  completed has been deprecated.

.. hit at org.gradle.api.internal.provider.TransformBackedProvider.lambda$beforeRead$0(TransformBackedProvider.java:86)
```

And the rest, all seem to be hit from some `org.gradle.api.internal.*` path, so don't appear to be actionable.

(run some gradle task with --scan to see these deprecations in detail).

**Comment by csadilek** [comment]
We upgraded to Gradle 7 as part of https://github.com/mozilla-mobile/android-components/commit/1772620e8b06c12061cef67fd7c7ae0e8b9fc65d.
