### ISSUE TITLE
Migrate site permission db to new gv api

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#9391]
The gv team is working on a new api for site permissions right now we are storing all the data related in our own db but the new api will require us to migrate the data over as the new api offers storage.

https://bugzilla.mozilla.org/show_bug.cgi?id=1654832

**Comment by Mugurell** [comment]
@amedyne Should this ticket be moved to the staging board until when the GV work will be completed?
I don't think there's anything actionable on our side atm.

**Comment by Amejia481** [comment]
It looks like is taking a bit more for the GV team to land, but we could move it back until it lands

**Comment by Amejia481** [comment]
I created this [ticket](https://github.com/mozilla-mobile/fenix/issues/19587) for the QA team to perform some manual tests before integrating.
