### ISSUE TITLE
RustErrorException - Error executing SQL: database disk image is malformed

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9398]
There are a bunch of these warnings with different stacktraces: https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=is%3Aunresolved+Error+executing+SQL

Few examples:
During sync: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/8813918/?query=is%3Aunresolved%20RustErrorException

`places::history_sync::plan - incoming: record Guid("LWNbx-OryNT7") failed to apply: Error executing SQL: database disk image is malformed`

During bookmark fetch:
`getBookmarksWithUrl`: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/6879709/?query=is%3Aunresolved%20Error%20executing%20SQL

During database initialization: https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/10347160/?query=is%3Aunresolved%20Error%20executing%20SQL

etc..

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7996)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796413

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
