### ISSUE TITLE
PlacesConnectionBusy - Error executing SQL: database is locked

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9399]
These happen on write storage requests.

Mostly they happen during `noteObservation`, as users are browsing around and we're recording history:
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9483637/?query=is%3Aunresolved%20database%20is%20locked

Rarely, the same error ends up as a crash when hit from a different storage api (create bookmark in this case): https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9586334/?query=is%3Aunresolved%20database%20is%20locked

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7998)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796412

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
