### ISSUE TITLE
[Bug] PWA session is also selected when created

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#9405]
Fenix issue: https://github.com/mozilla-mobile/fenix/issues/17199

This is caused by `WebAppIntentProcessor`creating PWA session with no `selectTab` vlue, while default is ` selectTab = true`.

**Comment by csadilek** [comment]
Fixed by: https://github.com/mozilla-mobile/android-components/commit/2b328920df219db9c33457cdf2a16f369805a401
