### ISSUE TITLE
Add support for sharing actual images from the context menu

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#9418]
Needed for https://github.com/mozilla-mobile/fenix/issues/12414. Please see this issue for more details.

**Comment by Mugurell** [comment]
The end result should be something like this
<img src="https://user-images.githubusercontent.com/11428869/104742711-744c6d80-5753-11eb-8b32-b65a1b4230da.gif" width="40%" />
[video](https://drive.google.com/file/d/1W6T7lfU822BNfHKY_ej1ttn3UZO34Eie/view?usp=sharing)

Though there are some case in which the share operation might fail
-  resource could not be downloaded
- .. could not be persisted locally
- the 1 second operation timeout would be reached (timeout added to not block the UX for bigger images / slow internet)

Currently in this cases the process would silently fail. The same seems to happen on Chrome.
Maybe we should though show a generic Toast for the user to make the user aware of these situations?

**Comment by Mugurell** [comment]
Talked "offline" with @topotropic to which I also shared an APK with the current patch applied.
- regarding the long URLs: data URLs and HTTP URLs with more than 200 characters should be replaced with an empty string which should ensure a good balance of useful information and not be too long to be displeasing.
- regarding the silent fail we can go with it for now
- there was also a concern about data usage for downloading the images to share but I think the effect is negligible. In normal browsing users would see a lot of other images that are "downloaded" to be rendered.
There is also the possibility of GeckoView sending us a Reponse from which we could get the image without having to download it but it is unclear atm in which and how many situations this will happen.

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly build with LG G7 (Android 8.1.0).
