### ISSUE TITLE
Investigate reducing number of pre-created threads

### ISSUE THREAD

**Issue by csadilek** [mozilla-mobile/android-components#9424]
We have a lot of components initializing their own threads for file and storage access e.g. via `Executors.newSingleThreadExecutor()` which are then used in custom coroutine scopes.

In addition, every `Store` gets a dedicated thread too, and arguably small stores living in the application could use the main thread for reducing e.g. the `AccountSettingsFragmentStore` in Fenix.

Ideas:
- Create thread pools for storage and file access and re-use threads across components. This might not be ideal as it introduces complexity and unexpected dependencies.
- Where safe and multiple threads can be used we could rely on `CoroutineScope(Dispatchers.IO)` more.
- Add a parameter to `Store` to allow reducing on the main thread.

Background: Fenix uses over 120 threads a few seconds after startup

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8023)

**Comment by jonalmeida** [comment]
For components like push and Nimbus, the use case for a `Executors.newSingleThreadExecutor()` is to ensure that coroutine tasks are executed in a queue.

A shared queue could possibly work for that as well?

**Comment by csadilek** [comment]
> A shared queue could possibly work for that as well?

Yes, good point. We should look into that as well for all components we have using a single thread.

**Comment by mcomella** [comment]
> For components like push and Nimbus, the use case for a `Executors.newSingleThreadExecutor()` is to ensure that coroutine tasks are executed in a queue.
> 
> A shared queue could possibly work for that as well?

See also https://github.com/mozilla-mobile/perf-frontend-issues/issues/180 for some related ideas for how we might do serial execution of tasks.

**Comment by Mugurell** [comment]
@csadilek I'm seeing other ticket linked to this.
Are you actively working / plan to work on this?
Seems like you have the needed context already but the backlog is currently running low and I'm not sure if this something that can be picked up by others or not.

**Comment by csadilek** [comment]
@Mugurell This is more of a meta issue really. I would like to work on it and break it down more / try different things, but I won't get to it short term. So, if anyone wants to investigate, and propose ideas I am all for it. I think though that https://github.com/mozilla-mobile/fenix/issues/17590 would be a better first step.

I both cases though we need to discuss any potential "fixes" beforehand. /cc @pocmo

**Comment by pocmo** [comment]
> I both cases though we need to discuss any potential "fixes" beforehand.

👍 


Also note that we added `Dispatchers.Cached` in AC a while ago too:
https://github.com/mozilla-mobile/android-components/blob/master/components/support/base/src/main/java/mozilla/components/support/base/coroutines/Dispatchers.kt#L17

**Comment by mcomella** [comment]
Impact: memory usage would go down significantly if we reduce the number of threads. Unknown impact on delays to the user experience.

Perf triage: @jonalmeida will file sub-issues for quick fixes.

**Comment by jonalmeida** [comment]
I remembered a bit too late that there are already issues filed:
- https://github.com/mozilla-mobile/android-components/issues/9734
- https://github.com/mozilla-mobile/android-components/issues/7334

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795418

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
