### ISSUE TITLE
Push initialization issues with Android 84.0 & 86.0

### ISSUE THREAD

**Issue by jrconlin** [mozilla-mobile/android-components#9426]
Noting a few odd behaviors I encountered while attempting to debug a push issue. I'm not sure there's enough here to act as a proper bug, but I wanted to record abnormal behaviors I've seen in case there are additional similar events.

I ran both in an Android Emulator (running Android 10/API 29), but was able to observe similar behaviors on a device. In most cases, deleting app data and cache resolved the issue.

1) when loading https://mozilla-services.github.io/WebPushDataTestPage/ (or other similar test pages), I would sometimes see an error that the subscription info was empty. This would be triggered if the result of a `PushManager.getSubscription()` promise returned an empty structure or one that did not contain expected values. Sadly, I was not able to capture logcat info for that. 

2) A user reported that they were able to get a valid subscription info block, but that subscription updates were returning a 410. That hints to me that possibly the FCM token that the device is reporting may be invalid or old? Again, clearing the data cache seemed to help with that.

Once these issues were cleared, I was able to send and receive messages without issue, even after device restarts.

**Comment by jonalmeida** [comment]
@jrconlin For 1, did the test page give you and error similar to "can't access property "endpoint", subscription_info is null"?

If so, this is basically the outcome of the 410 error result. Any interactions with autopush while in the state will give you weird results like this.

**Comment by jrconlin** [comment]
The error I was seeing was just "subscription_info is null" but that could have been truncated for some reason. I'm willing to believe that it's related to the 410 error, since clearing the browser cache resolved the problem. 

Kinda wonder if there's a way for the server to return a richer error in these cases, so that the client might try to see if it can force an FCM token refresh or something?

**Comment by jrconlin** [comment]
Also, going to close this as a dupe. It should still show up in searches for folks experiencing the same issue.
