### ISSUE TITLE
browser-storage-sync implementation for credit cards and addresses storage

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9454]
Larger issue: #9452

An a-s backed implementation of https://github.com/mozilla-mobile/android-components/issues/9453

Follow how `PlacesHistoryStorage` and `PlacesBookmarksStorage` are wired up, and `SyncableLoginsStorage` for how to initialize an encrypted store (see `unlock`).

**Comment by gabrielluong** [comment]
Marking as blocked on #9453
