### ISSUE TITLE
Gecko credit card storage delegates

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9455]
Larger issue: #9452

Once we have https://github.com/mozilla-mobile/android-components/issues/9454 and know shape of the necessary Gecko delegates for credit cards, we can implement them.

TBD link to delegate work in bugzilla (per esawin).

**Comment by grigoryk** [comment]
We'll also need delegate wrappers in `browser-engine-*`.

**Comment by grigoryk** [comment]
GV API doc: https://docs.google.com/document/d/1jSvIrmv0nWNY57X9voq_rcW4fpeF6M9YWzDQ1u9eN_A/edit#heading=h.r9grb5139qxx

**Comment by gabrielluong** [comment]
Marking as blocked on #9454

**Comment by gabrielluong** [comment]
Separately the validation delegates to https://github.com/mozilla-mobile/android-components/issues/9803.
