### ISSUE TITLE
Introduce SyncEngine types for credit card/addresses syncing

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9456]
Larger issue: https://github.com/mozilla-mobile/android-components/issues/9452

Introduce new `SyncEngine.CreditCards` and `SyncEngine.Addresses` to `service/fxa/sync/*`.

Once there's support for these storages in `mozilla.appservices.syncmanager.SyncManager`, we can teach `WorkManagerSyncManager` about them as well.

**Comment by gabrielluong** [comment]
Just waiting on https://github.com/mozilla-mobile/fenix/pull/19195, which will have the added CreditCard sync engine from AC https://github.com/mozilla-mobile/android-components/pull/10054. This should allow us to add the CreditCard sync preference, but let's also hide the preference visibility to align with whether or not the credit card autofill is enabled.

**Comment by gabrielluong** [comment]
I think this was done in https://github.com/mozilla-mobile/android-components/pull/10054.
