### ISSUE TITLE
feature-prompts: credit cards

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9457]
<img width="396" alt="Screen Shot 2021-03-02 at 6 07 24 PM" src="https://user-images.githubusercontent.com/1190888/109727466-64151400-7b82-11eb-855f-55239576a693.png">

Similar to logins, we will need to add a credit card prompt to feature-prompts. [See original Logins PR here ](https://github.com/mozilla-mobile/android-components/pull/5316/)

- [ ] Add new prompt type in `PromptRequest`
- [ ] Listen for prompt type in `PromptFeature` to launch new `Fragment`
- [ ] Create a `CreditCardDialogFragment` based on UX mocks
- [ ] Validate and save values from prompt to storage layer

**Comment by gabrielluong** [comment]
This is waiting on the feature-prompt refactor done in https://github.com/mozilla-mobile/android-components/issues/9752.
