### ISSUE TITLE
browser-storage-sync implementation for addresses

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9458]
Larger issue: https://github.com/mozilla-mobile/android-components/issues/9452
Credit cards counter part: https://github.com/mozilla-mobile/android-components/issues/9454

Interfaces to be defined in https://github.com/mozilla-mobile/android-components/issues/9453 to map well with what APIs we have available in A-S.

**Comment by gabrielluong** [comment]
Marking as blocked on #9453

**Comment by gabrielluong** [comment]
I think this is actually resolved by #9454 since the credit card and address storage are combined.
