### ISSUE TITLE
AndroidKeyStore issues

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9459]
After digging through Sentry a bit, here's a quick summary of what we're seeing (on Fenix Nightly, where we end up using AndroidKeyStore for password engine key management and fxa/sync state encryption):

```
InvalidKeyException - Error executing SQL: file is not a database (DatabaseLoginStorage#unlock):
https://sentry.prod.mozaws.net/operations/firefox-nightly/?query=is%3Aunresolved+InvalidKeyException
172 users, 2300 events
36% android 9, 23% android 10, 10% android 8
46% rooted

RustErrorException
logins::ffi - Not a database / invalid key error (DatabaseLoginStorage#unlock)
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9213672/?query=is%3Aunresolved%20invalid%20key%20error
192 users, 4500 events
73% android 10, 11% android 9, 5% android 11
70% rooted

InvalidKeyException - Keystore operation failed:
Paths such as FirefoxAccount#tryPersistState - SecurePreferencesImpl23#putString - 

android.security.KeyStoreException: Invalid key blob
getPasswordsEncryptionKey

InvalidKeyException: Keystore operation failed

(AndroidKeyStoreCipherSpiBase in ensureKeystoreOperationInitialized)
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/9842425/?query=is%3Aunresolved%20InvalidKeyException
29 users, 83 events
81% android 6, 9% android 10, 7% android 9
11% rooted
```

Let's consider what we can do to improve the situation a bit, and what could be causing these.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8055)

**Comment by grigoryk** [comment]
See description and links in https://github.com/corona-warn-app/cwa-app-android/pull/1235

In short, I wonder if we can use a similar retry/backoff init strategy for reducing likelihood of hitting KeyStore initialization issues.

**Comment by jackyzy823** [comment]
Another AndroidKeyStore issue i encountered recently is https://github.com/mozilla-mobile/fenix/issues/6813 .

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796432

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
