### ISSUE TITLE
Display a list of active Nimbus experiment

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#9464]
As part of https://github.com/mozilla-mobile/fenix/issues/17291, we want Dev/QA to be able to see a list of active Nimbus experiments. Selecting a Nimbus experiment will display a list of experimental branches (Control, Treatment 1, Treatment 2, etc) for a given experiment, and allow Dev/QA to manually opt into a different branch of their choice so they can test the different variation manually. We want as much of the code to live in AC since we expect this Nimbus tooling to be available beyond Fenix.

**Comment by SoftVision-CiprianMuresan** [comment]
@gabrielluong , if I understood this correctly, the fix here has not made it into the latest Nightly app and https://github.com/mozilla-mobile/fenix/issues/17291 still needs to land in order for us to see the list in action, right?

I've also looked at what experiments are on Prod and Stage in the nimbus-desktop-experiments collection and I haven't seen any mobile experiments listed there? Would it be possible to have at least 1 mobile experiment staged for when this is actionable by QA?

**Comment by gabrielluong** [comment]
> @gabrielluong , if I understood this correctly, the fix here has not made it into the latest Nightly app and [mozilla-mobile/fenix#17291](https://github.com/mozilla-mobile/fenix/issues/17291) still needs to land in order for us to see the list in action, right?
> 
> I've also looked at what experiments are on Prod and Stage in the nimbus-desktop-experiments collection and I haven't seen any mobile experiments listed there? Would it be possible to have at least 1 mobile experiment staged for when this is actionable by QA?

I still need to address review comments in the attached PR, and you are right that we need https://github.com/mozilla-mobile/fenix/issues/17291 to land before this can be tested. We will have to see what our options are when this lands and how we can add a mobile experiment.

**Comment by SoftVision-CiprianMuresan** [comment]
Thanks for the info! Could you please leave a mention for me when the issue has landed in both places?
