### ISSUE TITLE
[Telemetry] Telemetry for Open Saved Data in New Tab from AwesomeBar 

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/android-components#9470]
Emit facts for these in AC in the corresponding Suggestion Providers. For example, for bookmarks in the BookmarkStorageSuggestionProvider onSuggestionClicked lambda.

Related to https://github.com/mozilla-mobile/fenix/pull/16626

**Comment by rocketsroger** [comment]
For https://github.com/mozilla-mobile/fenix/issues/14866
