### ISSUE TITLE
Reconsider Observer Pattern for Top Sites

### ISSUE THREAD

**Issue by ekager** [mozilla-mobile/android-components#9477]
We use an `Observer` pattern for knowing when the Top Sites DB has been updated ([one example](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt#L50)) and this doesn't follow the rest of the `Flow`/`LiveData` patterns we use with Room DBs. 

Is there a good reason we are using these here? I looked around and it seems like this could be refactored to use a `Flow` return type which would then be `collected` by [`TopSitePresenter`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/presenter/DefaultTopSitesPresenter.kt) and would be cleaner/more consistent.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8070)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795417

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
