### ISSUE TITLE
Misleading name/behaviour for SessionManager's Observer.onAllSessionsRemoved

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#948]
`onAllSessionsRemoved` is fired when either `removeAll` or `removeSessions` were invoked. It doesn't fire when all sessions were removed from the manager (i.e. manager is in the empty state).

There's a docstring comment above that method describing this discrepancy, but it would be better if it was named something very explicit, like `onRemoveAllSessionsInvoked`.

ISTM that the state observers should be particularly interested in is the `empty` state, which this callback doesn't cover. With the addition of a default session in #933, the only way to reliably track "emptiness" would be to monitor `onSessionRemoved` in combination with `onAllSessionsRemoved`, and check for manager's size.

Should we just have a dedicated callback for the empty state? `onBecameEmpty` perhaps, or session-centric `onAllSessionsRemoved` given that we differentiate it from `onRemoveAllSessionsInvoked`.

**Comment by pocmo** [comment]
Eventually this will die with the migration to `browser-state`. :)
