### ISSUE TITLE
Support GV - INPUT_RESULT_IGNORED

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#9480]
GV recently added a new result of how the user touch was handled in https://bugzilla.mozilla.org/show_bug.cgi?id=1687430

This new value needs to have immediate support in the `browser-engine-gecko` otherwise we would crash the app.
As a quick fix, for the time being, based on the comment of the new value `Specifies that an input event was consumed by a PanZoomController internally and browsers should do nothing in response to the event.` I propose us mapping this to [`INPUT_RESULT_UNHANDLED`](https://github.com/mozilla-mobile/android-components/blob/master/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt#L147) that will have the app not react for this. eg: The toolbar will not be animated.

__
Based on hiro's feedback from https://bugzilla.mozilla.org/show_bug.cgi?id=1687430 we should simply drop the new return value.

**Comment by Mugurell** [comment]
After testing it a bit with the dynamic toolbar and seeing it for fling gestures, also based on the GV code I propose actually mapping this new value to [`INPUT_RESULT_HANDLED`](https://github.com/mozilla-mobile/android-components/blob/master/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt#L142) that would probably ensure we'll behave the same.

If the new event would be mapped to `INPUT_RESULT_UNHANDLED` then 
- a fling up gesture would show the toolbar everytime while 
- a swipe up gesture would keep the bottom toolbar hidden

**Comment by sflorean** [comment]
Verified as fixed on latest Nightly.
