### ISSUE TITLE
Write concept-fetch tests that cover code paths in the rusthttp component

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#9494]
Following the investigation from https://github.com/mozilla-mobile/fenix/issues/17585 and conversation and https://github.com/mozilla/application-services/issues/3829, we can avoid running into this bug at runtime by adding some tests that exercise our `concept-fetch` component API against the rust http component in app services.

This would help us know if we are changing an API that a-s, as a consumer, would need to be aware of.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8081)

**Comment by jonalmeida** [comment]
Taking this off the board for now. We might not need this for the moment since we might have https://github.com/mozilla/application-services/issues/3872 that fixes the root problem.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793146

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
