### ISSUE TITLE
module: Public Suffix List

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#95]
A bunch of our apps use the public suffix list to split domains into parts. It would be helpful to wrap the list into a component and add some code to use it.

**Comment by pocmo** [comment]
okhttp comes with a PublicSuffixDatabase:
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/publicsuffix/PublicSuffixDatabase.java

**Comment by ekager** [comment]
Focus could use this to fix this bug (no priority assigned)
https://bugzilla.mozilla.org/show_bug.cgi?id=1445758

**Comment by pocmo** [comment]
Related code in Fennec: https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/util/publicsuffix/PublicSuffix.java

In Fennec Gecko sends the base domain (public suffix + 1) to the app whenever the URL changes.

**Comment by pocmo** [comment]
Assigning myself: Weekend hacking project :)

**Comment by pocmo** [comment]
Code landed. Follow-up issues have the "publixsuffixlist" label.
