### ISSUE TITLE
Add integration test for PlacesHistoryStorage in DefaultTopSitesStorageTest

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#9501]
I really recommend doing away with the mocks, and just using the real storage implementation instead. It's a little bit more working setting things up, but really not much more - you'd need to actually insert history items and visits yourself to prep the storage.

For an example of how to set this up, see `browser-storage-sync` component. Specifically, you may need to copy-paste some bits from `build.gradle`:
```
// These dependencies are part of this module's public API.
    api(Dependencies.mozilla_places) {
        // Use our own version of the Glean dependency,
        // which might be different from the version declared by A-S.
        exclude group: 'org.mozilla.components', module: 'service-glean'
    }
...
testImplementation Dependencies.mozilla_places
testImplementation Dependencies.mozilla_full_megazord_forUnitTests
testImplementation Dependencies.mozilla_glean_forUnitTests
...
```

(it may work without the glean stuff, try that first; i don't recall the details right now)

The result should be a much more robust and useful test suite which exercises our whole stack! This will become a good integration test, instead of a "we're calling the right APIs" unit test. The latter is helpful, but the former actually gives you confidence that the system is working correctly.

_Originally posted by @grigoryk in https://github.com/mozilla-mobile/android-components/pull/8806#discussion_r526322094_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8085)

**Comment by grigoryk** [comment]
@gabrielluong could you push up a WIP of this? Curious which issues you ran into. Happy to pair up on this.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796261

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
