### ISSUE TITLE
W/OkHttpClient: A connection to https://incoming.telemetry.mozilla.org/ was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#952]
I found this in my logs:

> W/OkHttpClient: A connection to https://incoming.telemetry.mozilla.org/ was leaked. Did you forget to close a response body?

I'm guessing the platform's OkHttpClient noticed we forgot to close a response body. I filed this in components because it's the only thing I know of that connects to incoming.telemetry.mozilla.org; note I may be on an older components version.

**Comment by mcomella** [comment]
I think this came from a long-running background process.

**Comment by pocmo** [comment]
The legacy telemetry library was removed.
