### ISSUE TITLE
[Feature suggestion][telemetry] Enable to know how many users who opt-out from sending usage data

### ISSUE THREAD

**Issue by chianger** [mozilla-mobile/android-components#953]
We're considering this user story https://github.com/mozilla-tw/Rocket/issues/2487 in Firefox Rocket.
The intention is to know our users better. With this metric we would know if in some cases lots of users tend to opt-out from sending usage data.

Current limitation is that, whenever user opts out, the telemetry shuts down so that we're not able to know.

**Comment by chianger** [comment]
> Interesting. So you want to send a last telemetry ping when the user opts out? 
YES.
> Is there a specific ping you would want to use for that (core ping? and event?)
@cnevinc, you might know better than me.

**Comment by cnevinc** [comment]
We can use event ping for that.  Thanks!

**Comment by pocmo** [comment]
Some more questions:

* Would it be okay to upload already collected events/pings and then end with the "opt out" event?
* Should this use our normal re-try mechanism? If we can't send the opt-out event ping immediately: Should we continue to re-try sending it?
* Do you need to be notified via a callback that the opt-out event ping has been sent successfully?

**Comment by cnevinc** [comment]
I've created https://github.com/mozilla-tw/Rocket/pull/2787 for this

**Comment by pocmo** [comment]
Nice! This means (as discussed in Taipei) this won't need a change in the telemetry library, right? I'm going to close this issue here.
