### ISSUE TITLE
How to change cache storage location

### ISSUE THREAD

**Issue by duncanokeyo** [mozilla-mobile/android-components#9546]
I see that geckoview stores cache in /data/data/$packagename/cache  . How can i change this location to my custom location. And also can i use webextensions to read from the cache files?
![Screenshot from 2021-01-29 10-33-57](https://user-images.githubusercontent.com/6240014/106245678-eaee6e00-621d-11eb-8840-dd4071cfe59c.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8112)

**Comment by csadilek** [comment]
We don't provide API to change this location in A-C.
