### ISSUE TITLE
Use mockk as a mocking library

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#9547]
AC currently uses [`mockito-kotlin`](https://github.com/mockito/mockito-kotlin) as a mocking library.
Which works ok.
It is a familiar framework, a bridge between Kotlin and Mockito, built on top of Mockito's very stable codebase, sprinkled with some Kotlin optimizations.

On the other hand [`mockk`](https://mockk.io/) has a DSL built from the ground up based on Kotlin features with full support for mocking final classes / functions, Kotlin objects / extension functions and other cool features.
More - https://medium.com/@oleksiypylypenko/mockk-intentions-dbe378106a6b

Fenix uses `mockk` which I think made the life there easier.
I recently saw some situations on AC in which `mockk` would've probably helped while mockito couldn't.
Would be awesome to get more persons which used both to chime in with their experiences.

It's probably not feasible to refactor all tests to `mockk` but having the option to use it for future tests I think helps.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8113)

**Comment by pocmo** [comment]
>  I recently saw some situations on AC in which mockk would've probably helped while mockito couldn't.

Can you expand on this? What were you missing?

We also had some rough experiences with mockk in Fenix, I think. What's a bit frightening to me is that mockk is basically maintained by a single person.

**Comment by Mugurell** [comment]
> Can you expand on this? What were you missing?

Things not possible with `mockito-kotlin`
- mocking Kotlin objects / extension. This one is really the biggest thing missing. And for a Kotlin project it's an important part.
- similarly - mocking Java static classes and methods (from Android)

Other things like a better DSL with more lambdas and hierarchical mocking though they help with making the tests easier to read are not really a must but they're also nice.

**Comment by csadilek** [comment]
A while ago we decided not to do this, given issues with mockk that we had to work around.
