### ISSUE TITLE
Fix View.getSystemUiVisibility() View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR and View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR  deprecation in Android 11

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#9554]
File: [Window.kt](https://github.com/mozilla-mobile/android-components/blob/a8afd5789a66b06f746679c38757b9ff77970683/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/view/Window.kt)

Deprecation docs:
https://developer.android.com/reference/android/view/View#getSystemUiVisibility()
https://developer.android.com/reference/android/view/View#SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR
https://developer.android.com/reference/android/view/View#SYSTEM_UI_FLAG_LIGHT_STATUS_BAR

**Comment by mcarare** [comment]
We should wait until https://developer.android.com/jetpack/androidx/releases/core has a stable version for 1.5.0 so we can use `WindowInsetsControllerCompat`

**Comment by codrut-topliceanu** [comment]
🎉
