### ISSUE TITLE
Fix Bitmap.WEBP deprecation in Android 11

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#9555]
Files: 
[ThumbnailDiskCache.kt](https://github.com/mozilla-mobile/android-components/blob/35c99f4ba90532ec301df4148ac49be48b902004/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/utils/ThumbnailDiskCache.kt#L75)
[IconDiskCache.kt](https://github.com/mozilla-mobile/android-components/blob/dfeb54a78e6c0a39a917811d07a148416a4122f4/components/browser/icons/src/main/java/mozilla/components/browser/icons/utils/IconDiskCache.kt)

Deprecation docs: https://developer.android.com/reference/android/graphics/Bitmap.CompressFormat#WEBP

**Comment by mcarare** [comment]
Running tests for these changes https://github.com/mozilla-mobile/android-components/issues/9602.

**Comment by mcarare** [comment]
Closed in https://github.com/mozilla-mobile/android-components/pull/9676. Opened a follow-up for increasing test coverage: https://github.com/mozilla-mobile/android-components/issues/9684.

**Comment by Amejia481** [comment]
🎉
