### ISSUE TITLE
`java.lang.IllegalArgumentException` crash on nightly

### ISSUE THREAD

**Issue by fbertsch** [mozilla-mobile/android-components#9556]
Steps:
1. Go to www.reddit.com/r/videos
2. Click a video to expand it
3. Start playing the video
4. Click the small image of the video to close it

Expected behavior: closes the video
Actual behavior: Crash

Latest crash info (no associated crash report):
```
18edf71d-03ab-43a8-98a4-2d8cd2f52017
java.lang.IllegalArgumentException: Could not process image.
----
java.lang.IllegalArgumentException: Could not process image.
at org.mozilla.gecko.mozglue.GeckoLoader.nativeRun(Native Method)
at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:101)
```

**Comment by rocketsroger** [comment]
After some investigation this crash was fixed with https://github.com/mozilla-mobile/android-components/pull/9538.  I'll use this issue to add RuntimeException as GeckoView team suggested.  The crash itself should be fixed in the next Nightly.
