### ISSUE TITLE
There's no searchEngineManager parameter anymore

### ISSUE THREAD

**Issue by interfect** [mozilla-mobile/android-components#9577]
https://github.com/mozilla-mobile/android-components/blob/3ab790cec70eab083e77299ba52e14c659f75158/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt#L87

This line of this comment refers to a `searchEngineManager`, but instead the function (now?) takes a `defaultSearchEngineProvider`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8141)

**Comment by csadilek** [comment]
This was fixed by https://github.com/mozilla-mobile/android-components/pull/10045.
