### ISSUE TITLE
[Spike] Upgrade to Java 11

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#9579]
This issue was raised on upgrading to SDK 30 here: https://github.com/mozilla-mobile/android-components/pull/9568.

In order to run robolectric with SDK 30 we need to update the robolectric version but also to use Java 9. This will imply that all devs (and contributors) should download/ install Java 9 or higher because the embedded Java version in Android Studio(1.8) is not suitable.

The other option is to continue to use SDK 28 with robolectric and adjust the failing tests. I am not sure what other implications this would have.

Do we plan to upgrade to using Java 9 or is it too much trouble at the moment?

**Comment by mcarare** [comment]
@Amejia481 This is the issue related to upgrading to Java 9. 

For the https://github.com/mozilla-mobile/android-components/pull/9568 PR I have managed to fix unit tests so we can treat that issue separately from this one.

**Comment by Amejia481** [comment]
@pocmo if we update to Java 9, do have update CI severs?

**Comment by pocmo** [comment]
Yeah, that is likely, we currently use Java 8 in the CI images:
https://github.com/mozilla-mobile/android-components/blob/master/taskcluster/docker/base/Dockerfile#L35

I think I recall that something else will require Java 11+ soon? Was it the upcoming Gradle plugin version? May make sense to switch to 11+ immediately if possible.

**Comment by mcarare** [comment]
> I think I recall that something else will require Java 11+ soon? Was it the upcoming Gradle plugin version? May make sense to switch to 11+ immediately if possible.

https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html

**Comment by Amejia481** [comment]
> Yeah, that is likely, we currently use Java 8 in the CI images:
> https://github.com/mozilla-mobile/android-components/blob/master/taskcluster/docker/base/Dockerfile#L35
> 
> I think I recall that something else will require Java 11+ soon? Was it the upcoming Gradle plugin version? May make sense to switch to 11+ immediately if possible.


Yes agree, many of our decencies are requiring Java 11

**Comment by mcarare** [comment]
Also, installing Java 11 will be easier as no oracle account is needed to download JDK (can be done using brew on macOS, for example.)
So, should I rename the topic to "upgrade to Java 11"? 😄

**Comment by pocmo** [comment]
Currently trying upgrading in the Reference Browser repository. Follow along here:
https://github.com/mozilla-mobile/reference-browser/pull/1536
