### ISSUE TITLE
Dismiss collection menu popup when configuration changed

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#9582]
Currently when rotating a device while the collection menu popup is opened will leave popup in the wrong position.  The popup should be dismissed when device is rotated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8146)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1793141

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
