### ISSUE TITLE
support-ktx README points to wrong artifact

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#959]
docs:

> implementation "org.mozilla.components:support-ktx:{latest-version}"

But I needed to include:

> implementation "org.mozilla.components:ktx:$moz_components_version"

The question is:
- Is the artifact name correct?
- Do the docs need to be corrected?

**Comment by Amejia481** [comment]
It' looks like the new naming convention is only available on version 0.25.2
and on http://maven.mozilla.org
take a look here http://maven.mozilla.org/?prefix=maven2/org/mozilla/components

**Comment by pocmo** [comment]
See this mailing list posting:
https://lists.mozilla.org/pipermail/android-components/2018-October/000057.html

We already updated our READMEs to point to the new resources.
