### ISSUE TITLE
Remove microsoftonline.com from Domains list

### ISSUE THREAD

**Issue by cpeterso** [mozilla-mobile/android-components#960]
"microsoftonline.com" is in the list of global domains, but the server is (ironically) not online. Does A-C have a test to validate the domains in the Domains list?

http://www.microsoftonline.com/

https://github.com/mozilla-mobile/android-components/blob/master/components/browser/domains/src/main/assets/domains/global#L53

**Comment by pocmo** [comment]
> Does A-C have a test to validate the domains in the Domains list?

No, currently we do not have that. We'd somehow need to separate this into some kind of "monitoring" task - so that our test cases (and therefore our PRs, releases etc) do not depend on all the servers being up.

**Comment by pocmo** [comment]
Interestingly it's still top 45 of the Alexa list:
https://www.alexa.com/topsites

**Comment by pocmo** [comment]
It's also part of our localized lists, e.g.:
* https://github.com/mozilla-mobile/android-components/blob/210751ad2b02639cbfc729b0e96a0c2dc204e846/components/browser/domains/src/main/assets/domains/gb#L23
* https://github.com/mozilla-mobile/android-components/blob/210751ad2b02639cbfc729b0e96a0c2dc204e846/components/browser/domains/src/main/assets/domains/sg#L26
* https://github.com/mozilla-mobile/android-components/blob/210751ad2b02639cbfc729b0e96a0c2dc204e846/components/browser/domains/src/main/assets/domains/us#L18

**Comment by pocmo** [comment]
Maybe only sub domains are in used?

This one works:
* https://login.microsoftonline.com
