### ISSUE TITLE
Stop depending on JCenter

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9603]
JCenter is going away:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

The official date is May 1st, but the timeline mentions some maintenance beginning April 12th, so let's assume it's gone in April more or less and move on asap.

Some ideas:
- Depend on Maven Central only and see where we are at. A large chunk of our dependencies should be available there. Now there's a high chance more libraries migrate to it. I'm not so sure about older versions of libraries, let's see.
- Everything that isn't available in a reasonable place (we don't want to add random repositories) could be cached by us - either on maven.mozilla.org, or in repos directly too.

This will also affect release branches.

Apps:
- [ ] Fenix: https://github.com/mozilla-mobile/fenix/issues/17819
- [ ] Focus: https://github.com/mozilla-mobile/focus-android/issues/4694
- [ ] Reference Browser: https://github.com/mozilla-mobile/reference-browser/issues/1446

**Comment by pocmo** [comment]
Here's a nice search query from Christian which looks for JCentral usage in our repositories:
https://github.com/search?q=org%3Amozilla-mobile+jcenter&type=code

**Comment by pocmo** [comment]
Trying to build AC without jcenter, the first thing I get is:

```
> Could not resolve all files for configuration ':browser-domains:lintClassPath'.
   > Could not find org.jetbrains.trove4j:trove4j:20160824.
     Searched in the following locations:
       - https://maven.mozilla.org/maven2/org/jetbrains/trove4j/trove4j/20160824/trove4j-20160824.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :browser-domains > com.android.tools.lint:lint-gradle:27.0.1 > com.android.tools:sdk-common:27.0.1
         project :browser-domains > com.android.tools.lint:lint-gradle:27.0.1 > com.android.tools.external.com-intellij:intellij-core:27.0.1
```

**Comment by pocmo** [comment]
This dependency is coming indirectly from the Android Gradle plugin. Unfortunately the latest (stable) version doesn't help.

**Comment by owlishDeveloper** [comment]
@pocmo were you able to find any sort of workaround for trove4j?

**Comment by pocmo** [comment]
@owlishDeveloper I left some links in our build.gradle file: https://github.com/mozilla-mobile/android-components/blob/master/build.gradle#L73-L77 - Jetbrains seems to be interested in moving those artifacts to Maven Central and I am waiting for that. However I confirmed with RelEng that we can manually put those artifacts on maven.mozilla.org too, and that's what I am planning to prepare if this doesn't get resolved otherwise soon. Since filing the issue JFrog extended the deadline for JCenter to February 1st 2022 (read only), so at least it is not as urgent anymore (although they mention service brown-outs, which is scary too): https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.

**Comment by pocmo** [comment]
I just saw a taskcluster failure where we were unable to fetch a plugin from JCenter. It almost looks like JCenter is always a target for Gradle plugins even if not mentioned explicitly? Anyhow, this needs some investigation so that we do not fail building with missing plugins at some point:

> ] > Could not resolve all artifacts for configuration ':buildSrc:classpath'.
[task 2021-03-16T15:44:36.754Z]    > Could not resolve org.gradle.kotlin:plugins:1.3.6.
[task 2021-03-16T15:44:36.754Z]      Required by:
[task 2021-03-16T15:44:36.754Z]          project :buildSrc > org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:1.3.6
[task 2021-03-16T15:44:36.754Z]       > Could not resolve org.gradle.kotlin:plugins:1.3.6.
[task 2021-03-16T15:44:36.754Z]          > Could not get resource 'https://plugins.gradle.org/m2/org/gradle/kotlin/plugins/1.3.6/plugins-1.3.6.module'.
[task 2021-03-16T15:44:36.754Z]             > Could not GET 'https://jcenter.bintray.com/org/gradle/kotlin/plugins/1.3.6/plugins-1.3.6.module'

**Comment by pocmo** [comment]
@owlishDeveloper `trove4j` is now available on Maven Central and we were able to remove the workaround for it.
