### ISSUE TITLE
PR green, master red: What happened?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9605]
This PR was just merged:
https://github.com/mozilla-mobile/android-components/pull/9595

Everything is green. But it breaks on master:
https://firefox-ci-tc.services.mozilla.com/tasks/groups/U9JPYPJIQki9hFBE80VF2Q

In both cases it affected tests (one test failure and one test **build** failure). I assume we may not resolve test-only dependencies? 🤔 

CC @bhearsum

**Comment by pocmo** [comment]
In this case the dependency was only a `testImplementation` dependency. Maybe we do not follow those?

**Comment by bhearsum** [comment]
> In this case the dependency was only a `testImplementation` dependency. Maybe we do not follow those?

We definitely do not follow them, per https://github.com/mozilla-mobile/android-components/blob/99c19e992e68463126f8ef361bd95863439d2632/taskcluster/ac_taskgraph/loader/build_config.py#L30 - but it's easy to add if we need to.
