### ISSUE TITLE
Integrate GV's new InputResultDetail

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#9614]
Currently the `inputResult` from GeckoView about how a user touch was handed [is cached here](https://github.com/mozilla-mobile/android-components/blob/b2ee43400c5e6850fa8b950c9dc920d42440f3f8/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt#L121-L129) and then used for knowing how to animate the toolbars and the pull to refresh throbber.

https://bugzilla.mozilla.org/show_bug.cgi?id=1678505 will expose a separate `InputResultDetail` that will expand the low set of values `InputResult` offered allowing for a better UX of the dynamic toolbars and pull to refresh feature and so fixing a few of the bugs that we have in the process.

**Comment by gabrielluong** [comment]
@mcarare can this be closed now?

**Comment by mcarare** [comment]
@gabrielluong I think @Mugurell still has some investigations to do, regarding the use of the additional details the new API provides.

**Comment by Mugurell** [comment]
This is not yet started but planning to work on it this week after making a plan for the changes in https://github.com/mozilla-mobile/android-components/issues/9772.
