### ISSUE TITLE
Add (front-end) feature skeleton to support-base component

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#962]
At least our front-end feature components always have start() / stop() methods. They also have a presenter and an interactor that get started and stopped.

I am in a situation where I want to write a "feature" that like ToolbarFeature/ToolbarPresenter/ToolbarInteractor needs to track the currently selected session (See code in ToolbarPresenter). This already feels like a common use case and boilerplate code that I would like to avoid writing again.

**Comment by pocmo** [comment]
> common use case and boilerplate code

* Register to session manager
* On session selected update local session reference
* Subscribe to new session
* Unsubscribe from previous session
* Start/Stop the subscription if the app is in foreground/background
* If the selected Session itself updates *"do something"*

**Comment by pocmo** [comment]
@csadilek What do you think?

**Comment by csadilek** [comment]
@pocmo I like the idea! I think this particular one could live in `feature-session` as we have everything we need there and other features (e.g `feature-toolbar`) already depend on it. Are you thinking a re-usable class that we'd delegate to from other features? 

I am happy to help with this / or pick it up next if you're busy.

**Comment by pocmo** [comment]
> Are you thinking a re-usable class that we'd delegate to from other features?

Didn't have anything specific in mind yet. Mostly wanted to avoid the boileterplate and just write something like:

```Kotlin
class MyFeature: BaseSessionFeature() {
   // This observer magically follows the currently selected session
   val selectedSessionObserver: Session.Observer {
       // ... do something
   }
}
```

> I am happy to help with this / or pick it up next if you're busy.

Yeah, feel free to pick it up. :)
