### ISSUE TITLE
Migrate from Kotlin synthetics to Jetpack view binding

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9642]
Getting lots of warnings about `kotlin-android-extensions` being deprecated during a build. Migration guide: https://goo.gle/kotlin-android-extensions-deprecationkotlin-android-extensions

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8201)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795456

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
