### ISSUE TITLE
Local publication is failing

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9643]
```
> Task :browser-domains:publishAarPublicationToMavenLocal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':browser-domains:publishAarPublicationToMavenLocal'.
> Failed to publish publication 'aar' to repository 'mavenLocal'
   > Invalid publication 'aar': multiple artifacts with the identical extension and classifier ('aar', 'null').
```

**Comment by grigoryk** [comment]
Seems like all components are failing, I just happen to hit `browser-domains` first.

**Comment by mcarare** [comment]
This seems to fail after the upgrade of `kotlin-gradle-plugin` from 1.4.21 to 1.4.30 (Along with `stdlib)`. I will take a look at the release notes to see what changed.

**Comment by mcarare** [comment]
I do not see why this is should not be working anymore, maybe it has to do with the `digital.wup.android-maven-publish` plugin we use that is deprecated: https://github.com/wupdigital/android-maven-publish.

I haven't used [Maven Publish plugin](https://developer.android.com/studio/build/maven-publish-plugin) so I cannot test if this solves the issue, but maybe @pocmo has more expertise in this and can test the plugin change.

**Comment by pocmo** [comment]
Fixed in https://github.com/mozilla-mobile/android-components/issues/9640

**Comment by pocmo** [comment]
We reverted the Kotlin version upgrade yesterday. I'll open a PR to migrate to `maven-publish` and then hopefully we can try again. :)
