### ISSUE TITLE
Include androidTestImplementation when looking at dependency tree for build optimization

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#9666]
This is what we did for `testImplementation`:
https://github.com/mozilla-mobile/android-components/pull/9662

`androidTestImplementation` is a bit more complicated since not all modules support it.

bhearsum mentioned some ideas [here](https://github.com/mozilla-mobile/android-components/pull/9662#pullrequestreview-586614774):

> A couple of quick ideas here:
1) An allow or deny list to track components that do or do not support this.
2) Always run this command, but don't break on failure -- either include or don't include (I don't know which makes more sense here) the component if the command fails. This would obviously be less than ideal if the command fails for a reason other than `androidTestImplementation` not existing, but it may be better than the current state of things.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8216)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795415

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
