### ISSUE TITLE
Expose api for supporting HTTPs only mode

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#9682]
As support for HTTPs only mode has landed on [GV](https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/doc-files/CHANGELOG#v87) we could start exposing the API from ac. For more details see https://bugzilla.mozilla.org/show_bug.cgi?id=1672478

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8221)

**Comment by Amejia481** [comment]
Related https://github.com/mozilla-mobile/fenix/issues/16952

**Comment by opusforlife2** [comment]
Is there any timeline for this? HTTPS-only is pretty much a core feature of Firefox now. I enable it for everyone I can, but the majority of people use mobiles to access the internet.

**Comment by csadilek** [comment]
This was completed. 🎉
