### ISSUE TITLE
[Bug] Fullscreen PWAs are put in PIP mode when pressing home

From Fenix - https://github.com/mozilla-mobile/fenix/issues/17967


### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#9698]
From https://github.com/mozilla-mobile/fenix/issues/17967

Currently we're only checking [if the page is in fullscreen](https://github.com/mozilla-mobile/android-components/blob/b266ac3d16e15cabc969cfe33c9cf965f557e257/components/feature/session/src/main/java/mozilla/components/feature/session/PictureInPictureFeature.kt#L46)
What Chrome, Fennec and other browsers do is checking if there is media playing in fullscreen.
We should do the same.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8227)

**Comment by CharlesAdam** [comment]
Can you assign me to this issue?

**Comment by Mugurell** [comment]
@CharlesAdam For easily testing the AC patch in Fenix I suggest adding a line with the relative/absolut path to the AC project in Fenix's `local.properties` as described here - https://github.com/mozilla-mobile/fenix#auto-publication-workflow-for-android-components-and-application-services

**Comment by CharlesAdam** [comment]
Woah I was trying to figure out how I would test it, thanks for the suggestion

**Comment by CharlesAdam** [comment]
#9701

**Comment by CharlesAdam** [comment]
Ok, sent the MR: #9701

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795412

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
