### ISSUE TITLE
Provide option to change EngineView visibility (especially hide)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-components#970]
When a WebView is visible in the view hierarchy, even if it's obscured, it is focusable by screen readers who can read its content. In my app, I get into this situation and it's undesirable: the home screen covers the WebView but the WebView will continue to be focusable by the screen readers. I tried to disable this functionality via `View.setImportantForAccessibility` but WebView doesn't appear to obey this when it's changed dynamically. The only way I could prevent the WebView from being focused by screen readers was to hide it from the view hierarchy (`View.GONE`).

afaict, `EngineView` doesn't currently support an option to change its visibility: it'd be helpful for my use case if we added one.

**Comment by pocmo** [comment]
`EngineView` being an interface doesn't expose methods from `View`. We added the little helper `asView()` to it that will cast it to `View` for your.

Is `engineView.asView().setVisibility(View.GONE)` something that could work for you?

**Comment by mcomella** [comment]
Yeah, that should work – thanks.

`EngineView` being called `*View` is misleading then – I wonder if we can
improve the naming.

**Comment by pocmo** [comment]
> `EngineView` being called `*View` is misleading then – I wonder if we can improve the naming.

fwiw it's a always `View`. But `EngineView` being an interface I have no way of declaring that (There's no `View` interface in Android):
https://github.com/mozilla-mobile/android-components/blob/master/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt#L12
