### ISSUE TITLE
Consider add new domain lists to a-c

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/android-components#971]
A-C already have domains and autocomplete.
But there's no resource for the top domains for different countries
Would it be nice if we can contribute our new list where other apps can use?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8238)

**Comment by pocmo** [comment]
Yes, that's definitely possible. Some time ago we added some more countries for Focus.

Note that we have been following a strict process to pick and sanitize the domains. We start with the Alexa top list for the country and then follow this process:
https://firefox-source-docs.mozilla.org/mobile/android/fennec/defaultdomains.html

**Comment by pocmo** [comment]
@cnevinc Do you have a specific list of countries in mind? Rocket's target countries?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796330

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
