### ISSUE TITLE
AutoPushFeature: Use Dispatchers.Cached for dedicated coroutine dispatcher

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#9734]
[Sebastian suggested](https://github.com/mozilla-mobile/android-components/issues/9424#issuecomment-782162053) using the [`Dispatchers.Cached`](https://github.com/mozilla-mobile/android-components/blob/master/components/support/base/src/main/java/mozilla/components/support/base/coroutines/Dispatchers.kt#L17) coroutine dispatcher for similar situations needed by `AutoPushFeature`.

We should test this out to see if the following flows work:
 - Initialization
 - New token received
 - Verification flow
 - Push messages received immediately after
 - Receiving push messages after the 60 sec idle when the thread is terminated.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8254)

**Comment by cpeterso** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796423

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
