### ISSUE TITLE
Streaming downloadable media does not have media notification

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#9748]
For the site  https://file-examples.com/index.php/sample-video-files/.  Some file types such as MP4 is streamed but does not have a media notification.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8263)

**Comment by rocketsroger** [comment]
Another URL test case https://www.learningcontainer.com/mp4-sample-video-files-download/

**Comment by rocketsroger** [comment]
Related https://bugzilla.mozilla.org/show_bug.cgi?id=1694192

**Comment by sv-ohorvath** [comment]
The same issue with the automated UI tests in MediaNotificationTest https://github.com/mozilla-mobile/fenix/issues/15754

**Comment by lobontiumira** [comment]
Reproducible on Beta 91.0.0-beta.5 with Sony Xperia Z5 Premium (Android 7.1.1).

**Comment by sv-ohorvath** [comment]
I can still reproduce this issue sometimes.
I've also found that muted videos don't have a notification even after un-muting and this is reproducible 100%. 
For example, the first video on https://pauljadam.com/demos/autoplay-loop-muted-controls.html

**Comment by plwt** [comment]
User feedback: https://support.mozilla.org/en-US/questions/1385592

**Comment by jens1o** [comment]
We also received user feedback via Google Play on this topic, most notably YouTube audio controls seemed to stop appearing.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796359

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
