### ISSUE TITLE
Test crash reporter foreground service with Android 12

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#9749]
There are some changes in Android 12 for foreground service.  We should test against Android 12 to confirm that crash reporting still works correctly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8264)

**Comment by Amejia481** [comment]
I think we should bump the priority on this https://github.com/mozilla-mobile/fenix/issues/25608

**Comment by rocketsroger** [comment]
Confirmed that crash reporting process works as expected in Android 12 emulator.  This is also confirmed by Sentry crash reporting that there are fatal crash reports from Android 12 users after target SDK is updated to 31+.

**Comment by rocketsroger** [comment]
No work is needed.  Closing
