### ISSUE TITLE
Investigate feasibility and use cases for linking Sentry and Socorro crash reports

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#9750]
Investigate into if linking Sentry and Socorro crash reports can be helpful.  If this is something that we want, investigate if it is feasible.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8266)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792901

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
