### ISSUE TITLE
Add media notification advance controls

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#9763]
Currently media notification while streaming video only have pause and play.  Investigate into adding advance media control in the media notification.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8277)

**Comment by sheikh-azharuddin** [comment]
Also the notification have a thumbnail which is missing in Firefox notification. The notification looks more richer in chromium browser 

Firefox
![Screenshot_20210224-090810839 (1)](https://user-images.githubusercontent.com/58127841/108944188-49253a00-7680-11eb-868c-fa1944fe2d0d.jpg)

Brave/chrome
![Screenshot_20210224-090839923 (1)](https://user-images.githubusercontent.com/58127841/108944204-517d7500-7680-11eb-929f-2776069f6a4b.jpg)

**Comment by hakkikaancaliskan** [comment]
@sheikh-azharuddin there is an issue for that https://github.com/mozilla-mobile/fenix/issues/17670

**Comment by sheikh-azharuddin** [comment]
I guess this might be due to firefox not utilising the apis and controls exposed by the os..for example if you play any song in gaana app on Android 9 you won't get the seek bar whereas if you use the gaana app in android 10 you will get the seek bar in the media notification

Somehow I feel firefox is not leveraging the controls and APIs exposed by the os but rather using universal one..

**Comment by seranpion** [comment]
Hello. I would like add my voice to this issue.


Also: The title & artist of the persistent notification is the title & URL of the page rather than the values provided in the `MediaMetadata` object.
Which is strange, because the arkwork provided is displayed.
Should I open another issue for that?

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796358

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
