### ISSUE TITLE
[Spike] Investigate the changes needed to support GVs InputResultDetail

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#9772]
GV will soon offer from https://bugzilla.mozilla.org/show_bug.cgi?id=1678505 more complete APIs for informing clients about how user's touch was handled.

The new `InputResultDetail` does not immediately replace the current `InputResult` to give us time to adapt.
After the new APIs are available let's make a plan about how to use them and what changes will be needed in the app.

The actual refactoring of both the toolbar and pull to refresh features is to follow in https://github.com/mozilla-mobile/android-components/issues/9614

**Comment by Mugurell** [comment]
I hoped we could leverage `inputResultDetail` to have the toolbar and the pull to refresh functionality driven entirely from GeckoView.
But it seems like it won't be possible atm and we still need our [BrowserGestureDetector](https://github.com/mozilla-mobile/android-components/blob/b266ac3d16e15cabc969cfe33c9cf965f557e257/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserGestureDetector.kt) and [VerticalSwipeRefreshLayout](https://github.com/mozilla-mobile/android-components/blob/b266ac3d16e15cabc969cfe33c9cf965f557e257/components/ui/widgets/src/main/java/mozilla/components/ui/widgets/VerticalSwipeRefreshLayout.kt) so we'll still need to also keep intercepting the touch events.

If using just the `inputResultDetail` values we'll get into issues that since now been fixed - scrolling horizontally will scroll the toolbar, zoom gestures will also, and others similar.

https://user-images.githubusercontent.com/11428869/111774997-dbec7980-88b8-11eb-880b-93383b18bc2e.mp4

But we can use the new details as another check for whether to animate the toolbar or the pull to refresh throbber and I saw that for example https://github.com/mozilla-mobile/fenix/issues/16576 would now be fixed.

**Comment by Mugurell** [comment]
As to what changes are needed to support `InputResultDetail` I propose:
- deprecating the existing [InpuResult enum](https://github.com/mozilla-mobile/android-components/blob/master/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt#L137) and [getInputResult()](https://github.com/mozilla-mobile/android-components/blob/master/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt#L94)
- replace them with a new `InputResultDetail` class and `getInputResultDetails()`. A new class to encapsulate the logic for extracting the current data from the `InputResult#scrollableDirections` and `InputResult#overscrollDirections`using bitwise operations.
- have this changes ride the release trains.

After the implementation is done in Nightly we can recheck the issues from https://github.com/mozilla-mobile/fenix/projects/54#card-54078554

**Comment by gabrielluong** [comment]
@Mugurell should we close this issue if it's done on the kanban board? If there's follow up work, I would propose we break it down and file new issues for them.

**Comment by Mugurell** [comment]
Sure. Thank you!
