### ISSUE TITLE
Custom download manager

### ISSUE THREAD

**Issue by UltraBurstXD** [mozilla-mobile/android-components#9795]
Hi,
I'm wondering if there are some plans to add custom download manager for mobile devices. Well, first because like desktop, we could "keep" (temporarily in phone's storage) really monstrous chunks of data and save some time or someone's data plan if (common) internet related issues occurs. And with tweaked "resume" function continue from last point... Second, there are already few mobile browsers doing something similar, and I think it's really appreciated by many users... :)

**Comment by hakkikaancaliskan** [comment]
I think you should have been opened this issue in fenix repo
https://github.com/mozilla-mobile/fenix

**Comment by UltraBurstXD** [comment]
Oh... Sorry for inconvenience...
