### ISSUE TITLE
Add pressed state for unselected toggle buttons

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#980]
> When you press on a toggle button, there's no animation to indicate that you've pressed it. There is no effect right now.

**Comment by Amejia481** [comment]
@pocmo Is this the expected behavior?
[Now](https://drive.google.com/file/d/1uyLT9QfxB_kAiMzxu0hVflrqq7_onmjv/view)
[Before](https://drive.google.com/file/d/1sZjC3bDktQzPhzm_fWH-XYtyYKiKVJzE/view)

**Comment by pocmo** [comment]
Closing this as this does not require a change in the component.
