### ISSUE TITLE
Support users denying permissions twice on DownloadsFeature

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#9812]
Related issue https://github.com/mozilla-mobile/fenix/issues/17650

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8321)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1792931

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
