### ISSUE TITLE
Add credit card provider models

### ISSUE THREAD

**Issue by gabrielluong** [mozilla-mobile/android-components#9813]
We should add data class for the various credit card providers (AMEX, MA, V, etc) with rules about their card number lengths, regexp to validate their card numbers, and anything that is needed.

We allocated a E3 estimate to buffer time to look up Desktop implementation of these credit card provider validations.

**Comment by mcarare** [comment]
@gabrielluong Some questions:
In what module should this model live? 
Do we have icon resources from UX for provider icons or should we use SVGs used in desktop Firefox? (Not all provider have a SVG, some just a png)
