### ISSUE TITLE
Do no require write storage permission to downloading files on devices with Android 11 and above

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#9830]
In devices with Android 11 and above we are using the [scoped storage api](https://github.com/mozilla-mobile/android-components/blob/d017f023c9c622f7c590129df4b78580c5f9e325/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt#L835) and we are only writing to the public download directory that doesn't require any additional permission.  We could waive the permission requirements for these devices as it's not needed.

**Comment by czlucius** [comment]
May I work on this issue?

**Comment by Amejia481** [comment]
Please, do so :) 
If you need any help just let me know.

Mostly we have to skip [the checks for permissions](https://github.com/mozilla-mobile/android-components/blob/b360a589a0db05813093c71df9367c49a4a87c79/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt#L166) when we are on Android 11 and above.

**Comment by czlucius** [comment]
The write storage permission is completely not required(not used at all in the downloads component)? Are there other areas that use this write permission even in >= API 30? If not, I can add `maxSdkVersion` to the permission in the Android Manifest.

**Comment by czlucius** [comment]
![image](https://user-images.githubusercontent.com/58442255/126750831-b2b34a2f-c5f4-473c-b24f-4543d8c1875a.png)
What do I do for the PR checklist? How do I run the test/what tests do I need to create?

Thank you.

**Comment by czlucius** [comment]
I have made a PR for this issue: #10686

**Comment by Amejia481** [comment]
> `maxSdkVersion`

I'll have to double check, but I think It won't be a problem as for now we are only writing to the public downloads directory, but maybe when we allow to change the download directory could cause issues https://github.com/mozilla-mobile/fenix/issues/5764.

**Comment by Amejia481** [comment]
> What do I do for the PR checklist?

The checklist is just for reference of what all PRs should have, when you complete an you just have to check it.
 

> How do I run the test/what tests do I need to create?

I would focus on creating tests for the module that you changed (`feature-downloads`), making sure we don't require the permission on devices with Android 11.

For running test for `feature-downloads` you can use:
`./gradlew :feature-downloads:testDebug `

You can find more information [here](https://developer.android.com/studio/test/command-line). This [documentation](https://mozac.org/contributing/testing-components-inside-app) could help you to have a better idea of how to work with Android Components locally.  On CI, they should run on every PR you can see each task on the "**Checks**" Tab on GitHub.

**Comment by czlucius** [comment]
> > `maxSdkVersion`
> 
> I'll have to double check, but I think It won't be a problem as for now we are only writing to the public downloads directory, but maybe when we allow to change the download directory could cause issues [mozilla-mobile/fenix#5764](https://github.com/mozilla-mobile/fenix/issues/5764).

Ok. 
But I think the permission is deprecated on newer Android versions (>=11) and no longer grants any permissions.
https://developer.android.com/about/versions/11/privacy/storage#permissions-target-11

If there is a need to choose the download directory, the System Access Framework needs to be used to pick the directory

**Comment by Amejia481** [comment]
👍🏽

**Comment by czlucius** [comment]
I keep on receiving this error while building:

```Gradle sync failed: Unrecognized Android Studio (or Android Support plugin for IntelliJ IDEA) version '202.7660.26.42.7486908', please retry with version 2020.3.1 or newer. ```

**Comment by hakkikaancaliskan** [comment]
@czlucius team is currently working on Jetpack Compose, maybe you should try with Android Studio canary version 🤷

**Comment by czlucius** [comment]
Noted. Thanks.

**Comment by Amejia481** [comment]
Sorry about that, as @hakkikaancaliskan mentioned we trying to integrate Jetpack Compose and it requires 

- Java 11 (when invoking Gradle on the command line)
- [Android Studio - Arctic Fox [RC 1]](https://developer.android.com/studio/preview)(comes with Java 11 bundled)
- Everything else should be downloaded by Gradle as needed

**Comment by czlucius** [comment]
Hi
I've added some tests to the PR, is there anything else I need to do?
Thanks.
