### ISSUE TITLE
Remove media meta data bitmap workaround

### ISSUE THREAD

**Issue by rocketsroger** [mozilla-mobile/android-components#9860]
This is to remove the workaround for https://github.com/mozilla-mobile/android-components/issues/9859.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8356)

**Comment by rocketsroger** [comment]
Once an investigation / fix is done in https://bugzilla.mozilla.org/show_bug.cgi?id=1697255.  Remove this workaround if possible.

**Comment by gabrielluong** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1796357

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
