### ISSUE TITLE
Remove authorizeOAuthCode from FirefoxAccount

### ISSUE THREAD

**Issue by grigoryk** [mozilla-mobile/android-components#9863]
We're not using this yet, so we can just hide this bit of API from our consumers for now.

(this facilitates authorizing secondary clients, e.g. Fenix authorizing a hypothetical newMozApp, which we don't yet do).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8358)

**Comment by jonalmeida** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794201

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
