### ISSUE TITLE
Implement new menu designs for Extension menu name and position.

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#9873]
The new menu designs have the Extensions (Add-ons) placed inside the menu items, no longer at the top or at the bottom.

This would mean removing `appendExtensionSubMenuAtStart` and maybe using a mechanism similar to the one used to insert extensions in the main menu.

The name is also to be changed: https://github.com/mozilla-mobile/fenix/issues/17799#issuecomment-790873134

**Comment by cadeyrn** [comment]
@mcarare Firefox for desktop will revert the naming change and continue to use "Add-ons" instead of "Extensions" [1]. Should Firefox für Android do the same to be consistent?

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1698931

**Comment by sflorean** [comment]
Closing this and we will test the upcoming issues related to this functionality.
