### ISSUE TITLE
Create feature-downloads (Non UI)

### ISSUE THREAD

**Issue by Amejia481** [mozilla-mobile/android-components#988]
Breaking in small parts this issue #459

- [ ] Subscribe to downloads in the currently selected session (I assume we do not need to subscribe to it in all Sessions?)

- [ ] Consume Download objects and pass the data to Androids Download Manager

- [ ] Call back into the app to notify if a download is done

**Comment by pocmo** [comment]
@csadilek This is probably another use case for #962 (always tracking the current session) :)
