### ISSUE TITLE
Perma build-feature-downloads failure because of spellcheck warning for Norwegian Bokmal

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#9887]
This is a failure of the task which checks the 'downloads' feature in android-components.

Log: https://treeherder.mozilla.org/logviewer?job_id=333155814&repo=android-components
```
[task 2021-03-14T00:32:06.116Z]   Errors found:
[task 2021-03-14T00:32:06.116Z]   
[task 2021-03-14T00:32:06.116Z]   /builds/worker/checkouts/src/components/feature/downloads/src/main/res/values-nb-rNO/strings.xml:46: Error: "media" is a common misspelling; did you mean "medier" ? [Typos]
[task 2021-03-14T00:32:06.116Z]       <string name="mozac_feature_downloads_write_external_storage_permissions_needed_message">Tilgang til filer og media er nødvendig for å laste ned filer. Gå til Android-innstillinger, trykk på tillatelser og trykk på tillat.</string>
```

@Delphine , can you reach out to Havar if [the string](https://pontoon.mozilla.org/nb-NO/all-projects/all-resources/?search=mozac_feature_downloads_write_external_storage_permissions_needed_message&string=220775) needs to be changed or the spellchecker silence?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8374)

**Comment by Delphine** [comment]
Hi, I updated the string in Pontoon while I wait for the localizer to get back to me. Thanks

**Comment by st3fan** [comment]
@Archaeopteryx can you point me to something that explains how this linter works? I'm curious what tool is run and where the rules come from.

**Comment by st3fan** [comment]
I've updated the String Sync PR with the change that Delphine made in Pontoon. To shorten the turnaround time.

Addressed in https://github.com/mozilla-mobile/android-components/pull/9891 which is now green.

**Comment by Archaeopteryx** [comment]
The spell checker: https://android.googlesource.com/platform/tools/base/+/studio-master-dev/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/TypoDetector.java
This could be turned off like this: https://developer.android.com/studio/write/lint#gradle

**Comment by jonalmeida** [comment]
The fix has been merged, so let's close this now. I don't think we're going to disable the linter since it seems to be useful for catching real bugs like this.
