### ISSUE TITLE
Move variant-specific fact in GeckoEngineSession.loadUrl outside of src

### ISSUE THREAD

**Issue by jonalmeida** [mozilla-mobile/android-components#9908]
In [`GeckoEngineSession.loadUrl`](https://github.com/mozilla-mobile/android-components/blob/6e5735dbacdb8b3e111feb21b91276197b6d6a99/components/browser/engine-gecko-nightly/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt#L175), we emit a fact for internal performance metrics/testing that is specific to each variant by the `Component.kt` [generated class](https://github.com/mozilla-mobile/android-components/blob/8d02e5944fe0f0b5edc49308515b3954474be192/components/support/base/build.gradle#L78-L102).

During [merge day](https://mozac.org/contributing/merge-day) however, we overwrite the original contents of release and beta as we promote the `src` files. This ends up moving `Component.BROWSER_ENGINE_GECKO_BETA` from beta to release and `Component.BROWSER_ENGINE_GECKO_NIGHTLY` from nightly to beta during these events.

We can do better!

@pocmo suggested that we should find a better way to reference "this component" which would work for all components in the future.
 
This issue was born from the discussion here: https://github.com/mozilla-mobile/android-components/pull/9900#discussion_r595072030

**Comment by pocmo** [comment]
> @pocmo suggested that we should find a better way to reference "this component" which would work for all components in the future.

Since we do not copy over `build.gradle` one idea would be to create a buildconfig flag referencing the current `Component` item and then using that in code.

**Comment by pocmo** [comment]
This will be solved with #10070 because after that we only have one component. :)
