### ISSUE TITLE
Qr Fragment: Increase test coverage

### ISSUE THREAD

**Issue by mcarare** [mozilla-mobile/android-components#9917]
Testing some methods in QR fragment is difficult, but we should try to add some more tests to increase test coverage.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8393)

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1795159

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
