### ISSUE TITLE
[Bug] Browser menus can be too narrow

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#9922]
Seen while testing https://github.com/mozilla-mobile/fenix/issues/17772
With [newCoreMenuItems](https://github.com/mozilla-mobile/fenix/blob/1f96887f96a8c627ae9f8468df76c8f0eace6dbf/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt#L76) the menu may be too narrow.

Currently seems to only reproduce only when the toolbar is set on top:

https://user-images.githubusercontent.com/11428869/111120385-f13d6d00-8573-11eb-886b-24ecd096b148.mp4

**Comment by Mugurell** [comment]
This is a very interesting issue of the [`DynamicWidthRecyclerView`](https://github.com/mozilla-mobile/android-components/blob/86cd6f201f1bd75d3a1a8f4418192dbfc08f9ada/components/browser/menu/src/main/java/mozilla/components/browser/menu/view/DynamicWidthRecyclerView.kt) that allows the menu to have a dynamic width (with some safe bounds) happening when there are many items to be displayed.

The RecyclerView is a bit too dynamic, in that it will always have the width of the maximum **displayed** children. This means that depending on the parent and LayoutParams, with enough items to scroll through it could potentially yo-yo in width depending in what's displayed at that exact moment.

I think this is a bit unexpected and what we'd want is to have it have the width of the largest item.

Saw that in the first `onMeasure` the width will be reported correctly, because all children are accounted, but then in the first layout phase [`detachAndScrapAttachedViews`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:recyclerview/recyclerview/src/main/java/androidx/recyclerview/widget/RecyclerView.java;l=9489;drc=dbdba1b15d56a8d30b63785d3758897de15b1018) will be used to limit how many items will actually be laid out depending on if they fit the screen. And this is done by actually removing the child views so if we try to measure the list again, there are fewer children to measure and we might get different dimensions.

To accommodate our needs seems like we should just cache the first reported width and only use that afterwards.

**Comment by abodea** [comment]
Verified as **fixed** on the latest **Nightly and Debug** builds with **Google Pixel 4 XL (11)** for more details please check the following:

| Device  | Build | Reproducible? |
| ------------- | ------------- |  :-------------: |
| Google Pixel 4 XL 11  | **Nightly** 4/7/21  | **No**  |
| Google Pixel 4 XL 11  | **Nightly** 4/6/21  | **No**  |
| Google Pixel 4 XL 11  | **Debug** 4/7/21 (latest Master)  | **No**  |
| Google Pixel 4 XL 11  | **Debug** 3/30/21  | **Yes**  |

Note that the latest mentioned try on the table is with a version of Master before the merges.
