### ISSUE TITLE
Add a sticky footer RecyclerView

### ISSUE THREAD

**Issue by Mugurell** [mozilla-mobile/android-components#9932]
Saw the need for this on Fenix - https://github.com/mozilla-mobile/fenix/issues/17772 which intends to use a collapsed menu with not all items shown on the screen. The list of items may be so big that even if the menu fits the screen not all items would be shown.

https://user-images.githubusercontent.com/11428869/111622784-425a9480-87f2-11eb-92b0-07b75e3a01af.mp4

&nbsp;
From that ticket I understand there is a need to always show the list of navigation buttons
<img src="https://user-images.githubusercontent.com/11428869/111621044-2950e400-87f0-11eb-8797-1aa7eec8f2fe.png" width="33%" />
so we need a RecyclerView with sticky footers support and a property added to each BrowserMenuItem to indicate that that item should be a sticky footer.

**Comment by Mugurell** [comment]
Asking UX if we should use a sticky header/footer for all browser menus.
(for example when showing the menu while in landscape, do we want to keep that navigation buttons row fixed in place (at the top/bottom of the menu) and only scroll the rest of the items?)

**Comment by Mugurell** [comment]
Asking @topotropic and also @channingcarter how important showing the navigation buttons bar is and if we want it displayed in all cases. (with rest of the menu items scrollable but this always fixed in place and visible).

**Comment by eliserichards** [comment]
Confirmed with @topotropic and @channingcarter that this should definitely be done now 👍
