### ISSUE TITLE
Perma uitabcounter failure because string mozac_tab_counter_open_tab_tray_plural uses '%1$' instead of '%1$s' for Bulgarian

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla-mobile/android-components#9939]
cc @Delphine 

Log: https://firefoxci.taskcluster-artifacts.net/Kmj2H19uQiuV5YgV0-L3vg/0/public/logs/live_backing.log

https://pontoon.mozilla.org/bg/android-l10n/all-resources/?search=mozac_tab_counter_open_tab_tray_plural&string=217741 should use  `%1$s` instead of `%1$`.

**Comment by Delphine** [comment]
FIxed in Pontoon.
