### ISSUE TITLE
Remove unneeded libraryOveride from Nimbus.kt

### ISSUE THREAD

**Issue by dmose** [mozilla-mobile/android-components#9969]
Once the next version of application-services lands, [this libraryOverride](https://github.com/mozilla-mobile/android-components/blob/0bc7edf4a84a437c3819bd11f212d47998ba02e3/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/Nimbus.kt#L240-L245) should no longer be needed, as mozilla/application-services#3963 will have made the default be correct.

cc @rfk @travis79 @jhugman

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8419)

**Comment by csadilek** [comment]
This override (in Nimbus.kt) now lives in application services. Sound like it can be removed, but should be filed and done there.
