### ISSUE TITLE
Telemetry probe to measure alive tabs

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/android-components#9997]
Individual issue to track [new telemetry related to page persistence metrics](https://github.com/mozilla-mobile/android-components/issues/9624).

We would like a new telemetry probe to measure alive tabs when the app is moved from to the foreground from the background.  We would like to measure:

-  number of alive tabs when
    - going to background
    - going back to foreground and how long we've been backgrounded (so we can plot tab retention with 1,5,10,30 minutes)

This metrics could help us track how memory/performance affects retaining tabs/getting killed and how often our users get their tabs reloaded. Also it can help us know how many tabs are actually alive in users devices (e.g. when thinking about memory/performance tradeoffs based on number of tabs)

**Comment by pocmo** [comment]
I wrote a patch that gathers the following data when the app goes to foreground/background:

```
----------------------
Background:
      Active tabs:  8
      Crashed tabs: 0
      Total tabs:   8
----------------------
Foreground:
      Active tabs:  4
      Crashed tabs: 0
      Total tabs:   8
----------------------
Time in background: 80288 ms
Active tab diff:    -4
Crashed tab diff:   0
Total tab diff:     0
```

@dblohm7 Does this data cover what you need here?

I am not really sure yet how to map this to metrics in Glean. My guess is that we could record this as a single event (when the app comes to the foreground) and attach the data as extras. But I am not sure if this will be the best way for analyzing this data.

@fluffyemily Do we have someone who can help us with getting this data analyzed / plotted and who may have an idea how to best model it for that? I assume that GLAM won't be sufficient and we may need some custom dashboard on Redash?

**Comment by dblohm7** [comment]
@pocmo LGTM!

As for the analysis bit, I would suggest asking on #glam in slack, they've been helpful to me in the past.

**Comment by pocmo** [comment]
After asking in `#data-help`, using an event with extras seems to be the right choice.

**Comment by pocmo** [comment]
Probe landed in Fenix and should be in the next Nightly build.

**Comment by dblohm7** [comment]
\o/ Thanks @pocmo !
