### ISSUE TITLE
Telemetry probe to measure the number of times we get killed in the background

### ISSUE THREAD

**Issue by fluffyemily** [mozilla-mobile/android-components#9999]
Individual issue to track [new telemetry related to page persistence metrics](https://github.com/mozilla-mobile/android-components/issues/9624).

- number of times we get killed in the background using
-     onKill (for content process) and
-     getHistoricalProcessExitReasons for main process https://developer.android.com/reference/kotlin/android/app/ActivityManager#gethistoricalprocessexitreasons (API30 only I think)

This metrics could help us track how memory/performance affects retaining tabs/getting killed and how often our users get their tabs reloaded. Also it can help us know how many tabs are actually alive in users devices (e.g. when thinking about memory/performance tradeoffs based on number of tabs)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8445)

**Comment by dblohm7** [comment]
The first bullet (for the number of times background content processes have been killed) was already landed as part of #17864, so this issue only needs to deal with the `getHistoricalProcessExitReasons` bit.

**Comment by csadilek** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1794924

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
